### ISSUE TITLE
Comment out most of docs/environment

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#1011]
Sometimes people wanting to test labwc throw the example environment file into their config dir and wonder why their keyboard layout is suddenly changed. Same for the breeze cursor theme, it might not be available on the given system.

Maybe we should simply comment those settings out so they still serve documentation purposes but do not actually change the keyboard layout.

**Comment by johanmalm** [comment]
Good idea.

Suggest commenting out all.

XDG_CURRENT_DESKTOP is set in session.c anyway.
