### ISSUE TITLE
Feature Request: OSD showing position when moving, size when resizing a window

### ISSUE THREAD

**Issue by Gusar321** [labwc/labwc#1013]
Openbox has this. Didn't occur to me how much I look at it when placing/resizing windows until I was checking out labwc for a potential switch to wayland. So I would really welcome seeing this feature in labwc too.

**Comment by Consolatis** [comment]
Personally I've never been an excessive Openbox user, are there some screenshots of how that looks?

**Comment by johanmalm** [comment]
Yes, I know what that looks like. It's a tiny OSD with `1024x768` (or whatever) at the center of the window. It changes with resize.

**Comment by Consolatis** [comment]
> Yes, I know what that looks like. It's a tiny OSD with `1024x768` (or whatever) at the center of the window. It changes with resize.

I see, is the OSD hiding again based on some timeout after the last change or this is only for interactive resize with the mouse, e.g. rendered on start of the resize until releasing the mouse button?

If its only with the mouse it should be relatively trivial to implement in `src/interactive.c`. The timeout based variant that also triggers on keybind resizes would involve some more changes I guess.

Personally I don't mind the feature as long as it is either disabled by default or at least can be disabled via config.

**Comment by Consolatis** [comment]
Thanks for the screenshots :)

@johanmalm is this in scope of labwc?
And if yes, do you want to implement it? Otherwise I could give it a try, sounds fun to implement.

**Comment by johanmalm** [comment]
Go for it. Agree it would be a nice feature to have.

http://openbox.org/wiki/Help:Configuration#Resize_.28and_move.29

labwc-scope 2.6.1
Have changed it to a B

**Comment by Consolatis** [comment]
- #1021

Testing / feedback welcome.

**Comment by Gusar321** [comment]
That was fast. Thank you for working on this! It works. I agree thought that bold font would look better.

About current limitations, supporting popupPosition is not needed IMO, but size hints would be nice to have, if it's not too difficult to implement

**Comment by Consolatis** [comment]
Have implemented size hints for X11 applications but for wayland native ones its might not be possible (but I'd have to look further into it).

As far as I remember (!) there are no size hints in the wayland world, the way the functionality works instead is by the compositor telling the client to resize to width `504` and the client in turn committing to `500`. So we only know that the client has some preferences as how it dimensions should look like but we don't know if that size hint would be `5`, `10`, `20`, `25`, `50`, `100`, `125`, `250` or `500`. We could obviously try to track many resize attempts during an interactive resize and then try reduce the set of possible options but that really gets too complex in regard to the benefit it would provide.

**Comment by Consolatis** [comment]
> Do native wayland terminals, like foot, even implement resizing by character?

`foot` doesn't seem to implement it, `havoc` does, as well as `mate-terminal` in wayland native mode (libvte based AFAIR).

**Comment by johanmalm** [comment]
xcfe4-terminal even does its own 80x25 (or whatever) OSD.

**Comment by johanmalm** [comment]
Agree with not trying to do anything size-hint related for wayland on the server side

**Comment by Consolatis** [comment]
Implemented by
- #1021

Feel free to comment if there is anything missing or there are issue with the feature.
