### ISSUE TITLE
wayland build: menu.xml emacs command fails, works in terminal

### ISSUE THREAD

**Issue by CaptainBloodz** [labwc/labwc#1017]
labwc -v
labwc 0.6.4-20-g7a19184, i.e. 2022-08-07

wayland only build here.

command  :
`<item label="Reconfigure"><action name="Execute" command="emacs ~/.config/labwc/autostart ~/.config/labwc/environment ~/.config/labwc/ ~/.config/labwc/menu.xml ~/.config/labwc/rc.xml" /></item>`

returns in console :
emacs : Could not open file:  /dev/tty

launches fine from terminal, e.g. foot. (TUI mode), as well as X compatible build (GUI mode).

**Comment by CaptainBloodz** [comment]
Nice workaround...
Initial concern menu.xml compatibility regarding xwayland status.
Will check from other pure wayland desktop installed here :
Should it return the same, I'd  consider the issue out of scope here.

**Comment by Consolatis** [comment]
All commands executed from labwc keybinds or menu entries run without a controlling terminal, so all commands that should run in a terminal need to be started explicitly via one. In the case of the emacs GUI mode I am not sure why it doesn't work, I don't really have any experience with that. Maybe it requires a specific command line argument to start in GUI mode rather than in terminal mode.

I'll assume the issue is fixed, feel free to comment if that is not the case or if you have further questions.

**Comment by CaptainBloodz** [comment]
> All commands executed from labwc keybinds or menu entries run without a controlling terminal, so all commands that should run in a terminal need to be started explicitly via one. In the case of the emacs GUI mode I am not sure why it doesn't work, I don't really have any experience with that. Maybe it requires a specific command line argument to start in GUI mode rather than in terminal mode.
> 
> I'll assume the issue is fixed, feel free to comment if that is not the case or if you have further questions.

I've never meant emacs GUI should work in pure wayland... I think it doesn't actually.

**Comment by CaptainBloodz** [comment]
Nice heads-up.
Building here on gentoo which has a big warning against gtk option:

[ebuild   R   *] app-editors/emacs-30.0.9999:30-vcs::gentoo  USE="-X -Xaw3d -acl alsa (-aqua) -athena cairo dbus dynamic-loading -games gfile gif gmp gpm gsettings -gtk gui gzip-el harfbuzz imagemagick inotify jit jpeg json kerberos lcms libxml2 -livecd m17n-lib mailutils -motif png (-selinux) sound -source sqlite ssl svg -systemd threads tiff toolkit-scroll-bars tree-sitter -valgrind webp -wide-int -xattr xft xpm xwidgets zlib"

Maybe this ignored gtk build option should be reconsidered?
