### ISSUE TITLE
Sticky Windows

### ISSUE THREAD

**Issue by surmeier** [labwc/labwc#1032]
In most tiling compositors, there is a concept of sticky windows. "sticky" is used in bspwm and sway for app interfaces that always appear above the rest. This functionality is also useful in the floating context. 

PiP works partially on labwc, but the windows does not remain in the foreground. I would like to have an arbitrary app, say a clock app, appear above the rest of the other app windows until it is closed. The snapping behavior like on MacOS or Windows would be a nice to have, but not strictly necessary. 

I understand that implementing this functionality may be more complicated on wayland than xorg, so if it is outside the scope of this project than I understand.

**Comment by Consolatis** [comment]
That should be possible with the `ToggleAlwaysOnTop` [action](https://labwc.github.io/labwc-actions.5.html#entry_action_name=togglealwaysontop).

It currently serves a double duty role as "being on top of all windows" and "being visible on all workspaces", that might change in the future.

**Comment by surmeier** [comment]
Ok, thanks. This works, although a manual step.  

Sometimes I'm getting confusing behavior when doing the action on PiP windows, sometimes the video is treated as a separate window to the browser, but sometimes instead of toggling the video window the browser is toggled on top. This is a much more niche issue than the one I stated originally, so I'll close the issue.
