### ISSUE TITLE
Send command from console to labwc

### ISSUE THREAD

**Issue by Bezzumnbiu** [labwc/labwc#1035]
Hello,
Can't figure out how to trigger labwc actions from outside
Now I want to make buttons for the waybar to go to different workspaces, but I can’t figure out how to make a call from labwc itself.
For example, in sway, I can move to another workspace with the swaymsg workspace number 2 command, but does labwc have a similar solution?

**Comment by heroin-moose** [comment]
You can’t, that is the explicit design choice. All communications with the compositor must happen through the established protocols.

**Comment by stefonarch** [comment]
Except` labwc --<option>` there's only an indirect way, using shortcuts and `wtype` or similar tools.
I've found a solution for who likes buttons to switch: https://github.com/stefonarch/LXQt-Wayland-files/blob/main/lxqt-panel.md#desktop-cyclerswitcher

**Comment by Bezzumnbiu** [comment]
I assumed that I would just have to emulate keystrokes. Thanks for the info
