### ISSUE TITLE
Feature Request: Option to hide SSD borders / disable resize borders on maximized windows

### ISSUE THREAD

**Issue by gurrgur** [labwc/labwc#1044]
Currently maximized windows are resizable at the screen corners. The problem with this is that at the screen edges other UI elements such as the SSD buttons or scroll bars are not clickable.

I usually flick the mouse to the top right corner to close a maximized window, so this gets in my way often. Likewise, I often flick the mouse towards the right edge of the screen to grab the scrollbar. This is standard behaviour e.g. on kwin/plasma or windows and its a must have feature in my book.
 
I am aware that using a theme without borders yields the desired behaviour, however borders on unmaximized windows are essential to create contrast between windows that share a similar backgroud color.

**Comment by Consolatis** [comment]
This sounds sensible.

I am not sure if we'd need some setting for this behavior (and what the default should be) as I don't know what the usual expectation of other users would be.

Did some initial work in
- #1045

Feel free to test if you are fine with compiling labwc yourself. When using a single screen the PR should allow for the `flick-mouse-to-corner` and `flick-mouse-to-edge` use-cases.

**Comment by gurrgur** [comment]
Thanks for the quick response. I tested the WIP branch and it works great for both usecases!

IMO this behaviour should be the default behaviour. Having close button and scroll bar more easily accessible far outweights the ability to resize maximized windows via mouse. I mean, we already have the restore button for this. Also if someone really wanted to resize a maximized window, it would be possible to use either a key combination or key-down + mouse movement.

Personally I wouldn't add a setting for this, but in the end it probably depends on whether there is demand for specific functionality.

To get some more context I quickly checked how some other projects are doing it:

- **kwin** uses plugins for drawing SSDs. It is up to the decoration plugin to implement this / expose a setting. The default decoration breeze has a setting for enabling borders on maximized windows and also allows resizing. Resizing from the windows buttons is also possible, however when not moving the mouse, the buttons still respond (despite the mouse showing as a resize cursor).
- **mutter**: Unsurprisingly, no user exposed setting to be found here. The default is no border / resize borders on ssd decorated windows (though it might be possible for a user to add borders through gtk css overrides).
- **xfwm4**: There is a setting that allows drawing borders for maximized windows. It is disabled by default. When enabled, windows can be resized from the edges, but not from where the ssd window buttons are.
- **openbox**: Some time ago I verified that openbox behaves exactly like labwc does currently on master.

**Comment by Consolatis** [comment]
- #1045

merged into the master branch. We decided to unconditionally remove the borders and un-round the rounded corners on maximize. If this is an issue for somebody feel free to comment and we'll additionally add a new (default enabled) config option which allows to disable the behavior.

@gurrgur thanks for bringing this up and also clearly stating `flick-to-edge` and `flick-to-corner` not working. That moved the issue from a plain design (looks better) to an UX issue.

**Comment by iamcheyan** [comment]
Hi — reviving the thread from the merge comment on #1045:

> We decided to unconditionally remove the borders and un-round the rounded corners on maximize. If this is an issue for somebody feel free to comment and we'll additionally add a new (default enabled) config option which allows to disable the behavior.

As of 0.20.1 that option still doesn't exist, and I turned out to be one of the people it matters to: my theme relies on the active border color for contrast between maximized windows on a shared background.

Would the maintainers be open to a PR adding a theme option like `keepBorderOnMaximize` (default off — current behavior unchanged, border shown on maximize when enabled)? Happy to implement it.

**Comment by johanmalm** [comment]
@iamcheyan Happy to discuss. Please could you open a feature-request under discussions instead.
