### ISSUE TITLE
Menus, titlebar text, and rounded corners are blurred when output scale is >1

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#105]
For some reason labwc does not scale the output on my laptop. I have 3000x2000 14" display and I see the following:

labwc: 
![scaling-bad](https://user-images.githubusercontent.com/15263497/140153145-13c056db-0297-4bc3-9f68-0815b33d7a01.png)

sway:
![scaling-good](https://user-images.githubusercontent.com/15263497/140153576-cf2fd265-1a84-44dc-b7aa-fb362df88ecb.png)

**Comment by johanmalm** [comment]
You need to set the scale.
Could you try installing kanshi and set ‘scale 2’

https://github.com/johanmalm/labwc/blob/master/docs/autostart

Is it automatic in sway or do you set the scale somewhere?

**Comment by heroin-moose** [comment]
Here, kanshi with scaling factor 2:

![scaling-x2](https://user-images.githubusercontent.com/15263497/140182083-34f6bcef-a49d-48dd-89f3-50583be1fedf.png)

I'm sure if the difference is visible, but compare this to the one from sway.

**Comment by johanmalm** [comment]
Okay. Yeah, does seem right.
Not sure why. Will have to investigate or seek help.
Could you confirm if you get the same with GTK and Qt apps.
Have you set scaling with gsettings?
Is it just font the looks blurred or other parts of GUI apps? What about Client Side Decoration of GTK apps?

**Comment by heroin-moose** [comment]
It seems that GTK3 and Qt5 apps scale properly. However, with alacritty and other non-toolkit apps the fonts are blurry.

**Comment by ARDiDo** [comment]
[This branch may fix the upscaled appearance.](https://github.com/ARDiDo/labwc/tree/hidpi_scale_filter) However, I haven't been able to test this since I don't have a HiDPI screen.

**Comment by droc12345** [comment]
I don't use alacritty, but why are you trying to use display scaling instead of alacritty's font size in the config file.

**Comment by heroin-moose** [comment]
Because that's how HiDPI works. The application settings stay the same and the scaling factor is applied by the GUI toolkit. For example, consider the situation where you have two output with different scaling.

**Comment by droc12345** [comment]
I was just playing with my 4k/1080p setup and there's some weirdness going on with what labwc "thinks" the scaling is and what it actually is. I use kanshi to set different outputs, and it does apply scaling to the 1080p monitor. But labwc thinks the scaling is not there, and wdisplays (wlroots app) picks up that value from labwc and it reports as no scaling even though it's being applied. I turned on wayland debugging and it shows the correct scaling, so it's being applied, but it's being lost (or never picked up correctly) by labwc. Any scaling and associated font rendering is at a level below labwc/wlroots.

Having said the above, with scaling applied, there's no blurring on the 1080p monitor, at least with various apps I tried (I use foot as a term emulator).

The main difference in looks, between various toolkits or apps that display fonts, is how they're being rendered by the app or toolkit.

**Comment by droc12345** [comment]
johanmalm, I don't think you're handling multiple outputs the right way.
On further playing, if I have both monitors on, and the position set the way I want in kanshi, it's being overridden by labwc, the position for each monitor is being ignored, and the scaling factor is being set to one (but only for info from labwc) whereas the actual monitor is showing scaling properly. In other words what labwc tells me about the monitors, doesn't match to the reality, at least for the scaling factor. 

If you need any further info, let me know.

**Comment by ARDiDo** [comment]
Thanks for bringing wdisplays up @droc12345, I hadn't heard about it before. While I was playing around with wdisplays, I found out that when changing the scale through it, the window wont update its textures for the new scale. wdisplays is a gtk3 based application, and would correctly scale textures before the scale was updated while it was open. This leads me to believe that toolkit based applications check the scale when they start, but wait for some event afterwards. Alacritty likely doesn't bother checking the scale at startup, and chooses to wait for the event instead.

**Comment by ARDiDo** [comment]
I think I've figured it out. When a view enters a monitor, we need to send an enter event, like we do with layer surfaces, using wlr_surface_send_enter(), as well as send a leave event when the view leaves a monitor. I tested this a little bit using wdisplays and foot, and the textures updated when the scale was changed. I'll get to work on implementing this fully.

**Comment by ARDiDo** [comment]
Small update- I've mostly fixed the OSD, titlebar text, and I'm working on menu text.

I still need to test what happens when we have multiple monitors with different scaling methods.

**Comment by johanmalm** [comment]
Thanks @ARDiDo 
I’ve written a patch for supporting menu separators, but need to refactor the menu.c code somewhat. I’ll hold off on this, as I suspect it’ll get difficult to rebase otherwise. No rush though 😄

**Comment by ARDiDo** [comment]
I've fixed the menu text, but unfortunately it requires that the user hits the reconfigure button to update the textures. Right now, I'd rather leave fixing that until after we've applied both of our patches.

I've only had a short opportunity to test a multi-monitor setup. It might take me another week or two to fix the bugs I've found.

**Comment by Consolatis** [comment]
Should be fixed with latest master.
