### ISSUE TITLE
Stuck dragging window with CSD feat. waybar

### ISSUE THREAD

**Issue by DynamoFox** [labwc/labwc#1053]
How to reproduce:
 - Set "layer": "top" in Waybar configuration file and ensure the panel is located at the top of the screen
 - Launch waybar with that configuration
 - Pick a window with client-side decorations (tested: Firefox, Thunerbird, adwaita-1-demo)
 - Drag it to the top of the screen as if you were to maximize it
 - Observe the window did not maximize and is still being dragged even if the left mouse button has been released

This doesn't occur with windows using SSD.

Note that In Firefox&Thunderbird specific cases left clicking the decoration to get rid of the dragging will not work.
Left clicking on adwaita-1-demo will instead stop the drag.

Reproduced as well by Consolatis on IRC.

**Comment by Consolatis** [comment]
Reproduced with wl_example_panel.py in "top" layer + exclusive zone + Firefox with CSD.

**Comment by DynamoFox** [comment]
I can confirm that moving the first condition beneath the other two in the snippet above is enough to solve the issue.

Now the Firefox window correctly maximizes and isn't dragged by the pointer anymore.

**Comment by Consolatis** [comment]
Pushed the PR:
- #1056

Feel free to give it a test ride, in my local tests it fixes the issue and I didn't spot any side effects.

**Comment by DynamoFox** [comment]
I've have rebuilt labwc with that PR and I can confirm that it's working as intended without manifesting any other annoyance so far. Thank you!
