### ISSUE TITLE
Focus on menus and keyboard navigation

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1058]
If _root-menu_ or _client-menu_ are opened by shortcut mouse action is required to get focus and select items, "Focus" action has no effect:
```

    <keybind key="A-C-Space">
      <action name="ShowMenu">
        <menu>client-menu</menu>
      </action>
      <action name="Focus" />
    </keybind>

```

Related: it's not possible to navigate  menus by keyboard arrows.

**Comment by stefonarch** [comment]
When clicking the titlebar the menu opens at cursor position, so it's easy to navigate. But if triggered by shortcut it opens at the top left corner of the window and the cursor can be far away. 

Keyboard input and focus are mostly synonyms  here actually.

**Comment by Consolatis** [comment]
- #1059

Feel free to give it a test ride.

**Comment by stefonarch** [comment]
Already driving, thanks, works like a charm :)
Didn't test yet submenus though as I use a very limited menu only.

**Comment by stefonarch** [comment]
I'm I right and it's not possible to create more menus to call by shortcuts?

**Comment by Consolatis** [comment]
> Am I right and it's not possible to create more menus to call by shortcuts?

No, that should actually work. The example rc.xml even does it to use different menus for left and right click on the desktop.
