### ISSUE TITLE
Limited modifiers compared to X?

### ISSUE THREAD

**Issue by alaricljs** [labwc/labwc#1061]
I've been waiting for an Openbox-adjacent to arrive for Wayland so I could be at least somewhat motivated to give the new thing a try.  Unfortunately I tripped up right at the beginning.

I have 5 modifiers in common use under Openbox - Shift, Ctrl, Alt, Super, Meta.  There's still 2 more I could add in, but only 1 cool name (Hyper) and I haven't quite found a good reason to.  I really do not want to lose a modifier though.

Is the modifier limit intrinsic to Wayland or is it something that labwc could handle?

**Comment by Consolatis** [comment]
> Is the modifier limit intrinsic to Wayland or is it something that labwc could handle?

I am not 100% sure but I think its a labwc limitation. Wayland applications (and labwc itself) use libxkb for the keymaps so having more modifiers should be possible. Its not exactly my area of expertise though. You could give `xev` (xwayland) and `wev` (wayland native) a try to debug the modifiers that applications receive.

These are the modifiers that wlroots (which we depend on) supports:
```
 WLR_MODIFIER_SHIFT = 1 << 0,
 WLR_MODIFIER_CAPS = 1 << 1,
 WLR_MODIFIER_CTRL = 1 << 2,
 WLR_MODIFIER_ALT = 1 << 3,
 WLR_MODIFIER_MOD2 = 1 << 4,
 WLR_MODIFIER_MOD3 = 1 << 5,
 WLR_MODIFIER_LOGO = 1 << 6,
 WLR_MODIFIER_MOD5 = 1 << 7
```

Labwc however only supports Shift, Control, Alt, and W / logo for keybinds.

**Comment by jonhiggs** [comment]
I'm also short a modifier. I would love to see support for mod3 and/or mod5.

**Comment by Consolatis** [comment]
Just had a look at [Openbox](http://openbox.org/wiki/Help:Bindings#Syntax) and they seem to support `M` and `H` for Meta (`Mod5` apparently) / Hyper (`Mod3` apparently). Additionally they support `Mod[1-5]` so `Mod1-f` would be the same as `A-f` and `Mod4-f` the same as `W-f`.

**Comment by Consolatis** [comment]
`M` and `H` should now work in latest master. Feel free to comment if there are any issues with it.

**Comment by jonhiggs** [comment]
xkb allows you to assign Mod[1-5] to any key you choose (see modifier_map). I think it's standard for Mod1 to be applied to Alt_L and Alt_R but you can put the modifier on whatever key(s) you choose.

In my case I'd like to be able to put mod1 on Alt_R and mod3 on Alt_L and give them differnet actions. I'm currently unable to do that because Alt_L and Alt_R get the same actions as each other and I cannot assign actions to Mod1 or Mod3.

I'm coming from Fluxbox where [the modifiers](https://linux.die.net/man/5/fluxbox-keys) are addressed by their name (mod[1-5]), rather than the key (alt).

I'm no expert on this, I've just noticed some things while trying to do unusual things.

**Comment by jonhiggs** [comment]
I've got a key reporting Hyper_L with mod3 according to wev, but using an action like this doesn't work.

```
    <keybind key="H-j">
      <action name="Execute" command="wtype -k Down" />
    </keybind>
```

**Comment by Consolatis** [comment]
Can you paste the output of `xmodmap -pm`?
I think I actually forgot to add `Hyper_L` and `Hyper_R` to our internal list of modifiers, same for `Meta_L` and `Meta_R`.

If you want to test you can change `src/keyboard.c` line 136 and add them so it reads
```c
/* Right hand Alt key for Mod5 */
|| sym == XKB_KEY_Mode_switch
|| sym == XKB_KEY_ISO_Level3_Shift
|| sym == XKB_KEY_Hyper_L
|| sym == XKB_KEY_Hyper_R
|| sym == XKB_KEY_Meta_L
|| sym == XKB_KEY_Meta_R
/* Prevents storing layout change notifier in pressed */
|| sym == XKB_KEY_ISO_Next_Group;
```

We should try to get rid of that hardcoded list and instead get all modifier syms from xkb to prevent these issues.

**Comment by jonhiggs** [comment]
> Can you paste the output of `xmodmap -pm`?

I must be missing some dependency because I'm getting the error `modmap:  unable to open display ''`.

> If you want to test you can change src/keyboard.c line 136

That worked. Thank you very much.

**Comment by Consolatis** [comment]
> That worked. 

Thank you for testing!
I'll cook up a PR in the next days which adds the 4 additional modifiers.

How did you manage to have a key emit `Hyper_L` and `Mod3`, I assume you had to modify your xkb layout file?

**Comment by jonhiggs** [comment]
> How did you manage to have a key emit Hyper_L and Mod3, I assume you had to modify your xkb layout file?

Yeah, I made a derivative version of `swap_lalt_lwin` in `/usr/share/X11/xkb/altwin` and added a new reference to the rules.

```
// Swap the left Alt with Super and Super with Hyper.
partial modifier_keys
xkb_symbols "swap_lalt_lwin_lhyper" {
    key <LALT> {[  Super_L  ], type[group1] = "ONE_LEVEL" };
    key <LWIN> {[  Hyper_L ]};
    modifier_map Mod4 { <LALT> };
    modifier_map Mod3 { <LWIN> };
};
```

It's a bit nasty. I'll have to work out how to do it in ~/.config/xkb if that's possible.

**Comment by Consolatis** [comment]
Should be fixed in latest master.
