### ISSUE TITLE
Add libinput Tap drag lock feature

### ISSUE THREAD

**Issue by burein-ita** [labwc/labwc#1064]
Using a49e12e11238771ab9b7195cfa5f4ce03ec10742
Arch-Linux

Right now is not possible to configure libinput `Tap drag lock` feature from rc.xml.
This makes using labwc with a touch-pad mildly annoying.

According to the [libinput docs:](https://wayland.freedesktop.org/libinput/doc/latest/tapping.html#tap-and-drag)
>When enabled, libinput >will ignore a finger up event during a drag process, provided the finger is set down again within >a implementation-specific timeout.

**Comment by Consolatis** [comment]
I didn't look into the specific config option but I start to wonder if we should try to implement "all the settings" for libinput rather than adding new ones bit by bit when requested.

**Comment by tokyo4j** [comment]
I was working on this from before, so I made a PR for reference.

**Comment by droc12345** [comment]
Touchpad settings you might want look at

disable while typing    
natural scroll  
scroll factor   
middle button emulation 
tap button map  
clickfinger behavior    
tap-to-click    
drag lock       
tap-and-drag
along with acell profile and sensitivity

**Comment by alaricljs** [comment]
https://wayland.freedesktop.org/libinput/doc/latest/scrolling.html

- scroll_method
- scroll_button

Please
