### ISSUE TITLE
Waybar dragging broken by DND changes ("wrong source for drag request")

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#1070]
Under recent versions of labwc, it is no longer possible to drag and drop windows in the "wlr/taskbar" module of [Waybar](https://github.com/Alexays/Waybar).

There appear to be two somewhat separate regressions here.

To reproduce these regressions, run labwc with Waybar and open two windows. Press the left mouse button on the entry in the taskbar for one of these and drag it onto the entry for the other, then release the mouse button. You should see a drag icon and a subsequent reordering of the two taskbar items. Then do the same motion again, this time dragging the second program's taskbar entry (this is the *exact* same motion as the entries have switched places). The same thing should happen.

As of commit 3bd441c, the first drag worked, but the second drag attempt causes a bunch of warnings to be printed stating "[../src/dnd.c:109] wrong source for drag request".

As of commit a89bcc3, no drag is started even on the first button press and the taskbar entries do not reorder. On the first drag attempt the same "wrong source for drag request" warnings are seen.

CC @johanmalm.

**Comment by johanmalm** [comment]
Thanks for reporting. Will investigate.

**Comment by johanmalm** [comment]
This was fixed by the focus tracking changes shortly after `0.6.5`
