### ISSUE TITLE
Remember and restore keyboard layout per window

### ISSUE THREAD

**Issue by kyak** [labwc/labwc#1076]
Users that have multiple keyboard layouts often prefer that the current keyboard layout is remembered and restored per window. `labwc` only allows setting keyboard layout globally for all windows.

The scenario is usually the following. The user types something in a window (say, chat) using one keyboard layout, then switches to another window (say, browser or IDE) and changes keyboard layout there. Then the user switches back to his chat window and continues typing in whatever keyboard layout was active in that window.

In X, there are a bunch of daemon-like programs (i've used many of them throughout the years) that allow for this functionality.

In wayland, it seems like compositor's job. Please refer to https://github.com/swaywm/sway/issues/2361 for some discussion.

Please consider implementing this functionality in `labwc`.

**Comment by stefonarch** [comment]
I agree,  kind of must-have for many, it's present as a [plugin](https://github.com/AlexJakeGreen/wayfire-kbdd-plugin) in wayfire too.

**Comment by johanmalm** [comment]
Happy to merge.
Does anyone fancy drafting a patch?

**Comment by Consolatis** [comment]
Working on it with the help of @kyak via IRC.

**Comment by Consolatis** [comment]
- #1077

Testing appreciated, especially if LED status indicators likes `grp_led:scroll` still works as expected when switching focus to a window with a different layout. I've only tested it nested with a hacked wlroots that allows toggling the layout via the wayland backend.

**Comment by xxhh1112** [comment]
qq
