### ISSUE TITLE
Support idle-inhibit protocol

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#108]
```
~$ swayidle
Display doesn't support idle protocol
```

Am I missing something? Has anyone got `swayidle` working?

**Comment by johanmalm** [comment]
Protocol not yet implemented :smile:

**Comment by 01micko** [comment]
> Protocol not yet implemented smile

Yeah thought so, but in **6. Integrate** _swaylock_ can only be run manually. Not that useful :smile_cat:

**Comment by 01micko** [comment]
Excellent, working here. Thanks @ARDiDo and @johanmalm :+1:
