### ISSUE TITLE
Window switcher styling not working under some conditions

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1098]
With condition=unknown,

All lines with "window-switcher" in `themerc` have no effect here:
```
osd.bg.color: #ffffff
osd.border.color: #3294a8
osd.border.width: 3
osd.label.text.color: #484848
osd.window‐switcher.width: 700
osd.window‐switcher.padding: 4
osd.window‐switcher.item.padding.x: 3
osd.window‐switcher.item.padding.y: 3
osd.window‐switcher.item.active.border.width: 2
```
I noticed it first on my laptop, while on the PC it was working until some day ago. 
It works with default or or no config files. Using `themerrc-override` doesn't make any difference.

**Comment by stefonarch** [comment]
After lots of test and exclusion it _seems_ that the `-d `option is part of the issue.

With identical config folders using
`exec labwc -d -C $XDG_CONFIG_HOME/lxqt-wayland/labwc -s lxqt-session` the issue is present, while with `exec labwc  -s lxqt-session`  `the file `themerc-override` works as expected, but in `themerc`  settings have no effect still.

**Comment by Consolatis** [comment]
> All lines with "window-switcher" in `.themerc` have no effect here:
> It works with default or or no config files. Using `themerrc.override` doesn't make any difference.

Just to ensure it was a typo while posting the report: it is `themerc-override`, e.g. `-` rather than `.` and `$theme_dir/openbox-3/themerc` rather than `.themerc`.

> exec labwc -d -C $XDG_CONFIG_HOME/lxqt-wayland/labwc -s lxqt-session the issue is present, while with exec labwc  -s lxqt-session the file themerc-override works as expected, but in themerc settings have no effect still.

Didn't look into it yet but the `-C` is also a difference here.

**Comment by johanmalm** [comment]
I'll have a look post `0.6.5` bump. Suspect we don't handle `$XDG_CONFIG_HOME` properly.

**Comment by stefonarch** [comment]
Fixed the typos, and it's non -d but -C (took -d for directory...).
It doesn't look that using `$XDG_CONFIG_HOME` or using full path makes a difference, it looks like just another path doesn't work here. But I like to test also it on the other installation. too many factors around.

**Comment by stefonarch** [comment]
Tested on the labwc, basically the same findings:
*  with custom folder (labwc -d -C $XDG_CONFIG_HOME/lxqt-wayland/labwc) no way to style the window switcher
* with default folder (no path specified) switcher can be styled `exclusively` by `themerc-override`

**Comment by Consolatis** [comment]
Using `gdb --args build_master/labwc -V -s foot -C ~/.config/labwc/test` correctly uses changes from `themerc-override` for me.

Do you get something like
`00:00:00.744 [../src/theme.c:524] read theme-override /home/test/.config/labwc/test/themerc-override`
or
`00:00:00.756 [../src/theme.c:520] no theme override '/home/test/.config/labwc/test/themerc-override'`
in your logs?

Maybe the issue here is that `$XDG_CONFIG_HOME` isn't set on wherever you start labwc?

**Comment by stefonarch** [comment]
The path is set by the start script which executes at the end labwc and everything is working in every config files for ages except those 5 lines as I found out only some day ago. The binary is for sure ok.

Did you test the lines inside a `themerc` ? 

Here I've 2 lines in themerc-override, the second works:

```
osd.window‐switcher.width: 1200
osd.bg.color: #ffffff
```
```

 [../src/theme.c:524] read theme-override /home/stef/.config/lxqt-wayland/labwc//themerc-override
 [../src/theme.c:500] read theme /usr/share/themes/Vent-dark/openbox-3/themerc
```

**Comment by Consolatis** [comment]
> Did you test the lines inside a `themerc` ?

Yes:
- `osd.window-switcher.width: 200` in `/usr/share/themes/Numix/openbox-3/themerc`
- `<theme name="Numix" />` in `~/.config/labwc/test/rc.xml`
- empty (well, all commented out) `~/.config/labwc/test/themerc-override`
- started with `-C ~/.config/labwc/test`
- `00:00:00.425 [../src/theme.c:500] read theme /usr/share/themes/Numix/openbox-3/themerc`
- `00:00:00.439 [../src/theme.c:524] read theme-override /home/test/.config/labwc/test/themerc-override`
- `A-Tab` OSD is ridiculous narrow

then
- modified `~/.config/labwc/test/themerc-override` to use `osd.window-switcher.width: 1600`
- doing a `Reconfigure`
- `00:01:26.830 [../src/theme.c:500] read theme /usr/share/themes/Numix/openbox-3/themerc`
- `00:01:26.845 [../src/theme.c:524] read theme-override /home/test/.config/labwc/test/themerc-override`
- `A-Tab` OSD is ridiculous wide

**Comment by stefonarch** [comment]
Well, thanks, nice - but cannot reproduce ;)
Wait no: actually I managed to make it work in the theme but not anymore in override but it's too weird to describe how and there's no logic in it.

Actually I had set the switcher to show="no" always, because I've only few windows per desktop. I stumbled upon that while fixing themes with only supported options, purging all openbox-only stuff. Giving up for the moment on this.

**Comment by Consolatis** [comment]
Another random idea: a different kind of `-` could trigger this as well, e.g. some language specific unicode char that looks like a `-` but isn't.

**Comment by xxhh1112** [comment]
good

**Comment by stefonarch** [comment]
Just tested it with latest git  `0.6.5-37-g47a80fc` and styling for swithcer is working now.

**Comment by stefonarch** [comment]
Talking about mysteries: I noticed in my themerc-override a line not working....
```

#themerc-override.

# copied from manpage, works:
#osd.window-switcher.width:200

# this line works too:
#osd.window-switcher.width: 400

#this one not, doesn't depend from the value:
osd.window‐switcher.width: 200
```
 I think this was the cause for the issue but have no clue what's wrong. If I C&P the lines posted here I can reproduce it-

**Comment by Consolatis** [comment]
As written inhttps://github.com/labwc/labwc/issues/1098#issuecomment-1732450072 your `-` char is some unicode character sometimes. Suggest rewriting the non-functioning lines with `it` layout in `nano` or something.
