### ISSUE TITLE
failed to build commit: 4028a94

### ISSUE THREAD

**Issue by CaptainBloodz** [labwc/labwc#1118]
repository:               https://github.com/labwc/labwc
   updating from commit:     e5aef0331996aa0c77f7ea2f0af390b40704f626
   to commit:                4028a9482f9399e3c3587f5c6eca6c0b128c9afc

ends as

FAILED: labwc.p/src_view.c.o 
x86_64-pc-linux-gnu-gcc -Ilabwc.p -I. -I../labwc-9999 -Iinclude -I../labwc-9999/include -I/usr/lib64/libffi/include -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/elogind -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -DWLR_USE_UNSTABLE -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wunused-macros -Wno-unused-parameter '-DLABWC_VERSION="0.6.5-10-g4028a94"' '-DGETTEXT_PACKAGE="labwc"' '-DLOCALEDIR="/usr/share/locale"' -march=native -mtune=native -O2 -flto -fuse-linker-plugin -fno-fat-lto-objects -pipe -Wa,-mbranches-within-32B-boundaries -pthread -MD -MQ labwc.p/src_view.c.o -MF labwc.p/src_view.c.o.d -o labwc.p/src_view.c.o -c ../labwc-9999/src/view.c
../labwc-9999/src/view.c:5:10: fatal error: wlr/xwayland.h: No such file or directory
    5 | #include <wlr/xwayland.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

where [I] gui-libs/wlroots
     Installed versions:  0.16.2-r1(0/16)(15:24:48 26/08/2023)(drm libinput x11-backend -X -tinywl -vulkan) unchanged.

I could step commit per commit if requested...

**Comment by CaptainBloodz** [comment]
wlroots[X] fixed the breakage.
Wasn't required in earlier build.

**Comment by Consolatis** [comment]
Oh, right. We didn't guard the xwayland include itself. Thanks for pointing that out!

Following diff should fix it, will create a PR later.

```diff
diff --git a/src/view.c b/src/view.c
index 23b345fe..6e41f382 100644
--- a/src/view.c
+++ b/src/view.c
@@ -2,7 +2,6 @@
 #include <assert.h>
 #include <stdio.h>
 #include <strings.h>
-#include <wlr/xwayland.h>
 #include "common/mem.h"
 #include "common/scene-helpers.h"
 #include "labwc.h"
@@ -15,6 +14,10 @@
 #include "workspaces.h"
 #include "xwayland.h"

+#if HAVE_XWAYLAND
+#include <wlr/xwayland.h>
+#endif
+
 #define LAB_MIN_VIEW_WIDTH  100
 #define LAB_MIN_VIEW_HEIGHT  60
 #define LAB_FALLBACK_WIDTH  64
```

**Comment by Consolatis** [comment]
Should be fixed in latest master. Thanks again for the fast report :)

**Comment by CaptainBloodz** [comment]
Building fine here...
Thks 4 the quick fix.
