### ISSUE TITLE
Unable to move window by cursor

### ISSUE THREAD

**Issue by varbhat** [labwc/labwc#112]
I want to drag window around the screen, but it seems to be not working.

I am using labwc-git from AUR and dragging window with cursor is not working. 

Tried applications are foot, firefox and pcmanfm-qt

Please help.

**Comment by ARDiDo** [comment]
Hey @varbhat. Could you tell me how you have been attempting to move the windows?
Are you trying to move them by clicking on the titlebar and dragging it, or are you holding down the alt-key while clicking anywhere on the window and dragging?

**Comment by johanmalm** [comment]
Is this the first time you’re running labwc?
Have you been able to move windows before?

Are you trying to move the windows by dragging the titlebar or by pressing alt+left clicking on the app.

Does it work with client-side-decorations - for examples with mousepad.

Are you running on bare metal or under X11 or through virtualbox/similar.

Can you move windows using key-binds (e.g. alt+arrows)?

If you have a rc.xml, try removing it to confirm it’s not a config error.

Does it work with sway with floating windows?

**Comment by varbhat** [comment]
@ARDiDo ,i normally clicked on the title bar and tried to move. didn't press Alt-key

**Comment by varbhat** [comment]
> Is this the first time you’re running labwc? Have you been able to move windows before?

Yeah. it's first time. Have used openbox/fluxbox before though but not labwc.

> 
> Are you trying to move the windows by dragging the titlebar or by pressing alt+left clicking on the app.
> 
by just dragging the titlebar like in popular DEs(like plasma)

> Does it work with client-side-decorations - for examples with mousepad.
> 
> Are you running on bare metal or under X11 or through virtualbox/similar.
> 

bare metal. 

> Can you move windows using key-binds (e.g. alt+arrows)?
It works.
> 
> If you have a rc.xml, try removing it to confirm it’s not a config error.
> 

> Does it work with sway with floating windows?
Yeah. it can be moved.

**Comment by varbhat** [comment]
Well, saw in Readme that Alt+left click is used to move windows.

Isn't it possible to just move windows by dragging without pressing any key?

**Comment by johanmalm** [comment]
^^ so, it looks like the issue relates to the config file.
Could you paste the <mouse> section?

**Comment by varbhat** [comment]
@johanmalm ,

I can move windows if i press alt key while dragging the cursor.

Is it possible to move windows without pressing alt key by simply dragging the cursor?

**Comment by varbhat** [comment]
@johanmalm ,what i meant is that, i need to just click titlebar of window and drag the cursor and window must move.

**Comment by johanmalm** [comment]
It’s designed to work by just grabbing the titlebar, so something odd is going on.

Could you delete your $HOME/.config/labwc/rc.xml + restart the compositor and confirm if it works then

**Comment by varbhat** [comment]
@johanmalm ,

i think https://github.com/labwc/labwc/commit/12137ba4468ff0c0872fe463663669e5f69fc140 fixed it 😅

**Comment by johanmalm** [comment]
Excellent
