### ISSUE TITLE
Keybinds lost and not recoverable

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1129]
It happened now for the third time but unfortunately I have no idea what triggers it. I've only lxqt-panel and virtualbox with `toggleKeyBinds` set by window rules and no shortcut for it. 

It happened never before until maybe a week ago and I've to restart the session because reconfigure won't help. Log is [here](https://pastebin.com/u1wSdwFY).

**Comment by Consolatis** [comment]
I don't completely understand the issue. You have a window rules which executes `ToggleKeybinds` for lxqt-panel and virtualbox and can't escape it? Not even when focusing or opening another window?

In any case if you configure a keybind for `ToggleKeybinds` you should always be able to disable it for the currently focused window.

**Comment by stefonarch** [comment]
> You have window rules which execute ToggleKeybinds for lxqt-panel and virtualbox and can't escape it?

Those rules work fine if focus is on there. I mentioned it because it's the only setting where toggleKeybinds is involved. I'm not even sure if it's about toggleKeybinds - they just stopped to work altogether and I've no idea why. Virtualbox was never involved.

**Comment by johanmalm** [comment]
@stefonarch Are you able to consistently re-produce it? If so, can you give me the steps to re-produce.
Does it happen if you run with `labwc -C /dev/null'?

**Comment by stefonarch** [comment]
As I said: I've no idea how to trigger it, can only wait and look if it happens again and maybe then I'll find the steps.

**Comment by johanmalm** [comment]
> As I said: I've no idea how to trigger it, can only wait and look if it happens again and maybe then I'll find the steps.

Okay. Do you restart your computer every day or are you on a long-running (old) tty session? I'm just thinking that we've made a few changes to keyboard handling recently, so if you're on a long running instance, it might be worth re-starting.

**Comment by stefonarch** [comment]
Usually I've long uptimes, until a week or more, only suspending to RAM. After updating labwc I restart the session though.

**Comment by stefonarch** [comment]
It happened again, switching layout, and I can it reproduce always now which is real nasty.
Can reproduce it with default rc.xml and
```
cat .config/labwc/environment 
XKB_DEFAULT_LAYOUT=it,ch
XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle,grp_led:scroll
XCURSOR_THEME=Breeze_Snow
XCURSOR_SIZE=28
MOZ_ENABLE_WAYLAND=1
```

**Comment by stefonarch** [comment]
> Downgrade didn't resolve too.

As it's present on  both machines (arch/debian) I downgraded now more.
 0.6.5 is working and the issue starts with e77330bc3fe733412e92f4e90d797d31ee6c5652

**Comment by Consolatis** [comment]
I stumbled over this issue as well while testing an implementation for further modifiers.
We are adding `XKB_KEY_ISO_Next_Group` to pressed. It can be recovered from when pressing one of the modifiers, then pressing and releasing the second one and only then releasing the first one. I'll add a fix for this in the new modifier PR.

**Comment by stefonarch** [comment]
That worked, and that was probably the way to get keybinds back again I stumbled blindly upon.

**Comment by johanmalm** [comment]
Great detective work!! I love it when we get to the bottom those weird defects.

**Comment by Consolatis** [comment]
Should be fixed on latest master. Feel free to comment if there are further issues.

**Comment by stefonarch** [comment]
Confirming fix, thanks!
