### ISSUE TITLE
Screen on crash app

### ISSUE THREAD

**Issue by Nosirus** [labwc/labwc#1144]
Hi,
Small problem that I can't find the solution.
I often turn off the screen when I'm not using the computer, but when I turn it back on, no applications are displayed.
When I watch from a distance with sunshine and screen off no problem.
It seems to be when I turn on the screen

I use Nixos if that helps

**Comment by johanmalm** [comment]
Could you check if the same happens with `sway`?

**Comment by johanmalm** [comment]
If you alt-tab are the applications still present?

**Comment by Nosirus** [comment]
No with alt-tab there is no application.
Before I was on wayfire and I never noticed this problem.
I might try with sway when I can

**Comment by johanmalm** [comment]
Will close this for now. Please shout if the bug still exists. Ideally, if you're able to provide steps to re-produce it's easier to fix.
