### ISSUE TITLE
Window Switcher doesn't dissapear after released keys.

### ISSUE THREAD

**Issue by Elxsie** [labwc/labwc#1159]
I've run into a bug: sometimes when I use `Alt+Tab` to switch between windows, the window list doesn't disappear after I've selected the window I want and released the `Alt` key. This steals focus and causes subsequent key presses to produce unexpected results.
My current workaround is to press `Alt` again, which successfully hides the window switcher.
Any suggestions or help would be greatly appreciated. Thank you.

`ArchLinux, labwc 0.6.5`

**Comment by johanmalm** [comment]
Would you mind testing with “master”.
We’ve pushed a few fixes since 0.6.5

**Comment by Elxsie** [comment]
> Would you mind testing with “master”. We’ve pushed a few fixes since 0.6.5

I will try, thank you.

**Comment by johanmalm** [comment]
We've fixed lots of keyboard/keybind issues recently, so suspect this is fixed. Feel free to re-open if not the case.
