### ISSUE TITLE
can't bind C-Escape anymore

### ISSUE THREAD

**Issue by Arnaudv6** [labwc/labwc#1160]
keywords: _control, ctrl, esc._

Problem: can't bind C-Escape anymore
This worked fine in release 0.6.5
Now I can bind C-A-Escape, or A-Escape, but not C-Escape.
config:
``` XML
    <keybind key="C-Escape">
      <action name="Execute">
        <command>$COLOREXE top</command>
      </action>
    </keybind>
```

**Comment by johanmalm** [comment]
Binding to `C-Escape` works for me with `master`.

What XKB environment variables have you got set?

`set | grep XKB`

Does it work if you unset all the XKB env vars and restart the compositor?

**Comment by Arnaudv6** [comment]
Thanks Johan for the support, I had this:
```shell
XKB_DEFAULT_LAYOUT=fr
XKB_DEFAULT_MODEL=pc105
XKB_DEFAULT_OPTIONS=terminate:ctrl_alt_bksp
XKB_DEFAULT_VARIANT=oss
```
but C-Escape's been working for months like this, and unsettling them has no effect (other that screwing my letters).
I'll try to bisect soon (TM).

**Comment by Arnaudv6** [comment]
I bisected this down to... 881d788.
Apologies for my support request: I got hit by var expansion feature regression.
Since labwc _used to_ do var expansion, I did not prefix the action line with `sh`
All is well after all, closing.
