### ISSUE TITLE
Context menus of X-applications immediately close upon opening

### ISSUE THREAD

**Issue by dirk-hub** [labwc/labwc#1161]
An observation I made using latest master of labwc:
all the context menus of X applications (LibreOffice, IntelliJ) immediately close upon opening, barely showing for a single frame if at all.
Reverting back to labwc 0.6.5 does not exhibit this effect, so this is the version I am currently using.

**Comment by johanmalm** [comment]
Thanks for reporting.

@jlindgren90 I guess this is hints->input related. It seems to be causing lots of user issues. Similar X client focus reported in IRC.

Shall we revert and consider using the hints->input check as part of a window-rule instead?

**Comment by jlindgren90** [comment]
Let me see if I can reproduce with LibreOffice. Context menus seem like they ought to be unmanaged surfaces so I'm not sure why WM_HINTS would have anything to do with this.

**Comment by jlindgren90** [comment]
It might rather be related to the focus_change signal handling.

**Comment by jlindgren90** [comment]
I can't reproduce this with LibreOffice, labwc 125bab47961bd7c8a25667ce9a0abec7f6cf03ba.

**Comment by jlindgren90** [comment]
IntelliJ IDEA's welcome screen is just blank gray here under labwc.

**Comment by dirk-hub** [comment]
Oh my, unreproducible issues are the worst

**Comment by jlindgren90** [comment]
Can you confirm what commit of labwc showed the issue? Does it still happen with the default config, e.g. `labwc -C /dev/null -s foot`? What version of LibreOffice are you using and with what UI toolkit (LibreOffice supports GTK, Qt, as well as a fallback)?

**Comment by jlindgren90** [comment]
Ah I can reproduce the issue now with `SAL_USE_VCLPLUGIN=gen libreoffice`. With the GTK or Qt plugins active, it doesn't occur.

**Comment by jlindgren90** [comment]
4028a9482f9399e3c3587f5c6eca6c0b128c9afc is the first bad commit
```
commit 4028a9482f9399e3c3587f5c6eca6c0b128c9afc
Author: John Lindgren <john@jlindgren.net>
Date:   Wed Sep 27 18:24:35 2023 -0400

    seat: use focus_change event to update focused/active view
    
    - Connect to wlr_seat_keyboard_state's focus_change event.
    - Add view_from_wlr_surface(), which does what the name says.
    - Use focus_change event along with view_from_wlr_surface() to update
      server->focused_view and set SSD states via view_set_activated().
    - Eliminate desktop_focused_view() since server->focused_view should be
      reliably up-to-date now.
    - Eliminate view_focus/defocus() since we can now just call
      seat_focus_surface() directly.
```

**Comment by dirk-hub** [comment]
LibreOffice Calc's About:

Version: 7.5.7.1 (X86_64) / LibreOffice Community
Build ID: 50(Build:1)
CPU threads: 16; OS: Linux 6.5; UI render: Skia/Raster; VCL: x11
Locale: de-DE (de_DE.UTF-8); UI: en-US
Debian package version: 4:7.5.7-1
Calc: threaded


Doing a bisect now...

**Comment by jlindgren90** [comment]
@dirk-hub Thanks. I did a bisect, you're welcome to confirm but I suspect you will end up at the same commit 4028a9482f9399e3c3587f5c6eca6c0b128c9afc.

**Comment by dirk-hub** [comment]
`git bisect start
# status: waiting for both good and bad commits
# good: [48e0b3f6a6bc7a60d8414f5f366a9d7bc3f1c42e] build: bump version to 0.6.5
git bisect good 48e0b3f6a6bc7a60d8414f5f366a9d7bc3f1c42e
# status: waiting for bad commit, 1 good commit known
# bad: [125bab47961bd7c8a25667ce9a0abec7f6cf03ba] output: fix invisible cursor after wlopm --off && wlopm --on
git bisect bad 125bab47961bd7c8a25667ce9a0abec7f6cf03ba
# bad: [2e07bc754e024aa4beeb865ef09482d06957f2b7] README.md: update section 1.4 too
git bisect bad 2e07bc754e024aa4beeb865ef09482d06957f2b7
# bad: [607c295527c36d9709776d27d833514a63400d17] src/view.c: guard xwayland include
git bisect bad 607c295527c36d9709776d27d833514a63400d17
# good: [3022985ba797a061df8c8ac33b2dfb77bf20dcb3] view: try to reduce confusion in focused_view tracking
git bisect good 3022985ba797a061df8c8ac33b2dfb77bf20dcb3
# good: [d56cf92794c311ac23807b87d006e687f613efb5] keyboard: fix release event bug after session lock
git bisect good d56cf92794c311ac23807b87d006e687f613efb5
# bad: [4028a9482f9399e3c3587f5c6eca6c0b128c9afc] seat: use focus_change event to update focused/active view
git bisect bad 4028a9482f9399e3c3587f5c6eca6c0b128c9afc
# good: [bb5d272dc98b25f05bc21375df3b55a99734dfb0] README.md: describe --force-fallback-for option
git bisect good bb5d272dc98b25f05bc21375df3b55a99734dfb0
# first bad commit: [4028a9482f9399e3c3587f5c6eca6c0b128c9afc] seat: use focus_change event to update focused/active view
`

Yes, that's the one.

**Comment by jlindgren90** [comment]
@dirk-hub please confirm if this is fixed for you, otherwise we can reopen the issue.

**Comment by dirk-hub** [comment]
Works for me :+1:
