### ISSUE TITLE
swaylock surface loses focus, can't unlock session

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#1166]
About 1 in 10 times (rough guess), I return to a labwc session locked using swaylock and can't unlock it; key presses don't seem to register with swaylock at all. (swaylock is displayed correctly though.)

So far I've determined that when this occurs, `keyboard_key_notify()` is still being called and `handle_compositor_keybindings()` returns false (as it should) but there is no focused surface to send the keypresses to (`seat->seat->keyboard_state.focused_surface` is NULL).

I'm continuing to try to find the root cause, but it's slow progress since the issue only occurs once every few days. Just wanted to record that the issue exists, and progress so far in debugging it.

(Not sure if related to #885.)

**Comment by johanmalm** [comment]
1. Does it happen independently of any output-layout changes?
2. `swaylock` has pushed a few commits which look like potential bug fixes since `1.7.2`. Are you running with their `master`?

**Comment by jlindgren90** [comment]
I am not sure yet whether it's related to output changes or not. I'll keep in mind to try the newer swaylock, thanks for the heads-up.

**Comment by jlindgren90** [comment]
It happened once more this evening and I captured a little more log output. The swaylock surface was not unmapped, it just lost focus. I'm currently thinking this is not a swaylock bug but something on our side.

I'm looking suspiciously at all the `seat_focus_surface()` call sites that don't have a `!server->session_lock` check. For example, there is one in `desktop_focus_view()` but not in the `else` branch of `desktop_focus_topmost_view()`.

**Comment by jlindgren90** [comment]
Found it. I can reproduce the issue by locking the screen while an xfce4-notifyd notification is onscreen (running with GDK_BACKEND=x11), but no focusable views. When the notification is destroyed, the `else` branch of `desktop_focus_topmost_view()` is entered and calls `seat_focus_surface(seat, NULL)`.

So technically this issue was introduced by 3022985ba797a061df8c8ac33b2dfb77bf20dcb3 (which refactored `desktop_focus_topmost_view()` and `desktop_focus_view()`) and would be fixed (accidentally) by #1173.

I'll work on a fix.

**Comment by Consolatis** [comment]
Nice debugging!
