### ISSUE TITLE
Dialog window hidden behind child window

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#1168]
I can only remember it happening in calibre, when a dialog window pops up after already having a child window open. So for example: main window -> child window -> dialog window, the dialog is hidden behind the child window. Sorry for probably improper terminology? See https://0x0.st/H46J.mkv

Related: #998

**Comment by johanmalm** [comment]
@Flrian I can't reproduce this.
I have followed exactly what you do in the video but my 'security risk' dialog appears in front of the other windows. Even when I click on the other windows, I can't make the dialog go behind.
I'm on labwc 'master' and the latest calibre on Arch Linux.

**Comment by johanmalm** [comment]
> Ah, I somewhat figured out the problem. I'm on gentoo and because I don't want to compile the whole of Qt just for calibre I'm using the binaries [from the calibre website](https://calibre-ebook.com/download_linux). I couldn't reproduce it on arch with calibre from the repos either, so I tried it with the binaries from the website and it happened then too. They probably bundle some outdated libraries or something, who knows.

Thanks. If it comes back with any toolkit/setup in a way that I can re-produce it should be easy to solve. Agree, let's leave for now.
