### ISSUE TITLE
sway & labwc   ctrl-c ctrl-v

### ISSUE THREAD

**Issue by devosalain** [labwc/labwc#117]
When i want to copy paste, from a sway window , ctrl-c, into a client labwc window ctrl-v it, does not work.

**Comment by 01micko** [comment]
It works fine here with gtk and native wayland apps.

For example, I `ctrt-c` from firefox to `ctrl-v` geany text editor all the time and I can `ctrl-shift-v` paste into `foot` vt as well.

**Comment by johanmalm** [comment]
@devosalain is it possible to do the same from sway to sway?

**Comment by johanmalm** [comment]
I've just tried doing the same running sway under sway - and that doesn't work either. Will therefore consider it out of scope.
If anyone has any real need for this; or has some good ideas for how to implement, please shout. Will close for now.

**Comment by Consolatis** [comment]
Sounds like this is about wlroots nested wayland/x11 backends not implementing the backend side of clipboard sharing. Didn't verify that but if thats indeed the case and you need that to work it should be raised at https://gitlab.freedesktop.org/wlroots/wlroots/-/issues
