### ISSUE TITLE
Can I completely disable decorations?

### ISSUE THREAD

**Issue by 1qh** [labwc/labwc#1182]
I know there's a ToggleDecorations action. But is there any way to make it toggle off by default?

**Comment by Consolatis** [comment]
You could try a window rule like this:
```xml
<windowRules>
  <windowRule identifier="*" serverDecoration="no" />
</windowRules>
```
Combined with `<core decorations="server" />` this should disable all server side decorations + disable decorations for applications that are willing to give up their client side ones.

**Comment by 1qh** [comment]
Thank you, it works perfectly!
