### ISSUE TITLE
Can I hide these boxes in the Desktop Switcher OSD?

### ISSUE THREAD

**Issue by 1qh** [labwc/labwc#1199]
![image](https://github.com/labwc/labwc/assets/64073540/7991e5bc-d381-49b7-a4e1-5ccc117c7cb7)

**Comment by Consolatis** [comment]
You can hide the whole OSD (via `popupTime="0"`) but we don't currently provide a way to hide just the boxes.
That could be implemented though, the OSD would then only contain the name.

**Comment by 1qh** [comment]
Yes, since I find out a better way to name the workspaces, I think those boxes can be hidden for a cleaner look

```xml
  <desktops number="10">
    <names>
      <name>1️⃣·········</name>
      <name>·2️⃣········</name>
      <name>··3️⃣·······</name>
      <name>···4️⃣······</name>
      <name>····5️⃣·····</name>
      <name>·····6️⃣····</name>
      <name>······7️⃣···</name>
      <name>·······8️⃣··</name>
      <name>········9️⃣·</name>
      <name>·········🔟</name>
    </names>
  </desktops>
```

I hope that we can have an option to hide just the boxes in the next release. Thanks a lot!

**Comment by Consolatis** [comment]
Should be fixed in latest master, you can set either `osd.workspace-switcher.boxes.width` or `osd.workspace-switcher.boxes.height` in your theme or in `~/.config/labwc/themerc-override` to `0`.
