### ISSUE TITLE
noob feedback

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1205]
I'm a Tiny Core Linux user/contributor exploring wayland for the first time and was immediately drawn to labwc. Thank you for this great project. I packaged labwc and it has been added to the official TCL repository.

I just have one feedback item and one question:

Feedback: On your [waybar integration suggestion](https://labwc.github.io/integration.html#waybar) you suggest adding this to the waybar configuration file:
```
   "wlr/taskbar": {
        "format": "{app_id}",
        "on-click": "minimize-raise",
    }
```
 
I'd like to suggest that a trailing comma be added, like so:
```
   "wlr/taskbar": {
        "format": "{app_id}",
        "on-click": "minimize-raise",
    },
```
 
The missing comma had this labwc/waybar beginner going around in circles for a while.
 
Question: In section "1.6 Screenshot" of README.md you show a nice bar at the bottom. Would you happen to know the name of that bar and the configuration used?
 
Thanks!

**Comment by Consolatis** [comment]
> I packaged labwc and it has been added to the official TCL repository.

Very nice, thanks :)
I've added you to our list of maintainers (#1206) to tag for releases which change something regarding packaging (e.g. new dependencies and similar). See #1104 for an example. I hope that is fine, feel free to notify us if we should rather not do that and I modify the PR.

> I'd like to suggest that a trailing comma be added, like so:

done:
- labwc/labwc.github.io#36

> Question: In section "1.6 Screenshot" of README.md you show a nice bar at the bottom. Would you happen to know the name of that bar and the configuration used?

That bar is not yet public because its developer (e.g. me) is way too lazy to fix some things.

**Comment by bdantas** [comment]
Hi, Consolatis. Thank you for adding me to the maintainer list. It would be definitely be helpful to know about changes relevant to packaging (such as a change in dependencies). 
 
Thanks for making the small tweak to the waybar integration--I can confirm that the website shows the trailing comma now. 
 
Pity to hear your bar is not ready for public testing. I will check out sfwbar. Thanks for the recommendation.
