### ISSUE TITLE
Keybindings stop working after laptop lid close/open

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#1208]
A few times, I've seen all keybindings in labwc stop working. I've finally figured out that it is triggered after closing and then reopening the laptop lid. With some extra logging, I've determined that the laptop is generating a keypress with keycode 0x8f / keysym 0x1008ff2b (XF86XK_WakeUp) but no matching key release. This causes the `key_state_nr_pressed_keys() > 1` check in `handle_compositor_keybindings` to trigger and no keybindings to be handled from that point on.

I'm not sure of the best way to solve this. The "no other keys pressed" check seems a bit prone to situations where odd keycodes like this get stuck. I'm wondering if that check is really necessary. If it is, maybe a timeout could be added to check for keys that are stuck for an unreasonably long time?

**Comment by Consolatis** [comment]
We've talked about a timer based safety net before, it might be an option. But we should ensure that it won't just delete whatever is in there at the point it triggers (maybe have the _set_pressed()` function automatically add a timestamp?). Another idea was to maybe empty the set on `Reconfigure`.

The check is necessary so we don't trigger for example a `A-z' keybind while pressing `A-z-q`.
There is already a `is_layout_switch` check in there that prevents (almost) the same situation from happening when switching keyboard layouts.

For your specific case we could maybe move the `is_layout_switch` check to its own function where it then then also checks for
- `XKB_KEY_XF86WakeUp` and possibly also for
- `XKB_KEY_XF86Suspend`
- `XKB_KEY_XF86Hibernate`

**Comment by johanmalm** [comment]
In terms of context, it's pretty important not to send release events to clients if the press event was absorbed (which the `key-state.c` logic is primarily there to prevent).

Maybe we ought to soften the `key_state_nr_pressed_keys() > 1` check. It's there to make sure we don't press more than one 'normal' key (currently considered anything that isn't a modifier + `XKB_KEY_ISO_Group_Next`). Could we instead consider a 'normal' key to be a `Latin 1` key (range `0020`..`00FF`) and thus filter out `WakeUp`, `Suspend`, `Hibernate`, `ISO_Next_Group`, and anything else we haven't come across yet. Or we could make it a bit more sophisticated to include KP (keypad) keys, Home, End, etc.

https://github.com/xkbcommon/libxkbcommon/blob/6073565903488cb5b9a8d37fdc4a7c2f9d7ad04d/include/xkbcommon/xkbcommon-keysyms.h#L559

**Comment by johanmalm** [comment]
Or keep it a bit wider and only filter out:
- `Extension function and modifier keys` (incl. ISO_Next_Group)
- `XFree86 vendor specific keysyms` (incl. WakeUp, etc)

https://github.com/xkbcommon/libxkbcommon/blob/6073565903488cb5b9a8d37fdc4a7c2f9d7ad04d/include/xkbcommon/xkbcommon-keysyms.h#L359
https://github.com/xkbcommon/libxkbcommon/blob/6073565903488cb5b9a8d37fdc4a7c2f9d7ad04d/include/xkbcommon/xkbcommon-keysyms.h#L2476C4-L2476C35

**Comment by Consolatis** [comment]
I am not sure why we would receive a `press` event for a key but not a `release` one though, that is the main issue in this case.
If there'd be a way to only exclude such keys that would help a lot and should completely fix this class of bug.

In regards to only `Latin 1`: that would be an issue as we now also support keys for different keyboard layouts as keybinds. So basically random unicode codepoints can be legit keys for a keybind.

Regardless of how we handle the exclusion of further keys, I think some kind of safety net would be a good addition.
IMHO the least impact would be an implementation that changes `struct key_array` from `key-state.c` from

```c
struct key_array {
	uint32_t keys[MAX_PRESSED_KEYS];
	int nr_keys;
};
```
into something like this
```c
struct pressed_key {
	uint32_t key;
	time_t timestamp;
};
struct key_array {
	struct pressed_key keys[MAX_PRESSED_KEYS];
	int nr_keys;
};
```
And then do something like this
```c
static void
add_key(struct key_array *array, uint32_t keycode)
{
	if (!key_present(array, keycode) && array->nr_keys < MAX_PRESSED_KEYS) {
		struct timespec now = { 0 };
		clock_gettime(CLOCK_MONOTONIC, &now);
		array->keys[array->nr_keys++].key = keycode;
		array->keys[array->nr_keys++].timestamp = now.tv_sec;
	}
}
key_state_safety_net() {
	struct timespec now = { 0 };
	clock_gettime(CLOCK_MONOTONIC, &now);
	for (int i = 0; i < pressed.nr_keys; i++) {
		if (pressed.keys[i].timestamp + KEY_PRESS_EXPIRE_TIMEOUT <= now.tv_sec) {
			remove_key(&pressed, pressed.keys[i].key);
			wlr_log(WLR_ERROR,
				"Key state safety net triggered: had to remove keycode %u",
				pressed.keys[i].key);
		}
	}
}
```

**Comment by johanmalm** [comment]
This might just be a very good approach. Will have a look at openbox's code tomorrow.

**Comment by Consolatis** [comment]
Closing as #1226 has been merged.
