### ISSUE TITLE
yes command behaving unexpectedly

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1209]
Scripts that use `yes` (either busybox version or coreutils version) behave unexpectedly when running in terminal emulators (e.g., havoc) running inside labwc. Some scripts litter the screen with "Broken pipe" errors or, worse, enter an infinite loop. Here is one way to trigger an infinite loop:
```
echo "this is a test" >test.txt
busybox yes "password" | bcrypt test.txt
```
I think this is because labwc disabled SIGPIPE in version 0.6.3 and the terminal emulators are inheriting the disabled signal.

Is there a way for me to restore the normal SIGPIPE behavior in my shell? Not in the whole GUI environment--just shell scripts (including those running in a terminal emulator). I use busybox ash. Any help would be greatly appreciated.

**Comment by Consolatis** [comment]
From what I understand, signal handlers are *not* inherited by a `execvp` [0].

Additionally we remove all blocked signals when spawning a new process:  https://github.com/labwc/labwc/blob/master/src/common/spawn.c#L46-L48

When you get a `Broken pipe` error that seems to indicate that the application in question in fact got a `SIGPIPE`.

> busybox yes "password" | bcrypt test.txt

I don't have busybox (or bcrypt) on my system but this looks more of a bcrypt usage thing, potentially related to this quote from the [man page](https://linux.die.net/man/1/bcrypt):
> Passphrases may be between 8 and 56 characters.

[0]
See `man execve`:
>    Effect on process attributes
       All process attributes are preserved during an execve(), except the following:
       *  The dispositions of any signals that are being caught are reset to the default (signal(7))

**Comment by bdantas** [comment]
Hi Consolatis. Wow, thank you for getting back to me so quickly!
 
Password meets bcrypt criteria (these same scripts work fine in Xorg in an environment with identical kernel, userland tools, etc). Good to know that handlers are not inherited. There is definitely something in my new wayland environment that is negatively affecting `yes`.
 
But I think I'll just avoid the usage that results in endless loop and will silence the nuisance "Broken pipe" messages with this trivial wrapper script for `yes`:
```
#!/bin/sh
exec /usr/bin/yes "$@" 2>/dev/null
```
Thanks again.
 
P.S. Migration from X to wayland has been otherwise seamless for me. I find it humorous that I can detect no breakage in the big, complicated things (web browser, email client, etc.). It's only this pinnacle of software engineering (Busybox's `yes` applet) that is behaving in unexpected ways! Go figure.

**Comment by Consolatis** [comment]
> There is definitely something in my new wayland environment that is negatively affecting `yes`.

Maybe `foot` vs `havoc` would make a difference? I can't reproduce it via `busybox yes "foo" | head -c 1` in either `foot` nor `havoc` though.

**Comment by clbr** [comment]
Just to clarify, later in the execve man page it says
"POSIX.1-2001 specifies that the dispositions of any signals that are
          ignored  or  set  to  the  default are left unchanged."

So I read it as SIG_IGN gets inherited but a signal handler would get reset.

**Comment by clbr** [comment]
This page says it more clearly:
https://lwn.net/Articles/631631/

"sets up the signal handlers for the new program; any signal handler that's not SIG_IGN gets set to the default SIG_DFL value (so any ignored signals are inherited by the new program)"

**Comment by Consolatis** [comment]
@clbr thanks for looking that up.
Hm.. interesting. Maybe we *do* have to set it manually to `SIG_DFL` again before doing the exec.

@bdantas if you have the chance, trying to comment out the line mentioned in the edit of https://github.com/labwc/labwc/issues/1209#issuecomment-1783985003 would confirm that this is actually the issue here.

**Comment by bdantas** [comment]
@clbr Thanks for pitching in and for confirming what I suspected based on observed behavior.
 
@Consolatis: I recompiled labwc with this
https://github.com/labwc/labwc/pull/1210
and `yes` now behaves as expected. I will re-package labwc for TCL x86_64 with this fix. Many thanks!

**Comment by Consolatis** [comment]
Should be fixed on latest master.

Thanks @bdantas for reporting + testing and thanks @clbr for stepping in and correcting me.
