### ISSUE TITLE
alt-F4: run script if no windows left to close

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1211]
Hi Consolatis. In X I used to have the keyboard shortcut `alt-F4` bound to a shell script (call it "A") that would close the active window and, if there are no windows left, it would run a second shell script (call it "B") that presents user with GUI power options.
 
pseudocode of A looks like this:
```
#!/bin/sh
xdotool close-active-window || B
```
I'm trying to implement something similar for my laptop running labwc. Can you think of an obvious solution? If I could find the CLI approach to close active window and/or calculate the number of existing windows, I could make progress. But, alas, I can find neither.

**Comment by Consolatis** [comment]
[wlrctl](https://git.sr.ht/~brocellous/wlrctl) will likely open many possibilities regarding scripting. It supports the foreign-toplevel protocol (and as such activate, minimize, maximize, fullscreen, close) and also supports the virtual keyboard protocol which could be used to inject keys which in turn trigger keybinds.

**Comment by bdantas** [comment]
Ah, that's nice. I had checked out `ydotool` but it had nothing to offer in the window-management department. I had not heard of wlctrl before now but I was a fan of wmctrl in X. I think wlctrl is exactly what I need. Thank you for the recommendation.

P.S. I suffer from a condition called forced-Windows-at-work. My desire for this behavior from alt-F4 is a symptom of that condition :p

**Comment by Consolatis** [comment]
Not tested but something like that might work:
`wlrctl window close 'state:active' || echo "ayayay no windows left to close"`

**Comment by johanmalm** [comment]
> P.S. I suffer from a condition called forced-Windows-at-work. My desire for this behavior from alt-F4 is a symptom of that condition :p

I suffer from the same malady.

I can confirm that this works `wlrctl window close 'state:active' || foo` - nice one @Consolatis 

Maybe `foo` could be a `yad` script?

**Comment by johanmalm** [comment]
Like so...

```bash
#!/bin/sh

yad --center --borders=20 \
	--title="Exit" \
	--button="Suspend":"systemctl suspend" \
	--button="Poweroff":"systemctl poweroff" \
	--button="Cancel"
```

**Comment by bdantas** [comment]
> I can confirm that this works `wlrctl window close 'state:active' || foo` - nice one @Consolatis
> 
> Maybe `foo` could be a `yad` script?
It works for me, too, and is exactly what I was looking for. `foo` is, indeed, a `yad` script. Almost identical to what you showed except that TCL uses busybox init instead of systemd, so commands are different.
 
Thank you both very much!
