### ISSUE TITLE
way to remember some specific app's window size?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1213]
Hello again, Consolatis. Sorry to bother, but another small thing came up and I'd appreciate your input. Some windows have a default size that is too tall, causing the bottom of the window (including `Cancel` and `Save` buttons, for example) to be inaccessible (i.e., beyond the bottom of the screen). For me, the gtk3 file selection box that pops up when selecting a destination for a download is most notorious for this, requiring resizing (or Alt + click + drag upwards) every time.

In X I used fluxbox's [apps](http://fluxbox.org/help/man-fluxbox-apps.php) file for this. Before I was a fluxbox user, I used devilspie2. Now in wayland+labwc I'm a bit lost. Can labwc or a helper application do something like this?

**Comment by Consolatis** [comment]
Hm.. you could potentially [define a region](https://labwc.github.io/labwc-config.5.html#regions) and then use [SnapToRegion](https://labwc.github.io/labwc-actions.5.html#entry_action_name=snaptoregion_region=value) in a [window rule](https://labwc.github.io/labwc-config.5.html#window_rules).

That should then cause the window to always spawn at the same place and size based on your region definition.
