### ISSUE TITLE
dmenu dialog loses keyboard focus

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1217]
When I launch dmenu (for example, by running `ls /home/bruno | dmenu` in a terminal emulator), the dmenu dialog appears but I need to be careful not to click anywhere away from the dialog. If I accidentally click off of the dialog, it becomes impossible to interact with the dmenu dialog again, even though it is still visible. I think the dmenu dialog is escaping labwc's detection, because it has neither window decorations nor does is appear in the alt+tab menu.
 
dmenu seems popular, which makes me think that this strange behavior is because of me (doing something wrong--e.g., not understanding how to make it detectable by labwc). Do you have any idea how to select dmenu dialog again if I accidentally click somewhere else on my desktop before making a selection?

P.S. If this is a dmenu issue and not a labwc issue, no problem--just let me know and I'll ask about this elsewhere.

**Comment by Consolatis** [comment]
This sounds like an issue with the xwayland stacking order. We did recently change some things around in that area.
Thoughts @jlindgren90 ?

**Comment by jlindgren90** [comment]
I can take a look later on. Is this with 0.6.5 or with labwc built from master branch?

**Comment by bdantas** [comment]
This is on labwc 0.6.5

Some more details: I just tested same dmenu version (5.2) on a system running X. In X, dmenu doesn't have window decorations either--so that's not a problem. The problem is that in X, dmenu grabs the keyboard focus and won't let it go until the user makes a choice (it is possible to click on windows, but all keyboard activity goes to dmenu). 
 
I guess a better statement of the bug is this: In labwc, dmenu is unable to forcibly retain keyboard focus until user is done making a selection. This is a problem because dmenu is not running in a selectable window, so when it loses keyboard focus it becomes impossible to interact with it.

**Comment by jlindgren90** [comment]
Thanks. Can you try the latest master branch to see if it's any better/different? There have been a number of changes to both stacking order and focus handling recently.

**Comment by johanmalm** [comment]
Well, `dmenu` falls into a category of X applications that run without GTK/Qt and use Override Redirect (OR) window as the main window. `rofi` and `jgmenu` are other examples of this type of application.

Unless we implement `XKeyboardGrab()` support through `xwayland-keyboard-grab` protocol there isn't a whole lot we can do about it.

We are consistent with X, whereas sway take a slightly different approach (see https://github.com/labwc/labwc/issues/1078#issuecomment-1712789893). I can't say for sure, but I think `sway`'s approach is likely to lead to problems with other XWayland applications, for example games, NetBeans, etc. that push X behaviours to the limit.

I'd rather be correct than apply some focus trick to just cover things over. I think the next step should be to draft a patch implementing support for `xwayland-keyboard-grab` to see if that puts us in a better situation.

**Comment by jlindgren90** [comment]
Okay, but it sounds like dmenu gets focus initially and yet can't be focused again by clicking on it(?) That seems inconsistent and I'd like to understand why that is.

**Comment by bdantas** [comment]
> it sounds like dmenu gets focus initially and yet can't be focused again by clicking on it(?)
 
That's exactly correct.
 
I'm actually not a big fan of the behavior in X where dmenu gets keyboard focus and won't let go until user makes a choice. If in labwc it were possible for dmenu to lose focus but regain it when clicked, IMHO that would be superior to the behavior in a pure X environment.

**Comment by johanmalm** [comment]
Apologies for being narrow minded about this and clinging onto `XKeyboardGrab()`. I think you make some good points and @jlindgren90's patch works great. `dmenu`, `jgmenu` and `rofi` now work better and I can't find any side-effects.

I think my reticence originates from going wrong with override-redirect surfaces in the early development of labwc, but we're dealing with a much more mature code-base now, so I need to relax a bit :smile:

**Comment by jlindgren90** [comment]
> I'm actually not a big fan of the behavior in X where dmenu gets keyboard focus and won't let go until user makes a choice.

A very minor point - this is still the case in labwc if you're working with other XWayland views. dmenu "steals" key presses from those since they're all using the same XWayland instance.

**Comment by johanmalm** [comment]
> A very minor point - this is still the case in labwc if you're working with other XWayland views. dmenu "steals" key presses from those since they're all using the same XWayland instance.

Yes, I did notice that. There are some interesting 'internal' X behaviors. Similar with popups closing closing when changing window focus to another XWayland window.

**Comment by jlindgren90** [comment]
> Similar with popups closing when changing window focus to another XWayland window.

That behavior, I actually like :)

**Comment by bdantas** [comment]
> @jlindgren90's patch works great. `dmenu`, `jgmenu` and `rofi` now work better and I can't find any side-effects.
 
I just tested the patch and can confirm that the bug is solved. Thank you all!
