### ISSUE TITLE
[Feature Request] Mouse window snapping

### ISSUE THREAD

**Issue by skyne98** [labwc/labwc#122]
Hey, there! 

It would be nice to have the possibility to use your mouse to snap windows (or make them full-screen by snapping). I would suggest it should replicate the behavior of the new Windows 11, where you can snap windows not only sides, but also corners, which helps on big screens.

In my head, I see two alternative behaviors working together:
1. When using your mouse to drag the window (either using the decoration or `Alt+LMB`), moving it close to one of the edges of some display will `suggest` releasing the button to snap it there (the same way as `Meta+Arrow Key` would).
2. When doing the same actions as in behavior number 1, but holding `Shift` in the process, the compositor will now be tracking your cursor being in some regions of the screen, not edges. Something like this ![image](https://www.howtogeek.com/wp-content/uploads/2021/06/Windows-11-Snap-Layouts.png?height=200p&trim=2,2,2,2) but not configurable for now (to make it simpler?).

As an additional point, I think it is important to allow users to drag the windows which were double-clicked back into their original forms (and sizes), making them not full-screen again.

I would be glad to help somehow, or get involved, but my experience with C is very limited, I am mostly a Rust/.NET/JS/TS/Dart developer. If there is any way I can help, please tell me!

**Comment by Consolatis** [comment]
By "`suggest` releasing the button" I guess you mean something like a mostly transparent overlay covering the area the window would take if it would be released.

Both `1.` and `2.` should be doable.
@johanmalm is something like `SnapToRegion` within the scope of labwc, either now or later?

As `SnapToEdge` is already implemented I might give it a try.
Sounds like the view should be placed in `interactive_end()` if `view->server->input_mode` == `LAB_INPUT_STATE_MOVE` && view is in X pixel distance of one of the output's edges.
While the overlay should likely be drawn in `process_cursor_move()` using the same condition.
I have zero knowledge about graphic stuff so no idea how to render that overlay but one after the other.

**Comment by Consolatis** [comment]
So whats left is the overlay and possibly regions.

I don't know how one would even configure regions though
- based on raw (output local) pixel coordinates (that would require another config section to define outputs in the first place)?
- just setting a predefined layout like `quarter`, `twobythree`, `threebytwo` which then gets calculated based on current output area?
- what about those mixed region tilings like one half screen on the left and 3 1/3 half-screens on the right
- or how would one express a 2/3 screen on the left and a 1/3 screen on the right

**Comment by skyne98** [comment]
Hey there! Awesome progress, I am sorry I missed the notification for this issue getting an update.

> By "suggest releasing the button" I guess you mean something like a mostly transparent overlay covering the area the window would take if it would be released.

Yep, this is exactly what I meant by it.

> I don't know if that is better than drawing it below. I think it feels a bit more natural.

Honestly, I don't know about it. I feel like it's always a good idea to at least aim in the direction of familiarity, so it would be nice to replicate the behavior of Windows, GNOME, KDE, etc. In this case, the overlay is supposed to be under the window. Also, if you think about it, wouldn't it be a little jarring to have the actual window you are dragging to appear under something for a short period of time?

> I don't know how one would even configure regions though

I think my initial idea for the initial implementation was to have the exactly same regions that usual snapping uses. `Shift` is supposed to just change the behavior from “touch the edge” to “detect the region from the current pointer location”. Sorry about the Windows screenshot, which might have been a little misleading. Currently, I see more value in implementing more edges parallel with regions for them, instead of letting users configure them. Let's say, after snapping to left and right, we also allow snapping to quarters of windows by adding “corner” edges as well as small corner regions. 

Later we can add some options which are region-only, like having a small part of the middle of the screen arrange the window into the middle third of it. However, implementing this will require a mechanism that detects that now you want a “three-column” configuration and adapts regions accordingly.

Otherwise, it's amazing to see someone pick up this issue!

**Comment by Consolatis** [comment]
Should be fixed by
- #433
