### ISSUE TITLE
some windows open in sfwbar's exclusive zone

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1221]
Some windows (mostly of non-gtk X apps--e.g., `feh`) open at the very top of the screen. I use `sfwbar` and prefer to have the bar at the top of the screen. So current options are a) to have the bar at top layer, which results in part of window being obscured (functionally undesirable), or b) to have the bar at bottom layer, which results in part of the bar being obscured (cosmetically undesirable).

For now I'm going with option "b" which seems less bad. This is what it looks like: [screenshot](https://gnuser.ddns.net/public/screenshot001.jpg).

Is there anything you guys can do for `labwc` to interpret layer shell exclusive zones more strictly? Ideally the user wouldn't have to care whether the bar is bottom layer or top layer because windows would stay out of the bar's exclusive zone.

**Comment by Consolatis** [comment]
Could we somehow map `output->usable_area` to xwayland @jlindgren90 ?
Similar to strut partial but the other way around.

**Comment by jlindgren90** [comment]
See #1204 :)

**Comment by jlindgren90** [comment]
If needed, we could also override the window's requested position not to overlap panels. I've considered improving our onscreen/offscreen checks in the past but have not done anything about it yet.

**Comment by Consolatis** [comment]
> See #1204 :)

Heh, right. Completely forgot about that :)

> If needed, we could also override the window's requested position not to overlap panels.

That might be a good option until we track wlroots 0.17 with master.

**Comment by jlindgren90** [comment]
Is this issue specific to `sfwbar` or does it occur with `waybar` as well? I tried `waybar` (at the top of the screen) and `feh` seemed to be positioned correctly, below (not overlapping) the panel. Are there other applications besides `feh` that show the issue?

**Comment by Consolatis** [comment]
sfwbar or waybar shouldn't make a difference as long as they use the exclusive zone feature of the layershell protocol.
E.g. if a maximized window is not below / above the panel (in z-order) it should be fine as a reproducer.

**Comment by bdantas** [comment]
> Is this issue specific to `sfwbar` or does it occur with `waybar` as well?
 
I have not tested `waybar`. In case it matters, `feh` is being launched from a

**Comment by johanmalm** [comment]
<margin top="" bottom="" left="" right="" output="" />

Specify the number of pixels to reserve at the edges of an output. New, maximized and tiled windows will not be placed in these areas.

**Comment by Consolatis** [comment]
> <margin top="" bottom="" left="" right="" output="" />

Isn't `<margin>` handled basically the same as the layershell exclusive zone (as in: it updates `output->usable_area`)?

**Comment by johanmalm** [comment]
> > `<margin top="" bottom="" left="" right="" output="" />`
> 
> Isn't `<margin>` handled basically the same as the layershell exclusive zone (as in: it updates `output->usable_area`)?

Oh, yeah. Good point. Ignore my suggestion.

You could use a window rule with regions / move / resize.

Or just use a wayland client.

**Comment by jlindgren90** [comment]
I can reproduce this after poking at it a little more, but only if I run `feh --geometry 640x460+0+0`. Without the `--geometry` parameter the positioning is fine.

**Comment by bdantas** [comment]
> I can reproduce this after poking at it a little more, but only if I run `feh --geometry 640x460+0+0`. Without the `--geometry` parameter the positioning is fine.
 
Interesting discovery. I can confirm. I forgot that my `feh` is a wrapper script that specifies the window size that I like using `--geometry` flag. If I remove the flag, the window does not encroach in the area of the bar and there is no need for the region + window rule workaround.

**Comment by jlindgren90** [comment]
I think our code still needs some fixes. For example the top_left_boundary_check() function in xwayland.c is supposed to handle this situation, but doesn't take into account the usable area and uses a hard-coded corner of 0,0 instead.

Let's leave this issue open for now. I'll work on a fix later on.
