### ISSUE TITLE
application window not brought into focus when file opened in new tab

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1222]
Some applications such as `geany` create a new window with first opened document, but new tab in existing window when subsequent documents are opened. I think it relies on `dbus` to accomplish this.
 
When running in `labwc`, I'm finding that `geany` gets focus (as expected) when a new window is created with first opened document. However, when I open a second document, `geany` does not get focus. This is unexpected. In X, anytime a new document is opened in `geany` the application gets focus, even if the document is being opened in a new tab of existing window.

Is this a bug in `labwc`, a missing `labwc` configuration option, or a bug in my understanding? :) 

EDIT: I already tried adding this to `~/.config/labwc/rc.xml`:
```
  <focus>
	<raiseOnFocus>yes</raiseOnFocus>
  </focus>
```
But it didn't help. I don't think the issue is that `geany` isn't being raised. Based on what I'm observing on swfbar, I think the issue is that the application is not getting focus when second and subsequent documents are opened.

**Comment by stefonarch** [comment]
Same can be seen with featherpad  when "Open always in separate windows" is unchecked ("single instance").

**Comment by milisarge** [comment]
If we talk at `geany` specific, only workaround is selecting any tabs from `geany` then it works as expected (tested with 0.6.4/5). Can you test this workaround @bdantas ?

**Comment by bdantas** [comment]
@milisarge - I'd love to test the workaround, but I'm afraid I don't understand it. Can you please provide more detail?

**Comment by milisarge** [comment]
just select some of opened tabs at geany, then try to open a new document, it should focus then. (detailed video https://0x0.st/HyC7.mp4)

**Comment by bdantas** [comment]
Thanks for the video. The workaround doesn't work for me, unfortunately. I opened several documents, then focused geany and clicked on a tab. When I opened another document from my file manager, geany did not focus.

**Comment by Consolatis** [comment]
To make this work at all some conditions have to be satisfied:
- the calling application (usually a file manager of sorts) has to request a proper activation token via the xdg-activation protocol
  - "proper" refers to the calling application supplying an own surface which has mouse- or keyboard focus at the time the token is requested. This is done to prevent random applications stealing focus.
- the called application has to receive the token (usually done via some dbus magic or by using a specific env var)
- the called application finally has to reqeust focus from the compositor using the xdg-activation protocol and the received token
- the token used must be no older than 30 seconds (as far as I remember)

If one of these steps fail the request will not be allowed. In this case, if it works using a different file manager its likely that the file manager in use either doesn't support the xdg-activation protocol properly or the token isn't ending up in the target application.

This can be debugged when starting labwc with the `-d` flag and looking out for:
- "Not activating surface"
- "Denying focus request"
- "Ignoring focus request"
- "Activating surface" for when labwc allows the request

If none of these messages show up in the log geany didn't request focus.

Another very similar issue was raised via IRC before which also involves geany (strangely enough): in that case the request was accepted by labwc ("Activation surface") but geany didn't actually get raised and focused. That feels like a bug but I am not sure how that can happen.

---

Personally, I am using a work around for applications that don't support the xdg-activation protocol, see https://labwc.github.io/tips-and-tricks.html#run-or-raise for a more generic solution (that one doesn't support arguments though).
Stored at `~/bin/pluma` and made executable:
```bash
#!/bin/bash
/usr/bin/pluma "$@"
wlrctl window focus pluma
```

**Comment by bdantas** [comment]
Hi Consolatis. That's a very nice workaround, thank you. I'll be using it for geany.
 
Another workaround is to just have separate windows for separate documents, using a wrapper script like this:
```
#!/bin/sh
exec /usr/bin/geany --new-instance "$@"
```
But that particular flag is obviously geany-specific. 
 
Some applications rely on dbus to open multiple documents in a single instance of the software (i.e., in same window, under same PID). I experimented some more and it turns out that geany does not fall into that category. But if a different application `foo` does fall into that category and does not have a flag like `--new-instance`, a hacky way to force different documents to open in different windows is this:
```
#!/bin/sh
DBUS_SESSION_BUS_ADDRESS=none foo "$@"
```

**Comment by Consolatis** [comment]
I've removed this issue from the 0.6.6 milestone. I think the reason this specific issue occurs is either because
- the file manager used to open the new file is not supporting the xdg-activation protocol properly
- or the target application (geany) doesn't support it properly and may send subsurfaces for activation rather than its main xdg surface
- or there is a missing communication link between the two, e.g. not using the same dbus session or similar

Or really any mix of the above.
I will close this issue for now, if there are further information available feel free to comment though.
