### ISSUE TITLE
Keybindings for multimedia keys are no longer active

### ISSUE THREAD

**Issue by jp7677** [labwc/labwc#1223]
Hi there,

I'm using keybindings like this for the multimedia keys (the ones on the function keys) of my keyboard in my configuration: 

```
<keybind key="XF86LaunchA"><action name="ToggleFullscreen" /></keybind>
<keybind key="XF86LaunchB"><action name="Execute" command="fuzzel"/></keybind>
```

Unfortunately those bindings, this also includes volume and playback keys, do no longer work on master, but are still fine with 0.6.5.

To trigger the first action I need to press `fn`+`f1` for `XF86LaunchA`. I still see events like `XF86LaunchA` in `wev`, but labwc doesn't react anymore. Do I need to change my keybindings somehow to reactive them?

In case this is a regression,  running `git bisect` I could isolate this to this commit (assuming that I didn't screw up when bisecting and this isn't a false positive):

```
git bisect log
...
# first bad commit: [e77330bc3fe733412e92f4e90d797d31ee6c5652] keyboard: make keybind match stricter

commit e77330bc3fe733412e92f4e90d797d31ee6c5652
Author: Johan Malm <jgm323@gmail.com>
Date:   Tue Sep 26 17:51:54 2023 +0100

    keyboard: make keybind match stricter
    
    ...and avoid failing to send release events to clients for any keys that were
    not absorbed by a keybind.
    
    Do not match keybinds if there are other non-modifier keys (not part of any
    defined bind) pressed at the same time.
    
    Only store non-modifier keycodes in the key-state.c 'pressed' array.
    This makes the call to wlr_seat_keyboard_notify_enter() in seat_focus()
    consistent with the equivalent in sway (in seat_keyboard_notify_enter()).
    
    Fixes: issue #1091

```

Thanks for all your work, I really like labwc!

**Comment by Consolatis** [comment]
Thank you for pointing out this regression!
A fix for this issue need some more discussions on the way forward in regards to our keybind handling.

**Comment by Consolatis** [comment]
Should be fixed on latest master. If there are still keybind related issues for multimedia keys feel free to reopen / comment.
