### ISSUE TITLE
way to toggle touchpad using rc.xml?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1228]
My machine is a ThinkPad laptop. I never use touchpad (only trackpoint) but my wife (who sometimes takes the laptop from me while I'm using it haha) only uses the touchpad. So I need a way to toggle the touchpad on and off (both in wayland and in Xwayland) while the laptop is running.

For now I'm using this effective but ugly hack, where toggle in "off" position does not actually disable the touchpad but runs `evtest` in the background to eat all its output:

```
#!/bin/sh

device_path=$(sudo libinput list-devices | grep -A 1 -i touchpad | grep -o '/dev/input/.*$') # e.g., /dev/input/event4

if pgrep evtest >/dev/null; then
    sudo pkill evtest
    notify-send "touchpad-toggler" "touchpad enabled" &
else
    sudo evtest --grab "$device_path" >/dev/null 2>&1 &
    notify-send "touchpad-toggler" "touchpad disabled" &
fi
```
Can you think of a more elegant solution, that actually turns the touchpad on and off? I found some libinput-related configuration options [here](https://www.mankier.com/5/labwc-config#Configuration-Libinput) but none of them seem to be related to turning input devices on and off.
 
I don't want to cause any more work for anyone. Just wondering if there is an obvious, elegant solution that I'm missing because I'm a wayland/labwc noob.

**Comment by dglava** [comment]
I had the same question and was told that this https://github.com/labwc/labwc/pull/961 will implement/allow that feature.

**Comment by bdantas** [comment]
> #961 will implement/allow that feature.
 
@dglava - Nice! Thank you for sharing.
