### ISSUE TITLE
wtype cannot send named keys to yad

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1233]
I am a keyboard guy and am figuring out how to automate various things in my shiny new labwc box. 

When I create a yad text entry dialog with `yad --entry` I'm finding that `wtype "hello world"` is able to send the text to the entry box but `wtype -P Home` is not able to send the Home key.

I cannot reproduce the issue in other applications running in Xwayland (i.e., other applications are able to receive both strings and named keys from `wtype`).

Can anyone reproduce this problem? Is it a bug in yad or labwc?

P.S. Can anyone recommend a wayland applet similar to `yad` that I can use to create GUI text entry dialogs from shell scripts? Finding such an applet would be a better solution that figuring out where this bug is.

**Comment by Consolatis** [comment]
You might need to release the key again via lowercase `-p`.

**Comment by bdantas** [comment]
I'm not sure what you mean, but I tried these with no luck:
```
$ sleep 5; wtype -P Home -p
Missing argument to -p
$ sleep 5; wtype -P Home -p Home # didn't work
$ sleep 5; wtype -p Home # didn't work
```

**Comment by bdantas** [comment]
I tried this and observed the yad dialog very carefully:
```
$ sleep 5; wtype -P Home -s 500 -p Home
```
The blinking cursor does stop blinking for a brief moment but does not move. _Something_ is happening but Home key is not being sent correctly.

**Comment by bdantas** [comment]
Yes, `Home` key works in other Xwayland applications, including when sent through `wtype`.

`xev` identifies it correctly as press and release. Both when I physically press it as well as when I simulate pressing it with `wtype -P Home -s 500 -p Home`.

**Comment by bdantas** [comment]
Here is what `xev` sees when I send `wtype -P Home -s 500 -p Home` to the Event Tester window:
```
KeyPress event, serial 179, synthetic NO, window 0xa00001,
    root 0x194, subw 0x0, time 445339, (59,0), root:(961,79),
    state 0x10, keycode 9 (keysym 0xff50, Home), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 183, synthetic NO, window 0xa00001,
    root 0x194, subw 0x0, time 445831, (59,0), root:(961,79),
    state 0x10, keycode 9 (keysym 0xff50, Home), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by Consolatis** [comment]
Strange, not sure what is going on then. Maybe somebody else has an idea, including a wayland native replacement for `yad`

**Comment by bdantas** [comment]
FWIW I tried a different named key (`End`) and result was the same. I also tested `zenity` and, interestingly, it has the same issue as `yad` (i.e., it accepts strings from `wtype` but not named keys).

**Comment by Consolatis** [comment]
If you want to rule out `wtype` itself as the cause (although based on the events you see via `xev` it seems fine) you could try [some python example](https://github.com/Consolatis/wl_framework/blob/main/examples/wl_virtual_keyboard.py) which happens to send `home` and `end` as well.

**Comment by bdantas** [comment]
Hi Consolatis. Yes, I'd like to exclude `wtype` being the culprit.

I'm trying to send keyboard output using your python script + module, but it doesn't seem to like me:

```
$ ./wl_virtual_keyboard.py --delay 1 "hello world"

Warning: This example will inject key events.
It has to be called with a --delay argument like

"./wl_virtual_keyboard.py --delay 5"

to provide enough time to switch to a text editor like nano.
```

**Comment by Consolatis** [comment]
In the root directory of the repo: `./run_example examples/wl_virtual_keyboard.py --delay 5`
Should likely fix that dont-shoot-yourself-in-the-foot message :)

**Comment by bdantas** [comment]
Still no luck when I do it that way:
```
bruno@x230:/mnt/data/Downloads/wl_framework$ ./run_example examples/wl_virtual_k
eyboard.py --delay 5 "hello world"

Warning: This example will inject key events.
It has to be called with a --delay argument like

"examples/wl_virtual_keyboard.py --delay 5"

to provide enough time to switch to a text editor like nano.
```
Oh, well. Don't worry about this issue. It seems too minute.
 
I'll find some workaround for yad/zenity. If I find a particularly good replacement I'll mention it here.

**Comment by Consolatis** [comment]
The issue is the `hello world` argument, the example doesn't allow to supply any text via argument and has to be modified to make it do something different. It's really just a showcase of the Python API for the virtual keyboard protocol.

**Comment by bdantas** [comment]
I removed "hello world" and got an error (something about `fd` missing from module `os`). So I installed python3.9, changed the script's shebang accordingly, and ran with only "--delay 5" and now it finally works :) I'll try to test yad.

**Comment by bdantas** [comment]
I removed all the example output from your showcase script except for `self.keyboard.send_key("home")`. The simulated keypress works everywhere except yad.

**Comment by bdantas** [comment]
wtype can send both strings and named keys to `dmenu`, which will do very nicely for my application. Cheers!
