### ISSUE TITLE
tooltips sometimes show through windows

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1234]
This is just cosmetic, but I wanted to let you guys know because it happens often: If tooltip of application A is showing when application B is launched, application A's tooltip continues to display on application B's window.

Here is an example from today--I was checking my email in Thunderbird then launched my web browser. Cursor happened to be over Thunderbird's "Write" button when web browser was launched. In this screenshot you can see Thunderbird's "Create a new message" tooltip in the middle of nowhere in web browser's window:
![screenshot001](https://github.com/labwc/labwc/assets/5084088/0449dd19-3ceb-4ee4-9431-85c39447d280)
When this happens it can sometimes be difficult to get the tooltip to stop showing.

EDIT: The expected behavior, of course, is to stop showing tooltips of windows that are behind the focused window. I'm sorry all I can do is report issues--I wish I could help fix them, but windowing and graphics are not my forte at all :cry:

**Comment by Consolatis** [comment]
Hm.. Are Thunderbird / brave running wayland native or via xwayland? (`[xdg-shell]` or `[xwayland]` in `A-Tab` dialog)

**Comment by bdantas** [comment]
Thunderbird is in xwayland. Brave is wayland native (`[xdg-shell]` in `A-Tab` dialog).

The question about `A-Tab` is tricky to answer because it depends on scenario:
 
Normal human being scenario: If Thunderbird is already showing tooltip, as soon as I press `Alt` the tooltip goes away, so when I add `Tab` to make `A-Tab`, tooltip is already gone when focus goes to Brave. 
 
Nerd-trying-to-create-problems scenario: If I press `Alt`, then move cursor over a Thunderbird button to see a tooltip, then add `Tab` to make `A-Tab` and switch to Brave, Thunderbird's tooltip continues to show on the Brave window.

**Comment by bdantas** [comment]
Congratulations on 0.6.6. It is awesome! This is the only bug I can find in it, after extensive testing.
 
Unfortunately, because I launch all my applications with keyboard shortcuts (which means the mouse can be in any random place on the screen when applications are launched), I experience this bug several times an hour.

**Comment by Consolatis** [comment]
I think the main issue is that Thunderbird (via xwayland) doesn't close its popup on (mouse) focus loss.
Can you also reproduce the issue with two xwayland applications (e.g. the new window is also a xwayland window)?

**Comment by bdantas** [comment]
No. When a new xwayland application is launched, tooltips of other xwayland applications disappear.

This issue only happens when a wayland application (e.g., brave or foot) is launched while an xwayland application is showing a tooltip.

**Comment by Consolatis** [comment]
Right, it seems that xwayland isn't notified about the mouse focus loss. Any ideas @jlindgren90 ?

**Comment by jlindgren90** [comment]
I don't really know much about "mouse focus". It may be simply that to XWayland, the native Wayland view doesn't exist and therefore the topmost XWayland (underneath the native Wayland one) still has "mouse focus".

There a few problems that crop up in XWayland that I simply don't know how (or if it's possible) to solve; this might be one of them.

**Comment by Consolatis** [comment]
Maybe its actually keyboard focus rather than mouse focus? I am not sure if xwayland even has the concept of mouse focus, other than wayland native. If the tooltip is gone when spawning a new xwayland window that could indicate that xwayland as a whole isn't notified about the keyboard focus loss. Or it could indicate that there is nothing like a keyboard focus loss either in X11 and instead giving focus to another X11 window is used as the trigger to close own popups. And as we don't give keyboard focus to another xwayland window, Thunderbird (in this case) still thinks it owns they keyboard and doesn't destroy its tooltip.

We could obviously simply hide all unmanaged surfaces whenever we switch to a wayland native window but I feel that causes further issues as users may actually want to have some specific unmanaged surfaces around.

**Comment by jlindgren90** [comment]
Thunderbird seems to show tooltips regardless of whether it has keyboard focus (it's the same under Openbox).

**Comment by bdantas** [comment]
> Thunderbird seems to show tooltips regardless of whether it has keyboard focus (it's the same under Openbox).
 
I can confirm that. Same with Caja.

**Comment by Consolatis** [comment]
Hm.. random thought: could we maybe "park" the xwayland cursor somewhere (like `-10|-10`) when switching away from xwayland?

**Comment by jlindgren90** [comment]
Incidentally, Firefox had issues with stuck tooltips on OS X for years, and the fix was apparently to hide them when losing keyboard focus. Maybe Thunderbird needs to do similar.
https://arstechnica.com/gadgets/2023/10/22-year-old-firefox-tooltip-bug-fixed-in-a-few-lines-offering-hope-to-us-all/

**Comment by bdantas** [comment]
> Hm.. random thought: could we maybe "park" the xwayland cursor somewhere (like `-10|-10`) when switching away from xwayland?
 
What a clever idea! That would definitely solve the problem.

**Comment by bdantas** [comment]
> hide them when losing keyboard focus.
 
That would also solve the problem. But again, it's not just Thunderbird that's doing this. It's every xwayland application I've tested.

**Comment by jlindgren90** [comment]
> Hm.. random thought: could we maybe "park" the xwayland cursor somewhere (like `-10|-10`) when switching away from xwayland?

This could potentially work. Not sure of -10,-10 is safe (there could be a view there) or if something like -32768,-32768 would be better.

If we could send a synthetic press/release event as well (to the root window) it could also solve the issues of XWayland popup menus remaining open.

**Comment by johanmalm** [comment]
> If we could send a synthetic press/release event as well (to the root window) it could also solve the issues of XWayland popup menus remaining open.

Yes - that's what I've had in mind. I'm not sure if I've seen that solution somewhere, or if I've just imagined it.

**Comment by johanmalm** [comment]
I can't reproduce it - so can't really test. Would it work to do something like calling `xwm_set_net_active_window(xwm, XCB_WINDOW_NONE);` on focus change?

Or possibly `s/XCB_WINDOW_NONE/xwm->screen->root/`?

https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/xwayland/xwm.c?ref_type=heads#L2235

**Comment by Consolatis** [comment]
All of `xwm_` is private.

**Comment by jlindgren90** [comment]
> Would it work to do something like calling `xwm_set_net_active_window(xwm, XCB_WINDOW_NONE);` on focus change?

The public API for this is to call `wlr_xwayland_surface_activate(xsurface, false)` for the previously focused surface. We already do that (via `view_set_activated`).

**Comment by johanmalm** [comment]
Okay... maybe if we focus the root-window then?

Have just installed caja - but can't reproduce with that either... my computer must be magic :smile:

**Comment by bdantas** [comment]
@johanmalm - Thank you for trying to reproduce the issue. Your computer must be more magical than mine. Given that you are not suffering from this pesky bug, I'm all the more grateful for you trying to fix it.
 
Prior to opening/focusing a wayland window, I believe any of these behaviors would solve the issue:
- Parking the xwayland cursor
- Hiding active tooltips
- Sending a keystroke (e.g., Alt_L)

I'd like to test the idea of focusing the root-window, but that's more tricky to test without confounders (other behaviors that, by themselves, make the tooltip disappear--such as moving the mouse). Is there a shell command that I could use to test this (somethine like  `sleep 5; labwc focus-root`)?

**Comment by jlindgren90** [comment]
Correct me if I'm wrong but I don't think "focus" as a concept makes sense for the X11 root window. Or thought of another way, it is always focused: it must receive all input events because otherwise nothing would (all other windows are children of the root window).

**Comment by bdantas** [comment]
I think part of the issue is that xwayland tooltips are "always on top". Here is a little video to illustrate this. In video, the expected behavior is for the focused `foot` terminal to be higher on the window stack than the tooltip of the unfocused xwayland window.

https://github.com/labwc/labwc/assets/5084088/0ad3687e-73b7-4de9-bbc0-0a865c2b72bf

**Comment by bdantas** [comment]
I did the same experiment on Devuan running MATE in a pure X environment. In this environment, tooltip also seems to be "always on top" (same as in labwc), so I guess that's expected behavior. The difference is that in the X environment, the tooltip only appears for as long as the mouse pointer is directly above the associated button--see video below.

https://github.com/labwc/labwc/assets/5084088/3d645689-1456-4414-a259-356722b6371b

I hope the videos are helpful.

**Comment by jlindgren90** [comment]
I can't seem to reproduce it.

**Comment by bdantas** [comment]
@jlindgren90 - Thank you very much for trying. In that case, I assume it's something specific to running xwayland in Tiny Core Linux. I'll explore that possibility and will update you guys if I make any progress.

**Comment by bdantas** [comment]
Completely disabling all tooltips in xwayland windows would be an attractive option for me. Is there a way to issue a total prohibition, or does it have to be done piecemeal per toolkit (gtk3, gtk2, qt5, etc)?

**Comment by 01micko** [comment]
I'm running puppy-linux, labwc-0.6.6 and can't reproduce with ;

1. `mhwaveedit` is running (gtk2) and trying to launch `lxterminal` from keyboard short cut (gtk3) 
2. `mhwaveedit` running and tried launching `geany` (gtk3) from lxterminal like so ; `sleep 5;  geany`

In first instance as soon as I tap a key the tooltip is gone. Second, as soon as `geany` opens tooltip is gone.

@bdantas - random thought, config issue?

**Comment by johanmalm** [comment]
> I'm running puppy-linux, labwc-0.6.6 and can't reproduce with ;
> 
> 1. `mhwaveedit` is running (gtk2) and trying to launch `lxterminal` from keyboard short cut (gtk3)
> 2. `mhwaveedit` running and tried launching `geany` (gtk3) from lxterminal like so ; `sleep 5;  geany`
> 
> In first instance as soon as I tap a key the tooltip is gone. Second, as soon as `geany` opens tooltip is gone.
> 
> @bdantas - random thought, config issue?

@01micko I did/found the same. Used mate (xwayland) and foot (wayland)

**Comment by bdantas** [comment]
@01micko and @johanmalm - Thank you for trying to reproduce. I'm glad it's not a labwc issue. I will turn focus of my investigation to distro-specific issues such as version of supporting packages (e.g., xwayland, gtk3).

In the meantime, I can immediately make my situation more comfortable by disabling tooltips in the two offending applications:
- email client: In Thunderbird's config editor, setting `browser.chrome.toolbar_tips` to `false` disables all tooltips
- file manager: I will switch from caja to my other favorite file manager, xfe, which can be compiled without tooltips (`#define TOOLTIP_TIME 0` in xfedefs.h).

Thanks again for all your help. Happy hacking!
