### ISSUE TITLE
Regression: windowrule and margin race

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1235]
With a commit after a62cd9fe51209843c654c83db46f89d8bb3f4903 was apparently introduced an regression:
On session start `lxqt-session` starts its components and autostarts some apps, which get placed according some windowrules.  For  the panel:

```
<margin top="38"/>
....
    <windowRule identifier="lxqt-panel" skipTaskBar="yes" skipWindowSwitcher="yes" matchOnce="true">
      <action name="ToggleAlwaysOnBottom"/>
      <action name="MoveTo" x="0" y="0"/>
    </windowRule>
```
It was always working fine at session start and  now on both machines the panel first opens  in correct position at 0 0 and after a second or so it goes below the margin of 38px. When I restart the panel it turns back to 0 0 as normal.

I could do some bisect but maybe someone has an idea what causes this now.

**Comment by stefonarch** [comment]
More narrow: happens after 984aeb0b0bf8858217528342baab0b28889fa699

**Comment by Consolatis** [comment]
Likely related to 57075ce864ff39ae812c21fe78c8575ee571178d
- #1225

For usual applications not overlapping the panel makes sense. However for a panel itself, obviously not that much.
Thoughts on how we could deal with this situation and allow some applications to get positioned within the margin / usable area?

@jlindgren90 @johanmalm

**Comment by jlindgren90** [comment]
Hmm. Probably at a minimum, windows that set _NET_WM_STRUT_PARTIAL should not be moved based on their own strut. That should fix the immediate issue.

More generally this seems like yet another area where _NET_WM_WINDOW_TYPE would be helpful.

**Comment by jlindgren90** [comment]
> Hmm. Probably at a minimum, windows that set _NET_WM_STRUT_PARTIAL should not be moved based on their own strut. That should fix the immediate issue.

Seeing now that a margin was explicitly set. So _STRUT_PARTIAL not really relevant here.

Is there any windowRule to ignore margins?

**Comment by johanmalm** [comment]
Just played with this. Floating windows now move when usable area is changed (e.g. when starting `waybar`). We used to only adjust tiled/maximized/etc.

**Comment by jlindgren90** [comment]
Maybe the presence of a MoveTo rule ought to override that behavior.

**Comment by johanmalm** [comment]
Openbox has a `<application><position force="yes">` option.
But I think we ought to start with whether we actually want floating windows to move with changes in usable-area. We had previously taken a view that they shouldn't. IIRC sway moves them so that the offset into the usable area remains the same. Our current behaviour is to clamp/push the floating window if you know what I mean.

**Comment by johanmalm** [comment]
Although we only do it from the top! A panel at the bottom doesn't move the window

**Comment by johanmalm** [comment]
I think my preference is to not move floating window with a change in usable area, but don't feel strongly.

**Comment by johanmalm** [comment]
I've just check on Openbox. Maximized windows adjust when _NET_WM_STRUCT_PARTIAL changes, but floating windows do not (so consistent with how we used to do it).

**Comment by jlindgren90** [comment]
I'm fine with going back to that. Do we want any special case for an initial position of 0x0? I seem to recall you saying Openbox had something like that.

**Comment by johanmalm** [comment]
Just thinking... :smile:
Feeling a tired + indecisive this evening.

**Comment by Consolatis** [comment]
> I'm fine with going back to that. Do we want any special case for an initial position of 0x0? I seem to recall you saying Openbox had something like that.

My 2 cents: IHMO for most use cases it would make sense to adjust a initial position of 0x0 until we can reflect the usable_area in X11. Maybe with a comment added that makes it clear that it is a workaround because properly solving it requires wlroots 0.17.

However, I think that would also break the margin for the panel again so we may indeed need a window rule property which says ignore usable area / margin for the 0x0 case.

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc/assets/6955353/d5b664de-898e-4b1a-afde-7597be6cb118

I think I quite like this.

I vote for just keeping it and creating a window-rule like `<position x="" y="">` which ignores attempt to move it. I think it's better to keep `MoveTo` as it is.

And - apologies for not taking in the full extent of PR #1225. I only clocked the initial-positioning side of it.

**Comment by johanmalm** [comment]
I get "file corrupt" on mp4 above, so trying webm here of same recording:

[recording.webm](https://github.com/labwc/labwc/assets/6955353/cdd082df-193b-4039-b587-7d046fafade8)

**Comment by johanmalm** [comment]
How about we leave #1225 as is, but add a window-rules (such as PR #1236)

@stefonarch Thanks very much for catching/reporting this regression. Any testing with #1236 would be appreciated. Just add `ignoreUsableArea="yes"` to the window rule. I tested it with `pcmanfm-qt --desktop` (which works fine with it), but haven't tried with `lxqt-panel`

**Comment by Consolatis** [comment]
> How about we leave #1225 as is, but add a window-rules (such as PR #1236)

Fine by me.

**Comment by stefonarch** [comment]
Can confirm that the rule works fine for `lxqt-panel`, thanks. Hoping things get not overcomplicated though.

**Comment by jlindgren90** [comment]
In theory, the long-term fix here should be for lxqt-panel to support layer-shell; then the window rules should not be necessary. But last I knew that still requires changes/fixes in Qt.

**Comment by stefonarch** [comment]
That's the situation, after migration to Qt6 is done hopefully this can be achieved.

**Comment by Consolatis** [comment]
Fixed by adding a new window rule property [fixedPosition](https://labwc.github.io/labwc-config.5.html#entry_windowrules_windowrule_fixedposition=) that additionally prevents interactive resizing.

**Comment by stefonarch** [comment]
Thanks!
