### ISSUE TITLE
Shifted keystrokes are delayed when typing quickly (regression 0.6.5 -> master)

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#1238]
In master (368ede74602e as of writing), Shift+ or Ctrl+ keystrokes are noticeable delayed when typing quickly. I'm not talking about keybindings, but basic keystrokes like Shift-A (for a capital A) or Ctrl+V (paste). It's a little hard to quantify but very noticeable when doing a significant amount of typing, because there is a small delay with every capital letter and most punctuation.

I think this started happening in the last week or two. The issue is definitely not present in 0.6.5.

**Comment by jlindgren90** [comment]
`git bisect` points to 984aeb0b0bf8858217528342baab0b28889fa699 as the first bad commit, from:

- #1077

**Comment by Consolatis** [comment]
*Might* be related to
```c
wlr_seat_set_keyboard(seat->seat, wlr_keyboard);
```

Just guessing though.

**Comment by johanmalm** [comment]
I can reproduce.

Have rebased (locally) `unbound-key-release` onto master, but no difference.

**Comment by jlindgren90** [comment]
I can confirm it's related to the `wlr_seat_set_keyboard` call in `keyboard_modifiers_notify`. Commenting out that line makes the delay disappear.

Also, pressing even Shift on its own causes the delay -- it doesn't have to be a combination.

**Comment by johanmalm** [comment]
Have just confirmed the same.
Shall I do a patch?
