### ISSUE TITLE
[Feature Request] Cursors for moving and resizing

### ISSUE THREAD

**Issue by skyne98** [labwc/labwc#124]
Hey there!

Probably a fairly simple thing to do, but I think it would make the experience feel much more polished, is to display a proper “type” of cursors whenever you drag around or resize a window.

In theory, this would mean to somehow ignore the cursor requested by the application at the moment of dragging or resizing.

Those should probably be (equivalents from CSS):
* for movement: `move` or ![example](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/move.gif)
* for resizing, depending on the corner/side: `n-resize` or ![example](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/n-resize.gif), `ne-resize` or ![example](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor/ne-resize.gif)...etc

**Comment by johanmalm** [comment]
Thanks. I’ll take this one on

**Comment by skyne98** [comment]
Amazing, will be anticipating impatiently for the news!

**Comment by johanmalm** [comment]
https://user-images.githubusercontent.com/6955353/143786732-42867e4c-7dc6-4745-bae5-eeb66ffe4795.mp4

Setting xcursor to "move", etc in `interactive.c` was easy, but had to add a `cursor_rebase()` to revert at the end of move/resize. Will commit/push soon.

`ne-resize` et al are set by `https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/xcursor/wlr_xcursor.c#L324`

**Comment by skyne98** [comment]
Looks like the result is super worth it!

**Comment by johanmalm** [comment]
Done, I think.
Will close for now.

**Comment by johanmalm** [comment]
Should it be "move" or "grab"? Sway uses "grab". Any ideas?

**Comment by Joshua-Ashton** [comment]
Could make it configurable

**Comment by johanmalm** [comment]
Yes. Good idea.

**Comment by skyne98** [comment]
I think grab would be a nice default, it feels "nicer" in some strange way, more human

**Comment by johanmalm** [comment]
Changed to "grab"
