### ISSUE TITLE
XKB rules don't apply to notebook keyboard alone

### ISSUE THREAD

**Issue by txgk** [labwc/labwc#1246]
Hi, thanks for this very nice project. I like using it a lot :)

But during my transition from sway I realized that XKB rules don't work very well.

Here's the case: back in sway I used to have these settings:

```
input type:keyboard {
	xkb_options caps:swapescape,grp:alt_shift_toggle
	xkb_layout us,ru
}
```

All these do is just add Russian keyboard layout and swap Caps Lock key with Escape key.

I found a way to add this functionality in labwc by adding these lines to `environment` file:

```
XKB_DEFAULT_OPTIONS=caps:swapescape,grp:alt_shift_toggle
XKB_DEFAULT_LAYOUT=us,ru
```

And it worked fine until I tried to use my notebook keyboard alone.

You see, when at home, I use external keyboard instead of my notebook keyboard because it's more convenient for me to type that way. In this case labwc handles custom XKB rules specified in `environment` file without a problem.

But I often have to take my notebook to places and I just use notebook keyboard there and this is where the issue arises. When I start labwc without external keyboard attached, it doesn't apply custom XKB rules specified in `environment` file. I can see them in my environment (`env` command lists them), but they are not working (neither Russian layout nor CapsLock-Escape swap).

If there's more info needed from me to fix this, I'd be glad to provide it :^)

**Comment by johanmalm** [comment]
Hi there and welcome.
I'm not sure why it doesn't work with the builtin keyboard.
I have a laptop and sometimes use an external keyboard with it. It works fine - albeit I have slightly different settings to you.
I suggest the following
Run with `labwc 2> my_log.txt` to see if xkb produces any errors. If there is anything, post here.
Try with something simpler, for example `XKB_DEFAULT_LAYOUT=ru` to see if that works. If it does, gradually build up until it breaks.
Are you running from tty, or nested under wayland/X11, or with emulation (qemu or similar)?

**Comment by txgk** [comment]
I found out more about the problem.

1. It also happens in sway (sorry, I didn't test it properly before).
2. It happens only when IME program like fcitx5 is running. It somehow overrides XKB rules for xwayland clients and the only way to repair them is to start Wayland-native program, type something there and switch back to xwayland client - then XKB rules for it get restored somehow.

I could just add Russian layout to my IME program and get rid of XKB rules altogether, but I desperately need `caps:swapescape` option.

Do you think I should go to fcitx5 issue tracker instead?
