### ISSUE TITLE
CapsLock: is there a command to toggle -or- file with status?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1248]
Hi Consolatis. My ThinkPad X230 does not have an LED to show CapsLock status. In my old X with fluxbox setup, I rigged things so that pressing CapsLock would run a shell script that would toggle the CapsLock state and also add/remove an icon from taskbar.
 
I'd like to implement a similar solution in labwc + sfwbar. To do this, I need either of these:
 
a. shell command that toggles CapsLock state in labwc
b. a file to parse to determine current CapsLock state
 
Do you know of a way to achieve either a) or b)?

**Comment by johanmalm** [comment]
I don't know of a way to do either, short of crafting a custom IPC.

I tried with `wtype -k Caps_Lock` but doesn't seem to do it.



https://github.com/labwc/labwc/issues/637

**Comment by bdantas** [comment]
Hi, johanmalm. Another strategy would be for a keybind rule in `~/.config/labwc/rc.xml` that binds CapsLock to a script simply toggles an icon, and for labwc to "replay" the key so that it can do its normal thing (i.e., toggling sticky Shift). 
 
Under X I'd use `sxhkd` which had a handy tilde modifier that would allow this kind of replay. Does labwc's keybindings support this? Maybe wayland doesn't work this way?
 
Thanks for the tip, Flrian. `ydotool` is not available in my distro's repo but I'll look at it and see if I can compile it and give it a shot.

**Comment by johanmalm** [comment]
> Another strategy would be for a keybind rule in `~/.config/labwc/rc.xml` that binds CapsLock to a script that simply toggles an icon, and for labwc to "replay" the key so that it can do its normal thing (i.e., toggling sticky Shift).

We could consider adding an option for keybinds to be 'absorbed', i.e. carry out keybind action but still send the key press to the client with focus. I'd prefer a clear use-case for this though because the code is hard enough as it is :smile:

In terms of setting an indicator for caps-lock using a script every time the cap-lock key is pressed, I think is a bad design choice (because you don't know the state, just that it's been toggled). 
 
> Under X I'd use `sxhkd` which had a handy tilde modifier that would allow this kind of replay. Does labwc's keybindings support this? Maybe wayland doesn't work this way?

I used to too. I'm pretty sure that wouldn't work on Wayland. It would be possible to write something similar but it would require root privileges, so again not really a sensible choice for most use-cases.

**Comment by bdantas** [comment]
Hi johanmalm. One of the things I like about my new wayland environment in general and labwc in particular is that things are less complicated. Don't worry about about the idea to 'absorb' the keybinds if it makes part of labwc's code more difficult to maintain.

I tinkered around some more and actually found a simple solution. The kernel is aware of CapsLock state. Even though my laptop doesn't have a CapsLock LED, `cat /sys/class/leds/*capslock/brightness` outputs `1` when CapsLock is on, and `0` when it is off.

I'm going to write an sfwbar widget that runs the `cat` command above every second and makes an icon visible or invisible as appropriate. It's a bit expensive given that I don't use CapsLock very often, but my laptop has more than enough resources to spare.

**Comment by bdantas** [comment]
Just a quick, happy follow-up:
 
> Another strategy would be for a keybind rule in `~/.config/labwc/rc.xml` that binds CapsLock to a script that simply toggles an icon
 
I tried the above approach and was pleasantly suprised that it works. If `capslock-toggler` is a custom script that simply toggles an icon's visibility (e.g., in sfwbar), adding this to `~/.config/labwc/rc.xml` works just fine:
```
	<keybind key="Caps_Lock"><action name="Execute" command="capslock-toggler" /></keybind>
```
I'm surprised that pressing CapsLock not only executes `capslock-toggler` but also changes the CapsLock state without me having to figure out any hack to resend the CapsLock keypress.
