### ISSUE TITLE
how to request window size for a specific application?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1261]
I recently switched to Xfe file manager. Window is too narrow when it launches and Xfe does not have a `--geometry` flag, unfortunately. I need to solve this with labwc, if at all.
 
I tried this in `~/.config/labwc/rc.xml`...
```
  <regions>
 	<region name="xfe-placement" x="20%" y="10%" width="65%" height="80%"></region>
  </regions>

  <windowRules>
	<windowRule identifier="" title="Xfe*"><action name="SnapToRegion" region="xfe-placement" /></windowRule>
  </windowRules>
```
...and Xfe launches at desired size but the moment I move the window to somewhere on the screen, it shrinks to the narrow size.

Is there a way to request window of a specific application to actually be resized when launching (similar to clicking on a corner and manually resizing)?

**Comment by bdantas** [comment]
For the specific case of Xfe, I discovered that size and position parameters can be put in its config file (`~/.config/xfe/xferc`), like so:
```
[OPTIONS]
height=516
width=874
ypos=-593
xpos=-445
auto_save_layout=0
...
```
Even though I'm all set with this, it would still be a nice enhancement to labwc if an application window's size could be configurable via a windowRule. I'm sure some applications that default to a suboptimal window size have neither a `--geometry`-type flag nor the ability to set window size in its config file.

**Comment by Consolatis** [comment]
Right, SnapToRegion is a tiled state, similar to SnapToEdge,  maximized or fullscreen. As soon as an interactive movement is initiated it will restore to the size it was before.

Another use-case for a `MoveResizeTo` or some absolute `ResizeTo`? 
Currently we do have a absolute `MoveTo` but only a relative `ResizeRelative`. A workaround could be to use both actions in the window rule, `ResizeRelative` and `MoveTo`.

CC @johanmalm

**Comment by johanmalm** [comment]
Yes, we should implement `ResizeTo` (scope document 5.23.2)

https://github.com/labwc/labwc-scope#5-window-actions

**Comment by Consolatis** [comment]
In latest master you should now be able to do something like
```xml
  <windowRules>
	<windowRule identifier="" title="Xfe*">
		<action name="ResizeTo" width="800" height="600" />
		<action name="MoveTo" x="200" y="200" />
	</windowRule>
  </windowRules>
```

**Comment by bdantas** [comment]
Very nice! Thank you.

P.S. Switching from X+fluxbox to labwc has made my personal computing much simpler. I used to need fluxbox, sxhkd, devilspie2, and a special script to switch keyboard layouts. Now I can get all of that done with a few simple labwc configuration options. You guys have created something truly special. Software that can do as much as labwc is usually difficult to configure, whereas labwc configuration is refreshingly uncomplicated.
