### ISSUE TITLE
gammastep doesn't work anymore?. (on labwc specifically)

### ISSUE THREAD

**Issue by pablo-888** [labwc/labwc#1262]
Launching it does nothing. It doesn't crash or anything it just has no effect whatsoever.  Not sure what change caused it since I don't use labwc daily.

**Comment by Consolatis** [comment]
This is a regression since we moved to wlroots 0.17, it changed the API for gamma.

Ref: [wlroots MR](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4046) [sway PR](https://github.com/swaywm/sway/pull/7494)

**Comment by johanmalm** [comment]
> This is a regression since we moved to wlroots 0.17, it changed the API for gamma.
> 
> Ref: [wlroots MR](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4046) [sway PR](https://github.com/swaywm/sway/pull/7494)

Thanks for reporting + researching.

**Comment by stefonarch** [comment]
Same for wlsunset:
```

wlsunset -T 3000 -t 2000
registry: adding output 36
gamma control of output eDP-1 (36) failed

```

**Comment by Consolatis** [comment]
Should be fixed in latest master, feel free to comment if there are further gamma related issues.
