### ISSUE TITLE
Emulated input support

### ISSUE THREAD

**Issue by rayrapetyan** [labwc/labwc#1263]
Hello, what's the state of EIS support in labwc? Is there WIP or any plans? Would be nice to see it here: https://gitlab.freedesktop.org/libinput/libei/-/issues/1.

**Comment by Consolatis** [comment]
Labwc supports the wayland virtual keyboard protocol and the virtual pointer protocol.
Both are used for example in wayvnc. Labwc itself doesn't deal with dbus at all.
[wlrctl](https://git.sr.ht/~brocellous/wlrctl) can be used as well and might be available in your package manager.

I don't think there are any technical issues that would stop somebody from implementing a libei dbus portal which then internally uses the wayland protocols. Either as a standalone application or within for example https://github.com/emersion/xdg-desktop-portal-wlr/
See for example
- https://github.com/emersion/xdg-desktop-portal-wlr/issues/2
