### ISSUE TITLE
DMABUF feedback support

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#1268]
[wlroots MR](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3726)
[sway scene commit](https://github.com/swaywm/sway/pull/6844/commits/9c04a1894d5989a52d6e0541a3fd04e44b479709)

- #1278

**Comment by Consolatis** [comment]
As I don't really know of a way to test this I'll remove it from the 0.7.0 milestone.

**Comment by johanmalm** [comment]
Closed by #2234
