### ISSUE TITLE
[Feature Request] Window Rules

### ISSUE THREAD

**Issue by varbhat** [labwc/labwc#127]
Sway (and probably i3) has Window Rules(`for_window`). Using this,we can apply rules to windows which match certain criteria. I would like to have it in labwc.

Ex: In sway, i can prefix title of xwayland applications as "xorg" using the rule. I can make some windows floating using the rule. 

See 
https://i3wm.org/docs/userguide.html#for_window

https://github.com/varbhat/dotfiles/blob/46acf93c2606b9bee8106e2cde3a6e1ce9d0d570/dot_config/sway/config#L138 for more details.

**Comment by johanmalm** [comment]
It’s 2.7.1 in the Acceptance Criteria.
It’s Cat B, so low priority this side of v1.0
In terms of difficulty, it should be quite easy to implement if you fancy having a go. I think action.c would need to be refactored to allow this - possibly with a void *data argument to give some flexibility.

**Comment by varbhat** [comment]
2.7.1 is just `decor` and i feel it's not the same as rules
