### ISSUE TITLE
Cursor is located at the right edge of the display after turning monitor off/on the first time

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#1272]
See title, cursor isn't in the same position it used to be after turning my monitor off and then on again the first time, instead its at the right edge of the screen. Weirdly enough any time after that when I turn the monitor off and then on again it stays in the same place like it should.

**Comment by Consolatis** [comment]
Thoughts @jlindgren90 ?

I think there was also something with wlroots 0.17 now reacting to output scale changes for the cursor by itself as well but I didn't look further into it yet.
