### ISSUE TITLE
[Feature Request] IPC daemon

### ISSUE THREAD

**Issue by varbhat** [labwc/labwc#128]
It would be nice if IPC communication/daemon can be provided for labwc to be able to control it programmatically.

**Comment by johanmalm** [comment]
What type if IPC?
Unix socket?
Wayland Protocol?
To enable what?

**Comment by varbhat** [comment]
Sway/i3 provides JSON RPC over sockets. It would be better if labwc too provided RPC like that.

See projects like https://sr.ht/~tsdh/swayr/ which utilize it.

**Comment by bi4k8** [comment]
This is useful for tools like `swayidle`, which currently correctly detects idle time with labwc, but has no way of asking the compositor to set monitors to dpms on/off:
```sh
swayidle timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"'
```

It's also useful for external tools to be able to issue commands like "list all windows" followed by "focus a given window"; I'd like these to enable the window-search workflow I've built with `swaymsg` (and `wmctrl` under X) in the past.

**Comment by Consolatis** [comment]
> It's also useful for external tools to be able to issue commands like "list all windows" followed by "focus a given window"; I'd like these to enable the window-search workflow I've built with `swaymsg` (and `wmctrl` under X) in the past.

That is exactly what wlr-foreign-toplevel-management-unstable-v1 is for. And it is already implemented in labwc.

https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml
