### ISSUE TITLE
Changes in display power state destroy ouptut configuration and window arrangement

### ISSUE THREAD

**Issue by ahesford** [labwc/labwc#1281]
Related issue: https://github.com/labwc/labwc/issues/864

Changes in display power state, for example issuing a `wlopm --off` or just pushing the power button, will cause labwc to completely discard configuration and window arrangement for that output. I don't know if single-output setups are special-cased to some extent, but this is particularly problematic for multiple outputs:

- Any position configured or scale configured for that output will be lost
- All windows on that output will be gathered on another, active output (until the last remaining output is switched off)

Even with a single output, I suspect that a non-unit scale factor will be reset once the display is reactivated. This seems to be a consequence of disabling each powered-off output in `handle_output_power_manager_set_mode()` as [discussed here](https://github.com/labwc/labwc/issues/864#issuecomment-1493121122).

System details:
- Void Linux (rolling, up to date)
- labwc 0.6.6
- wlroots 0.16.2
- wlopm 0.1.0
- Video hardware: AMD Radeon RX 580

Steps to reproduce:
1. Launch `labwc` with a default configuration on multiple displays.
2. Launch a terminal on each output.
3. In one of the terminals, issue the command `wlopm --off '*' && sleep 20 && wlopm --on '*'`; adjust the sleep as necessary to allow each display to shut itself down.
4. Reconfigure the displays with some non-unit scaling. For example, with two 4K displays:
    ```sh
    wlr-randr --output DP-1 --pos 0,0 --scale 1.5 --output DP-2 --pos 2560,0 --scale 1.5
    ```
5. Again launch a terminal on each output.
6. Re-run step 3.

Expected behavior:
After Steps 3 and 6, the output configuration and window arrangement on each display should be the same as before the step was run.

Actual behavior:
All outputs will be reset to a default arrangement with unit scaling, and all windows will be coalesced onto one of the displays.

Comments:
It may be hard to distinguish a physical power-off of a display from pulling the cable, and one might argue that the appropriate response to physically disconnecting a display **should** cause labwc to reconfigure outputs. However, operations like `wolpm --off` seem primarily useful for power management during idle periods, and it seems appropriate in that case to save and restore all possible display state in that case.

**Comment by johanmalm** [comment]
Thanks for reporting. Agree, that doesn’t seem right. Will try with scale 1.5 to see if I can reproduce.

**Comment by ahesford** [comment]
Even without scaling, you should see all windows coalesce on one display. Furthermore, if the display sleep/wake ordering is just right, you might see the relative positions (e.g., left/right) change after waking.

**Comment by Consolatis** [comment]
Maybe we should just ignore wlopm events and simply \*not\* change any state at all. I am not sure if we still get frame request at that point though. In some setups we may also get a destroy signal for the display in those cases (in my case for example when just selecting another output or physically turning the monitor off).

**Comment by ahesford** [comment]
The plot thickens. I tested on two laptops, each with Intel graphics of different generations, and could not reproduce the issue (although one of the test setups triggered some other corner case). This could be a quirk of the displays (those that cause problems are Samsung U28E570 and U28E590 units) or an amdgpu issue (as noted before, this is a Radeon RX 580).

The first laptop has 12th-generation Intel Xe graphics and a 1920x1200 display connected to eDP-1. I run that with `scale 1.25` and, after a power cycle using `wlopm`, nothing changed. All open windows remained where I placed them, and the display scale was not reset.

The second laptop has 9th-generation Intel graphics and a 3840x2160 display. I can run this standalone and get the same results as the other laptop; power-cycling the display leaves the window positions and `scale 2.0` unchanged. I also run this laptop with the internal display disabled and two LG 4K displays connected---one on an internal HDMI connector (which I believe passes through an Nvidia GPU that is disabled at boot using an `acpi_call` invocation) and another connected to the DP port on a Thunderbolt dock. In this configuration, I can power cycle both external displays and the display arrangement, scale and window placement survives as expected.

The corner case was observed when I turned on the internal display alongside the two external displays. In that test, I put all three displays to sleep with `wlopm --off '*'`, waited for things to shut down, and woke them up with `wlopm --on '*'`. All three displays went dark, but the two external displays would not power on again. I tried another `wlopm` cycle (this time directed at a particular display), switching kanshi profiles, and even manually running `wlr-randr` to try to kick them on, but it required restarting the labwc session to get my displays back. I suspect this is an unrelated (or only marginally related) issue.

**Comment by Ph42oN** [comment]
I also have this happening, if i turn off and back on my 2nd monitor that is rotated, it does not stay rotated. It also breaks switching beetween MPRT and adaptive sync modes on my main monitor, looks like switching is detected as if monitor turned off and back on. I would prefer if i could make it behave same as it does on fluxbox, it keeps working like if that monitor was still turned on even when its off.

**Comment by ahesford** [comment]
This does not seem to be a labwc bug. I'm not even sure this is a wlroots bug, although it may be possible to modify wlroots behavior to work around the problem. Attached is a debug log wherein I:

1. Launch labwc with two DisplayPort outputs
2. The autostart script launches kanhsi with both displays in the desired arrangement, each set to scale 1.5
3. Launch two `foot` terminals via a keybind action, placing one on each output
4. After waiting a minute, issue the command `wlopm --off DP-2`; this is annotated in the log with a `#######` header
   - Note that `backend/drm/drm.c` in wlroots reports "connector DP-2: Turning off"
5. Launch another terminal, run `wlr-randr` to confirm that both displays are still "enabled"
6. Launch `wdisplays` to confirm the same, and also observe that DP-2 shows up as solid gray in the preview window; `wdisplays` knows that, although the display is enabled, it is not showing a picture
7. Issue the command `wlopm --on DP2`; this is again annotated in the log with a `#######` header
   - Note that it is only *after* the display-on action that wlroots reports "udev event for card0 (change)" and, later, "Received hotplug event for /dev/dri/card0"

At this point, wlroots destroys the DP-2 output and recreates it; this triggers a labwc layout change, and all windows that were originally on DP-2 are then relocated to DP-1 and centered. The recreation does not trigger `kanshi`, so the display opens in its preferred resolution with scale 1.0 rather than the previously set scale 1.5.
