### ISSUE TITLE
how can i have the panel in all my workspaces?

### ISSUE THREAD

**Issue by Attigliuzzo** [labwc/labwc#1288]
Hi,
i have enabled 2 workspaces but lxqt-panel is available only on the first workspace. Is possible to have it in all my workspaces?
Thanks for all your efforts

**Comment by Consolatis** [comment]
You need a window rule for that, something like [this](https://github.com/stefonarch/lxqt-labwc-session/blob/44da4856c7265f34e2541f1a2fe52f1285921b63/config/labwc/rc.xml#L89-L93).

**Comment by Attigliuzzo** [comment]
I added that action in my rc.xml file but i will wait the stable release (0.7) then it will work.
I removed the always on bottom option for lxqt-panel because i need to keep pcmanfm-qt desktop always on the bottom, no both of them.
Thanks for the tip.

**Comment by stefonarch** [comment]
> I added that action in my rc.xml file but i will wait the stable release (0.7) then it will work. I removed the always on bottom option for lxqt-panel because i need to keep pcmanfm-qt desktop always on the bottom, no both of them. Thanks for the tip.

You can use the rule well for both, no problem, by adding` <margin top="38"/>` for a 38px panel,

**Comment by Attigliuzzo** [comment]
> You can use the rule well for both, no problem, by adding` <margin top="38"/>` for a 38px panel,

@stefonarch , thanks i'll try.
