### ISSUE TITLE
[Feature Request] Toggleable Window Titlebar

### ISSUE THREAD

**Issue by varbhat** [labwc/labwc#129]
I use 14' laptop. As such, screen space is less. Sometimes,i would like to not see titlebar of a specific window/remove it to save space. It would be even more better if keybinding(configurable) exists to toggle titlebar for a window.

Also, i would like this feature to be controlled via [Window Rules](https://github.com/labwc/labwc/issues/127#issue-1065917728) too.

**Comment by johanmalm** [comment]
The action ToggleDecorations does this

https://raw.githubusercontent.com/labwc/labwc/master/docs/labwc-actions.5.scd

**Comment by varbhat** [comment]
@johanmalm , will we be able to apply this via rules? for example, i don't want to have decorations for chromium application. how can this be done?

**Comment by johanmalm** [comment]
> @johanmalm , will we be able to apply this via rules? for example, i don't want to have decorations for chromium application. how can this be done?

See issue 127

**Comment by johanmalm** [comment]
Could you confirm if ToggleDecorations works, and if so, close the issue.

**Comment by johanmalm** [comment]
If you create a keybind for this, could you use https://github.com/atx/wtype ?
I’ve not tried this myself. Would be interested to know if it works
