### ISSUE TITLE
Translations should be updated with the new OmniPresent menu

### ISSUE THREAD

**Issue by kyak** [labwc/labwc#1311]
Translations (pot and po files) should be updated with the new OmniPresent menu: https://github.com/labwc/labwc/pull/1256

cc @bnason

**Comment by Consolatis** [comment]
Just to avoid any confusion: it is not necessarily required that somebody adding a new default menu entry has to do the translations as well.

You obviously have a point here though, we should update the translations (if possible).

**Comment by kyak** [comment]
What I mean is that pot and po files need to be regenerated so that translators can pick it up and translate new strings.

**Comment by 01micko** [comment]
> Just to avoid any confusion: it is not necessarily required that somebody adding a new default menu entry has to do the translations as well.

`po` are for translations. `pot` is the template. So `labwc.pot` IMHO should be updated by the coder as it's the template. 728a6b0 adds some instructions for this in `CONTRIBUTING.md`.
