### ISSUE TITLE
ToggleOmniPresent finishing touches

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#1316]
- [x] maybe move into the workspaces sub menu so it gets hidden when there are no workspaces defined
- [x] rename the menu entry into something more easy to understand like "Visible on all workspaces"
  - [x] change pot file with the new text
- [x] sync up with the example `menu.xml`

**Comment by johanmalm** [comment]
"Always on Visible Workspace"?

**Comment by stefonarch** [comment]
That sounds like it would follow workspace switches somehow, no?
"Show on all workspaces" ?

**Comment by johanmalm** [comment]
![20231219_21h16m40s_grim](https://github.com/labwc/labwc/assets/6955353/2afaa6bf-97e1-4783-afa1-6a68f7adb2d2)

:smile:

**Comment by Consolatis** [comment]
Fixed by
- #1343
