### ISSUE TITLE
Chromium always briefly opens unmaximized first even with `<windowRule identifier="*"><action name="Maximize"/></windowRule>`

### ISSUE THREAD

**Issue by sgtpep** [labwc/labwc#1320]
Discovered some inconsistencies in how some complex apps (like browsers) react to `<windowRule identifier="*"><action name="Maximize"/></windowRule>`:

- Scenario 1. I don't have `<windowRule identifier="*"><action name="Maximize"/></windowRule>` in `rc.xml`, I open previously unmaximized Chromium, manually maximize it, then reopen it. Chromium always first briefly displays its window unmaximized then maximizes it after some short delay.
- Scenario 2. I have `<windowRule identifier="*"><action name="Maximize"/></windowRule>` in `rc.xml`, I open previously unmaximized Chromium. Chromium always first briefly displays its window unmaximized then `<action name="Maximize"/>` takes effect and Chromium gets maximized after some short delay.
- Scenario 3. I have `<windowRule identifier="*"><action name="Maximize"/></windowRule>` in `rc.xml`, I open previously unmaximized Firefox. Firefox opens maximized and then then breifly switches to the previous unmaximized state.

Expectation: Ideally, all apps should open maximized straight away without flickering with `<action name="Maximize"/>`.

Fwiw, I was a heavy Openbox user in the past with Xorg and actively used window rules, and they worked flawlessly with all the apps and windows.

**Comment by Consolatis** [comment]
It might make a difference if Chromium / Firefox use the X11 or the wayland native backend. Does it happen in all cases?
(`MOZ_ENABLE_WAYLAND=1` for Firefox / `--enable-features=UseOzonePlatform --ozone-platform=wayland` for Chromium)

**Comment by sgtpep** [comment]
- Ironically, Chromium opens correctly maximized with no flickering with `--ozone-platform=x11` under `labwc` but unmaximized-then-maximized with `--enable-features=UseOzonePlatform --ozone-platform=wayland`.
- I couldn't find a way to test Firefox with wayland support disabled: there's a way to enable it with `MOZ_ENABLE_WAYLAND=1` but apparently no clear way to disable it back, and for some reason I have wayland enabled in Firefox by default judging by `about:support`.

**Comment by sgtpep** [comment]
Another scenario: no window rules in `rc.xml`, Chromium was previously unmaximized. Running `chromium --start-maximized` also produces flickering before actually maximizing.

**Comment by jlindgren90** [comment]
I have also noticed graphical glitches with XWayland apps starting maximized. I think this is due to the fact that wlroots (1) reports the initial maximize request in the `map` event but (2) only reports the `map` events to the compositor after the first repaint. So necessarily the app is forced to paint itself once at the non-maximized size before labwc even sees the `map` event.

It is on my TODO list to look into further (though not a high priority right now).
