### ISSUE TITLE
When connecting a wireless mouse to a wire, natural scrolling stops working

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#1322]
So I have a weird issue. I have a Logitech G703 wireless mouse, which charges via a USB cable. When connected via the USB cable, it effectively turns it into a wired mouse (the wireless bits stop working, you can unplug the dongle and it'll still work) and the OS will in fact recognize it as a different device.

under sway I could just set all input devices to natural scroll and that takes care of it. however, on labwc, when connected via the USB cable, it refuses to respect `<naturalScroll>yes</naturalScroll>` in rc.xml. disconnecting the cable (switching it back to wireless) results in proper behavior for natural scrolling.

not sure what the best approach to this particular bug is, since it's a _fairly_ niche issue

**Comment by johanmalm** [comment]
Could you paste the `<libinput>` section of the config. I'm keen to understand what you've set `<device category="">`.

**Comment by winteriscariot** [comment]
Ah it was a mistake in my config that I entirely missed, I had the device category set incorrectly. It is working properly when i set the category to 'default'. Sorry for the chatter!
