### ISSUE TITLE
Adaptive Sync ON only for fullscreen apps

### ISSUE THREAD

**Issue by Faugus** [labwc/labwc#1323]
If I enable Adaptive Sync, some desktop windows feel jerky.

Could you please add an option to enable Adaptive Sync only for fullscreen apps like KDE and Hyprland do?

**Comment by johanmalm** [comment]
Sounds relatively straight forward looking at where we set adaptive sync in `output.c`. It'd be good if someone with adaptive sync could have a go a this to confirm that it works.

**Comment by Faugus** [comment]
Actually, it's not the window. It's the mouse cursor that feels jerky cause having Adaptive Sync ON on desktop makes the refresh rate of the monitor get stuck at 48Hz (I have a 144Hz monitor).

**Comment by Ph42oN** [comment]
I think that is not how its supposed to work, for me refresh rate instantly jumps from 48 to 165hz when moving mouse. But anyways i could try making this option, it could be useful to me too as my monitor has issue that sometimes it flickers at low refresh rates like 48hz.

**Comment by Consolatis** [comment]
Implemented by
- #1364
- #1388

Thanks @Ph42oN :)
