### ISSUE TITLE
Odd multi display behavior with a nonstandard configuration. 

### ISSUE THREAD

**Issue by Sinaaaa** [labwc/labwc#1327]
Like this everything is fine, I have a pair of mirrored displays, have not noticed major issues.
`wlr-randr --output HDMI-A-1 --pos 0,0 --output VGA-1 --pos 0,0  --preferred --output HDMI-A-2 --off`

If we add a third display to the mix that is only "touching" the main mirrored display, then games I launch run out of bounds, or sometimes half out of bounds & using my normal keybinds -or the mouse- to move it to my main display leads to flickering, but the game window(windowed full screen mode) will not budge and even trap the mouse irrevocably. 
If I open a VLC window on my auxiliary display I cannot use the mouse to interact with VLC itself, only the titlebar. (keyboard commands work)
I like using a display configuration like this, because the mouse is caged to the display I'm working on, unless I pixel accurately move it the bottom-left(or top-right) corner. 
`wlr-randr --output HDMI-A-1 --pos 0,0 --output VGA-1 --pos 0,0  --preferred --output HDMI-A-2 --pos -1440,1080 --mode 1440x900`

I managed to fix VLC with making all the display pos parameters positive like this:
`wlr-randr --output HDMI-A-1 --pos 2000,2000 --output VGA-1 --pos 2000,2000  --preferred --output HDMI-A-2 --pos 560,3080 --mode 1440x900`
Gaming of course is still not possible, unless I start the game first & then switch to a different display configuration afterwards. 

I should probably mention that an identical display configuration on Hyprland works perfectly. 
(though I use the default config file's display features, I'll try it with wlr-randr later just to be sure, edit: It works fine.)

**Comment by johanmalm** [comment]
Thanks for reporting.
Sounds like a bug we need to investigate.
Is it on 0.6.6 or master or both?

**Comment by Sinaaaa** [comment]
> Is it on 0.6.6 or master or both?

I installed it from AUR, the AUR helper says it's 'AUR Explicit (1): labwc-0.6.6-1'.

**Comment by johanmalm** [comment]
`master` has been ported to `wlroots 0.17` so has a year's worth of changes. There isn't a big change on the `labwc` side though.

`wlroots` change a number of things relating to outputs between `0.16` and `0.17` hence the question.

**Comment by Sinaaaa** [comment]
> `master` has been ported to `wlroots 0.17` so has a year's worth of changes. There isn't a big change on the `labwc` side though.
> 
> `wlroots` change a number of things relating to outputs between `0.16` and `0.17` hence the question.

I will try it later today, that does sound very significant indeed.

**Comment by johanmalm** [comment]
There is some output related fixes in wlroots `0.17.1`.
Any chance of testing with that?

https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.17.1

**Comment by Sinaaaa** [comment]
I think I did the installing part right & considering how smooth & lag free my cursor is that seems very likely. 
(download tar > extract tar> `meson setup build/`    >   `ninja -C build/`   >   `sudo ninja -C build/ install`) This whole having multiple version wlroots on my system is just really weird & confusing..

Anyhow, while I'm very happy about the smooth lag-free cursor, there is no change in this display-game behavior. 

Is there a reliable way to check the wlroots version currently in use ?

**Comment by Narrat** [comment]
You could have tried the `labwc-git` package from the AUR instead of `labwc`. Didn't check when the dep changed to wlroots 0.17, but IIRC when you build your packge it was already on wlroots 0.17.
But that it is obsolete now :) New push to the AUR `labwc` package with the update to 0.7.0.

Regarding checking the binaries if they're dynamically linked:
```
$ readelf -d /usr/bin/labwc

Dynamic section at offset 0x41fb0 contains 36 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-server.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libwlroots.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libxkbcommon.so.0]
(....)
```
```
libwlroots.so.12 == wlroots 0.17
libwlroots.so.11 == wlroots 0.16
```

**Comment by Sinaaaa** [comment]
I'm already on the git version, updating that without installing 17.1 manually just tells me that "Run-time dependency wlroots found: YES 0.17.0" so that's probably not it. 

Either case, there is no improvement with this problem.

**Comment by johanmalm** [comment]
If you build with the command below you'll get the latest `wlroots/` in `subprojects/`:

```
meson setup --force-fallback-for=wlroots build/
ninja -C build
```

**Comment by Sinaaaa** [comment]
I may have figured this one out. It's not a labwc problem, so I'm closing this. (I managed to reproduce this in some shape or form on xorg)
The issue is that some games expect to interact with displays in a certain way that gets broken if the display setup is weird like mine. (so I suppose it's a wine problem) The workaround is to make sure the game is started on a monitor that is pos 0x0, while all the odd stuff is to the right.
