### ISSUE TITLE
Feature request: <resize><drawContents>no</drawContents> ... </resize>

### ISSUE THREAD

**Issue by Sinaaaa** [labwc/labwc#1328]
With compositing on resizing a Chromium window on an aging intel IGPU is often laggy experience, with a high polling rate gaming mouse on Wayland it's horrible. Only on Hyprland it's not, maybe because of some wlroots ENVs I have on there, I don't yet know, but in KDE, Gnome, labwc it is. (Maybe the trick is that the border I'm dragging gets more CPU time on Hyprland and also maybe they are doing a trick with window content warping for resize, which is a fancy way of doing the same thing I'm asking for here in this post) 
Openbox has a feature that helps sidestepping this problem, if 
```
 <resize>
    <drawContents>no</drawContents>
...
  </resize>
```
is added to the rc.xml the system doesn't have to struggle redrawing everything, battery is saved on a laptop etc etc..
Please consider adding this, if you feel like it someday ^

Thank you (and contributors as well) for developing labwc, it's already so much better than openbox in some fundamental ways. (window aero snap without janky half-assed workarounds and the horrible titlebar seperator that ruins consistent theming is not in labwc at all!)

**Comment by johanmalm** [comment]
Thanks for the feedback.
This has been on our mind to implement.
We want labwc to run well on very-low spec hardware, so this is definitely in the spirit of the scope.

**Comment by tokyo4j** [comment]
As I found Steam is so laggy for resizing today, I made a [prototype](https://github.com/tokyo4j/labwc/tree/drawcontents) of this feature.
I'll make a PR in coming weeks. This won't be included in next release.

https://github.com/labwc/labwc/assets/22029524/bf92f780-3980-4a58-b05f-c13961fe24a1

**Comment by Consolatis** [comment]
This is looking great!

Additionally we can also deduplicate incoming resize events, e.g. if the cursor position is the same as in the last call (maybe just some simple static vars within `process_cursor_resize`) just do nothing. This should help with crazy high update gaming mice.

**Comment by tokyo4j** [comment]
> Additionally we can also deduplicate incoming resize events, e.g. if the cursor position is the same as in the last call (maybe just some simple static vars within process_cursor_resize) just do nothing. This should help with crazy high update gaming mice.

I wonder if this helps. We are already eliminating resize events with duplicated size in `xdg_toplevel_view_configure()` and xwayland counterpart. I guess the problem is that the cursor jumps for more than 1 pixel for every signal from the mouse when we quickly move the mouse.

I think we can deduplicate resize events based on timestamp rather than cursor position.
