### ISSUE TITLE
Regression: Panel with keyboard interactivity getting focus and thus breaking click-on-active-window-to-minimize

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#1336]
Ref:
- https://github.com/LBCrion/sfwbar/issues/130

This is another fallout from the focus refactoring. As the keyboard focus is indeed somewhere else we should likely keep updating the SSD to the `inactive` state as we currently do (though that is debatable) but we should maybe not update the foreign-toplevel handle `activated` state.

I am not sure how to properly approach this, ideas very welcome @jlindgren90 @johanmalm 
Basically what we'd need to do here is to lie to foreign toplevel clients that the `actived` state didn't change but only when the newly focused wlr_surface is set (so we still `deactivate` on the `Unfocus` action for example) but the `view` is \*not\* set (e.g. the newly focused surface is a layershell or xdg popup surface).

However, we still need to reset that state later on when an actual different view is focused but we have updated `server->focused_view` since then so we don't know that we still need to update the foreign toplevel `activated` state from the earlier view.

The relevant parts are
https://github.com/labwc/labwc/blob/17cbfb7299190f3c0b659ff506d4c1f9e8261382/src/seat.c#L346-L376
and
https://github.com/labwc/labwc/blob/17cbfb7299190f3c0b659ff506d4c1f9e8261382/src/view.c#L264-L287

Edit:
Or as alternative we could just add another early return like
```c
/*
 * Prevent focus switching to layershell
 * clients from updating any view state
 */
if (!view && server->focused_view && event->new_surface
        && wlr_layer_surface_v1_try_from_wlr_surface(event->new_surface)) {
    return;
}

/*
 * Due to the previous conditions we may end up in a situation where
 * we give focus to a previously focused view that was never deactivated
 */
if (view == server->focused_view) {
    return;
}
```

**Comment by jlindgren90** [comment]
Since layer-shell surfaces are not "views", I can see an argument for not deactivating the current view when a layer-shell surface has keyboard focus. We do the same for xwayland "unmanaged" (override-redirect) surfaces in some cases.

**Comment by johanmalm** [comment]
At first, I couldn't reproduce this because I was running a 6 month old build of `sfwbar`. Bisecting revealed that the breaking commit is: https://github.com/LBCrion/sfwbar/commits/113093f8642c56b9eabf153460aee11dfcb0d673

But, that's probably irrelevant because I support the panel should be allowed to take keyboard_focus for navigating xdg-popup menus with arrow keys and other such things.

I'll login to sway to see how it behaves.

> edit: we'd want to re-examine the definition and usage of `server->focused_view` in that case. Maybe it would make sense to rename it to `server->active_view` since it might not actually have keyboard focus at all times.

Good point.

**Comment by Consolatis** [comment]
> I suppose the panel should be allowed to take keyboard_focus for navigating xdg-popup menus with arrow keys and other such things.

Yes, I think the same. The protocol combination of layershell + exclusive or on_demand keyboard interactivity doesn't mix well with the foreign-toplevel-protocol. I think panel authors should be free to support the keyboard without having to fear that whenever the user interacts with the panel the `activated` state of the current window is being reset.

**Comment by johanmalm** [comment]
@Consolatis You proposal looks good. I've created a PR #1342 for it
