### ISSUE TITLE
No windows inside margin

### ISSUE THREAD

**Issue by vicencb** [labwc/labwc#1340]
Hi, i've got a desktop panel that uses SDL.
SDL does not support layer-shell https://github.com/libsdl-org/SDL/issues/7262
So, i am setting labwc with: `<margin top="0" bottom="0" left="80" right="0" output="" />`
Now i can manually drag the panel inside the margin, but as soon as i release the mouse button, the panel is relocated outside the margin.
The SDL window is created with `SDL_CreateWindow("title", -80, 0, 80, 1000, SDL_WINDOW_SKIP_TASKBAR | SDL_WINDOW_BORDERLESS)`, that is, at position (-80, 0) and size (80, 1000) in order to place the panel inside the margin, but the position is ignored.
Also, the panel appears in the window list when pressing `A-Tab`, despite `SDL_WINDOW_SKIP_TASKBAR`.
The same application works with openbox as expected. With labwc, i am setting `SDL_VIDEODRIVER=wayland` environment variable.
This has been tested with `0.6.6-59-g17cbfb7`.

This program can be used as a reproducer of the issue:
```c
#include <SDL.h>

int main() {
  SDL_SetHint(SDL_HINT_VIDEO_ALLOW_SCREENSAVER, "1");
  SDL_Init(SDL_INIT_VIDEO);
  SDL_Window *window = SDL_CreateWindow("title", -80, 0, 80, 1000, SDL_WINDOW_SKIP_TASKBAR | SDL_WINDOW_BORDERLESS);
  SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, 0);
  SDL_Event event = {};

  while (event.type != SDL_QUIT) {
    SDL_SetRenderDrawColor(renderer, 232, 232, 232, 0);
    SDL_RenderClear(renderer);
    SDL_RenderPresent(renderer);
    SDL_WaitEvent(&event);
  }

  SDL_DestroyRenderer(renderer);
  SDL_DestroyWindow(window);
  SDL_Quit();
  return 0;
}
```

It is compiled with `cc sdltest.c $(pkgconf --cflags --libs sdl2)`

**Comment by johanmalm** [comment]
We don't (yet) support the X `skipTaskbar` property. You can do a window-rule for it though if you want.
Regarding the position, can you go outside the 'usable-area' (i.e. area not taken up by other panels) by specifying a negative value in X?

**Comment by vicencb** [comment]
Thanks for the workaround of using window rules, that works fine for skipping the taskbar.
But positioning does not work. The reproducer program was already setting the position to negative X (-80, 0).
I also tested with position (0, 0), but nothing, the panel always appears on the middle of the screen.

Also, there is another minor issue with the margin: the openbox config is `margins` while in labwc it is `margin`.

**Comment by vicencb** [comment]
I gave it another try and achieved what i wanted. The window-rule setting is:
```
skipTaskbar
skipWindowSwitcher
action name=MoveTo x=0 y=0
```
