### ISSUE TITLE
Dependency issues when building 0.7.0 on Debian Stable

### ISSUE THREAD

**Issue by jonleivent** [labwc/labwc#1356]
I'm trying to build labwc 0.7.0 on Debian 12, which doesn't have recent enough libs.  The meson build first complains about missing wayland (actually it first complains about the existing wlroots subproject not being the right version - I fixed that manually with a git checkout).  I added a wayland.wrap to get it to download wayland:

```
[wrap-git]
url = https://gitlab.freedesktop.org/wayland/wayland.git
revision = 1.22.0

[provide]
dependency_names = wayland-server
```

Then it complains about wayland-protocols, so I added wayland-protocols.wrap:
```
[wrap-git]
url = https://gitlab.freedesktop.org/wayland/wayland-protocols.git
revision = 1.32

[provide]
dependency_names = wayland-protocols

```
But then it crashes with:
```
../protocols/meson.build:1:0: ERROR: Could not get an internal variable and no default provided for <InternalDependency null: True>
```
Any ideas on how to work around this?

**Comment by stefonarch** [comment]
Just tried too, it was looking for  libwaylandserver` found 1.21.0 but need: '>=1.22'`
but I'm afraid to break my system, installing https://gitlab.freedesktop.org/wayland/wayland, I'll try in a WM first. 
```
$ls src
libwayland-client.so            libwayland-server.so            wayland-client-protocol-core.h  wayland-server-protocol-core.h
libwayland-client.so.0          libwayland-server.so.0          wayland-client-protocol.h       wayland-server-protocol.h
libwayland-client.so.0.22.90    libwayland-server.so.0.22.90    wayland.dtd.h                   wayland-version.h
libwayland-client.so.0.22.90.p  libwayland-server.so.0.22.90.p  wayland-protocol.c
libwayland-private.a            libwayland-util.a               wayland-scanner
libwayland-private.a.p          libwayland-util.a.p             wayland-scanner.p

```
Looks like labwc 0.6.* will be the limit on actual debian stable systems, so backporting essential things/bugfixes could  be the way for some time.

**Comment by Consolatis** [comment]
I am running Bullseye (e.g. Debian 11) + selected packages from Stretch + Testing + Sid. However that is really not recommend.
For wayland-protocols it doesn't really matter, its just some XML files after all (be it via subproject or via a newer Debian repo). But for libwayland and libdrm it might become an issue. Debian is currently transitioning to wlroots 0.17.x but that obviously doesn't help for current stable either ([wlroots](https://tracker.debian.org/pkg/wlroots), [labwc](https://tracker.debian.org/pkg/labwc))

> Looks like labwc 0.6.* will be the limit on actual debian stable systems, so backporting essential things/bugfixes could be the way for some time.

That is planned already (but only for bugfixes): https://github.com/labwc/labwc/issues?q=label%3Abackport

**Comment by johanmalm** [comment]
I broke my Ubuntu machine doing this type of stuff, so have to run it in XServer mode. So, my advice is to not do system wide installations.

**Comment by jonleivent** [comment]
> I am not sure what could cause this issue. I'd recommend creating a new build dir to ensure that everything is configured fresh, e.g. something like meson setup build_test meson compile -C build_test. A complete log of the configure step might help as well.

I tried something like that - `rm -rf`'ed build and started completely fresh.  No change.

Attached is the meson configure log...
[meson-log.txt](https://github.com/labwc/labwc/files/13759602/meson-log.txt)

**Comment by jonleivent** [comment]
Also checked that I am able to build 0.6.6.  So whatever happened was introduced since.

**Comment by Consolatis** [comment]
> Looking for a fallback subproject for the dependency libdisplay-info
> Neither a subproject directory nor a libdisplay-info.wrap file was found.
> Subproject  libdisplay-info is buildable: NO (disabling)
> Dependency libdisplay-info from subproject libdisplay-info found: NO (subproject failed to configure)
> Message: Required for the DRM backend.

https://tracker.debian.org/pkg/libdisplay-info
Seems to be available in the bullseye-backports repo

**Comment by jonleivent** [comment]
I installed `libdisplay-info-dev` from backports, and that gets the config further, but still fails:
[meson-log.txt](https://github.com/labwc/labwc/files/13759907/meson-log.txt)

**Comment by jonleivent** [comment]
Looks like I need to install `libliftoff-dev`...

**Comment by jonleivent** [comment]
but the one in bookworm is the wrong version: 0.3.0, but the config wants >=0.4.0.  And none in bookworm-backports.

**Comment by jonleivent** [comment]
I can add https://gitlab.freedesktop.org/emersion/libliftoff as a subproject...

**Comment by jonleivent** [comment]
Did that.  Also installed `librsvg2-dev` to get past the next missing dependency.  But it still fails:
[meson-log.txt](https://github.com/labwc/labwc/files/13759968/meson-log.txt)

**Comment by Consolatis** [comment]
libliftoff is optional, I am not even sure if it does anything for labwc.

> protocols/meson.build:1:0: ERROR: Could not get an internal variable and no default provided for <InternalDependency null: True>

Hm, looking at the error message again, I guess its failing on `wl_protocol_dir` in `protocols/meson.build`.
I could reproduce the issue by `meson setup foobar --force-fallback-for=wayland-protocols` with the same `wayland-protocols.wrap` file as described in the top post.

Sadly it is [not packaged](https://tracker.debian.org/pkg/wayland%2Dprotocols) in stable-backports.

**Comment by jonleivent** [comment]
Installed `libvulkan-dev`, just in case that became a hard dependency.  Still have the same config failure.

**Comment by Consolatis** [comment]
I think I got it:
```diff
diff --git a/protocols/meson.build b/protocols/meson.build
index 527f9d4c..1cec5594 100644
--- a/protocols/meson.build
+++ b/protocols/meson.build
@@ -1,4 +1,4 @@
-wl_protocol_dir = wayland_protos.get_variable(pkgconfig: 'pkgdatadir')
+wl_protocol_dir = wayland_protos.get_variable('pkgdatadir')
 wayland_scanner = find_program('wayland-scanner')

 wayland_scanner_code = generator(
```

**Comment by jonleivent** [comment]
I'll try that now...

**Comment by jonleivent** [comment]
It works!  Thanks!
