### ISSUE TITLE
labwc 0.7.0 fails to run wezterm, gitk on a vmware vm

### ISSUE THREAD

**Issue by tranzystorekk** [labwc/labwc#1361]
This issue encompasses two seemingly related problems with labwc 0.7.0 (and probably wlroots 0.17), specifically in a VMWare setup:

- running gitk (a typical xwayland program) causes labwc to crash: [labwc gdb backtrace](https://0x0.st/HgJy.txt) [labwc log](https://0x0.st/Hgpb.log.old)
- running wezterm fails [wezterm log](https://0x0.st/HgpB.txt)

On a related note, tinywl with wlroots0.17 also fails to run wezterm [tinywl log](https://0x0.st/HgJK.log)

Also confirmed the above problems don't happen on labwc 0.6.6/wlroots 0.16

Environment:

- OS: Void Linux
- Vmware Workstation Player 16
- labwc 0.7.0 + wlroots 0.17.1

**Comment by stefonarch** [comment]
No issue here running wezterm, but gitk is not found on arch/AUR.

**Comment by johanmalm** [comment]
`gitk` is just part of `git`. IIRC you need to install `wish` too.

**Comment by Narrat** [comment]
Like johanmalm stated: `gitk` is part of `git` and needs additionally the `tk` package installed as it uses said toolkit for the interface. May be missing because `tk` is only an optional dep for git.

**Comment by Consolatis** [comment]
Tracked in
- #1829
