### ISSUE TITLE
menu Execute item can no longer use wlrctl keyboard to put text into focused window in 0.7.0

### ISSUE THREAD

**Issue by jonleivent** [labwc/labwc#1366]
I have a labwc menu Execute action item that uses `wlrctl keyboard` to put some text into the focused window.  It was working prior to 0.7.0 (I had been using the multisock branch - so whatever that was based on).  When a menu is up, where is keyboard data sent to by labwc?  Has it changed to send it to somewhere else other than the currently focused window?  The same command, when run from a labwc keybinding, still works.  So the problem is what labwc does with virtual keyboard text when a menu is up.  I can understand there being a reason to direct that text at the menu if it has a way to use text.  Is there a workaround?

**Comment by jonleivent** [comment]
It looks like this is due to the fix for #1058 and #1059, which were fixed earlier than 0.7.0.  I was stuck on the multisock branch, and didn't pick up those fixes earlier.

Would it be possible to turn off keyboard input to the menu after a menu item is selected but before that item is executed, so that any text the item generates goes to the focused window instead of back to the menu?

**Comment by Consolatis** [comment]
Hm.. good point and nice research. Does it work when you use `Return` / `Enter` to trigger the menu entry?

**Comment by jonleivent** [comment]
> Does it work when you use Return / Enter to trigger the menu entry?

Yes it does work!
