### ISSUE TITLE
Turning the display off when using waylock impedes unlocking the session (keyboard doesn't register any input)

### ISSUE THREAD

**Issue by charbelnicolas** [labwc/labwc#1369]
I'm using waylock ([GitHub Page](https://github.com/ifreund/waylock)) and when I lock the session and turn my display off I lose the ability to unlock the session when I turn on the display back again.

It seems the keyboard stops registering all input... I can still see the mouse cursor moving though (which is another bug IMO)

_"\<keybind key="W-S-l">
        \<action name="Execute" command="waylock -init-color 0x333333 -input-color 0x555555 -fail-color 0xf57d7d" />
\</keybind>"_

**Comment by johanmalm** [comment]
What version/commit are you running with? We fixed a couple of surface focus bugs relating to `ext-session-lock` for `0.6.6`

https://github.com/labwc/labwc/blob/ccd4ab943e694ef380aa0e8d40431fd215dc8eee/NEWS.md?plain=1#L143

**Comment by charbelnicolas** [comment]
I'm running the latest version 0.7.0 on arch linux (not the git version)

**Comment by charbelnicolas** [comment]
By the way, this doesn't happen with swaylock so there must be something wrong with waylock... I'll raise an issue in waylock's github...

**Comment by johanmalm** [comment]
It may well be labwc. Sorry, just haven’t got to this one yet.

**Comment by charbelnicolas** [comment]
This was fixed on waylock's latest release version 0.6.4!

**Comment by johanmalm** [comment]
Awesome. Thanks for reporting back.
