### ISSUE TITLE
toggling decoration on a maximized window puts decoration outside usable screen area

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#137]
This is an unfortunate interaction between maximize and decoration-toggling that I think just needs to be handled as a corner case.

To reproduce:
- run some taskbar, e.g. waybar
- open a normal client
- disable the client's decoration with a key binding
- maximize the client
- reenable the client's decoration

The decoration will overlap the taskbar instead of resizing the window to the same size an already-decorated window becomes when maximized.

**Comment by johanmalm** [comment]
We ought to create a `desktop_arrange_views()` that iterates over views and makes sure they respect the `usable_area`.

**Comment by Consolatis** [comment]
Same is true for the other way round: Maximizing a window and then disableing the decoration.
I would expect the compositor to issue a resize event to the window so it can fill up the additional space.
