### ISSUE TITLE
xkill equivalent in labwc?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1371]
I'd like to set some keyboard combination in _rc.xml_ that allows me to then click on a window that I want labwc to close. Ideally labwc would also send SIGTERM or SIGKILL to the process that created the window. Is something of this sort currently possible?

P.S. I'm sorry if this functionality is already implemented and documented. I looked through the documentation and did not find anything obvious.

**Comment by johanmalm** [comment]
It's not currently possible.

It's probably not the most trivial thing to write, but happy to accept patches for it.

**Comment by stefonarch** [comment]
FYI wf-kill plugin per wayfire: https://github.com/soreau/wf-kill

**Comment by bdantas** [comment]
I bound `W-x` (Super+x) to `xkill` in `rc.xml` and, somewhat surprisingly, it works exactly as expected for Xwayland applications. Since most of my applications are running in Xwayland anyway, this is just fine. Thanks, guys.
