### ISSUE TITLE
A configure is scheduled for an uninitialized xdg_surface

### ISSUE THREAD

**Issue by Narrat** [labwc/labwc#1372]
Noticed this output in the labwc log. But I cannot tell if this comes from labwc or wlroots. Or if this a warning, an error or something that should be covered? (I lean to error, because it is written in red)
Or moved to upstream for the offending program(s).
Didn't find a reference in the repo (issues, pr, discussion)

Example:
```
00:00:12.657 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5247f4a70
00:00:18.294 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5245295b0
00:00:19.663 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b524823160
00:00:26.856 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5245296c0
00:00:27.985 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5245296c0
00:00:29.227 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5245296c0
00:05:51.187 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5245296c0
00:05:55.742 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b52484ae30
00:05:55.997 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b5248174c0
00:05:59.840 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b52484ae30
00:06:01.927 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0x55b524816370
``` 
How to reproduce: Happens for example with `waybar` and the tooltip for modules (if enabled for a module those appear if hovering with the mouse above).

Edit: Ha.. there is a discussion: https://github.com/labwc/labwc/discussions/1365 Not found because of typo

**Comment by Consolatis** [comment]
I vaguely remember something about wlroots changing the xdg_surface event flow so that it now (with wlroots 0.17) triggers at an earlier state than it was with wlroots 0.16. Thus what \*might\* happen here is that we try to position the popup before it was properly initialized. If that is indeed the culprit we may need to listen to another signal here before positioning the popup. I assume this change is listed in the breaking changes of wlroots 0.17 but I didn't verify.

**Comment by johanmalm** [comment]
I did have a quick look at this when OP first posted. Nefsen402 scene-graph branch of sway issued the same message with waybar (just fewer of them). Might be a `wlroots` thing we need to patch. Just haven't had a chance to look further yet.

**Comment by Consolatis** [comment]
This can be reproduced easily nested + waybar tooltips (I have an older waybar version here though, no clue if its also reproducible with a recent version, I assume yes).

Added some debug logging and the issue seems to be that we are calling `wlr_xdg_popup_unconstrain_from_box()` before the popup is ready. I'll debug a bit more.

```
00:00:06.200 [types/wlr_compositor.c:692] New wlr_surface 0xaaaaabd68760 (res 0xaaaaabd66460)
00:00:06.201 [types/xdg_shell/wlr_xdg_surface.c:388] new xdg_surface 0xaaaaabd68ba0 (res 0xaaaaabd68cc0)
00:00:06.201 [../src/layers.c:337] new layer popup
00:00:06.201 [../src/layers.c:272] creating layer popup
00:00:06.201 [../src/layers.c:289] wlr_xdg_popup_unconstrain_from_box - start
00:00:06.201 [types/xdg_shell/wlr_xdg_surface.c:169] A configure is scheduled for an uninitialized xdg_surface 0xaaaaabd68ba0
00:00:06.201 [../src/layers.c:291] wlr_xdg_popup_unconstrain_from_box - end
```

**Comment by charbelnicolas** [comment]
I'm getting this error all the time while using chromium:

![ss_2024_02_23_22_27_42](https://github.com/labwc/labwc/assets/14960414/ebb6b117-2333-4a16-a95e-616541fb8449)

**Comment by Consolatis** [comment]
> I'm getting this error all the time while using chromium:
> 
> ![ss_2024_02_23_22_27_42](https://private-user-images.githubusercontent.com/14960414/307491297-ebb6b117-2333-4a16-a95e-616541fb8449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTEzNTgsIm5iZiI6MTcwODc1MTA1OCwicGF0aCI6Ii8xNDk2MDQxNC8zMDc0OTEyOTctZWJiNmIxMTctMjMzMy00YTE2LWE5NWUtNjE2NTQxZmI4NDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA1MDQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MzM2NjNmMmM4YjdkYTQwMzgxMzU1ZTVmZTk2NGFkZDA3NWRkYWEzNGQxNDIyOGYxNWIwYTQyMmQwMzQyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SN8F5gMsqkji1KdP0qlfL_NyANs8r8u3N-s1fiFdZg)

That indeed sounds like the same issue for xdg popups and could likely be solved the same way: by delaying `popup_unconstrain()` to the first commit rather than when creating the popup.

**Comment by Consolatis** [comment]
- #1558

I added the fix for layershell clients like waybar and also for the usual popup case so Chromium should now also be fine.

Testing would be much appreciated so that we can include the fix in the next release.
