### ISSUE TITLE
Cursor disappears when closing wayland clients (reappears when cursor is moved again)

### ISSUE THREAD

**Issue by charbelnicolas** [labwc/labwc#1393]
When closing kitty or chromium with their wayland clients, the cursor disappears. It only shows back again if the cursor is moved. This does not happen when using chromium with Xwayland.

**Comment by Sinaaaa** [comment]
Aye this is happening all the time with various other things as well, such as closing rofi with 'esc'.

**Comment by Minda1975** [comment]
Same here in Artix and labwc version `0.7.0-86-g02d274e`

**Comment by johanmalm** [comment]
Thanks for reporting. Let me know if there is a case I've missed.

**Comment by charbelnicolas** [comment]
Worked out pretty good, thank you!
