### ISSUE TITLE
Applications overlap bottom-placed-status-bars (waybar, sfwbar) at launch.  However, they don't overlap top-placed status bars.

### ISSUE THREAD

**Issue by orchardstreet** [labwc/labwc#1399]
This can be annoying for those who prefer bottom-placed status bars.  Status bars are most traditionally at the bottom.  Sfwbar is at bottom by default for example.  So I think it'd be nice if labwc prevented overlapping bottom status bars on application launch, like it currently does if a status bar is at the top.

I was told via IRC that labwc may only be checking not to overlap status bars on the left and top because of the "'titlebar issue".  Indeed, programs don't overlap status bars that are at the top of the screen, unlike the bottom.

Thanks :)

**Comment by johanmalm** [comment]
IIRC we just move to make sure top/left in not outside.
I guess it's only a problem if you have the panel in the "bottom" layer... and at the "bottom" of the screen.

Try:

```
function("SfwbarInit") {
  SetBarId "bar-0"
  SetLayer "top"
}

window {
  -GtkWindow-direction: bottom;
}
```

I suppose we could resize windows on launch to always fit within the output... I think I would quite like that actually regardless of the panel issue.
