### ISSUE TITLE
Keyboard layout is stuck in Great Britain English and I can't change it to US

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#1400]
I have my /etc/locale.conf set to `LANG=en_US.UTF-8` however whenever I load up labwc it defaults to British English, and screws up my keyboard: multi-fn layered keyboard, keybindings are producing incorrect symbols in Labwc.

going into labwc-tweaks and changing they keyboard layout to us English does *not* fix the problem.

I'm not familiar with any rc.xml options (either in labwc or openbox) that will let me assign the correct layout. This does not occur in any other compositor -- sway, hyprland, wayfire, plasma, etc -- so i assume this must be an issue with labwc itself.

just built the latest master on Arch Linux and the issue is there

**Comment by winteriscariot** [comment]
XKB_DEFAULT_LAYOUT is set in .config/labwc/environment:

```
~/.config/labwc $> grep LAYOUT environment 
## Use the XKB_DEFAULT_LAYOUT variable to set the keyboard layout. For example
XKB_DEFAULT_LAYOUT=us
~/.config/labwc $>
```

**Comment by winteriscariot** [comment]
SOLUTION: 

Removing `XKB_DEFAULT_LAYOUT=us` from my environment file corrects my keyboard issues 

So it appears like explicitly setting that env var from my ~/.config/labwc/environment file for some reason forces it into UK layout

**Comment by scottmicciche** [comment]
This happened to me and I traced it to the labwc-tweaks code:

https://github.com/labwc/labwc-tweaks/blob/master/update.c#L112

**Comment by johanmalm** [comment]
Thanks for reporting and fault finding. Fixed.
