### ISSUE TITLE
how to query current keyboard layout?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1403]
I have this in my `~/.config/labwc/environment`:
```
XKB_DEFAULT_LAYOUT=us,us(intl)
XKB_DEFAULT_OPTIONS=grp:shift_caps_toggle
```
and am able to successfully toggle the international variant (which offers deadkeys for diacritical marks) on and off by pressing `Shift`+`CapsLock`.

I'd like to be able to query current keyboard settings from a shell script. Strangely, output of `setxkbmap -query` is exactly the same for both `us` and `us(intl)`:
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us
```
Even if I run `setxkbmap -query -verbose 10` the output is the same for both keyboard settings.
 
I've scoured the internet for an answer but have found nothing helpful except for the clue that in Wayland, it's the compositor that is responsible for keyboard configuration.

Please, how do I query labwc for current keyboard layout? If labwc cannot tell me this directly, is there a file somewhere on filesystem that changes when labwc toggles between keyboard states? An Xwayland solution would be just fine. Thanks in advance for any help.

**Comment by stefonarch** [comment]
Atm there is only a indirect way, see https://github.com/labwc/labwc/discussions/951

**Comment by bdantas** [comment]
Thanks, stefonarch. Very clever, and works like a charm.

P.S. I needed to exit labwc to console restart labwc for the change to `~/.config/labwc/environment` to take effect (i.e., reconfiguring labwc by sending it SIGHUP was not enough).
