### ISSUE TITLE
tablet: Add pen/pad button bindings

### ISSUE THREAD

**Issue by jp7677** [labwc/labwc#1404]
Follow up from https://github.com/labwc/labwc/issues/1060 and https://github.com/labwc/labwc/pull/1398

We can map pen and pad buttons to mouse buttons. It would be cool to also bind actions to them. Similar like mouse bindings, but for tablet buttons. The branch mentioned here https://github.com/labwc/labwc/issues/1060#issuecomment-1786384495 already contains idea's for that.

(Tablet support for me is very much complete, so this is rather a "nice to have" feature)

**Comment by jp7677** [comment]
Based on above mentioned branch, this is probably the easiest way to allow pen/pad buttons in regular mouse bindings:

<details>

  <summary>Patch</summary>

````diff
diff --git a/src/config/mousebind.c b/src/config/mousebind.c
index c578c46..8e43a2d 100644
--- a/src/config/mousebind.c
+++ b/src/config/mousebind.c
@@ -8,6 +8,7 @@
 #include "common/list.h"
 #include "common/mem.h"
 #include "config/mousebind.h"
+#include "config/tablet.h"
 #include "config/rcxml.h"
 
 uint32_t
@@ -35,6 +36,11 @@ mousebind_button_from_str(const char *str, uint32_t *modifiers)
        } else if (!strcasecmp(str, "Middle")) {
                return BTN_MIDDLE;
        }
+
+       uint32_t tablet_btn = tablet_button_from_str(str);
+       if (tablet_btn != UINT32_MAX) {
+               return tablet_btn;
+       }
 invalid:
        wlr_log(WLR_ERROR, "unknown button (%s)", str);
        return UINT32_MAX;
diff --git a/src/input/tablet.c b/src/input/tablet.c
index 0a24d61..b4d7bea 100644
--- a/src/input/tablet.c
+++ b/src/input/tablet.c
@@ -97,7 +97,7 @@ tablet_get_mapped_button(uint32_t src_button)
                }
        }
        wlr_log(WLR_DEBUG, "no button map target for 0x%x", src_button);
-       return 0;
+       return src_button;
 }
 
 static void
diff --git a/src/input/tablet_pad.c b/src/input/tablet_pad.c
index 3c1b2a9..895574b 100644
--- a/src/input/tablet_pad.c
+++ b/src/input/tablet_pad.c
@@ -18,10 +18,6 @@ handle_button(struct wl_listener *listener, void *data)
        struct wlr_tablet_pad_button_event *ev = data;
 
        uint32_t button = tablet_get_mapped_button(ev->button);
-       if (!button) {
-               return;
-       }
-
        cursor_emulate_button(tablet_pad->seat, button, ev->state, ev->time_msec);
 }
 
````

</details>

This allows the following bindings to work just fine.
(Also no need to map `pad` in the `tablet` section)

````xml
  <mouse>
    <default />
    <context name="Root">
      <mousebind button="Pad" action="Click">
        <action name="GoToDesktop" to="left" wrap="no" />
      </mousebind>
      <mousebind button="Pad4" action="Click">
        <action name="GoToDesktop" to="right" wrap="no" />
      </mousebind>
    </context>
  </mouse>
````

But not sure if the `mouse` section is the most beautiful place for pen/pad button bindings. On the other hand, we clearly state that we only do mouse emulation for a tablet, that ofc includes the buttons....

**Comment by jp7677** [comment]
Sleeping a night over it and also playing with the bindings, I actually like it. The change is simple, no configuration changes involved (except accepting new values for mouse binding button), and also no side effects from what I saw.
If you are also ok with this approach, I'm happy to PR this.

**Comment by jp7677** [comment]
> Sleeping a night over it and also playing with the bindings, I actually like it. The change is simple, no configuration changes involved (except accepting new values for mouse binding button), and also no side effects from what I saw. If you are also ok with this approach, I'm happy to PR this.

Actually scratch that. While this works fine for any pen/pad button that isn't mapped. It would be very confusing for pen/pad button that are mapped. E.g. we cannot map Stylus to left and at the time bind W+Stylus to something else. Furthermore we allow re-mapping of default bindings, but no un-mapping.

I have a different idea though. What about just extending the list of available mouse buttons like this:

```c

	if (!strcasecmp(str, "Left")) {
		return BTN_LEFT;
	} else if (!strcasecmp(str, "Right")) {
		return BTN_RIGHT;
	} else if (!strcasecmp(str, "Middle")) {
		return BTN_MIDDLE;
	} else if (!strcasecmp(str, "Side")) {
		return BTN_SIDE;
	} else if (!strcasecmp(str, "Extra")) {
		return BTN_EXTRA;
	} else if (!strcasecmp(str, "Forward")) {
		return BTN_FORWARD;
	} else if (!strcasecmp(str, "Back")) {
		return BTN_BACK;
	} else if (!strcasecmp(str, "Task")) {
		return BTN_TASK;
	}

``` 

`BTN_SIDE` until `BTN_TASK` seem to be valid potential mouse buttons. I have a mouse here where additional buttons  are reported as `side` until `forward`. Having more mouse buttons to map to, leaves enough room to bind my 4 pad buttons to them and then the action can be bound to the mouse button as usual. I guess this is much less confusing since mouse and pen/pad buttons are not mixed and we stay true to the fact that the tablet just emulates a mouse. Having more buttons to play with is I guess also good news for regular mouse users.

**Comment by johanmalm** [comment]
Sorry it took a while to get to this. 

The last patch is probably the best. Keeps it clean.
If in the future there is a use-case for binding tablet buttons directly (without mapping) we can consider a `<tablet><tabletbind>` section then. I suspect this covers a lot of cases though!
