### ISSUE TITLE
On-the-fly keyboard layout changes?

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1407]
I can change the keyboard layout by setting XKB_DEFAULT_LAYOUT in ~/.config/labwc/environment and restarting labwc.

Is it possible to change the keyboard layout without having to restart labwc? Changing the value in environment and calling labwc --reconfigure doesn't work, and the environment file doesn't seem to be automatically monitored for changes. Updating the environment variable directly in a terminal doesn't work, either with or without a labwc --reconfigure.

I'm assuming this is possible - for some locales, people need to switch between two keymaps on the fly - but I can't see anything in the documentation other than just setting the environment variables.

**Comment by stefonarch** [comment]
Take a look t the example file:
https://github.com/labwc/labwc/blob/6cf19d1cdbffc699ca8f7899d8e2bb680474789a/docs/environment#L14

Any option can be used among the ones listed here:
`localectl list-x11-keymap-options | grep grp:`

**Comment by spl237** [comment]
Ah - while that does indeed handle the on-the-fly switching of keymaps, it doesn't solve the actual problem I am having! If the user wants to change keyboard to one not previously defined - say switching from a US to UK keyboard layout because they have plugged in a new keyboard, or as part of an initial setup wizard where the user sets their keyboard layout before setting their password for the first time - it needs to be possible for the keyboard layout to be changed to any other layout on the fly.

**Comment by Consolatis** [comment]
We do read the environment file on reconfigure and also apply it to the environment so spawing new applications after that point will include the changes.

However, we do currently not re-create the xkb layout (nor the xcursor theme). I think there is an issue for that somewhere. It should be possible to implement, although it might become a bit finicky if combined with [`layoutScope=window`](https://labwc.github.io/labwc-config.5.html#entry_keyboard_layoutscope=) as we only store the "group" modifier index per window. Thus if the new keyboard layout now suddenly changes their meaning (or even the count) things might get a bit quirky.

**Comment by spl237** [comment]
> We do read the environment file on reconfigure and also apply it to the environment so spawing new applications after that point will include the changes.

Just tried that - it doesn't seem to work.
So if I have XKB_DEFAULT_LAYOUT=gb in ~/.config/labwc/environment and hence a GB keyboard layout, if I change that line to XKB_DEFAULT_LAYOUT=us, save the file and then run labwc --reconfigure in a terminal, I still get the GB keyboard layout on newly-opened applications thereafter.

**Comment by Consolatis** [comment]
> if I change that line to `XKB_DEFAULT_LAYOUT=us`, save the file and then run `labwc --reconfigure` in a terminal, I still get the GB keyboard layout on newly-opened applications thereafter.

Right, because as said above we do not recreate the xkb state on reconfigure. `env | grep -i layout` should show the updated env var in a new terminal though. But that obviously doesn't help regarding the issue.

**Comment by spl237** [comment]
> Right, because as said above we do not recreate the xkb state on reconfigure. `env | grep -i layout` should show the updated env var in a new terminal though. But that obviously doesn't help regarding the issue.

See my edited comment above - if I do exactly that, the environment variable hasn't updated for me in the new terminal.

**Comment by Consolatis** [comment]
> > Right, because as said above we do not recreate the xkb state on reconfigure. `env | grep -i layout` should show the updated env var in a new terminal though. But that obviously doesn't help regarding the issue.
> 
> See my edited comment above - if I do exactly that, the environment variable hasn't updated for me in the new terminal.

Just tested again with `foot` in a nested labwc session and for me that works. E.g. in `~/.config/labwc/environment`: `XKB_DEFAULT_LAYOUT=de,us` -> `XKB_DEFAULT_LAYOUT=de,nl` -> `labwc --reconfigure` -> `env | grep -i layout` in the old terminal: `de,us` > spawning a new  terminal: `de,nl`. Maybe in your case the terminal emulator uses some kind of master process that keeps its environment and uses it when spawning new instances?

**Comment by johanmalm** [comment]
We ought to support this. It's one of the few things that requires a compositor re-start to take effect.

Might be as simple as called `keyboard_init()` (minus the `wlr_keyboard_group_create()`) on reconfigure.
I'm not sure how we best handle `view->keyboard_layout` if indeed `XKB_DEFAULT_LAYOUT` has changed. Maybe we just set them all to `0`?

**Comment by spl237** [comment]
> > > Right, because as said above we do not recreate the xkb state on reconfigure. `env | grep -i layout` should show the updated env var in a new terminal though. But that obviously doesn't help regarding the issue.
> > 
> > 
> > See my edited comment above - if I do exactly that, the environment variable hasn't updated for me in the new terminal.
> 
> Just tested again with `foot` in a nested labwc session and for me that works. E.g. in `~/.config/labwc/environment`: `XKB_DEFAULT_LAYOUT=de,us` -> `XKB_DEFAULT_LAYOUT=de,nl` -> `labwc --reconfigure` -> `env | grep -i layout` in the old terminal: `de,us` > spawning a new terminal: `de,nl`. Maybe in your case the terminal emulator uses some kind of master process that keeps its environment and uses it when spawning new instances?

OK, found what I was doing wrong! I wasn't thinking and was launching the new instance of the terminal from the taskbar, which is running as a different process from labwc itself, so has a different environment. If I launch the terminal from a labwc keyboard shortcut, the environment has updated as expected.

**Comment by spl237** [comment]
> Might be as simple as called `keyboard_init()` (minus the `wlr_keyboard_group_create()`) on reconfigure.

Just tried that and it doesn't seem to work, but I could have been doing it wrong!

All I did was to add `keyboard_init(g_server->seat)` to the end of the reload_config_and_theme function in server.c, and to modify keyboard_init to have an "inited" flag so that wlr_keyboard_group_create was only ever called once.

That said, looking at the code in keyboard_init, xkb_map_new_from_names is being called with an empty rule set, so I can't see how it can generate a new keymap anyway? But I've not really used these functions myself, so I may be completely wrong on that...

**Comment by spl237** [comment]
A bit more fiddling suggests that should have been `keyboard_init (&(g_server->seat))`, but it still seems to make no difference; I can now see the environment variable changing in the terminal, but the terminal is still using the original keymap.

**Comment by spl237** [comment]
Tested - works for me. Many thanks!
