### ISSUE TITLE
Touchscreen association with output device

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1422]
Under wayfire, it is possible to make configuration settings to bind touchscreens to specific output devices:

https://github.com/WayfireWM/wayfire/wiki/Configuration#input-device-specific-options

I can see the function new_touch in src/seat.c, which looks as if it does the requisite mapping, but I can't see how to set the name of the output device in the input device structure. Is it done as part of a libinput block? Or is this not yet supported?

**Comment by johanmalm** [comment]
See #1417 - thanks to @jp7677

**Comment by johanmalm** [comment]
@jp7677 Is this a discussion you want to be part of to help advise + shape.

Might be as simple as adding an optional name attribute.

If we need to create a list of config objects to match different can explain the preferred way of doing that. 

I can test this myself, so prefer if someone else takes the authoring+testing.

**Comment by jp7677** [comment]
Thanks for asking, sure, I'm happy to help.

Yes, I've indeed never considered the situation that multiple drawing tablets might need different configurations. I guess this is not that common, but this situation might occur.

I'm not that familiar with touch devices. Are we really talking about touch devices without a monitor, like an Apple Magic Touchpad? For a single device, something like `<touch mapToOutput="DP-1" />` should be fine. When multiple such devices are connected (imho not a common situation), I also think that an identifier attribute in the `tablet` (for tablets) and `touch` element would work for the configuration. That said, I don't think `name` is sufficient since users might use exactly the same device twice, so `name` wouldn't be unique. Unfortunately I don't see something like a `serial` or `id` in `wlr_input_device`  :(

If we are talking about (multiple) touchscreens (thus touch is physically linked to an output), may be the current output mapping just fails because the output comes up later than the touch device (thus `touch->output_name` contains a not yet existing output name on startup?). The "wrong" startup order happened for my tablet, that's why I added `seat_output_layout_changed()`.  If that's the case, it is worth a try to extend the switch statement in that function https://github.com/labwc/labwc/blob/master/src/seat.c#L652 with something like this for touch devices: 

```c
case WLR_INPUT_DEVICE_TOUCH:
    struct wlr_touch *touch = wlr_touch_from_input_device(input->wlr_input_device);
    map_input_to_output(seat, input->wlr_input_device, touch->output_name);
```

Eventually that is sufficient to automatically re-map the touch device to its own output once the output comes up.

**Comment by spl237** [comment]
> Thanks for asking, sure, I'm happy to help.
> 
> Yes, I've indeed never considered the situation that multiple drawing tablets might need different configurations. I guess this is not that common, but this situation might occur.
> 
> I'm not that familiar with touch devices. Are we really talking about touch devices without a monitor, like an Apple Magic Touchpad? 

No, just the opposite! There are various LCD panels available for the Pi with built-in touch elements, and it is possible to connect more than one to the Pi at a time. (Not many people do this, admittedly, but enough do that we need to handle it.)

>For a single device, something like `<touch mapToOutput="DP-1" />` should be fine. When multiple such devices are connected (imho not a common situation), I also think that an identifier attribute in the `tablet` (for tablets) and `touch` element would work for the configuration. That said, I don't think `name` is sufficient since users might use exactly the same device twice, so `name` wouldn't be unique. Unfortunately I don't see something like a `serial` or `id` in `wlr_input_device` :(

Yes, this is indeed a possible problem if you have multiple identical touch devices connected. To avoid it, we have modified the kernel to amend device names so that they will always be unique - https://github.com/raspberrypi/bookworm-feedback/issues/138

**Comment by jp7677** [comment]
Thanks for the clarification. Here is to hoping that `wlr_touch->output_name` ( https://github.com/labwc/labwc/blob/master/src/seat.c#L277 ) already contains the correct output name. Are you able to validate this? My suggestion above is based on that, but I couldn't find any documentation that explains the meaning of this field. So I don't know if this is correct.

**Comment by spl237** [comment]
I don't know, and don't have the hardware with me to test - I can try it on Monday and see what happens!

**Comment by jp7677** [comment]
What mean is: if the input device already knows to which output it belongs (thus `touch->output_name` already contains the output name you would configure manually otherwise), we can just use that info to bind to the correct output.without any manual configuration.

**Comment by tokyo4j** [comment]
I found KWin's code which seemingly tries to match a touchscreen with an output:
https://github.com/KDE/kwin/blob/a89d1f80586d8797a95f66130447f7c49b080ac6/src/backends/libinput/connection.cpp#L583-L660

**Comment by jp7677** [comment]
> For my Envy 13 x360 laptop, `touch->output_name` is null, unfortunately.

Thanks for the feedback. Could you please test this PR https://github.com/labwc/labwc/pull/1426 ? With this PR you should be able to map your touch device to an output. I haven't done any heuristics for other output detection like the KDE people did. Tbh, I would prefer  to not do this here. 
This PR also doesn't add  any device name distinction. This might be material for a follow-up.

**Comment by jp7677** [comment]
Related: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/2945 and https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/930
But as found by Consolatis , current `touch->output_name` is only used when running nested (https://github.com/labwc/labwc/pull/1426#discussion_r1451611245), so in fact `touch->output_name` doesn't provide any useful information at the moment for the scenarios mentioned here.

**Comment by spl237** [comment]
At a slight tangent - that is the second reference I have seen recently to running labwc "nested" - what exactly does that mean? I assume it is starting a second session of labwc from inside another session - is that the case? If so, how do you do it?

**Comment by johanmalm** [comment]
Yes. Just issue the command “labwc”. If you run labwc from a terminal you can see debug logs in real time which can be handy for debugging.

**Comment by spl237** [comment]
As a suggestion - would it perhaps be possible to support multiple touch devices by a mechanism whereby the entries in rc.xml, instead of being

`<touch mapToOutput='DSI-1'>`

were something like

`<touch inputDevice='touch_device1' mapToOutput='DSI-1'>
<touch inputDevice='touch_device2' mapToOutput='HDMI-1'>`

where the inputDevice string is the device name as reported by libinput?

**Comment by spl237** [comment]
I think that would make sense, yes.

**Comment by jp7677** [comment]
The question in that case is I think still how to correlate the `wlr-input` devices to `libinput` devices when two devices have the same vendor/product/name attribute.

**Comment by jp7677** [comment]
> The question in that case is I think still how to correlate the `wlr-input` devices to `libinput` devices when two devices have the same vendor/product/name attribute.

Sorry, I should do more research. There is `wlr_libinput_get_device_handle(dev)` which does exactly what I was questioning. That said, as far as I'm seeing, `libinput` also give you only name/product/vendor and additionally the sysname (e.g. `event5`). Looking further though, there is `libinput_device_get_udev_device(handle)` (requires linking with `libudev`!) which allows access to udev properties like device path which from my understanding contains unique elements that don't change between reboots. So may be `name` can be added for simple distinction between devices (also covers the Pi) and additionally (optionally) something from `udev` for separation of multiple identical devices.

**Comment by johanmalm** [comment]
> Edit: Not sure though if adding another dependency is justified for this fallback.

`wlroots` already has udev as dependency. Would patching `wlroots` be a good option? I have not (yet) given it any consideration, so am not suggesting it as a preferred option.

**Comment by jp7677** [comment]
> This raises again the question if we should instead hook all that stuff into the libinput category rather than having an own one for touch. Something like
> 
> ```
> <libinput>
>   <device name="touch_device1" mapToOutput="DSI-1" />
>   <device name="touch_device2" mapToOutput="HDMI-A-1" />
> </libinput>
> ```

Yes. The other way around would probably also make some sense, so eventually something like this:

```xml
<mouse name="My Mouse" port="USB1-5">
  <doubleClickTime>500</doubleClickTime>
  <scrollFactor>1.0</scrollFactor>
  <libinput>
    <naturalScroll></naturalScroll>
  </libinput>
</mouse>

<touch name="My Touch" port="USB1-1" mapToOutput="" >
  <libinput>
    <disableWhileTyping></disableWhileTyping>
  </libinput>
</touch>

<tablet name="My Tablet" port="USB1-2" mapToOutput="" rotate="0">
  <area top="0.0" left="0.0" width="0.0" height="0.0" />
  <map button="Tip" to="Left" />
  <map button="Stylus" to="Right" />
  <map button="Stylus2" to="Middle" />
</tablet>
```
(may be even without the  `<libinput>` outer elements, thus e.g. `<disableWhileTyping>` directly within `<touch>`)
PS: Currently there isn't any `port` property unfortunately.

**Comment by spl237** [comment]
This works fine for me - many thanks.
