### ISSUE TITLE
Document new root window menu stuff

### ISSUE THREAD

**Issue by Joshua-Ashton** [labwc/labwc#143]

**Comment by johanmalm** [comment]
@bi4k8
There is quite a bit to document in `git diff 8eab1e8..a9f11c5`.

- `labwc-actions(5)`
- `<mouse><context><mousebind>` section and `menu.action` in `labwc-config(5)'
- Reflect the new default mouse section in rc.xml.all https://github.com/labwc/labwc/blob/d568c60003805d225abadb58414b672fc1315283/docs/rc.xml.all#L116

I've not been able to keep up this week. Can have a go at doing it, but don't want to duplicate effort if you are :smile:

**Comment by bi4k8** [comment]
I'll write some docs this weekend.

**Comment by johanmalm** [comment]
Cool. I've just done a tiny bit on `rc.xml.all`. Will push shortly.

I've just looked through the code. I think these are it:

Add mouse contexts
- Client
- Frame
- Desktop (Same as Root?)
- Root

New config-actions:
- Focus
- Iconify
- Raise
- Resize

**Comment by johanmalm** [comment]
@bi4k8 Would you mind casting your eyes over my last few commits.

**Comment by bi4k8** [comment]
Looks good in general; I've made a couple specific comments inline.

**Comment by bi4k8** [comment]
PRs #156 and #157 should cover these new features--is there anything left that's slipped through the cracks?

**Comment by johanmalm** [comment]
@bi4k8 Thanks. I'll have a look over the next couple of days and will close this issue with done.

**Comment by johanmalm** [comment]
Complete
