### ISSUE TITLE
[Idea] Move wiki repository tab to labwc.github.io

### ISSUE THREAD

**Issue by ludg1e** [labwc/labwc#1436]
Currently I see that under the wiki tab on this repository there's only the list of distributions that have labwc packaged.
I suggest moving that list to labwc.github.io (maybe adding a new section to the getting-started page) and just leave on the wiki tab a note like: "See labwc.github.io" or even disable the wiki tab under repository settings maybe.

**Comment by redtide** [comment]
It is stated that the page is community-maintained, how community could contribute if you move it to a website? Via pull requests?

The wiki here is like a sandbox where to put ideas or contribute without much effort, so it makes  sense to keep it as it is IMO.

And I'm not even a Gollum wiki fan :)

**Comment by ludg1e** [comment]
I was meaning as website the labwc website, https://labwc.github.io. The source code is at https://github.com/labwc/labwc.github.io

Also, true, gonna move to discussions
