### ISSUE TITLE
Error building on Alpine Linux

### ISSUE THREAD

**Issue by Username58260** [labwc/labwc#144]
I am attempting to build labwc on Alpine Linux and get the following error when running `ninja -C build`

![FileName__0](https://user-images.githubusercontent.com/95015583/144633006-6aa5c260-c8a5-434a-9665-aee2ff808f35.jpg)

**Comment by bi4k8** [comment]
This looks to be [this issue](https://stackoverflow.com/questions/40515557/compilation-error-on-clock-gettime-and-clock-monotonic/40515669); we can either change our C standard or add `#define _POSIX_C_SOURCE 199309L` before `#include <time.h>` in `cursor.c`.

**Comment by johanmalm** [comment]
I think I have had this with musl before.
Does `#include <sys/time.h>` after `#include <time.h>` help?
If so, that could be an easy fix.

**Comment by johanmalm** [comment]
I've tested with `docker`. Works fine now.
