### ISSUE TITLE
leafpad crashing under labwc 0.7.0 (segfault?)

### ISSUE THREAD

**Issue by ahesford** [labwc/labwc#1445]
### Discussed in https://github.com/labwc/labwc/discussions/1444

<div type='discussions-op-text'>

<sup>Originally posted by **ludg1e** January 16, 2024</sup>
OS: arch linux
labwc 0.7.0
Virtualbox

Tried running leafpad and basically crashed
I have xorg-xwayland installed and the labwc build (AUR) has xwayland enabled
Crashes as well when trying to run xterm and chromium (xwayland)

Log with `labwc -s leafpad 2> labwc-log.txt`: https://paste.centos.org/view/raw/edd8f1e7

It basically crashes instantly and I see this
![image](https://github.com/labwc/labwc/assets/77110723/412e467a-02da-44c5-818e-7d338ace6d70)

Log with `labwc -d -s leafpad 2> log.txt`: https://paste.centos.org/view/raw/f8b17dd0
![image](https://github.com/labwc/labwc/assets/77110723/21a74f35-9fc0-455a-9c94-75cca2de9743)</div>

**Comment by ahesford** [comment]
I cannot reproduce this using leafpad in a nested session or urxvt in a standalone session on the console. In both cases, I can launch labwc 0.7.0 (as packaged on Void Linux) or a build of the current master branch.

**Comment by Consolatis** [comment]
There seems to be something going on with wlroots 0.17 and virtualized GPU drivers.
Maybe some env vars from https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md may help?

E.g. `WLR_EGL_NO_MODIFIERS=1` and / or `WLR_DRM_NO_MODIFIERS=1` and / or `WLR_DRM_NO_ATOMIC=1`.
You could also try to use software rendering via `WLR_RENDERER=pixman`.

**Comment by ludg1e** [comment]
By setting WLR_EGL_NO_MODIFIERS=1, WLR_DRM_NO_MODIFIERS=1 and WLR_DRM_NO_ATOMIC=1 here's the log
It's a 20MB log, kinda crazy though: https://fromsmash.com/labwc-14xx

Running `gdb --args labwc -d -s leafpad, r, bt` it says no debugging symbols found in labwc

**Comment by stefonarch** [comment]
As said here on labwc 0.7.0-59-g417fa21 with AMD Gpu same with xterm, no backtrace, while no issue with leafpad. Xterm opens a fraction of seconds.

**Comment by ludg1e** [comment]
Seems to be happening on virtual guests (VMware too). Already reported on wlroots (https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3788)
This issue didn't happen on labwc 0.6.6, so it could be either a labwc 0.7 issue or an upstream wlroots 0.17 issue

Related: #1361

**Comment by johanmalm** [comment]
@ludg1e If you bulid with commans below you'll get debug symbols for both labwc+wlroots. It also enables ASAN which means you get a backtrace on crash.

```
meson setup --force-fallback-for=wlroots build/
meson configure -Db_sanitize=address,undefined build/
meson compile -C build/
```

If you then run with `./build/labwc 2>log.txt` and provide that here (or possibly even better - on the `wlroots` issue) that might help solve it.

**Comment by ludg1e** [comment]
@johanmalm done what you've said, now labwc doesn't crash, and leafpad just throws an error on the term (1)

Though, the log is 50 MB... https://fromsmash.com/labwc-bigga-log
1
![image](https://github.com/labwc/labwc/assets/77110723/f0abf581-9fc0-4047-8a6a-423245c9cc0b)

**Comment by ludg1e** [comment]
Will test if this happens when sway 1.9 (based on wlroots 0.17) releases

**Comment by ludg1e** [comment]
Can confirm it also happens with Sway 1.9, so it's an upstream wlroots 0.17 issue

**Comment by Consolatis** [comment]
Tracked in
- #1829
