### ISSUE TITLE
Questions (programming)

### ISSUE THREAD

**Issue by droc12345** [labwc/labwc#1454]
I am trying to figure out where a few things are, in an earlier version (pre scene) I had patches for changing alpha on windows, but I'm not sure where the data for that is now. Any hints would be appreciated.
I'm looking to do something like have non-focused windows be partly transparent.

I would like to add/modify the change workspace to skip empty (no windows) workspaces
OR
add/modify the next window to look at all windows no matter the workspace.

I'm not asking for anyone else to do it, I'm just needing to know where to look.

Thanks

**Comment by johanmalm** [comment]
Regarding desktop_cycle_view() and osd.c I can do some refactoring first (on my TODO list).

We need to common-ize those two before changing view-criteria.

Think I already started that on a branch somewhere. Will have a look Mon/Tue

**Comment by droc12345** [comment]
That would be nice, I assume keep the old behavior and have a new option to see all workspace/windows.

Looking at sway has given me some ideas as to how to implement opacity.
But I have to think about how to set options to use it properly.
Points to consider....
Can all windows but focused be opaqued to some value?
Can opacity be set (config option) for some windows and can it be easily changed or toggled?
I'm looking at having config option(s) for setting.

Thanks for the replies

**Comment by ahesford** [comment]
The function `view_set_activated` is called when windows change focus, so you can set opacity there.

You can define arbitrary opacity values to, *e.g.*, set, increment, decrement or toggle opacity, and then you can bind these as desired, including to window actions that can force them on certain windows when created.

**Comment by johanmalm** [comment]
`add/modify the next window to look at all windows no matter the workspace` should be easy following #1479

**Comment by droc12345** [comment]
applying patch gives me a segment violation.

as soon as I trigger the action, it immediately seg faults and goes back to cmdline.
It doesn't even show a highlight of the window, so something in the way the list is gathered is my best guess.
But I haven't checked the code that much, just a gut feeling.

I'll look at it later, it's given me a direction to go, so I'm happy.
