### ISSUE TITLE
Should move/resize on an inactive window activate that window?

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#1459]
I realized that openbox behaves differently in that case in that it activates the window being resized, and that makes sense to me.

https://github.com/labwc/labwc/assets/4444593/fe3298ae-37f5-48a7-b650-fb803fe93396

**Comment by Consolatis** [comment]
We should do that, at least that is what docs/rc.xml.all does (via `A-Left` / `A-Right` on the `Frame` context and via `TitleBar` for dragging that one. I am not sure if the `TitleBar` context matches the invisible resize area around the window though.

I also didn't verify if `docs/rc.xml.all` is in sync with our hardcoded defaults.

**Comment by Consolatis** [comment]
Its missing a `Raise`

We should likely test if `labwc -C /dev/null` and `labwc -c docs/rc.xml.all` works correctly.

**Comment by daniel005007** [comment]
hi. sorry for the off-topic, but can you tell us which panel/bar you're using and share its configuration file?
