### ISSUE TITLE
Selection in alacritty broken by latest commits

### ISSUE THREAD

**Issue by Joshua-Ashton** [labwc/labwc#146]
Doing selection in alacritty doesn't stop doing it after you release the mouse anymore

**Comment by bi4k8** [comment]
Can you reproduce this behavior with `labwc -c /dev/null` (to use the default built-in configuration)?

if not, you'll need to include your `rc.xml` to help reproduce and fix this.

**Comment by ARDiDo** [comment]
I can replicate this, but I'm not entirely sure this is a labwc problem. I experience the exact same problem on other wayland compositors, as well as on Xorg.

**Comment by johanmalm** [comment]
This is working fine for me now. I'll close for now assuming it's overtaken-by-events, but please do say if you don't think it is.
