### ISSUE TITLE
DPMS support for screen blanking?

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1477]
labwc doesn't seem to support this, as far as I can tell?

Wayfire allows you to set the DPMS timeout to enable or disable screen blanking in its idle plugin - https://github.com/WayfireWM/wayfire/blob/master/plugins/single_plugins/idle.cpp

Is there a way of doing this in labwc?

**Comment by ahesford** [comment]
You can use `wlopm` to toggle power to displays, and `swayidle` can do this for you after idle timeouts.

**Comment by spl237** [comment]
OK, thanks - will give that a go...

**Comment by scottmicciche** [comment]
wlopm does not trigger dpms on my system, but sway power off does.  I've been trying to get wlopm to trigger dpms, so I'll follow this conversation as I might be missing something.

**Comment by johanmalm** [comment]
Just to add a couple of points to @ahesford's response...

1. DPMS refers to VESA Display Power Management Signaling which is a deprecated standard. 
2. We support the `wlr-output-power-management`, `idle-inhibit` and `ext-idle-notify` protocols to achieve a similar outcome (hence the sign-post to the `wlopm` and `swayidle` clients).

Ref:
- https://github.com/labwc/labwc/blob/9ecd8c2b43991132a6454091944f66a82bea862c/docs/autostart#L28-L34
- https://en.wikipedia.org/wiki/VESA_Display_Power_Management_Signaling
- https://github.com/swaywm/sway/pull/7083
- https://wayland.app/protocols/wlr-output-power-management-unstable-v1
- https://wayland.app/protocols/ext-idle-notify-v1
- https://wayland.app/protocols/idle-inhibit-unstable-v1

**Comment by scottmicciche** [comment]
Thank you for the clarification, John.  That code bit is exactly what I have in place.  My screen blanks for sure and I can simply turn the monitor off with the power button.  Zero issues with labwc, nothing breaks or crashes when I turn the monitor back on.  Whatever sway does in its power off, triggers my monitor to sleep mode but it does not recover cleanly in sway.

**Comment by spl237** [comment]
Yes, that all seems to work fine for me - many thanks all!
