### ISSUE TITLE
client-menu

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#148]
The following actions are not supported.
- `Unshade` (because we don't do shades)
- `Drag`

**Comment by ahmadraniri1994** [comment]
Is there a kind of "client-menu" ? Like when we right click on window then we see "maximize, minimize, close and resize).

**Comment by johanmalm** [comment]
Use intend to do a client menu, but not sure when and how.

**Comment by johanmalm** [comment]
Added to https://github.com/labwc/labwc-acceptance-criteria/blob/main/TODO.md so will close this for now.
