### ISSUE TITLE
Resize-handles only appear on one screen when an application spans two windows

### ISSUE THREAD

**Issue by lurch** [labwc/labwc#1486]
I'm using Labwc (built from `master`) running on a Raspberry Pi 4. I have two monitors plugged in (one is 1440p and the other is 1080p - I don't think this has any impact on this bug, but mentioning it just in case!).
If I open a window e.g. file-manager, then if the window is entirely within the left-monitor or entirely within the right-monitor, then the window-resize handles work correctly on every part of the window border. But if I have the application window straddling both monitors, then the resize-handles only appear on one monitor, and on the other monitor the window doesn't have resize-handles on the window border. It appears to be the monitor that contains the "largest" part of the window, that's the one that gets the resize-handles.

I.e.
* if the window is 100% within monitor 1, then the resize-handles work everywhere on monitor 1
* if the window is 70% within monitor 1 and 30% within monitor 2, then the resize-handles work on monitor 1 but don't appear on monitor 2
* if the window is 30% within monitor 1 and 70% within monitor 2, then the resize-handles don't appear on monitor 1, but do work on monitor 2
* if the window is 100% within monitor 2, then the resize-handles work everywhere on monitor 2

**Comment by Consolatis** [comment]
You mentioned a file-manager, does it use server or client side decorations and does the behavior differ between the two?

When using server side decorations there is an invisible resize area around the window. The resize cursor is set on both, the invisible resize area and the borders themselves. Is this happening for both or just the invisible area around the window?

**Comment by lurch** [comment]
@spl237 tells me that we're using server-side decorations, and we're seeing the same behaviour for both the borders themselves and also the invisible resize area.

**Comment by Consolatis** [comment]
Hm.. right. We restrict the invisible resize area to the usable area of `view->output` so we
- don't overlay bottom layer panels
- don't leak the invisible resize area into a neighboring output

I had a quick test nested and the window can actually be resized on the 2nd output but you'd have to hit the (potentially very small e.g. 1px wide) border itself to do so. 

I am not sure how to tackle this properly, we might need to have a list of outputs the window is currently visible on (currently we only have the one where the majority of the window is in) and then include that 2nd output in the condition.

I think we do have logic like that for the wlr-foreign-toplevel protocol already (so panels can be configured to only show the windows on the output where the panel is). Maybe we can generalize that one a bit and then use it for both. wlroots 0.18.x also brought changes to scene node internal output lists so maybe we could also use those directly.

With the following patch the invisible resize area can be debugged a bit easier:
```diff
diff --git a/src/ssd/ssd_extents.c b/src/ssd/ssd_extents.c
index 9a926a2b..0c42a624 100644
--- a/src/ssd/ssd_extents.c
+++ b/src/ssd/ssd_extents.c
@@ -11,7 +11,7 @@ static struct ssd_part *
 add_extent(struct wl_list *part_list, enum ssd_part_type type,
 		struct wlr_scene_tree *parent)
 {
-	float invisible[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
+	float invisible[4] = { 0.0f, 0.5f, 0.0f, 0.5f };
 	struct ssd_part *part = add_scene_part(part_list, type);
 	/*
 	 * Extents need additional geometry to enable dynamic
```

**Comment by Consolatis** [comment]
- #1491

Testing would be appreciated.

**Comment by Consolatis** [comment]
Should be fixed on latest master. Please comment if not.

**Comment by Consolatis** [comment]
> However, if the right-hand border of the application window is exactly on the HDMI-A-1 / HDMI-A-2 border, then I get no resize-cursor for the right-border of the application window, on either monitor. This means that if I "accidentally" resize the right-edge of the application window so that it lands on the border between the monitors, there's then **no** way to subsequently move (resize) the right edge of the window after this

This is a deliberate decision to prevent windows that are for example snapped to the right edge of the left monitor leaking their resize handles into the neighboring monitor. If am not sure how we could detect if such a position of a window happened by accident or with an action like `GrowToEdge` or `MoveToEdge`. Workarounds like mirroring the resize area to the inside of the window in such cases feel not that great for UX as it would prevent users interacting with potential scrollbars or similar.

> it seems my only option is to move the _entire_ window by dragging the application title-bar to a new position.

A small part of the right bottom/top corners should also still be usable to resize. You could also use `Alt-RightMouseButton` in the default config AFAIR.

**Comment by spl237** [comment]
> > However, if the right-hand border of the application window is exactly on the HDMI-A-1 / HDMI-A-2 border, then I get no resize-cursor for the right-border of the application window, on either monitor. This means that if I "accidentally" resize the right-edge of the application window so that it lands on the border between the monitors, there's then **no** way to subsequently move (resize) the right edge of the window after this
> 
> This is a deliberate decision to prevent windows that are for example snapped to the right edge of the left monitor leaking their resize handles into the neighboring monitor. If am not sure how we could detect if such a position of a window happened by accident or with an action like `GrowToEdge` or `MoveToEdge` or mouse resistance on the screen edge. Workarounds like mirroring the resize area to the inside of the window in such cases feel not that great for UX as it would prevent users interacting with potential scrollbars or similar.

I think this is sensible - having resize handles on a different monitor from the window being resized is just going to lead to confusion. I don't think it's a problem.

**Comment by lurch** [comment]
> Workarounds like mirroring the resize area to the inside of the window in such cases feel not that great for UX as it would prevent users interacting with potential scrollbars or similar.

Ahh, that's a very good point which I hadn't considered :grinning:
