### ISSUE TITLE
Inconsistency: using placement="cursor" gap is not considered

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1494]
I've the menu and quickstarts on top left, every app I open from there by mouse click doesn't respect gap, while placement="automatic" does respect gap value.

**Comment by ahesford** [comment]
This is expected, unless the menu and quickstarts adjust the usable area of the display. Cursor placement will always center the view under the cursor, but the view will be adjusted to fit within the usable area of the output. There isn't really a good (or even consistent) way to place a view under the cursor and respect gaps between other views.

**Comment by stefonarch** [comment]
I referred actually to the gap on screen border, sure other windows can't be considered.

**Comment by ahesford** [comment]
This is definitely a placement bug.

**Comment by Consolatis** [comment]
Should be fixed on latest master. Please comment if not.

**Comment by stefonarch** [comment]
it is, thanks to you all!
