### ISSUE TITLE
Failed to render cursor buffer

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#150]
To preface this, I'm running proprietary Nvidia drivers, so I'm sorry if they're unsupported and I shouldn't be making an issue.

The compositor works fine until I open 2 instances of the foot terminal emulator, move them around and then move my cursor into the window itself. It disappears, and when I exit lab, this is the output on the screen (it's cut off by my shell):
`es/output/cursor.c:354] Failed to render cursor buffer=11.00pt/14px, dpi=91.001.80x90 (logical), DPI=91.00low`

Running labwc-git from the AUR

**Comment by johanmalm** [comment]
There are a few wlroots issues relating to cursors, for example

https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3189

If you’ve got time there are a few suggestions and you might be help diagnose it.

**Comment by johanmalm** [comment]
Have you set the output scale at all? That might affect it.

If you’re able to reproduce on sway, that would give as an indication if it’s labwc related or not.

**Comment by johanmalm** [comment]
I've close this for now assuming it's a generic `wlroots` issue. Please shout if you don't think it is.
