### ISSUE TITLE
How Do I Put Window Icon in Top Left Corner of Clients

### ISSUE THREAD

**Issue by VehementHam** [labwc/labwc#1509]
![image](https://github.com/labwc/labwc/assets/75701545/7de3db76-47b5-4cef-8efb-568fbd0c40bd)
How do I put the window icon in the top left corner of clients as seen in the picture above?

**Comment by Consolatis** [comment]
That is not possible with the labwc rendered decorations and that will likely remain that way due to the complexity involved in figuring out the right icon for a given application compared to X11.

It could technically be done by applications themselves if they use client side decorations.

**Comment by VehementHam** [comment]
Is it possible for me to change the color o f the dot in the top left color?

**Comment by VehementHam** [comment]
Or remove it?

**Comment by Consolatis** [comment]
> Is it possible for me to change the color o f the dot in the top left color?

Yes, see https://labwc.github.io/labwc-theme.5.html#entry_window.active.button.unpressed.image.color
So you could create `~/.config/labwc/themerc-override` with the content
```
window.active.button.menu.unpressed.image.color: #ff0000
window.active.button.menu.unpressed.image.color: #00ff00
```

> Or remove it?

Labwc does not yet support the `titleLayout` setting which allow for that in a straight forward fashion. In the meantime you can store your own icon in your theme directory and call it `menu.xbm` (or `menu-active.png`/`menu-inactive.png` or `menu-{active,inactive}.svg` if labwc is compiled with svg support). That includes storing a completely transparent icon. See https://labwc.github.io/labwc-theme.5.html#buttons for more information.

**Comment by VehementHam** [comment]
Thanks

**Comment by VehementHam** [comment]
Should I close?

**Comment by Consolatis** [comment]
Closing for now as the original feature request regarding application icons on the titlebar is not planned in the foreseeable future. It might change at some point if wayland protocols like https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269 gain traction.
