### ISSUE TITLE
Resistance for window edges that are covered by another window feel non-intuitive

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#1513]
Potential options:
- ignore completely covered windows by using private state of wlroots (`node->visible`) ([test implementation](https://github.com/ahesford/labwc/tree/hide-and-seek))
  This has various downsides:
  - private state
  - influenced by users setting `WLR_SCENE_DISABLE_VISIBILITY` env var
  - ignores server side decorations
  - causes shaded windows to be ignored completely, even if visible
- notify the user why the movement stopped for a bit, for example by using outlines similar to the `A-Tab` OSD
- do our own edge visible calculations on `interactive_begin()`
- disable window-edge resistance by default, at least for 0.7.1.
- other?

**Comment by ahesford** [comment]
If we don't have a good answer and want to push ahead with 0.7.1, disabling window-edge resistance by default may be a temporary option. It doesn't fix the intuition, but at least makes it opt-in.

**Comment by Consolatis** [comment]
Added as option in the post above.
