### ISSUE TITLE
Reload monitor configuration on hotplug events

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1524]
Due to labwc not containing (I think?) any code to control monitor resolutions etc, it is necessary for the user to call something like wlr-randr to configure monitors.

This can be done as part of an autostart, so if the user wishes to change the resolution of a monitor and have that new resolution load whenever the machine is rebooted, in addition to calling wlr-randr at the time the resolution change is initially made, a corresponding wlr-randr command can be included in autostart.

However, if a monitor is hot-plugged - i.e. unplugged and then immediately reconnected - this custom monitor configuration is lost, as there is no mechanism by which it can be automatically reloaded.

(In wayfire, because monitor configurations are stored as part of the general wayfire config file, on a hotplug, the previously set resolution for that output is automatically reloaded.)

Has any thought been given to implementing such behaviour? I can relatively easily simply re-run relevant calls to wlr-randr when a hotplug event occurs, but it will involve running an additional application to monitor for hotplugs and make the relevant calls, which is a bit messy.

**Comment by Consolatis** [comment]
The suggestion solution is indeed to use something like [kanshi](https://sr.ht/~emersion/kanshi/) which will monitor for new output globals and apply its stored configuration based on the output name.

**Comment by spl237** [comment]
Excellent - that looks very useful. I'll have a play....

**Comment by spl237** [comment]
Yes, that works perfectly for me - many thanks!
