### ISSUE TITLE
"Lost" windows after disabling monitor and "ghost" monitor

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#1532]
Looks pretty much like #177, but probably best to open a new issue.

It's not always reproducible. The steps that lead to the bug in the case I just encountered are not quite the same as in #177, although the starting dual-monitor setup is the same:
* Start labwc in dual-monitor mode (in my case laptop monitor on the left, external monitor on the right).
* Have a few windows open on the external monitor only (in my case a terminal running xfsettingsd and xfce4-display-settings to manipulate outputs via wlr-output-management).
* Disable the laptop monitor on the left.

In this case, some windows may disappear, but remain listed via alt-tab. Also, the last time this happened to me (maybe the other times too, but I hadn't noticed), the laptop monitor, while disabled according to wlr-randr (and the return of wlr-output-management in xfce4-display-settings), is actually ghost monitor on the right in labwc, i.e. I can move a window to the right off-screen (but not to the left).

I suspect the windows are there, but it's hard to check, as reactivating the laptop monitor moves them again.

This is with latest git-master.

**Comment by Consolatis** [comment]
> Disable the laptop monitor on the left.

How do you do this? When using the `wlr-output-power-management` protocol (via `wlopm` or the protocol itself) we only disable the output but do not remove it from the layout as far as I remember (to ensure that the windows do \*not\* change the position and are still on the same spot when then enabling the output again). If the output is instead disabled via the wlr-output-management` protocol (via `wlr-randr` or the protocol itself) the output should be removed from the layout and thus trigger the movement of the windows to the remaining outputs.

**Comment by Consolatis** [comment]
> So this would be a regression introduced by #1528, and I guess this can be closed and this discussion should be continued there instead?

Yes, that would be a better place. I'll write a new minimal PR which only returns the `failed` event and creates a new config if one of the outputs couldn't be committed. After the release I can then try to make #1528 a bit more robust.
