### ISSUE TITLE
can not disable cursor

### ISSUE THREAD

**Issue by Michael65589** [labwc/labwc#1535]
I don't want a cursor on my screen because we use an embedded device without mouse.

I add a cursor item to the .config/labwc/rc.xml

```
...
<theme>
  <cursor type="none" />
</theme>
...
```

But the cursor appears anymore
How can I switch off the cursor?

**Comment by Consolatis** [comment]
Labwc is designed as a traditional desktop compositor first and foremost so there is always a mouse cursor by default. However, applications are in control of the mouse cursor when it is over their window. So if you run some application in fullscreen and that application hides the cursor it is hidden. I don't think we support any other way to hide the cursor.

Labwc might not be the best option for your use-case. Feel free to keep experimenting with it and ask questions on how to make things work better for you though, maybe there are some missing features that would also align with our design goal.

**Comment by 01micko** [comment]
Install a transparent cursor theme. There are a few floating around the web if you search.

**Comment by Michael65589** [comment]
I think a transparent cursor can be an option. But how should I install a cursor theme?
When I start only labwc a mouse pointer appears. I think it is the default cursor, isn't it? Is there a default folder (/usr/share/icons/cursors/) where to save the transparent cursors?

**Comment by 01micko** [comment]
Usually cursors are at `/usr/share/icons/$THEME_NAME/cursors` where THEME_NAME may be an icon theme with an included cursor theme or simply just a cursor theme.

**Comment by Michael65589** [comment]
Thanks. I just tried it and it works perfektly.
I will close this issue.

**Comment by dmitry-azaraev** [comment]
If there is physically no pointers, then they generally should not be displayed, like on TV (this is kinda special / optional, as pointer can be emulated from keyboard or so, even on some oldy desktops). [I'm did not meant here labwc specifically.]

My main point, what if system still thinks what you have pointer, even if it is transparent - it still have side effects: pointer will have position and may hover any elements under it.
