### ISSUE TITLE
ToggleKeybinds: keyboardmodifier stick in wlfreerdp

### ISSUE THREAD

**Issue by dmitry-azaraev** [labwc/labwc#1537]
I'm use wlfreerdp and toggle keybinds with shortcut like W+F6. For testing it is easier to use S+F6 instead.

Once I'm press S+F6 - shift modifier stick in pressed state, until I'm did not press shift again (same for Super modifier).

However, I'm can't reproduce this in kitty, foot, chromium, so I'm very not sure what it is really labwc keyboard handling issue. Application which most requires this feature - possibly having buggy implementation, lol. :)

**Comment by dmitry-azaraev** [comment]
I'm trace problem a bit, and the problem I'm think at labwc side, I guess.

For first normal Shift keydown/keyup sequence:
1. Shift pressed: `wl_keyboard_listener::key` - OK (indicates key pressed)
2. Shift pressed: bunch of `wl_keyboard_listener::modifiers` - OK
4. Shift released: `wl_keyboard_listener::key` - OK (indicates key released)
5. Shift released: bunch of `wl_keyboard_listener::modifiers` - OK 

When we use any key-bound labwc shortcut next situation happens (assuming we pressing something like Shift+F12), it can be bound to `Debug`, or `ToggleKeybinds` is not matters:
1. Shift pressed: `wl_keyboard_listener::key` - OK
2. Shift pressed: bunch of `wl_keyboard_listener::modifiers` - OK
3. F12 pressed: (event for shortcut key is suppressed is not generated) - OK
4. F12 released: (event for shortcut key is suppressed is not generated) - OK 
5. Shift released: `wl_keyboard_listener::key` - FAIL (key event is not generated)
6. Shift released: bunch of `wl_keyboard_listener::modifiers` - OK 

`wlfreerdp` rely on key event, is then sent to remote machine, while other software i guess did not require this event, they smart enough to "unpress" key from modifiers event(s) [but this kinda dirty workaround for something].

PS: I'm not sure - is `wl_keyboard_listener::modifiers` should really be sent for every modifier? There is 7 events every time generated, looks like event designed to deliver all state at once. However I'm not familiar with all this xkb stuff.

**Comment by Consolatis** [comment]
Where do these `wl_keyboard_listener::{key,modifiers}` come from? `WAYLAND_DEBUG` from wlfreerdp or labwc internal callbacks?

**Comment by dmitry-azaraev** [comment]
I'm just printf'ed this events in wlfreerdp directly.

**Comment by dmitry-azaraev** [comment]
`WAYLAND_DEBUG=1 foot` is enough to see this thing, it is not specific to wlfreerdp.

**Comment by Consolatis** [comment]
Might be related: https://github.com/labwc/labwc/pull/1226#pullrequestreview-1726120212

**Comment by Consolatis** [comment]
> I'm just printf'ed this events in wlfreerdp directly.

Hm, in that case it is indeed weird that there are multiple wl_keyboard_modifier events, there should only be one for each modifier state change, e.g. in case of `Shift Press` and `Shift Release` there should only be two modifier events sent to the client.

**Comment by charbelnicolas** [comment]
Could this be related to https://github.com/labwc/labwc/issues/1507?

**Comment by dmitry-azaraev** [comment]
@charbelnicolas no, there is different - modifier events in this case already flow as they should, but key events (e.g. key release) doesnt not flow.

PS: Key modifier events are optional. Client might not rely on them at all, because they are already derivation from key press & release. There is no any objection to having nor process this events at all, because all clients maintain key state in one or other way. However, i guess, it is just more or less just handy event(s). Some comment in #1226 just confirm what "they are rely on key modifiers" and everything fine. But there is pure keyboard handling misconception, and/or bugs workarounding.

**Comment by tokyo4j** [comment]
Should be fixed by #2455
