### ISSUE TITLE
How can I rotate the touch input?

### ISSUE THREAD

**Issue by Michael65589** [labwc/labwc#1539]
Is there a way to rotate the touch? Can this be done by the rc.xml or should this do the touch driver?

**Comment by Consolatis** [comment]
https://labwc.github.io/labwc-config.5.html#touch

**Comment by Consolatis** [comment]
Hm.. I'd expect wlroots to handle that when the touch device is mapped to an output and the output is rotated but didn't verify that.
See https://labwc.github.io/labwc-config.5.html#touch for how to manually map the touch device to an output.

**Comment by Michael65589** [comment]
Yes you are right. My mistake. I didn't bind the touch to the output. Now it's working.
Thanks
