### ISSUE TITLE
Are two acitve windows possible?

### ISSUE THREAD

**Issue by Michael65589** [labwc/labwc#1542]
Hi,
I have an application running. Out of this application I start a second application, in my case a GStreamer pipeline. After the GStreamer started the main application is frozen.
I looked behind the scenes with lswt and saw that the GStreamer is activated and the main application not.

So my question: Is ist possible to have two windows active? And when it is possible how can I configure that?

Thanks

**Comment by Consolatis** [comment]
> in my case a GStreamer pipeline. After the GStreamer started the main application is frozen.

It should not be frozen. In the wayland case it might not get frame callbacks if its surface is completely covered by something else and thus invisible, marked as being active or not should not make any difference. What an application does in case it doesn't get frame callbacks is completely up to the application. Similar thing if an application starts another application in its UI thread and uses a blocking `waitpid(child_pid)` call or anything like that.

> So my question: Is it possible to have two windows active? And when it is possible how can I configure that?

That is more a question if two applications can receive keyboard focus at the same time and the answer to that is: no, that is not possible.
