### ISSUE TITLE
Modifiers not reported in click events on a layer-shell surface in on-demand keyboard interactivity mode

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#1554]
They are in fact sometimes reported, but rarely. I have this problem initially with xfce4-panel, but it's reproducible with a simple GTK window to which you apply `gtk_layer_init_for_window()`.

For comparison, it works pretty well with wayfire 0.8.0, although you'd better left-click on the panel first to make sure it's gained focus (which is not at all what a user expects, but hey...).

Originally reported against gtk-layer-shell, but it turns out the problem is with labwc (0.7.0, git master): https://github.com/wmww/gtk-layer-shell/issues/175

**Comment by johanmalm** [comment]
`wlroots` only broadcasts modifiers to the client with the surface that currently has keyboard-focus.

IIRC the protocol is not clear on approach here. Many compositors have opted to take the `wlroots` approach (e.g. Cosmic) - I think to avoid 'waking up' clients every time a modifier is pressed.

I'm of a mind to patch `labwc` to optionally broadcast modifiers to all clients to solve this type of problem. It would also have the benefits of all clients knowing the `keyboard-group` (e.g. what layout is in use).

**Comment by Consolatis** [comment]
> Modifiers not reported in click events on a layer-shell surface in on-demand keyboard interactivity mode

Hm.. that indeed sounds a bug from our side. Maybe it is a race condition between receiving the mouse button event vs the keyboard modifiers. E.g. if you run via `WAYLAND_DEBUG=1`, do the modifiers maybe show up after the button event?

> `wlroots` only broadcasts modifiers to the client with the surface that currently has keyboard-focus.

In this case (with on-demand keyboard interactivity) the keyboard focus should be on the layershell client, if it isn't there might be something wrong.

> I'm of a mind to patch `labwc` to optionally broadcast modifiers to all clients to solve this type of problem. It would also have the benefits of all clients knowing the `keyboard-group` (e.g. what layout is in use).

That would likely interfere with the layout-per-window setting.

**Comment by Tamaranch** [comment]
Ok so I've been fooled once again, sorry. _When_ the layer-shell surface gets the focus, the modifiers are well reported, whether in exclusive or on-demand mode. The problem is that it doesn't always get the focus as it should in on-demand mode.

This can be difficult to check with xfce4-panel, as several things interact (including overlay layer-shell surfaces for external plugins, themselves in on-demand mode), but with a simple GTK window transformed into layer-shell, it's easily reproducible:
* if you're lucky, the window gains focus on opening, and then the modifiers are well reported;
* otherwise, or if you make it lose focus by clicking elsewhere, it seems almost impossible to give it focus by clicking on it afterwards, so, in particular, modifiers are no longer reported.

This is where wayfire (0.8.0 at least) has a different behavior: if the window doesn't have focus, it's possible that a right-click on it won't give it focus, and so modifiers won't be reported (which is already a bug from my point of view). But a left-click usually (always?) gives it the focus, so that modifiers are then reported.

My use case with xfce4-panel is as follows: Ctrl + click on a plugin allows to access its options menu, if right and left clicks are already taken by main actions (typically activate a window by left-clicking and access the actions menu on this window by right-clicking for the tasklist plugin).

**Comment by Consolatis** [comment]
> * otherwise, or if you make it lose focus by clicking elsewhere, it seems almost impossible to give it focus by clicking on it afterwards, so, in particular, modifiers are no longer reported.

That sounds like an issue, indeed. I'll try to debug this in the coming days but no promises.

**Comment by Consolatis** [comment]
Should be fixed by
- #1594

Please reopen / comment if that is not the case.
