### ISSUE TITLE
Games feel jittery even running at around 100 FPS

### ISSUE THREAD

**Issue by Faugus** [labwc/labwc#1557]
I tried with KDE and this problem doesn't happen.

With VRR ON, games are buttery smooth.
I record gameplay videos and of course the VRR doesn't apply to the video and the recording is jittery/choppy.

```
[faugus@archlinux ~]$ labwc -v
labwc 0.7.0-164-g17bad48
```

This is my Environment file:
```
XKB_DEFAULT_LAYOUT=us
XKB_DEFAULT_VARIANT=intl
XCURSOR_THEME=Breeze_Snow
XCURSOR_SIZE=24
WLR_NO_HARDWARE_CURSORS=1
XDG_CURRENT_DESKTOP=gtk
```

**Comment by Consolatis** [comment]
Depending on the game `WLR_NO_HARDWARE_CURSORS` may prevent direct scanout from happen. Unless you have issue with the cursor without it I'd recommend removing the env var.

**Comment by Faugus** [comment]
I set `WLR_NO_HARDWARE_CURSORS` because in some games (like Uncharted) the mouse cursor was stuttering with VRR ON.
I just tried to remove it and nothing changed.

I tried to set -20 priority to labwc and nothing changed aswell.

**Comment by Consolatis** [comment]
Just so that we are on the same page:
- VRR on, no recording, smooth game
- VRR off, no recording, smooth ?
- VRR on, recording, gameplay smooth, recording jittery ?
- VRR off, recording, gameplay smooth, recording jittery ?

**Comment by Faugus** [comment]
- VRR on, no recording, smooth game
- VRR off, no recording, JITTERY game
- VRR on, recording, gameplay smooth, RECORDING JITTERY
- VRR off, recording, GAMEPLAY JITTERY, RECORDING JITTERY

**Comment by Faugus** [comment]
I forgot to mention that on Last Epoch, the MangoHud's frametime graph is a straight line and running at around 100 FPS and feels jittery.

**Comment by Consolatis** [comment]
Alright, so:
- VRR on smooth gameplay and VRR off jittery gameplay.
- the recording is always jittery

Do you have a chance to test the same with sway 1.9?
They are now using the same rendering backend as we do so it might shed a light on the area where we can proceed to debug.

Completely random thought:
Does the same happen when using the vulkan renderer? (`WLR_RENDERER=vulkan` in `~/.config/labwc/environment`)

**Comment by Faugus** [comment]
> Do you have a chance to test the same with sway 1.9?

I could, but not today, unfortunately.

> Does the same happen when using the vulkan renderer? (WLR_RENDERER=vulkan in ~/.config/labwc/environment)

I tried this before and it didn't change anything.

I just recorded a video to show you the jittery and looks like the recording is better now.
I think removing the `WLR_NO_HARDWARE_CURSORS` did the trick.

I'll do more tests and report back.

**Comment by Faugus** [comment]
@jp7677 I applied the patch as you suggested and it didn't change anything.

**Comment by Consolatis** [comment]
This is not exactly an area of expertise of mine, so just some more random thoughts.

AFAIR the frame rate of the recording is dictated by the recording application. On wlroots based compositors there is also the choice between using shared system memory buffers (SHM) or GPU buffer handles (dmabuf). I don't know if there are recording applications out there that make use of that.

What are you using for the recordings, OBS via screenshare portal and pipewire? If yes you could try [wf-recorder](https://github.com/ammen99/wf-recorder) for testing as well (but that only works on wlroots based compositors). OBS might also have some `wlr-screencopy-unstable-v1` protocol plugin.

Increasing the niceness of the recording application *might* also help.

**Comment by Faugus** [comment]
@Consolatis I'm using [https://git.dec05eba.com/gpu-screen-recorder/about/](url) which only uses GPU.

But as I said, recording is better now, probably `WLR_NO_HARDWARE_CURSORS` was the problem.
Check the video https://youtu.be/Z9H9afcptEE.

The gameplay (without recording and VRR) is jittery compared to KDE. 100 FPS feels like 30 FPS, while on KDE is smooth.

**Comment by Consolatis** [comment]
> @Consolatis I'm using [https://git.dec05eba.com/gpu-screen-recorder/about/](url) which only uses GPU.

This seems to grab the frames directly from the DRM plane and thus skips the whole compositor layer. Very interesting. Thanks for posting that link.

As for why its jittery during normal gameplay I am not sure. You could potentially try the [ToggleTearing](https://labwc.github.io/labwc-actions.5.html#entry_action_name=toggletearing) action.

**Comment by Faugus** [comment]
@Consolatis it worked!
When I toggle it, the game becomes smooth.
But is there a way to enabled it by default?

**Comment by Consolatis** [comment]
As far as I remember the application can [request](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/staging/tearing-control/tearing-control-v1.xml?ref_type=heads#L100) the activation of tearing. So that is something that could potentially be done via wine but I don't follow the topic so don't know what is planned there.

For [adaptiveSync](https://labwc.github.io/labwc-config.5.html#entry_core_adaptivesync) we do have a `fullscreen` option so it gets enabled automatically when an application is in fullscreen.
Maybe we could add something similar for [allowTearing](https://labwc.github.io/labwc-config.5.html#entry_core_allowtearing).

In the meantime your could potentially use a [windowRule](https://labwc.github.io/labwc-config.5.html#window_rules), e.g. something like this
```xml
<windowRule title="some game title as shown in A-Tab">
    <action name="ToggleTearing" />
</windowRule>
```

**Comment by Faugus** [comment]
```
  <windowRules>
    <windowRule identifier="*">
      <action name="ToggleTearing" />
    </windowRule>
  </windowRules>
```
That didn't work. I still need to toggle it manually.

**Comment by Faugus** [comment]
> Maybe we could add something similar for [allowTearing](https://labwc.github.io/labwc-config.5.html#entry_core_allowtearing).

I think that would be the best option @Consolatis.

**Comment by Consolatis** [comment]
> > Maybe we could add something similar for [allowTearing](https://labwc.github.io/labwc-config.5.html#entry_core_allowtearing).
> 
> I think that would be the best option @Consolatis.

Thoughts @ahesford @Ph42oN ?

**Comment by Faugus** [comment]
![image](https://github.com/labwc/labwc/assets/112667550/d90e0ec3-53fd-425e-9852-bc8cf0cb9fe9)
KDE has this option enabled by default. That's why gaming without VRR is smoother on KDE.

**Comment by ahesford** [comment]
A `fullscreen` option to `allowTearing` was part of the original PR.  We could add that option back by modifying `get_tearing_preference` in `output.c` to check for a `fullscreen` option and, if that's set, see if the active view is fullscreen; if so, it can return `true` without checking `server->active_view->tearing_hint`.

**Comment by Consolatis** [comment]
> A `fullscreen` option to `allowTearing` was part of the original PR. We could add that option back by modifying `get_tearing_preference` in `output.c` to check for a `fullscreen` option and, if that's set, see if the active view is fullscreen; if so, it can return `true` without checking `server->active_view->tearing_hint`.

Thanks!
Added #1568 based on your suggestion.
@Faugus testing the PR would be much appreciated.

**Comment by Faugus** [comment]
@Consolatis Do I need to enable something in the rc.xml file?

**Comment by Faugus** [comment]
@Consolatis it's working!
The only problem is if I'm running on fullscreen and I try to change to borlerless window, the game crashes.

**Comment by Consolatis** [comment]
> @Consolatis it's working!

Sweet, thanks for testing.

> The only problem is if I'm running on fullscreen and I try to change to borderless window, the game crashes.

Does the same happen when you use `yes` and `ToggleTearing`? And does it happen when you do no use tearing at all?

**Comment by Faugus** [comment]
@Consolatis I tried with several games.
Looks like this window problem only happens with the Wine Wayland Driver.
With Proton and regular Wine everything works fine.
Since the Wine Wayland Driver is still in development, there's no need to worry about it now.

**Comment by Consolatis** [comment]
Well, the proper solution here would actually be for the wine wayland driver to set the tearing hint itself. But having a more generic option available on the compositor level still sounds like a good idea to me. We'll likely merge #1568 in a few days after the release.

**Comment by Faugus** [comment]
Thank you so much!
