### ISSUE TITLE
Window focus doesn't change in response to touch events

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1566]
When using a touchscreen, touching the content area of a window in the background interacts with that content, but does not bring the window to the foreground.

I'd expect this to work the same as a mouse click, in that clicking anywhere in a window brings that window to the foreground.

The only way to bring a window to the foreground by touch is to touch the headerbar.

**Comment by tokyo4j** [comment]
Something like this, in addition to #1550 ?
```diff
diff --git a/src/input/touch.c b/src/input/touch.c
index 1650059..1354fa5 100644
--- a/src/input/touch.c
+++ b/src/input/touch.c
@@ -6,6 +6,9 @@
 #include "common/scene-helpers.h"
 #include "idle.h"
 #include "input/touch.h"
+#include "config/mousebind.h"
+#include "action.h"
+#include "view.h"
 #include "labwc.h"
 
 /* Holds layout -> surface offsets to report motion events in relative coords */
@@ -109,6 +112,14 @@ touch_down(struct wl_listener *listener, void *data)
 		double sx = lx - x_offset;
 		double sy = ly - y_offset;
 
+		struct mousebind *mousebind;
+		struct view *view = view_from_wlr_surface(touch_point->surface);
+		wl_list_for_each(mousebind, &rc.mousebinds, link) {
+			if (mousebind->mouse_event == MOUSE_ACTION_PRESS
+					&& mousebind->context == LAB_SSD_CLIENT) {
+				actions_run(view, seat->server, &mousebind->actions, 0);
+			}
+		}
 		wlr_seat_touch_notify_down(seat->seat, touch_point->surface,
 			event->time_msec, event->touch_id, sx, sy);
 	} else {
```

**Comment by jp7677** [comment]
I think `view_move_to_front` (https://github.com/labwc/labwc/blob/master/src/view.c#L1926) fits better, so more like:

```c
struct view *view = view_from_wlr_surface(touch_point->surface);
if (view) {
    view_move_to_front(view);
}
```

That said, I'm not sure if that snippet is sufficient for focus management and guarding. There is also `desktop_focus_view` (https://github.com/labwc/labwc/blob/master/src/desktop.c#L41), but that on the other hand might be a bit overkill for every touch-down.

**Comment by spl237** [comment]
For the time being, I've added @tokyo4j 's suggestion to the existing PR to make headerbar touches work - I've tried it here and it seems to work for me; if it turns out not to be the best solution, we've at least got all the touch stuff on the same PR for now!

https://github.com/labwc/labwc/pull/1550

**Comment by Consolatis** [comment]
Thanks! Should be fixed by
- #1550
