### ISSUE TITLE
Mouse cursor size not updated on --reconfigure

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1587]
Relatively minor issue, but if you update XCURSOR_SIZE or XCURSOR_THEME in the environment file and then call labwc --reconfigure, the mouse cursor does not change.

The environment variables are reloaded as expected, but it looks to me as if the only place those two variables are checked is in cursor_init, which is only called from server_init at startup.

Is it possible to re-call cursor_init as part of the reload on a SIGHUP? Or does there need to be a different cursor_update function to handle this?

**Comment by johanmalm** [comment]
Ah yes, we ought to get this done. On the TODO list.

**Comment by Consolatis** [comment]
> Is it possible to re-call cursor_init as part of the reload on a SIGHUP? Or does there need to be a different cursor_update function to handle this?

Sadly there doesn't seem to be a way to just update the theme / size of an existing xcursor manager so we'd need a small function that basically contains everything up to `/* Set the initial cursor image so the cursor is visible right away */`. That function can then be called on reconfigure and on `cursor_init()`. The new function would also need to clean up the old `seat->xcursor_manager` if already set (e.g. `wlr_xcursor_manager_destroy()`).
