### ISSUE TITLE
Action MoveToOutput uses name attribute twice

### ISSUE THREAD

**Issue by bnason** [labwc/labwc#1589]
The action `MoveToOutput` uses name attribute twice. I expected that the second one would be called `output` instead.

`<action name="MoveToOutput" name="HDMI-A-1" direction="value" wrap="no" />`

[Documentation](https://labwc.github.io/labwc-actions.5.html#entry_action_name=movetooutput_name=hdmi-a-1_direction=value_wrap=no)

**Comment by Consolatis** [comment]
I am not even sure this works at all, the node name should show up as `name.action` and that usually creates a new action rather than modifying the current one.

**Comment by bnason** [comment]
Attempting to use the action as described produces the following error parsing the config file
`Entity: line 1: parser error : Attribute name redefined`

**Comment by Consolatis** [comment]
- #1590

Testing welcome.

**Comment by bnason** [comment]
@Consolatis I have tested this and the action is now working.
