### ISSUE TITLE
No tray icon with Qt6 program - QSystemTrayIcon with SNI

### ISSUE THREAD

**Issue by dglava** [labwc/labwc#1597]
I have noticed that sometimes the tray icon of a Python Qt6 program isn't being displayed when running a taskbar which implements a system tray (with StatusNotifierItem). At first I thought it was an issue with Qt6 itself, but after raising a bug report[0], I was told that it's a Wayland compositor issue. I have tested it and indeed, the test program displays an icon properly on KDE Plasma for example. I have tested it with the same taskbar program (Waybar) on KDE Plasma and it's working, which seems to support the theory that it's a Wayland compositor issue. Waybar with labwc is giving me the `QSystemTrayIcon::setVisible: No Icon set.` error.

I have experienced it in Sway as well, which makes it sound to me like it might be a wl-roots problem? Before I open an issue there, I thought I should raise it here, since I initially noticed it with labwc. Is it something on labwc's end or a wl-roots issue?

Python test program:
https://gist.githubusercontent.com/dglava/b0b988da4fea78a7409698fb02a0acdd/raw/3a346bde96f051d9e8fbf383e1e442db55cde77f/gistfile1.txt

Dbus log of a broken icon:
https://gist.githubusercontent.com/dglava/354e74ff970f1b150cfb56b996453097/raw/5305c78cb9031e5fb3e8430a7a3e2194eb23bec0/gistfile1.txt

Dbus log of a working icon:
https://gist.githubusercontent.com/dglava/b20fc0fc0b35ffe8a12500d9ad7cabc6/raw/3ebf0b6f3ea1ca3999bd455b3b75c44aafa5b0ae/gistfile1.txt

[0] https://bugreports.qt.io/browse/QTBUG-122793

**Comment by johanmalm** [comment]
Interesting. Thanks for reporting.

I'm not sure, but suspect it's some environment setting or service.

I've just tried your script with `lxqt-panel`. It shows in the system tray, but I just a 'default' icon and the error message below.

```
Error on DBus request(:1.168,/StatusNotifierItem): QDBusError(org.freedesktop.DBus.Error.UnknownProperty, Property org.kde.StatusNotifierItem.IconThemePath was not found in object /StatusNotifierItem)
Service ":1.168" unregistered
```

@stefonarch @jlindgren90 I assume SNI is working with your panel setups? Any idea what might cause this?

**Comment by jlindgren90** [comment]
SNI is working fine with qmpanel. Both the panel and the applets are using Qt6 now.

FWIW, the error probably has nothing to do with labwc directly, since there is nothing Wayland (or X11) specific about SNI - it's all over D-Bus.

**Comment by jlindgren90** [comment]
I use qt6ct to set up the icon theme here.

**Comment by stefonarch** [comment]
No issues here on `lxqt-panel`, shows the volume icon, but `lxqt-qtplugin` is working here (qt6) not qt6ct.
I heard about issues with qbittorrent and generic icon, here I've no issues with is too. Strawberry is another qt6 client.

**Comment by johanmalm** [comment]
Thanks both.

Looks like it only picks up 'hicolor' on my system.

```
for path in QIcon.themeSearchPaths():
    print("%s-%s" % (path, QIcon.themeName()))
```

```
/home/johan/.icons/hicolor
/home/johan/.local/share/icons/hicolor
/usr/share/icons/hicolor
:/icons/hicolor
```

It works if you manually set the theme that you use, for example:

```
QIcon.setThemeName("Papirus")
```

**Comment by johanmalm** [comment]
> I use qt6ct to set up the icon theme here.

Oh, yes... with `QT_QPA_PLATFORMTHEME=qt6ct` in `~/.config/labwc/environment` (and then setting the icon theme in `qt6ct`) it works!!

I was still using `qt5ct`. Whoops.

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc.github.io/pull/47/files

**Comment by dglava** [comment]
Thanks for looking into this. I followed the recommendations and it's working properly now.
