### ISSUE TITLE
Cursor does not get set on desktop

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#161]
This manifests as:
- moving a cursor off of a window with a non-pointer cursor (e.g. the selection bar for a terminal) leaves the cursor set to that window's cursor while over the wallpaper
- starting labwc displays the cursor at 1x even if the display scale is set (e.g. by `kanshi`) to another scale factor

**Comment by ARDiDo** [comment]
Well, since I'm handling all of the other HiDPI weirdness, and part of this is HiDPI related, I'll try to tackle this one.

**Comment by ARDiDo** [comment]
https://github.com/labwc/labwc/commit/4ce96f75dc4e3bd08812581b8713b72eaf213089 fixed this on my end. Closing.

**Comment by bi4k8** [comment]
Are you sure that's the right commit? It seems unrelated--my guess is 7d68eeb5eb909fe6e9d13b2b8e0de8367b7635a9 (the following commit) has fixed this.

**Comment by johanmalm** [comment]
Yes, I’m sure that was just a typo.
