### ISSUE TITLE
Dragging a tiled window in nested session causes flickering

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#1621]
This issue is not visible in bare metal. 

Demo:

https://github.com/labwc/labwc/assets/22029524/9a4c5ff2-c633-4cb5-a0b7-844787138153

After some debugging, I found the cause is that `view->pending.height` is used to calculate the final position of the view in the process of applying resistance at the first call to `process_cursor_move()` after `interactive_begin()` stores `view->natural_geometry` in `view->pending`.

A small change below fixed the issue. Would it cause any side effects, @ahesford?

```diff
diff --git a/src/edges.c b/src/edges.c
index 7253569..a3f8db5 100644
--- a/src/edges.c
+++ b/src/edges.c
@@ -530,7 +530,7 @@ edges_adjust_move_coords(struct view *view, struct border edges,
 	if (view_geom->y != *y) {
 		int tshift = border.top + rc.gap;
 		int bshift = border.bottom + rc.gap
-			+ view_effective_height(view, /* use_pending */ true);
+			+ view_effective_height(view, use_pending);
 
 		adjust_move_coords_1d(y, edges.top, tshift,
 			edges.bottom, bshift, *y < view_geom->y);
```

**Comment by ahesford** [comment]
Nice find! I think your fix is correct.
