### ISSUE TITLE
NLS: "Workspace"

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#1630]
At the time of writing, `rcxml.c` at line ~1484~ contains the string "Workspace". 

Being an UI element it probably should be internationalised.

Whoops line 1384

**Comment by Consolatis** [comment]
I assume you refer to the default for the workspace prefix?
```c
rc.workspace_config.prefix = xstrdup("Workspace");
```

I guess we could indeed localize that one.

**Comment by 01micko** [comment]
Might not be worth the effort as when I start with no config there is no label "Workspace [nr]". I'm running with `it` locale and the the menu works fine but osd is rather bland. Here's a snippet of the `pot` file after doing the changes.

```pot
#: src/menu/menu.c:744
msgid "Move right"
msgstr ""

#: src/menu/menu.c:749
msgid "Always on Visible Workspace"
msgstr ""

#: src/menu/menu.c:752 src/config/rcxml.c:1384
msgid "Workspace"
msgstr ""

#: src/menu/menu.c:755
msgid "Close"
msgstr ""

```

Because the string translation is the same the existing `mo` files should 'just work`.

**Comment by Consolatis** [comment]
If you add `<desktops number="4" />` to your config it should show it.

**Comment by 01micko** [comment]
> If you add `<desktops number="4" />` to your config it should show it.

Just looking at that!

**Comment by Consolatis** [comment]
And I think by default Mouse wheel on the desktop changes workspaces.

**Comment by 01micko** [comment]
Hrm..

Here's what I have in `rcxml.c`

```c
rc.workspace_config.prefix = xstrdup( _("Workspace") );
```

It all builds fine, runs with `it` (or any supported locale should do) but fails to translate.

The comments in the `pot` and `po` files shouldn't make a difference, but I'll test that out anyway by adjusting `po/it.po`

**Comment by 01micko** [comment]
Don't know what (if anything) I did but it's working now. I changed comments on wrong file (`lt.po`, not `it.po`). `LANG=it` shown in screencap.

![workspace-it](https://github.com/labwc/labwc/assets/1019119/798fcbe6-f138-4a4b-ae89-c91634613a68)

**Comment by 01micko** [comment]
Don't know what happened but all working now, without changing comments. I think I'll just change all the comments anyway, saves hassle for translators.

![workspace-it](https://github.com/labwc/labwc/assets/1019119/750b3de9-cec6-407b-afa9-d4238907d64e)

**Comment by Consolatis** [comment]
Very nice :)

Fancy opening a PR?

**Comment by 01micko** [comment]
Working on it.

**Comment by 01micko** [comment]
Tested a few locales and all working sweet. PR very shortly after some house keeping.

![ar](https://github.com/labwc/labwc/assets/1019119/ec6596d5-ce64-4c41-8dd1-2f2f6a12a629)

**Comment by Consolatis** [comment]
Uh, is that even RTL? I didn't know that that actually works, awesome!

**Comment by 01micko** [comment]
Pretty cool eh? That's all part of the testing :smiley_cat:
