### ISSUE TITLE
Programs to enhance labwc experience.

### ISSUE THREAD

**Issue by droc12345** [labwc/labwc#1634]
As of at least conky 1.19.6 they've added the ability to use wayland. 
The main window works, is sticky across workspaces and pretty much behaves like a pane
with the ability to do normal conky stuff, ie placement, size, data, etc.
The lua components of it don't work, as they are all based on X, at least at the moment.

But I've quit using waybar, for system level display, I find conky much more flexible, for that purpose.

I also started using nwg-wrapper  ( https://github.com/nwg-piotr/nwg-wrapper ) as a replacement 
for the waybar taskbar as far as showing what's running. I run something lswt in it to show foreign toplevel info.
I never used the click stuff in waybar as I prefer keybindings. 

These 2 could be added to labwc.github.io in the integration area. 

This shows how it looks on my system
https://github.com/droc12345/images/blob/main/data/desktop.jpg

**Comment by tranzystorekk** [comment]
I'm not sure we want to curate a list of general wayland tools in the integration docs section. IIUC it's meant more as an overview of the types of tools that can be integrated and a starting point for your own config with a few simple examples.

**Comment by winteriscariot** [comment]
There is a doc page that addresses this, though it's far from complete: https://labwc.github.io/integration.html

**Comment by johanmalm** [comment]
I think a note on `conky` would be good on the integration page.

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc.github.io/pull/52

**Comment by droc12345** [comment]
Sweet.

**Comment by 01micko** [comment]
@droc12345 I've compiled conky with wayland support and am using a bunsenlabs boron config. Works well.

I have 2 outputs and want to know if you can start conky on an output other than the default in conky with wayland. Any ideas?

**Comment by 01micko** [comment]
Still can't figure out where to add output placement for conky, but I suspect it isn't supported yet.

Anyway, I've been ricing and made a bunsenlabs-boron mockup [here](https://github.com/01micko/screenshots/blob/main/2024/labwc-boron-riceriso.png). Uses `sfwbar` and `labwc`.

**Comment by droc12345** [comment]
I'm not sure if it's set to allow for other than the initial monitor, but I haven't dug in-depth looking for it.
I'll dig through the code sometime and look for it, or I'll leave a question on github. 
https://github.com/brndnmtthws/conky


Like the mockup - **two thumbs up**

**Comment by 01micko** [comment]
@droc12345 , Seems like the only way to set conky's output on wayland is to add the screen dimensions from the left _only_ using `gap_x`. For example, both of my outputs are 1920x1080 so measuring from the left, 3500px or so is reasonably sane. Thanks for taking a look.

`conkyrc` :

```
        alignment = 'top_left',	
        out_to_x = false,
        out_to_wayland = true,
	gap_x = 3520,
```

**Comment by Consolatis** [comment]
Not sure why conky doesn't support specifying the screen though, layershell supports that afair.

**Comment by 01micko** [comment]
> Not sure why conky doesn't support specifying the screen though, layershell supports that afair.

I'm not sure about that -  see https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_output

**Comment by Consolatis** [comment]
https://github.com/brndnmtthws/conky/blob/main/src/display-wayland.cc#L588 uses `nullptr` for the output in `zwlr_layer_shell_v1_get_layer_surface`. To quote from the layershell protocol:

```
         You may pass NULL for output to allow the compositor to decide which
         output to use. Generally this will be the one that the user most
         recently interacted with.
```

So conky would need to bind to the outputs first, figure out the right one based on its name and then use that output pointer for the `zwlr_layer_shell_v1_get_layer_surface()` call.

**Comment by 01micko** [comment]
That explains why wherever I start conky that output gets conky, even when saving a config change it will restart wherever my text editor is open (in relation to the output).
