### ISSUE TITLE
[Feature request]  vertical title bar

### ISSUE THREAD

**Issue by Facundo-c-c** [labwc/labwc#1651]
add an option to set the tittle bar in vertical (maybe on the left side of the window) 

why:
 
- unique feature (just a few wm has it)
- allows user config a different workflow
- looks cool

**Comment by ahesford** [comment]
You're right that this would be unique and may look cool, but I think it's well outside project scope and would require extensive rethinking of several parts of labwc.

Unless other maintainers are strongly interested, I don't think this is a likely candidate for addition.

**Comment by Consolatis** [comment]
I would not say that we will never support this or that it is out of scope for labwc but in the foreseeable future this is not something we'll likely spend any work on. We would likely also not accept PRs that implement this feature unless that PR can prove that it doesn't complicate the already quite messy SSD implementation even more. In the end the labwc maintainers are responsible for - well - maintaining labwc and we thus have to choose our battles wisely.

**Comment by johanmalm** [comment]
Agree.

We don't like saying no to feature requests, but it's a necessary part of maintain a long term project.
