### ISSUE TITLE
Strange doubleclick on title behavior

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#1657]
So this is a bit of a weird one, but I noticed this today.

I currently have the following mousebind set:

    <context name="Title">
      <mousebind button="Left" action="DoubleClick">
        <action name="Iconify"/>
      </mousebind>
      [...]
ie, doubleclick titlebar to minimize

however, I noticed that labwc seems to register any click within the application itself as a titlebar click, so long as the second click ends on the titlebar. so for instance, if I have featherpad open, I can click in the empty space next to the toolbar icons, then very quickly move my mouse to the titlebar and click a second time. if done fast enough (within the double click time window) this causes the window to iconify.

it appears that labwc is reading that first click, the one within the application content, as a click on the titlebar. double clicking within the application context (so the second click is *not* on the titlebar) behaves as expected.

latest labwc git (11b6836) on arch

**Comment by Consolatis** [comment]
Yes, I think we only use the cursor position of the second click to determine the target.
Is this something that results in unwanted behavior? E.g. is this an issue outside of manually reproducing it?

If yes we could potentially store the first target and on the 2nd click compare the two targets and if they differ do not call the bound action.

**Comment by winteriscariot** [comment]
The only reason I noticed this behavior is because it was unexpected, and a window disappeared when I didn't expect it to. This is also not the way it behaves in openbox, fwiw, so maybe worth restricting it to the titlebar imo.

**Comment by winteriscariot** [comment]
iirc, the first time i noticed, I had clicked something in the window, then went to immediately drag it, but it disappeared instead.

so in my *particular* case, could maybe not register that second click if it's a click-and-hold?

**Comment by Consolatis** [comment]
> iirc, the first time i noticed, I had clicked something in the window, then immediately went to drag it, but it disappeared instead.

That sounds like something that totally can happen. Lets fix this.

**Comment by tokyo4j** [comment]
I experienced this problem too when I first started using labwc. Setting `<mouse><doubleClickTime>` (default is `500`) to `200` mitigated this, but more sophisticated solution would be ideal.

**Comment by johanmalm** [comment]
Does #1659 solve this?

**Comment by Consolatis** [comment]
Should be fixed in latest master. Thanks for the report.
