### ISSUE TITLE
Thank you very much for your labors and project

### ISSUE THREAD

**Issue by Ved-un** [labwc/labwc#1669]
Hi. Thank you very much for your labors and project.

I would like to ask you - for example, I have a yambar panel - why if I set the window coordinates using gap from the edge of the monitor - it considers yambar as a window and makes indents from it and not from the edge?

For example, if I run Conky - everything is fine and labwc doesn't consider it as a window...

**Comment by Consolatis** [comment]
What setting exactly do you use for the labwc side and for the yambar side?
Yambar should ignore the usual gap setting when its running as a layershell client.

**Comment by johanmalm** [comment]
For layer-shell clients there is a setting called exclusive which decides if other windows should take them into account when positioned.

**Comment by johanmalm** [comment]
https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_exclusive_zone

**Comment by Ved-un** [comment]
Thanks for the info, but it must be a problem with **yambar** itself.    
I will try another panel instead of **yambar**.
