### ISSUE TITLE
[Request] Add an option to make iconified windows rendered as icons

### ISSUE THREAD

**Issue by donmor** [labwc/labwc#1675]
Please add an option to make iconified windows into icons on desktop, which can be dragged and dropped, or resumed by double-clicking. This is the default behavior of some WMs in 1990s like CDE, Windows3.1 (In fact even windows 10 do so if explorer is gone)

~~Bring me back to the good old days XD~~

**Comment by Consolatis** [comment]
The most challenging part of this would be to get the icons. We'd need to parse .desktop files and that doesn't sound like something that labwc should do. Personally, I'd just use some panel for this case which makes it easy to see all applications and un-iconify them (or `A-Tab` or a custom pipe menu that only shows minimized windows).

**Comment by donmor** [comment]
> The most challenging part of this would be to get the icons. We'd need to parse .desktop files and that doesn't sound like something that labwc should do. Personally, I'd just use some panel for this case which makes it easy to see all applications and un-iconify them (or `A-Tab` or a custom pipe menu that only shows minimized windows).

Hmm, or we can just do what windows above 95 do when explorer is down (a small bar with title and control buttons

**Comment by Consolatis** [comment]
Actually while thinking about this.. this is something that could totally be done with an external client.

It receives the window states via foreign-toplevel protocol and uses the layershell protocol to act as a desktop. When then double clicking on one of the icons the window is unminimized and activated via foreign-toplevel protocol and then hidden from the desktop.

**Comment by stefonarch** [comment]
I think the reason why now panels are used for that is simple: the desktop is mostly covered with windows usually and a bad place for any kind of launchers therefore.

**Comment by johanmalm** [comment]
Hi @donmor Agree with @Consolatis that this feels very much like client-space. Could be done with GTK3 or Qt6 without too much effort.
