### ISSUE TITLE
Waybar taskbar button is clicked when CSD window is dragged and released on it.

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#1676]
After Alexays/Waybar#3049, waybar's taskbar button is clicked when CSD windows are dragged and released on the button to maximize the window.

https://github.com/labwc/labwc/assets/22029524/fc9b9705-c371-442e-9ed4-f10b4b84114b

The problems are:
- With Alexays/Waybar#3049, waybar listens for cursor button release events rather than press events to activate/minimize/unminimize the window
- In `cursor_button_release()`, `interactive_finish()` updates the cursor focus from the grabbed CSD client into waybar, then release event is sent to waybar (see code below)

https://github.com/labwc/labwc/blob/67669dcf1e7dcc6536d02cd007c8f10aa93a7279/src/input/cursor.c#L1044-L1054

I confirmed #1564 fixes this issue.

EDIT:
Of course, just calling `wlr_seat_pointer_notify_button()` before `interactive_finish()` will work just fine.

**Comment by Consolatis** [comment]
If we do indeed change the cursor focus in `interactive_finish()` and then send a button release event that we expect to go the the CSD window that sounds wrong, regardless of other circumstances. So to me it seems like we should indeed switch the two calls around.
