### ISSUE TITLE
Shadow of close-button on fullscreen window with rounded corners

### ISSUE THREAD

**Issue by Narrat** [labwc/labwc#1682]
> Slightly hijacking this thread as reading rounded corners reminded me of something. Had a default labwc session and in the default config rounded corners are active. If a window is set to ~fullscreen~ maximized (`ToggleMaximize`) those corners won't be round anymore (dunno if that is to be expected or intended), but the shadow on the close-button (if the mouse hovers above) will still be with rounded corners.

As requested.
Just noticed this, personally I don't care about rounded corners and therefore no preference in what to expect (should the window still have rounded corners or should the shadow be drawn without).
IIRC was with a build of labwc up to d68376f2

**Comment by Consolatis** [comment]
Fullscreen or Maximized? In fullscreen there should be no buttons at all.

**Comment by Narrat** [comment]
Ah, didn't thought of the distinction. It is `ToggleMaximize`

**Comment by Consolatis** [comment]
It is a bit annoying to fix, thus added it to the release milestone after the next one so we don't forget about it.
