### ISSUE TITLE
Popups/new windows behind main window

### ISSUE THREAD

**Issue by letkan** [labwc/labwc#1696]
This happens frequently with GTK apps, I use pcmanfm for files and every time I want to for example rename a file, the popup opens behind the main window. Sometimes if I click on a text file in the file browser Geany opens it behind pcmanfm. Just now I opened a picture in Gimp and the popup for setting the color profile opened behind the main window. Is there any way I can control this? Sometimes even launching a new app it ends up behind other windows that are opened.

**Comment by letkan** [comment]
> What version of labwc is this happening with? 
0.7.1
>Do you use `<focus followMouse="yes" raiseOnFocus="yes" />` by chance?
I'm pretty sure I don't, where would those settings be?

**Comment by Consolatis** [comment]
> I'm pretty sure I don't, where would those settings be?

in `~/.config/labwc/rc.xml` (or depending on the packaging in  your distro in `/etc/xdg/labwc/rc.xml` if you don't have a local one in your home directory) See https://labwc.github.io/labwc-config.5.html#focus for what they mean.

**Comment by Consolatis** [comment]
Can you reproduce the issue when you start labwc in its default configuration like `labwc -C /dev/null`?

**Comment by letkan** [comment]
> Can you reproduce the issue when you start labwc in its default configuration like `labwc -C /dev/null`?

I'll do it this afternoon and get back to you

**Comment by droc12345** [comment]
is pcmanfm running under xwayland or wayland?

**Comment by letkan** [comment]
> is pcmanfm running under xwayland or wayland?

How could I tell? I launch it in Wayland and it's the gtk3 version so I'm guessing it's Wayland

**Comment by Consolatis** [comment]
If you press `A-Tab` it should show up as either `[xdg-shell]` or `[xwayland]` on the left.

**Comment by letkan** [comment]
> Can you reproduce the issue when you start labwc in its default configuration like `labwc -C /dev/null`?

Unfortunately I can't, with `labwc -C /dev/null` all I get is the very basic desktop and the menu only has Reconfigure and Exit so I can't launch any application to test. Unless I misunderstood something.

**Comment by Consolatis** [comment]
You can start labwc with `labwc -C /dev/null -s foot` (or whatever your terminal editor of choice is).

**Comment by letkan** [comment]
> You can start labwc with `labwc -C /dev/null -s foot` (or whatever your terminal editor of choice is).

Ok, I got it, the behavior is the same, copy/pasted a file in pcmanfm and the popup asking me to rename it went behind the main window.

**Comment by Consolatis** [comment]
Thanks for confirming,
This sounds like like some GTK applications are activating themselves via the xdg-activation protocol to be kept on top or something like that. The only other situations I can think of that could cause this is either the `followMouse` setting or having pcmanfm being set to always on top.

Can you try adding this window rule to your rc.xml config?
```xml
<windowRules>
	<windowRule identifier="*" ignoreFocusRequest="yes" />
<windowRules>
```

and then start labwc as usual to see if it fixes the issue?

**Comment by letkan** [comment]
Ok, in regards to pcmanfm, no change (scenario where I copy/paste a file), this operation launches 2 windows, one where you are supposed to rename the file and the other, which displays the progress of the operation. The first one remains behind the main window, the second one, on top. The normal behavior is, main window first, progress second, confirm/change name, last. With Gimp there is improvement, the popup for changing the profile is on top now as it's supposed to.

**Comment by letkan** [comment]
But this works better:
`<placement>
    <policy>automatic</policy> 
  </placement>`
All windows are visible, the stupid thing is that the progress window is focused instead of the name confirmation one but it's a decent compromise.

**Comment by Consolatis** [comment]
If all the cases you saw involve spawning at least two separate sub windows and then one of them being rendered behind the parent window it could theoretically also point to some bug in labwc while we try to raise all sub windows when the parent window (or one of its sub windows) gets focus.

**Comment by letkan** [comment]
> Just to clarify: this doesn't happen when just a single sub window opens on top of its parent window

It happened once with Gimp but also, as I mentioned above, it happened more then once to open a text file from the file browser in a text editor which opened behind the file browser instead of in front of it, usually when I had several other windows opened.

**Comment by letkan** [comment]
With the text editor, the first file I click opens in front  of pcmanfm, if I click another file, the editor opens it behind pcmanfm

**Comment by droc12345** [comment]
This is about the gtk+ version of pcmanfm not the qt version

How does it behave if you force pcmanfm to run in xwayland mode 
GDK_BACKEND=x11 pcmanfm

pcmanfm is an old app, that was designed to run under X, as far as I know it was never ported to 
wayland, it mostly works because of gtk+. But even with that, I always had problems making 
everything work under straight wayland.

**Comment by droc12345** [comment]
> But the issue with the text editor is unchanged.

Do you mean where you select from file manager, and then the editor opens the file?

**Comment by letkan** [comment]
So, I click a file to open, geany opens the file and gets focus; I click another file to open, geany opens file but pcmanfm stays in focus, geany is behind it. Geany version 2

**Comment by droc12345** [comment]
It sounds like pcmanfm is the problem, since it's what fires off geany. 
I'm not sure this is easily solvable from the labwc side.

**Comment by letkan** [comment]
Just tested Thunar and it behaves the same in regards to Geany

**Comment by letkan** [comment]
Mousepad editor behaves correctly.

**Comment by Consolatis** [comment]
There multiple issues here, the pcmanfm -> geany one and the pcmanfm rename dialog one.

From how I understand the pcmanfm -> geany issue (please correct me if wrong):
- pcmanfm open, geany not open
- opening a file in pcmanfm
- geany opens, loads the file and is in the foreground like its supposed to be
- switching back to pcmanfm and opening another file
- geany loads the new file but doesn't come to the foreground

If the above is correct that would mean that either pcmanfm or geany do not support the xdg-activation protocol (or it is blocked via the window rule mentioned above). That protocol allows a window to request getting raised and focused by using a `token` that was received from another application that had keyboard or mouse focus (e.g. pcmanfm). Usually in the scenario described the exchange of the token from pcmanfm to geany would take place over dbus or via an environment variable set by pcmanfm.

> Mousepad editor behaves correctly.

That would indicate that geany is the one that doesn't support the xdg-activation protocol.

I'll try to reproduce the issue with pcmanfm.

**Comment by droc12345** [comment]
> Could reproduce, if you copy a file to some directory and then copy the same file there again the "Confirm File Replacing" dialog indeed is behind pcmanfm.

Since it works once, is there something in the labwc code, that allows it to happen, 
but some bitmask, trigger, etc needs resetting after each use, and doesn't get reset?

**Comment by Consolatis** [comment]
Did some debugging:
```
00:00:09.573 [../src/view.c:2022] Moving root window 0xaaaaabdfc820 to front
00:00:09.573 [../src/view.c:1974]       moving view 0xaaaaabdfc820 'Confirm File Replacing' to front
00:00:09.573 [../src/view.c:2025] Moving child windows to front
00:00:09.573 [../src/view-impl-common.c:49] [map] identifier=pcmanfm, title=Confirm File Replacing

00:00:09.620 [../src/view.c:2022] Moving root window 0xaaaaabdde100 to front
00:00:09.620 [../src/view.c:1974]       moving view 0xaaaaabdde100 'bin' to front
00:00:09.621 [../src/view.c:2025] Moving child windows to front
00:00:09.621 [../src/view.c:1974]       moving view 0xaaaaabdf5f50 'Copying files' to front
00:00:09.621 [../src/view.c:2029] Moving originally requested child windows 0xaaaaabdf5f50 'Copying files' to front, has parent: yes
00:00:09.621 [../src/view.c:1974]       moving view 0xaaaaabdf5f50 'Copying files' to front
00:00:09.621 [../src/view-impl-common.c:49] [map] identifier=pcmanfm, title=Copying file
```

It seems pcmanfm doesn't properly set the parent on the "Confirm File Replacing" window and also spawns it before spawning the "Copying File" window. So it seems labwc is actually doing the right thing here, that "Confirm File Replacing" window doesn't appear to be a child window of pcmanfm.

**Comment by stefonarch** [comment]
>Could reproduce, if you copy a file to some directory and then copy the same file there again the "Confirm File Replacing" dialog indeed is behind pcmanfm. Not sure if this is a pcmanfm bug or a labwc bug though.

It looks like a pcmanfm flaw, as with pcmanfm-qt this works.

**Comment by letkan** [comment]
@Consolatis , all your assumptions are correct, renaming a file is a pcmanfm issue, geany not getting the focus is geany issue. I tried  a different editor (see Mousepad above) and it worked as it was supposed to.
Too bad no one bothered to fix pcmanfm, I'll use thunar/mousepad for labwc, no bugs so far
Thanks for looking into this

**Comment by Consolatis** [comment]
> Too bad no one bothered to fix pcmanfm

They might not be aware of the issue.
