### ISSUE TITLE
Labwc not respecting no-decorations flag?

### ISSUE THREAD

**Issue by delentef** [labwc/labwc#1699]
Hello,

I've been using labwc 0.7.1 on fedora 39 for about 2 weeks now and I find it very much to my liking, thanks for the awesome job!

I have coded in python a simple GTK3 splash-screen. Under XFCE the window.set_decorated(False) instruction ensured that the window had not title bar and no border; but on labwc the title and borders are still there. It's a minor annoyance, but is there a way to have them removed? Is it an expected behavior of labwc or wayland, it it an unimplemented feature yet or did I do something wrong? Thanks for any hint!

**Comment by Consolatis** [comment]
Labwc should support client decoration hints so not sure what is going on. Feel free to post your splashscreen code here and I can take a look.

**Comment by delentef** [comment]
Hello, thanks for your answer, here is my splash scren code:

```
#!/usr/bin/python3
#coding: utf-8

import sys
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk

if len(sys.argv) == 1:
    sys.exit(0)

try:
    image = Gtk.Image.new_from_file(sys.argv[1])
except:
    sys.exit(0)

#screenSize = Gdk.Monitor.get_geometry(Gdk.Display.get_primary_monitor(Gdk.Display.get_default()))
screenWidth = 1920 # screenSize.width
screenHeight = 1080 # screenSize.height
win = Gtk.Window()
win.set_decorated(False)
win.set_skip_taskbar_hint(True)
win.set_accept_focus(False)
win.set_title("Splash Screen")
win.connect("delete-event", Gtk.main_quit)
win.set_type_hint(Gdk.WindowTypeHint.SPLASHSCREEN)
win.set_gravity(Gdk.Gravity.NORTH_WEST)
win.add(image)
width, height = win.get_size()
win.move(screenWidth/2-width/2, screenHeight/2-height/2)
win.show_all()
Gtk.main()
```

**Comment by Consolatis** [comment]
It is a GTK annoyance, try adding `win.set_titlebar(Gtk.HeaderBar())` before the call to `set_decorated(False`), courtesy of malm at https://github.com/labwc/labwc/issues/1397#issuecomment-1890530745
