### ISSUE TITLE
Chromium 124 misbehaving in labwc

### ISSUE THREAD

**Issue by charbelnicolas** [labwc/labwc#1709]
I updated to chrome version 124 today and labwc started misbehaving. I don't know if it's chromium that broke or if labwc can't handle something new with chromium.

Normally I run chromium with the following arguments `chromium --gtk-version=4 --enable-chrome-browser-cloud-management` and it runs flawlessly as a wayland client `[xdg-shell]` but with Arch Linux's chromium 124 update today, when launching it with the exact same arguments, it is being treated as an xwayland application `[xwayland]`.

Here's a video:

[https://drive.google.com/file/d/1dX0SS2r90qaLpRf8eIvkPEUuMqoinwFh/view?usp=sharing](https://drive.google.com/file/d/1dX0SS2r90qaLpRf8eIvkPEUuMqoinwFh/view?usp=sharing)

Anyone getting the same issue? I'll try with another window manager and see if I get the same results. For the time being I downgraded to chromium 123 and it is working.

**Comment by Consolatis** [comment]
It is unlikely an issue with labwc itself as we didn't change anything that could trigger that. Maybe Chromium 124 started to require a newer xdg-shell version or some specific wayland protocol and falls back to xwayland if not available.

**Comment by tokyo4j** [comment]
Just force Chromium to use wayland.
For example, my `~/.config/chromium-flags.conf` (Arch Linux-only config file) looks like this:
```
--force-dark-mode
--enable-features=UseOzonePlatform,WebUIDarkMode
--enable-wayland-ime
--ozone-platform=wayland
```

**Comment by johanmalm** [comment]
Thanks @tokyo4j 

Yes, I've got a similar config file:

```bash
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

I use `Chromium 124.0.6367.49 Arch Linux` and can confirm it starts as `[xdg-shell]`

**Comment by charbelnicolas** [comment]
Well I have set the ozone platform set to wayland already on version 123 and it works (not by setting it through cli arguments but inside chromium settings). Something must have messed up in the update. I'll have to do it in the arguments now as well... Chromium is pretty glitchy when it comes to ozone platform settings.

**Comment by johanmalm** [comment]
Okay. Will close for now. 
Happy to try other settings/etc if helpful.
