### ISSUE TITLE
foreign.c maybe missing checks if view still exists

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#172]
As far as I understand, all handle_toplevel_handle_request_* callbacks are called once a wayland message for that particular request is received.
The view might have been destroyed in the meantime and thus wl_container_of(listener, ..) would return NULL (I assume) which then gets dereferenced.
I don't know enough about wlroots / labwc to be sure if that is possible but if yes all of those handlers should have a check like
```
if (!view) {
    /* Maybe log */
    return;
}
```

If that is indeed the proper way (and place) to deal with that race condition I'd add those checks and send a PR.

**Comment by johanmalm** [comment]
I agree - it feels right to add that check.

Looking at sway, they don’t seem to perform that check, which is odd.
https://github.com/swaywm/sway/blob/master/sway/tree/view.c
