### ISSUE TITLE
crash on Kill action with xwayland views

### ISSUE THREAD

**Issue by xi** [labwc/labwc#1739]
labwc crashes when I use the Kill action on xwayland views (tested with firefox, thunderbird, and xeyes). It does not crash on native wayland clients or when I manually call `pkill -SIGTERM firefox`.

**Comment by Consolatis** [comment]
Hrm, right. We just kill the pid of the wayland client which in this case is xwayland itself.

So there are two issues here:
- get the right pid (pid of the unix connection to the wayland socket for wayland native clients or `->pid` for xwayland ones)
- figure out why labwc is crashing when xwayland is killed

**Comment by xi** [comment]
Thanks for the quick fix!
