### ISSUE TITLE
menu press-drag-release doesn't select the menu item

### ISSUE THREAD

**Issue by ec1oud** [labwc/labwc#1750]
I'm very used to it working in openbox, so it feels really awkward trying to switch to labwc that I have to actually right-click, leave the menu open, and then click again on a menu item.

This applies to the desktop application menu, and menus in Qt applications (not sure if that could be a Qt bug), but not GTK applications.

**Comment by tokyo4j** [comment]
Oops, I didn't know mentioning an GitHub issue in commit message and pushing it always adds an item.

**Comment by Consolatis** [comment]
> Oops, I didn't know mentioning an GitHub issue in commit message and pushing it always adds an item in the issue.

Yeah that is a bit annoying but IMHO a GH UI issue and should not prevent us from working the way we want.

> and menus in Qt applications (not sure if that could be a Qt bug), but not GTK applications.

I vaguely remember some work around this topic about a year or so ago. I think it had something to do with popup grabs and Qt and GTK using different approaches for this is exact scenario. So it \*might\* be something that we could look into from the labwc side. This may also be different for wayland native and for xwayland windows.

**Comment by tokyo4j** [comment]
Reopened for Qt menu issue

**Comment by ec1oud** [comment]
Thanks for the quick response!  Yes that took care of the desktop menu.  In Qt widget applications it seems that the press-drag-release works the first time, but not subsequent times.

**Comment by ec1oud** [comment]
But with the same Qt application on Sway, the menu works fine every time.

**Comment by ec1oud** [comment]
I think the problem is Qt needs to see correct mouse button state for every mouse event, including mouse moves.  Don't assume that if you told us at the time that the left mouse button was pressed, that we will remember that it's still pressed while the user is dragging.  Reporting complete state in every event makes software more robust, in case some event went missing or there is some sort of bug on some system.

**Comment by tokyo4j** [comment]
The difference between labwc and sway is that labwc sends `wl_pointer.enter` to notify the client that the cursor focus is moved to the popup surface, while sway doesn't. So at least by applying the following patch labwc never sends `wl_pointer.enter` in this case and press-move-release selection always works:
```diff
diff --git a/src/input/cursor.c b/src/input/cursor.c
index df03dcf2..e89229c5 100644
--- a/src/input/cursor.c
+++ b/src/input/cursor.c
@@ -326,6 +326,7 @@ input_inhibit_blocks_surface(struct seat *seat, struct wl_resource *resource)
 static bool
 update_pressed_surface(struct seat *seat, struct cursor_context *ctx)
 {
+	return false;
 	/*
 	 * In most cases, we don't want to leave one surface and enter
 	 * another while a button is pressed.  We only do so when

```

However, I don't know what is the optimal behavior with this. The current behavior is the same as that of weston and weston seems to have the same problem.

Another finding is press-move-release selection sometimes doesn't work even at the first time. I don't know why.

https://github.com/labwc/labwc/assets/22029524/cc553671-f5fa-43db-8953-3519f095af6e

**Comment by ec1oud** [comment]
Our handling of enter events begins here:

https://code.qt.io/cgit/qt/qtwayland.git/tree/src/client/qwaylandinputdevice.cpp#n675

I see that it happens when entering the main window and also when entering the popup, and (in the debugger) this function appears to behave the same in both cases.  But it does not include button state.  And neither does pointer_motion at https://code.qt.io/cgit/qt/qtwayland.git/tree/src/client/qwaylandinputdevice.cpp#n751 ... looks like we do use stored state there, mButtons.  So probably mButtons got reset somewhere.  That happens in pointer_leave as it turns out (when it enters the popup, it leaves the main window).  So https://codereview.qt-project.org/c/qt/qtwayland/+/495622 looks related.

**Comment by Consolatis** [comment]
Thanks for the investigation. If it ends up being something that labwc is doing wrong (based on a wayland protocol or just logical sense) please don't hesitate to point it out.

**Comment by ec1oud** [comment]
Qt has a bug; https://codereview.qt-project.org/c/qt/qtbase/+/687074 fixes it on Weston.  But after applying the fix, now the bug is still there on labwc.  In fact I don't see the mouse release at all, when I press the mouse button, drag over the menu (popup window) and release.  And now I see the same issue with GTK 3 and GTK4 on labwc, but they are working fine in Weston.  (For example try gnome-text-editor and scite: both text editors that have right-click context menus with cut-copy-paste and stuff like that.  You should be able to press the right button, drag over Cut, and release, to cut the selected text.)

Currently I'm running extra/labwc 0.9.2-1 on Arch Linux.

**Comment by tokyo4j** [comment]
It's due to changes in wlroots 0.19 (#2787). I'm not sure what's the best solution for us. CC @jlindgren90

**Comment by jlindgren90** [comment]
Thanks @ec1oud for following up on this, and @tokyo4j for the mention. I'm interested to test the new Qt fix. I've been using a slightly different patch that I did not get around to submitting: https://github.com/jlindgren90/qtbase/commit/191d92b613825834e4229bcad46ddf1818985358

On the labwc side, #2787 says all that I know at this point - there are 2 wlroots commits that need to be reverted.

**Comment by ec1oud** [comment]
I didn't see whether this was reported upstream or not, so I did:  https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/4027

**Comment by Consolatis** [comment]
Lets use #2787 for further discussion so we don't have the information spread between two issues.
