### ISSUE TITLE
Steam running in big picture mode under xwayland makes waybar disappear

### ISSUE THREAD

**Issue by guzz46** [labwc/labwc#1752]
When I open steam in big picture mode, it runs under xwayland, and if I open an app like MPV in fullscreen, when I exit out of fullscreen the waybar has gone, even though its still running, when I close steam then the panel reappears again, I've made a short video of the issue below, and if I don't run steam in big picture mode then I have even bigger issues, this also happens on other panels too.

https://www.youtube.com/watch?v=WirdzEA4eZY

**Comment by Consolatis** [comment]
Yeah.. that look weird. Not sure what is going on there.

**Comment by guzz46** [comment]
When modifying waybar to run in the bottom layer the issue happens as soon as I open the steam client, it also happens if waybar is on the left of the screen or the bottom of the screen.

**Comment by Consolatis** [comment]
Llayershell clients with exclusive zone (e.g. most panels like waybar) should be hidden as soon as a fullscreen application is started. I am not quite sure why that wasn't happening with Steam before. So the behavior of it being hidden when mpv is fullscreen is intended. However when then leaving fullscreen the bar should show up again. This might have something to do with how steam big picture mode is implemented (e.g. maybe as unmanaged fullscreen), I can't really test this on my system.

If you want the panel be visible at all times you'd need to use the "overlay" layer instead which will be rendered on top of fullscreen windows.

**Comment by guzz46** [comment]
When I set the layer in waybar to overlay the problem goes away, but the only issue then is when watching a video in fullscreen a portion of the video is hidden under waybar.

**Comment by Consolatis** [comment]
> When I set the layer in waybar to overlay the problem goes away, but the only issue then is when watching a video in fullscreen a portion of the video is hidden under waybar.

Yes, that is why usually panels are configured for the "bottom" or "top" layers.

The actual question here is why steam big picture mode is not on top of the "top" layer waybar, if it was using fullscreen it should be but based on your video it isn't (at least initially). Somebody with Steam could maybe debug this a bit further, for example there might be an option to use `A-Space` to open the window menu for the Steam window and then rather than using fullscreen setting it to maximize and hide the decorations. If that works it could be set in a window rule instead of doing it manually. But I fear that it might not actually be a proper X11 window bug an "unmanaged" one where this kind of trick would not work. Maybe that is also something that could be changed somewhere within steam (e.g. "fullscreen" via "borderless fullscreen" or something like that).

**Comment by guzz46** [comment]
I'll have a play around and see if I can find something that works, but if I don't run it in big picture mode then steam just opens to the tray, and if I click on the tray icon and select library or store nothing happens, the labwc window switcher doesn't even register that steam is running, so I kind of have to run it in big picture mode at the moment.

**Comment by guzz46** [comment]
I've found a bit of a workaround, by creating a window rule that puts steam always on the bottom, the only slight issue is the window switcher doesn't register that steam is open, and when playing a game the same issue happens with the panel, so you can't "alt tab" to the steam client, because it's not in the window switcher, and if you "alt tab" out of the game you can't select the steam client from waybar because the game is on top of the bar, I'll see if I can create a window rule that resizes the steam client so it's not taking up the entire screen, and set a position where it doesn't overlap the waybar.

**Comment by tokyo4j** [comment]
I reproduced this issue, but it will take some time to debug this since I lack knowledge of xwayland.

**Comment by tokyo4j** [comment]
I found the problem is that the view for Big Picture Mode requests fullscreen before mapping.
We show or hide the top layer when a view requests fullscreen/un-fullscreen, but the view for Big Picture Mode is ignored because it's not in `server->views` yet.

**Comment by Consolatis** [comment]
> For some reason I can now run steam in normal window mode, so I don't need the window rule to keep steam below, but I found the same thing happens when launching and playing a game, when you alt tab out of the game the game is on top of waybar.

Yes, fullscreen is supposed to always on top of all layer windows < `Overlay`.
This behavior is slightly annoying though, I stumble on this as well when quickly A-Tabbing away from a fullscreen window. It is difficult to solve because we can't just use fullscreen + focused as condition (you could have a panel and fullscreen video on a second monitor but work on the first monitor).  So I am no quite sure how to tackle this issue.

**Comment by tokyo4j** [comment]
>  This behavior is slightly annoying though, I stumble on this as well when quickly A-Tabbing away from a fullscreen window. It is difficult to solve because we can't just use fullscreen + focused as condition (you could have a panel and fullscreen video on a second monitor but work on the first monitor). So I am no quite sure how to tackle this issue.

How about showing top layer if there's any windows above fullscreen window?

https://github.com/labwc/labwc/assets/22029524/cf466d70-febf-47db-bff4-748fd0c01d04

<details>
<summary>diff</summary>
```diff
diff --git a/src/desktop.c b/src/desktop.c
index e3feaa37..fecc2797 100644
--- a/src/desktop.c
+++ b/src/desktop.c
@@ -229,14 +229,29 @@ desktop_update_top_layer_visiblity(struct server *server)
 		wlr_scene_node_set_enabled(&output->layer_tree[top]->node, true);
 	}
 
-	/* And disable them again when there is a view in fullscreen */
+	/* And disable them again when there is a view in fullscreen without another view above it */
 	enum lab_view_criteria criteria =
 		LAB_VIEW_CRITERIA_CURRENT_WORKSPACE | LAB_VIEW_CRITERIA_FULLSCREEN;
 	for_each_view(view, &server->views, criteria) {
 		if (!output_is_usable(view->output)) {
 			continue;
 		}
-		wlr_scene_node_set_enabled(&view->output->layer_tree[top]->node, false);
+		bool another_view_above_fullscreen_view = false;
+		struct view *v;
+		for_each_view(v, &server->views,
+				LAB_VIEW_CRITERIA_CURRENT_WORKSPACE) {
+			if (v == view) {
+				break;
+			}
+			if (v->output != view->output || !view_is_focusable(v)) {
+				continue;
+			}
+			another_view_above_fullscreen_view = true;
+			break;
+		}
+		if (!another_view_above_fullscreen_view) {
+			wlr_scene_node_set_enabled(&view->output->layer_tree[top]->node, false);
+		}
 	}
 }
 
diff --git a/src/view.c b/src/view.c
index 19b5a33a..e9f30439 100644
--- a/src/view.c
+++ b/src/view.c
@@ -1987,6 +1987,7 @@ move_to_front(struct view *view)
 		view->impl->move_to_front(view);
 	}
 	view->server->last_raised_view = view;
+	desktop_update_top_layer_visiblity(view->server);
 }
 
 static void
@@ -1998,6 +1999,7 @@ move_to_back(struct view *view)
 	if (view == view->server->last_raised_view) {
 		view->server->last_raised_view = NULL;
 	}
+	desktop_update_top_layer_visiblity(view->server);
 }
 
 /*

```
</details>

**Comment by Consolatis** [comment]
> How about showing top layer if there's any windows above fullscreen window?

Hm.. right. I think that could work.

**Comment by tokyo4j** [comment]
> `BOTTOM` ones with exclusive zone won't be affected.

I think this is the limitation of the protocol.

As the protocol says normal windows should be between `top` and `bottom` and fullscreen windows should be in `top`, we should never show `bottom` panels when fullscreen windows are present as long as exclusive zones of `bottom` layer don't occlude fullscreen windows.

It also says the ordering within the same layer is undefined, so we can reverse the order of `top` panels and fullscreen windows, like my suggestion does. 

So I think my suggestion is the best we could do within the protocol and at least KDE Plasma (which also implements wlr-layer-shell) seems to work in this way.
Of course this will require some discussion.

**Comment by Consolatis** [comment]
> It also says the ordering within the same layer is undefined, so we can reverse the order of `top` panels and fullscreen windows, like my suggestion does.

That has been clarified in the the discussion of upstreaming the layershell protocol: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/28/diffs#0f7d62083cb06bea09093cc4019184cc26dda1da_0_135

However, regardless of what the protocol says I think its fine to make panels visible when there is a window on top of a fullscreen one. Another option could be to simply un-fullscreen when another window is going to be rendered on top but that would be even more annoying.

> We can remove the invisible exclusive zones of `bottom` panels if they are hidden by fullscreen windows, but I don't like updating `output->usable_area` and resizing windows every time the ordering of fullscreen window and `bottom` panel changes.

That wouldn't really help in this regard. I think we just have to accept that being the case and if users (like myself) are annoyed by that behavior they can configure their panels to use the top layer instead.

**Comment by tokyo4j** [comment]
I realized my statement didn't make sense. If we strictly follow the protocol, we can never raise a normal window above a fullscreen window in the first sense. Also, the protocol often uses the word "typically" to indicate it's not forcing the ordering of windows. 

Thank you for the advises anyway. I'll investigate about the protocol and possible implementations.
