### ISSUE TITLE
Shaded XWayland window on top of another XWayland gets (mouse) events

### ISSUE THREAD

**Issue by domo141** [labwc/labwc#1753]
In case where XWayland window (e.g. urxvt) is stacked on top of another XWayland window (e.g. urxvt)
and the window on top is shaded, the shaded area gets the events even when focus is moved to
the window lower in stacking order.

**Comment by tokyo4j** [comment]
> the shaded area gets the events even when focus is moved to the window lower in stacking order.

Sorry, what does "events" mean here?

**Comment by Consolatis** [comment]
> Sorry, what does "events" mean here?

from IRC history:
> \<Domo> hmm, scroll-wheel events seem to go to shaded view (just now)
> \<Domo> and not just those. cannot drag scrollbar in urxvt window when shaded view (which would unshade over the scrollbar) is on top of it

**Comment by johanmalm** [comment]
Consider `xcb_change_property()` as Openbox uses `XChangeProperty()` on shade/unshade.

`client_shade()`
https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/client.c#L3535

`client_change_wm_state()`
https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/openbox/client.c#L2502

`OBT_PROP_SETA32`
https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/obt/prop.h#L301-L303

`obt_prop_set_array32()`
https://github.com/danakj/openbox/blob/9e8813e111cbe6c1088f6abbc771a29470f05fc2/obt/prop.c#L529

**Comment by Consolatis** [comment]
Agree that this is likely the better solution but we can't really use it without creating a temporary xcb connection.
We basically need support for that in wlroots / xwm.c.

For now:
- #1778

Would appreciate testing.

**Comment by Consolatis** [comment]
Should be fixed on latest master.
