### ISSUE TITLE
Window switcher doesn't recognise MPV

### ISSUE THREAD

**Issue by guzz46** [labwc/labwc#1754]
I don't know if this is a window rule issue I've set or a bug, but the window switcher doesn't seem to recognise that MPV is open, for example if I have a browser open, a terminal open, a text editor open, and MPV open, when I "alt tab" the window switcher only shows the browser, the terminal, and the text editor, my window rule is below.

    <windowRules>
      <windowRule identifier="mpv" matchOnce="true">
        <skipTaskbar>no</skipTaskbar>
        <action name="MoveTo" x="981" y="564" />
        <action name="ToggleAlwaysOnTop"/>
      </windowRule>
    </windowRules>

**Comment by tokyo4j** [comment]
MPV is shown in the window switcher as expected with your window rule in my environment.
Is it the only `<windowRules>` in `rc.xml`? Or have you `Reconfigure`d or restarted labwc after modifying `rc.xml`?

**Comment by guzz46** [comment]
I believe its the only window rule, I've reconfigured labwc multiple times since, here's my window rule section

    # Window Rules
    #   - Criteria can consist of 'identifier' or 'title' or both (in which
    #     case AND logic is used).
    #   - 'identifier' relates to app_id for native Wayland windows and
    #     WM_CLASS for XWayland clients.
    #   - Criteria can also contain `matchOnce="true"` meaning that the rule
    #     must only apply to the first instance of the window with that
    #     particular 'identifier' or 'title'.
    #   - Matching against patterns with '*' (wildcard) and '?' (joker) is
    #     supported. Pattern matching is case-insensitive.

    
 
    # Example below for `lxqt-panel` and `pcmanfm-qt \-\-desktop`
    # where 'matchOnce' is used to avoid applying rule to the panel
    # configuration window with the same 'app_id'.

    <windowRules>
      <windowRule identifier="mpv" matchOnce="true">
        <skipTaskbar>no</skipTaskbar>
        <action name="MoveTo" x="981" y="564" />
        <action name="ToggleAlwaysOnTop"/>
      </windowRule>
    </windowRules>
</labwc_config>

**Comment by droc12345** [comment]
Does mpv have it's own window open?
And are we talking about a wayland window or Xwayland?

I have my mpv configured to not show window when playing audio files, and that won't show up in switcher.
Mine does show up when playing movies or anything where the mpv window is open.

**Comment by guzz46** [comment]
This happens when playing a video, I don't know if its an xwayland or wayland window, but the steam client shows up in the window switcher and its an xwayland window, this is on labwc 0.7.1 if that makes any difference.

**Comment by Consolatis** [comment]
The issue is likely `ToggleAlwaysOnTop`, the current master branch (and next release) should fix this.

**Comment by guzz46** [comment]
You're right, the problem goes away when I remove the ToggleAlwaysOnTop option.

**Comment by Consolatis** [comment]
> You're right, the problem goes away when I remove the ToggleAlwaysOnTop option.

Thanks for confirming.
