### ISSUE TITLE
Awkward keybinding problem

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1756]
In RPiOS, ever since we started customising the desktop, we have had the Windows key on the keyboard open and close the main application launch menu.

I have added a keybinding to our default labwc.config on Super_L, which generates the relevant call to the panel application to show or hide the menu, which works fine.

However, there are default keybindings which use the Windows key as a modifier - W+cursor snaps windows to the relevant half of the screen, for example. We'd like to keep these, as people use them, but the problem is that the initial keybinding on Super_L is triggered first, so the main menu opens (and stays open) when the Windows key is pressed and held, and then the window snaps when a cursor key is subsequently pressed.

Is there any way of making keybindings which are set up on modifier keys only not take effect until the modifier key is released if no other keys have been pressed in the interim?

This would allow me to use the Windows key in this way. So the actions would be:

Windows key pressed - Windows key released - binding on Super_L is triggered.
Windows key pressed - cursor key pressed - binding on Win + cursor is triggered, subsequent release of Windows key is ignored.

It's not a showstopper, but if keybindings on modifiers alone are allowed - and it seems they are - then at present they can trigger this multiple binding behaviour.

I'm happy to have a look at fixing this myself if it is thought that it would be useful, if someone can just give me a pointer in the right sort of direction! Many thanks in advance...

**Comment by Consolatis** [comment]
This is something that has come up before. I am not sure how we could handle that due to us processing the keybinds on press.
Maybe we could add an optional `on="release"` keybind argument or something like that.. And then check if no other key is currently pressed. However, that would then still trigger when pressing e.g. `W-Left`, then releasing `Left` and finally releasing `W`.

**Comment by spl237** [comment]
OK, if others have found this a problem as well, I'll have a poke about in the code and see if I can think of a solution...

**Comment by stefonarch** [comment]
> Maybe we could add an optional `on="release"` keybind argument or something like that..

We did something similar in `lxqt-panel` to allow super/winkey to open the menu.

**Comment by spl237** [comment]
Possible fix suggested in PR - works for me. No need to explicitly add an on-release flag to keybinds - I just assume that any modifiers-only keybind is to trigger on release, all others trigger on press. Feel free to try - comments welcome!
