### ISSUE TITLE
Green screen while gaming

### ISSUE THREAD

**Issue by guzz46** [labwc/labwc#1757]
This is a long shot but does anyone know what would cause a green screen of death after 20 to 30 minutes of gaming on steam? I experienced this problem about a month ago on lxqt with kwin as the window manager, but I found that when enabling EXPO it set my VDDIO voltage to 1.45v and after manually setting it to 1.25v I never experienced it again, but now running labwc its back again, after 20 to 30 minutes of gaming my screen goes completely green, I can still hear the game is running fine, and if I reattach my HDMI cable the screen is still green, the weird thing is I've gamed for a couple of hours without any issues on openbox, I might have to permanently switch back to X11?

**Comment by Bezzumnbiu** [comment]
If you have a problem with a green screen, then it is better to run tests to check the operation of the video chip. For example Furmark for a couple of hours or SuperPosition Benchmark.
Most likely your problem could arise due to overclocking

**Comment by guzz46** [comment]
Thanks for the reply, I forgot to mention this is using the integrated graphics of a Ryzen 8700g, its not overclocked, the igpu is stock, but the cpu is undervolted, I've not run any actual benchmarks, but I have gamed for a few hours straight on many occasions without issue on X11 after I lowered the VDDIO voltage, I just find it weird that after 20 to 30 minutes of gaming on wayland with the exact same bios settings I get a green screen.

**Comment by guzz46** [comment]
So I played around with my ram settings today and with the ram at 5600 and vddp voltage at 1.050v I could game for 1 and a half hours without any green screen, where before at the EXPO speed of 6000 I would be lucky to get 20 to 30 minutes, so hopefully its all solved now, I don't know why I could get away with higher ram speeds on X11 though.

**Comment by guzz46** [comment]
Turns out I can run my ram at 6000 on wayland, I just had to lower the VSOC voltage, strange that wayland triggered a green screen when using the exact same voltages as X11.

**Comment by Consolatis** [comment]
The frame pacing of wayland might simply be higher than on X11 and thus has a completely different usage profile of your GPU. It might also use optimized GPU buffer formats that X11 does not use. You really can't compare the two in this way. Anyway, this is slightly offtopic for labwc.

**Comment by guzz46** [comment]
Interesting, sorry I didn't mean to go off topic, I just thought I would post my findings in case someone else comes across the same problem and thinks its a Wayland or labwc issue, then hopefully this will show up in a google search, thanks.
