### ISSUE TITLE
"Lost" windows after disabling monitor

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#177]
Steps to reproduce:

1. Start `labwc` in a dual-monitor (side by side) setup
2. Move a window to the right-hand monitor
3. Disable the right-hand monitor using `wlr-randr`

The window becomes "lost" -- that is, there is no way to reach it with the mouse and move it back into the visible area.  It's still visible in the Alt-Tab window list, however.

Ideally, `labwc` would move the window automatically so that at least part of its titlebar is visible.

**Comment by johanmalm** [comment]
Maybe we could handle this in a similar way to issue #137 

How does the compositor know when an output it `turned off` by a screen-locking client (and therefore windows should not be re-arranged) versus when the user actually wants to disable a particular output (and therefore wants the windows re-arranged)?

**Comment by droc12345** [comment]
It would be hard to tell (impossible?) why the monitor is turned off (screen-lock or using wlr-randr) 
The system, even at kernel level will simply tell you the monitor is off or disabled, not who or why.

So, if you turn the monitor back on, does the window still display where it was? 
If so, then it sounds like it's working the way it's supposed to. 
If the window doesn't reappear on the now enabled second monitor then there is a problem, but a different kind.

**Comment by jlindgren90** [comment]
The window displays where it was before if I enable the monitor again.

Under X11 there is a concept of a "disabled" monitor (`xrandr --off`) which is separate from a monitor turned off to save power (`xset dpms force off`).  The same is true in e.g. Microsoft Windows.  Waking up/unlocking the system turns back on monitors which were turned off to save power, but leaves "disabled" monitors turned off.

Does Wayland not make such a distinction?  Or is `wlr-randr` the wrong tool to "disable" a monitor?

**Comment by droc12345** [comment]
Nothing wrong with wlr-randr, you could use wdisplays, but I think it would do the same thing.

From a system level, I can tell dpms is on/off, monitor is enabled/disabled and whether connected or not.
That's the only statuses that are available.

I'm not sure whether wlr-randr's off option does a disconnect or a disable. I'll have to check later.

**Comment by droc12345** [comment]
This was all done in a labwc session.

wlr-randr and wdisplay mess with the enable option.

Normal -- enabled=enabled status=connected
randr off - enabled=disabled status=connected
power off - enabled=enabled status=connected 

Other compositors do different things (no one is more right than anyone else) to the enabled and status states.

I don't have a screen locker installed and don't know what it does to the states mentioned above.
If it does things different than power off/randr off then it might be possible to program it, but this is really a niche case IMO.

**Comment by 01micko** [comment]
@droc12345 

I don't use a screen locker either but I do use `swayidle` to turn 'off' monitors with `wlr-randr`.

swayidle/config
```
timeout 300 'wlr-randr --output DVI-D-1 --off --output VGA-1 --off &' resume 'wlr-randr --output DVI-D-1 --pos 0,0 --on --output VGA-1 --pos 1920,0 --on &'
```

If I don't use the `--pos` arg my input gets reversed. Perhaps when turning on with `wlr-randr` you would need the `--scale` arg.

**Comment by droc12345** [comment]
01micko I hadn't thought of that, not a big deal since I was only testing.
Not likely to manually turn off the extra monitor just to turn it back on *lol* 

As I said, every compositor handles it differently, with wayfire, the monitor is stuck in an almost on state, 
when using wlr-randr off/on. Something in the way signals are being handled. 
I find the way labwc handles it as acceptable.

But this all goes to the original report, X does this, windows does something else, and the compositors are all different,
even the ones based on wlroots, as wlroots isn't handling all of the nitty-gritty for the compositors.

**Comment by 01micko** [comment]
> Not likely to manually turn off the extra monitor just to turn it back on _lol_

Haha, me either

Primarily _wlroots devs = sway devs_ and IMHO if they really want to improve wayland they should delegate some resources to other light-weight compositors.

**Comment by jlindgren90** [comment]
I tried sway for a comparison.  It has two different commands:

    swaymsg output <name> disable
    swaymsg output <name> dpms off

After `disable`:
- The workspace layout is adjusted as if the monitor is no longer present.
- `wlr-randr` reports `Enabled: no` for that output.

After `dpms off`:
- The workspace layout remains the same (as if the monitor is still there).
- `wlr-randr` reports `Enabled: yes` for that output.

It seems to me that `disable` and `dpms off` are meant for two different use-cases, and both are good to have.

`wlr-randr --off` currently seems like a broken mix of the two.  It behaves a little differently under sway vs. under labwc, but under both it can leave the workspace layout in an unusable state (impossible to move the mouse between remaining enabled monitors and/or impossible to access off-screen windows).

I have very little knowledge of Wayland protocol(s), but my two cents from a (power-)user standpoint would be:

1. It would be nice for `wlr-randr --off` to work similar to `xrandr --off` or `swaymsg output disable`. That is, it would "disable" a monitor completely, and labwc would then move windows as necessary so they aren't "lost".

2. For the "screensaver" use-case, perhaps `wlr-randr` could learn a new `--dpms-off` option, similar to `xset dpms force off` or `swaymsg output dpms off`.

**Comment by Consolatis** [comment]
In X11/mate I usually use Alt+Space to toggle the window menu (which gets opened on the output where the mouse is) and select 'Move'. This grabs the window like it would do with Alt+LeftButton and I can move it off the offscreen and back into the light.

```
<keybind key="W-m">
  <action name="Move" />
</keybind>
```
A-Tab to select the window and W-m to move it back.

**Comment by droc12345** [comment]
I've looked at wlr-randr, and it definitely uses enable/disable to turn the monitor off. 
And I've looked at swaylock (briefly) and didn't see where they were doing any kind of monitor setting like enable/disable.
They take over the input but evidently leave blanking alone, at least it appears that way.

I'm not sure how or if labwc checks or what it does when an output goes to/from enabled/disabled.
Enable/disable is similar to connected/disconnected, but code probably needs to look at both.

**Comment by droc12345** [comment]
A little more testing, I started an app on the 2nd monitor and labwc resonded 
to neither the 2nd monitor being enabled/disable or connected/disconnected.
When I would either connect the monitor or turn it back on with randr the app was still there.
I was doing alt-tab for changing apps and it would go between the main monitor app and 
the "invisible app on the 2nd monitor". I didn't try to interact kbd wise to see if input was
still going there. 

Wayfire (my other compositor) does move the app when the 2nd monitor becomes unavailable.
But even it's not right.

What should happen, is you get a udev change event for the monitor,
then one should check all outputs to see what states (enabled/status) have changed
and only do something with that one monitor and the apps on it.
