### ISSUE TITLE
Question: does anyone know how to get the window properties of a specific window?

### ISSUE THREAD

**Issue by guzz46** [labwc/labwc#1779]
I'm trying to see if a window rule will work from chromium's picture in picture window, but I can't figure out how to get the window properties of the window, I've tried wlprop but I get some socket error, I think maybe its expecting sway?

**Comment by tokyo4j** [comment]
I usually find `app_id` and `title` of opened applications from window swicther, since I'm lazy to use third party apps.

**Comment by guzz46** [comment]
The only thing that shows up in the window switcher is [xdg-shell]  [xdg-shell]  Picture-in-picture
I tried adding 'Picture-in-picture' but it doesn't work, I don't know if its the wrong window id or it just doesn't work for a picture in picture window

**Comment by droc12345** [comment]
Wlprop is a badly named application, it DOES NOT WORK ON ALL wlroots compositors,
right now, it only works on sway and hyprland, and that's because of IPC.

There is no way to get runtime info of existing windows without modifying the compositor
or running in debug mode and parsing the debug output.

And I'm not sure that it would even be possible to get the info of something like PiP.
Not sure if window rules would even work on it anyway.

**Comment by guzz46** [comment]
Success! I just had to change the identifier to title, well done labwc devs for creating a window manager with proper functionality, instead of just dumping windows either in the centre of the screen or in a cascade fashion, this is the window rule to open picture in picture in the bottom right corner of the screen.

      <windowRule title="Picture-in-picture" matchOnce="false">
        <skipTaskbar>no</skipTaskbar>
        <action name="ResizeTo" width="938" height="540" />
        <action name="MoveTo" x="981" y="540" />
        <action name="ToggleAlwaysOnTop"/>
      </windowRule>

**Comment by droc12345** [comment]
Sweet, glad it works. I was not sure if windowrules would work on something like a PiP, as it's not a normal application window. It's a media window attached to another app (chromium, firefox, etc).

Enjoy

**Comment by Consolatis** [comment]
There is for example [wlrctl](https://git.sr.ht/~brocellous/wlrctl) or [lswt](https://sr.ht/~leon_plickat/lswt/)
