### ISSUE TITLE
Launching a certain steam game crashes labwc

### ISSUE THREAD

**Issue by guzz46** [labwc/labwc#1788]
I have two steam games (halo and gears) that kick me out to the login screen when I try and launch them, they both unfortunately happen to use microsoft .net framework, I never had any issue with them on X11, I've tried a few different launch options, and proton GE without any success, the error log exceeded the maximum characters so I've attached it as a pdf, thanks.

[error.pdf](https://github.com/labwc/labwc/files/15248684/error.pdf)

**Comment by Consolatis** [comment]
Please attach a simple text file instead. Also, what version / package of labwc are you using?

**Comment by guzz46** [comment]
I'm on version 0.7.1 thanks

[error.txt](https://github.com/labwc/labwc/files/15248808/error.txt)

**Comment by Consolatis** [comment]
Thanks, the error is this (line numbers for `git checkout 0.7.1`):

> labwc: ../src/view.c:1941: view_move_to_front: Assertion `root' failed

I am not quite sure how this can happen.

My opinion: we should investigate and fix this before the 0.7.2 release and if necessary delay the release.
Thoughts @ahesford @jlindgren90 @johanmalm @tokyo4j ?

**Comment by tokyo4j** [comment]
> My opinion: we should investigate and fix this before the 0.7.2 release and if necessary delay the release.
Thoughts @ahesford @jlindgren90 @johanmalm @tokyo4j ?

I wonder if there's any criteria for delaying releases to fix bugs. Personally, I think we should delay the release only if there are critical regressions that degrade UX from previous versions. But this is not a strong preference and delaying releases doesn't matter for me as a user of labwc-(im-)git AUR.

Anyway, this issue is seemingly already fixed in the master branch so I guess we have nothing to fix before the release.

**Comment by Consolatis** [comment]
Personally I feel uncomfortable to ship a release with a known crash / assert trigger. I agree on the assumption that this is likely already fixed in latest master though, I wrote the comment before digging through the git logs.

**Comment by ahesford** [comment]
If the fix is known and straightforward to implement, delaying a release is reasonable. If the fix is not obvious or requires complex modifications, I wouldn't recommend delaying a release indefinitely to fix a longstanding issue.

Hopefully, this is already fixed by the noted commit.

**Comment by guzz46** [comment]
I'm on nixos, so I'm not sure how to go about installing labwc-git, I'll do some research and see if I can figure it out

**Comment by tokyo4j** [comment]
> I'm on nixos, so I'm not sure how to go about installing labwc-git, I'll do some research and see if I can figure it out

You can follow https://github.com/labwc/labwc?tab=readme-ov-file#2-build-and-installation

**Comment by guzz46** [comment]
Thanks but I don't know if that would work on nixos, its immutable, and I believe the only way to install software is declaring it in the configuration.nix file and then doing a "nixos-rebuild switch"

**Comment by tokyo4j** [comment]
You don't need to install for labwc to run. Just run `meson setup build`, `meson compile -C build` then run it with `build/labwc`.

**Comment by tokyo4j** [comment]
But if you're using display manager, you need to disable it or modify its configuration file to run the executable file you've built instead. I'm not sure if it's easy in NixOS.

**Comment by guzz46** [comment]
I get an error about not being able to find wayland-server when trying to build using meson

**Comment by johanmalm** [comment]
> I get an error about not being able to find wayland-server when trying to build using meson

That's a package you have to install. Not sure what it's called on Nix.

**Comment by tokyo4j** [comment]
> There doesn't appear to be a wayland-server package on nixos, unless its called something else

Isn't it in included in `wayland` package? In Arch `/usr/lib/pkgconfig/wayland-server.pc` is provided by `wayland` package.

**Comment by guzz46** [comment]
I have /nix/store/la9ax3jv86b69n6d5ybwqz3yggsl170x-wayland-1.22.0-dev/lib/pkgconfig/wayland-server.pc
But its not in /run/current-system/sw/lib/pkgconfig
I don't know why it can't find it when building with meson, I've tried to build it the nixos way but I can't figure out how to do it.

**Comment by tokyo4j** [comment]
https://nixos.wiki/wiki/FAQ/I_installed_a_library_but_my_compiler_is_not_finding_it._Why%3F
I know nothing about nix, but I did a quick search and found this.

**Comment by guzz46** [comment]
I tried that but it still gave the same error, someone over on reddit says I need to installing it via flakes, which looks too complicated for me to figure out, I guess I'll just have to wait for 0.7.2 to come out to see if its fixed the problem.

**Comment by Consolatis** [comment]
That fact that this happens with xwayland on 0.7.1 and the only way for the root to be `NULL` (child window of an unmanaged surface) is now handled in the master branch I consider this issue to be fixed, even without confirmation. Thus closing this for now but please confirm when you had a chance to test 0.7.2.

Sorry for the noise everybody.

**Comment by guzz46** [comment]
I finally managed to figure out how to install the master branch, and I can confirm the bug doesn't exist in the master branch, thanks.
