### ISSUE TITLE
Show layershell panel when another window is rendered on top of a fullscreen one

### ISSUE THREAD

**Issue by guzz46** [labwc/labwc#1792]
Someone correct me if I've got this wrong, but supposedly 0.7.2 fixed this bug https://github.com/labwc/labwc/issues/1752 where alt tabbing out of a full screen window like steam big picture or a full screen mpv video would result in waybar being below the full screen window that was just alt tabbed out of, I just upgraded to the latest labwc-git, running labwc -v in the terminal gives me 0.7.2, but I'm still experiencing this bug, thanks.

**Comment by Consolatis** [comment]
That is correct, what was fixed in #1752 is that the panel was shown initially even though steam big picture was fullscreen.
Another case that was fixed was that minimizing a fullscreen window should now show the panel. In the case where another window is rendered on top of a fullscreen window however, that will still make the fullscreen window be rendered on top of panels (which is technically correct but also results in kind of annoying user experience).

Lets keep the old issue closed and this one to track the another-window-overlays-fullscreen-but-panel-still-hidden issue.

CC @tokyo4j

**Comment by guzz46** [comment]
I see, in which case steam now goes full screen when entering big picture mode.
When you say minimizing out of a full screen window do you mean alt tabbing out of a full screen window? If so it still covers the panel when I alt tab out of a full screen window, be it steam big picture, or MPV, or a full screen YouTube video.

**Comment by guzz46** [comment]
The main issue for me was the ability to alt tab out of a paused steam game and still being able to access waybar, seeing as you can't really exit full screen easily from a running game like you can in MPV or a youtube video, but I just found a pretty effective workaround, in rc.xml set a keybind to Iconify (minimize), then when you want to effectively alt tab out of your running game you can just pause the game and press your key binding and it minimizes the game and you can view and access waybar, cool! the only slight downside is the audio still plays, but you can always mute it in pavucontrol if you need to.

**Comment by Consolatis** [comment]
> So what exactly is the difference between alt tabbing out of a full screen window using the window switcher and minimizing it with iconify

`A-Tab` just changes the stacking order and thus puts another window on top of what is currently there.

> could the alt tab window switcher do whatever iconify does when switching out of a full screen window?

That is actually a good idea and would be worth testing. I guess that could make this work for bottom layer panels as well.

I am not quite sure right now how that works with multiple monitors though as `A-Tab` technically just focuses and raises another window (and un-minimizes it if necessary) which would internally be the same as when clicking on a window on another monitor. But that could likely be handled.

**Comment by guzz46** [comment]
I've only got one monitor so I wouldn't know how the multi monitor situation would work, but unless there's something I'm missing, wouldn't it work if alt tab essentially functioned as normal except when it comes to full screen windows, where instead of placing another window on top of it, it would minimize it and then put the next window on top? kind of like a window rule for full screen windows to minimize them when alt tabbing out of them? assuming that's possible?

**Comment by tokyo4j** [comment]
> I think I understand what you're explaining, when you say minimizing out of a full screen window I assume you mean alt tabbing out of a full screen window to another window, like if I alt tab out of a full screen window (be it steam big picture, or MPV, or a full screen YouTube video) to show something like a maximized pdf viewer, the panel is still covered.

When the the focus is moved from a fullscreen window to non-fullscreen (including maximized) window, the fullscreen window is still opened behind the non-fullscreen window. The current implementation is "hide `top` layer if there are fullscreen windows opened", so that's what we expect.

But I do agree that this behavior is strange and not what users would expect.

> could the alt tab window switcher do whatever iconify does when switching out of a full screen window?

If you mean actually minimizing a fullscreen window when the focus is moved to a non-fullscreen window with window-switcher, I don't think it's the good way to fix this. If we implement this, when the focus is moved from a fullscreen window to a non-fullscreen window and then the non-fullscreen window is closed, the fullscreen window is kept minimized. I don't think this is what users expect from window-switcher.

One possible solution is, as I said in #1752, showing waybar if there are non-fullscreen windows above the fullscreen window (or if a non-fullscreen window is focused). It will work fine if you configure waybar to be placed in `top` layer, but if it's in `bottom` layer, fullscreen windows still hide waybar. This limitation comes from our implementation that we're not placing fullscreen windows above `top` layer, but hiding `top` layer when there are fullscreen windows.

IMO the most comprehensive solution is creating a scene-tree for fullscreen windows and placing it above `top` layer if a fullscreen window is focused, or below `bottom` layer otherwise.

**Comment by guzz46** [comment]
>  If we implement this, when the focus is moved from a fullscreen window to a non-fullscreen window and then the non-fullscreen window is closed, the fullscreen window is kept minimized. I don't think this is what users expect from window-switcher.

You're right, I just booted up an old laptop that has plasma 6 on it and alt tabbing out of a full screen window and it doesn't minimize it, it just places another window on top, but the panel is still visible when that happens, I think your solution is the better one, I have waybar on the top layer anyway, in the mean time minimizing the window is an effective workaround for switching from a full screen steam game and accessing waybar.

**Comment by Consolatis** [comment]
> IMO the most comprehensive solution is creating a scene-tree for fullscreen windows and placing it above `top` layer if a fullscreen window is focused, or below `bottom` layer otherwise.

Wouldn't that cause panels and friends to show up on top of the fullscreen window on a 2nd monitor when the focus is on some window on the 1st monitor? With the minimize approach I think we could hook into `end_cycling()` so it gets only triggered when actually using `A-Tab` but not when just clicking on another window.

**Comment by tokyo4j** [comment]
> Wouldn't that cause panels and friends to show up on top of the fullscreen window on a 2nd monitor when the focus is on some window on the 1st monitor?

Yes, it's difficult to implement my suggestion with the current design of how views are arranged, as all views belong to workspaces that cover all outputs. If we have something like `server->view_tree_fullscreen` which is not per-output, it will cause an undesirable behavior like you said.

> With the minimize approach I think we could hook into end_cycling() and check for the to-be-switched-to-window being on the same output as a fullscreen window so it gets only triggered when using A-Tab to switch to a window overlaying a fullscreen one but not when just clicking on another window.

It's possible, but I wonder if minimizing fullscreen windows is what users expect from window-switcher.

For example, KWin allows placing a normal window above a fullscreen window with Alt-Tab. That's not an usual workflow, but I think it should be possible (I might be biased here though).

A possible workaround for that would be minimizing fullscreen windows only when switching to a maximized window so users don't see whether the fullscreen window is minimized or not. But it still feels a bit strange that fullscreen windows are kept minimized when the focused maximized window is un-maximized or closed. Also, with this workaround, panels are  hidden when a normal window above a fullscreen window is focused.

So, for now, as I suggested in #1752, we should just make `top` layer visible if any normal windows are above fullscreen windows, though we cannot panels in `bottom` layer.

**Comment by Consolatis** [comment]
> It's possible, but I wonder if minimizing fullscreen windows is what users expect from window-switcher.

> A possible workaround for that would be minimizing fullscreen windows only when switching to a maximized window so users don't see whether the fullscreen window is minimized or not. But it still feels a bit strange that fullscreen windows are kept minimized when the focused maximized window is un-maximized or closed. Also, with this workaround, panels are hidden when a normal window above a fullscreen window is focused.

Agree to all your observations.

> So, for now, as I suggested in #1752, we should just make `top` layer visible if any normal windows are above fullscreen windows, though we cannot panels in `bottom` layer.

Sounds good to me.

**Comment by droc12345** [comment]
IMO, a fullscreen window should be like a maximized window.
The only effective difference is losing the decorations for full screen.

Though it might seem odd maybe someone wants to have a full screen app, with possibly some other app opened over it. Maybe add an option to fullscreen to allow/disallow windows over it.

**Comment by guzz46** [comment]
> IMO, a fullscreen window should be like a maximized window

Just throwing out ideas here, this may not be possible to implement, but if when switching from a fullscreen window it would toggle it from fullscreen to maximized with no decorations? and then when its brought back on top again its toggled back to fullscreen?

**Comment by tokyo4j** [comment]
> Just throwing out ideas here, this may not be possible to implement, but if when switching from a fullscreen window it would toggle it from fullscreen to maximized with no decorations? and then when its brought back on top again its toggled back to fullscreen?

It's possible, but I guess it requires maintaining another state in the window and complicates the codebase.

**Comment by guzz46** [comment]
The fix works great, thanks
