### ISSUE TITLE
vmware: gvim let labwc compositor crash

### ISSUE THREAD

**Issue by dgod** [labwc/labwc#1793]
I'm on vmware workstation 17.0.2
with Fedora 40
labwc 0.7.2

start labwc under gnome, run gvim under labwc, then labwc crash, the output is like below
00:00:06.224 [types/wlr_linux_dmabuf_v1.c:217] Failed to close buffer handle: Invalid argument
XWAYLAND: [destroyed object]: error 7: importing the supplied dmabufs failed
(EE) failed to dispatch Wayland events: Protocol error
Gdk-Message: 21:23:51.834: Error reading events from display: Broken pipe
(EE) could not connect to wayland server
Segmentation fault (core dumped)

with gdb to debug, the result is useless, like below
(gdb) backtrace 
#0  0x00007ffff7f9a850 in wl_event_loop_dispatch ()
    at /lib64/libwayland-server.so.0
#1  0x00007ffff7f9b0d5 in wl_display_run () at /lib64/libwayland-server.so.0
#2  0x00005555555647b6 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/main.c:195

likely every other gtk3 programs use the x11 backend have the same behavior.

**Comment by Consolatis** [comment]
Is that new with 0.7.2?

**Comment by dgod** [comment]
downgrade to 0.7.1, have the bug

**Comment by dgod** [comment]
downgrade to 0.7.1, have the bug

**Comment by dgod** [comment]
set gvimrc with 
set lines=999
columns=999

will have another problem
WW) glamor: Failed to allocate 13007x16384 FBO due to GL_OUT_OF_MEMORY.
(WW) glamor: Expect reduced performance.
Error getting buffer

gnome deal this well

**Comment by dgod** [comment]
set gvimrc with 
set lines=999
columns=999

will have another problem
WW) glamor: Failed to allocate 13007x16384 FBO due to GL_OUT_OF_MEMORY.
(WW) glamor: Expect reduced performance.
Error getting buffer

gnome deal this well

**Comment by Consolatis** [comment]
There is some kind of issue with wlroots 0.17 and vmware (or more precise its GPU drivers). I don't know what it is and can't test it personally. Using labwc 0.6.6 would likely work around it (it uses wlroots 0.16.x).

**Comment by Consolatis** [comment]
Tracked in
- #1829
