### ISSUE TITLE
request to allow multiple IME popups

### ISSUE THREAD

**Issue by dgod** [labwc/labwc#1794]
at src/input/ime.c, there says
                 * With current input-method-v2 protocol, creating multiple IME
		 * popups is not useful because they just stack up at the same
		 * position.

It's not true, I'm a china input method author, in my case there need two popup, one for normal candidate panel, one for tip the current status which shown at focus or some key pressed.

**Comment by tokyo4j** [comment]
Do you mean you want to manage two IME popups for the candidates and the tip, and show one of them at the same time? In that case, my comment is wrong and we should support multiple IME popups.

I prohibited multiple IME popups just to simplify the codebase and tested only with Fcitx5, but I'm starting to regret it.

**Comment by dgod** [comment]
Yes, I need two, but use one at a time is enough.

Of course, if we can show tip window over the candidate panel is better, but the wayland protocol likely not support do such thing.
