### ISSUE TITLE
Shadows for snapped windows

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#1797]
Snapped windows loose shadows, please make them stay.

**Comment by stefonarch** [comment]
If yes only as an option... kwin_wayland has it and it looks very  bad IMHO.

**Comment by tsujan** [comment]
They had shadow at first, but then it was decided that they shouldn't.

I almost agree with @stefonarch, although IMO it wouldn't look so bad. However, the lack of shadow serves as a sign of the snapped state (in contrast to a window with the same size and at the same position).

**Comment by Consolatis** [comment]
I really can't say anything about this as the whole concept of shadows feels strange to me personally as a user.

**Comment by tsujan** [comment]
> the whole concept of shadows feels strange to me personally as a user.

Can I ask why? To me, shadows are not only nice but useful too: they're good for distinguishing the boundaries of overlapped, borderless windows (`border.Width: 0`).

**Comment by Consolatis** [comment]
> Can I ask why? To me, shadows are not only nice but useful too: they're good for distinguishing the boundaries of overlapped, borderless windows (`border.Width: 0`).

I can see the point of using shadows instead of borders. However personally I prefer borders.

**Comment by Vladimir-csp** [comment]
Indication for a snapped window (to edge) could be a missing border in corresponding direction (or lack of rounded corners on titlebar in case of top edge and shown titlebar).

BTW, maximized horizontal/vertical states could also drop corresponding borders.

**Comment by stefonarch** [comment]
>Indication for a snapped window (to edge) could be a missing border in corresponding direction (or lack of rounded corners on titlebar in case of top edge and shown titlebar).

I'm using gaps which would need an exception.

**Comment by johanmalm** [comment]
Let's close this for now. 

When someone has time/means/ability to contribute to the drop-shadow implementation I suggest we take a broader view of scope and config options.
