### ISSUE TITLE
SendToDesktop keeps focus with follow="no"

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#1800]
Window is somewhere else, but still receives input.

**Comment by Vladimir-csp** [comment]
Strangely, could not work around it by adding a second action `Unfocus`
```
    <keybind key="C-W-1">
      <action name="SendToDesktop" to="1" follow="no" />
      <action name="Unfocus" />
    </keybind>
    <keybind key="C-W-2">
    ...
```

**Comment by Vladimir-csp** [comment]
...and putting `Unfocus` first makes it the only action applied to the window. So each action in the keybind checks for a focused window, not a single check per keybind?

**Comment by droc12345** [comment]
If you unfocus first how does it know which window to send?

And yes, each action checks things for itself, the actions are not chained, just executed one after another.

**Comment by Consolatis** [comment]
> Window is somewhere else, but still receives input.

Thanks for the report. We should indeed focus the then topmost window on the current workspace.

**Comment by Vladimir-csp** [comment]
Why does sending+unfocusing workaround not work? Window is still focused, so `Unfocus` action should apply, but it does not. Could be an indication of a hidden bug.

**Comment by Consolatis** [comment]
From a quick look in the code, `Unfocus` only resets the keyboard focus, it will not focus the topmost surface. So further input should then not be relayed to the now hidden window. Is that actually the case?

**Comment by Vladimir-csp** [comment]
Yes, input stops, and no other window is focused.

**Comment by Vladimir-csp** [comment]
Usable workaround: add `NextWindow` action.
