### ISSUE TITLE
Feature request: Move/resize partially maximized windows

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#1806]
Contrary to snapped windows, moving partially maximized windows seems to be a good thing. They already can be moved by `MoveToEdge` without loosing maximized state. The same could be done for dragging along the unmaximized axis. Dragging along maximized axis could unmaximize with some (large) resistance.

The same for resizing: Free resizing along unmaximized axis (by actions or drag), remove maximized state if resizing along maximized axis with some (large) resistance.

**Comment by Consolatis** [comment]
Already tracked in
- #1521
