### ISSUE TITLE
Failed to register as Toplevel Manager

### ISSUE THREAD

**Issue by hiddenvaad** [labwc/labwc#182]
Hello,
I have been trying to use Labwc for few days but I wasn't able to use waybar with the wlr/taskbar module.
When I start waybar i get this error:
`[Error] Failed to register as Toplevel Manager `
I also tried to use nwg-panel for the taskbar but i get the same result. Both bars work perfectly on sway tho.

**Comment by johanmalm** [comment]
What version are you using.
The `wlr_foreign_toplevel` protocol was implemented after `0.3.0`
See https://github.com/labwc/labwc/blob/master/NEWS.md
If you're on Arch, try using labwc-git from the AUR

**Comment by hiddenvaad** [comment]
I have seen the news, looks like now is working thanks!
