### ISSUE TITLE
Magnifier is broken for pixman renderer

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#1822]
See #1820.

On pixman renderer, the border of magnifier is not drawn and damage tracking for magnifier doesn't work correctly.

According to @Consolatis, this is already fixed in wlroots (https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4659).

I think either of following options should be taken before the next release:
- Confirm the wlroots fix is backported and the issue is solved
- Highly discourage users from using magnifier on pixman renderer
- Disable magnifier for pixman renderer

**Comment by Consolatis** [comment]
My 2 cents:
Variant 1 would be the best, variant 3 is a good fallback approach, 2 doesn't sound that great.

For anybody wanting to test the fixes backported to wlroots 0.17:
https://gitlab.freedesktop.org/Consolatis/wlroots/-/tree/backport_017/pixman_render_perf

At least nested it did fix the pixman + magnifier issue for me but also causes a pixman + dropshadow issues instead so there is further work to be done on the wlroots side.

CC @spl237 @cillian64

**Comment by droc12345** [comment]
I'm not sure the logic is 100% correct in scene-helpers.c
I upgraded to the latest git yesterday, and I noticed my idle watts went up from 3.1 to 5.1 (on average)
I chased it down to lab_wlr_scene_output_commit in scene-helpers..

I reworked it slightly and my watts went back to normal.
Basically I moved the checks for last_mag and wants_magnification to where they made sense.
I haven't tested the magnifier part, as I've not used it yet.

If interested I'll pull up a PR.

**Comment by spl237** [comment]
Just to confirm, I've tried the wlroots patch referred to above on Pi, and it does indeed fix the magnifier under pixman for me as well, both windowed and full-screen. (And does also break drop shadows!)

**Comment by droc12345** [comment]
Try this patch #1832  and see if it still works for magnification. 
I think it should I just rearranged and added extra checks.

**Comment by Consolatis** [comment]
It seems like the magnifier and drop shadows are both [fixed](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4690) in wlroots master / 0.18 (not yet tested though). However there is some hesitation to backport the two changesets to 0.17 (as its more than just a bugfix). So the question is if we can fix the wlroots 0.17 branch separately for this magnifier bug. Thoughts @cillian64 ?

**Comment by cillian64** [comment]
> It seems like the magnifier and drop shadows are both [fixed](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4690) in wlroots master / 0.18 (not yet tested though).

I've just done a quick test and both the magnifier and drop-shadows work for me with pixman on wlroots master (using your `chase/0.18` labwc branch with the magnifier cherry-picked)

> However there is some hesitation to backport the two changesets to 0.17 (as its more than just a bugfix). So the question is if we can fix the wlroots 0.17 branch separately for this magnifier bug. Thoughts @cillian64 ?

A lot of the old pixman transform code (before my "performance" patch basically rewrote that function) just don't make any sense to me, especially how it handles source crop (see https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4653#note_2386254) which is what I suspect is going wrong here.  I briefly tried a few simple things I thought might fix it but it's remaining thoroughly broken with the magnifier.

I understand the hesitation to backport something which isn't a minimal bugfix but given how many issues we found with the old pixman transform code (and that nobody noticed them outside of drop shadows and the screen magnifier) it feels reasonable to backport my changes, I think we're unlikely to make it more broken than the original 0.17 release.

**Comment by Consolatis** [comment]
Makes sense, should I prepare a backport MR for wlroots then containing the pixman rewrite MR + the recent fixup MR or do you want to do so instead?

**Comment by cillian64** [comment]
If you'd be able to do the MR that would be great, I'm going to be mostly AFK tomorrow and next week.

**Comment by Consolatis** [comment]
> If you'd be able to do the MR that would be great, I'm going to be mostly AFK tomorrow and next week.

Will do over the weekend. Thanks for your work on the pixman renderer.

**Comment by Consolatis** [comment]
The backport PR has been merged to the 0.17 branch and is thus part of a future 0.17.4 release.
It is also included when compiling labwc without a system wide dependency or with `--force-fallback-for=wlroots` (and an up-to-date `subprojects/wlroots/` repository).

I'll leave the issue open until 0.17.4 is actually released.

**Comment by tokyo4j** [comment]
Closing as 0.17.4 was released a week ago.

I confirmed magnifier and drop-shadows work fine with pixman renderer in my Arch Linux setup.
@Consolatis Thank you for your effort!
