### ISSUE TITLE
Is there any way to get an application's icon?

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1824]
I've been toying with the idea of adding application icons to the alt-tab window switcher - wayfire does this, and it's quite nice visually to break up what would otherwise be a long list of plain text.

I can add arbitrary icons easily enough, but the problem is getting the correct icon for an application.

Am I correct in my understanding that there is no way to do this directly from within the compositor; the only way to do it is to search and parse the .desktop files on the system until you find the one which corresponds to the app-id, and then to look up the Icon entry in that file in the icon theme?

That appears to me to be the case, and it doesn't seem worth the effort involved; I just wanted to check that this wasn't a problem which someone else had already got an elegant solution for!

**Comment by Consolatis** [comment]
Right, I think most panels do some variation of:
- try to load app_id.desktop, if found use the icon defined therein
- try to load lowercase(app_id).desktop
- try to load a "app_id" icon directly
- try to load a "lowercase/app_id)" icon directly
- go through all .desktop files and check `StartupWMClass` for the "app_id" (most compositors are using the WM_CLASS of xwayland windows as app_id for the foreign-toplevel-protocol)

There is a wayland protocol in the works but I didn't follow that one in detail:
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/269

**Comment by spl237** [comment]
Yes, that was what I had understood to be the case. Thanks for confirming!
