### ISSUE TITLE
Do not run dbus-update-activation-environment if dbus implementation is dbus-broker

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#1827]
It reuses systemd environment, so no special handling is needed. Including stuffing a bunch of empty vars on exit.

**Comment by Consolatis** [comment]
Just my personal opinion but I'd rather not have even more dbus related special case handling in labwc. The existing ones are already quite annoying. You can set `LABWC_UPDATE_ACTIVATION_ENV=0` if you don't want labwc to update the environment at all but then you'd need to update the systemd one manually (for example via `autostart` file).
