### ISSUE TITLE
Inconsistent use of `_` and `-` in filenames

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#1835]
This is just a trivial suggestion to improve the codebase.

There are:
- `src/xwayland-unmanaged.c`
- `src/window-rules.c`
- `src/snap-constraints.c`
- `src/button/button-svg.c`
- `src/button/button-png.c`
- `src/button/button-xbm.c`
- `src/view-impl-common.c`
- `src/decorations/kde-deco.c`
- `src/decorations/xdg-deco.c`
- `src/input/key-state.c`
- `src/xdg-popup.c`
- `src/output-virtual.c`
- `src/common/string-helpers.c`
- `src/common/grab-file.c`
- `src/common/parse-bool.c`
- `src/common/parse-double.c`
- `src/common/scene-helpers.c`
- `src/common/file-helpers.c`
- `src/common/graphic-helpers.c`
- `src/common/surface-helpers.c`
- `src/session-lock.c`

and:
- `src/osd_field.c`
- `src/ssd/ssd_extents.c`
- `src/ssd/ssd_titlebar.c`
- `src/ssd/resize_indicator.c`
- `src/ssd/ssd_part.c`
- `src/ssd/ssd_border.c`
- `src/ssd/ssd_shadow.c`
- `src/input/tablet_pad.c`
- `src/common/fd_util.c`
- `src/common/scaled_font_buffer.c`
- `src/common/scaled_scene_buffer.c`

I think we should unify them to either of `-` or `_`  (I prefer `-`).

I'm going to create a file like `resize-overlay.c` for `<resize><drawContents>` and I'm a bit confused with it.

**Comment by domo141** [comment]
I also prefer '-'

-- reason 1, easier to type -- shift not needed
-- I had some other reason but cannot remember...oh yes, can concat $foo-$bar, but not $foo_$bar in shell scripts
-- there must have been other good reasons, too :D

**Comment by johanmalm** [comment]
I prefer hyphen `-`. Let's go with that.

**Comment by mgutz** [comment]
The main reason to prefer underscore convention is consistency with C identifiers.
