### ISSUE TITLE
SSD: `SetDecorations 'full'` does not work without `forceSSD.action="yes"`

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#1841]
@xi - I have found a problem with `SetDecorations`. Have not had a chance to re-visit the code. Any ideas?

Expected:
- Using the configuration below I expect to be able to switch between `full` and `border` on windows using server side decoration (SSD) with those respective keybinds.

Observed:
- I can set `border` - but cannot change back to `full`.
- Have tried with `xterm`, `foot` and `firefox`. Get the same result.
- I can change back to `full` with `SetDecorations` if I use `forceSSD.action="yes"` (but believe that should only be required for CSD windows).
- I can still cycle between `full`, `none` and `border` with `ToggleDecorations`

```xml
<keyboard>
  <keybind key="W-q" name.action="SetDecorations" decorations.action="full"/>
  <keybind key="W-v" name.action="SetDecorations" decorations.action="border"/>
</keyboard>
```

**Comment by xi** [comment]
I think I simply mixed up the handling of SSD/non-SSD windows. I pushed a fix. Good think we found this before this was released!
