### ISSUE TITLE
Add XKB_DEFAULT_VARIANT example to docs/environment

### ISSUE THREAD

**Issue by Bluey26** [labwc/labwc#1843]
I suggest to add this kind of example, in addition to the already present which uses brackets () , because `labwc-tweaks `will not recognize the brackets variants and it has issues to load the keyboard layouts presenting that syntax (Check https://github.com/labwc/labwc-tweaks/issues/75 for the complete issue).

It should be something as:

```
##Multiple keyboard layouts can be set by comma-separating the country codes.
##If a variant layout is needed, the syntax is layout(variant) , or specify the variants using XKB_DEFAULT_VARIANT 
##If the first keyboard layout does not need a keyboard variant use ,variant2 to specify the variant of the 2nd layout(check below example).
##If multiple layouts are used, specify the toggle-keybind using
##XKB_DEFAULT_OPTIONS as show below.


##For further details, see xkeyboard-config(7)


#XKB_DEFAULT_LAYOUT=se
#XKB_DEFAULT_LAYOUT=se,us(intl)
#XKB_DEFAULT_LAYOUT=se,us
#XKB_DEFAULT_VARIANT=,intl
#XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
#XKB_DEFAULT_OPTIONS=grp:shift_caps_toggle
```

The change should be done in : https://github.com/labwc/labwc/blob/master/docs/environment

**Comment by johanmalm** [comment]
Can we hang fire on this until we've decided how to implement it in `labwc-tweaks`

**Comment by Bluey26** [comment]
Hi, i think this issue is solved by now, there is no need to use `XKB_DEFAULT_VARIANT` anymore, since labwc-tweaks already supports the keyboard variants inside `XKB_DEFAULT_LAYOUT`.

Feel free to close this issue.

**Comment by johanmalm** [comment]
Yes. Good point. Thanks for checking back in on this one :smile:
