### ISSUE TITLE
How to fine-tune options for nested usage?

### ISSUE THREAD

**Issue by Botspot** [labwc/labwc#1848]
My main shell is labwc, but I want to run some nested labwc windows for testing automated browser events.
This somewhat works out of the box - just running `labwc` launches a 1280x720 window containing a second wayland display.

But compared to Weston's nested options, there seem to be no ways to customize its behavior. For example, I would like to set an initial screen size and disable xwayland. Is there a way to set those two parameters in a config file, as there do not seem to be command-line flags for it?
Regarding setting the window size, I am aware that nested window can be manually resized with the mouse, but I need to pick exact dimensions and make it repeatable.

With weston the command is simply `weston --width=1366 --height=768` or `weston --fullscreen`

**Comment by Botspot** [comment]
You may ask why I do not simply use Weston for this, and the answer is that I need to automate keyboard events  with `wtype` and take screenshots with `grim`, both of which say weston is lacking backend support for.

**Comment by Consolatis** [comment]
You can either use wlr-randr to set the resolution, something like `wlr-randr --output WL-1 --custom-mode 1366x768`.
That could be called in for example the `~/.config/labwc/nested/autostart` file and you then start the nested labwc via `labwc -C ~/.config/labwc/nested` to have its own setting directory.

If you just want to make the nested instance fullscreen you can also add a window rule to your parent compositor with something like this instead:
```xml
<windowRules>
    <windowRule identifier="wlroots">
        <action name="ToggleFullscreen" />
    </windowRule>
</windowRules>
```

**Comment by Botspot** [comment]
That worked perfectly.
