### ISSUE TITLE
How to force a screen refresh?

### ISSUE THREAD

**Issue by Botspot** [labwc/labwc#1849]
I have two instances of wlroots running:
1. main one handling my desktop
1. Secondary, nested labwc window for testing

I need to take periodic screenshots of the nested labwc window. Currently using `grim` for that. I run grim from `wayland-0` using this command: `WAYLAND_DISPLAY=wayland-1 grim`
However, there is a problem. If the nested labwc window is minimized, or even positioned behind other windows on my main desktop, `grim` hangs. I think the reason for this is that labwc is intelligent enough to avoid refreshing the screen, but in this case I want to force it to refresh.

What I've tried:
- Turning the screen off and back on again
    ```
    $ WAYLAND_DISPLAY=wayland-1 wlr-randr --output WL-1 --off
    $ WAYLAND_DISPLAY=wayland-1 wlr-randr --output WL-1 --on
    ```
    Causes these errors in /dev/stderr of the nested `labwc -V` process:
    ```
    00:00:04.714 [ERROR] [../src/output.c:685] failed to get output layout box
    00:00:06.527 [INFO] [../src/output.c:934] adaptive sync disabled for output NOOP-1
    00:00:06.527 [INFO] [../src/output.c:934] adaptive sync enabled for output WL-1
    00:00:06.529 [INFO] [../src/seat.c:280] map pointer to output WL-1
    
    xdg_surface@24: error 3: xdg_surface has never been configured
    00:00:06.531 [ERROR] [backend/wayland/backend.c:79] Failed to dispatch remote Wayland display
    00:00:06.531 [ERROR] [backend/wayland/backend.c:79] Failed to dispatch remote Wayland display
    ```
    and then labwc exits
- Calling xrefresh
    ```
    DISPLAY=:1 xrefresh
    ```
- Changing the dimensions of `wayland-1`
    ```
    WAYLAND_DISPLAY=wayland-1 wlr-randr --output WL-1 --custom-mode 480x361
    ```
    This shows promise. Grim saves an image but it is a PNG file containing only black pixels.
    ![20240525_14h33m16s_grim](https://github.com/labwc/labwc/assets/54716352/c876fa12-e6be-4046-a4c4-03bf74a5277d)
- Sending the nested labwc process the SIGHUP signal: Grim still hangs.
- Trying to disable adaptive sync with environment variable:
    ```
    CLUTTER_VBLANK=none labwc -V
    ```
    No change. Grim still hangs.
- Trying to disable adaptive sync in rc.xml:
    ```
    <adaptiveSync>no</adaptiveSync>
    ```
    No change. Grim still hangs.

Is there another tool that could be used to notify labwc that the screen is being "viewed"? For my purposes, I don't want to have to manually raise the labwc window to the front of my physical screen every time a screenshot needs to be captured.

**Comment by Consolatis** [comment]
That is a limitation of wlroots, when using the wayland backend it will enforce "adaptive sync" on the nested compositor which is driven by frame events of the outer compositor. As you noticed, this causes issues when making screenshots (or controlling it via wayvnc or the like). Depending on your use-case you could run the nested compositor completely headless instead (`WLR_BACKENDS=headless`) or add a headless output to your running nested session via [VirtualOutputAdd](https://labwc.github.io/labwc-actions.5.html#entry_action_name=virtualoutputadd_output_name=value).

For headless outputs you can define the refresh rate via wlr-randr (AFAIR it defaults to 60 but I am not sure right now).

**Comment by Botspot** [comment]
> Depending on your use-case you could run the nested compositor completely headless instead (`WLR_BACKENDS=headless`)

I noticed that. Seems that with headless mode output is named something different other than `WL-1`, causing wlr-randr to say `unknown output WL-1`. Is there a way to list valid outputs to I know what to replace `WL-1` with?

> or add a headless output to your running nested session via [VirtualOutputAdd](https://labwc.github.io/labwc-actions.5.html#entry_action_name=virtualoutputadd_output_name=value).

This looks promising, but is there a way to set that up without a keybinding?

**Comment by Consolatis** [comment]
>  Is there a way to list valid outputs to I know what to replace WL-1 with?
Just `wlr-randr` should list all outputs.

> This looks promising, but is there a way to set that up without a keybinding?

Not directly, however you could
- set `LABWC_FALLBACK_OUTPUT=foobar`, run labwc nested as usual and then close the output window. It should then create a headless fallback output. You could also add `WLR_WL_OUTPUTS=0`, that should then create the fallback output immediately.
- add the VirtualOutputAdd action to a keybind and use `wtype` / `wlrctl` to inject keys to trigger the keybind

**Comment by Botspot** [comment]
Very informative. Thank you.
It seems that the "adapytive sync" was actually keeping gpu usage down, so disabling it by going headless was using extra resources, by "displaying" a virtual 60fps screen. Maybe I could have reduced that frame rate by using wlr-randr, but 0 is better than 30fps.

I found a way to do the testing I needed without screen refreshes. Thanks for the help, especially the pointer to wlrctl. I had never come across it before and it seems quite useful.
