### ISSUE TITLE
How to hide the titlebar?

### ISSUE THREAD

**Issue by BenStigsen** [labwc/labwc#1855]
Thank you for creating `labwc`, it is exactly the kind of WM I'm looking for.

I'm trying to remove the titlebar and make this the default, I am however not sure how to do this.
I've tried the following in `~/.config/labwc/rc.xml`
```xml
<labwc_config>
  <windowRule identifier=""> <!-- also tried with identifier="*" -->
    <action name="SetDecorations" decorations="none" />
  </windowRule>
</labwc_config>
```
I've tried using `"*"` as the identifier, set `decorations="border"`, wrapping the window rule in `<windowRules>`, used `forceSSD="no"` and more.

**Comment by tokyo4j** [comment]
I guess you're missing `<windowRules>` element.

**Comment by BenStigsen** [comment]
Thank you for the help. The code above works, although I'll just build from source as I still want the border.
