### ISSUE TITLE
Set squared SSD corners when SSD client is tiled and notified about being tiled

### ISSUE THREAD

**Issue by jp7677** [labwc/labwc#1862]
Follow up from https://github.com/labwc/labwc/pull/1463

It would be nice if the SSD corners would follow GTK3/4 corners of getting squared when the client is tiled and tiling notifications for clients are enabled. 

Since we have already squared corners for maximized windows, I guess the infrastructure is somewhat there.

**Comment by Consolatis** [comment]
Yes, somewhat. We'd have to selectively round / square the left / right ones individually though.

I am also not convinced that this is a good idea for people using gaps and thus have some margin between their snapped windows to the screen edge. However, as we already support the tiling notification setting for this purpose I guess that should be fine. We might want to reconsider the default though if it would now also matter for SSD windows (it is currently `always`).

**Comment by salahoued** [comment]
If I understand correctly removing rounded corners when a window is tiled/snapped to a region is an intended behaviour in `0.7.3` and when not the client/window should keep its rounded corners like so:

### Not tiled:
![20240719_19h02m20s_grim](https://github.com/user-attachments/assets/738cddac-711f-4078-a524-3d7b39970d29)

### Tiled:
![20240719_19h02m43s_grim](https://github.com/user-attachments/assets/616c1269-433a-4d69-8040-95edbd306270)

### But I get this when a window is tiled and I run a `Reconfigure`:
![20240719_19h03m27s_grim](https://github.com/user-attachments/assets/0e5a9c14-747d-4a66-ab7f-007511fe17f2)

**Comment by Consolatis** [comment]
Can confirm, SSD tiled + Reconfigure is broken.
