### ISSUE TITLE
labwc won't start, plenty of errors

### ISSUE THREAD

**Issue by wastlnd** [labwc/labwc#1868]
Hi, I am using a minimal Arch installation without systemd/elogind or display managers, just runit as init and seatd. I have my user added to the video and seat groups. When I try to start labwc I get the following huge [error list ](https://pastebin.com/vYLrxLkU).
I tried to manually set the xdg runtime directory using the shell profile, according to the [Alpine wiki](https://wiki.alpinelinux.org/wiki/Wayland#XDG_RUNTIME_DIR), but it only starts inside a X session, not in the TTY at boot (and all the other errors show up as well). What may I be missing?

**Comment by johanmalm** [comment]
It looks like you've used an Openbox `rc.xml` file. The syntaxes are fairly close, but just taking the openbox files is a bad starting point.

Try without an `rc.xml` to just see if you can get it started with default settings.

You need a font installed (e.g. `ttf-dejavu`). You probably do already, but just to make sure.

Try with:

```
cd $HOME
mkdir foo
XDG_RUNTIME_DIR=$HOME/foo labwc
```

**Comment by wastlnd** [comment]
Hey @johanmalm thanks for your help, actually you were right, trying to run labwc without rc.xml works without throwing errors but.. again, it only works inside the X session. If I try the same command in tty I get:
Libseatd could not connect to socket /run/seatd.sock: Permission denied

**Comment by johanmalm** [comment]
I'm glad that worked.

I'm on Arch and I think systemd sets `XDG_RUNTIME_DIR`. I'm not sure what the advice is for non-systemd setups.

Presumably you could just add `export XDG_RUNTIME_DIR=$HOME/.run` to `.profile`, `.zshrc`, `.zshenv` or similar. I'm not sure what the "official" advice.

**Comment by wastlnd** [comment]
Thanks again @johanmalm , I don't know if there's a "best" solution for a systemd-less system, but in case I think Id have to create this .run directory by myself, right?

**Comment by Consolatis** [comment]
> I think Id have to create this .run directory by myself, right?

Yes.

Usually `$XDG_RUNTIME_DIR` is located on some tmpfs but technically its not required to be on a tmpfs. Usually its `/run/user/1000` for uid 1000. This has the benefit of being empty on system restart. You can use `mkdir -p "$XDG_RUNTIME_DIR"` in your `.profile` to create a directory if it doesn't exist.

**Comment by johanmalm** [comment]
I've tried running `labwc` with a very small setup on Arch a couple of times. The only dependency that was non-obvious (to me) was `polkit` and `ttf-dejavu` (or whatever).

I'll close this for now, but if you find a way to run without polkit, then let us know and we document it somewhere.

**Comment by Narrat** [comment]
Didn't test that yet, but somewhere on my ToDo is Polkit vs Seatd setup.
And there are some sparse ressources I stumbled upon so far:
https://github.com/swaywm/sway/wiki/Running-Sway-with-seatd%2C-elogind-or-systemd%E2%80%90logind#seatd
https://wiki.archlinux.org/title/Sway#Starting

And one thing I don't get from the initial post is whether seatd service is enabled and started (or if seatd-launch is used)

**Comment by wastlnd** [comment]
@johanmalm and @Narrat, thanks again for your suggestions, I didn't really used seatd as a service (the runit service requires dbus, that I have disabled), but simply type:
Sudo seatd -u $user | labwc
Instead of fiddling with the shell for the runtime directory, I found another option, that is installing pam_rundir, that automatically creates the /run/user/$uid directory and exports the variable. That should, in fact, require polkit, if I'm not wrong.
