### ISSUE TITLE
strange behavior of input method popup surface

### ISSUE THREAD

**Issue by dgod** [labwc/labwc#1871]
just let the popup surface destroy one key stroke, and get popup surface next key stroke.

test with firefox

the first time the position of surface is incorrect, just at the top left of screen
multiple surface shown at the screen

the attachment is my test c code.

[test.txt](https://github.com/user-attachments/files/15528784/test.txt)

**Comment by tokyo4j** [comment]
I really appreciate your report.

I've been worried that my IME implementations have any bugs that don't become apparent with Fcitx5... and it had.

**Comment by dgod** [comment]
thanks for your quick fix.
With this bug fixed, my input method nearly ready for labwc's input_method_v2 protocol.

**Comment by tokyo4j** [comment]
I tried your program in sway and Hyprland, but the problem of multiple popups were present in both compositors.
I guess re-creating `input_method_popup_v2` for the same `wl_surface` is something those compositors (and also labwc before my patch) don't expect, though I believe it's not violating the protocol.

So if you want to implement your IME in this way and make it usable also in those compositors, you can ask the developers there.
