### ISSUE TITLE
Child dialogs may be off-screen when their parents are

### ISSUE THREAD

**Issue by tsujan** [labwc/labwc#1876]
This happens with Qt and GTK alike:

 1. Place a window — like FeatherPad's — in such a way that it's partially outside the visible screen *at right and/or bottom*.
 2. Open a child dialog — like Preferences dialog or open-file dialog.

Then, depending on the position of the main window, the dialog may be off-screen partially. The reason is that it's opened centered relative to the main window. Since the important buttons of a dialog (OK, Cancel,...) my not be visible in this case, I think this is a UX issue, although it isn't a critical problem.

It doesn't happen when the main window is off-screen *at top and/or left*. It doesn't happen under Wayfire either. As the GTK window I used for testing was `gtk3-widget-factory`, I don't think it's related to server-side decoration (of Qt windows).

IMHO, a new window should always be opened inside the visible screen as far as possible (i.e., when its size is smaller than that of the screen), regardless of being a main window or a child dialog.

EDIT: I use LabWC 0.7.2, but it happened with previous versions too.

**Comment by johanmalm** [comment]
Good point. We ought to fix this.

**Comment by tsujan** [comment]
To be more precise, I wanted to add that it isn't limited to off-screen parent windows. It can also happen when a great enough child dialog is called by a small parent window near the bottom and/or right edge of the screen, like this:

![bottom_edge](https://github.com/labwc/labwc/assets/981076/89e782ad-9609-4e79-a3f2-b0945caf3c79)

The modality of the dialog (whether it prevents interacting with the parent window or not) isn't relevant either.

**Comment by stefonarch** [comment]
The fix works fine.
