### ISSUE TITLE
Is it possible to set 'minimal' borders for applications in rc.xml?

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#1881]
Using the 'ToggleDecorations' action you can cycle through 3 states of decorations:

SSD (with the labwc title bar at the top)
CSD (or no decorations at all if the client doesn't have them)
a 1px minimal border

I know if I use a Window Rule I can set `serverDecoration="no"` to force CSD (which removes decorations entirely for most windows)

However, I'd prefer on those non-decorated windows to have the minimal border (as it gives me something to grab for resize). I can cycle through using my ToggleDecorations keybinding, but I'm wondering:

Is it possible to set the minimal border in the config, and if so, what would that option be? I couldn't find anything in the manpages and 'serverDecoration' seems to either take 'yes' or 'no' or 'default' ('default' and 'yes' appear the same?)

Thanks!

**Comment by droc12345** [comment]
keepBorder should be what you need. man labwc-config and search for keepBorder.

**Comment by winteriscariot** [comment]
> keepBorder should be what you need. man labwc-config and search for keepBorder.

I actually don't think this does what I want. What this seems to do is only give the ToggleDecoration action 2 states: either full titlebar on top, or 1px minimal border, it disables the "CSD only" decoration option.

Applications with a windowRule of `serverDeocration="no"` still don't have a minimal border, even when `<keepBorder>yes</keepBorder>` is set.

**Comment by droc12345** [comment]
Should be able to set border width in themerc

**Comment by charbelnicolas** [comment]
Borders in labwc aren't that great IMO. Unlike other compositors, it still lacks the necessary configuration options and development to have something uniform and glitch-less.

I used to have a border when using awesome wm but dropped them completely on labwc.

Maybe in a few months or years we'll get something useful.

**Comment by johanmalm** [comment]
@winteriscariot 

Could you do a window-rule with `<action name="SetDecorations" decorations="border"/>`

If you want a particular `thickness` of that border, you can add `border.width: X` to `~/.config/labwc/themerc-override`

Ref:
- https://labwc.github.io/labwc-actions.5.html#entry_action_name=setdecorations_decorations=value_forcessd=no
- https://labwc.github.io/labwc-actions.5.html#entry_action_name=setdecorations_decorations=value_forcessd=no

Will close for now, but if there is something you can't achieve regarding those borders, let us know.

**Comment by johanmalm** [comment]
> Borders in labwc aren't that great IMO. Unlike other compositors, it still lacks the necessary configuration options and development to have something uniform and glitch-less.
> 
> I used to have a border when using awesome wm but dropped them completely on labwc.
> 
> Maybe in a few months we'll get something better.

@charbelnicolas Negative comments not welcome.

**Comment by charbelnicolas** [comment]
> > Borders in labwc aren't that great IMO. Unlike other compositors, it still lacks the necessary configuration options and development to have something uniform and glitch-less.
> > I used to have a border when using awesome wm but dropped them completely on labwc.
> > Maybe in a few months we'll get something better.
> 
> @charbelnicolas Negative comments not welcome.

Sorry, I got carried away, I love labwc :)

**Comment by winteriscariot** [comment]
> @winteriscariot
> 
> Could you do a window-rule with `<action name="SetDecorations" decorations="border"/>`
> 
> If you want a particular `thickness` of that border, you can add `border.width: X` to `~/.config/labwc/themerc-override`
> 
> Ref:
> 
>     * https://labwc.github.io/labwc-actions.5.html#entry_action_name=setdecorations_decorations=value_forcessd=no
> 
>     * https://labwc.github.io/labwc-actions.5.html#entry_action_name=setdecorations_decorations=value_forcessd=no
> 
> 
> Will close for now, but if there is something you can't achieve regarding those borders, let us know.

This doesn't do anything as far as I can tell.

> Should be able to set border width in themerc

this is not the problem this issue describes.

There are 3 potential border states: CSD, SSD, SSD-minimal (grabable border but no titlebar) but the labwc config only supports 2 (CSD, SSD)
