### ISSUE TITLE
Edit pixel buffers before rendering (Question)

### ISSUE THREAD

**Issue by Silitonix** [labwc/labwc#1885]
Hello every one!
is there any change to edit the opacity of some pixels from corner of window to make it round ?
where is the corresponding file and function for it if it exist ?
Thank you all !

**Comment by johanmalm** [comment]
You can crop wit wlr_scene_buffer_set_source_box

https://github.com/labwc/labwc/blob/3dd4bc7c3bea38d4ff889141967b3f699b903437/src/ssd/ssd-shadow.c#L46

I’ve not tried editing buffers directly.

**Comment by tokyo4j** [comment]
This may be worth a look: https://github.com/wlrfx/scenefx

**Comment by johanmalm** [comment]
Will close for now. Keen to hear if you make any progress on this.

**Comment by Silitonix** [comment]
> This may be worth a look: https://github.com/wlrfx/scenefx

how i use that ?
I am installed the project using AUR.
but there is nothing to do with that XD.
