### ISSUE TITLE
GoToDesktop with keyboard and mouse

### ISSUE THREAD

**Issue by Nosirus** [labwc/labwc#1889]
Is it possible to use GoToDesktop with the Super key and Scroll combination?
For example if I am in a full screen application.

**Comment by tokyo4j** [comment]
```xml
```

**Comment by tokyo4j** [comment]
I confirmed the following configuration does what you want:
```xml

    <context name="All">
      <mousebind direction="W-Up" action="Scroll">
        <action name="GoToDesktop" to="right" />
      </mousebind>
      <mousebind direction="W-Down" action="Scroll">
        <action name="GoToDesktop" to="left" />
      </mousebind>
    </context>
```

**Comment by Nosirus** [comment]
unfortunately it doesn't work, it continues to use the scroll as if the Super key was not pressed.

**Comment by tokyo4j** [comment]
Sorry, I forgot to mention that `All` context is only implemented in the git master and not in 0.7.2.
Are you using the git version already?

**Comment by Nosirus** [comment]
ah indeed no, I use version 0.7.2 on nixos unstable, I would have to look at how to use the git version with it.

**Comment by Consolatis** [comment]
If you replace the "All" context with "Frame" it should also work with 0.7.2. Not tested though.

**Comment by Nosirus** [comment]
well seen !
if i put in "frame" and "root" it's perfect

**Comment by Consolatis** [comment]
Nice, thanks for verifying that it works.
