### ISSUE TITLE
xdg_popup was destroyed while it was not the topmost popup

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#189]
This is something I finally managed to get an easy reproducer for.

Following is required to trigger this bug:
- client must be using layershell (no need to anchor somewhere, nor set a layer or exclusive zone)
- client must have a menu (might actually be the same for context menu, not tested)
- menuitem must have a tooltip
- user must hover over that item and wait until it shows up
- and then finally click that item

It is possible that the bug is actually on the GTK side although testing in sway does not disconnect the client.

Once triggered the (GTK) client terminates with this error:
> Gdk-Message: 16:24:27.232: Error 71 (Protocol error) dispatching to Wayland display.

The last message from the server:
```
[Server-0]
      1      wl_display.error(<obj id 23 [xdg_wm_base v2]>, 2, 'xdg_popup was destroyed while it was not the topmost popup')
[Server-0] disconnected
```

And finally the reproducer:
<details><summary>Reproducer</summary>

```
#!/usr/bin/env python3

import gi

gi.require_version("Gtk", "3.0")
gi.require_version('GtkLayerShell', '0.1')
from gi.repository import Gtk, GtkLayerShell

class Something(Gtk.Window):
	def __init__(self):
		super().__init__(title="Crash test")
		self.set_size_request(200, -1)

		menu = Gtk.Menu()
		bug = Gtk.MenuItem.new_with_label("Bug")
		bug.set_submenu(menu)

		trigger = Gtk.MenuItem.new_with_label("Trigger")
		trigger.set_tooltip_text("foobar")
		menu.append(trigger)

		notrigger = Gtk.MenuItem.new_with_label("No Trigger")
		menu.append(notrigger)

		quit = Gtk.MenuItem.new_with_label("Close")
		quit.connect('activate', lambda menuitem : Gtk.main_quit())
		menu.append(quit)

		menubar = Gtk.MenuBar()
		menubar.append(bug)
		self.add(menubar)

something = Something()
GtkLayerShell.init_for_window(something)
something.show_all()
Gtk.main()
```
</details>

**Comment by 01micko** [comment]
I can reproduce this with [gtkdialog](https://github.com/puppylinux-woof-CE/gtkdialog), however, I _do_ need to set an edge or a layer to get the the crash.

```
~$ sh mtest 

** (gtkdialog:19668): WARNING **: 19:01:55.509: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
Gdk-Message: 19:01:59.888: Error 71 (Protocol error) dispatching to Wayland display.
```

My trigger

```sh
#!/bin/sh
echo '<window edge="left">
	<menubar>
		<menu>
			<menuitem label="Bug">
			</menuitem>
			<menuitem label="Trigger" tooltip-text="trigger">
			</menuitem>
			<menuitem label="No Trigger">
			</menuitem>
			<menuitem label="Close">
				<action>exit:Quit</action>
			</menuitem>
		</menu>
	</menubar>
</window>' | gtkdialog -s
	
```

**Comment by Consolatis** [comment]
> I can reproduce this with [gtkdialog](https://github.com/puppylinux-woof-CE/gtkdialog), however, I _do_ need to set an edge or a layer to get the the crash.

Thank you for verifying the issue. Now I know it's not something related to my setup :)
I don't know gtkdialog but maybe it won't actually use LayerShell if there is no `edge` defined.

**Comment by 01micko** [comment]
It skips the `gtk_layer_shell` block if an attribute isn't set for the window widget, [widget_window.c](https://github.com/puppylinux-woof-CE/gtkdialog/blob/master/src/widget_window.c) so fully understandable.

**Comment by Consolatis** [comment]
From https://github.com/labwc/labwc-acceptance-criteria/blob/main/TODO.md
> seat: unfocus popups when changing focus - for example, when clicking on title bar, active menus should close

Warning: Assumptions ahead.
This could actually be the reason for the protocol error. I'd guess the menu is a popup.
When an item within that popup has a tooltip it creates another popup (I'd assume) which then has the focus.
If we now click the original menuitem the menu popup will be closed but the tooltip popup still own the focus and thus we get a `xdg_popup was destroyed while it was not the topmost popup`.

**Comment by 01micko** [comment]
I wonder if #155 is related?

**Comment by 01micko** [comment]
Forget the above mention, bug still exists.

**Comment by Consolatis** [comment]
fixed with current master / scene-graph API
