### ISSUE TITLE
 Set the LANG in $HOME/.config/labwc/environment ,  It don't take effect on  the menu of windows title.

### ISSUE THREAD

**Issue by knm100** [labwc/labwc#1901]
If set the LANG in /etc/environment ,  It take effect on  the menu of windows title.

the screenshot (Set the LANG in $HOME/.config/labwc/environment)
<img width="645" alt="批注+2024-06-13+111226" src="https://github.com/labwc/labwc/assets/166389780/7c8b135b-9b46-44ec-ab80-de697f340ddf">

**Comment by johanmalm** [comment]
I'm not sure, but `$HOME/.config/labwc/environment` sets it for the whole session, whereas I suspect the shell that the terminal invokes then sets it again.

This is not really my area of expertise, but I don't think you should set LANG in places other than `/etc/locale.conf` and similar (i.e. NOT in labwc configuration).

**Comment by knm100** [comment]
> I'm not sure, but $HOME/.config/labwc/environment sets it for the whole session, whereas I suspect the shell that the terminal invokes then sets it again.

why does LANG=zh_CN.UTF-8 can effect on konsole, not on windows title menu?
settting LANG=en_US.UTF-8  in /etc/locale.conf ,  LANG=zh_CN.UTF-8 in  $HOME/.config/labwc/environment, then reboot, You will simply reproduce it.

**Comment by tokyo4j** [comment]
> why does LANG=zh_CN.UTF-8 can effect on konsole, not on windows title menu?

This is because labwc initializes the locale and then reads `~/.config/labwc/environment`.

I made a PR to change this order.

**Comment by knm100** [comment]
@tokyo4j  Thank you very much!

**Comment by knm100** [comment]
Sorry, I tested it and found that there are still some problems with the storage
1.	when setting locale=zh_CN.UTF-8 to $HOME/.config/labwc/environment, the item “scorll up/down” in the window title still didn't follow the locale setting.
<img width="617" alt="zh_CN" src="https://github.com/labwc/labwc/assets/166389780/9c3407ae-d9f9-41c0-abf5-c237f5d61ef1">

As I can see in the labwc localisation, this menu item has already been translated.
<img width="229" alt="批注 2024-06-23 134714" src="https://github.com/labwc/labwc/assets/166389780/88a90b20-6e56-4eb4-b9e0-ba094b92fa2f">


2.	when setting locale=ja_JP.UTF-8 to $HOME/.config/labwc/environment, the the whole window title still didn't follow the locale setting.
<img width="666" alt="ja_JP" src="https://github.com/labwc/labwc/assets/166389780/fa525338-304b-4fea-8f68-0409fbef667e">

**Comment by stefonarch** [comment]
With Roll Up/Down : the sources have changed (capitalized) and language files are not updated yet.

**Comment by tokyo4j** [comment]
> 1. when setting locale=zh_CN.UTF-8 to $HOME/.config/labwc/environment, the item “scorll up/down” in the window title menu still didn't follow the locale setting.

That's something we should never miss before the next release.

> 2. when setting locale=ja_JP.UTF-8 to $HOME/.config/labwc/environment, the whole window title menu still didn't follow the locale setting.

It worked for me. Did you uncomment `#ja_JP.UTF-8 UTF-8` in `/etc/locale.gen`?

**Comment by knm100** [comment]
> It worked for me. Did you uncomment `#ja_JP.UTF-8 UTF-8` in `/etc/locale.gen`?

Yes,  after  added the locale  ja_JP.UTF-8, It worked.  

Thank  all of you.

**Comment by knm100** [comment]
I compiled the latest GIT version with  of  version with that the "Roll up/down"has been changed to "Roll Up/Down"  in the language file, but it's still the same as before(didn't following the setting of the locale).

**Comment by stefonarch** [comment]
I'm not sure about *.po files, but when source is changing translations are marked as "needs editing", with `*.ts` files they are displayed nevertheless, but I think here it's not the case, until translations  in https://translate.lxqt-project.org/projects/labwc/labwc/  are updated and merged. Theoretically we could remove the "needs editing" marks in all languages, but better wait for translators doing it atm

**Comment by knm100** [comment]
When I compiled, the .po file had  already  been translated.
![swappy-20240625-000356](https://github.com/labwc/labwc/assets/166389780/1722cfc4-f56d-4403-8db6-1c055aafba8c)

**Comment by stefonarch** [comment]
See the difference:
```

#: src/menu/menu.c:851
msgid "Fullscreen"
msgstr "全屏"

#: src/menu/menu.c:853
#, fuzzy
#| msgid "Roll up/down"
msgid "Roll Up/Down"
msgstr "滚动 上/下"

#: src/menu/menu.c:855
msgid "Decorations"
msgstr "装饰"
```
I've little knowledge about haow `.po` files are handled but the | and `,fuzzy` mean probably that the translation could be wrong/not updated.

**Comment by stefonarch** [comment]
@johanmalm 
I  changed now those settings, removing the hooks:

![immagine](https://github.com/labwc/labwc/assets/10681413/7c6bc41a-86b1-4eff-842c-42c410b8d13c)

I think this should be safe  in this case as the meaning hasnp't changed. Maybe they should be reactivated later, in weblate the strings are still marked for editing but the existing translation will be used now:
See https://github.com/labwc/labwc/pull/1930/files

**Comment by johanmalm** [comment]
Thanks. Yeah I did not the `fuzzy` thing. Assumed it made it case insensitive, but didn't investigate.

**Comment by knm100** [comment]
Rev  9fc41a9  is still the same as before(only "Roll Up/Down" didn't following the setting of the locale).

**Comment by johanmalm** [comment]
Are you doing a system wide installation (rather than running labwc from the local build directory)? I think you have to for i18n to work.

**Comment by stefonarch** [comment]
Did you update?
I can only confirm that after https://github.com/labwc/labwc/pull/1930 was merged changed translations work as before.

**Comment by knm100** [comment]
this is my labwc rev?
![swappy-20240625-174024](https://github.com/labwc/labwc/assets/166389780/26134ed3-e337-4494-aea8-f5771ac90beb)

**Comment by tokyo4j** [comment]
Roll Up/Down is not translated in Japanese as well. Adding following command in PKGBUILD fixed it:
```sh
find . -name '*.po' -exec sed -i '/#, fuzzy/d' {} \;
```
So `#, fuzzy` should be removed.

**Comment by stefonarch** [comment]
>So we should remove #, fuzzy.

You're right, I didn't check for good: https://github.com/labwc/labwc/pull/1935
