### ISSUE TITLE
Flickering with magnifier and gammastep

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#1905]
It doesn't matter the dimension, the magnified area flickers always at some seconds interval:

https://github.com/labwc/labwc/assets/10681413/a066af9f-5b5b-46b7-aed2-7a7ae5a9b332

**Comment by Consolatis** [comment]
Is this on the DRM backend or on the wayland backend?
Also what renderer is in use, the usual gles2 one or something other like vulkan?

**Comment by stefonarch** [comment]
Some responses, not sure about the right commands:

```
glxinfo | grep "OpenGL renderer"
OpenGL renderer string: AMD Radeon Vega 3 Graphics (radeonsi, raven2, LLVM 17.0.6, DRM 3.54, 6.6.32-1-lts)


$ eglinfo | grep -i "EGL_VENDOR"
$ vulkaninfo | grep "deviceName"
        deviceName        = AMD Radeon Vega 3 Graphics (RADV RAVEN2)

```

**Comment by droc12345** [comment]
Turn on debugging, and startw labwc with stdout/stderr redirections, then exit labwc.
View the log file, it will tell you what it's using, the backend as well as the renderer.

**Comment by stefonarch** [comment]
```
00:00:00.050 [render/egl.c:536] Using EGL_PLATFORM_DEVICE_EXT
00:00:00.051 [render/gles2/renderer.c:842] Creating GLES2 renderer
...
[backend/wayland/backend.c:436] Starting Wayland backend

```

**Comment by tokyo4j** [comment]
Could you post the full debug log when you experience the flicker?
Perhaps it includes messages like "Failed to build output state for HDMI-1" or "Failed to commit output HDMI-1".

**Comment by stefonarch** [comment]
Not very helpful I guess:
```

**Comment by tokyo4j** [comment]
I think I figured out the cause.

When I run a command like `gammastep -t 2000:6000 -l 0:0`, gammastep regularly updates the gamma setting in some interval.
And labwc currently doesn't draw the magnifier at the frame when the gamma setting is updated:
https://github.com/labwc/labwc/blob/1dadb128075864f0c0449700f2b6f9723ef842fc/src/output.c#L77-L101

So, drawing the magnifier also inside the if-block would solve the issue.

**Comment by Consolatis** [comment]
Right.. gamma changes don't go through `lab_wlr_scene_output_commit()` thus it doesn't use the magnifier. AFAIR the reason there was that by not mixing the gamma state with the other pending output changes it makes it easier to handle errors due to the gamma changes not working without also loosing unrelated pending changes. I can do a PR later this week unless somebody else wants to tackle it.

**Comment by Consolatis** [comment]
- #1920

Testing would be appreciated.

**Comment by stefonarch** [comment]
> Testing would be appreciated.

Was  waiting for sunset - no flickering anymore with gammastep now.

**Comment by Consolatis** [comment]
Sweet, thanks for testing. I'll look into rewriting the PR to reuse `lab_wlr_scene_output_commit()` with an optional state argument rather than bolting the magnifier on the gamma specific code path but that should not change anything in terms of logic.

**Comment by Consolatis** [comment]
Should be fixed for latest master. Thanks for reporting.
