### ISSUE TITLE
[Question] max_render_time adjustment setting?

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#1913]
Hi there,

Coming from a discussion on the Wayfire compositor issues section here: https://github.com/WayfireWM/wayfire/issues/2377
... it came to my attention that using a 2 buffers swapchain in fullscreen (ie: Direct Scanout) Vulkan programs doesn't cause halved framerate on labwc, while it happens in both Sway and Wayfire.

Direct Scanout is working on labwc for fullscreen Vulkan programs, it was apparently confirmed here: https://github.com/labwc/labwc/discussions/1518

So, my questions are: what default value for` max_render_time` is labwc using? Is there a setting for it? Is it dynamically adjusted when Direct Scanout is in use as purposed in the aforementioned Wayfire discussion?

Thanks!

**Comment by johanmalm** [comment]
We just use `wlroots` scene graph API out of the box so to speak and have not (yet) implemented `max_render_time`.
So we just render early in the 16ms period.

**Comment by vanfanel** [comment]
Ah! That explain the lack of framerate halving caused by the late rendering in other compositors when 2 buffers swapchain is used... Thanks! :)

**Comment by johanmalm** [comment]
Maybe we ought to add `max_render_time`. I looked at how `sway` did it and shouldn't be too much effort. Probably best done in the merge window after a release in case we get something wrong with it.

**Comment by vanfanel** [comment]
I'll be there testing it once it's added, for sure.

**Comment by Consolatis** [comment]
Honestly I am not sure if that is worth it. AFAIR it plays tricks by assuming the render time based on the last frames and then delays rendering up until that point. However if we now take longer to render we skip a complete frame which does sound even worse than rendering too early in the timeframe. Combine that with completely unforeseeable CPU / GPU or bus usage and latency based on whatever the user is doing. IMHO labwc should work decent in regards to performance but this might be a bit too much and is even a possible cause of skipping frames that wasn't there before. Feel free to correct me if I got the idea wrong though.

**Comment by vanfanel** [comment]
> Honestly I am not sure if that is worth it. AFAIR it plays tricks by assuming the render time based on the last frames and then delays rendering up until that point. However if we now take longer to render we skip a complete frame which does sound even worse than rendering too early in the timeframe. Combine that with completely unforeseeable CPU / GPU or bus usage and latency based on whatever the user is doing. IMHO labwc should work decent in regards to performance but this might be a bit too much and is even a possible cause of skipping frames that wasn't there before. Feel free to correct me if I got the idea wrong though.

I have to agree with that. Every program I've seen where previous frame times where used to infere the next had framerate problems / hiccups.
