### ISSUE TITLE
Labwc allegedly slow to send fractional scale to applications

### ISSUE THREAD

**Issue by AdamNiederer** [labwc/labwc#1914]
Hey, I'm noticing delayed startup using kitty on labwc. According to kitty's maintainer, this is because labwc is "taking forever to send the fractional scale to kitty after window creation", and that other compositors do it much quicker. I'm wondering if it's possible to send that scale earlier. Thanks!

Link to the kitty issue with reproduction steps:

https://github.com/kovidgoyal/kitty/issues/7540

Original issue text:

**To Reproduce**

1. Run an unconfigured labwc and terminal from a tty with `labwc -C none -s xterm` (can be any term including kitty)
2. From that terminal, run kitty with `kitty --config none`
3. Observe that the kitty window is created after ~250ms, but the terminal prompt does not appear for another ~250ms.
4. Further observe that all keyboard input before the display of the terminal prompt is dropped

This is an issue because it eats the first few characters of the command I want to run after opening a terminal

This delay does not occur on openbox, nor on labwc by using XWayland: `env -u WAYLAND_DISPLAY kitty --config none`, which reduces the startup time to just the ~250ms required to show the window; there is no delay between window showing and prompt showing.

I have reproduced this issue on the following two systems:

- Laptop with 6900HX, 680M, 3070ti and hybrid graphics enabled
- Desktop with 12600k, 7900XT and no hybrid graphics setup

**Screenshots**

A recording of this bug in action; the second time, I am typing "abcdef" after invoking kitty to demonstrate the late input capture

[kitty-startup-delay.webm](https://github.com/kovidgoyal/kitty/assets/4571394/bb71fc52-0df6-481f-94ba-688b9c3fa1f0)

**Environment Details**
```
labwc 0.7.2
```
```
kitty 0.35.1 created by Kovid Goyal
Linux 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64

Arch Linux 6.9.3-arch1-1 (/dev/tty)

Running under: Wayland (labwc 0.7.2) missing: preferred_scale
OpenGL: '4.6 (Core Profile) Mesa 24.1.1-arch1.1' Detected version: 4.6
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
  PATH                                /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:
  LANG                                en_US.UTF-8
  EDITOR                              emacs
  SHELL                               /bin/bash
  DISPLAY                             :0
  WAYLAND_DISPLAY                     wayland-0
  USER                                adam
  XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session0
  XDG_SEAT                            seat0
  XDG_SESSION_DESKTOP                 labwc
  XDG_SESSION_TYPE                    wayland
  XDG_GREETER_DATA_DIR                /var/lib/lightdm-data/adam
  XDG_CURRENT_DESKTOP                 wlroots
  XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
  XDG_SESSION_CLASS                   user
  XDG_VTNR                            7
  XDG_SESSION_ID                      9
  XDG_RUNTIME_DIR                     /run/user/1000
```

**Comment by ahesford** [comment]
Whether or not we can improve the latency of sending the fractional scale, this is fundamentally a design flaw in kitty. As the author notes, the decision was made to avoid a resize because of a fundamental limitation in Wayland. The Wayland behavior is well specified, and the application should be prepared to wait 1,000 years for the fractional scale to arrive if necessary. An application that refuses to launch a client window until an asynchronous event occurs isn't a very well-behaved client.

If we're going to play the "every other compositor" blame game, I'll note that "every other terminal emulator" (or, at least in my experience, foot and alacritty) behave just fine with labwc.

**Comment by tokyo4j** [comment]
By running `WAYLAND_DEBUG=client kitty 2>&1 | grep fractional`, I found `wp_fractional_scale_v1.preferred_scale` event is sent instantly after launching. I wonder why the author thought that is the cause.

**Comment by charbelnicolas** [comment]
Not that it matters but this exact bug made me switch to the foot terminal days ago when kitty got updated on Arch Linux from version 0.33.1 to 0.35 and I couldn't be happier! I actually started a discussion about the slow startup time on kitty's github repository but I got banned hehe

**Comment by ahesford** [comment]
Seems like this issue has been fixed upstream.
