### ISSUE TITLE
Very odd Thonny behaviour when unmaximising a window

### ISSUE THREAD

**Issue by lurch** [labwc/labwc#1921]
Hello,

I've noticed a **very** weird problem with Thonny's behaviour on Raspberry Pi OS Bookworm when using the labwc compositor.

Setup
=====
1. Download the latest version of "Raspberry Pi OS with desktop" from https://www.raspberrypi.com/software/operating-systems/ (problem is seen on both 32-bit and 64-bit OSes)
2. Flash it to a microSD card
3. Boot it up in a Raspberry Pi (problem is seen on both Raspberry Pi 4 and Raspberry Pi 5)
4. Ensure the OS is [fully up-to-date with APT](https://www.raspberrypi.com/documentation/computers/os.html#install-updates)
5. run `sudo apt install labwc`
6. run `sudo raspi-config` and then select "Advanced Options" -> "Wayland" -> "Labwc" -> "Ok" -> "Finish" and reboot when prompted to do so

Working examples
=====
These scenarios all work correctly (before I describe the failing scenario)
 * Launch Thonny (from the Programming menu), close Thonny, and then open it again. As expected, Thonny starts unmaximised (so now close it again).
 * Launch Thonny, maximise it, unmaximise it, close Thonny, and then open it again. As expected, Thonny starts unmaximised (so now close it again).
 * Launch Thonny, maximise it, close Thonny, and then open it again. As expected, Thonny starts maximised (so now close it again).

Failure case(s)
=====
 * Launch Thonny, maximise it (if it isn't already maximised), close Thonny, and then open it again. Now try unmaximising Thonny, and the entire window contents disappears!! You're left with just the title-bar visible, and nothing else. (if you click on the unmaximise button again, then the window contents reappear)
 * Problem number 2: If you close Thonny in this title-bar-only state, and then open it again, you get a fairly small window where none of the window-borders have a resize-cursor when you move over them. If you move this small-window by dragging on the title-bar, then after this you _do_ get resize-cursors on the window-borders.

This behaviour only occurs on Labwc (not Wayfire) and Thonny is (so far) the only application I've noticed doing this.

**Comment by cillian64** [comment]
I've just filed #1922 which is probably not the same as this but might be related.  Could you run labwc with the `-d` flag and capture stdout/stderr and see if there are any complaints about `client (%s) did not respond to configure request` or `window geometry for client (%s) appears to be incorrect - ignoring` (or anything else relevant)?

**Comment by tokyo4j** [comment]
I installed Thonny now and could reproduce it. It's not specific to Raspberry Pi.

**Comment by lurch** [comment]
I can confirm that if I run the tkinter code provided by @tokyo4j and then "unmaximise" the window, that exhibits the same problematic behaviour that I'm seeing with Thonny. So pinging @aivarannamaa in case this needs fixes from the Thonny-side in addition to the labwc-side.

**Comment by Consolatis** [comment]
Should be fixed on latest master, labwc now prevents storing a geometry smaller than what is required to render minimal server decorations (104 x 60). If the application provided value is smaller, labwc will use a fallback size of 640x480 instead.

Thanks @tokyo4j for investigating and fixing!
