### ISSUE TITLE
XDG configure state gets out of sync when clients timeout

### ISSUE THREAD

**Issue by cillian64** [labwc/labwc#1922]
I've been seeing an intermittent issue when repeatedly going in and out of fullscreen in Firefox when it's playing back video on a heavily loaded Raspberry Pi 4, using labwc with the gles2 renderer.  I can't get a screenshot, but what I see is the fullscreen video but with a transparent band at the bottom through which I can see my desktop (and can actually click and interact with the desktop too).

I can try to write up a more detailed reproducer if needed.  I'm happy to try fixing this myself if I can get some guidance on context/strategy.

What I believe is happening in my case is:

1. Toggle window maximization, Firefox window size changes from A to B
2. labwc sends XDG configure to Firefox to go from size A to B
3. Firefox doesn't respond in `CONFIGURE_TIMEOUT_MS` because it's being busy/slow
4. labwc discards the pending configure and assumes Firefox is still in state A.
5. Firefox eventually applies the configure and is now in state B
6. Toggle window maximization, Firefox window size changes from B to A
7. labwc thinks Firefox is already in state A so doesn't bother sending a configure
8. Now Firefox and labwc are out of sync, labwc expects size A but Firefox is sending surfaces of size B.  We get the "Window geometry for client (%s) appears to be incorrect - ignoring" error and things look a bit strange.

I'm not sure what the original logic was behind having configures time out. I'm also not sure whether other clients apply configures with a delay or just ignore them entirely. So, it's not obvious to me the best way to fix this, but a few ideas I have are:

- If a configure times out then always send the next configure, even if it appears pointless.  I'm not 100% sure this will entirely solve the problem as stopping after step 5 might still leave things inconsistent.
- If a configure appears to timeout then mark the pending config as "probably forgotten" but still keep track of it.  Then if the client later starts sending surfaces which match this config then apply it.
- Increase `CONFIGURE_TIMEOUT_MS` to make the problem less common.  I expect making the timeout 1000ms would make the problem go away for me at least.  Not sure what the downsides of a longer timeout are.

**Comment by johanmalm** [comment]
It's not obvious to me what the problem is here.

The timeout was originally added in this PR which contains quite a lot of info: https://github.com/labwc/labwc/pull/803/files

This issue might be related: https://github.com/labwc/labwc/issues/1902

What version of firefox are you using? I can replicate the kiosk issue with `>=126`

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc/pull/803#issuecomment-1449354919

> There is another problem (in the current code) which can be seen when attempting to tile an xdg-shell view that doesn't allow resizing. Example: the "about" window of xfce4-terminal. In that case, we never get a commit acknowledging the configure-request, and it remains "pending" indefinitely until an unrelated commit. As a result, we delay moving the "about" window to its tiled location, until the mouse cursor is moved over it -- then it suddenly jumps.
> 
> This presumably started occurring after [ecd03b7](https://github.com/labwc/labwc/commit/ecd03b70ef93616b0de73b795a5c05180dadcc3c) (haven't verified). To fix it, I would suggest a timeout (100 ms?) after which, if we haven't received the acknowledgement commit, we move the view anyway.

In hindsight, it may be better to check if max-size == min-size (which IIRC is the way we should disallow window resize on Wayland).

See comment here: https://github.com/labwc/labwc/issues/1294#issuecomment-1848674287

@jlindgren90 - Any thoughts? Can you remember if there were other reasons for the timeout?

**Comment by jlindgren90** [comment]
IIRC the "Window geometry for client (%s) appears to be incorrect - ignoring" is probably a client side bug. The client updated one or the other of window geometry/surface size but not both in sync. There were reports of this occuring with some Qt apps. I never saw it personally.

The timeout, I think, was added earlier. We need that to avoid a poorly behaving app from hanging up window movement/resizing.

I don't have time to try to reproduce or debug anything myself right now.

**Comment by Consolatis** [comment]
History of the "window geometry for client .. appears to be incorrect":
- https://github.com/labwc/labwc/issues/1194#issuecomment-1773944610
- #1229

**Comment by jlindgren90** [comment]
@cillian64 since you said:

>  I'm happy to try fixing this myself if I can get some guidance on context/strategy.

I have some questions I would suggest investigating (and I am curious myself).

> 4. labwc discards the pending configure and assumes Firefox is still in state A.

What do you mean by "state A" here? Just the window/surface size?

> 5. Firefox eventually applies the configure and is now in state B

If "state" refers to window/surface size, then labwc should see the resize happen when Firefox eventually "applies the configure". When that happens, `handle_commit()` (xdg.c) should be called. Both `view->current` and `view->pending` should be updated to the new surface size ("state B") since the pending configure timed out already. Can you check if that's happening?

> 6. Toggle window maximization, Firefox window size changes from B to A
> 7. labwc thinks Firefox is already in state A so doesn't bother sending a configure

I am not following this part. How did the Firefox window size change if labwc didn't send a configure? Did Firefox resize spontaneously?

**Comment by cillian64** [comment]
I've started seeing this problem more often with Firefox and also with Chromium so delved in for another go.  I'm pretty sure I now know what's going wrong, so ignore the issue description and my earlier comments.  Merge request incoming shortly with my proposed fix.

Here's what I think is going wrong (sorry for the wall of text).  The problem is the heuristics in `view_impl_apply_geometry()` which detect top-edge or left-edge resizes based on geometry.  What I see is:

- Starting state: window is maximized with position 0,64 size 1920x1016
- Window calls `xdg_toplevel::set_fullscreen()`
- Compositor sends a configure event with size 1920x1080. `view->pending` is set to position 0,0 size 1920x1080
- We hit the 100ms timeout and `handle_configure_timeout()` is called.
  - `handle_configure_timeout()` calls `view_impl_apply_geometry(view, 1920, 1016)` to apply the pending move while keeping the current size
    - In `view_impl_apply_geometry()`, the resizing_top_edge heuristic triggers because the top edge of the window is moving from y=64 to y=0 while the bottom edge is staying at y=1080.
    - Because it thinks a top-edge-resize is taking place it keeps the bottom edge at the same place while applying the requested height.
    - So our window is left at position 0,64 size 1920x1016 with no pending change.
- Eventually the client acks the configure and changes its size to 1920x1080. Its position stays the same.
- We're now left with a view marked as fullscreen (so undecorated) but with position 0,64 size 1920x1080.

My proposed solution is to make `handle_configure_timeout()` directly set `view->current.x` and `view->current.y` instead of calling `view_impl_apply_geometry()`.  Because it's using a mix of the pending position with the current size, the top/left-edge resize logic doesn't make sense anyway: The logic in `view_impl_apply_geometry` is intended for when the client chooses a different size to what we expected, and doesn't work when the the client is going to use the size we asked for but is just taking its time.  With the current code, if you get slow configure timeouts while dragging a top/left-edge resize then the window's top-left stays in the same place while the bottom-right grows/shrinks.  After my fix, with a laggy client, dragging the top-left resize repositions the window when the timeout occurs and the actual resize happens when the client catches up.  To me this feels much less weird.

I've made a standalone reproducer, a simple wayland/xdg client with a configurable delay to actioning xdg configure events.  If anyone else wants to test/reproduce let me know and I'll clean it up and push it up somewhere.

**Comment by tokyo4j** [comment]
> I've made a standalone reproducer, a simple wayland/xdg client with a configurable delay to actioning xdg configure events. If anyone else wants to test/reproduce let me know and I'll clean it up and push it up somewhere.

If it's not too much hassle, I will really appreciate it if you provide the reproducer. It will also help validating changes to `handle_configure_timeout()` made in the future development.

**Comment by cillian64** [comment]
> If it's not too much hassle, I will really appreciate it if you provide the reproducer. It will also help validating changes to `handle_configure_timeout()` made in the future development.

Sure, see here: https://gist.github.com/cillian64/e647d10ce588a4516670c4eb5c3d50da.  My changes are pretty bodgy so very much without warranties.

**Comment by tokyo4j** [comment]
> Sure, see here: https://gist.github.com/cillian64/e647d10ce588a4516670c4eb5c3d50da. My changes are pretty bodgy so very much without warranties.

Confirmed the issue. Thank you.

<img src="https://github.com/user-attachments/assets/2bb3216e-93ea-4b74-aa67-43657350e367" width="40%" />
