### ISSUE TITLE
Dnd icon is rendered below layer-shell surface

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#1933]
Labwc 0.7.2/git master, it's a regression introduced in 0.7.0 (it worked with 0.6.6)

Use case: xfce4-panel with tasklist plugin, try to drag and drop a window button from the tasklist (so you must have a terminal window open, or something). The dnd icon doesn't appear, because it's actually rendered under the panel, as can be seen by moving the pointer out of the panel.

**Comment by tokyo4j** [comment]
Looks like bf326cc introduced this behavior. Looking the prior code, I guess even in 0.6.6 dnd icon was shown below layer-shell surfaces when dnd is performed  -> a new output is plugged -> dnd is started again on the new output.

**Comment by Consolatis** [comment]
Should be fixed in latest master. Thanks for reporting.

**Comment by Tamaranch** [comment]
I can confirm it fixes the issue, thanks!
