### ISSUE TITLE
error code 129

### ISSUE THREAD

**Issue by moncheeta** [labwc/labwc#1951]
Hello!
I have installed labwc on voidlinux, and I wanted to run it. Unfortunately, I always get exit status code 139 without any error messages. [Here](https://github.com/user-attachments/files/16060760/debug.txt) is debug output(from `labwc -d`). Any ideas of what could be going wrong? Any help would be greatly appreciated!

**Comment by tokyo4j** [comment]
Is your title wrong? If error code is 139, it means labwc SEGFAULT'ted and we need to fix it before 0.7.3 as long as we can.

I find nothing suspicious in the debug log but it's usual when the process SEGFAULT's.

Could you try following commands to get the backtrace?

```sh
git clone https://github.com/labwc/labwc.git
cd labwc
meson setup build
ninja -C build
gdb build/labwc
```

Then inside gdb, type `r` to start debugging and type `bt` on crash to get the backtrace. You may need to install some dependencies like meson or wayland-protocols.

**Comment by moncheeta** [comment]
I have no clue what happened. I got 129 persistently until hours later when it magically started working again. If I can reproduce the issue, I will upload a backtrace. Until then, I will close this issue.

**Comment by Consolatis** [comment]
It might have been missing fonts (like no font installed at all). We did add add a font package to the Void CI for this reason. The longer term plan is to catch that situation and terminate cleanly with an appropriate error message so the user can react to that but that hasn't materialized yet.
