### ISSUE TITLE
Using two screen for X11/Wayland backend breaks cursor coordinates

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#196]
- `WLR_X11_OUTPUTS=2 build/labwc -s foot` (nested in X11)
- `WLR_WL_OUTPUTS=2 build/labwc -s foot` (nested in sway/labwc)

completely breaks cursor coordinates. Doing the same for sway works as intended.

**Comment by Consolatis** [comment]
Alright, after diving into sway, wlroots and tinywl I think the issue is that emulating two nested screens like that causes two **absolute** input devices to be created which must be mapped into their respective outputs or regions.

`wlr_cursor_map_input_to_output()` and/or `wlr_cursor_map_input_to_region()` are likely the solution.
See `sway/input/seat.c::seat_apply_input_config()`

Currently it works something like that:
- `labwc/src/cursor.c::cursor_motion_absolute()` gets triggered with x,y being between 0.0 and 1.0
- That function calls `wlroots/types/wlr_cursor.c::wlr_cursor_absolute_to_layout_coords()`
- Which in turn calls `get_mapping()` inside the same file and as there is no mapping set up:
- calls `wlroots/types/wlr_output_layout.c::wlr_output_layout_get_box(layout, NULL)` which then returns the extends of the whole layout.
- Thus all cursor coordinated are translated into the whole layout dimension
- `labwc/src/cursor.c::process_cursor_motion()` gets called using the translated coordinates

Result: If we have two screens, each 800x600 we can move the cursor in either screen from left (x=0) to right (x=1200).

I don't intend to send a PR for this because there is way too much I don't know about wlroots input handling and I don't want to mess up something else while fixing this.

**Comment by johanmalm** [comment]
I think this does it :smile:

**Comment by Consolatis** [comment]
Great stuff :)
Had a quick test and now it works and I can test it to verify the cursor coordinates in #197 and #198 or try to figure out #194.

I guess as a side effect this supports other absolute pointers like multi screen setups which include touchscreens.
