### ISSUE TITLE
Add resistance option for tiled windows

### ISSUE THREAD

**Issue by orfeasxyz** [labwc/labwc#1968]
This is a small UX enhancement to prevent accidentally moving a tiled window (and subsequently messing it up) when clicking on its titlebar.

**Comment by Consolatis** [comment]
That is not a bad idea. Thanks for the suggestion.

**Comment by tokyo4j** [comment]
Some CSD clients like Firefox or other GTK apps have this feature (though it just requests resizing when the cursor movement distance exceeds a threshold I guess). It'll be nice if we can implement the similar behavior for SSD clients.

**Comment by jlindgren90** [comment]
Resistance would be nice for maximized windows too. I accidentally move (and unmaximize) these fairly often.
