### ISSUE TITLE
shadows of qt windows

### ISSUE THREAD

**Issue by knm100** [labwc/labwc#1969]
I setted window shadows in the ~/, .local/share/themes/lxqt-Labwc/openbox-3/theme.rc.  but they didn't take effect.
![swappy-20240708-140942](https://github.com/labwc/labwc/assets/166389780/d055a41f-5762-4670-9410-8d22336be4a9)
![swappy-20240708-142020](https://github.com/labwc/labwc/assets/166389780/3d89e0bb-2950-433d-8069-455122b945bf)

The GTK program seems to come with its own shadows and didn't follow my settings
![swappy-20240708-141911](https://github.com/labwc/labwc/assets/166389780/24316bfb-e884-4723-8f6a-c61a3575ba41)
Can I set all the windows to be shadowed like the GTK program?

**Comment by tokyo4j** [comment]
Did you set `<theme><dropShadows>` to `yes`?

**Comment by knm100** [comment]
thank you so much,  it worked.
