### ISSUE TITLE
Monitor configuration when in greeter

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#1970]
I previously asked https://github.com/labwc/labwc/issues/1524, about how to save custom monitor resolutions and configs, and it was suggested I use kanshi.

This works really well, but I have realised there is a use case which it does not cover - the greeter.

I use lightdm to manage the startup process, and if I set it to not autologin, it displays our custom greeter. This does not run as a particular user - I have tried putting a kanshi config into /root/ and starting kanshi as part of the greeter startup, but that doesn't work - the kanshi process starts but goes defunct (perhaps because it cannot find a valid config?)

Has anyone found a solution for setting a custom monitor resolution while in a greeter? I'd guess my best bet is to try a direct call to wlr-randr when the greeter starts based on a config in a file somewhere, but it feels a bit kludgey. TIA.

**Comment by Consolatis** [comment]
Isn't lightdm using X11?

**Comment by spl237** [comment]
No, it's WM agnostic - you can use it to start labwc and wayfire sessions, and run the greeter in the appropriate environment as well.

**Comment by Consolatis** [comment]
> This does not run as a particular user - I have tried putting a kanshi config into /root/ and starting kanshi as part of the greeter startup, but that doesn't work - the kanshi process starts but goes defunct (perhaps because it cannot find a valid config?)

I vaguely remember that lightdm on Debian has its own user and isn't run as root. But I am not sure about the details, its quite some time since I used it.

Capturing the kanshi logs might help.

**Comment by spl237** [comment]
Ah - copying a config file into /var/lib/lightdm/.config/kanshi seems to do something promising...

**Comment by droc12345** [comment]
display-setup-script=kanshi in lightdm.conf might do something

**Comment by spl237** [comment]
OK, got this working - you can copy a valid config to /var/lib/lightdm/.config/kanshi, and spawn kanshi as part of the greeter, and everything seems to work - thanks for the pointers!
