### ISSUE TITLE
Magnifier doesn't work with full-screen surfaces (direct scanout?)

### ISSUE THREAD

**Issue by jech** [labwc/labwc#1980]
The magnifier is a great feature for us middle-aged people, thanks a lot.

Unfortunately, it doesn't work with Brave (a Chromium variant) running in native Wayland mode ("Preferred Ozone Platform" set to "auto").  When toggling the magnifier over a Brave window, the maginifier keeps zooming in, as though it were magnifying itself.  When disabling the magnifier, the Brave window is corrupted where the magnifier used to reside, until I force a redraw by switching desktops and switching back again.

I've tried both by using the "ToggleMagnify" and "ZoomIn" actions, and the corruption is the same.

Since the magnifier is most useful with badly formatted web pages, this sadly makes it mostly useless for my usage.

**Comment by johanmalm** [comment]
Could you confirm that you're using `wlroots 0.17.4`
There was a bug that affect zoom before that version.

**Comment by jech** [comment]
I've just upgraded to 0.17.4, and the issue is still there.

**Comment by johanmalm** [comment]
> I've just upgraded to 0.17.4, and the issue is still there.

Might be worth doing a re-build + restarting the compositor if you haven't already.

What's in your `~/.config/chromium-flags.conf`?

I've got the following and it's working fine here

```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```

**Comment by jech** [comment]
> Might be worth doing a re-build + restarting the compositor if you haven't already.

I'm using Debian's pre-built version.  I have restarted after upgrading the shared library.  I can rebuild from sources if you think it's useful.

What's in your ~/.config/chromium-flags.conf?

I have no such file.  However, `chrome://gpu` indicates the following command line:
```
/opt/brave.com/brave/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --ozone-platform-hint=auto --flag-switches-end --ozone-platform=wayland --eye-dropper-not-supported --component-updater=url-source=https://go-updater.brave.com/extensions
```

**Comment by johanmalm** [comment]
> I'm using Debian's pre-built version.

Ah, what version is that? We only introduced `ZoomIn` + `ZoomOut` in `0.7.3` which released on Friday, so unless you're using some 'rolling-release' debian package, that might be why.

**Comment by jech** [comment]
0.7.3 has been in Debian Unstable since 13 July.  I confirm that the magnifier works fine both with foot (native Wayland) and with Emacs (X11), just not with Brave.

**Comment by johanmalm** [comment]
Right. Thanks for confirming. That clearly looks like a bug then.

**Comment by Consolatis** [comment]
I am really not sure why Brave could not be magnified. All the magnifier does is increasing some part of the output frame, it doesn't care about what it actually magnifies. Is there a difference if Brave is fullscreen vs maximized vs a smaller window?

**Comment by jech** [comment]
I can only reproduce the issue when Brave is maximised, the magnifier seems to work fine when Brave is windowed.

**Comment by tokyo4j** [comment]
Does starting brave with `--use-gl=egl` or `--use-gl=desktop` make any changes (you may need to modify `.desktop` file)?

**Comment by jech** [comment]
> Does starting brave with --use-gl=egl or --use-gl=desktop make any changes 

Either off those solves the issue (the magnifier works).  However, `chrome:gpu` indicates that either of these options disables use of the GPU (all items in the *Graphics Features Status* section or switched off, except for *Multiple Graphics Threads*).

**Comment by jech** [comment]
Ah!  I can reproduce the issue by running mpv in full screen.

Surprisingly, it happens even if I run `mpv --vo x11 --hwdec=none`.

**Comment by tokyo4j** [comment]
So are you running Brave in fullscreen mode? Then starting labwc with env var `WLR_SCENE_DISABLE_DIRECT_SCANOUT=1` might work, like #1764.

**Comment by Consolatis** [comment]
Right that could totally be the reason, fullscreen == maximized with CSD and no panels == potential direct scanout. I never looked into how that is implemented within wlroots but maybe we can simply disable direct scanout from our side when the magnifier is active.

**Comment by Nefsen402** [comment]
`scene->direct_scanout` is a private interface. Maybe it would be worth adding a bool to the options when calling either `scene_build_state` or `scene_output_commit`?

**Comment by Consolatis** [comment]
> `scene->direct_scanout` is a private interface. Maybe it would be worth adding a bool to the options when calling either `scene_build_state` or `scene_output_commit`?

I'd still prefer it over `wlr_output_lock_attach_render()` because it can basically not go wrong. Note that the fix is for wlroots 0.17 only for now but we'd carry it to 0.18 as well.

For wlroots 0.19 (which is a \*loooong\* time away) making it public or exposing a small wrapper function like `wlr_scene_prevent_direct_scanout()` sounds easier than throwing it in an option to `scene_build_state()`.

**Comment by Nefsen402** [comment]
`wlr_scene_prevent_direct_scanout()` relies on implicit state, I would not accept a patch like that.

**Comment by Consolatis** [comment]
> `wlr_scene_prevent_direct_scanout()` relies on implicit state, I would not accept a patch like that.

Well, `wlr_scene_prevent_direct_scanout(struct wlr_scene *scene, bool prevent_scanout)`.

**Comment by jech** [comment]
@Consolatis:

> @jech could you verify if WLR_SCENE_DISABLE_DIRECT_SCANOUT=1 indeed fixes it?

Yes, it looks like it does.  Tested with both Brave and mpv.

**Comment by Consolatis** [comment]
> > @jech could you verify if WLR_SCENE_DISABLE_DIRECT_SCANOUT=1 indeed fixes it?
> 
> Yes, it looks like it does. Tested with both Brave and mpv.

Sweet, thanks for testing.
Then #1989 should work as well. If you feel like it you could also test that branch (without the env var).

**Comment by jech** [comment]
> Then #1989 should work as well. If you feel like it you could also test that branch (without the env var).

Confirmed, it fixes the issue.

**Comment by Consolatis** [comment]
Should be fixed in the master branch (now requires wlroots 0.18) and the `v0.7` branch and thus be part of 0.7.4 likely released around Friday. Thanks for the report!
