### ISSUE TITLE
way to customize CapsLock behavior?

### ISSUE THREAD

**Issue by bdantas** [labwc/labwc#1986]
Is there a way to configure labwc so that CapsLock acts as an additional Backspace key? A separate, related question: How to configure a custom keyboard shortcut (e.g., both Shift keys pressed concurrently) to toggle the CapsLock state?

In X I can achieve both of the above with this command: `setxkbmap -layout us -option caps:backspace,shift:both_capslock`
 
Ideally, user would customize these behaviors in labwc's configuration (e.g., in `rc.xml`) and it would work in both wayland-native as well as xwayland applications. Is this currently possible?

**Comment by stefonarch** [comment]
Try in ` ~/.config/labwc/environment` for the   'XKB_DEFAULT_OPTIONS=`

**Comment by bdantas** [comment]
Hi stefonarch. Yes, it works with this in `~/.config/labwc/environment`:
```
XKB_DEFAULT_OPTIONS=caps:backspace,shift:both_capslock
```
Very nice. Thank you very much.
