### ISSUE TITLE
SnapToEdge does not work with Firefox

### ISSUE THREAD

**Issue by 1z-z1** [labwc/labwc#201]
Version: Built from source around 15:00 PST
OS: Postmarket OS / Alpine OS

Firefox is not moving with SnapToEdge but is working with MoveToEdge.

If I change the size of the Firefox window and then use SnapToEdge it will *sometimes* work but once it has been resized it no longer wants to move with SnapToEdge and MoveToEdge must be used.

**Comment by Joshua-Ashton** [comment]
Works fine here?

**Comment by johanmalm** [comment]
Thanks for reporting. Found a bug. Now fixed.

**Comment by 1z-z1** [comment]
Nice! 
Pulled, rebuilt and can confirm that Firefox is snap back and forth on the fly.
Thank you!
