### ISSUE TITLE
labwc is not detecting mouse clicks while the cursor is moving

### ISSUE THREAD

**Issue by akasmix** [labwc/labwc#2011]
I dunno how to explain it, but it seems that labwc detects mouse movement when you try to click a button (close, minimize) and completely ignores the click. If you point the mouse at a button and try to click it, the button ends up not being clicked due to micro-movements of the mouse. Or, if you do it slowly, but the mouse movement is a bit bigger, the drag is triggered instead of the click (possibly because you moved away from the button).

Is there a solution? Or is it my setup?

labwc 0.7.2

P.S. Sorry for my bad English, it's not my native language.

**Comment by tokyo4j** [comment]
That's strange, because `Press` actions should be executed if the press and release are done in the same button regardless of mouse movements.

Could you show me the output of running `labwc -d 2> log.txt` (from inside any wayland session or from VT) and trying to close any window with the top-right button?

In my setup, it says:
```
00:00:05.431 [../labwc/src/action.c:739] Handling action 24: Focus
00:00:05.431 [../labwc/src/action.c:739] Handling action 28: Raise
00:00:05.431 [../labwc/src/action.c:739] Handling action 2: Close
```

**Comment by Consolatis** [comment]
There were some changes in the default config regarding title and titlebar drag quite a while ago. If you still have an old configuration that might be the culprit and running labwc with its internal config like `labwc -c /dev/null` may fix it.

**Comment by akasmix** [comment]
Yes, that's it. I started from scratch and the problem seems to have gone away.
