### ISSUE TITLE
Application menus open in incorrect location when portion of window overlaps multiple outputs

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#2012]
I noticed that if I have an application window in which part of the window is on a second display, any in-application menus that are opened, open in the wrong location, on the wrong monitor.

Since it's hard to see it with screencap, I've attached a video recorded with my smartphone

I've confirmed this is the case on all applications, GTK and Qt applications, running in native Wayland (not XWayland, though XWayland apps like Steam exhibit similar behaviors)

Arch Linux, 3 monitors (tie-fighter layout, portraits on the side with a landscape in the middle), latest git build of labwc

https://github.com/user-attachments/assets/22610800-ee4c-4e5f-a189-5818df38299b

**Comment by Consolatis** [comment]
They are aligned on the monitor where the top left part of the window is located. Maybe we could use the whole output layout dimension as reference instead of a single output geometry.

**Comment by tokyo4j** [comment]
Following patch will fix this:
```diff
diff --git a/src/xdg-popup.c b/src/xdg-popup.c
index c17d195a..0b73bd74 100644
--- a/src/xdg-popup.c
+++ b/src/xdg-popup.c
@@ -27,10 +27,10 @@ popup_unconstrain(struct xdg_popup *popup)
 {
 	struct view *view = popup->parent_view;
 	struct server *server = view->server;
-	struct wlr_box *popup_box = &popup->wlr_popup->current.geometry;
+	struct wlr_box *scheduled = &popup->wlr_popup->scheduled.geometry;
 	struct output *output = output_nearest_to(server,
-		view->current.x + popup_box->x,
-		view->current.y + popup_box->y);
+		view->current.x + scheduled->x,
+		view->current.y + scheduled->y);
 	struct wlr_box usable = output_usable_area_in_layout_coords(output);
 
 	struct wlr_box output_toplevel_box = {
```

`wlr_popup->scheduled.geometry` stores the geometry designated by `xdg_positioner` before unconstraining.

**Comment by stefonarch** [comment]
Can confirm both the issue and the patch above  working. The PR though didn't fix it, it misses some changes?

**Comment by tokyo4j** [comment]
> Can confirm both the issue and the patch above working. The PR though didn't fix it, it misses some changes?

That's strange. The PR is logically the same as the patch above. What application are you testing with?

**Comment by stefonarch** [comment]
I'll retest again later, I applied the PR patch manually and it didn't work. Testing is with featherpad (the "help" menu), here with the patch above:

![screen_full_sab_22:08:52_](https://github.com/user-attachments/assets/ca966f8d-69f3-405c-b7a9-23100596add0)

**Comment by tokyo4j** [comment]
> The PR doesn't contain
> ```
> -		view->current.x + popup_box->x,
> -		view->current.y + popup_box->y);
> +		view->current.x + scheduled->x,
> +		view->current.y + scheduled->y);
>```

That's just because I decided not to rename `popup_box` to `scheduled` in the PR. It should not change anything in the binary. Popups in featherpad works fine with the PR in my setup.

**Comment by tokyo4j** [comment]
@stefonarch
If you still have the issue, feel free to report it again.
