### ISSUE TITLE
xdg-popup: un-constraining is incorrect with gedit (CSD clients with shadow)

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#2017]
Looks like `wlr_xdg_popup_unconstrain_from_box()` takes the constraint box relative to top-left of `wl_surface` geometry rather than top-left of window geometry designated by `set_window_geometry` request.

![20240721_22h03m34s_grim](https://github.com/user-attachments/assets/cd478785-a147-440e-95a3-00014af7e21f)

**Comment by Consolatis** [comment]
Fixed by
- #2016
