### ISSUE TITLE
Animations & desktop effects

### ISSUE THREAD

**Issue by orfeasxyz** [labwc/labwc#2019]
Coming from X11, it was common to use a compositor like picom for various effects (e.g. blurring, focused vs unfocused darkening) and animations (fading in/out). It would be nice if we could support these kind of effects. I personally don't deem this is as a must-have feature but I would like some extra visual clarity.

**Comment by ahesford** [comment]
Such things are [https://github.com/labwc/labwc?tab=readme-ov-file#11-what-is-this](expressly contrary to the intent of the project]. Compositors like Wayfire exists to fill this niche.
