### ISSUE TITLE
Unable to select all text in certain GTK text input fields

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#2039]
I'm tracking an issue in the latest git build where the text in GTK text input fields -- specifically in the file picker window -- will not remain selected all. In my testing it seems that this is an issue with GTK+labwc (and it might just be GTK3); Qt and other toolkit file pickers don't have this issue. I tested this in latest Arch repo sway on the same machine and it is not a problem, so it appears to be a labwc issue.

To reproduce:

I used  the Pinta image editor, but saw it in other applications as well that use GTK3; for instance the Drawing image editor. I do not have a GTK4 app that uses a file picker to test with.  

If I attempt to Save an image I am presented with the GTK file picker dialog. I am presented with the 'Unsaved Image 1.jpg' text in the Name field:

![image](https://github.com/user-attachments/assets/f34c4c5e-3a0b-4fe1-9226-5b6987351534)

If I attempt to double-click to select all of the text in that field, or if I try to use Ctrl-A to select it all, or if I try and click and drag across the text to select it, it will not remain selected.

Not really sure what other info I can bring, but this is consistent across applications

labwc-git 0.7.3.r52.g750d37b1-1

**Comment by winteriscariot** [comment]
I used Foliate to test the GTK4 file picker and the issue appears to be in GTK4 as well

**Comment by tokyo4j** [comment]
What do you mean by "not remain selected"? When you select the texts by double click or Ctrl-A, does it transiently gets selected and then instantly gets unselected without any subsequent interaction?

**Comment by winteriscariot** [comment]
Did a quick screen grab to show it in action. It's most obvious when you drag-and-select the text, cuz you can see as soon as I let go of the mouse button the selection goes away.

It's harder to see since I don't have a camera on my keyboard, but when the text cursor jumps to the end of the text field is when i'm pressing Ctrl-A

I'd say it gets transiently selected but only for like 1ms, it's so quick you can't really see it.

[Kooha-2024-07-31-06-10-45.webm](https://github.com/user-attachments/assets/181717a7-78b7-4eb5-a784-206f51142ec8)

**Comment by tokyo4j** [comment]
Unfortunately, I cannot reproduce the issue.

Does the issue still exist when you launch labwc with `labwc -C /tmp`? (you will need to install `foot`, press `Super+Enter` to start it and launch `pinta` from it)

**Comment by davidphilipbarr** [comment]
I had this happen when i was running a clipboard manager (wl-clip-persist) killing it sorted out the problem.

**Comment by winteriscariot** [comment]
> I had this happen when i was running a clipboard manager (wl-clip-persist) killing it sorted out the problem.

thanks for the hint!! i'll fiddle with that cuz i'm definitely running a clipboard manager

**Comment by winteriscariot** [comment]
For anyone else coming across this issue, the relevant issue in wl-clip-persist is here: https://github.com/Linus789/wl-clip-persist/issues/3

running it with `--clipboard regular` instead of `primary` or `both` fixes the issue.
