### ISSUE TITLE
Build Failure on Gentoo due to wlroots versions

### ISSUE THREAD

**Issue by tidux** [labwc/labwc#2053]
Please update the ebuild to enable support for wlroots 0.18.

`Dependency wlroots found: NO. Found 0.18.0-dev but need: '<0.18.0' ; matched: '>=0.17.0'`

**Comment by tidux** [comment]
That's the opposite problem I have, it refuses to build with 0.18.

**Comment by droc12345** [comment]
Which ebuild are you using? Which distro?

**Comment by Consolatis** [comment]
> That's the opposite problem I have, it refuses to build with 0.18.

Right, it looks like Gentoo packaged wlroots 0.18 weirdly then, the last version of `wlroots` should be 0.17.x. Starting from wlroots 0.18 it got its `0.18` version included in the `.pc` file and uses a `/usr/include/wlroots-0.18/` sub directory allowing multiple version of wlroots to be installed simultaneously. See for example the experimental Debian [package](https://packages.debian.org/experimental/arm64/libwlroots-0.18-dev/filelist).

So unless that is being fixed I guess the only three options are
- compiling manually (and thus use the wlroots.wrap file included in the labwc repo)
- using the `labwc-9999` [package](https://gpo.zugaina.org/Overlays/wayland-desktop/gui-wm/labwc) which seems to correspond to the current master branch and thus should work with wlroots 0.18
- waiting 1 and a half weeks until we release 0.8.0

**Comment by thesamesam** [comment]
In the end, I think this issue was https://bugs.gentoo.org/935705.
