### ISSUE TITLE
Feature Request: Add config in NixOS Home-Manager

### ISSUE THREAD

**Issue by saveliybyru** [labwc/labwc#2058]
Hello!
I use NixOS and earlier used only Gnome, but i would like use LabWC and now I write this issue from LabWC =)
And I planned in future use full time this WM. It's cool, but not comfortable configuration only LabWC not in home-manager.
What do you think about this idea?
Thank's for added LabWC into nixpkg.

**Comment by ahesford** [comment]
I suspect this request is better made of the home-manager project.

**Comment by johanmalm** [comment]
@saveliybyru welcome!

We can help you build from scratch, configure, etc. but this seems to relate to a NixOS and we're trying to not get into distro-space.

You might be able to get some help from distro-maintainers if it's not clear in their documentation.

https://github.com/labwc/labwc/blob/master/CONTRIBUTING.md#packaging
