### ISSUE TITLE
Mouse action not working on client when context Set to None

### ISSUE THREAD

**Issue by netfun81** [labwc/labwc#2062]
I have an application that uses Alt-Left mouse button + drag to zoom.   The default A-Left drag action moves the window.  Therefore I disabled it in my rc.xml with:
``    <context name="Frame">
      <mousebind button="A-Left" action="Drag">
        <action name="None" />
      </mousebind>
    </context>   
``
That disabled the client window from moving when I press Alt-left mouse button and drag.   However, it also disabled that function within my application.    Is there a workaround for this?    Thanks

**Comment by droc12345** [comment]
I typically just add another modifier, rather than try and disable it.
Or you could just comment it out.

**Comment by netfun81** [comment]
I tried changing it to "focus" instead of "None" and then my application would focus when I pressed Alt-Left mouse button drag instead of using its own internal hotkey, is there a way to ignore the mouse command completely in rc.xml?

**Comment by Consolatis** [comment]
> That disabled the client window from moving when I press Alt-left mouse button and drag. However, it also disabled that function within my application. Is there a workaround for this? Thanks

You mean that also disables the zoom function in your application?

You might also need to disable the `Press` action for `A-Left`, e.g. something like
```xml
<mouse>
	<default />
	<context name="Frame">
		<mousebind button="A-Left" action="Press" />
		<mousebind button="A-Left" action="Drag" />
	</context>
</mouse>
```

**Comment by netfun81** [comment]
Thank you Consolatis!  I set A-Left Press to none and that prevented the mouse grabbing from my application.  Makes sense now.  Really enjoying having an openbox experience on wayland.  Great work devs.

**Comment by netfun81** [comment]
working fine closing issue
