### ISSUE TITLE
Disabling root menu

### ISSUE THREAD

**Issue by humaidq-tii** [labwc/labwc#2063]
I couldn’t find an option to disable the root menu, and setting it to empty automatically populates: https://github.com/labwc/labwc/blob/72df8fe73c9c42cd0d7362dbf87d7956ed78a635/src/menu/menu.c#L846

For some setups/scenarios it might be useful to disable this menu.

**Comment by Consolatis** [comment]
You can disable the root menu via `rc.xml`:

```xml
<mouse>
	<default />
	<context name="Root">
		<mousebind button="Left" action="Press" />
		<mousebind button="Right" action="Press" />
		<mousebind button="Middle" action="Press" />
	</context>
</mouse>
```

**Comment by p2ndemic** [comment]
> You can disable the root menu via `rc.xml`:
> 
> <mouse>
> 	<default />
> 	<context name="Root">
> 		<mousebind button="Left" action="Press" />
> 		<mousebind button="Right" action="Press" />
> 		<mousebind button="Middle" action="Press" />
> 	</context>
> </mouse>

thank you!
