### ISSUE TITLE
Hotplug event and output restore functionality doesn't seem to restore output's scale on Kanshi event

### ISSUE THREAD

**Issue by kode54** [labwc/labwc#2064]
I have two outputs, DP-1 (LG 24UD58-B - 3840x2160@60Hz, defaults to 1.0 scale, Kanshi overrides this to 2.0 on startup and hotplug), and DP-2 (Dell P2414H - 1920x1080@60Hz, defaults to 1.0 scale, Kanshi not really overriding anything here).

On hotplug, such as changing FreeSync mode, or when DPMS powers the monitor back on, or if I power it off manually, and it reconnects on power on. This event causes windows to migrate momentarily to DP-2 and back again to DP-1. DP-1 also spends an instant at 1.0 scale, so some windows also change sizes for just an instant.

Some windows don't restore their scale back to 2.0 properly. Thus far, the list includes:
* SwayNC
* Telegram Desktop
* wf-background (if I happen to be using it instead of swaybg)

Other(s) don't seem to restore outputs properly, and get stuck displaying things on DP-2:
* mako

**Comment by Consolatis** [comment]
Are there clients (like foot) which properly update when kanshi kicks in with the new scale?
If yes that would indicate client issues with the ones you mentioned, if foot also doesn't react to the new scale it might be some labwc or wlroots issue.

**Comment by kode54** [comment]
Closing this as a Client issue, but I'll make note of this information to reproduce it for those projects.
