### ISSUE TITLE
layer-shell BOTTOM layer + popup (like menus) gets mouse focus confused

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#207]
Panel is a layershell client which uses `BOTTOM` layer + exclusive zone. When a menu opens and leaves the exclusive zone it is rendered on top of the other toplevels. When you hover over an item it is correctly selected:
![zindex-1](https://user-images.githubusercontent.com/35009135/148675758-e78d191e-4060-4839-aa0f-90ee8a43c707.png)
However if there is another toplevel behind, it will get the mousefocus instead of the menu. Same happens for context menus on the lower panel.
![z-index](https://user-images.githubusercontent.com/35009135/148675760-7f87a07a-9b14-4804-a337-b8ca369aee94.png)
This is very confusing and it should be the same for rendering and for mouse focus.
I guess panels should always use the TOP layer when they have any kind of popups like menus the user can interact with.

If that is the design decision made then menu popups of `BOTTOM` layer layershell clients should be rendered below the other toplevels. Otherwise the mousefocus should follow the the rendering.

**Comment by johanmalm** [comment]
Good spot. I think it's right that the panel is `BOTTOM` - we just need the `view_at()` / `surface_at()` type function to deal with layer-popups in the same order they are rendered.

Would this sort of thing work?

```
diff --git a/src/desktop.c b/src/desktop.c
index 277e331..0ac21d5 100644
--- a/src/desktop.c
+++ b/src/desktop.c
@@ -313,6 +313,34 @@ wlr_surface *layer_surface_at(struct wl_list *layer, double ox, double oy,
 	return NULL;
 }
 
+static bool
+surface_is_xdg_popup(struct wlr_surface *surface)
+{
+	if (wlr_surface_is_xdg_surface(surface)) {
+		struct wlr_xdg_surface *xdg_surface =
+			wlr_xdg_surface_from_wlr_surface(surface);
+		return xdg_surface->role == WLR_XDG_SURFACE_ROLE_POPUP;
+	}
+	return false;
+}
+
+static struct wlr_surface *
+layer_surface_popup_at(struct output *output, struct wl_list *layer,
+		double ox, double oy, double *sx, double *sy)
+{
+	struct lab_layer_surface *lab_layer;
+	wl_list_for_each_reverse(lab_layer, layer, link) {
+		double _sx = ox - lab_layer->geo.x;
+		double _sy = oy - lab_layer->geo.y;
+		struct wlr_surface *sub = wlr_layer_surface_v1_surface_at(
+			lab_layer->layer_surface, _sx, _sy, sx, sy);
+		if (sub && surface_is_xdg_popup(sub)) {
+			return sub;
+		}
+	}
+	return NULL;
+}
+
 struct view *
 desktop_surface_and_view_at(struct server *server, double lx, double ly,
 		struct wlr_surface **surface, double *sx, double *sy,
@@ -329,6 +357,8 @@ desktop_surface_and_view_at(struct server *server, double lx, double ly,
 	double ox = lx, oy = ly;
 	wlr_output_layout_output_coords(output->server->output_layout,
 		wlr_output, &ox, &oy);
+
+	/* Overlay-layer */
 	*surface = layer_surface_at(
 			&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY],
 			ox, oy, sx, sy);
@@ -336,6 +366,27 @@ desktop_surface_and_view_at(struct server *server, double lx, double ly,
 		return NULL;
 	}
 
+	/* Check all layer popups */
+	*surface = layer_surface_popup_at(output,
+			&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_TOP],
+			ox, oy, sx, sy);
+	if (*surface) {
+		return NULL;
+	}
+	*surface = layer_surface_popup_at(output,
+			&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM],
+			ox, oy, sx, sy);
+	if (*surface) {
+		return NULL;
+	}
+	*surface = layer_surface_popup_at(output,
+			&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND],
+			ox, oy, sx, sy);
+	if (*surface) {
+		return NULL;
+	}
+
+	/* Top-layer */
 	*surface = layer_surface_at(
 			&output->layers[ZWLR_LAYER_SHELL_V1_LAYER_TOP],
 			ox, oy, sx, sy);
```

**Comment by johanmalm** [comment]
I've installed mate-panel 1.26.1 but can't reproduce the issue.
If the above patch doesn't work, could you let me know what branch/version you're using and I'll try to build mate-panel.

**Comment by Consolatis** [comment]
That panel in the screenshots is something I wrote but didn't publish yet. Mate-panel uses `BOTTOM` layer as well though and behaves the same for me. Tested with PRs https://github.com/mate-desktop/mate-panel/pull/1275 and https://github.com/mate-desktop/mate-panel/pull/1276 merged into a new brach but should show the same behavior without those PRs. I didn' test any commits of those branches where forked from `master`.

Here is a much simpler reproducer:
```
#!/usr/bin/env python3

import gi

gi.require_version("Gtk", "3.0")
gi.require_version('GtkLayerShell', '0.1')
from gi.repository import Gtk, GtkLayerShell

class Panel(Gtk.Window):
	def __init__(self):
		super().__init__(title="Crash test")
		self.set_size_request(200, -1)

		menu = Gtk.Menu()
		bug = Gtk.MenuItem.new_with_label("Bug")
		bug.set_submenu(menu)

		trigger = Gtk.MenuItem.new_with_label("Trigger")
		trigger.set_tooltip_text("foobar")
		menu.append(trigger)

		notrigger = Gtk.MenuItem.new_with_label("No Trigger")
		menu.append(notrigger)

		quit = Gtk.MenuItem.new_with_label("Close")
		quit.connect('activate', lambda menuitem : Gtk.main_quit())
		menu.append(quit)

		menubar = Gtk.MenuBar()
		menubar.append(bug)

		menu = Gtk.Menu()
		for x in range(10):
			item = Gtk.MenuItem(label=f"Test category {x}")
			submenu = Gtk.Menu()
			for y in range(10):
				submenu.append(Gtk.MenuItem(label=f"Test entry {y}"))
			item.set_submenu(submenu)
			menu.append(item)
		layertest = Gtk.MenuItem(label=f"Layer test")
		layertest.set_submenu(menu)
		menubar.append(layertest)
		self.add(menubar)

panel = Panel()
GtkLayerShell.init_for_window(panel)
GtkLayerShell.auto_exclusive_zone_enable(panel)
GtkLayerShell.set_anchor(panel, GtkLayerShell.Edge.TOP, True)
GtkLayerShell.set_anchor(panel, GtkLayerShell.Edge.LEFT, True)
GtkLayerShell.set_anchor(panel, GtkLayerShell.Edge.RIGHT, True)
GtkLayerShell.set_layer(panel, GtkLayerShell.Layer.BOTTOM)
GtkLayerShell.set_namespace(panel, "panels")

panel.show_all()
Gtk.main()
```
Requires `python3-gi`, `gir1.2-gtklayershell-0.1`  and `gir1.2-gtk-3.0` (package names on Debian).

Will test your diff later and report back.

**Comment by Consolatis** [comment]
Your diff fixed the issue for me and I didn't discover any negative side effects yet :)

Only thing left is that the extended areas around toplevels which allow resizing[^1]  are bleeding into the panels.
Example is if maximizing a toplevel, the resize area below and above the toplevel are on top of the panels and are still triggering a resize of the toplevel (and show the resize edge cursors). They thus prevent interacting with the panel unless the panels are larger than the resize extends + you move the pointer way up/down before clicking.
If the panels are using the `TOP` layer that doesn't happen.

[^1]: Best feature ever by the way, I absolute hate that on Mate you have to target a 1px wide border to resize if not using `A-RMB`

**Comment by ahmadraniri1994** [comment]
So, is mate panel really usable on labwc? Thanks.
It needs xwayland or run natively on Wayland?

**Comment by Consolatis** [comment]
@ahmadraniri1994 Honestly: no.
It doesn't even have a context menu for close / maximize / minimize nor icons in the task switcher.

**Comment by ahmadraniri1994** [comment]
> @ahmadraniri1994 Honestly: no. It doesn't even have a context menu for close / maximize / minimize nor icons in the task switcher.

Yeah, but run natively on Wayland is more than enough for me, I still have waybar which provide taskbar and other stuffs. Thanks and I'm really glad to find this post.

**Comment by Consolatis** [comment]
@ahmadraniri1994 Yes, the traditional "top" panel mostly works (app menu, application launchers, clock, ..). Applets apparently have to be build in-process. Be aware of another bug (#189) though that if you hover over an item in the menu until it shows a tooltip and then click that item the panel will crash. The bug is likely a labwc bug but that hasn't been verified yet.

**Comment by 01micko** [comment]
@Consolatis if and when you do release your unnamed panel you will have a keen tester here. Apologies for slight off topic.

**Comment by johanmalm** [comment]
> Only thing left is that the extended areas around toplevels which allow resizing[1](#user-content-fn-1-df86c50b14647d43a989a155596cf4a5) are bleeding into the panels.

Fixed. Thanks for point it out.

**Comment by Consolatis** [comment]
Perfect. Just had a quick test and I think all issues about panels in `BOTTOM` layer have been fixed.

@johanmalm Thank you :)

**Comment by johanmalm** [comment]
Just realised that the resize cursor fix won’t work for clients with CSD. Will do a more generic solution tomorrow.
