### ISSUE TITLE
`zwlr_foreign_toplevel_handle_v1::output_enter` is not sent when xwayland surface is re-mapped

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#2074]
When I close a window of Slack desktop app, its xwayland surface is unmapped and the corresponding taskbar item disappears (and then slack app runs in background). However, when I open Slack again and the xwayland surface is re-mapped, its taskbar item is still missing.

I confirmed following patch fixes this issue:

```diff
diff --git a/src/xwayland.c b/src/xwayland.c
index 738c2b17..e7b4b148 100644
--- a/src/xwayland.c
+++ b/src/xwayland.c
@@ -771,6 +771,8 @@ xwayland_view_map(struct view *view)
 	if (xwayland_surface->strut_partial) {
 		output_update_all_usable_areas(view->server, false);
 	}
+
+	foreign_toplevel_update_outputs(view);
 }
 
 static void
```

In my observation, the reason why xdg surfaces don't suffer from this bug is that `handle_commit() -> view_impl_apply_geometry() -> view_moved() -> view_update_outputs()` sends `output_{enter,leave}` events when re-mapped, since `view->{pending,current}` and `view->outputs` are reset to zero on unmap (if I understand correctly).

~I'd like to delegate this to other devs as I don't know how commit/map/unmap work in xwayland.~

**Comment by Consolatis** [comment]
Hm, I have a feeling that we should just do `foreign_toplevel_update_outputs()` whenever creating a new foreign_toplevel_instance so we sync the initial outputs at hat point. Another option here could be to verify that `view->outputs` is correctly reset on unmap and thus detects new outputs when mapping.

**Comment by tokyo4j** [comment]
> Hm, I have a feeling that we should just do foreign_toplevel_update_outputs() whenever creating a new foreign_toplevel instance so we sync the initial outputs at that point.

Agreed. I opened #2075 with that approach.

> Another option here could be to verify that view->outputs is correctly reset on unmap and thus detects new outputs when mapping.

I considered this approach at first, but the former approach turned out to be simpler for this issue.
