### ISSUE TITLE
lab_wlr_scene_output_commit should update after wltoots 0.18 update

### ISSUE THREAD

**Issue by yuiiio** [labwc/labwc#2078]
since 
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/06d301bf1a15826fb6ab89b9c40d40ecb86060cc

https://github.com/labwc/labwc/blob/master/src/common/scene-helpers.c#L45
```diff
        if (!wlr_output->needs_frame && !pixman_region32_not_empty(
-                       &scene_output->damage_ring.current) && !wants_magnification) {
+                       &scene_output->pending_commit_damage) && !wants_magnification) {
                return true;
        }
```
this and wlroots !4753 fixes fullscreen(direct scan-out) VRR.(broken since wlroots 0.18 update)

**Comment by Consolatis** [comment]
This will sadly break the magnifier but after some talks with @Nefsen402 we found a suitable solution that should work with wlroots 0.18.0 and 0.18.1 (when the wlroots fixes are backported).

I'll open a PR later, thanks for bringing this up!

**Comment by yuiiio** [comment]
thank you! Consolatis
