### ISSUE TITLE
backward text

### ISSUE THREAD

**Issue by spectrum70** [labwc/labwc#209]
Hi all,
i like to open the (possible) issue with 

"labwc is a great job" :)

I am using master, just fetched.  35e24a67ec9743af36901fe4641f76bf173ec88e
I noticed this: when you put mouse focus on google search box, in the browser, and just after you move the mouse to the left side, outside of the browser window perimeter, and you now type in the google box, the text is displayed backward, as nice magic reverse effect :)

Shoud be simple to reproduce. I am not sure by the way if it is a labwc or wayland/wlroots related.

**Comment by bi4k8** [comment]
I wasn't able to reproduce this behavior, using Wayland-native Chromium (`--enable-features=UseOzonePlatform --ozone-platform=wayland`) on a nested `labwc -c /dev/null` also from commit 35e24a6.

Can you clarify:
- the browser you used (Chrome, Chromium, Firefox, or something else)
- whether the browser is Wayland-native or running through XWayland
- whether you're referring to the search box in the browser's navigation bar or the search box in the page at https://google.com/
- whether the order of the letters is reversed or whether the entire piece of text is displayed as a mirror image
- where the reversed letters are visible (in the search box or as a copy elsewhere on the screen)

A screenshot or screencast might also help.

**Comment by johanmalm** [comment]
Also, do you get the same in sway?

**Comment by spectrum70** [comment]
I could try several times before being able to reproduce this.

The reason of the issue seems to be the fact the cursor stay blocked on the left of the box while typing.

Chromium Version 96.0.4664.93 
i am in Xwayland
Search box in the page

file:///home/angelo/Pictures/screenshot_202201131642113444.png

**Comment by Consolatis** [comment]
That is a nice bug. It almost makes the magic smoke come out.
In some situations labwc will erroneously send release events for keys or mouse buttons. Maybe something like that happened here and Chromium interpreted something as a Unicode RTL character or the release events triggered some Chromium or XWayland client keyboard layout feature.

**Comment by johanmalm** [comment]
Would you mind checking if it's fixed with the recent commits?
If it isn't, is there any chance you could track down when this started. Maybe start by checking out the tagged versions to get a feel for when it started.

**Comment by spectrum70** [comment]
I just verified  master
0c0c54fe43980a23b3064bcffe86bcd2b064c712

Still issue is open.

It happens also on dissenter browser.

To make it happening, looks like you need to type while mouse moves to the left side. Something like, focusing google search box, and moving mouse left just after, while typing, quite difficult i know. Anyway, will try to find a best way.

**Comment by AndersonTorres** [comment]
Just passing here randomly, this same "gnitirw drawkcab" heisenbug sometimes happened to me when I used another WM, namely, cardboard.

It happened randomly, whenever I tried to fill some form like the GitHub title for an issue. Coincidentally, it happened when I used Brave.

I "solved" this by merely changing to another tab or another application and coming back.

**Comment by spectrum70** [comment]
Hi,
a nearly 100% working way to reproduce it
- open google (but i see whatever textbox on whatever app may be the same)
- perform a search and get the google page changed with textbox on top, as attached
 file:///home/angelo/Pictures/screenshot_202202021643794731.png

- in the google search box type abc and double click on it select the text by mouse
- then keeping left mouse button clicked move fast the mouse out of the browser window, left side
- now type, text should be seen backward

It is just the effect of cursor staying on left side of the box.

**Comment by johanmalm** [comment]
https://octodon.social/@emersion

Does compiling against wlroots 0.15.1 help?

**Comment by spectrum70** [comment]
Issue still there with wlroots 0.15.1

**Comment by acoolstraw** [comment]
Does it still happen? Do you use Nvidia drivers?

**Comment by johanmalm** [comment]
Could you test this with the master branch? It’s likely it’s been resolved.

**Comment by Consolatis** [comment]
Will close this for now, feel free to comment here if this is still an issue on the latest master branch.
