### ISSUE TITLE
latest commits on master break gtk2 applications conky but gtk3 still work

### ISSUE THREAD

**Issue by fungilife** [labwc/labwc#2098]
First I noticed conky then many gtk2 didn't work, while their corresponding gtk3 versions worked (sakura leafpad lxpanel ... pcmanfm )

rc11 was the latest tried

**Comment by johanmalm** [comment]
By `rc11`, do you mean commit `107d84c` (11 commits after `0.8.0`)?
Is that definitely the "breaking" commit?
Can you try with `0.8.0` - or even `0.7.4` to confirm if it works with those.
What is the error you get with the gtk2 versions?

**Comment by fungilife** [comment]
Yes, joborun offers both stable 0.8.0 replacing 0.7.3 and 0.7.4 and a labwc-git pkg currently labwc-git 0.8.0.r4.g497d3d8e  all work well
r11.g107d84ce and I think the one before it were breaking conky and gtk2 apps

**Comment by droc12345** [comment]
gtk2 has never worked well with wayland, and I doubt it ever will.

**Comment by Consolatis** [comment]
There were only these commits between 0.8.0 and current master:
- cd961b1a (HEAD -> master, origin/master, origin/HEAD) action: add Enable/DisableTabletMouseEmulation
- 107d84ce scaled-font-buffer.c: initialize `buffer` to avoid bug waiting to happen
- 9bc381d9 menu: use theme->menu_item_height instead of menu->item_height
- 0552c6b7 menu: support titles
- a368bbee Add unit test for common/buf.c
- 5ae9eed1 src/menu: prevent delayed pipe menu response on item destroy
- c4b8b531 Translation updates from weblate
- 05bbb9b3 Translation updates from weblate
- 497d3d8e output: set 'labwc' as app_id and title for nested outputs (reported last good above)
- 33820c2a xwayland: remove dissociate work-around
- 8b12b501 xdg: destroy foreign toplevel handle on unmap
- f3145739 xwayland: sync foreign-toplevel and associated outputs on re-map
- 98c876d7 (tag: 0.8.0) build: bump version to 0.8.0

None of these change anything in regards to GTK 2 or window handling.
How exactly are GTK 2 apps and conky broken?

**Comment by droc12345** [comment]
gtk2 should work ok under xwayland, as it does understand X. 
If you're running gtk2 apps under Xwayland, then I'd look at changes for that.

**Comment by fungilife** [comment]
I am just reporting what I've witnessed, all mentioned things have never had a problem before and up to the 4th rc past 0.8.0 release, now they are all broken.   Reverting back to previous 0.8.0 and rc4 cures the problem, nothing else altered in the system.

**Comment by droc12345** [comment]
Are you running the apps under Xwayland?

How are they broken?

**Comment by fungilife** [comment]
off course they run under xwayland, how else would they run?

This is an arch like system without systemd, for a some time (0.7.0 +) we have had labwc as our #1 wayland solution, several people excited about it, contributing, modifying, trying stable and rc builds ... 

This is the first time we have experienced this.

**Comment by fungilife** [comment]
rc12 d961b1a  same thing
"cannot open display"
A few also say segmentation fault

All gtk3 built software work fine

**Comment by Bluey26** [comment]
I would not discard some changes in the other apps. I use `conky `and from time to time it seems to crash in here. But i am using `labwc 0.7.3-72-g00512d05`

coredumpctl says that it is a `SIGSEGV` I could provide more information, but i do not see anything related to labwc in the `coredump info conky` but things about X11 and libstc++

OS is Archlinux, systemd

**Comment by Consolatis** [comment]
> "cannot open display"
That sounds like the `DISPLAY` env var isn't set for some reason or maybe something regarding the permissions for `/tmp/.X11-unix/X0` is wrong. If it mainly affects GTK 2 application it might also be an indicator that something regarding GTK2 or its packaging has changed in a subtle way.

Another option could be that labwc or wlroots disabled some feature like xwayland during compilation, a look in the build logs might help there.

**Comment by 01micko** [comment]
FWIW I'm running  latest`vivaldi` (chromium clone) via Xwayland, `urxvt` runs and `mhwaveedit` runs (gtk2) and I updated  `labwc` master to latest commit 5 minutes ago. Slackware64-current base.

**Comment by 01micko** [comment]
Oh, forgot also running `conky`, but that *should* run as an `xdg-shell` app if built correctly.

**Comment by fungilife** [comment]
The only thing changing in this system is labwc, nothing else, and reverting to r4 cures the problem.

Here is another clue I noticed today that may help identifying the problem:

One can start labwc within X and it starts as an X-window.  With previous editions starting say leafpad (gtk2) from say foot inside the labwc window, starts leafpad within that wayland window, with newer versions (where I get "can't open display" and exits, it starts the gtk2 application in X.  If I do the same with l3afpad it starts within the wayland window session.

**Comment by fungilife** [comment]
> **PS1**: After i realized i could upgrade the package to 0.8.0, i did it. After restarting the system, `conky` seems to still work in here, and `leafpad` works too.

The problem starts beyond 0.8.0 between the 5th and 12th rc (10-11-12th) seem to have the problem, reverting to 4th cures it.  We stay as close to arch as possible with the exception of systemd/logind/dbus but Xorg pkgs haven't changed much in a long while.

gtk 2 and 3 have changed a month or two ago, we have had several labwc builds since then.  It may very well be something we need to adjust to comfort labwc but in this case it is the only thing changing back/forth fixing/breaking and little feedback on what is causing it.

**Comment by Consolatis** [comment]
You can start labwc with `labwc -d 2>/tmp/labwc.log`, then once started start a native X11 application like `xcalc`. Should also work nested on top of an already running labwc. Then post the logfile.

**Comment by fungilife** [comment]
https://termbin.com/2lix

problem rc10-12
x11:  xdg: wayland-0

no problem  rc4
x11: :1 xdg: wayland-0

**Comment by fungilife** [comment]
I build r19 now (latest) and problem is solved

xwayland is not a make dependency it is not present in build (meson auto on) but is listed as running dependency for the pkg.
