### ISSUE TITLE
New windows don't always receive keyboard focus

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#210]
If the cursor is over an existing window, new windows do not receive keyboard focus. This makes it frustrating to e.g. open a terminal and begin typing it, because it requires finding the cursor and moving it onto the newly-opened window.

This behavior is relatively recent, perhaps related to focus cleanups around maximize/etc.

**Comment by johanmalm** [comment]
Linked to this?

https://github.com/labwc/labwc/commit/6651d45ed44e2af28e8f99f326cb4ef4190f0bdd

**Comment by bi4k8** [comment]
Yep, reverting 6651d45 fixes this for me.

**Comment by johanmalm** [comment]
I'm hoping this is not fixed. Would appreciate feedback if possible.

**Comment by johanmalm** [comment]
Believe this is fixed
