### ISSUE TITLE
wlroots 0.16.0 compatibility

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#211]
https://github.com/swaywm/sway/commit/d6f8820a8b7190a2ce76a0f140e1514e2c32dd50

**Comment by ARDiDo** [comment]
Since our master branch is based off of wlroots 0.15.0, do you want to create an alternative branch to chase the wlroots master branch?

**Comment by johanmalm** [comment]
Can’t make up my mind what’s best. What do you think?

I thought I’d just watch sway for any breaking changes in wlroots, log them here and deal with them later. I guess it’s the lazy, simple approach, but could avoid a headache if we do significant code re-factoring like splitting labwc.h into separate head files.
The advantage of maintaining a branch tracking 16, is that it’s easier to check if odd bugs are fixed through changes in wlroots

**Comment by ARDiDo** [comment]
Yeah, I think that this lazy approach will save us some headaches that we'd get from creating a separate branch.

**Comment by johanmalm** [comment]
Ha ha. Sounds like the beginning of a profound development policy... laziness before complexity :smiley:

**Comment by droc12345** [comment]
I've made a couple of changes, one to meson files, the other to add includes so latest labwc git compiles against latest wlroots git.

https://github.com/droc12345/labwc/commit/66251c6335047c8740c65304dceb7453fbd24de3
This patch adds a system_wlroots option, to allow for disabling using system wlroots and instead using the latest git version.
It also changes the meson.build file to incorporate the new option and pretties up some of the file.
It also changes the pointer in wlroots.wrap to point to HEAD (always latest git)

https://github.com/droc12345/labwc/commit/240340af5cfa92d5b40467612aacd63449ebd582
This patch replaces wlr_surface.h with wlr_{sub}compositor.h (wlr_surface.h is being depreciated) in layers.h
and adds layers.h to subsurface.c and xdg.c (to get them to compile - gcc 11.2)

**Comment by johanmalm** [comment]
Covered by PR #238
