### ISSUE TITLE
RFC: nomenclature for "Omnipresent" button and its theming

### ISSUE THREAD

**Issue by ahesford** [labwc/labwc#2112]
From https://github.com/labwc/labwc/issues/2111#issuecomment-2308527094:

I didn't read the Openbox spec when adding the omnipresent button. It seems what I call the "Omnipresent" mouse context is called "AllDesktops" in Openbox.

If we care about keeping this compatible with Openbox, I'd propose one of two things:

1. Moving the context name to "AllDesktops" and changing the theme variable to "desk" to agree with the image names, or
2. Accepting "AllDesktops" and "Omnipresent" as synonyms for the mouse context, and then accepting both "desk" and "omnipresent" as synonyms in the theme file. If both exist, the "omnipresent" variant would take precedence because it would be specific to labwc.

I think I favor the second option because "Omnipresent" seems a nicer description than "AllDesktops", but I could go either way.

Let's decide whether to act and, if so, which path to take, and I'll PR the favored fix.

**Comment by Consolatis** [comment]
Personally I'd favor variant 1. Supporting both for the icon would mean 4 more icons (`(normal, toggled) * (no_hover, hover)`) and also complicate the logic when either loading the icons or selecting them. Regarding the mouse context I don't really mind either way; IMHO we should support whatever Openbox calls the context but may additionally also support `Omnipresent` but I don't feel strongly about it.

**Comment by 01micko** [comment]
With png/svg icons it's 8 more re #2114

**Comment by Consolatis** [comment]
Implemented via
- #2115
