### ISSUE TITLE
document new ssd buttons

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#2113]
A description in `labwc-theme.5` is needed for the new 'desk' and 'shade' buttons; `xbm`, `png` and `svg`

**Comment by stefonarch** [comment]
I see.

```
Note: Button elements (i.e. window.[in]active.button.\*) may be defined uniquely
for each type of button ("menu", "iconify", "max", "shade", "desk" or "close")
by appending the type after the "button" node. For example:
```
but `window.inactive.button.desk.unpressed.image.color: #939597` still doesn't work while `omnipresent` does.

**Comment by 01micko** [comment]
@stefonarch weird, seems to work here but I edited my theme directly

```conf
window.inactive.button.desk.unpressed.image.color: #ff0000
window.inactive.button.shade.unpressed.image.color: #00ff00
window.inactive.button.menu.unpressed.image.color: #0000ff
```

![btnwin](https://github.com/user-attachments/assets/5fd2de0e-70e1-4ec4-bf07-92943105bf77)

**Comment by stefonarch** [comment]
Never mind, issue is in front of the screen: I updated labwc and reloaded my config, but forgot to restart my session ... all fine.

**Comment by 01micko** [comment]
oh PEBKAC :smile:  (Problem Exists Between Keyboard and Chair)

**Comment by 01micko** [comment]
I get that A LOT
