### ISSUE TITLE
seatd-launch

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#212]
Let's follow this
https://github.com/swaywm/sway/commit/e1db1f8218998c428e8b087dda6660449ef2891a

**Comment by ARDiDo** [comment]
I never knew that was why Arch switched from libseat to seatd. Neat.

Should we leave this issue open until sway officially deprecates libseat?

**Comment by johanmalm** [comment]
Yes, I think just staying close to sway’s approach is sensible for this sort of stuff (i.e. just produce a warning for the minute).

I’ll have some time on a computer soon. Just thought I’d track a few TODO things here
