### ISSUE TITLE
[Feature request] Allow pressing ESC to leave magnifier

### ISSUE THREAD

**Issue by manfred3000** [labwc/labwc#2121]
At least for me it'd feel more intuitive to leave the magnifier on pressing `ESC` instead of having to toggle it with a keybinding - if I want to magnify the screen I just press e.g. `W-+`, and then simply leave on `ESC`...

BTW, thanks everyone for all your work on this awesome WM (I appreciate pretty much every new feature that had been added in recent releases)!

**Comment by ahesford** [comment]
This isn't possible, because the magnifier doesn't receive focus. If you want an ephemeral magnifier that can be easily dismissed, take a look at something like [hyprmag](https://github.com/SIMULATAN/hyprmag) or the [hyprpicker](https://github.com/hyprwm/hyprpicker) color picker.

**Comment by manfred3000** [comment]
I was afraid that it wasn't possible - thanks for your confirmation.
