### ISSUE TITLE
[Request] Add support for ~/Desktop icons

### ISSUE THREAD

**Issue by xplshn** [labwc/labwc#2123]

**Comment by orfeasxyz** [comment]
The compositor does support desktop icons through the layer shell protocol. You can use something like [pcmanfm-qt](https://github.com/lxqt/pcmanfm-qt) with `pcmanfm-qt --desktop`. One problem I've had with it however is that it didn't work properly with two outputs (icons only appeared on my second monitor).

**Comment by orfeasxyz** [comment]
> > The compositor does support desktop icons through the layer shell protocol. You can use something like [pcmanfm-qt](https://github.com/lxqt/pcmanfm-qt) with `pcmanfm-qt --desktop`. One problem I've had with it however is that it didn't work properly with two outputs (icons only appeared on my second monitor).
> 
> Oh, so the issues I experienced with sway when using `pcmanfmqt --desktop` weren't the fault of pcmanfmqt but rather Sway's?

I am not really familiar with sway but I would assume that it does support it. What was your issue exactly? Also make sure you're running a recent version of pcmanfm-qt that supports Wayland (reference: https://github.com/lxqt/pcmanfm-qt/releases)

**Comment by xplshn** [comment]
> > > The compositor does support desktop icons through the layer shell protocol. You can use something like [pcmanfm-qt](https://github.com/lxqt/pcmanfm-qt) with `pcmanfm-qt --desktop`. One problem I've had with it however is that it didn't work properly with two outputs (icons only appeared on my second monitor).
> > 
> > 
> > Oh, so the issues I experienced with sway when using `pcmanfmqt --desktop` weren't the fault of pcmanfmqt but rather Sway's?
> 
> I am not really familiar with sway but I would assume that it does support it. What was your issue exactly? Also make sure you're running a recent version of pcmanfm-qt that supports Wayland (reference: https://github.com/lxqt/pcmanfm-qt/releases)

The issue was that pcmanfmqt did not display anything with `--desktop`. But I shall test again and see what happens when using the more recent versions in the Alpine edge repos.
