### ISSUE TITLE
xdg_toplevel_set_fullscreen only sends config after a buffer is bound

### ISSUE THREAD

**Issue by jc-kynesim** [labwc/labwc#2135]
It seems to be the case that if I try to set fullscreen with xdg_toplevel_set_fullscreen then the expected configure callbacks only occur once a buffer has been added to the surface and committed - simply committing the surface without a buffer isn't sufficient. This is annoying as I want to size the buffer based on the size of the fullscreen but I'm not allowed to know that till after I've already attached and committed a buffer. Running the same code under Wayfire gives me config callbacks when I expect them i.e. in the roundtrip after I've committed the surface but before I've attached a buffer to that surface.

Is this expected behaviour? If so is there an approved way of getting the "correct" size for the buffer to attach to the surface before doing so for the 1st time? I can use wl_output to get some values but that feels wrong.

**Comment by johanmalm** [comment]
I can't remember without going digging in the code.
@jlindgren90 - can you remember off the top of your head?

**Comment by jlindgren90** [comment]
OP didn't say what version of labwc, but this sounds the same issue that should have been fixed by #2007.

**Comment by johanmalm** [comment]
> OP didn't say what version of labwc, but this sounds like the same issue that should have been fixed by #2007.

Thanks. Yeah, I remember you worked on it :smile:

**Comment by jc-kynesim** [comment]
labwc 0.7.2 (current version on Raspberry Pi). Given the date on #2007 I'm guessing it predates that. Many thanks - I'll wait for the version that has the fix to roll around.

**Comment by jc-kynesim** [comment]
I can confirm that this is fixed in 0.8.0
