### ISSUE TITLE
When the width of the window is less than the length of the title, there will be a noticeable shrinkage process

### ISSUE THREAD

**Issue by knm100** [labwc/labwc#2142]
Please See the video 

https://github.com/user-attachments/assets/51a08691-2133-46f0-8eef-69d601a38207

**Comment by tokyo4j** [comment]
What application are you running? Also, debugging log with `WAYLAND_DEBUG=client` will be helpful.

**Comment by knm100** [comment]
the application is nm-tray,  please see the debug message with WAYLAND_DEBUG=client
[1.txt](https://github.com/user-attachments/files/17002072/1.txt)

**Comment by knm100** [comment]
fixed so fast,  thank you! @tokyo4j
