### ISSUE TITLE
menu contrast 

### ISSUE THREAD

**Issue by davidphilipbarr** [labwc/labwc#2148]
The menus can visually blend in with certain applications as there is no contrast to separate them, such as a border (or a shadow!). 
Obviously this can be over come by setting a different colour for the menu bg, this might create some visual inconsistencies with other desktop apps. 

i guess this lays somewhere between a feature request and a usability issue, probably mostly the former :)

screen shot for example.
![lab_menu](https://github.com/user-attachments/assets/0ef0ac05-0563-4b82-ba6d-2e55be9e86bd)

**Comment by tokyo4j** [comment]
Yeah, I agree we should support a border for menus. I haven't realized the UX degradation by the lack of border because I always use dark theme, but in your screenshot, it's indeed a problem.

**Comment by jp7677** [comment]
GTK also applies shadows to menus, may be that would also (additionally/alternatively) fit here.

**Comment by johanmalm** [comment]
Openbox theme specification include `menu.border.width` and `menu.border.color`. We just haven't implemented them yet.

**Comment by droc12345** [comment]
I like to set my menu background with slightly off white color, with a hint of transparency

menu.items.bg.color: #f5f2efdd

**Comment by tokyo4j** [comment]
Implemented by #2376.
