### ISSUE TITLE
"go there..." and I noticed an empty space

### ISSUE THREAD

**Issue by droc12345** [labwc/labwc#2159]
Hm, didn't quite understand what happens with "go there..." and I noticed an empty space, maybe not the right place to discuss this.
![immagine](https://github.com/user-attachments/assets/a1d0a0ad-db80-4069-82c6-eb6694732746)

_Originally posted by @stefonarch in https://github.com/labwc/labwc/issues/2158#issuecomment-2360938506_

**Comment by droc12345** [comment]
I don't run lxqt, so I've never seen that.

It looks like there are 2 views, that don't have titles.
if you move down from LXQT Appearance Config* does it highlight?

**Comment by stefonarch** [comment]
Just happened again, so my edit wasn't the reason. I can highlight the empty spaces  and it will finish at the top of the list. With some fiddling it looks like VLC is the reason, also if minimized to tray. Opened a bunch of other apps, all fine. No idea why, it doesn't show unusual things with `lswt`.

**Comment by droc12345** [comment]
I don't have vlc installed, but I may install just to see what's going on.

**Comment by droc12345** [comment]
Is vlc running under Xwayland?

**Comment by droc12345** [comment]
I guess the easy way is to filter out titles if null. I'm assuming it's null and not just spaces.
I can't install vlc as it wants me to install the whole X world.

@johanmalm would this work?

```
 		wl_list_for_each(view, &server->views, link) {
 			if (view->workspace == workspace) {
+				char *Title = view_get_string_prop(view, "title");
+				if (string_null_or_empty(line)) {
+					continue;
+				}
+
 				if (view == server->active_view) {
 					buf_add(&buffer, "*");
 				}
-				buf_add(&buffer, view_get_string_prop(view, "title"));
+				buf_add(&buffer, Title);
 
 				current_item = item_create(menu, buffer.data, /*show arrow*/ false);
 				current_item->id = xstrdup(menu->id);
```

**Comment by stefonarch** [comment]
Just checked, in fact it's an xwayland issue, I checked with element and it's identical. It was just by chance that there was VLC in the quicklaunch of my testuser. `QT_QPA_PLATFORM=xcb lxqt-config-input ` produces the same.

**Comment by droc12345** [comment]
When labwc goes to update foreign title, we check -- if (!view->toplevel.handle || !title) and then bail
which is why lswt and others don't show an empty title.

I think we want to do the same thing, but I'll wait for johan to say something.

**Comment by stefonarch** [comment]
Btw I still fail to check what "Go there..." is for. I can go to workspaces and apps directly and if I select it nothing happens and it goes to my active app.

**Comment by droc12345** [comment]
It's just a visual shortcut to GoToDesktop, 

Lets say you have all the windows minimized on a workspace, but don't want to click (and unminimize) a window
then use, Go there, to go to that workspace.

**Comment by stefonarch** [comment]
I saw that. But I can simply click the header for the workspace.

**Comment by droc12345** [comment]
The header (workspace name) isn't clickable, it's a separator element. 
Something else has focus and that's what get selected.

**Comment by stefonarch** [comment]
O, didn't notice it, right.

**Comment by droc12345** [comment]
Can  you try this patch to see if it fixes the empty lines, I don't have xwayland.
https://patch-diff.githubusercontent.com/raw/labwc/labwc/pull/2161.patch

**Comment by stefonarch** [comment]
It looks fixed now, yes, tested both with element and vlc.

**Comment by droc12345** [comment]
Sweet, thanks for testing.
