### ISSUE TITLE
New padding introduced into theme

### ISSUE THREAD

**Issue by winteriscariot** [labwc/labwc#2160]
So this morning while I was updating labwc to latest git and playing with new theme options (such as circle highlight for caption buttons, and client menu) when I noticed that things changed slightly.

I don't have a before image, but here's the current situation:

![image](https://github.com/user-attachments/assets/8eee5c15-dc08-4e6c-ba42-22f5ab276ba4)

There's a few pixels to the right of the highlighted caption button that didn't exist before: the highlight went all the way to the edge of the titlebar.

If this was an intended change then no big deal, it just felt a little cleaner when the highlight would go all the way to the edge.

**Comment by winteriscariot** [comment]
![image](https://github.com/user-attachments/assets/1e7b681b-7b7c-4482-acbe-26713a71fafe)
better screenshot with more contrast. it's not the border that's causing it, there's space between the highlight and the border. you can see how on the top edge the highlight goes all the way to the border.

**Comment by jp7677** [comment]
This is indeed wanted behavior. The padding pushes the buttons more to inner area. Making the hover effect also cover the padding area is technically not so easy and, more important, the button underneath would no longer be centered within the hover effect. 

I recommend to either use the circle hover with padding, or the rectangle hover effect without padding.

**Comment by winteriscariot** [comment]
Thank you!
