### ISSUE TITLE
Missing Border in Maximized Windows (Shaded Mode)

### ISSUE THREAD

**Issue by AnirvanB** [labwc/labwc#2217]
### Description

There seems to be an issue with window borders in unmaximized versus maximized windows when in shaded mode.

Unmaximized window (shaded mode): The window displays the borders as expected (assuming borders are defined).

Maximized window (shaded mode): The borders go missing.

### Expected Behavior 

The borders should remain visible when the window is maximized, just like it does in the unmaximized state. I hope/ expect that the border rendering remains consistent across both maximized and non-maximized window states in shaded mode.

### Screenshots

1. Unmaximized window (shaded mode):
![a.png](https://github.com/user-attachments/assets/d319b563-fc58-44ea-9544-a1506a47f78d)

2. Maximized window (shaded mode):
![b.png](https://github.com/user-attachments/assets/3d382500-79f7-40d7-b325-5a4d24c24be7)

### Environment

labwc version: 0.8.0

Operating System: Void Linux

### Additional Notes

This issue can be replicated consistently across different applications. I’ve tested this on multiple themes, and the problem persists regardless of the theme in use.

---

Thank you for all the hard work and continuous improvements on labwc! It’s a fantastic compositor, and this issue aside, everything has been running smoothly. I look forward to any insights or fixes you might have for this border rendering problem.

**Comment by johanmalm** [comment]
If we take the 'shaded' state to one side, we hide the border on purpose when windows are maximized - just like we square the corners of the titlebar.

Isn't it reasonable and probably of least surprise to the users if the shaded state follows this convention.

Tbh I'd never really thought about it, but having played with it now the as-is seems intuitive.

**Comment by AnirvanB** [comment]
Maybe it's just me, but I feel like something looks off, and I might be overthinking it. If you think it's not a problem, feel free to close the issue.

**Comment by tokyo4j** [comment]
I agree with @johanmalm.

When you make a window in maximized-and-shaded state, I guess you maximize it first and make it shaded. So, if we take your suggestion and make the border shown also in maximized-and-shaded windows, it means the borders are hidden on maximization and shown again when the window is shaded. I don't think this transition of border visibility is intuitive.

**Comment by AnirvanB** [comment]
Thank you both, @johanmalm and @tokyo4j, for reviewing this and sharing your thoughts.

> I guess you maximize it first and make it shaded.

That is correct!

My perspective is that shaded windows are a special case where borders appear in normal, snapped and in full-screen mode. However, while this holds true for the first two cases, it doesn't for the third. I also see potential cases where borders could work well in full-screen , such as when using a bar with margin (like in the image below). 

![d.png](https://github.com/user-attachments/assets/dbc203d2-f310-41f8-9fb3-8c8c28ab02ca)

While, I understand that such border transition might not be intuitive for the general user base. I feel it could benefit those who pay close attention to details, like ricers. Perhaps this could be implemented as an optional, non-default setting. Just me doing some wishful thinking! 😅
