### ISSUE TITLE
After opening a menu from `show_window_menu` request, DnD stops working

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#2220]
After I opened a menu from `xdg_toplevel::show_window_menu` request, drag-and-drop stops working, emitting an error message:

```
00:00:06.990 [../src/dnd.c:24] wrong source for drag request
```

https://github.com/user-attachments/assets/02eaf1a7-6d15-42b0-bbac-d41a8e8dcb30

**Comment by tokyo4j** [comment]
Here's what happened:

1. Labwc calls `wlr_seat_pointer_notify_button()` on button press
2. Gedit sends `xdg_toplevel::show_window_menu` request
3. Labwc opens client-menu
4. Labwc handles button release, but doesn't call `wlr_seat_pointer_notify_button()` since `server->input_mode == LAB_INPUT_STATE_MENU`. Thus wlroots thinks the button is still pressed.
5. Labwc executes the action, closes the menu, and switches to another window (e.g. firefox window in the demo).
6. Labwc calls `wlr_seat_pointer_notify_button()` on button press. This means `wlr_seat_pointer_notify_button()` is consecutively called twice for button presses. This sets `wlr_seat->pointer_state.button_count` to `2`.
7. The window initiates DnD, but `wlr_seat_validate_pointer_grab_serial()` fails since `wlr_seat->pointer_state.button_count` must be `1`.

So this bug is not limited to menus opened with `xdg_toplevel::show_window_menu` requests. I could reproduce the same problem with the following mousebind:

```xml
<context name="Frame">
      <mousebind button="C-Right" action="Release">
        <action name="ShowMenu" menu="client-menu" />
      </mousebind>
    </context>
```

Perhaps the same problem happens with `Move`/`Resize` actions.

**Comment by johanmalm** [comment]
This feels similar to managing key events that are "absorbed" by keybinds.

https://github.com/labwc/labwc/blob/a5d89a2e4c610b5ed51011a49815d8466ac46643/src/input/keyboard.c#L312
https://github.com/labwc/labwc/blob/master/src/input/key-state.c
