### ISSUE TITLE
Tearing preference is fully denied as result of tearing page-flip commit failures

### ISSUE THREAD

**Issue by RicArch97** [labwc/labwc#2229]
Since kernel 6.11.1, tearing (async pageflips) now work with the DRM atomic interface, without having to launch with the `WLR_DRM_NO_ATOMIC=1` variable. However it does not currently work as expected in LabWC.

Here's the scenario: i was playing a game, initially tearing was working fine. After some time it no longer did. Checking the logs there seemed to be commit failures where tearing was requested. In MR https://github.com/labwc/labwc/pull/1996 a change was made to fully disable the tearing functionality after a certain amount of failures has happened, though I'm not convinced that this is the right approach.

With the Sway tearing implementation, we also take possible failures into account: https://github.com/swaywm/sway/blob/master/sway/desktop/output.c#L291 If the output state cannot be committed when requesting tearing, then we simply commit the frame without tearing. Commits where tearing is requested could basically fail indefinitely without having impact on usability. I tested the same game in Sway master with tearing enabled and there were no issues (tearing not getting disabled, nor any frame related issues).

I don't think we should just full disable the user defined preference for tearing if commits with tearing page flip enable fail an X amount of times, but rather just handle the failures in a better way. What does everyone think?

**Comment by johanmalm** [comment]
Sounds sensible, but have to admit that this is not an area where I've been following the "thinking" too much.
@kode54 @ahesford 
Any views on this?

**Comment by ahesford** [comment]
I don't have any particular insight or preference here. If the output test as done by sway really caries no appreciable cost, checking indefinitely seems fine.

**Comment by johanmalm** [comment]
> I don't have any particular insight or preference here. If the output test as done by sway really caries no appreciable cost, checking indefinitely seems fine.

Yeah.

@RicArch97 Would you have the means, ability (and interest) to draft a patch for discussion with @kode54 ?

**Comment by RicArch97** [comment]
Actually i was wrong about us fully negating the tearing preference if it fails for X times, but then it is finally committed without tearing page-flip.  One difference i see is that in Sway, the output is state is **tested** first (without committing it yet) with tearing enabled, and then actually **committed** with tearing if the test is positive, or else committed without tearing. 

It seems that in LabWC, we currently always commit first, and then check if it failed. We currently try an X amount of times with tearing first, before committing again without tearing. Maybe @kode54 can shed some light on why that is necessary. To me it seems that a few frames without tearing in-between would not be noticeable, instead of re-trying the same tearing page flip for let's say 120 times before finally taking action. Wouldn't that cause a lot of frames to be dropped if it keeps failing?

**Comment by RicArch97** [comment]
> > I don't have any particular insight or preference here. If the output test as done by sway really caries no appreciable cost, checking indefinitely seems fine.
> 
> Yeah.
> 
> @RicArch97 Would you have the means, ability (and interest) to draft a patch for discussion with @kode54 ?

Sure, I can run some tests and propose a change, if applicable

**Comment by ahesford** [comment]
We don't try several times with tearing before permanently disabling tearing. We try each frame exactly once with tearing allowed and, if that fails, commit it without the tearing allowance. In the meantime, we count the number of successive frames that were committed without the tearing allowance and, if that exceeds the permitted number of failures, permanently disable it.

**Comment by RicArch97** [comment]
I've played around with both LabWC and Sway tearing, and noticed the following:

### Tearing page flip not possible when cursor image is moving

Currently, it seems that whenever the cursor is moved when tearing is active, the commits always fail. This is the same for Sway and LabWC. Moving the cursor can easily generate a hundred failure logs. This was initially found and tested using vkcube, by running: `vkcube -- present_mode 0`.

LabWC logs:
```
00:01:07.005 [ERROR] [../src/output-state.c:45] Failed to commit frame
00:01:07.005 [INFO] [../src/common/scene-helpers.c:117] Failed to commit output DP-1
00:01:07.011 [ERROR] [backend/drm/atomic.c:79] connector DP-1: Atomic commit failed: Invalid argument
00:01:07.011 [DEBUG] [backend/drm/atomic.c:84] (Atomic commit flags: PAGE_FLIP_EVENT | PAGE_FLIP_ASYNC | ATOMIC_NONBLOCK)
``` 

Sway logs:
```
00:01:13.092 [DEBUG] [wlr] [backend/drm/atomic.c:79] connector DP-1: Atomic commit failed: Invalid argument
00:01:13.092 [DEBUG] [wlr] [backend/drm/atomic.c:84] (Atomic commit flags: PAGE_FLIP_ASYNC | ATOMIC_TEST_ONLY)
00:01:13.092 [DEBUG] [sway/desktop/output.c:310] Output test failed on 'DP-1', retrying without tearing page-flip
```

A point of notice:

It seems that LabWC currently just tries to do the commit with tearing, and checks for failures afterwards, which might be more expensive, based on the timestamps in the logs. There is some time between the fail log from LabWC and the drm atomic backend. 

Sway currently uses `wlr_output_test_state` to determine whether **just tearing** can be applied, and there is no additional time between the log from Sway and the log from the drm atomic backend.

You can see that by atomic commit flags provided to the atomic DRM backend:

- LabWC: (PAGE_FLIP_EVENT | PAGE_FLIP_ASYNC | ATOMIC_NONBLOCK) -> doing the actual commit
- Sway: (PAGE_FLIP_ASYNC | ATOMIC_TEST_ONLY) -> just testing for tearing

### Tearing testing in game (Overwatch 2)

When in the game menu's, moving the cursor also caused the tearing commits to fail (for both LabWC and Sway) just like in vkcube. This, as result of consecutive failures, caused LabWC to permanently disable the tearing.
```
00:01:58.249 [INFO] [../src/output.c:166] setting tearing allowance failed for two consecutive seconds, disabling
```

For Sway, the tearing never gets permanently disabled, so it just keeps testing to see if tearing is possible, then falling back to regular page-flip without tearing when the cursor is moved.

When actually in a game, where the cursor is now bound to moving the weapon, and no cursor image is visible, the tearing commit no longer fail, and tearing is observed as expected. This is also the case on both LabWC and Sway. Though in my tested, the tearing was already disabled with LabWC at this point.

### Possible solution

We could handle the pending output state change the same way as we handle the gamma lut, in `ouput_apply_gamma`. This means creating and initializing a new pending output state, applying the tearing allowance, and then test the state. Something like:
```c
struct wlr_output_state pending;
wlr_output_state_init(&pending);

if (output_get_tearing_allowance(output)) {
  pending.tearing_page_flip = true;

  if (!wlr_output_test_state(output->wlr_output, &pending)) {
    wlr_log(WLR_DEBUG, "Output state with tearing failed, committing without tearing");
    pending.tearing_page_flip = false; 
  }
}

// do the commit...
lab_wlr_scene_output_commit(output->scene_output, &pending);

wlr_output_state_finish(&pending);
```

This could cause the tearing to fail as many times as possible (note: fail log is debug) without it getting permanently disabled. The output test for tearing doesn't seem to be that expensive, for it to cause latency concerns.

What are your thoughts?

**Comment by ahesford** [comment]
I think the proposal from @RicArch97 seems reasonable.

**Comment by RicArch97** [comment]
> Regarding your observation of mouse cursor movement making the tearing commits fail, that is a kernel limitation.

I way i looked at it was that the cursor image isn't supposed to tear, so if the cursor image needs to be updated, a frame with `PAGE_FLIP_ASYNC` set will be rejected. Anyways, I'm just setting foot in the whole Wayland / compositing space, so I'm mostly going off assumptions and quick scans through the codebase, i have a lot to catch up on 🙂 

> In terms of performance I am not sure, we'd add a test commit for every frame which we currently don't do. On the flip side its only if the user enabled tearing so that would be fine by me.

The tearing does work fine when actually in a game, where the cursor image usually is not present, which is probably 90% of the cases where tearing is used. Maybe we could just do the test commit for the time being, until improvements are made at kernel side? Then we don't have to force usage of the legacy DRM API, for the few cases where tearing is requested

**Comment by kode54** [comment]
If this patch is accepted eventually, you won't have as much to worry about cursor movements causing tearing failures:

https://lore.kernel.org/all/20241002-tonyk-async_flip-v9-0-453b1b8977bd@igalia.com/
