### ISSUE TITLE
AlwaysOnTop makes a window visible on all workspaces

### ISSUE THREAD

**Issue by whitespace-rebel** [labwc/labwc#2237]
Hello everyone,

AlwaysOnTop makes a window visible on all workspaces (Omnipresent). This is not how I remember it from Openbox.
IMHO AlwaysOnTop and Omnipresent are two different concepts and should be activated/deactivated/toggled separately.

**Comment by stefonarch** [comment]
Already on the todo list: https://github.com/labwc/labwc/issues/1151

**Comment by whitespace-rebel** [comment]
> Already on the todo list: #1151

Okay, this can be closed then.
