### ISSUE TITLE
Icon loader initialization fail

### ISSUE THREAD

**Issue by kabishchev** [labwc/labwc#2247]
**Steps to reproduce:**

1. Install Papirus icon theme, which inherits missing icons from Breeze icon theme:

```
/usr/share/icons/Papirus-Dark/index.theme

[Icon Theme]
Name=Papirus-Dark
Inherits=breeze-dark,hicolor
```

2. Make sure you don't have Breeze icons installed on your system

3. Set Papirus or Papirus-Dark as you icon theme in rc.xml

4. Launch labwc, you should see no app icon in your titlebar

```
00:00:00.052 [ERROR] [sfdo-icon] Couldn't find an icon theme file for breeze
00:00:00.052 [ERROR] [../labwc/src/icon-loader.c:94] Failed to initialize icon loader
```

**Expected behaviour:**
Load Papirus icon theme no matter if Breeze icons are installed or not

Distro: Arch Linux, latest versions of labwc-git and libsfdo (compiled from AUR)

**Comment by vyivel** [comment]
Assuming "[m]ake sure you don't have Breeze icons installed on your system" is not a deliberate setup, this is a packaging error; all dependencies of a theme are expected to be present, see https://gitlab.freedesktop.org/xdg/default-icon-theme/-/issues/21 and https://gitlab.freedesktop.org/xdg/default-icon-theme/-/commit/cfaec5f37300746951674dc86429ca9f892ca542.

As a workaround, labwc could add a new option to supply `SFDO_ICON_THEME_LOAD_OPTION_ALLOW_MISSING` to the loader (https://gitlab.freedesktop.org/vyivel/libsfdo/-/blob/661c7a0af09e6224aa675853be908d3f09f5a501/include/sfdo-icon.h#L47).

**Comment by kabishchev** [comment]
Thanks for the clarification, I didn't know this. So, it's not really a bug then.

Anyway, in Arch `papirus-icon-theme` package doesn't require `breeze-icons` even as a weak dependency. I assume it may be relevant for many other distros as well, so it would be nice to have some kind of workaround here.

**Comment by johanmalm** [comment]
@kabishchev - any chance of trying with #2248 ?

**Comment by kabishchev** [comment]
> @kabishchev - any chance of trying with #2248 ?

Just recompiled labwc-git with your PR, everything seems to be OK.

No icon-loader initialization errors and all Papirus icons are showing in titlebars even with no Breeze icons installed

![screenshot](https://github.com/user-attachments/assets/bcae6673-ee46-4975-b339-d4536c516ca2)
