### ISSUE TITLE
Qutebrowser crashes on touchpad scroll

### ISSUE THREAD

**Issue by ahmadraniri1994** [labwc/labwc#225]
I'm getting  a weird behaviour when I'm opening qutebrowser on LABWC, it opens ordinarily for about 2 minutes and start hang and crash / force closed. I never get this behaviour on other wayland compositors (sway, hikari). I have no clue if it's related to LABWC specifically. Thanks.
OS : Archlinux
Labwc : Latest master (two recent update still same).

**Comment by johanmalm** [comment]
I don't normally use `qutebrowser`, but have just installed/ran it for a while. Seems to work fine here, so I'm unable to reproduce and fault find. I'm on Arch also.

It is just `qutebrowser` that hangs or the whole `labwc` compositor?

If you run `qutebrowser` from the terminal, do you get any error messages when it hangs?
If not, could you try running it with debug log-level (`qutebrowser -l debug`)

**Comment by ahmadraniri1994** [comment]
Well, I'll check it later.

**Comment by ahmadraniri1994** [comment]
I'm sorry for late reply, turns out it's happening on my debian setup too.
Qutebrowser log : https://pastebin.com/Fa3kkwzV

**Comment by ahmadraniri1994** [comment]
For some reason I reinstall my archlinux, I did reinstall labwc too (labwc-git from aur), but the issue still exixt. Dunno why.

**Comment by ahmadraniri1994** [comment]
These are some stuffs I got when I run qutebrowser from commandline : 
> [ahmad@LIDGNULINUX ~]$ qutebrowser 
> 07:35:59 INFO: Run :adblock-update to get adblock lists.
> 07:36:00 WARNING: Wayland does not support QWindow::requestActivate()
> Segmentation fault (core dumped)

**Comment by ahmadraniri1994** [comment]
Turns out every qt apps crash on labwc, soon after the apps are opened, the apps will crash. Will investigate it further.

**Comment by ahmadraniri1994** [comment]
Set QT_QPA_PLATFORM=xcb seems fix the issue, but it means every QT apps use xwayland now.

**Comment by ahmadraniri1994** [comment]
I give up, hope the next release will fix the issue (oops still exist when I compile the last master).

**Comment by Consolatis** [comment]
> These are some stuffs I got when I run qutebrowser from commandline :
> 
> > [ahmad@LIDGNULINUX ~]$ qutebrowser
> > 07:35:59 INFO: Run :adblock-update to get adblock lists.
> > 07:36:00 WARNING: Wayland does not support QWindow::requestActivate()
> > Segmentation fault (core dumped)

Maybe we could get some more information from the backtrace.
For that you'd start it like `gdb qutebrowser`, then press `r` and once it crashes type `bt`. 
By typing `q` you get out of the gdb shell.

**Comment by ahmadraniri1994** [comment]
Qutebrowser isn't binary executable apparently , it's a Python script type, is it still can be debugged  with GDB?

**Comment by ahmadraniri1994** [comment]
Qutebrowser output from `qutebrowser -l debug` : 
[qb2.log](https://github.com/labwc/labwc/files/8021040/qb2.log)

**Comment by Consolatis** [comment]
> Qutebrowser isn't binary executable apparently , it's a Python script type, is it still can be debugged with GDB?

https://www.qutebrowser.org/doc/stacktrace.html#_getting_the_stack_trace

I tested qutebrowser a bit on a nested labwc session (started as wayland native with `QT_QPA_PLATFORM=wayland qutebrowser`) and didn't enounter a segfault yet.

**Comment by ahmadraniri1994** [comment]
Sorry for being late, I follow your advice, here the gdb.txt file : 
[gdb.txt](https://github.com/labwc/labwc/files/8030883/gdb.txt)

**Comment by Consolatis** [comment]
Last calls in that stacktrace are `flushScrollEvent()` and `handleMouse()`. So I assume this bug has something to do with mouse scrolling. Are you running Qutebrowser in maximized state or have multiple monitors? It might be related to mouse scrolling in Quitebrowser while another application currently has the mouse focus. I am not sure this bug (I still can't reproduce it) really is in labwc thogh. You said its happening in other QT applications as well, do those only crash on mouse scroll events as well?

**Comment by ahmadraniri1994** [comment]
@Consolatis I don't use mouse but touchpad, and it's true if I use touchpad (to scroll) then qutebrowser will crash. I test it right now without using touchpad and surprisingly works fine. Other qt apps are random, I mean like pcmanfm-qt works fine but qt5ct not.

**Comment by ahmadraniri1994** [comment]
Update : mouse seems to work fine (scrolling mostly ).

**Comment by Consolatis** [comment]
That would explain why I couldn't reproduce the bug :)
I have an old netbook around, will test once I get it functional again. I can't promise any timeframe though.

**Comment by ahmadraniri1994** [comment]
@Consolatis yeah, thanks.

**Comment by Consolatis** [comment]
I can indeed reproduce the issue with qutebrowser and two finger touchpad scrolling.
Didn't yet have the time for further investigation but at least I now have a starting point :)
