### ISSUE TITLE
Labwc crashes every time I attempt to open an X11 application

### ISSUE THREAD

**Issue by amoli79** [labwc/labwc#2254]
Hi to all,

for the past few days, I’ve been experiencing an issue: every time I try to open an X11 application (such as iwgtk or gsimplecal), Labwc crashes. However, Hyprland is working fine, so it doesn’t seem to be a Wayland problem.

Here’s the end of the error log, I found it by typing labwc -d > labwc10.log 2>&1. If I do not redirect the output the log is empty (I'm attaching the full log for reference, [labwc10.log](https://github.com/user-attachments/files/17451258/labwc10.log)):

labwc: ../libsfdo-v0.1.3/sfdo-desktop/entry.c:138: sfdo_desktop_entry_get_startup_wm_class: Assertion `entry->type == SFDO_DESKTOP_ENTRY_APPLICATION' failed.
Io error: Connection reset by peer (os error 104)
Io error: Connection reset by peer (os error 104)
Io error: Connection reset by peer (os error 104)
Error: ExitFailure(1)

Does anyone have any ideas on how to fix this?

Regards,

Vassari

**Comment by Consolatis** [comment]
Thanks for the report.
Can you give #2256 a try?

**Comment by amoli79** [comment]
Hi.

Yeah, sure. In a couple of hours will do.

Thank you!

**Comment by amoli79** [comment]
Hi,

everything is working fine now, but I have one question:

The first time I left my Openbox session open and launched Labwc from another TTY, I noticed that iwgtk opened inside Openbox instead of Labwc, even though I was calling it from Labwc. However, gsimplecal opened in Labwc as expected.

After that, I changed how SDDM calls Labwc to use the latest build you provided. When I entered Labwc from SDDM (after closing Openbox), iwgtk opened correctly within Labwc.

Is this behavior normal?

In any case, I consider the problem solved. Thank you!

**Comment by Consolatis** [comment]
Thanks for testing.

> The first time I left my Openbox session open and launched Labwc from another TTY, I noticed that iwgtk opened inside Openbox instead of Labwc, even though I was calling it from Labwc. However, gsimplecal opened in Labwc as expected.

Some X11 applications may just open on the first X11 server found and ignore the `DISPLAY` environment variable. That would be a client bug.
