### ISSUE TITLE
Setting video mode with wlr-randr doesn't work correctly with Labwc 

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#2278]
Hi there,

wlr-randr reports many video modes available for my display:

```
~$ wlr-randr 
HDMI-A-1 "ViewSonic Corporation XG2401 SERIES UG2184100356 (HDMI-A-1)"
  Make: ViewSonic Corporation
  Model: XG2401 SERIES
  Serial: UG2184100356
  Physical size: 530x300 mm
  Enabled: yes
  Modes:
    1920x1080 px, 60.000000 Hz (preferred, current)
    1920x1080 px, 143.766006 Hz
    1920x1080 px, 120.000000 Hz
    1920x1080 px, 119.879997 Hz
    1920x1080 px, 100.000000 Hz
    1920x1080 px, 60.000000 Hz
    1920x1080 px, 59.939999 Hz
    1920x1080 px, 50.000000 Hz
    1920x1080 px, 30.000000 Hz
    1920x1080 px, 29.969999 Hz
    1920x1080 px, 25.000000 Hz
    1600x1200 px, 60.000000 Hz
    1680x1050 px, 59.882999 Hz
    1400x1050 px, 59.948002 Hz
    1280x1024 px, 75.025002 Hz
    1280x1024 px, 60.020000 Hz
    1440x900 px, 59.901001 Hz
    1280x960 px, 60.000000 Hz
    1152x864 px, 75.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 60.000000 Hz
    1280x720 px, 59.939999 Hz
    1280x720 px, 50.000000 Hz
    1024x768 px, 75.028999 Hz
    1024x768 px, 70.069000 Hz
    1024x768 px, 60.004002 Hz
    832x624 px, 74.551003 Hz
    800x600 px, 75.000000 Hz
    800x600 px, 72.188004 Hz
    800x600 px, 60.317001 Hz
    800x600 px, 56.250000 Hz
    720x576 px, 50.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 60.000000 Hz
    720x480 px, 59.939999 Hz
    720x480 px, 59.939999 Hz
    640x480 px, 75.000000 Hz
    640x480 px, 72.808998 Hz
    640x480 px, 66.667000 Hz
    640x480 px, 60.000000 Hz
    640x480 px, 59.939999 Hz
    640x480 px, 59.939999 Hz
    720x400 px, 70.082001 Hz
  Position: 0,0
  Transform: normal
  Scale: 1.000000
  Adaptive Sync: disabled
```

Now, if I try to set a mode other than preferred, like this:
`wlr-randr --output HDMI-A-1 --custom-mode 1920x1080@120.000000`
or like this:
`wlr-randr --output HDMI-A-1 --custom-mode 1920x1080@120`

....the video mode is set but reverted back immediately to the mode Labwc was running on at launch, even before my monitor can sync to the new mode.

If I do the same via SSH (after exporting **WAYLAND_DISPLAY** env variable, of course) the new mode is kept as expected, but that's of course not the way wlr-randr is intended to be used.

Other WLRoots-based compositor like Sway or Wayfire don't seem to be affected: setting a mode on-the-fly via wlr-randr works correctly on those.

Using latest stable Labwc v0.8.1.

**Comment by vanfanel** [comment]
The problem is using `--custom-mode 1920x1080@120` when the mode is listed.
Using `--mode 1920x1080@120` instead, it works as intended.

Using  `--custom-mode` to set an "stock" supported mode seems to be possible on other WLRoots compositors.

**Comment by Consolatis** [comment]
I am not sure but I think there were changes on the wlroots side for 0.18 regarding that so I'd assume this also won't work anymore for other wlroots 0.18.x based compositors.

**Comment by vanfanel** [comment]
Ok sir! Understood! :)
