### ISSUE TITLE
Change keyboard keys in layout

### ISSUE THREAD

**Issue by Gisi0** [labwc/labwc#2281]
It is possible to change the keyboard layout?
Like switching y with z.

Thank you

**Comment by johanmalm** [comment]
See step 1 of https://labwc.github.io/getting-started.html

Basically, set environment variable `XKB_DEFAULT_LAYOUT` to the desired layout.

I'm not sure about swapping y and z... have feeling some german layouts do that.

**Comment by Gisi0** [comment]
I have an US keyboard, with swapped z y keys.

**Comment by qrp73** [comment]
yes, you can setup keyboard layout for labwc in the following way:

```$ mkdir -p ~/.config/labwc && nano ~/.config/labwc/environment```

add the following lines:
```
XKB_DEFAULT_MODEL=pc105
XKB_DEFAULT_LAYOUT=us,ru
XKB_DEFAULT_OPTIONS=grp:alt_shift_toggle
```

this config setup two layouts: ```us``` and ```ru``` and allows to toggle them with ```Alt```+```Shift``` shortcut

**Comment by ahesford** [comment]
If you want to do arbitrary key rearrangements like swapping `Y` and `Z`, it's probably easiest to just remap scan codes with `udev`.

**Comment by qrp73** [comment]
> If you want to do arbitrary key rearrangements like swapping `Y` and `Z`, it's probably easiest to just remap scan codes with `udev`.

Different keyboard layout may have different place for the same letter. For example:
```us``` layout:
qwertyuiop 
asdfghjkl 
zxcvbnm  

```de``` layout:
qwertzuiop 
asdfghjkl 
yxcvbnm

```fr``` layout:
azertyuiop 
qsdfghjkl 
wxcvbn,

```ru``` layout:
йцукенгшщз 
фывапролд 
ячсмить

As you can see on ```de``` abd ```us``` layout letters Z and Y are swapped. 

Another example, on ```us``` layout you have the symbol " while on ```gb``` layout the same key has symbol @.
This is why it is hard to use default ```gb``` layout, because almost all non ```us``` layouts have symbol " on this key, like on ```us``` layout.

**Comment by Narrat** [comment]
I may miss the point, qrp73, but remapping with `udev` works on the hardware level of the keyboard? If the keyboard is available in the `hwdb`, then scancodes of all keys can be translated to keycodes. Which can be "[rewired](https://wiki.archlinux.org/title/Map_scancodes_to_keycodes)". The actual keyboard layout is then not of much interest?

**Comment by Gisi0** [comment]
The udev way works fine.
But a way like xmodmap would be nice, it could do more.

**Comment by Gisi0** [comment]
Input-remapper works.
Thank you all

**Comment by levpr1c** [comment]
> yes, you can setup keyboard layout for labwc in the following way:
> 
> `$ mkdir -p ~/.config/labwc && nano ~/.config/labwc/environment`
> 
> add the following lines:
> 
> ```
> XKB_DEFAULT_MODEL = pc105
> XKB_DEFAULT_LAYOUT = us,ru
> XKB_DEFAULT_VARIANT =
> XKB_DEFAULT_OPTIONS = grp:alt_shift_toggle
> ```
> 
> this config setup two layouts: `us` and `ru` and allows to toggle them with `Alt`+`Shift` shortcut

sps bratanchik
