### ISSUE TITLE
How to auto startup an app. 

### ISSUE THREAD

**Issue by ThePcUser** [labwc/labwc#2282]
I had written this code in this file "~/.config/wayfire.ini" so the chromium auto starts up after a reboot or powerloss. 

[autostart]
terminal = chromium-browser --hide-crash-restore-bubble

But after I switched to labwc, it is not working. Could you please tell me how I should do this so it works with the new labwc?

Thank you!

**Comment by ahesford** [comment]
You're looking for

    ${XDG_CONFIG_HOME}/labwc/autostart

The introductory section of [labwc-config.5](https://labwc.github.io/labwc-config.5.html) covers the various startup files that will be read.
