### ISSUE TITLE
Title-bar buttons not aligned correctly in 0.8.1

### ISSUE THREAD

**Issue by tsujan** [labwc/labwc#2286]
This screenshot shows the left title-bar buttons of a normal window with Labwc 0.8.0:

![titlebar-old](https://github.com/user-attachments/assets/1ce82091-36d9-4e98-a239-84aa3c372ee2)

The buttons are perfectly aligned.

After I upgraded to 0.8.1, I added these lines to my theme to have the same sizes

```
window.button.width: 20
window.button.spacing: 6
window.titlebar.padding.width: 3
window.titlebar.padding.height 3
```

The result is this:

![titlebar-new](https://github.com/user-attachments/assets/7f75a915-306e-4669-9ec5-3e4d13bb4f83)

The close button at the left is one pixel off vertically (you could check it in GIMP). The same happens with my right-most menu button. The other buttons are OK.

However, this offset doesn't exist in maximized or tiled windows. I have `<cornerRadius>8</cornerRadius>` in `rc.xml`.

**Comment by tsujan** [comment]
Found and commented out these lines, and the issue disappeared:

https://github.com/labwc/labwc/blob/2b877d22936dabd333fe8fbe9eb961e8196301b9/src/ssd/ssd-titlebar.c#L171-L184

**Comment by tokyo4j** [comment]
I reproduced this issue also with auto-generated hover effects and I think this is a minor regression from #2225 that changes the loaded icon buffer to be smaller than it is in the image file.

Here are the image file and the dump of the internal buffers for button icons when I set `window.button.width: 20`  and `window.button.height: 26`:

1. The raw image for the icon (100x100)
![menu-active-png](https://github.com/user-attachments/assets/7aeaddf8-6f39-4d5d-b5fa-5c35692392ef)

2. The dumped buffer for the non-hover icon (26x26)
![menu-active](https://github.com/user-attachments/assets/f59902b3-6310-4b76-be77-44365987111a)

3. The dumped buffer for the auto-generated hover icon (26x33)
![menu-active-hover](https://github.com/user-attachments/assets/0848adf1-82b9-453b-a4d3-5fd84bec849a)

The buffers in (2.) and (3.) are downscaled and centered to fit in the 20x26 space in the titlebar. This almost works fine, but as you can see by opening the buffer in (3.) with image viewer, there are asymmetrical gaps (3px on top and 4px on bottom) in the intermediate buffer for the auto-generated hover icon and this asymmetry is not taken into account when downscaled and centered in the titlebar.

As a result, the asymmetry is amplified and  the hover icon is misaligned:

https://github.com/user-attachments/assets/afe9f7f2-8446-4aff-999d-e83d5be9e7e1

I made a patch to fix this by seeing both `window.button.width` and `window.button.height` when creating intermediate buffers, but I'm not sure this is the right way to go.

**Comment by tokyo4j** [comment]
I was hoping this to be fixed before the next release, but the fix will be postponed for the next release cycle.

I'm working on major rework of icon rendering which should fix the issue, but the patch is so large for the next release.

**Comment by tokyo4j** [comment]
@tsujan Sorry, I forgot to mention that setting `window.button.width` and `window.button.height` should fix the issue for now.

**Comment by tsujan** [comment]
It's OK. I use my [workaround](https://github.com/labwc/labwc/issues/2286#issuecomment-2449761101) until its fixed. Thanks for caring!
