### ISSUE TITLE
Weirdness with window rules and calibre after 96da82c

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#2288]
I have a window rule that is supposed to make sure the calibre window is maximized and on desktop 3 when I open it. After 96da82c something weird is happening. 
If I close the calibre window while it is maximized (so it also should start maximized), it doesn't get moved to desktop 3. If I close the window while it is unmaximized, it gets maximized and moved to desktop 3. But the same thing happens with any sub windows I open in calibre too, for example with the preferences, add books window or an error message, even though `matchOnce="true"` should make sure that only applies to the main calibre window.

https://github.com/user-attachments/assets/4e51f2b5-8082-4fcb-ab48-585b491247a3

```
    <windowRule identifier="calibre-gui" matchOnce="true">
      <action name="Maximize"/>
      <action name="SendToDesktop" to="3" follow="no"/>
    </windowRule>
```

**Comment by ahesford** [comment]
Sorry, I overlooked some logic errors and some defaults when merging the identified commit. Would you mind testing #2289? It seems to work for my simple test case:

```xml
<windowRule identifier="foot" matchOnce="true">
  <action name="Maximize" />
  <action name="SetDecorations" decorations="border" />
</windowRule>
```
