### ISSUE TITLE
menu.overlap.x does not work with negative values

### ISSUE THREAD

**Issue by Ved-un** [labwc/labwc#2294]
Hello!
Thank you very much for your hard work and great project.

I have this problem in **labwc 0.8.1**

When using in **themerc-override**
`menu.overlap.x: 5`
the submenu moves to the left and overlaps the main menu,

and with negative values
`menu.overlap.x: -5`
nothing happens at all, although it should be shifted to the right.

P.S.
I would like you to add menu border parameters (like in Openbox).
`menu.border.width`
`menu.border.color`
because without border menu often merges with the background.

**Comment by tokyo4j** [comment]
From git-blame, b605868 seems to have added a check to ensure `menu.overlap.x` >=0. I guess this is just a mistake and we can just remove the check.

**Comment by jp7677** [comment]
Sorry, that was me ;)
Should be adressed in https://github.com/labwc/labwc/pull/2356
