### ISSUE TITLE
Swaybg causes many "Failed to get DMA-BUF from buffer" logs

### ISSUE THREAD

**Issue by RicArch97** [labwc/labwc#2297]
After setting a wallpaper with swaybg, i see **alot** of these logs:

```
00:00:07.930 [DEBUG] [backend/drm/fb.c:147] Failed to get DMA-BUF from buffer
00:00:07.930 [DEBUG] [backend/drm/drm.c:734] connector DP-2: Failed to import buffer for scan-out
```

These are DEBUG logs though, so I'm wondering whether this is an actual issue, or just information.

Reproduction steps (i have 2 monitors):

1. Start LabWC with debug enabled; `labwc -d 2> labwc.log`
2. Set a wallpaper with `swaybg`, e.g. `swaybg -o "*" -i somewallpaper.png -m fill`
3. Checks your logs live, so you can actually see what triggers it:  `tail -f labwc.log`
4. I had an alacritty window open with the logs on my DP-1. DP-2 was empty (just had the wallpaper). Moving the cursor around there caused the large spam of the logs as shown above.
5. Moving the alacritty window to DP-2, and moving around the cursor on the empty (except wallpaper) DP-1 also caused a spam of those logs, but for DP-1.
6. Moving between the wallpaper and the alactitty window with the mouse also generated those logs.

Any idea why this happens, and if this is an issue at all?

Full log: 

[labwc.log](https://github.com/user-attachments/files/17608154/labwc.log)

**Comment by Consolatis** [comment]
From memory: swaybg uses shm to create its buffers (e.g. CPU accessed system memory vs some GPU texture) . The (wlroots) debug log message should likely not exist at all. It shows up when direct scanout fails to use the most optimal path via dmabufs. Direct scanout in turn is automatically activated once a client spans the full output width / height and there is no other surface covering it.

**Comment by RicArch97** [comment]
Good to know, thanks!
