### ISSUE TITLE
can't see a SSD window menu icon 

### ISSUE THREAD

**Issue by wastlnd** [labwc/labwc#2299]
I have set the icon theme name in the rc.xml file but the Pale Moon browser window still shows the generic xbm icon. Other apps work fine, and I do have a /usr/share/applications/palemoon.desktop file that correctly points to the PNG icon. The icon theme is Adwaita. I also downloaded a palemoon.svg icon and put it in .local/share/icons/apps/hicolor/scalable, no difference.

**Comment by wastlnd** [comment]
Further info, I have tested Chromium too, but this time the icon is visible.

**Comment by Consolatis** [comment]
To debug this we'd need
- `palemoon.desktop`
- output of `wlrctl window list | grep -i palemoon`

@johanmalm this might warrant an own issue template as "window icon for application $x doesn't work" will pretty likely show up more in the future.

**Comment by johanmalm** [comment]
> 
> @johanmalm this might warrant an own issue template as "window icon for application $x doesn't work" will pretty likely show up more often in the future.

Yeah, good idea. Won’t be able to look at it for a couple of days. Maybe Wednesday.

**Comment by wastlnd** [comment]
Hey @Consolatis, here's the palemoon.desktop file:
https://aur.archlinux.org/cgit/aur.git/tree/palemoon.desktop?h=palemoon-bin
The `wlrctl` command doesn't return any output.

**Comment by Consolatis** [comment]
`wlrctl window list` should have a line in there of the running palemoon window. If it isn't called palemoon that is likely the issue here.

**Comment by wastlnd** [comment]
Indeed, in this list the browser is just genericaly called "Navigator" (the way sfwbar calls the web browser).

**Comment by 01micko** [comment]
@wastlnd just saw your cross post in `sfwbar`. It's looking more like a pale moon bug to me, or even a packaging bug.

**Comment by wastlnd** [comment]
Hey @01micko yes I cross posted there because sfwbar has the same issue, it doesn't even show the app name. It's weird because the icon and the desktop file are installed to the standard location, I'm perplexed as to what should the bug be about.

**Comment by 01micko** [comment]
Hmmm.. my system is on labwc-0.7.4 so I can't test the window icon but the sfwbar ison is working for me (it is already in my icon theme as an svg, I know that because I built the icon theme! https://github.com/01micko/labbe-material-icons)
![20241105_21h18m13s_grim](https://github.com/user-attachments/assets/915b86dc-0063-44ab-8899-0a035939013d)

**Comment by wastlnd** [comment]
Hmm Indeed Pale Moon doesn't seem to install SVG icons, just PNG. However I also tried to download a palemoon.svg from the web and placed in in .local/share/icons, it didn't work..

**Comment by 01micko** [comment]
I just tested on my laptop running labwc-0.8.1 and Pale Moon in the `alt-tab` OSD exposes itself as 'Navigator' !!! .. and my lappy is on latest (almost) sfwbar too. More to come... (oh, the `sfwbar -d -g` on it exposes 'Navigator too)

**Comment by 01micko** [comment]
If I copy an icon to `/usr/shareicons/hicolorscalabe/apps/Navigator.svg` (it's real svg) here's what happens:


![Navigator](https://github.com/user-attachments/assets/434b1df0-c78b-4663-a8b9-c60db5db59f8)


And here's the OSD

![palemoon-navigator](https://github.com/user-attachments/assets/dd62861e-882c-41f6-a41b-af7b759955d6)


re: https://github.com/LBCrion/sfwbar/issues/259

**Comment by Consolatis** [comment]
So this is a palemoon (or packaging) bug. As it seems to be running on xwayland (based on the screenshot) it should be enough to add this to palemoon.desktop:
```desktop
[Desktop Entry]
..
StartupWMClass=Navigator
```

That should allow labwc to find to correct .desktop file and thus the icon name and thus the png or svg item.

**Comment by 01micko** [comment]
@Consolatis `StartupWMClass=Navigator` fixes it for both `labwc` and `sfwbar` in my laptop setup - and BTW the Arch PKGBUILD just repackages the palemoon GTK2 tarball. IDK why because I've built pale moon before and it's no harder than building firefox.
