### ISSUE TITLE
Weird cycling focus logic when switching between workspaces

### ISSUE THREAD

**Issue by pirat89** [labwc/labwc#2329]
### Problem description

When switching between workspaces/desktops, each time a different window (available/visible on the target workspace) is activated/focused, even when the window originally focused/active is available on both (original and target) workspaces. This is weird and kind of annoying as many times I start to type on keyboard when a different window is focused after the workspace switch, so I guess this is not intended behavior. Witch 3+ windows set as omnipresent, the focus cycle through all of them after each change of the workspace.

Additional Notes:
* I realized that when using multiple outputs and I haven't tried it yet with a single output device to see whether it depends to that fact anyhow. Both omnipresent windows are displayed in the same output.
* I guess there is a logic to unfocus current active window when switching a workspace which leads to the situation the next window is picked.
* If I have a time, I will take a look at it if I can find more or come up with a fix.
* The behaviour seems same in labwc `0.7.4` and newer - including `0.8.1`. (I haven't tried versions before 0.7.4)

### Steps to reproduce

1. open 2+ windows and set both of them omnipresent
2. go to a different workspace

the focus is switched each time.

### labwc build source

Release

### labwc version

0.8.1

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Fedora 40+

**Comment by Consolatis** [comment]
Can confirm, something is off with omnipresent + desktop switching.

**Comment by Consolatis** [comment]
Can you give #2332 a try?

**Comment by pirat89** [comment]
@Consolatis works like a charm. thanks!

**Comment by Consolatis** [comment]
Thanks for reporting and testing. Should be fixed in the master branch.
