### ISSUE TITLE
Create tag 0.5.0

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#233]
It'd be good to drop another tag soon. Do say if there are any fixes/issues that you'd particularly like to see resolved (preferably not a wish list of new features :smile:)

**Comment by Consolatis** [comment]
I think the mouse focus issues we were talking about in IRC should be fixed before the release. #226 seems related as well.

**Comment by johanmalm** [comment]
v0.5 branch created and tagged at 0.5.0
The issues described by @Consolatis have been fixed by @jlindgren90 
README updated with IRC link on master branch.
