### ISSUE TITLE
Reload cursor theme + keyboard-layout on SIGHUP

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#235]
Required for live updating the config, for example via https://github.com/labwc/labwc-tweaks/pull/3

**Comment by Consolatis** [comment]
This may be relevant for reconfiguring keyboard-layout https://github.com/swaywm/wlr-protocols/pull/31#issuecomment-457906043

**Comment by johanmalm** [comment]
Implemented a long time ago via (at least) #1587 and #1619
