### ISSUE TITLE
HDMI hotplug events cause applications to switch back from fullscreen

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#2362]
### Problem description

When an HDMI hotplug event occurs, application windows which are full screen drop back to windowed

### Steps to reproduce

1. Launch labwc
2. Start an application which can be fullscreened - Chromium or Geany, for example
3. Fullscreen the app - F11 usually
4. Pull the HDMI cable out and reconnect to force a hotplug event - some monitors will do this if power-cycled, but not all
5. The app will now no longer be fullscreened

### labwc build source

Release

### labwc version

0.7.4

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Raspberry Pi OS

**Comment by Consolatis** [comment]
That has been changed for labwc 0.8.0 in
- #2040

I don't know how complicated it is to backport this to the v0.7 branch
