### ISSUE TITLE
Cannot set resolutions etc with multiple monitors connected on 0.8.1

### ISSUE THREAD

**Issue by spl237** [labwc/labwc#2366]
### Problem description

With a single monitor connected, I can set resolution etc using either wlr-randr (0.2.0) or kanshi (1.5.1).

With two monitors connected, settings made in either are ignored - wlr-randr returns the message "failed to apply configuration".

This is a regression from 0.7 - under 0.7.4, this works fine; under 0.8.1, it doesn't.

### Steps to reproduce

1. Connect two monitors
2. Launch labwc
3. Try to set the resolution on one monitor using wlr-randr - wlr-randr --output HDMI-A-1 --mode 1920x1080 or whatever
4. Resolution does not change; wlr-randr reports "failed to apply configuration"

### labwc build source

Local build

### labwc version

0.8.1 (with a couple of upstream patches)

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

RPiOS

**Comment by spl237** [comment]
Just tried using the trixie version of wlr-randr (0.4.1) - no difference; still unable to set resolution.

**Comment by spl237** [comment]
When running kanshi from the command line. it reports "failed to apply configuration for profile '<anonymous at line 1, col 9>'

**Comment by cillian64** [comment]
Looks like this is actually my fault with a downstream patch I added in our wlroots package.

**Comment by spl237** [comment]
Was indeed a problem with our wlroots - thanks to @cillian64 for fixing it, and apologies for the FUD to everyone else!
