### ISSUE TITLE
Multiple menus do not seem to work

### ISSUE THREAD

**Issue by juanitotc** [labwc/labwc#2367]
### Problem description

Using the following works in rc.xml in openbox, but not in labwc

```xml
<menu>
    <file>system-tools.xml</file>
    <file>ondemand.xml</file>
    <file>menu.xml</file>
  </menu>
```

### Steps to reproduce

start labwc - menu.xml is parsed and appears, but not the other menu files

### labwc build source

Local build

### labwc version

0.8.1

### labwc environment

From a console prompt

### Distribution

TinyCoreLinux

**Comment by Consolatis** [comment]
`<file>` is not supported by labwc. And neither the `<menu>` element in `rc.xml`.

You could either paste the content of the files into `~/.config/labwc/menu.xml` (assuming they use a correct `id` tag, without the `<openbox_menu>` root entry) and then do something like this in `menu.xml`
```xml
<menu id="root-menu">
	<menu id="system" />
	<menu id="ondemand" />
	<menu id="somethingelse" />
</menu>
```
