### ISSUE TITLE
Generalize menus

### ISSUE THREAD

**Issue by keshto** [labwc/labwc#237]
Would be nice to write our own menus:
```
<menu id="display-menu" label="">
	.... #settings for display options and change wallpaper
</menu>
```
that can be called on lets say right click on root. In other words don't limit ourselves to only `client/root-menu`

**Comment by Consolatis** [comment]
Menus may contain submenus. Thus, what you could do is adding a display-menu as submenu of the root-menu which has entries with action name="Execute" for wdisplays / some custom shell script which replace a sway-bg process or similar.

**Comment by keshto** [comment]
Yes, but that would litter my main menu :) also when I right click instead of left click that still does not solve the issue of just showing that menu itself. The idea is to have self contained menus to bring up. That way we could do things like select wifi APs with a dynamic menu when clicking on an icon, create a shutdown menu, etc.

**Comment by Consolatis** [comment]
The current layout of the menu code is not really designed to handle multiple menus. Even the newish window menu (aka `client-menu`) is kind of hacked onto it. I am not saying its impossible to add other menus but it would require a redesign of the menu code.

Not sure if this would be in scope of labwc. I wouldn't mind this feature but wouldn't work on it immediately either.
What are your opinions @johanmalm @ARDiDo?

**Comment by keshto** [comment]
Just read your edit. If the menus are too static, what about exposing some sort of IPC/api that an independent menumaker type application consume? That would also give labwc a little more modularity for those who use solely wofi type launchers. However, it does depart from the blackbox paradigm, but then again without dynamic menus etc we sorta already departed.

**Comment by keshto** [comment]
Sorry one last comment. I like the fact there is no IPC etc. complexity. Maybe this all can be solved with a menu application (most likely will have to wrote one) that we can call. That way we can get rid of the menu code and still invoke this menu application to show a popup menu. That would solve the generalize request here, as well as concerns in #230, and even the modularity aspect.

**Comment by Consolatis** [comment]
> Would be nice to write our own menus [..] that can be called on lets say right click on root. In other words don't limit ourselves to only `client/root-menu`

With https://github.com/johanmalm/labwc/pull/4 it will be pretty easy to implement multiple menus. The PR doesn't yet allow for the functionality but I'll add it.

Re IPC / external menus: Not in scope for labwc
Re dynamic ("pipemenus" [^0]): They might be implemented at some point but nobody is working on it currently.
[^0]: http://openbox.org/wiki/Help:Menus#Pipe_menus
