### ISSUE TITLE
[Feature] Activities view where one can see all windows

### ISSUE THREAD

**Issue by keshto** [labwc/labwc#240]
Something like the Gnome activities view would be awesome. Unfortunately it requires the WM to take care of this, even though having it as a separate program would be more desirable. https://github.com/dreinharth/byway/commit/5777dd6f955569da739a42a5caa6c479f699b038 Is a simple implementation (written in zig).

**Comment by Consolatis** [comment]
If you are fine with icons instead of actual window previews an external application could use the foreign top level protocol to get the list of open windows + ability to switch to them. Basically just like a panel with a different layout.

**Comment by keshto** [comment]
Only icons are worse than a text task switcher IMO because I often have many of the same application instance open. Also, even with labels they don't differentiate much because some have the same titles that is why previews are nice.

**Comment by Consolatis** [comment]
I think this is not really in scope for labwc.

Maybe the screencopy protocol will get extended to capture single surfaces (and track their movement) at some point which would then allow for a live preview of application windows and thus allow creating an external "activities view" implementation.

Here are some links regarding capturing single surfaces only but I bet there is more information out there somewhere:
https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/issues/93
https://github.com/emersion/xdg-desktop-portal-wlr/issues/12#issuecomment-628090094
