### ISSUE TITLE
Menus in Qt apps appear for a millisecond and disappear

### ISSUE THREAD

**Issue by txtsd** [labwc/labwc#242]
I'm unable to use rightclick menus in any Qt apps, even with `QT_QPA_PLATFORM=wayland`
Menubar menus work if you click on an entry, then move the mouse away and back to the menubar.

**Comment by keshto** [comment]
What version of labwc are you using? The latest commit https://github.com/labwc/labwc/commit/588f2331511159b1b497a9e98792741bce41d7be changed some logic for menus, so if you are running master you might want to try before that and see if you have the same issue. If you are running older commit then try latest and see if that fixes it.

**Comment by txtsd** [comment]
I was running the latest commit. You want me to run an older build instead?

**Comment by keshto** [comment]
Well, like I said there is a recent change so try the commit before the one linked above and see if that works better for you.

**Comment by Consolatis** [comment]
@txtsd same behavior for `QT_QPA_PLATFORM=xcb`? Also, are you using Qt5 or Qt6?

**Comment by txtsd** [comment]
@Consolatis It works fine with `xcb`. I tried both qt5 and qt6 apps on master.

**Comment by txtsd** [comment]
Seems like it might be a system thing? The same thing happens in sway.

**Comment by johanmalm** [comment]
Okay. Will close here for now then. Shout if you think it's labwc related.
