### ISSUE TITLE
Update links in readme and wiki to point to organisation repo

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#243]
See links at
- https://github.com/labwc/labwc#2-build
- https://github.com/labwc/labwc/wiki/Build

The wiki page for `Build` seems rather outdated as well, maybe we should just remove it completely.
Thanks to hype_ for pointing it out in IRC.

**Comment by hype3** [comment]
I fixed the wrong links #244

**Comment by Consolatis** [comment]
Thanks :)
