### ISSUE TITLE
text-input enable state maybe not sync with surface focus when use A-Tab to switch window

### ISSUE THREAD

**Issue by dgod** [labwc/labwc#2435]
### Problem description

sometimes I find that when app switch use the alt tab, input method is not activated. use mouse to switch app is ok.
I only find qt6 have this problem, gtk3 is ok(gtk 4 can't start, has error 71).

### Steps to reproduce

1 run labwc with one input method, two qt6 based app
2 use alt tab switch between the app
3 in ime.c handle_text_input_enable is not called most times, and  text_input->input->current_enabled keeps 0

### labwc build source

Release

### labwc version

0.8.2

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

fedora

**Comment by tokyo4j** [comment]
Looks like a Qt bug. `zwp_text_v3.enable` request is double-buffered and `zwp_text_v3.commit` must follow to actually enable the text-input, but Qt seems to send `zwp_text_v3.enable` alone upon receiving keyboard focus.

The following video shows that the first character typed in featherpad after Alt-Tabbing is always not composited ("a" -> "あ"):

https://github.com/user-attachments/assets/0bfe6a7b-e9f8-4b8d-8579-b27a3493a95e

**Comment by dgod** [comment]
Use mouse click to switch window I don't have the problem, and Use KDE plasma desktop  the same qt app don't have problem.
Use keybind to switch window have some difference?

**Comment by tokyo4j** [comment]
Do you click the Qt app window to move focus? The issue also happens when I set `<focus followMouse="yes" />` and hover the window to move focus.

If I use mouse click to move focus, Qt seems to send `zwp_text_input_v3.commit` after receiving `wl_pointer.button`:

```
[ 134440.701] {Default Queue} zwp_text_input_v3#14.enter(wl_surface#34)
[ 134440.704] {Default Queue}  -> zwp_text_input_v3#14.enable()
[ 134440.706] {Default Queue} wl_pointer#26.button(40106, 34656087, 272, 1)
[ 134440.712] {Default Queue} wl_pointer#26.frame()
[ 134440.718] {Default Queue} wl_pointer#26.button(40107, 34656128, 272, 0)
[ 134440.720] {Default Queue} wl_pointer#26.frame()
[ 134440.722] {Default Queue} xdg_toplevel#37.configure(1109, 696, array[4])
[ 134440.725] {Default Queue} xdg_surface#36.configure(40105)
[ 134440.931] {Default Queue}  -> wp_viewport#39.set_destination(1109, 696)
[ 134440.937] {Default Queue}  -> xdg_surface#36.set_window_geometry(0, 0, 1109, 696)
[ 134440.940] {Default Queue}  -> xdg_surface#36.ack_configure(40105)
[ 134440.945] {Default Queue}  -> xdg_surface#36.set_window_geometry(0, 0, 1109, 696)
[ 134441.135] {Display Queue} wl_display#1.delete_id(45)
[ 134441.494]  -> wl_surface#34.frame(new id wl_callback#43)
[ 134441.509] {Default Queue}  -> wl_surface#34.offset(0, 0)
[ 134441.511] {Default Queue}  -> wl_surface#34.attach(wl_buffer#44, 0, 0)
[ 134441.514] {Default Queue}  -> wl_surface#34.damage_buffer(0, 0, 1109, 696)
[ 134441.516] {Default Queue}  -> wl_surface#34.commit()
[ 134441.531] {Default Queue} wl_callback#45.done(40107)
[ 134441.600] {Default Queue}  -> zwp_text_input_v3#14.commit()
```

**Comment by tokyo4j** [comment]
> Use KDE plasma desktop the same qt app don't have problem.

Did you confirm they are using text-input-v3 protocol? In my setup, they use text-input-v2 protocol so it makes sense that they don't have this issue.

**Comment by dgod** [comment]
I

> > Use KDE plasma desktop the same qt app don't have problem.
> 
> Did you confirm they are using text-input-v3 protocol? In my setup, they use text-input-v2 protocol so it makes sense that they don't have this issue.

I don't know what they really use, but can sure kde of fedora support text-input-v1, v2, v3

**Comment by dgod** [comment]
More likely a qt bug, use gnome shell with ibus have the bug too. so close this.
