### ISSUE TITLE
New maximized windows are not avertised as such by zwlr_foreign_toplevel_handle_v1::state

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#2460]
### Problem description

Using xfce4-panel's intellihide feature shows that windows maximized at opening are not advertised as such. Originally reported in https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/889.

### Steps to reproduce

1. Run `xfconf-query -c xfce4-terminal -p /misc-maximize-default -s true --create --type bool`
2. Run `xfconf-query -c xfce4-panel -p /panels/panel-1/autohide-behavior -s 1 --create --type int`
3. Open xfce4-terminal (or a new window of xfce4-terminal)
4. Run `WAYLAND_DEBUG=1 xfce4-panel 2>&1 | grep 'state(array\[8'`
5. See that there is no output from the above command, and the panel does not hide (as it should, since the active window is maximized)

With the same steps in wayfire, the panel hides and the command in 4. gives this output:
```
[1814883.972] {Default Queue} zwlr_foreign_toplevel_handle_v1#4278190081.state(array[8])
[1814884.458] {Default Queue} zwlr_foreign_toplevel_handle_v1#4278190081.state(array[8])
[1814884.787] {Default Queue} zwlr_foreign_toplevel_handle_v1#4278190081.state(array[8])
[1814884.928] {Default Queue} zwlr_foreign_toplevel_handle_v1#4278190081.state(array[8])
```

### labwc build source

Local build

### labwc version

0.8.2+29+g1550eb9

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Arch Linux

**Comment by Consolatis** [comment]
Thanks for the report!

Should be fixed by
- #2461

**Comment by Tamaranch** [comment]
Yes, I can confirm it fixes the issue, thanks!
