### ISSUE TITLE
Keyboard focus is moved to the surface below the cursor on finishing window switcher with followMouse="yes" & followMouseRequiresMovement="no"

### ISSUE THREAD

**Issue by tokyo4j** [labwc/labwc#2475]
### Problem description

#2455 reintroduced #849.

In `osd_finish()`, we call `seat_focus_override_end()` which clears `server->input_mode` and then call `cursor_update_focus()` which moves the keyboard focus to the surface below the cursor with `followMouse="yes"`, `followMouseRequiresMovement="no"` and `server->input_mode == PASSTHROUGH`.

### Steps to reproduce

1. Set `followMouse="yes"` and `followMouseRequiresMovement="no"` in `rc.xml`.
2. Open 2 windows and put cursor on one of them.
3. Start window switcher and try to move the cursor on the other window.
4. Keyboard focus stays on the window.

### labwc build source

Local build

### labwc version

0.8.2-37-gbad788cc-dirty

### labwc environment

From a TTY or some display manager like lightdm

**Comment by tokyo4j** [comment]
Perhaps we don't need to consider this issue as a bug since #849 is an issue from days when `followMouseRequiresMovement` was always `no`, if I get it correctly.

I even wonder if there are users who actually prefer `followMouseRequiresMovement=no`... Maybe we can remove that option?

**Comment by Consolatis** [comment]
I think it is actually more correct now. The default for `followMouseRequiresMovement` is 'yes' anyway and I assume that is what most people who want to use follow mouse in the first place will stick with. The other mode is a more strict variant with the idea of 'focus-what-is-under-the-cursor-at-all-times` which is what happens now. So I think we are fine as is.

**Comment by tokyo4j** [comment]
OK, I agree with you now.

Then we should describe this change in the 0.8.3 release note. @johanmalm

**Comment by tokyo4j** [comment]
For what it's worth, I realized that window switcher becomes almost unusable with  `<focus followMouse="yes" followMouseRequiresMovement="no" raiseOnFocus="yes" />`, because the window below the cursor is always raised, discarding the selection with window switcher. But the experience with that configuration before #2459 was already bad  since the the window below the cursor was raised as soon as the cursor is moved.

Anyway, there would be little amount of users who prefers `<focus followMouse="yes" followMouseRequiresMovement="no" raiseOnFocus="yes" />`, so this can be addressed later.

**Comment by johanmalm** [comment]
> Then we should describe this change in the 0.8.3 release note.

@tokyo4j So something like this? `With followMouse="yes" and followMouseRequiresMovement="no" in rc.xml
  focus cannot be changed whilst using the window-switcher.`

**Comment by Consolatis** [comment]
Technically it still can because the window switcher also raises the selected window. So if the cursor happens to be on both surfaces and the stacking order changes due to the `A-Tab` selection that would change the focus.

**Comment by johanmalm** [comment]
> Technically it still can because the window switcher also raises the selected window. So if the cursor happens to be on both surfaces and the stacking order changes due to the `A-Tab` selection that would change the focus.

Attempt 2: `With followMouse="yes" and followMouseRequiresMovement="no" in rc.xml, keyboard-focus semantics have subtly change whilst using the window-switcher.`

Or do we just not mention it because it's such an edge case.

**Comment by tokyo4j** [comment]
> Attempt 2: With followMouse="yes" and followMouseRequiresMovement="no" in rc.xml, keyboard-focus semantics have subtly change whilst using the window-switcher.

Yeah I think this is fine. Though not very detailed, I like this brief explanation rather than explain it in more than 3-4 lines for such an edge case.
