### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by CerisWhite** [labwc/labwc#248]
I was originally going to open a pull request, but this is minor enough that I decided against it:

Per commit #245, the link
`https://raw.githubusercontent.com/labwc/labwc/master/docs/labwc-config.5.scd`
is typo'd as
`https://raw.githubusercontent.com/abwc/labwc/master/docs/labwc-config.5.scd` (missing an L from the first `labwc`)

**Comment by johanmalm** [comment]
Thanks. Sorted.
