### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by probonopd** [labwc/labwc#2482]
### Problem description

![{DCF9EC2B-7038-47CF-B21B-5D64017EDD13}](https://github.com/user-attachments/assets/5f2093ee-7259-4bd3-acf2-98fe877fcf91)

### Steps to reproduce

Look at https://github.com/labwc/labwc/actions

### labwc build source

Local build

### labwc version

main

### labwc environment

Not Applicable

### Distribution

Debian

**Comment by Consolatis** [comment]
We are very much aware of that. The reason is that wlroots 0.18.x recently entered Debian Testing but labwc needs one more day to do the same. See https://tracker.debian.org/pkg/labwc

So it should fix itself tomorrow and if not we will adjust the CI.
