### ISSUE TITLE
Cannot use Alt+Left (mouse and touchpad) to move window (v0.5 branch).

### ISSUE THREAD

**Issue by ahmadraniri1994** [labwc/labwc#259]
I'm happy to try v0.5 branch since the scroll bug on qt apps are fixed, but now I can't use Alt+Left to move and drag windows (both touchpad and mouse). Switch to master suddenly the problem is gone. I don't know if this behaviour is already reported before. Thanks.

**Comment by 01micko** [comment]
+1

Can still drag by titlebar though.

**Comment by ahmadraniri1994** [comment]
Yeah. So, is it confirmed ? Better switch v0.5 again then. Thanks.

**Comment by 01micko** [comment]
I wouldn't. You should still be able to drag windows and resize. I'm sure there'll be a simple fix.

**Comment by Consolatis** [comment]
> Yeah. So, is it confirmed ?

Yes it is confirmed by code as well. Fallout of #241.

Currently working on a fix that hopefully doesn't break anything else.
Would be great if you could test drag and drop of #260

**Comment by Consolatis** [comment]
#260 has been merged into the v0.5 branch so just updating it should solve the issue here (+ double click in foot).
Further testing of v0.5 branch would be greatly appreciated because we are thinking about doing a minor 0.5.1 release soon.

**Comment by ahmadraniri1994** [comment]
Confirmed, drag with Alt+left works again. Thanks.

**Comment by 01micko** [comment]
Fixed with no popup regressions, tested firefox and vivaldi. :smile:

**Comment by 01micko** [comment]
![20220228_11h46m54s_grim](https://user-images.githubusercontent.com/1019119/155911368-4e61b73a-f182-4734-8349-798f3bb05cfa.png)

**Comment by Consolatis** [comment]
@01micko awesome! thank you :)
