### ISSUE TITLE
top waybar not clickable when a window is tiled to it

### ISSUE THREAD

**Issue by spectrum70** [labwc/labwc#265]
If i position a window with the titlebar in contact with a top waybar of height 10, trying to click the waybar have no effect since i get the window title resize cursor over it all.
Not sure if there is a config option related to resize cursor to avoid this.

**Comment by johanmalm** [comment]
I changed the default from 20 (which is a bit excessive) to 8 for the time being.

I clumsily managed to include that in another commit. Sorry.
labwc/labwc@6b8c10dcd45c8fb1cc25bfc671b373c491837044

One way of dealing with this is to put `waybar` in the `top` layer.

We will fix this for panels in the bottom layer too one day, but it's not trivial, so want to stabilize the scene-graph implementation first.
