### ISSUE TITLE
NLS support - discussion

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#269]
There is whole world out there that needs to know about __labwc__.

NLS is an ongoing task. With every update:
- `.pot` files must be updated (if relevant).
- Obviously the need for translators arises and updates added as needed.

Structural changes need to be made:
- The build scripts may need to be updated
- gettext (is there another?) support needs to be added
- better now than later

There's a lot more to it than a few dot points. I think it's necessary, at least to begin initial support now or soon.

**Comment by johanmalm** [comment]
Yes, great idea.

I don't know much about i18n myself, but suggested the following steps:

1. Research and agree coding approach. I.e. do we use gettext()? And if so, how does that really work? What are the steps in producing po files.
2. What's the scope? Menu files only, or all `wlr_log` messages, or something else?
3. Do we setup a separate translation project to reduce the commit noise on labwc:master?

**Comment by 01micko** [comment]
> 1. Research and agree coding approach. I.e. do we use gettext()? And if so, how does that really work? What are the steps in producing po files.

Well, `gettext` is GNU, compatible with the project licence. IDK what else exists in the context of `C`.  [This tutorial](https://www.labri.fr/perso/fleury/posts/programming/a-quick-gettext-tutorial.html) is basically what I have done previously, albeit my programs are much simpler than `labwc`.

> 2. What's the scope? Menu files only, or all `wlr_log` messages, or something else?

I'm thinking just GUI; at this point that's menus only.

> 3. Do we setup a separate translation project to reduce the commit noise on labwc:master?

Maybe until there are a few translations and everything is working well then squash some commits and merge back into the main line.

My 2 cents.

**Comment by 01micko** [comment]
Other things -
- Setting `setlocale(LC_ALL, "");` may break floating point math in locales that use a different decimal delimiter ([JWM](https://github.com/joewing/jwm/blob/8369b5800bccdd4be38d7059b3de8f9dbee6385c/src/misc.c#L228) has a fix for this, I'm sure `openbox` would have similar)
- IDK the implications for non-GNU os as `setlocale() [locale.h], textdomain(), bindtextdomain() [libintl.h]` are GNUisms; [gettext manual](https://www.gnu.org/software/libc/manual/html_node/Translation-with-gettext.html) says: 
> On systems where these functions are not part of the C library they can be found in a separate library named libintl.a (or accordingly different for shared libraries).

Hopefully that takes care of Alpine and the BSDs.
- RTL support ([fribidi](https://github.com/fribidi/fribidi) in GUI, `pango` should take care of it [already builtin in `labwc`])
- hard or optional dependency?

**Comment by 01micko** [comment]
Ok, some progress - sucsessfully generated `labwc.pot`

```pot
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the labwc package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: labwc\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-03-12 10:22+1000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: src/menu/menu.c:423
msgid "Reconfigure"
msgstr ""

#: src/menu/menu.c:425
msgid "Exit"
msgstr ""

#: src/menu/menu.c:441
msgid "Minimize"
msgstr ""

#: src/menu/menu.c:443
msgid "Maximize"
msgstr ""

#: src/menu/menu.c:445
msgid "Fullscreen"
msgstr ""

#: src/menu/menu.c:447
msgid "Decorations"
msgstr ""

#: src/menu/menu.c:449
msgid "Close"
msgstr ""
```

**Comment by 01micko** [comment]
I have this working now.

![it](https://user-images.githubusercontent.com/1019119/158038294-2b12e1f1-13ad-49e6-93e1-615456a2fbb1.png)

I'm not issuing a PR at this stage because there's a couple of `meson` version dependant issues that need addressing. The show stopper is that I'm on `meson-59.4` and the `${LOCALE}.po` files generated always seem to end up with `charset=ASCII` and that fails to generate the `gmo` files with encoding errors. I believe `meson >= 60.0` addresses this, but for a gettext implementation one would think that this would have been buitin from the start :confused:  
I changed the charset to `UTF-8` and that seems to work fine, at least for `it`, need to test `de` and `es`.

Instead I'll offer a diff of what I have so far (attached):

[i18n-diff.zip](https://github.com/labwc/labwc/files/8238675/i18n-diff.zip)


The `labwc.pot` and three `.po` files are included that generate `de.mo`, `es.mo` and `it.mo` - just menus. Please excuse the bad translations if so! I used online Collins dictionary. And besides, this is for demonstration purposes.

**Comment by 01micko** [comment]
`de` and `es`

![de](https://user-images.githubusercontent.com/1019119/158038847-38a0aaba-91b7-4453-8159-9a3d49782a4c.png)


![es](https://user-images.githubusercontent.com/1019119/158038851-dfdb9499-8775-49c5-8865-5d742cf51e33.png)


Would be nice if I knew a shorter Spanish translation for 'Fullscreen' :laughing:

**Comment by eli-schwartz** [comment]
> Do we setup a separate translation project to reduce the commit noise on labwc:master?

You could use something like transifex and then just merge the final translations in bulk into git immediately before release.

> The show stopper is that I'm on `meson-59.4` and the `${LOCALE}.po` files generated always seem to end up with `charset=ASCII` and that fails to generate the `gmo` files with encoding errors. I believe `meson >= 60.0` addresses this, but for a gettext implementation one would think that this would have been buitin from the start :confused: 

AFAIK this behavior comes from GNU gettext's msginit program, which documents:
> These values are set according to the content of the POT file and the current locale. If the POT file contains charset=UTF-8, it means that the POT file contains non-ASCII characters, and we keep the UTF-8 encoding. Otherwise, when the POT file is plain ASCII, we use the locale’s encoding.

**Comment by 01micko** [comment]
> AFAIK this behavior comes from GNU gettext's msginit program, which documents:

Yes, later on discovered that. It doesn't matter because the `.po` files need to be edited manually (or with po-edit or something) to fix encoding.

Just taking a look at transifex.

Thanks.

**Comment by johanmalm** [comment]
Thanks for moving this forward @01micko 
I haven't really got a preference as yet, but I'd like to add another option to the mix.
If we're only translating the 7 menu entries, we could simply add some location entries in the `menu.xml` file, a bit like xdg desktop entry (https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html) does for Name, Comment and so on. `gettext()` is generally intended for hard-coded strings in the C code, so considering that the strings we're intending to translate are actually designed to be read from xml-files, it does give us some options.

It would merely just be a matter of
- parsing the `$LANG` environment variable
- somehow specifying the the location (e.g. `rootmenu[en]`) in `menu.xml`
- installing menu.xml as part of the `meson install` process.

It might potentially makes it easier for distributions and derivatives to extend the menus and include translations. Let's be honest... not many people would probably want the current hard-coded rootmenu :smile:

**Comment by 01micko** [comment]
Well yes with the main menu this is true and I like your idea, but the window menus don't use `xml` and I don't think that they can.

BTW, gettext's scope is far more reaching than `C`. Many languages are supported including scripts and I believe XML based _languages_ too. Even `.desktop` files.

**Comment by Consolatis** [comment]
> the window menus don't use xml and I don't think that they can.

Actually they do, they just fall back to the internal hardcoded one. See docs/menu.xml.

**Comment by 01micko** [comment]
My bad, was tired,

Anyway if only menus then can probably abandon gettext if the other method works.

Was a good exercide though. Now I know how to use meson with gettext :smile:

**Comment by Consolatis** [comment]
I think NLS would still make sense for manpages, default menu.xml and possibly comments in docs/rc.xml.all

**Comment by 01micko** [comment]
On further thought, I think my implementation (see diff in [this post](https://github.com/labwc/labwc/issues/269#issuecomment-1065984219) ) makes sense.

- `menu.xml` doesn't necessarily contain the `<menu id="client-menu" label="ClientMenu">` block if generated from a menu generator - nor should it.
- extensible to `wlr_log()` messages, which could be advantageous as **labwc** adoption grows (and it's growing :smile: ) and probably should be added to the scope.

It _does not_ solve the issue of documentation translations. I'm thinking maybe a 'docs' repo under the org for that.

A possibility with that infra structure in place, is that if a non-English locale is detected when `meson` is first called to configure the project then the `docs[${LOCALE%_*}]` repo could be added as a subproject - alongside the default docs. What do you think @eli-schwartz ? Possible with `meson`?

**Comment by 01micko** [comment]
Moving forward with this soon.

**Comment by 01micko** [comment]
@johanmalm 

What is this translation like of `labwc(1)` from [vivaldi translate](https://vivaldi.com/features/translate/)? 
(They are Norwegian so shouldn't be too bad :sweden: `<->` :norway: :thinking: ).

---

labwc (1)

# NAMN

labwc - En Wayland som staplar kompositören

# SYNOPSIS
*labwc* [alternativ...]

# BESKRIVNING

Labwc är en wlroots-baserad staplingskompositör för Wayland.

Det syftar till att vara lätt och oberoende, med fokus på att helt enkelt stapla fönster och göra några fönsterdekorationer. När det är praktiskt möjligt använder det klienter för tapeter, paneler, skärmdumpar och så vidare.

# ALTERNATIV

*-c* Ange en konfigurationsfil med sökväg

*-C* Ange en konfigurationskatalog

*-d* Aktivera full loggning, inklusive felsökningsinformation

*-h* Visa hjälpmeddelande och sluta

*-s* Kör kommandot vid start

*-v* Visa versionnumret och avsluta

*-V* Aktivera mer verbosloggning

# KONFIGURATION OCH TEMA
Labwc använder openbox-specifikation för konfiguration och tema, men stöder inte alla alternativ. Följande filer styr utseendet och beteendet:

- ~ / .config / labwc / rc.xml
- ~ / .config / labwc / menu.xml
- ~ / .config / labwc / autostart
- ~ / .config / labwc / environment
- ~ / .themes / openbox-3 / themerc

Ekvivalenta XDG-baskatalogspecifikationsplatser hedras också.

Konfigurationsfilen och temat laddas om på mottagningssignalen SIGHUP .

Autostart-filen körs som ett skalskript. Detta är en plats för att ställa in en bakgrundsbild, starta en panel eller liknande.

Miljöfilen analyseras \<variable\> = \<value\> anger miljövariabler i enlighet därmed. Det rekommenderas att ange tangentbordsinställningar här, till exempel: `XKB_DEFAULT_LAYOUT = gb`. Se xkeyboard-config (7) för mer information. Observera att miljöfilen behandlas annorlunda med openbox där den helt enkelt kommer från innan du kör openbox.

# SE Också

labwc-config(5), labwc-theme(5), labwc-actions(5)

---

**Comment by johanmalm** [comment]
Better than 90% correct I'd say. Just the odd word that needs tweaking.

**Comment by 01micko** [comment]
My idea is that manpages and docs are going to be a user case thing so I don't see a benefit in incorporating into `labwc`. I envisage a separate repo, which I should start one day under my github account, say `labwc-docs-i18n` or something and when it's ready, transfer it to the org account.

The idea to install (or package) would be to have a meson routine getting the `$LANG` var from the users' environment (or for packagers just use the LANG direct).

Example: 

```
LANG=$LANG meson [options] build # if match isn't found, error
```

or for packagers

```
LANG=de meson [options] build # maybe LANG=all - have that as an option?
```

I know compiler and linker options can be passed to meson like that but @eli-schwartz is that possible with languages or is it better to make an option for meson? I suppose the `LINGUAS` file should be scanned so maybe an option is best.

Of course usual dependency checks (I'm thinking just `scdoc` should be fine) will be needed.

@johanmalm @Consolatis ?

**Comment by johanmalm** [comment]
Like the idea of a separate i18n repo.
Not sure how that would work with meson

**Comment by Consolatis** [comment]
I am a bit skeptical about building stuff based on language detection on the build host. Most applications are not built on the same system that they run on (unless you use gentoo).

IMHO all language man pages should be built and the deciding factor for choosing one over the other would then be the language setting on the system that actually runs man.

Regarding the separate repo I don't have any strong opinion in either direction.

**Comment by 01micko** [comment]
The separate repo is for maintainability and less noise on the main repo. Using a `subproject` should be possible, but the conversion from `.scd` to groff _may_ (I'm not too sure) need to be done locally, and that _would_ depend on the current machine's locale.

When I get time I'll do more research on the subject, but I think it's a worthwhile investment.

**Comment by eli-schwartz** [comment]
> I know compiler and linker options can be passed to meson like that but @eli-schwartz is that possible with languages or is it better to make an option for meson? I suppose the `LINGUAS` file should be scanned so maybe an option is best.

I already stated above that that is not possible. Compiler and linker options as environment variables is a universal standard, which Meson respects because support for it is built into Meson itself. Ad-hoc, completely arbitrary user-specified options do not have built-in support, and thus the only way to specify ad-hoc completely arbitrary user-specified options is by adding them to meson_options.txt

> The separate repo is for maintainability and less noise on the main repo. Using a `subproject` should be possible, but the conversion from `.scd` to groff _may_ (I'm not too sure) need to be done locally, and that _would_ depend on the current machine's locale.

I'm... genuinely baffled as to why you think that conversion from `.scd` to groff, a matter of running a compiler (not a C compiler, but a documentation compiler) on an ***input*** file and producing an ***output*** file, would not work unless the current machine has defined the system locale to a specific value?

You simply have a bunch of `*.scd` files, one for each manual and each language, and you run the scdoc documentation compiler on each one, in turn, and produce output files based on the input files. This can be done on any machine that has, well, scdoc. It's not like scdoc will error out with the message "I refuse to work because you are trying to build a manpage for a language that isn't your current locale, and I bet you didn't want that, you silly goose".

Also, you need to produce ***all*** man pages for ***all*** languages. If you don't, then linux distros will distribute absolutely nothing and you've wasted all your time in writing and publishing documentation, so why did you even bother? However, the distros will helpfully submit a bug report to alert you to the fact that you should build the documentation so that they can distribute it. :)

There are ***zero*** consequences of distributing documentation for all languages, unconditionally.

You're talking a lot about putting it in a separate repo as a subproject for the sake of "less noise", but I don't understand what that has to do with which manual pages you then build. Either the subproject is used and people do build documentation at all, or it is not used and they do not build documentation at all. If they do build documentation at all, then they need scdoc, and once they have scdoc, there is no cost to building all of it.

And again, in order for this to have baseline minimum usability, *all* languages must be built when building a linux distribution, or the whole thing is a waste of time. It's built once by a distro, and then distributed to thousands of users, so that decision ***cannot*** be made at build time.

I have literally never ***once*** seen a project refuse to build any manual pages other than whichever one is the current system locale. Although I suppose there is always a first time for anything.

**Comment by eli-schwartz** [comment]
> Like the idea of a separate i18n repo.
> Not sure how that would work with meson

You can simply add it as a `subproject('labwc-docs-i18n')`, and include it as a `subprojects/labwc-docs-i18n.wrap` file describing how to acquire it.

You can publish Github Releases manually uploaded attachments using `meson dist --include-subprojects` to create suitable release tarballs. These will contain the i18n repo inside, so that people building the release are guaranteed to get the same version that was used to generate the release, and without triggering network sandbox violations.

**Comment by johanmalm** [comment]
@01micko Feels like we've moved a long way since this and that we should close this.
