### ISSUE TITLE
how to run multiple commands at once in the labwc menu

### ISSUE THREAD

**Issue by Parmjot-Singh** [labwc/labwc#275]
I want to run;
`swaylock -f -e -i /usr/share/backgrounds/odin.jpg && sudo systemctl suspend`
As an option in my menu, but it doesn't want to run, because of the `&&`.
It spits out this error:
`
[hexagon@dell ~]$ labwc
Entity: line 1: parser error : xmlParseEntityRef: no name
tion name="Execute"><command>swaylock -f -e -i /usr/share/backgrounds/odin.jpg &
                                                                               ^
Entity: line 1: parser error : xmlParseEntityRef: no name
ion name="Execute"><command>swaylock -f -e -i /usr/share/backgrounds/odin.jpg &&
                                                                               ^
00:00:00.310 [../labwc-0.5.0/src/menu/menu.c:273] xmlParseMemory()
`
If I have two command objects, it only selects the second one, and not the first one. How would I do both commands.
Yes, I have tried putting quotes around it...

**Comment by 01micko** [comment]
Write a script, make it executable, put it in `PATH` (/usr/local/bin or something) and call the script from the menu.

Most menus are only designed for one action/execute string unlike a one liner in the terminal.

**Comment by johanmalm** [comment]
As a general point, you have to escape XML characters (e.g. `&amp;` for `&`)

For commands, we execvp() without `sh -c ""` to avoid a shell wrapper for everything. (https://github.com/labwc/labwc/blob/4ee9f351eaba445158aac9aecb638f96e82656af/src/common/spawn.c#L15)

I think it's safer that way too and follows XDG recommendations  (https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s07.html)

I've not tried it, but you might be able to write it like `sh -c "A && B"` or `sh -c "A || B"` where A and B are your respective commands.

Again, can't remember and not tried it, but could you not specify multiple `<action></action>`. If not, we ought to consider implementing.

**Comment by Consolatis** [comment]
> Again, can't remember and not tried it, but could you not specify multiple `<action></action>`. If not, we ought to consider implementing.

Just tested with current master and it works. An entry like
```xml
  <item label="Calculators">
    <action name="Execute"><command>galculator</command></action>
    <action name="Execute"><command>xcalc</command></action>
  </item>
```
indeed spawns both calculators for me.

It is not the same as using `galculator && xcalc` though as they are different processes without any dependency on each other.
To archive that create an own script like @01micko suggested.
