### ISSUE TITLE
Generated menu from labwc-menu-gnome3 crash labwc.

### ISSUE THREAD

**Issue by ahmadraniri1994** [labwc/labwc#276]
Hi, I realize when I add generated menu from labwc-menu-gnome3 will crash labwc when I click desktop wallpaper, I kick out into TTY because of it.
Os : Debian.
Labwc latest master.
N.B : the previous versions seems fine with generated menu.

**Comment by johanmalm** [comment]
Please could you post the menu.xml that causes a crash.

Could you also post “labwc -d 2>log”

**Comment by ahmadraniri1994** [comment]
[menu.xml.txt](https://github.com/labwc/labwc/files/8249379/menu.xml.txt)
Here the xml file that causes crash. I'll soon post the output of "labwc -d 2>log".

**Comment by ahmadraniri1994** [comment]
[labwc.log](https://github.com/labwc/labwc/files/8249522/labwc.log)
That's the output of "labwc -d" instead of "labwc -d 2>log", because "labwc -d 2>log" just gives one line "aborted" and I think that's not gonna help. Fyi I use the exact format for menu.xml on labwc's archlinux and it's just fine. Thanks for the help.

**Comment by ahmadraniri1994** [comment]
I figured it out, finally. The genereated menu have some mess up parts.

**Comment by Consolatis** [comment]
We should likely still figure out why its causing a crash though.

Btw: I love those unicode icons!
```
  <item label="🌏 Web browser">
    <action name="Execute"><command>qutebrowser</command></action>
  </item>
  <item label=" Explorer">
    <action name="Execute"><command>pcmanfm</command></action>
  </item>
  <item label="🔧 Tweaks">
    <action name="Execute"><command>labwc-tweaks</command></action>
  </item>
  <item label=" Terminal">
    <action name="Execute"><command>env TERM=xterm-256color term</command></action>
  </item>
  <item label=" Reconfigure">
    <action name="Reconfigure"></action>
  </item>
  <item label=" Exit">
    <action name="Exit"></action>
  </item>
  <item label=" Wlogout">
    <action name="Execute"><command>wlogout -p layer-shell</command></action>
  </item>
```
Most of them aren't rendered correctly in my browser but are fine in Pluma / console / labwc.

**Comment by ahmadraniri1994** [comment]
@Consolatis @johanmalm I'll post the fixed menu.xml soon.

**Comment by ahmadraniri1994** [comment]
[menu-fixed.xml.txt](https://github.com/labwc/labwc/files/8251226/menu-fixed.xml.txt)
That's my latest menu.xml , no more crash anymore. I'm not sure which part I removed or changed.

**Comment by Consolatis** [comment]
@ahmadraniri1994 thank you. I can reproduce the crash using your menu.xml file.
