### ISSUE TITLE
When using wapanel some surfaces do not receive cursor-button

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#278]
When using https://github.com/Firstbober/wapanel some areas do not receive cursor-button.

Do we need  to create nodes for layer-shell subsurfaces so that `desktop_node_and_view_at()` returns the correct node/surface?

The same issue has been observed with the gkt-layer-shell popup plus/minus buttons

**Comment by Consolatis** [comment]
The gtk-layer-demo issue with the `+` and `-` buttons for margin also happens for v0.5.

**Comment by Consolatis** [comment]
The focus is now shifted to 0.6 / latest master branch, thus: closing again.
