### ISSUE TITLE
Changing TTY sometimes closes all running clients

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#281]
While running 4ee9f351eaba445158aac9aecb638f96e82656af, but this has been observable for quite some time (weeks-months at least).

I haven't been able to track down the exact conditions under which this happens (is it on change to a console VT, change back to labwc, what other conditions are required, etc.).

**Comment by 01micko** [comment]
Interesting that my input was dead after doing a remote backtrace - possibly related. Couldn't change VT via local or remote.

Relevant discussion - https://github.com/labwc/labwc/issues/194#issuecomment-1007276587

**Comment by Consolatis** [comment]
Does this still happen with current master or the latest v0.5 branch?

**Comment by 01micko** [comment]
Yes, hit Ctrl-F2 and then tried to switch back but lost input. Should have tried to plug in a keyboard but interestingly, events from the power button were picked up and soft powered down, so probably good that I didn't plug in a keyboard.

**Comment by bi4k8** [comment]
I haven't been able to reproduce this in a long time.

**Comment by Consolatis** [comment]
Alright, will then close this for now. If it still happens just leave a comment and we'll reopen.
