### ISSUE TITLE
Alt-tab switcher shown on only one output

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#283]
In `master` (with the scene-graph changes), the Alt-Tab window switcher is shown on only one output, near the top-left corner.
In `v0.5`, it was centered and was shown on all outputs.

I personally preferred the `v0.5` behavior.

**Comment by johanmalm** [comment]
Sorry, yes that's me just not having gotten around to it yet following the scene-graph refactoring.
Agree - it should be center aligned and on both outputs.

**Comment by bi4k8** [comment]
I believe window borders during alt-tab are also missing post-scene-graph.
