### ISSUE TITLE
[feature request] virtual keyboard support.

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#286]
Needed? Probably not. Nice to have? Certainly one day.

https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/protocol/virtual-keyboard-unstable-v1.xml

**Comment by Consolatis** [comment]
same for virtual pointer. Both would be nice to extend labwc with a virtual screen which can be controlled by a VNC client via wayvnc.

**Comment by fictitiousexistence** [comment]
Unable to use "wtype" program. Get the error message "Compositor does not support the virtual keyboard protocol". 

Am able to use ydotool but it doesn't work properly for certain characters.

**Comment by johanmalm** [comment]
Implemented by PR #570
