### ISSUE TITLE
[dumb question] Starting xwayland

### ISSUE THREAD

**Issue by ignition-ctrl** [labwc/labwc#287]
I compiled labwc and am really enjoying so far as I migrated from Openbox. However, I would like to start xwayland in order to still use some x applications (like some appimages or rofi). I don't understand how to start labwc with xwayland or how to start it within a running instance. Probably a simple answer but I can't find it on the internet or the man pages. Sorry for the dumb question.

**Comment by johanmalm** [comment]
It build with xwayland by default, so you should just be able to run x applications.
Does rofi not work?
Have you built it yourself? If not, what distro are you using?

**Comment by ignition-ctrl** [comment]
Sorry, thought I mentioned. I compiled it myself on Linux Mint 20.2. I have xwayland installed according to apt

**Comment by ignition-ctrl** [comment]
Recompiling and after meson build noticed I don't have the right dependencies for the xwayland backend. My fault. I'll compile xwayland and see what happens

**Comment by johanmalm** [comment]
Okay. Once you've compiled you should just be able to run xwayland apps without doing anything. For example `labwc -s xterm` or `labwc -s leafpad`

**Comment by ignition-ctrl** [comment]
Recompiled with xwayland, running perfectly, thank you.
