### ISSUE TITLE
1px top and right gap when Chromium is maximized (client-side decorations)

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#292]
Normally there is no gap surrounding windows, but in labwc 0.5.0, Chromium with CSD has a 1px gap on the top and on the right.
![image](https://user-images.githubusercontent.com/45886986/161854339-83872577-c2da-4522-b207-7c271678df82.png)
Becomes very noticeable when a title bar is placed behind it and some pixels from the letters are visible

**Comment by acoolstraw** [comment]
Continues to happen when a video is full screen, quite obvious when the background is white

**Comment by acoolstraw** [comment]
Doesn't appear to happen anymore after I reinstalled labwc and system title bars and borders off and on. Weird.

**Comment by johanmalm** [comment]
Maybe it had got out of sync with system libraries if you built it yourself?
Anyway, that’s good news. Shout if it cones back.
