### ISSUE TITLE
Add support for waybar sway/socket

### ISSUE THREAD

**Issue by s3rj1k** [labwc/labwc#293]
Currently some of waybar modules does not work as they require sway socket to function.

```
[2022-04-06 14:57:30.518] [warning] module sway/workspaces: Disabling module "sway/workspaces", Socket path is empty
[2022-04-06 14:57:30.522] [warning] module sway/mode: Disabling module "sway/mode", Socket path is empty
[2022-04-06 14:57:30.527] [warning] module sway/window: Disabling module "sway/window", Socket path is empty
[2022-04-06 14:57:30.535] [warning] module sway/language: Disabling module "sway/language", Socket path is empty
```

**Comment by Consolatis** [comment]
https://github.com/labwc/labwc-acceptance-criteria#31-ipc

> The labwc devs do not intend to implement any custom IPC or Wayland protocols, even if it's sometimes tempting to solve a short term problems.
> 
> So, IPC will only be through [wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols) and [wlr-protocols](https://gitlab.freedesktop.org/wlroots/wlr-protocols); and SIGHUP if you want to count that.
>
> The reason for this is that we believe that custom IPCs and Wayland protocols create a fragmentation that hinders general Wayland adoption.
>
> Where current protocols are not sufficient, we would rather work with upstream and the wider eco-system to plug any gaps.
>
> See issues #128, #190

**Comment by s3rj1k** [comment]
@Consolatis Ok, so is there a workaround to use sway/waybar specific modules in labwc?

**Comment by Consolatis** [comment]
Depending on the module there might be. I don't use waybar so I am not sure what those modules do.
- `Workspace`: won't work anyway because labwc doesn't yet support workspaces (#40)
- `Mode`: If that one is about display modes it should be possible to replace it's internals by wayland/wlroots protocols as shown in `wdisplays` or `wlr-randr`
- `Window`: If that module is about window management the wlroots [foreign-toplevel-protocol](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml) should be used, see for example [sfwbar](https://github.com/LBCrion/sfwbar)
- `Language`: Not sure if there is a wayland protocol for showing / changing the layout

**Comment by s3rj1k** [comment]
@Consolatis Maybe I am missing some log entries, but basically I am talking about two modules, one that provides currently selected language (xkb in Xorg) and second one is for getting a list of open applications (taskbar).

**Comment by s3rj1k** [comment]
If there is any chance of getting above information from labwc and it's a matter of supporting this in waybar, it will be good to know, at least a possibility to openup an issue with waybar to add support already sounds good.

**Comment by Consolatis** [comment]
A tasklist (and the possibility to switch / minimize / maximize / close applications) should work for any panel that implements the foreign-toplevel-management protocol.
Regarding the language/layout I simply don't know if there is support in some wayland/wlroots protocol to 1) show the current layout and 2) change it.

**Comment by s3rj1k** [comment]
So taskbar module in waybar is indeed uses foreign-toplevel-management protocol, this is good.
https://github.com/Alexays/Waybar/wiki/Module:-Taskbar

**Comment by s3rj1k** [comment]
Waybar language module is Sway specific: https://github.com/Alexays/Waybar/wiki/Module:-Language :(

**Comment by s3rj1k** [comment]
So how we can hack something to get basic language information out of labwc? Basically this is https://github.com/labwc/labwc/issues/190 question

**Comment by Consolatis** [comment]
#236 might help depending on your usecase. Personally I never used that feature so I never really investigated the whole issue.

**Comment by s3rj1k** [comment]
@Consolatis Thanks, added a question to one of more relevant issues about xkb.
