### ISSUE TITLE
Client window position wrong when maximized (with CSDs enabled)

### ISSUE THREAD

**Issue by dnkl** [labwc/labwc#296]
Some clients are positioned wrong when maximized, when CSDs have been enabled (`<decoration>client</decoration>`):

![alacritty-in-labwc](https://user-images.githubusercontent.com/14031526/163667721-87ffa4a0-f76d-42cf-bd7a-604b27c41495.png)

In the screenshot above, we see (the bottom of) Alacritty in a nested labwc (labwc is running with its Wayland backend inside River). See how there's an empty area between alacritty's bottom border, and labwc's bottom border? Same thing on the right side. Furthermore, though not seen in the screenshot, the CSD's **titlebar** is **not** visible at all (it should be).

Foot has the same issue.

It looks like labwc simply anchors the XDG toplevel's upper left corner to the output's (0,0) coordinate, without taking the window geometry into account.

Both Alacritty and foot implements CSDs using sub-surfaces. The titlebar, and the left border is positioned using **negative** coordinates. This is also reflected in the client's call to `xdg_set_window_geometry()`.

https://wayland.app/protocols/xdg-shell#xdg_surface:request:set_window_geometry:

> When maintaining a position, the compositor should treat the (x, y) coordinate of the window geometry as the top left corner of the window. A client changing the (x, y) window geometry coordinate should in general not alter the position of the window.

**Comment by johanmalm** [comment]
Not sure. Will investigate.

Alacritty shows CSD for me. Foot doesn't. Both maximize fine (without any gaps around them).
I've just realised though that view_move_to_edge() doesn't work correctly with `<decoration>client</decoration>`

We use padding/margin for xdg/xwayland-shell respectively. See https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/include/labwc.h#L307

Maybe we've implemented padding/margin wrong... I've mostly tried with GTK + Qt + some xwayland apps.
For example: 
- https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/src/view.c#L389
- https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/src/xdg.c#L46

We've done significant refactoring recently to use the wlroots scene-graph API. Does it work as expected with 0.5.1? It does for me. If it does for you, it might be some of the wlr_scene_node_set_position() calls that haven't been done right https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/src/xdg.c#L65

**Comment by dnkl** [comment]
Ah, sorry, forgot to mention I'm testing with labwc-0.5.1. My bad.

Alacritty is 0.10.1
Foot is latest master, but version doesn't matter here.

> Alacritty shows CSD for me. Foot doesn't. Both maximize fine (without any gaps around them).

Not sure exactly what Alacritty does, but foot has a setting, `[csd].preferred = client|server`. It will use that in the initial call to `zxdg_toplevel_decoration_v1_set_mode()`. The default is `server`. It would appear labwc replies with `ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE` even though I've set `<decoration>client</decoration>`. Changing `[csd].perferred = client` in `foot.ini` (or on the command line, using the `-o` option) enables CSD on foot as well.

> Does it work as expected with 0.5.1 (which is scene-graph free)? It does for me. If it does for you, it might be some of the wlr_scene_node_set_position() calls that haven't been done right

Nope. But let me see if I can build and test latest labwc as well.

**Comment by dnkl** [comment]
Seems to work fine on latest master! Sorry for the noise...

It'd still be nice to figure out the CSD issue with foot, but I guess that's a separate issue. Want me to open one?

**Comment by Consolatis** [comment]
> Seems to work fine on latest master! Sorry for the noise...

No need to feel sorry, 0.5.1 is intended as a stable branch and as such we should likely figure out what is going on there as well.
Thanks for bringing this up.

**Comment by Consolatis** [comment]
As this should be fixed on 0.6 and the master branch I'll close this issue.

0.5. will not receive further support unless its a really minor fix.
