### ISSUE TITLE
Inconsistency between CSD/SSD reported to client, and actually rendered

### ISSUE THREAD

**Issue by dnkl** [labwc/labwc#297]
As mentioned in https://github.com/labwc/labwc/issues/296#issuecomment-1100699231, setting `<decoration>client</decoration>` doesn't actually enable CSDs in foot, but does in Alacritty. What gives?

The difference is how these two applications use the xdg-decoraction protocol. This protocol has two methods: `set_mode()` and `unset_mode()`.

Alacritty uses `unset_mode()`, while foot uses `set_mode()`.

`unset_mode()`:

> Unset the toplevel surface decoration mode. This informs the compositor that the client doesn't prefer a particular decoration mode.

`set_mode()`:

> Set the toplevel surface decoration mode. This informs the compositor that the client prefers the provided decoration mode 
After requesting a decoration mode, the compositor will respond by emitting an xdg_surface.configure event. The client should then update its content, drawing it without decorations if the received mode is server-side decorations. The client must also acknowledge the configure when committing the new content (see xdg_surface.ack_configure).
> 
> **The compositor can decide not to use the client's mode and enforce a different mode instead.**

Key words here are **prefers** and **can enforce a different mode instead**.

What I suspect is happening is that labwc receives foot's `set_mode()` request, where foot says it **prefers** SSDs, and labwc replies with "sure ok, no problem" (i.e. foot receives `ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE` in the xdg toplevel decoration `configure` event - this has been verified, see attached ` WAYLAND_DEBUG` logs).

But when rendering the foot window, labwc just looks at its `<decoration>` setting and decides to not draw any SSDs.

`WAYLAND_DEBUG` logs (`grep decoration`  - full logs are attached):

Alacritty
```
[1604551.033] wl_registry@2.global(15, "zxdg_decoration_manager_v1", 1)
[1604551.049]  -> wl_registry@2.bind(15, "zxdg_decoration_manager_v1", 1, new id [unknown]@8)
[1604551.068] wl_registry@2.global(16, "org_kde_kwin_server_decoration_manager", 1)
[1604607.326]  -> zxdg_decoration_manager_v1@8.get_toplevel_decoration(new id zxdg_toplevel_decoration_v1@22, xdg_toplevel@19)
[1604607.352]  -> zxdg_toplevel_decoration_v1@22.unset_mode()
[1604615.769] zxdg_toplevel_decoration_v1@22.configure(1)
[1604621.488] wl_registry@38.global(15, "zxdg_decoration_manager_v1", 1)
[1604621.501] wl_registry@38.global(16, "org_kde_kwin_server_decoration_manager", 1)
[1604728.868] wl_registry@39.global(15, "zxdg_decoration_manager_v1", 1)
[1604728.875] wl_registry@39.global(16, "org_kde_kwin_server_decoration_manager", 1)
```

Foot
```
[1614107.530] wl_registry@2.global(15, "zxdg_decoration_manager_v1", 1)
[1614107.542]  -> wl_registry@2.bind(15, "zxdg_decoration_manager_v1", 1, new id [unknown]@14)
[1614107.558] wl_registry@2.global(16, "org_kde_kwin_server_decoration_manager", 1)
[1614110.118]  -> zxdg_decoration_manager_v1@14.get_toplevel_decoration(new id zxdg_toplevel_decoration_v1@23, xdg_toplevel@22)
info: wayland.c:1453: requesting SSD decorations
[1614110.139]  -> zxdg_toplevel_decoration_v1@23.set_mode(2)
[1614181.568] zxdg_toplevel_decoration_v1@23.configure(2)
info: wayland.c:818: using SSD decorations
[1614752.888]  -> zxdg_toplevel_decoration_v1@23.destroy()
[1614754.351]  -> zxdg_decoration_manager_v1@14.destroy()
```

[foot.log](https://github.com/labwc/labwc/files/8500334/foot.log)
[alacritty.log](https://github.com/labwc/labwc/files/8500335/alacritty.log)

labwc: 0.5.0-100-g6b4d9b9
Alacritty: 0.10.1
Foot: latest master

**Comment by johanmalm** [comment]
Thanks for raising this. I'll take some advice from the other devs about the best approach here.
I think I prefer the compositor to decide for simplicity and for a consistent clook. Not sure if many users really care about letting the client decide??

Looks like the the ssd is rendered depending on the `view->ssd.enabled` flag (which is good).
https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/src/ssd/ssd.c#L169

But that boolean is set on map https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/src/xdg.c#L320
which interestingly happens after the xdg-toplevel-decoration-configure event which triggers this function
https://github.com/labwc/labwc/blob/6b4d9b9383f76c8a1bb26fbdf0a3a7b79df590a3/src/view.c#L304

So, it should be easy to sort out the logic - we just need to work out what behavior we want. I'll give people a few days to comment and will reach out to a couple on IRC

**Comment by dnkl** [comment]
> Not sure if many users really care about letting the client decide??

In the compositors I have tested so far, the compositor always decides. I.e. foot's request is typically ignored.

Without having giving it much thought; if the compositor allows **its** preferred decoration mode to be unconfigured/unset, _then_ it could (should?) let the client choose. But if the user has configured a specific mode in the compositor, that's what should be used, imho.

**Comment by Consolatis** [comment]
> if the user has configured a specific mode in the compositor, that's what should be used, imho.

Agreed, and in the case you describe above, labwc should respond to use CSD even if the client would prefer SSD.
So this sounds like a bug in labwc.

> if the compositor allows its preferred decoration mode to be unconfigured/unset, then it could (should?) let the client choose.

AFAIR we have `client` and `server` but maybe we could have a third option like `unspec` (or some better word for it) for always respecting the requests of the client?

Personally, I don't really care as long as I can force the clients to use SSD.

**Comment by Consolatis** [comment]
> > if the user has configured a specific mode in the compositor, that's what should be used, imho.
>
> Agreed, and in the case you describe above, labwc should respond to use CSD even if the client would prefer SSD.

The issue here is that we can't actually know if the client even has any kind of CSD implementation.
So if we really were to overwrite the client request for server side decorations with client ones we might end up with no decorations at all (which is a different case from what this issue is about but still valid).

> But when rendering the foot window, labwc just looks at its `<decoration>` setting and decides to not draw any SSDs.

#838 should finally fix that. If labwc is configured to use `client` side decorations and foot is configured to prefer client decorations as well it will use it.
If foot is configured to prefer server side decorations it will use those even if labwc is configured to use `client` ones. If that is not the desired behavior I think the right solution to state that preferences (e.g. `no preference`) would be for foot to indeed use `unset_mode()` in which case labwc would use whatever the user configured labwc to use. If the protocol would allow a client to also declare that it doesn't support any client side decorations we could potentially use the other variant and completely ignore what the application prefers but without that knowledge honoring the client side preferences seems like the best choice.
