### ISSUE TITLE
latest master focus issue

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#304]
Just built and installed latest.

I had geany open maximised on one output and vivaldi-snapshot maximised on the other and the cursor was confused.

Had a google search box with blinking ibeam (text) cursor and keyboard events were being sent to geany until I minimised geany.

**Comment by Consolatis** [comment]
There was a change recently about mouse press events in https://github.com/labwc/labwc/commit/3d337857b7b0edb76083b4e6a7e15abfb288182a
(added break statement, reversed event ordering) but I didn't investigate if that one is actually related to this issue here.

**Comment by johanmalm** [comment]
:fearful:

**Comment by 01micko** [comment]
Try in about 12 hours.

**Comment by 01micko** [comment]
Yep that fixes it.

That isn't the only anomaly though. It persists with that reversion. I'll open a separate issue.

**Comment by Consolatis** [comment]
Thanks for reporting and testing :)
