### ISSUE TITLE
Maximised window resizes very small when dragging app across outputs.

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#305]
NOTE: app has to be started maximised. If not, then it's maximised, it reverts to the size it was before maximised.

Seems only affecting pure wayland apps.

wayland: Tried, geany, vivaldi-snapshot, firefox - all show small window

Xwayland: Tried gimp and vivaldi-stable and no problem.

Just guessing, size is about 600x200. My displays are 1920x1080.

**Comment by Consolatis** [comment]
Dragging a maximized window will automatically un-maximize it (you could release it at the top edge of the target and it should automatically maximize again).

So to clarify: Issue is when starting an wayland native application in maximized mode (like `foot -m`) and then un-maximizing it (be it via dragging or double click on the title bar or just using the maximize button), it becomes a very small window?

**Comment by 01micko** [comment]
No the drag operation makes it small... and I just tried foot -m

![20220427_05h32m58s_grim](https://user-images.githubusercontent.com/1019119/165378227-9d66ddd9-aff1-4928-afdb-61a88829ff8f.png)

__But wait__, it's early morning here and I just realised I was testing 0.5.1! So the bug has been there for quite a while and I only just discovered it!

**Comment by johanmalm** [comment]
Should be done.  Have tested, but as always... if anyone has time to double-check that is welcome.

**Comment by 01micko** [comment]
Fixed for me. Thanks :smile:
