### ISSUE TITLE
Certain apps snap to corner and refuse to be dragged out

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#309]
Certain apps (Chromium, VS Code/Electron, VLC, qBittorrent) snap to the top left corner, with the center of the app in the corner. They refuse to be dragged out, as they just snap back into place. The only way to return them to normal behavior is to tile them (Super + Arrow Key) and sometimes it only works if you tile it horizontally (arrow down). Thought I'd make an issue about it even though I've discussed this on IRC with @Consolatis

**Comment by Consolatis** [comment]
This bug is really nasty. It should "only" happen for XWayland applications and you should be able to "unstuck" the window with `Alt-Mouse_Left` to drag the window somewhere else.

I might have some time this WE to try to fix it but can't really promise anything yet.

**Comment by acoolstraw** [comment]
Alt-Mouse_Left doesn't seem to work, just goes right back in place.

**Comment by johanmalm** [comment]
I think `src/resistance.c` is linked to this.

Do you get the issue if you set the following in `rc.xml`?

```
  <resistance>
    <screenEdgeStrength>0</screenEdgeStrength>
  </resistance>
```

In `src/cursor.c:177`, if I add the following fprintf()s I sometimes get different values even when I'm resizing a long way from any edges.

```
	fprintf(stderr, "new_view_geo.width=%d, ", new_view_geo.width);
	resistance_resize_apply(view, &new_view_geo);
	fprintf(stderr, "%d\n", new_view_geo.width);
```

I've not investigated further, but that seems good lead to me.

**Comment by 01micko** [comment]
I was seeing this but in latest it doesn't seem to happen.

**Comment by johanmalm** [comment]
I cannot reproduce this, so find it difficult to look into. I've tried with qbittorrent, chromium and vlc (running as xwayland apps) but they all behave as I expect them to.

@acoolstraw could you help with some more information.

1. Does it still happen with the latest `master`?
2. Does it happen with both xwayland and xdg-shell applications?
3. What is it you're doing when they center on the top-left corner? Are you dragging them around with the mouse, or using some keybind? 
4. Can you consistently re-produce it? Are you able to describe the steps you take for me to try to re-produce it?
5. Does it still happen if you set `<screenEdgeResistance>` to 0 as I described above?

**Comment by acoolstraw** [comment]
I will try the latest master as I have a slightly old version. It seems to happen with xwayland applications, I'm not sure if xdg-shell ones are affected. Probably not. I usually drag them or click them, it happens very suddenly and randomly so I'm not sure what exactly triggers it.

**Comment by 01micko** [comment]
Try latest :^) @acoolstraw

**Comment by acoolstraw** [comment]
I tried latest, and I also edited `<screenEgeResistance>`, and it doesn't seem to happen anymore, but I'm not entirely sure if it's gone... :thinking:

**Comment by johanmalm** [comment]
https://github.com/labwc/labwc/commit/87a64b64fa956c9b968be3a7589d12390e32f7fa might have solved this.

**Comment by acoolstraw** [comment]
Seems to be fixed
