### ISSUE TITLE
First turn off the external screen and then turn it on, the program crashes

### ISSUE THREAD

**Issue by fakeczg** [labwc/labwc#312]
When we use wlr-randr to turn off the external screen first, and then turn it on, the program crashes！

![image](https://user-images.githubusercontent.com/54363314/165873090-f4546855-b3ce-496f-87bc-65961082ddde.png)

**Comment by Consolatis** [comment]
First of all, thanks for your bug report.

Would be great if you could test #315.

**Comment by fakeczg** [comment]
> First of all, thanks for your bug report.
> 
> Would be great if you could test if #315 fixes this issue for you.
I just tested it and it's ok！

![image](https://user-images.githubusercontent.com/54363314/166127563-f3b2ff65-bc89-4b53-af50-59b5f8125ef3.png)
