### ISSUE TITLE
Tap to click?

### ISSUE THREAD

**Issue by Camiropan** [labwc/labwc#319]
firstly, thanks for labwc. I'm a big fan!

Is there a way to activate "Tap to click"?

**Comment by johanmalm** [comment]
It would be enabled be default. 

If not, does adding the following to `~/.config/labwc/rc.xml` help?

```
  <libinput>
    <device category="non-touch">
      <tap>yes</tap>
    </device>
  </libinput>
```

**Comment by Camiropan** [comment]
upgrade to v0.5.1 was the solution, thanks!
