### ISSUE TITLE
Alt+Tab dialog does not disappear

### ISSUE THREAD

**Issue by Camiropan** [labwc/labwc#320]
The Alt+Tab dialog doesn't disappear and the only think i can do is switch between the windows in the dialog. 
(Version 5.0)

**Comment by johanmalm** [comment]
Could you try with version 0.5.1
Quite a few bugs were ironed out between 0.5.0 and 0.5.1

```
git clone https://github.com/labwc/labwc
cd labwc
git checkout 0.5.1
meson build
ninja -C build
./build/labwc
```

**Comment by Camiropan** [comment]
in v0.5.1 it works perfect, thanks!
