### ISSUE TITLE
Cannot start labwc on Nvidia machine

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#324]
On Arch Linux, I installed `egl-wayland`, `wlroots-eglstreams-git`, `nvidia`, `labwc-git`, `polkit`. I also installed some other packages that I don't remember.

Edited `/etc/mkinitcpio.conf`: `MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)`

However, when starting `labwc` it says:

```
[backend/backend.c:217] Found 0 GPUs, cannot create backend
[backend/backend.c:386] Failed to open any DRM device
[../labwc/src/server.c:191] unable to create backend
```

Likely pointless to support Nvidia's proprietary drivers because neither does sway or any other compositor, but wondering why this issue occurs

**Comment by Joshua-Ashton** [comment]
> Likely pointless to support Nvidia's proprietary drivers because neither does sway

Being user hostile is bad, actually.

**Comment by acoolstraw** [comment]
Didn't want this to be a "support Nvidia" issue, if that is not what the devs want or have the resources to do.

**Comment by acoolstraw** [comment]
> I will write up a guide about how to use it on NVIDIA tomorrow :)

That'd be great! Is it usable?

**Comment by Joshua-Ashton** [comment]
Yes it is usable.

Turns out you are just missing `nvidia-drm.modeset=1`. I will add this to the readme.

**Comment by acoolstraw** [comment]
Master branch labwc core dumps.

Logs:
https://i.troplo.com/i/5002384dfd2b.txt
https://i.troplo.com/i/1616c971a341.txt

Version: `labwc 0.5.0-136-gfbbe273`
Distro: Arch Linux

Compiled with this command (because wlroots seems to break it on Arch now): `meson --force-fallback-for=wlroots build_master && meson compile -C build_master`

**Comment by acoolstraw** [comment]
```
13:35:26 Consolatis | so if you want to give that a try: go into src/server.c line 285, that should state server->xdg_shell = wlr_xdg_shell_create(server->wl_display);
13:35:34 Consolatis | and change it to server->xdg_shell = wlr_xdg_shell_create(server->wl_display, 2);
```
also core dumps if you do this and build with `wlroots-git`

**Comment by acoolstraw** [comment]
Installing `sway` fixed it, it's likely that I just had no fonts installed
