### ISSUE TITLE
New minor bugfix release from the stable branch: 0.5.2

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#329]
We just released labwc version [0.5.2](https://github.com/labwc/labwc/releases/tag/0.5.2) which depends on wlroots 0.15.1.
This is a minor bugfix release from the stable branch mostly to ease packaging by properly using the system provided wlroots.

If not available labwc will still fall back to the wlroots subproject wrap file and clone / build wlroots 0.15.1.
The fallback can be prevented by using `--wrap-mode=nodownload` for the initial meson setup.

We are very happy to see labwc showing up in some distro user repositories and are grateful to the respective maintainers:
- @narrat (Arch)
- @jbeich (FreeBSD)
- @adcdam (Slackware)

If you have any suggestions or questions regarding packaging feel free to post here.
If you are maintaining labwc for another distro and want to be notified on future releases feel free to post as well.

**Comment by jbeich** [comment]
Can you make future releases appear on [Releases](https://github.com/labwc/labwc/releases) page? I'm currently subscribed via "Watch -> Custom -> Releases" but don't receive notifications unless CC'd directly (like in this issue). Creation of regular tags doesn't trigger notifications.

**Comment by johanmalm** [comment]
Will do. I hadn't realized what the benefit was of creating github-releases. I now do :smile:
