### ISSUE TITLE
Implement screen sharing

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#335]
IMO one of the most critical thing that is missing is the ability to share the screen.

**Comment by Consolatis** [comment]
Screensharing is implemented.

Your application either needs to use the [wlr-screencopy  protocol](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-screencopy-unstable-v1.xml) directly (see for example [wf-recorder](https://github.com/ammen99/wf-recorder)) or the xdg-desktop-portal dbus service.
For the dbus service to work you need pipewire and the [xdg-desktop-portal wlroots backend](https://github.com/emersion/xdg-desktop-portal-wlr) which may or may not be available in your distro repository.
