### ISSUE TITLE
bemenu doesn't render after launching a game

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#336]
If you launch a game (fullscreen), `bemenu-run` doesn't render but functions normally (records keyboard and launches programs). Appears to be unrelated to https://github.com/labwc/labwc/issues/317. Not Nvidia-specific

Games I can confirm it happens with: CSGO, Wreckfest, Veloren, will test more.

Using labwc master branch.

**Comment by Consolatis** [comment]
Just to be clear, it also doesn't render anymore when the game is closed and you have to restart labwc to get it working again?

**Comment by acoolstraw** [comment]
Yes - it works again after a while but I have no idea when or what makes it work again.

**Comment by johanmalm** [comment]
@acoolstraw would you mind doing some detective work on this?
If you can't pin it down, I'll install steam/CSGO to try to reproduce it, but last time my poor old laptop struggled it cope, so not promising.

Things to confirm or try:

1. Can you consistently reproduce it - or is it intermittent?
2. Do you get the same on sway?
3. Could you run bemenu-run from a terminal with `WAYLAND_DEBUG=1 bemenu-run` to see what is happening on the protocol. If you run it with when it's working and when it isn't, can you spot anything different?
4. Run `labwc` nested with `WAYLAND_DEBUG=server` to see what labwc is doing. Again if you could do that with bemenu-run behaving normally and when it isn't.
5. Run bemenu-run from `https://git.sr.ht/~kennylevinsen/wlhax` to get a live view on some info.

**Comment by acoolstraw** [comment]
1. It's pretty consistent - it stops being broken a while after the game is closed, but it always does this when a full screen game is launched. Veloren seems to also trigger this, it's not only CSGO/Steam games. Any full screen game really it seems.
2. I will try to set up sway, but I can't give any promises since I haven't used sway before so it'll take a bit :/
3. I ran that, I'll wait for bemenu-run to start working again and see if anything is different in the logs.
4. Nesting labwc seems to launch things in the original WM? Is this normal?
5. Will do

**Comment by Consolatis** [comment]
I have a feeling that this is related to the now fixed #377.
Is this fixed on the latest master? If not does starting it with `BEMENU_BACKEND=x11`fixes it?

**Comment by johanmalm** [comment]
This is fixed for me. Will close. @acoolstraw if you're able to, could you check and confirm?

**Comment by acoolstraw** [comment]
Fixed
