### ISSUE TITLE
VLC has weird behavior

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#337]
On the master branch, if you launch VLC (running under Xwayland), it first starts out at the bottom right corner, if you maximize it, it moves to somewhere around the top left, and then maximizing it again works normally. This appears to be happening less recently, perhaps due to some commit, or just it being weird.

Also, VLC's player controls appear in the middle of the screen instead of the bottom, and cannot be moved. It also stops appearing after you move your cursor away and move it again, sometimes.

**Comment by acoolstraw** [comment]
VLC behavior appears to have improved, the player controls no longer show up in the middle of the screen, but they still stop reappearing after the first time (when you move your cursor, they should show up, and then fade away, but this only happens the first time you move your cursor)

**Comment by Consolatis** [comment]
Closing for now, feel free to post a comment if this is still an issue and we'll reopen the issue.
