### ISSUE TITLE
Fix url in the build wiki

### ISSUE THREAD

**Issue by AdriandMartin** [labwc/labwc#343]
Replace "johanmalm" with "labwc" in the GitHub's urls of [the Build wiki page](https://github.com/labwc/labwc/wiki/Build). 

Currently, the command to copy is as follows:
```sh
git clone https://github.com/johanmalm/labwc
```

But it should refer to the organization's repository instead of that fork:
```sh
git clone https://github.com/labwc/labwc
```

The wiki's repository is hidden, so I couldn't fork it and change it myself.

**Comment by Consolatis** [comment]
Thanks, I updated the links manually.
I have no idea how the wiki works, I was under the impression everybody could update things on there.

Maybe @johanmalm can shed a light on this. Leaving this issue open for now.

**Comment by AdriandMartin** [comment]
> I've tweaked the settings. Anyone should be able to edit now.

I confirm, now the wiki's edition is available if you're logged into GitHub
