### ISSUE TITLE
Output scaling of SSD buttons / title

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#348]
I don't understand the scene-graph scaling:
![scale_5](https://user-images.githubusercontent.com/35009135/170690751-c4d9c182-4e5d-4096-aa64-4c6a90728c5f.png)

`wlr_scene_rect` gets scaled just fine, so the buttons (and their hover overlays) seem correct.
`wlr_scene_buffer` however.. the SSD title doesn't seem to be touched \*at all\* but the icons on the buttons seem as if they were, for example, replicated to the right (especially visible on the window-menu one on the left).
The rounded corners however, are seemingly scaled correctly as well (which are also `wlr_scene_buffer`).

For the record: titlebar scene node layout
```
                                X     Y        Node
                             ----  ----  ----------------
+-- titlebar.active           290    98  [0xaaaaab42a970]
   +-- rect                   316    98  [0xaaaaab43d110]  title bar between the buttons
      +-- buffer              626   102  [0xaaaaab43eca0]      title
   +-- buffer                 289    97  [0xaaaaab43d1e0]  rounded corner left
      +-- buffer              300   107  [0xaaaaab43d330]      window-menu icon
      +-- rect                290    98  [0xaaaaab43d480]      hover overlay
   +-- rect                   912    98  [0xaaaaab43d550]  usual button
      +-- buffer              921   106  [0xaaaaab43d620]      minimize icon
      +-- rect                912    98  [0xaaaaab43d770]      hover overlay
   +-- rect                   938    98  [0xaaaaab43d840]  usual button
      +-- buffer              947   106  [0xaaaaab43d910]      maximize icon
      +-- rect                938    98  [0xaaaaab43da60]      hover overlay
   +-- buffer                 964    97  [0xaaaaab43db30]  rounded corner right
      +-- buffer              973   106  [0xaaaaab43dc80]      close icon
      +-- rect                964    98  [0xaaaaab43ddd0]      hover overlay
```

Original issue: #289

**Comment by johanmalm** [comment]
Not had a chance to look, but this might be a useful source to compare with
https://github.com/Nefsen402/sway/blob/scene-graph/sway/sway_text_buffer.c

The have a `struct text_buffer_output` and `handle_output_enter()`
I think fundamentally our buffer points to a `cairo_t` which surface should be made bigger the greater the output scale

**Comment by johanmalm** [comment]
On phone, so can’t compile/test/experiment but found this:

https://github.com/labwc/labwc/blob/78dc2ea7feb4e61b64dbc6c26b3de2bc30eb630a/src/theme.c#L357

buffer_create_cairo() takes a scale variable

In theme.c we hard code it to 1
In osd.c we set it to output->scale but don’t change width+height accordingly.

**Comment by Consolatis** [comment]
For a first glance, looks like they are reacting to the max scale as seen by output_enter / output_leave (+ some subpixel stuff). If subpixel setting or max scale changed they are regenerating a wlr_buffer and use `wlr_scene_buffer_set_buffer()` to set the new one.

So it appears wlroots indeed doesn't touch wlr_scene_buffers at all regarding scale changes.
But why are our icons all messed up then? The pixel size seems correct and I'd expect wlr_scene_buffer to not require a `wlr_scene_buffer_set_source_box()` when the dimensions of the backing `wlr_buffer` is equal to what we want to show.

As for actual font rendering, pango seems to support some scale attribute:
https://github.com/Nefsen402/sway/blob/scene-graph/common/pango.c#L75-L80

**Comment by Consolatis** [comment]
> So it appears wlroots indeed doesn't touch wlr_scene_buffers at all regarding scale changes.

This seems wrong. After some further experiments, `wlr_scene_buffers` \*are\* scaled automatically:
![swappy-20220528_133937](https://user-images.githubusercontent.com/35009135/170823900-84f0311c-e12c-4ab2-824f-a7766bb73544.png)

But the font buffer doesn't seem to be scaled correctly for whatever reason and the icons are scaled by duplicating random stuff to the right. Still no clue what is happening there.

**Comment by Consolatis** [comment]
> Some piece of the puzzle is missing.

Hah, finally found it:
![swappy-20220529_180858](https://user-images.githubusercontent.com/35009135/170881911-eb858274-1652-4143-a40a-bc87510bfb11.png)

> I'd expect wlr_scene_buffer to not require a `wlr_scene_buffer_set_source_box()` when the dimensions of the backing wlr_buffer is equal to what we want to show.

Well. that was exactly the issue.

Apparently we have to set the source box even though the backing buffer doesn't change at all.
```c
/**
 * Set the source rectangle describing the region of the buffer which will be
 * sampled to render this node. This allows cropping the buffer.
 *
 * If NULL, the whole buffer is sampled. By default, the source box is NULL.
 */
void wlr_scene_buffer_set_source_box(struct wlr_scene_buffer *scene_buffer,
        const struct wlr_fbox *box);
```
At least the wlroots docs are absolutely not clear on this and I think it is also a bit counter intuitive to have to set the source box for a scene_buffer with a backing buffer that isn't ever changed. And if its changed behind our back I'd expect that part of the code to also set / update the source box.

**Comment by johanmalm** [comment]
> > Some piece of the puzzle is missing.
> 
> Hah, finally found it

Great effort :smile:

Do we need to re-write the xbm parse function to take into account scale, or will the icons scale up fine?

**Comment by Consolatis** [comment]
Regarding the XBM parser I'd say the wlroots scaling result is reasonably fine (especially as the built-in icons are 6x6).
The rounded corners seem fine as well. For the font labels in menu and title we should likely switch to some dynamic font buffer generator eventually.

Left is a scale of 1 and the right one a scale of 2:
![scale_6](https://user-images.githubusercontent.com/35009135/170886641-0c9286a7-90c4-4bb8-b55b-03aabf2ce118.png)

Keep in mind that if somebody wants to have the same visual appearance of two screens with different DPI they could also do it the other way round and set one of the screens to 0.75 for example and let the other be kept at 1. That should likely improve the blurriness.

**Comment by johanmalm** [comment]
Great effort.
Yes we can create font surfaces at scale 2,3...n later.
Maybe a simple solution to support those with HiDPI screens is to create the font surfaces at the scale equal to the greatest output->scale, and then scale down for the other outputs (if that works).
