### ISSUE TITLE
Intellij loses focus while typing

### ISSUE THREAD

**Issue by skerit** [labwc/labwc#352]
While I'm typing in Intellij IDEA, the window focus seems to be lost.
Anything I type further will not be registered by the application (not even application specific shortcuts) until I manually give the application focus again.

I'm not sure where the issue lies: Labwc, XWayland, Java, ...
There's a post on the Jetbrains forum regarding a similar bug on Sway: https://youtrack.jetbrains.com/issue/JBR-1822
But there they were just unable to type in new text, arrow keys and such still worked.
Plus that specific issue should have been patched in wlroots by now?

I tried some of the workarounds mentioned in there, but nothing seems to help.

**Comment by johanmalm** [comment]
Maybe we need to patch xwayland.c with this code?

https://github.com/swaywm/sway/blob/a535ed310f756a57129683c9d81c6a65e8338977/sway/desktop/xwayland.c#L108-L113

It does specifically refer to jetbrains in the sway code.

Are you a coder? Are you happy to have a go?

**Comment by Consolatis** [comment]
I wonder if this is related to #226

**Comment by johanmalm** [comment]
Thanks for testing/confirming. Much appreciated.

**Comment by johanmalm** [comment]
Just wonder, did the issue apply to both `0.5.2` and `master`?

**Comment by skerit** [comment]
@johanmalm Oops, I didn't even think to test that first. But I gave it a go now:

I built the commit before this change, commit e87aa19066e5dae6ddfe1f4c5d4537474083436a, and the problem was indeed still there.

I actually couldn't build the commit tagged with 0.5.2

In the mean time I've discovered a new Idea bug, I'll open a new issue for that.
