### ISSUE TITLE
Shift - Numbers keybinds do not work

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#365]
<keybind key="S-1">
      <action name="Execute"><command>foot</command></action>
    </keybind>

Shift-1 won't open foot, it will just write !

As a workaround using the keysym code does work, for example

    <keybind key="S-0x21">
      <action name="Execute"><command>foot</command></action>
    </keybind>

Shift-1 will open foot

**Comment by johanmalm** [comment]
I think this relates to the difference between raw and translated keysyms/modifiers.

Sway deals with both. 
https://github.com/swaywm/sway/blob/e5728052b59fb5b476c78c9f18b812a85d7f4503/sway/input/keyboard.c#L341-L347

The way labwc currently handles it is simpler and possibly more explicit. Happy to consider approaches here. Suggest starting with `user requirement` and then assessing the effort/maintainability of implementing.

**Comment by Consolatis** [comment]
> I'm not sure the case is so convincing for labwc

`S-1` will  interfere with usual application usage. However, this is also relevant to keybindings like `W-S-1` or  `A-S-1` which in my opinion are completely valid keybinds for a compositor and allow to directly address something like workspaces without removing the ability to use `C-1` or `A-1` for applications.

I am not sure how this could be implemented correctly though, I'd think that `0x21` a.k.a. `33` a.k.a `!` is depended on some keyboard layout settings.

**Comment by heroin-moose** [comment]
W-S-[0-9] works in sway, for example:

```
# Move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
```

**Comment by Consolatis** [comment]
In the meantime you can generate your own bindings if required via
`python3 -c "print('0x%x' % ord('>'))"`
Just replace `>` with whatever character shows up when you do a `S-key`

**Comment by Consolatis** [comment]
Should be fixed by
- #997

Note: the workaround keybinds will have preference over raw ones, e.g. `W-S-0x21` would get used if defined and `W-S-1` would not be used at all. Thus suggesting to replace all workaround keybinds with proper ones. Feel free to open a new issue if there are any further issues with the keybinds.
