### ISSUE TITLE
Flameshot loses focus

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#368]
Continuing from https://github.com/flameshot-org/flameshot/issues/2642

**Comment by johanmalm** [comment]
Looks like a Qt app. Are you running with wayland or X11 backend?

Does this commit help? https://github.com/labwc/labwc/commit/96315def57ee9206dad17b5777e5b1ff6af32ffe

On labwc I get `QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)`. Looks like swaybar handles that on sway. How did you overcome - i.e. what panel are you using?

**Comment by acoolstraw** [comment]
I don't use any panel right now.  I think I may be running with X11, but I have `QT_QPA_PLATFORM=wayland` as an environment variable

**Comment by Consolatis** [comment]
After some testing of @Flrian via IRC this seems to work fine when lying about the desktop environment via `XDG_CURRENT_DESKTOP=sway` (instead of `wlroots`). Closing for now, feel free to shout if this is still an issue.
