### ISSUE TITLE
New windows are not centered with HiDPI screens

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#376]
Hi,

I have the following `kanshi` config:

```
profile main {
    output DP-3 enable scale 2
}
```

With scale=1 new windows spawn in the middle of the screen, however with scale=2 they spawn in the upper left corner and partially off the screen.

**Comment by Consolatis** [comment]
Thanks for the report. It sounds like it should be an easy fix by just using the scaled coordinates for initial positioning.
Will cook something up and report back.

**Comment by Consolatis** [comment]
Should be fixed by #378
