### ISSUE TITLE
Statusbar remains hidden after exiting from a fullscreen application

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#377]
The following scenario does not work correctly:

1. Start labwc
2. Start waybar
3. Run mpv -fs /tmp/video.mpg
4. Press `q` in mpv

At this point waybar is hidden and will remain hidden until some other application will enter and leave fullscreen properly.

**Comment by Consolatis** [comment]
I tried to reproduce this but failed for a nested labwc session with latest master and latest v0.5 branch.
Tested using an old waybar version and the latest waybar master, in both cases the panel was still visible after pressing `q` to exit the mpv fullscreen.

Would you mind testing if this also happens for you if you start labwc nested on top of labwc?

**Comment by heroin-moose** [comment]
Hmm... it happens on workspace branch of @Consolatis fork. I'll try with nested labwc and I'll try clean master.

**Comment by Consolatis** [comment]
I can now reproduce it on latest master, thanks to @Flrian via IRC: if waybar is configure to use the top layer, it is invisible after quitting mpv.
Short term workaround: using the bottom layer + exclusive zone instead of the top layer.

**Comment by Consolatis** [comment]
I suspect this one to be the culprit:
https://github.com/labwc/labwc/blob/138b1852c1878786fc42f975de1df93b331b7856/src/view.c#L400-L404

If a view is destroy we should likely check if it was in fullscreen and then re-enable the top layer.

**Comment by johanmalm** [comment]
I can reproduce by putting `"layer": "top",` in `~/.config/waybar/config`

@Consolatis you proposal fixes it :smile:
