### ISSUE TITLE
grim does not work on latest master

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#383]
```
$ grim
failed to copy output DP-1
```
I have NVIDIA proprietary driver, however.

P.S. It works in nested labwc.

**Comment by acoolstraw** [comment]
why is this closed? I get this issue too and I'm just completely at a loss as to why it's happening

**Comment by Consolatis** [comment]
Also had some issues with latest wlroots master regarding screenshots but my GPU drivers are pretty much broken right now as well so it could have been a coincidence. 

For me it was accompanied with following log message: `No free output buffer slot`.
I can't reproduce it anymore though after downgrading and then again upgrading my GPU drivers and reinstalling various other parts of mesa / libdrm / libgbm.

Maybe `labwc -d 2>/tmp/labwc.log` on the non-nvidia system could shed some light on this.

**Comment by acoolstraw** [comment]
will do. I thought it was something wrong with my config - after installing Void it also happened, but if others have gotten this it's either something with wlroots/drivers/labwc or just same config error

**Comment by heroin-moose** [comment]
I was thinking it was my NVIDIA =/

**Comment by heroin-moose** [comment]
> For me it was accompanied with following wlroots log message: No free output buffer slot.

I have the similar messages from `mako` from time to time:

```
no buffer available
```

**Comment by Consolatis** [comment]
> I have the similar messages from `mako` from time to time:
> ```
>no buffer available
>```
> after that it renders blurry notification and stops responding. Dunno if related, but still.

That is an issue I had as well  but that was before I started seeing the screencopy issue so I think its unrelated. I could fix this one by building mako from master instead of using the version shipped by the Debian testing repos.

**Comment by heroin-moose** [comment]
Hmmm.

This is weird:

```
$ pacman -Q mako
mako 1.6-3

$ git -P log --oneline v1.6..master
0d95a16 (HEAD -> master, origin/master, origin/HEAD) contrib/apparmor: drop AppArmor profile
55104d3 contrib/completions: add bash completions
0e1a363 Add outer-margin to allow extra margin for first/last notifications
aafbc91 wayland: Don't render a frame on same-size configure
c55b314 wayland: Support HiDPI for cursor
ddc1849 build: use get_variable instead of get_pkgconfig_variable
6caaa55 wayland: set_dirty if we have outputs again
0b41230 wayland: don't render if we don't have outputs
f1bef8a build: use list for sdbus dep, drop sh for scdoc
197ce76 ci: drop removed "systemd" option
e55dfeb ci: drop -Dsystemd from freebsd build options
7aab924 Fix typos
6c955b7 Fix bad conditional in systemd service file
05fe203 Include <errno.h> to use errno in wayland.c
1af224e Load cursor theme from XCURSOR_THEME
6151ecb build: find build tools in build system instead of target
```

I'm  not sure which one fixes this.

**Comment by heroin-moose** [comment]
> will do. I thought it was something wrong with my config - after installing Void it also happe

@acoolstraw, which card (and driver) do you have?

**Comment by acoolstraw** [comment]
Intel 3rd-gen integrated GPU, so mesa I believe? I don't know much about drivers because I don't have to deal with them when it isn't Nvidia

**Comment by heroin-moose** [comment]
Yeah, then it's not broken drivers, intel usually works fine.

**Comment by acoolstraw** [comment]
any idea what this could be? it's really preventing me from doing basic things like screenshotting or recording

**Comment by acoolstraw** [comment]
alright, I looked around on the web and found this issue https://github.com/emersion/grim/issues/119

which led me to look into some other stuff about Vulkan and it seems like the issue has to do with `WLR_RENDERER` using `vulkan`, and I've had Vulkan-related errors in the past with wlroots.
```
WLR_RENDERER=pixman
WLR_NO_HARDWARE_CURSORS=1
```
these environment variables fix it, but I don't see it as a permanent solution

**Comment by Consolatis** [comment]
Interesting. `WLR_RENDERER=gles2` might provide better performance than using software rendering via pixman.

**Comment by acoolstraw** [comment]
Will try that on the next reboot.

**Comment by acoolstraw** [comment]
Huh. I'm using pixman and the issue's back.

**Comment by acoolstraw** [comment]
I might be using gles2, although `echo $WLR_RENDERER` says pixman.

**Comment by acoolstraw** [comment]
It appears pixman fixed it once and now it's broken again.

**Comment by acoolstraw** [comment]
it appears to have been an issue with running an older commit of labwc, or maybe an older version of wlroots since I compile with the `--force-fallback-for=wlroots` option. 

installing `labwc-git` from the AUR works, and so does compiling the workspaces PR and replacing the system binary with it.

**Comment by Consolatis** [comment]
Make sure to do `meson subprojects update wlroots` before building. Or if that doesn't work because you also have the system wide wlroots-git installation around, `rm -rf subprojects/wlroots` (or just cloning labwc into a new directory) + building with `--force-fallback-for=wlroots` should have the same effect.

I really hope wlroots does a release soon so we can stick to a defined version.

**Comment by acoolstraw** [comment]
It may be related to these:

https://github.com/emersion/xdg-desktop-portal-wlr/issues/214
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3440

**Comment by acoolstraw** [comment]
I think this should be closed, unless it's still happening for anyone on master

**Comment by heroin-moose** [comment]
Can confirm that works for me. Since I'm the reporter, I think I'll close it.
