### ISSUE TITLE
Reconfigure do nothing

### ISSUE THREAD

**Issue by m4lin** [labwc/labwc#393]
basically if i  change theme editing rc file save and hit reconfigure nothing happens. If i exit and restart labwc the theme is updated.
not sure if this is expeted, but i saw a video where Reconfigure basically update this.

**Comment by acoolstraw** [comment]
I also remember Reconfigure actually updating the theme, don't know if that actually was the case

**Comment by m4lin** [comment]
forgot to mention, version of labwc is labwc 0.5.0 running under Void Linux

**Comment by Consolatis** [comment]
Yes, `Reconfigure` should indeed update all the settings, including the theme.
Only exceptions are AFAIR cursor theme and keyboard layout for running applications.

@m4lin
I'd guess the keybinding for `Reconfigure` isn't set up correctly, Does `killall -SIGHUP labwc` in a terminal work?
You could also try to copy `docs/rc.xml.all` to `~/.config/labwc/rc.xml` and test with that config.

**Comment by johanmalm** [comment]
Weird, that functionality has existed since early versions.
Let's try with a few simple things:
- Could you post your rc.xml and menu.xml
- Give the names of the themes you're trying
- What happens if you change the theme in rc.xml and then run `killall -SIGHUP labwc` (=reconfigure)
- Could you try change themes with this little app https://github.com/labwc/labwc-tweaks
- Could you try with the master branch

**Comment by m4lin** [comment]
> Weird, that functionality has existed since early versions. Let's try with a few simple things:
> 
> * Could you post your rc.xml and menu.xml
> * Give the names of the themes you're trying
> * What happens if you change the theme in rc.xml and then run `killall -SIGHUP labwc` (=reconfigure)
> * Could you try change themes with this little app https://github.com/labwc/labwc-tweaks
> * Could you try with the master branch

> Yes, `Reconfigure` should indeed update all the settings, including the theme. Only exceptions are AFAIR cursor theme and keyboard layout for running applications.
> 
> @m4lin I'd guess the keybinding for `Reconfigure` isn't set up correctly, Does `killall -SIGHUP labwc` in a terminal work? You could also try to copy `docs/rc.xml.all` to `~/.config/labwc/rc.xml` and test with that config.

First thanks for the fast reply.

here some of the requested actions:

rc.xml --> https://pastebin.com/97uSa1ew  (already taken from doc/rc.xml.all and personalized)
menu.xml -->  https://pastebin.com/96Aq0Ujm 
themes names are Umbra and others from here https://github.com/addy-dclxvi/openbox-theme-collections
and here the most peculiar bit, if i try killall -SIGHUP labwc i do have on void the help message, see  here --> https://pastebin.com/7GP9QpAz
if i use another syntax, killall -s SIGHUP labwc it works, reload the configuration as expexted!! if i do man killall there is this bit: [-s, --signal SIGNAL, -SIGNAL] ... etc so apparently killall should accept both
killall -SIGHUP labwc and killall -s SIGHUP labwc, they should be the same, but apparently they are not!!

i am trying to build the labwc-tweak and i will update, but i believe the above strange behavior of killall is the core of the issue ... i wonder if this is a unique issue with the package included in Void. i will investigate.
if i cannot change void's killall, there is any way to change the killall command without re-build labwc? or it is basically in the source code?

thanks a lot

P.S. great software labwc!!! kepp up the work, i will try to contribute as much as possible.

Marco

**Comment by Consolatis** [comment]
> i believe the above strange behavior of killall is the core of the issue

Yes I am pretty positive this is the issue.

> if i cannot change void's killall, there is any way to change the killall command without re-build labwc? or it is basically in the source code?

I fear it actually is in the source code so can't currently be changed.

What you could do however, is to provide an own `killall` executable in a directory that comes before the main system paths.
I think bash for example usually detects if there is a `~/bin/` directory and if yes it sets it in front of the other `$PATH` entries.
`/usr/local/bin/` might be a system wide alternative variant.

There you could just throw something like this inside (not actually tested):
```bash
#!/bin/bash

KILLALL=/bin/killall

if test "$2" == "labwc"; then
  $KILLALL -s SIGHUP labwc
else
  $KILLALL "$@"
fi
```
`chmod +x` and name it `killall` and it should be called from now on

**Comment by johanmalm** [comment]
Good work. You've definitely found the problem.
No need to do anymore. We'll try to sort a path.

**Comment by Consolatis** [comment]
Alright, will close this then.

If you run into anything else feel free to open up a new issue.
