### ISSUE TITLE
GIMP and title bar disappearing

### ISSUE THREAD

**Issue by m4lin** [labwc/labwc#396]
issue with GIMP

to reproduce:

open GIMP, doesn't matter if an image is opened or not
maximize the window (double click on title bar or maximize button is the same)
close the program
re-open GIMP ... the title bar is no more visible
exit Gimp (file--> Quit)
from now on GIMP will always open maximized and no titlebar visible. 

to return to original normal state delete .config/GIMP folder

re-opening GIMP now the window title bar is back.

is that something expected? do not think so, it does not happens with other programs.

thanks

Marco

**Comment by m4lin** [comment]
yes you are right moving the window the titlebar is still there, so apparently is not disappeared but just "rendered" out of the screen. will play a bit more and report any other strange behavior.

**Comment by acoolstraw** [comment]
hm, is it just positioned in a way where the titlebar is not visible? while this should get fixed, you can just hold Alt and drag it with your mouse to move it into a position where the titlebar is visible

**Comment by m4lin** [comment]
> hm, is it just positioned in a way where the titlebar is not visible? 
while this should get fixed, you can just hold Alt and drag it with your mouse to move it into a position where the titlebar is visible

yes confirmed. is not abig bug, just a minor one, and i am trying most of the software i am usually using, but none yet has the same issue.

**Comment by m4lin** [comment]
UPDATE:

workaround: GIMP has an option for save window position on exit. uncheck the options will sort the issue in labwc.

![swappy-20220616_100755](https://user-images.githubusercontent.com/11050064/174035800-0b36ffad-14f0-4c5b-9ad4-e64ce551d1ac.png)

**Comment by acoolstraw** [comment]
same here

**Comment by johanmalm** [comment]
80792d446f64a7ed01b04e39e11018b904413533 fixes the empty window for me.
bfff9d02c717ad1a9b3693a843dd267774cdc7e9 fixes the positioning issue.
I'd appreciate feedback if you're able to test.

**Comment by johanmalm** [comment]
This is fixed for me. Will close.
