### ISSUE TITLE
Support switching from the current workspace to the most recently visited one

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#399]
It would be nice to be able to go back and forth between two workspaces (e.g. in my case the one with neovim and the other one with Mattermost). Openbox allows users to do this via GoToDesktop[1]:

```
<action name="GoToDesktop" to="last"/>
```

The Openbox implementation looks unnecessary complicated wrt to timeout, so IMO it's better to simply remember the last visited workspace.
 
[1] http://openbox.org/wiki/Help:Actions#GoToDesktop

**Comment by acoolstraw** [comment]
this could be somewhat of an A-Tab for workspaces

**Comment by heroin-moose** [comment]
Addressed in https://github.com/labwc/labwc/pull/400
