### ISSUE TITLE
Extent 'struct font' with a bool 'bold' flag + make get_font_height/width use it

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#408]
Height calculation doesn't seem correct for text using bold as can be seen by wrong centering of the workspace title on the y axis in #406.

**Comment by jlindgren90** [comment]
Was this perhaps addressed by #547?

**Comment by Consolatis** [comment]
I think so, was reading through that diff again and it appears `font_height()` now uses the same font as for rendering.
So I think you are right in that this has been fixed in the meantime. Thanks for mentioning it.
