### ISSUE TITLE
SnapToEdge does not consider turned off window decorations

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#409]
There is just a gap where the titlebar and border would be.
[Screenshot](https://user-images.githubusercontent.com/4444593/174590236-87afde56-8bd4-44b7-81d3-04f6f7b32fa0.png)

**Comment by m4lin** [comment]
> made by @Consolatis but not yet released

ok, will wait. at the moment I am using sfwbar, which is nice with the workspaces/desktop, not showing the workspaces in Labwc (it is designed for sway) but I mapped in Labwc keybinding to show OSD with ALL the opened windows, no matter the workspace. 
    <keybind key="C-Tab">
      <action name="Execute"><command>killall -s SIGUSR1 sfwbar</command></action>
    </keybind>
This way I have another way to visualize all the windows in current workspace, or ALL windows in ALL worskpaces, handy.

KR

**Comment by ahmadraniri1994** [comment]
> > btw which is the bar in the screenshot?
> 
> made by @Consolatis but not yet released

Perhaps it's too out of topic, Would you mind point me to its source code ? thanks

**Comment by Consolatis** [comment]
> Would you mind point me to its source code

It will be released publicly at some point
