### ISSUE TITLE
Implement <default /> for mousebinds

### ISSUE THREAD

**Issue by luke876** [labwc/labwc#416]
When I have an xdg-shell window focused and click on an xwayland window, the window I clicked captures input.
When I click from an xwayland window to another xwayland window the second one captures input.

However, when I click from an xwayland window into an xdg-shell window, the xwayland window keeps capturing input. I have to alt-tab switch to it to type in the xdg-shell window.

**Comment by Consolatis** [comment]
Which version of labwc are you using?

**Comment by luke512** [comment]
I am on the latest master commit. Actually, I realized after reporting this that clicking inside of any xdg-shell window doesn't focus it properly for me, even from one xdg-shell window to another.

**Comment by luke512** [comment]
I figured out the problem. Apparently defining one mousebind overwrites all other mousebinds, unlike keyboard shortcuts. At the very least I think there should be a warning about this in the manpage.

**Comment by johanmalm** [comment]
Yes, good point. We ought point that out in the example rc.xml and rc.xml.all as well as the man page.
I think we will add a `<devault />` option to mousebinds, too at some point.
