### ISSUE TITLE
Undecorated XWayland windows can't be moved

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#418]
Under X11, it's possible for an undecorated window to be moved by dragging it (from within the client area of the window).  The way this works is that the application handles the mouse events and simply sends "move window" requests to the window manager.  These types of windows (running in XWayland mode) currently can't be moved at all in `labwc` -- you can click and drag on them, but the windows just don't move.

Examples:
- Main window of Audacious in Winamp mode
- Detached toolbars of Qt applications (try `kdiff3`)

I don't think this is a recent regression but rather something that has never worked in `labwc` so far.  I would guess that there is some X11/NetWM message that isn't currently being handled.

I don't have time to look into a fix right now, but thought I'd document the issue in case someone else has time/inclination to work on it.

**Comment by johanmalm** [comment]
If you run with WLR_DEBUG (`labwc -d`), do you get any clues.
For example, do we get to this line?
https://github.com/labwc/labwc/blob/a3d3878d28cce8e7e67151c9c717299aa3f22a7a/src/xwayland-unmanaged.c#L33

**Comment by johanmalm** [comment]
Would you mind checking if it works in sway

**Comment by johanmalm** [comment]
Maybe we ought to handle move/resize :smile:
https://github.com/swaywm/sway/blob/a55472c6d882d806e9d6fc0a78a7f7d8f888492e/sway/desktop/xwayland.c#L590

**Comment by jlindgren90** [comment]
@johanmalm I didn't see your questions until now, sorry. I'll try to find some answers this weekend.

**Comment by Consolatis** [comment]
When trying to move a detached toolbar from `kdiff3` I get:
`00:02:50.816 [xwayland/xwm.c:823] unhandled X11 property 348 (_NET_WM_USER_TIME) for window 4194310`

Not sure if its the reason this fails but I get two of those every time I start the drag operation.

**Comment by jlindgren90** [comment]
I get the `_NET_WM_USER_TIME` message too -- not sure if it's related.
```
00:00:50.188 [DEBUG] [../src/action.c:155] Handling action Focus (15) with arg (null)
00:00:50.188 [DEBUG] [../src/action.c:155] Handling action Raise (18) with arg (null)
00:00:50.189 [DEBUG] [xwayland/xwm.c:823] unhandled X11 property 319 (_NET_WM_USER_TIME) for window 8388662
```
