### ISSUE TITLE
When we use wlr-randr to setting custom-mode the program crashes！

### ISSUE THREAD

**Issue by fakeczg** [labwc/labwc#424]
![image](https://user-images.githubusercontent.com/54363314/176396662-0c9a0139-1429-48c4-a5d9-504bf6009277.png)

When we use wlr-randr to setting custom-mode the program crashes!
wlr-randr --output eDP-1 --custom-mode 1366x768 
when we debug setting custom-mode: 
output->swapchain->width:1366 output->swapchain->height:768
output->width：1360 ， output->height:768

**Comment by Consolatis** [comment]
Upstream bug report: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3453

We might not test the custom solution properly, didn't verify though.

**Comment by Consolatis** [comment]
@Flrian Thanks for testing.

Assuming this has been fixed in the meantime. Shout if this is still an issue on labwc 0.6 or the latest master branch.
