### ISSUE TITLE
Activate windows on hidden workspaces

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#431]
Currently window activation via desktop notifications only works if the application that sent the notification is on the active workspace. It be would be nice to switch to the application on hidden workspace, because this is the most useful scenario (e.g. activating a chat window on dedicated workspace).

**Comment by Consolatis** [comment]
This requires somebody to figure out how the activation sequence actually works. Usually the application providing the notification is an external program listening on dbus (example: mako) and acting on behalf of another application.

AFAIR a wayland applications can't actually activate any other wayland application (nor is it even aware of the others).
So I \*assume\* what is happening is that application `A` (let's say `Thunderbird`) is requesting daemon `B` (lets say `mako`) to show a notification (via dbus) with given content. The user then clicks on the notification created by `B` and `B` gets the click event from the compositor. It then forwards the information that it has been clicked on by the user (and possibly on what control element) to the original application `A` which then (presumably)  sends a request  to the compositor to become activated.

It is that last part (`A` requesting activation) that we'd need to figure out the code path for and then just throw a `workspaces_switch_to(view->workspace)` in there.

**Comment by heroin-moose** [comment]
mako indeed uses it: https://github.com/emersion/mako/commit/6ac9242dce91ab094297c46b2e860d52846e38d9

**Comment by heroin-moose** [comment]
Sway implementation: https://git.b12f.io/starred/swaywm__sway/commit/9755684fb0fd665a65be2a3cbabc5d502244c459

**Comment by Consolatis** [comment]
Should be fixed by #758
