### ISSUE TITLE
Change monitor refresh rate

### ISSUE THREAD

**Issue by Relwi** [labwc/labwc#432]
To be honest, I don't know if this issue is related to this project or the wayland or something else, but I have a 144hz monitor and `xrandr` only shows me differents sizes at 60hz. Is there some way to fix it or will be in the future be available to change to 144hz? (if the problem is with `labwc`)

**Comment by Consolatis** [comment]
It is possible xwayland is limited to 60hz for whatever reason.
This would need some further investigation to figure out if its just reporting the 60hz or if its actually limited by that.

Short explanation: xwayland is the X11 backward compatibility layer for wayland and thus X11 applications like games are usually running via that compat layer.

**Comment by Relwi** [comment]
Yeah, I tried in the terminal `wlr-randr --output DP-1 --custom-mode 1920x1080@144Hz` and it works, but I see now this ![IMG_20220705_213822.jpg](https://user-images.githubusercontent.com/31081245/177403006-429efade-0b59-4e70-8705-289b5c5b86b0.jpg)

Don't know if you can appreciate, but is like an old TV

**Comment by Relwi** [comment]
> About the pixel puree I am not sure what is causing that, might be related to using the custom mode instead of the announced mode but could also be a dozen of other things.

Yep, aparentelly I needed to put the exact amount of Hz, so I used `wlr-randr --output DP-1 --mode 1920x1080@144.001007Hz` and now it works perfect
