### ISSUE TITLE
Environment variables aren't expanded after underscore

### ISSUE THREAD

**Issue by notchtc** [labwc/labwc#439]
When trying to use any env var containing underscores (for example `UNDER_SCO_RE`) in a keybind with `sh -c` or in the environment file only the first part is expanded. (`UNDER`)

So you get something like `(value of UNDER)_SCO_RE` instead of whatever `UNDER_SCO_RE` is set to.

**Comment by Consolatis** [comment]
Could you please post an example key-binding?

To workaround this you could temporarily use some small wrapper script like
```bash
#!/bin/bash
export WHAT_EVER="some value"
exec some_application
```

**Comment by notchtc** [comment]
```sh
sh -c "pamixer -i 5 &amp;&amp; pamixer --get-volume > $WOBSOCK
```

I have `$WOBSOCK` set to `$XDG_RUNTIME_DIR/wob.sock` in labwc's `environment` file.
It also doesn't work when I have just `$XDG_RUNTIME_DIR/wob.sock` in the keybind.

It works in the terminal.

I'm just gonna use a different directory for now.

**Comment by Consolatis** [comment]
I think I found the culprit:
https://github.com/labwc/labwc/blob/e05d4600beb4855a3b75a192d97fd6b02eb162e7/src/common/buf.c#L31

Should be easy to fix by adding a `|| *p == '_'` to that condition, so something like this:
```c
while (isalnum(*p) || *p == '_' || *p == '{' || *p == '}') { 
```

Not sure right if there are other (other than `_`) non alphanumeric characters allowed in environment names.

**Comment by 01micko** [comment]
> Not sure right now if there are other (other than _) non alphanumeric characters allowed in environment names

[No](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_231)
