### ISSUE TITLE
PreviousWindow is the same as NextWindow

### ISSUE THREAD

**Issue by alandiwix** [labwc/labwc#449]
PreviousWindow walks through the window list in the same direction as NextWindow.
Reproduce:
1. Open 5 windows.
2. Start walking through the windows using NextWindow hotkey.
3. Now use PreviousWindow hotkey.

Expected: PreviousWindow walks in the opposite direction.
Result: PreviousWindow and NextWindow do the same thing.

**Comment by Consolatis** [comment]
Hm.. there is quite a lot wrong / strange with the A-Tab bindings.
- A-Tab works and switches to the next (e.g. previously unfocused window), so `A-Tab` -> release -> `A-Tab` toggles between the same two windows which is the desired behavior.
- When inside the `A-Tab` OSD, pressing `A-S-Tab` correctly reverses the direction (as does every other key while `Shift` is held down)

When `PreviousWindow` or `NextWindow` is bound to a single key (e.g. `F1` and `F2`) it works on the first press, one is forwards, the other is backwards. However:
- the OSD stays alive until a modifier has been pressed and released
- further single `F1` or `F2` presses just go forward unless pressed together with `Shift`

**Comment by johanmalm** [comment]
Oh, I’d never thought about binding cycle-window to one key only. Should that be allowed?
Does anyone actually want it?

**Comment by Consolatis** [comment]
I think the main issue here is that we basically ignore any actions other than the first one and then handle all further input within the OSD logic itself. For me and my usage pattern that is completely fine (I am using `A-Tab` / `A-Shift-Tab` on my main DRM session and `W-Tab` / `W-Shift-Tab` on nested test sessions).

However if people see those 2 actions available they might expect them to work independently of an active OSD like they are used to from Openbox. So what we could do is to just remove both actions and instead add a new custom action like `CycleStart`, maybe with an additional `direction="forward|backward"` argument.

**Comment by Consolatis** [comment]
This makes `PreviousWindow` work correctly when bound to a single key (but will still show the OSD while the key is pressed).
Using `NextWindow` also kind of works when bound to a single key but will toggle between the 2 recently used windows, the same as `A-Tab` -> release -> `A-Tab`.

```diff
diff --git a/src/keyboard.c b/src/keyboard.c
index b1aca0d..b739e3e 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -147,6 +147,12 @@ handle_compositor_keybindings(struct keyboard *keyboard,
 		goto out;
 	}
 
+	if (server->osd_state.cycle_view
+			&& event->state == WL_KEYBOARD_KEY_STATE_RELEASED
+			&& !keyboard_any_modifiers_pressed(wlr_keyboard))  {
+		end_cycling(server);
+	}
+
 	/*
 	 * If a press event was handled by a compositor binding, then do not
 	 * forward the corresponding release event to clients
```

**Comment by vain** [comment]
Hi again,

FWIW, I got hit/confused by this as well.

I have two individual key binds:

```xml
<keybind key="W-j"><action name="NextWindow" /></keybind>
<keybind key="W-k"><action name="PreviousWindow" /></keybind>
```

I would have expected that one of them cycles the focus list forwards and the other one backwards. But the only way to cycle backwards in a meaningful way is to begin cycling *forwards*, keeping the modifier key pressed, and then press Shift additionally, which finally goes backwards. 🥴

**Comment by droc12345** [comment]
There does seem to be a problem with previous window.

I added a simple prinf inside desktop_cycle_view and got this
`00:00:43.504 [DEBUG] [../labwc-9999/src/input/keyboard.c:191] keycode matched`
`00:00:43.504 [DEBUG] [../labwc-9999/src/action.c:717] Handling action 12: PreviousWindow`
`forwards? 0, dir 2`
`forwards? 1, dir 1`
`forwards? 1, dir 1`
`forwards? 1, dir 1`
`forwards? 1, dir 1`

This was just holding down the alt button and hitting tab repeatedly,
For some reason it decides to go from previous to next (dir) while still trying to do previous.
But if I do next window (winkey & tab) and hold down the shift then reverse works, though it's not
even set as a keybind.

**Comment by johanmalm** [comment]
@droc12345 Sorry it took me a few days go look at this patch. I don't like you leave anyone waiting when they go to the effort of producing PRs.

I've had a look at the patch, but suggest that we need to evaluate + agree what behaviour we want before going any further with code.

`labwc` is currently designed to support cycling forwards and backwards with `A-Tab` and `A-S-Tab` respectively - achieved by a configuration as follows:

```xml
<keybind key="A-Tab" name.action="NextWindow"/>
<keybind key="S-A-Tab" name.action="PreviousWindow"/>
```

The actions above only 'commence' the interactive-cycling. When you're in the interactive-cycling, it's the Shift key that determines the direction.

I can see that this ends up being a big confusing if you define `{Next,Previous}Window` with:

```xml
<keybind key="W-j"><action name="NextWindow"/></keybind>
<keybind key="W-k"><action name="PreviousWindow"/></keybind>
```

I'm happy to discuss proposals to change current behaviour - but as a general rule, we don't like regressions so it would have to be a pretty convincing case.

Off the top of my head, the only thing I can think of as a solution to this is to check if the non-modifier key in the `{Next,Previous}Window` keybinds are different, and if so allow them to determine the direction when in interactive-cycling.

**Comment by droc12345** [comment]
Once you throw the arrow keys in, then things don't behave as expected. 
The patch I've written should work no matter the key combo, or using arrow keys in combination.
I've bound _next to W-tab_ and _previous to S-W-tab_ and next/prev work as they should.

But I'm more than happy to leave it as is, 
I was simply responding to what I saw as wrong behavior, given certain key combinations.
