### ISSUE TITLE
Name of possible keyboard keys

### ISSUE THREAD

**Issue by dglava** [labwc/labwc#456]
I wanted to map some keys on my keyboard to certain actions, but I couldn't find a list of all the keyboard keys to use. For example: I wanted to bind something to Page Up and I didn't know what the key's name was (inside labwc). I quickly checked my old Openbox config and found out it's `Page_Up` and it appears to work in labwc as well.

The [Openbox documentation](http://openbox.org/wiki/Help:Bindings#Keys) recommends to use `xev` to find out, but that's an X tool. Is there a Wayland tool which could be used? Alternatively, is it possible to include a list of all possible key names with labwc? I reckon that would be more user friendly in terms of documentation.

**Comment by Consolatis** [comment]
labwc is using libxkbcommon which has all the keysyms [defined in a header](https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h).

`xev` (which runs via xwayland) or `wev` (wayland native) should both do the trick.
Maybe we should mention `xev` and `wev` somewhere in the man pages.

**Comment by johanmalm** [comment]
Or on the 'getting-started' page on the website. Appreciate suggestions.

**Comment by Consolatis** [comment]
https://labwc.github.io/getting-started.html#step-3---set-a-shortcut-to-a-launcher

Maybe something like "You can use either `xev` (widely available, runs via xwayland) or `[wev](https://some.link.to/sources)` to figure out the name of a key."

**Comment by johanmalm** [comment]
Solved by #766
