### ISSUE TITLE
Decoration issues when running Chromium under Wayland natively

### ISSUE THREAD

**Issue by acoolstraw** [labwc/labwc#464]
When running Chromium without Xwayland, it will enable SSD, even when use system titlebar is disabled in the settings. If you switch it on and off, it gets fixed, but it comes back next restart.

Without the system titlebar, the minimize and maximize button are gone, leaving only the close button.

Also, when screensharing, the window that pops up notifying you a website is sharing your screen has SSD around it, when it should be decorationless, as shown here
![swappy-20220724_042257](https://user-images.githubusercontent.com/45886986/180629540-1f106e8c-40ce-4bf0-b239-89e4b4f0d00a.png)

**Comment by Consolatis** [comment]
May be related: #297

**Comment by Consolatis** [comment]
Should be fixed by #838

Feel free to comment if that is not the case and we'll reopen the issue.
