### ISSUE TITLE
Issues when trying to restore gamescope to fullscreen

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#470]
gamescope uses "Super + F" to toggle fullscreen, when trying to restore the window to fullscreen the game doesn't get resized properly and is very laggy.
https://user-images.githubusercontent.com/4444593/182277493-4a62bfa0-0a69-40c2-8830-883bc3b53a88.mp4

**Comment by Consolatis** [comment]
Interesting, so something gamescope does for requesting fullscreen differs from what we do when initiating the fullscreen.
Might still be worth looking into.

**Comment by johanmalm** [comment]
@Flrian Does gamescope actually send a fullscreen signal or does it attempt to do it some other way?
Could you insert an fprintf(stderr, "whatever");  at https://github.com/labwc/labwc/blob/ac5c9dae00fab736b81260df0c7247beb6478933/src/xwayland.c#L185 to confirm

I can't see anything obvious from the code.
