### ISSUE TITLE
menu.xml: Allow root-menu to have no label

### ISSUE THREAD

**Issue by devosalain** [labwc/labwc#472]
Right-mouse-click or Left-mouse-click only shows two things : 
-Reconfigure
-Exit
Although my menu.xml is:
``` 
<?xml version="1.0" encoding="UTF-8"?>

<openbox_menu>

<menu id="root-menu">
  <item label="Web browser">
    <action name="Execute"><command>firefox</command></action>
  </item>
  <item label="thunar">
    <action name="Execute"><command>thunar</command></action>
  </item>
  <item label="nemo">
    <action name="Execute"><command>nemo</command></action>
  </item>
  <item label="gtk-mixer">
    <action name="Execute"><command>gtk-mixer</command></action>
  </item>
  <item label="strawberry">
    <action name="Execute"><command>strawberry</command></action>
  </item>
  <item label="QTerminal">
    <action name="Execute"><command>qterminal</command></action>
  </item>
  <item label="xfce4-terminal">
    <action name="Execute"><command>xfce4-terminal</command></action>
  </item>
  <item label="Terminal">
    <action name="Execute"><command>kitty</command></action>
  </item>
  <item label="Reconfigure">
    <action name="Reconfigure"></action>
  </item>
  <item label="Exit">
    <action name="Exit"></action>
  </item>
  <item label="Poweroff">
    <action name="Execute"><command>systemctl -i poweroff</command></action>
  </item>
</menu>

</openbox_menu>
``` 

My O.S. is FreeBSD 13.1-RELEASE

**Comment by Consolatis** [comment]
Your `menu.xml` looks fine on the first look so it appears labwc is not picking it up correctly.
Is it available as `~/.config/labwc/menu.xml`?

**Comment by devosalain** [comment]
Yes it is.

**Comment by Consolatis** [comment]
Just tested your `menu.xml`, the root-menu misses a label (which can be empty). So something like this should work:
`<menu id="root-menu" label="">`

**Comment by devosalain** [comment]
Indeed, that fixed the problem.

**Comment by johanmalm** [comment]
`(label && id)` creates inline menu

https://github.com/labwc/labwc/blob/ac5c9dae00fab736b81260df0c7247beb6478933/src/menu/menu.c#L317

`id` only creates an submenu entry point to a menu defined elsewhere.

https://github.com/labwc/labwc/blob/ac5c9dae00fab736b81260df0c7247beb6478933/src/menu/menu.c#L339

At line 317 we could add `|| id && !strcmp(id, "root-menu)` ....  It makes the code a bit uglier and introduces a weird exception to the rule, but I suppose makes it a bit easier for the user :smile:
