### ISSUE TITLE
`bemenu-run -b` appears cut off

### ISSUE THREAD

**Issue by Joshua-Ashton** [labwc/labwc#480]
Might be a bemenu bug, havent looked into it yet.

![image](https://user-images.githubusercontent.com/21316711/183966155-6a5ea9c6-213a-4600-b3da-a71395eff106.png)

**Comment by johanmalm** [comment]
Works fine here.

**Comment by Consolatis** [comment]
Does this still happen on 0.6 release / latest master?

**Comment by Consolatis** [comment]
Closing for now. Feel free to shout if this still happens.
