### ISSUE TITLE
Partial motion event outside the surface when the pointer is grabbed - No event at all with layer-shell

### ISSUE THREAD

**Issue by Tamaranch** [labwc/labwc#483]
Labwc 0.5.3 on Arch Linux

Here is the code to reproduce the problem:

<p>
<details>
<summary>p.c</summary>

```c
#include <gtk/gtk.h>
#include <gtk-layer-shell/gtk-layer-shell.h>

static gboolean
on_button_press (GtkWidget *widget,
                 GdkEvent  *event,
                 gpointer   user_data)
{
  g_printerr ("%s\n", G_STRLOC);

  return FALSE;
}

static gboolean
on_button_release (GtkWidget *widget,
                   GdkEvent  *event,
                   gpointer   user_data)
{
  g_printerr ("%s\n", G_STRLOC);

  return FALSE;
}

static gboolean
on_motion_notify (GtkWidget      *widget,
                  GdkEventButton *event,
                  gpointer        user_data)
{
  g_printerr ("%s:x: %f\n", G_STRLOC, event->x);
  g_printerr ("%s:y: %f\n", G_STRLOC, event->y);

  return FALSE;
}

gint main (gint argc, gchar **argv)
{
  GtkWidget *window;
  GMainLoop *loop;
  GtkWidget *widget;

  gtk_init (&argc, &argv);

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  widget = gtk_button_new_with_label ("test");
  gtk_container_add (GTK_CONTAINER (window), widget);
  g_signal_connect (widget, "button-press-event", G_CALLBACK (on_button_press), window);
  g_signal_connect (widget, "button-release-event", G_CALLBACK (on_button_release), window);
  g_signal_connect (widget, "motion-notify-event", G_CALLBACK (on_motion_notify), window);

  if (g_strcmp0 (argv[1], "--layer") == 0)
    gtk_layer_init_for_window (GTK_WINDOW (window));

  gtk_widget_show (widget);
  gtk_widget_show (window);

  loop = g_main_loop_new (NULL, FALSE);
  g_signal_connect_swapped (window, "destroy", G_CALLBACK (g_main_loop_quit), loop);
  g_main_loop_run (loop);
  g_main_loop_unref (loop);
}
```

</details>
</p>

It is built by
```sh
gcc p.c -o p $(pkg-config --cflags --libs gtk+-3.0 gtk-layer-shell-0)
```

Run by
```sh
./p [--layer]
```
to activate or not layer-shell.

When the button is clicked and the pointer is moved outside the window:
* if layer-shell is not activated: the coordinates are only updated in one dimension, and if you are in the cross formed by the extension of the button in x and y. So they remain for example at (0,0) in the upper left corner, and they are only updated in x if you move above the window.
* if layer-shell is activated : there is no more motion event outside the window.

Releasing the button outside the window sends the corresponding event in both cases though.

On Wayfire for example, the motion event is sent and the coordinates are correctly updated in both cases.

**Comment by Consolatis** [comment]
> the coordinates are only updated in one dimension, and if you are in the cross formed by the extension of the button in x and y. So they remain for example at (0,0) in the upper left corner, and they are only updated in x if you move above the window.

This is the way it was designed for labwc. The use-case for these "out-of-surface" movements we thought about were selecting text in a terminal or using a scrollbar. All values are clamped to the surface area.
If this is against the spec we may change it but it seemed like a logical thing to do so an applications doesn't suddenly get coordinates which are outside of their surface area.

What is your use-case for allowing "out-of-surface" movements for layer shell clients?

**Comment by Tamaranch** [comment]
I am currently working on porting Xfce4-panel to Wayland, so I am trying to preserve the features offered on X11. Among these, there is the possibility to move the panel by grabbing it with side handles.

This is a constrained move, done manually by updating the panel position on motion signal. For positioning I can manage with layer-shell anchors and margins, but I also need a suitable motion signal.

I tried to use pointer constraints (conf. #475), which don't work well for that, before I realized that Wayfire emits a complete motion signal outside the panel, unlike Labwc.

Alternatively it seems I could use the relative-pointer protocol, for which a complete motion signal is emitted outside the panel on both Labwc and Wayfire, if I'm not mistaken. But it would obviously be easier with the classic motion signal.

I think eventually we will have to have our own Wayland compositor for Xfce anyway, maybe based on Labwc :)

**Comment by Consolatis** [comment]
> I am currently working on porting Xfce4-panel to Wayland

Great stuff :)
Is there a branch or PR somewhere where one could keep track of the progress?

> But it would obviously be easier with the classic motion signal.

The use-case makes sense and I don't think it would cause any issues (so far). It should also be relatively trivial to implement.
I'll have a look in the next days, no promises though.

**Comment by johanmalm** [comment]
https://github.com/adlocode/xfwm4/tree/wlroots/src

**Comment by Tamaranch** [comment]
> Is there a branch or PR somewhere where one could keep track of the progress?

Not yet. I'm still experimenting at the moment, and it's a long process that won't be merged right away. But I'm still thinking of opening a merge request on Xfce's GitLab in "not too long" to make it public.

Otherwise efforts are already underway to provide a Wayland compositor to Xfce, which is what the link above is about, but nothing official yet.

There have been discussions about this lately on the [xfce-dev mailing list](https://mail.xfce.org/pipermail/xfce4-dev/2022-July/thread.html).

**Comment by Consolatis** [comment]
Those coordinates would then still have to be relative though, right?
So for your example (using layershell without anchor) the `x` argument would turn negative once moving the cursor to the left of the button. Is this how wayfire is doing it as well?

**Comment by Tamaranch** [comment]
Yes, I think Wayfire's behavior is exactly the same in this respect whether layer-shell is enabled or not. That's also how it is on Weston, without layer-shell of course.

**Comment by johanmalm** [comment]
@Tamaranch 

Link below to the code responsible for the surface-button-press behavior. 
https://github.com/labwc/labwc/blob/1cdebbc22daa83222e9f5170cf3cb1afc4c4e90e/src/cursor.c#L282-L308

Commenting out some of those bits might help explore this.

**Comment by Tamaranch** [comment]
Thank you! Unfortunately I don't think I'll have time to look into the Labwc codebase in the near future. I'm content to take the existing compositors as they are for now. Maybe later :)

**Comment by johanmalm** [comment]
When starting to write labwc I did consider using xfwm4 theme syntax, but settled for openbox because I felt more familiar with it.
They're actually very similar though - both contain a themerc to set colors and then a bunch of icons.
We have been talking about adding png support to help conversion from GTK theme and so on.

**Comment by Consolatis** [comment]
I have a prototype available locally which works but is missing a clean up on layer surface unmap / destruction.
Will put up a PR when ready.

**Comment by johanmalm** [comment]
@Consolatis  Hmm.... I've just tried the `p.c` test. It does seem a bit glitchy. Maybe something isn't quite right??

> Thank you! Unfortunately I don't think I'll have time to look into the Labwc codebase in the near future. I'm content to take the existing compositors as they are for now. Maybe later :)

No worries :) I know what it's like. 
It'd be worth running with the master branch. We've implemented the wlroots scene-graph API and moved a long way from 0.5.3

**Comment by Consolatis** [comment]
> It does seem a bit glitchy. Maybe something isn't quite right??

Assuming you are referring to the dimensions: somehow the minimal size the SSD requires isn't used (as in the 4 SSD buttons are wider than the view itself). It fixes itself once initiating a resize but its obviously still an ugly bug. Stored that in the back of my mind, ready to be forgotten eventually. Guess I should have opened an issue about it instead.

**Comment by johanmalm** [comment]
Yes. x and y only update sporadically when cursor is outside the pressed surface

**Comment by Tamaranch** [comment]
I can confirm that the problem is solved when layer-shell is enabled (`./p --layer`), but not when it is not enabled (`./p`). But maybe you don't want to change the behavior in this case?

**Comment by Consolatis** [comment]
Yes, we decided to remove the clamping completely.

**Comment by Tamaranch** [comment]
Yes, I can confirm that the problem is solved in both cases now. Thanks!

**Comment by johanmalm** [comment]
@Tamaranch Sorry to bump an old issue - just wanted to ask some advice on building 
https://gitlab.xfce.org/Tamaranch/xfce4-panel/-/tree/wayland-xfw

I have installed the following from the AUR:
- xfce4-dev-tools-devel
- garcon-devel
- libxfce4util-devel
- libxfce4ui-devel

It also wants `libxfce4windowing` and `libxfce4windowingui`

I've tried building `https://gitlab.xfce.org/kelnos/libxfce4windowing/-/tree/main/` with

```
./configure --prefix=/usr
make
sudo make install
```

Seems to work fine except this warning:

```
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libxfce4windowingui-0.la '/usr/lib'
libtool:   error: error: cannot install 'libxfce4windowingui-0.la' to a directory not ending in /usr/local/lib
```


Following this, libxfce4panel autogen.sh seems to pick up `libxfce4windowing` but not `libxfce4windowingui`

Any advice?

**Comment by Tamaranch** [comment]
It should be
```sh
./autogen.sh --prefix=/usr
make
sudo make install
```
to build libxfce4windowing, as well as the panel.
Also make sure to install gtk-layer-shell: it's "optional", but its absence is currently not well guarded and [leads to a segfault](https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/103#note_60751).

**Comment by johanmalm** [comment]
Thanks. Got it.
And the panel is working :smile:

**Comment by Tamaranch** [comment]
Great! Feel free to report bugs if you want (or crashes, because small bugs might be a bit early), on the [merge request](https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/103) as long as it is not merged :slightly_smiling_face:
