### ISSUE TITLE
Application setting window title constantly lags compositor

### ISSUE THREAD

**Issue by Joshua-Ashton** [labwc/labwc#486]
I shoved the fps into the header of my engine, and noticed that it really lags the compositor when it sets the window title constantly.

**Comment by johanmalm** [comment]
Weird. Setting the window title shouldn't be expensive. Would you mind helping with steps to reproduce?

**Comment by Joshua-Ashton** [comment]
Seems to be a wlroots issue when I dug deeper. Disabling all labwc signals for it still lags. I just made an app that just does while(true) SetWindowTitle using SDL2

**Comment by Consolatis** [comment]
I am actually using this for my IRC notifications, although limited to a new title every 500ms for two applications (1x xwayland via `wmctrl`, 1x wayland native). I have zero issues with that producing any kind of lag.

I didn't test setting a new title ~ 240 times a second or something like that though. At which point this whole issue becomes rather theoretical anyway IMHO, update it once or twice a second instead.
