### ISSUE TITLE
Incorrect handling of floating XWayland windows (multiple issues)

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#494]
### Issue 1 - incorrect title bar highlight

Steps to reproduce:

- From an XWayland terminal window (I used xfce4-terminal, but I don't think it
  matters which), run `audacious` (in Qt 5 mode).
- Activate the Search Tool pane (use the "search" icon in the toolbar) if not
  already active.
- Undock the Search Tool pane (click the "restore" icon in the top-right corner
  of the pane, next to the "close" icon).

Expected result:

- The title bar of the main Audacious window remains highlighted as the active
  window.

Actual result:

- The title bar of some other, unrelated top-level window (sometimes the
  terminal window, sometimes the window of a third, completely unrelated
  application) gets the "active window" highlight color.
- However, key-press events are passed to the floating Search Tool pane (as
  expected, but contrary to what the highlighted title bar on the other window
  would suggest).

### Issue 2 - incorrect mouse event handling

Steps to reproduce:

- Start `kdiff3`.
- Right-click the toolbar, and un-check "Lock Toolbar Positions".
- Drag the toolbar to a floating position in front of the main kdiff3 window.

Expected result:

- Buttons on the toolbar can be clicked.

Actual result:

- Mouse clicks apparently "pass through" the toolbar to the main kdiff3 window
  below it.  Only if the main window is moved away, out from behind the toolbar,
  is it then possible to click buttons on the toolbar.
- Moving another, unrelated top-level window (such as a terminal window)
  underneath the kdiff3 toolbar also results in mouse clicks "passing through"
  the toolbar to that window.

**Comment by jlindgren90** [comment]
Versions:
labwc commit b39020213a8e3d7bc7c29082447bfe3edbb0e8ee
wlroots commit 7c575922c05e4d5fd9a403c2aa631a54c7531d44

**Comment by johanmalm** [comment]
Thanks for the analysis. Really appreciate your push to flush out these xwayland behaviors.
I haven't got much headspace to jump on these quickly - just to set expectations.

The one thing that springs to mind is that we still don't handle all signals. For example

https://github.com/labwc/labwc/blob/33bc37e7d05b870164d8faad2f0f057910a62eaa/src/xwayland-unmanaged.c#L107-L117

Does the debug log show any unmanaged set_override_redirect or request_activates?

**Comment by jlindgren90** [comment]
I will check the log and try to do a little more debugging when I have the chance. It might be a little while on my end too.

**Comment by Consolatis** [comment]
Fixed by #517
