### ISSUE TITLE
Should preview-border be positioned inside SSD max extents?

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#496]
It's currently positioned outside the ssd-max-extents which results in the border going outside the output when a window is maximized.

From memory openbox keeps the border within ssd-max-extents.

**Comment by Consolatis** [comment]
That should be easy to change:
https://github.com/labwc/labwc/blob/33bc37e7d05b870164d8faad2f0f057910a62eaa/src/osd.c#L106-L109

-> set_size(geo.width, geo.height)
-> set_pos(geo.x, geo.y)

I do not really have an opinion about it, both variants would be fine with me.

**Comment by johanmalm** [comment]
Well… I checked out a new branch and started hacking away on a fancy-rect patch… but got so confused by +i and -i etc… I just started laughing and remembered my last note-to-self… don’t code when stressed and tired cos it doesn’t work… so an issue will have to do for now 😄

**Comment by Consolatis** [comment]
yeah, the fancy_rect thingie really looks simpler than it was, it kinda made knots in my brain when thinking about the differently layered offsets for each side. In this case its only the size of the whole thing + positioning though. And those two are defined by the caller.
