### ISSUE TITLE
Cannot start labwc

### ISSUE THREAD

**Issue by Relwi** [labwc/labwc#508]
Recently I installed a very minimalism Arch Linux, I installed `labwc` with the AUR but I can't start it, with sddm I can login into it but I don't have display source and can't do anything.
![IMG_20220828_164146.jpg](https://user-images.githubusercontent.com/31081245/187079771-7b7304c5-6c15-4cf8-800c-98ad103a3ba8.jpg)

In another installation that I have done, it worked fine, but don't know why, may be I'm missing some basic package to install or something. I have installed a custom kernel btw, linux-tkg.

**Comment by Consolatis** [comment]
Your setup seems to miss a seat setup. you might get away with giving your user permission on /dev/dri/* and /dev/input/* (e.g. adding your user to the groups that have permissions there) but a proper solution would be to have your seat set up correctly on login. I think something like elogind or an alternative like systemd-logind is missing.

**Comment by acoolstraw** [comment]
I am pretty sure you just need `seatd` and `polkit`, should work.

Also make sure to install fonts, installing the `sway` package generally pulls all the dependencies.

**Comment by Relwi** [comment]
> I am pretty sure you just need `seatd` and `polkit`, should work with those two packages installed.
> 
Omg thank you so much, I have installed `seatd` but not `polkit`, now it works, thanks!

**Comment by acoolstraw** [comment]
`polkit` may be necessary if you use Pipewire btw
