### ISSUE TITLE
Key repeat stops working after entering/exiting screen lock and then using a keybind

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#510]
Tested with gtklock and swaylock.

1. Run swaylock.
2. Exit swaylock.
3. Use any keybind. Doesn't have to be with a modifier apparently, I use a keybind to mute on Pause and that triggers it too.
4. Key repeat stops working.

Getting key repeat to work again after that is very inconsistent, sometimes it seemed to work again just after switching windows. Quitting the running application looked to work at times, at others it didn't. Reconfigure worked at first but then it broke again after using a keybind I think? No clue what exactly is going on there.

**Comment by Consolatis** [comment]
Does it only happen when running swaylock via keybind or also when running swaylock from a terminal?

**Comment by Consolatis** [comment]
> but swaylock I only tested with terminal. 

nice. So to remove some keybind related variables here:

- swaylock in terminal
- exit swaylock
- random keybind

should break key-repeat

**Comment by johanmalm** [comment]
Found the problem. Just leaving a note here so that nobody wastes time on it.

In `wlr_seat_keyboard_notify_enter()` we need to provide an array of unbound-keycodes (i.e. any that are not part of a key-binding) instead of kb->keycodes.
