### ISSUE TITLE
Mouse cursor stutters/lags when tabbing out of graphically intense game and moving it over the SSD title bar

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#512]

**Comment by Consolatis** [comment]
As discussed on IRC: might be related to us setting the cursor image repeatably (even if not changed) which in turn causes wlroots to upload a new texture to the GPU way too often. Will need some investigation to either rule out that theory or to fix it by only setting the cursor image when its different than the last one.

**Comment by Consolatis** [comment]
If it isn't fixed by #536 feel free to complain, will then reopen this issue.
