### ISSUE TITLE
Unmanaged X11 windows may give focus to a wrong unmanaged window on unmap

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#520]
I think this should be a `wl_list_for_each_reverse()` instead, didn't test though.
We are adding to the list using `.prev` so the list is ordered correctly.
Thus `last created unmanaged xwayland surface` should be at the end of the list.

https://github.com/labwc/labwc/blob/d405a2b3c61fd5e82fbd4b719b86215d6b25469d/src/xwayland-unmanaged.c#L85-L95

**Comment by jlindgren90** [comment]
I wondered the same thing looking at that loop.  But I don't have a good test-case either.
