### ISSUE TITLE
Mouse focus issue (?) after new window is mapped under cursor

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#522]
Steps to reproduce:
1. Start Audacious in Qt 5 mode and display the Search Tool panel (docked inside the main window)
2. Drag the Search Tool panel header away from the main window to undock the panel (so that it becomes a floating window)
3. **Without moving the mouse** press and hold the left mouse button again
4. Attempt to move the Search Tool panel by moving the mouse around

Expected results:
The Search Tool panel moves with the mouse

Actual results:
The Search Tool panel does not move with the mouse

If the mouse is moved even a single pixel between steps 2 and 3, everything works as expected.  It's my guess that the Search Tool panel loses "mouse focus" (this is a thing in `wlroots` right?) due to being unmapped and remapped at the end of step 2.  Then it's necessary to move the mouse a smidge in order to give the Search Tool panel "mouse focus" again.

The same issue doesn't occur under Openbox.

edit: Numbering is hard.

**Comment by jlindgren90** [comment]
This is with `QT_QPA_PLATFORM=xcb` (so using XWayland).

**Comment by Consolatis** [comment]
> Tool panel loses "mouse focus" (this is a thing in wlroots right?)

Yes, it is. wlroots will send application a mouse enter event when newly entering a surface, same for leaving a surface.
Applications may use these events for example to set the cursor icon. See `cursor_rebase()` in `src/cursor.c`.

We are updating mouse focus in `process_cursor_motion)` so I think your theory is solid (unmapped, no mouse movement, click).

It might be enough to add a `cursor_rebase()` to the mouse press handler to fix this, AFAIR cursor_rebase checks if its the same surface and if yes simply returns.
