### ISSUE TITLE
Windows occasionally end up in weird half-unmaximized state

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#530]
Occasionally when attempting to unmaximize a window, it ends up in this weird in-between state:
![PXL_20220908_153354493](https://user-images.githubusercontent.com/1244737/189166109-cf4debcc-6a8d-43de-88b3-7af5c047a6c5.jpg)

There are a couple of things going on here:
- If the mouse cursor moves ever so slightly while pressed on the "unmaximize" button, `labwc` thinks we are trying to move the window by dragging on the titlebar (i.e. `interactive_begin()`).
- `interactive_begin()` changes `view->x` and `view->y` directly but is missing a call to `view_moved()`.  This leads to the scene-graph being out-of-date and not matching where `labwc` "thinks" the view is displayed.

I'll follow up with a pull request to fix at least the missing `view_moved()` call.

**Comment by Consolatis** [comment]
> If the mouse cursor moves ever so slightly while pressed on the "unmaximize" button, labwc thinks we are trying to move the window by dragging on the titlebar (i.e. interactive_begin()).

Yes, this one is slightly annoying. I think we have an issue for that somewhere.

> interactive_begin() changes view->x and view->y directly but is missing a call to view_moved(). This leads to the scene-graph being out-of-date and not matching where labwc "thinks" the view is displayed.

That should all be handled in `view_maximize()`:
`view->maximize()` -> `view_apply_*()` -> `view_move_resize()` -> `view->impl->configure()`

**Comment by Consolatis** [comment]
Might be related to 065c37d3f5eed86dc218c9722e245fa5fda9bd75 specifically the
https://github.com/labwc/labwc/blob/79d9cfcda6fbe8177dbe8b0ed810a347b2cb26e8/src/xwayland.c#L135-L140
part in the new configure handler in `xwayland.c`
In combination with the `interactive_begin()` hack:
https://github.com/labwc/labwc/blob/79d9cfcda6fbe8177dbe8b0ed810a347b2cb26e8/src/interactive.c#L49-L58

it might prevent the configure to go through normally.
So maybe we should just remove that hack and instead move the temporary `wlr_box` from
https://github.com/labwc/labwc/blob/79d9cfcda6fbe8177dbe8b0ed810a347b2cb26e8/src/interactive.c#L78-L80
to the top and then overwrite it, replacing the hack.

I didn't think this through completely but works in my head at least.
