### ISSUE TITLE
Grab mouse in xwayland (games) with multi-monitor setup

### ISSUE THREAD

**Issue by KaitoKariheddo** [labwc/labwc#534]
Playing games on multi-monitor setups result in mouse moving from one ot other monitor, e.g. if you look around ingame. 
According to the Arch Wiki wlroots already implement a catching extension. https://wiki.archlinux.org/title/wayland#Input_grabbing_in_games,_remote_desktop_and_VM_windows
Is it possible to activate this extension in labwc ?

**Comment by Consolatis** [comment]
Cursor constrains should be activated but its possible we are doing something incorrectly.

You can try to run your games via gamescope compositor on top of labwc as a work-around for now.

**Comment by KaitoKariheddo** [comment]
Thank you, gamescope works fine! Would be nice if you find the bug.

**Comment by Ph42oN** [comment]
I would like to see this feature too, as sometimes when i click outside game, my mouse still moves camera in game but keyboard goes into something else. I tried gamescope but it is not an option for me because adaptive sync does not work with it.

**Comment by Consolatis** [comment]
This should be fixed by #586.
If it isn't feel free to comment and we'll reopen this issue.
