### ISSUE TITLE
When switching from a game to an empty workspace the cursor becomes stuck (pointer constraint issue?)

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#537]
You can probably test it by running glxgears or something via gamescope. Also happens in a windowed instance and just tabbing out and trying to switch back while the cursor is outside the window, the cursor gets stuck there too.

I think this only started happening recently, not 100% sure though.

**Comment by Consolatis** [comment]
Is this still a thing with the pointer constraints being merged and now actually constraining the pointer?
