### ISSUE TITLE
Sometimes the wrong window is resized with resize edges

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#543]
It's a bit fiddly to reproduce, but occasionally when attempting to resize a window by using left-click-and-drag on a resize edge, the window underneath it gets resized instead.

An example is the second resize attempt in this video:
https://user-images.githubusercontent.com/1244737/190072383-9dd3663c-43a6-48bc-a46f-c63c59f907cc.mp4

The Geany window should be resized from its bottom-right corner, but instead the terminal window underneath is resized.

I think this is because internally, the resize actually starts on the first cursor-motion event (not the cursor-press event), and that's when the `view` and `resize_edges` are chosen.  But when the first motion event is reported, the mouse cursor may have already moved off of the resize-edge node.

To fix this, we probably just need to make sure that the `view` and `resize_edges` used for the interactive resize are computed in the cursor-press event, rather than the first cursor-motion event.

**Comment by Consolatis** [comment]
That might be because of the way Drag is implemented, not sure right now.
E.g. a button press is not a Drag, but a button press + movement is one and thus only then the mousebind triggers which then tries to find the view based on the current cursor coordinates.
Maybe we could reuse `seat->pressed.view` for this?

**Comment by jlindgren90** [comment]
> Maybe we could somehow reuse seat->pressed.view here?

My thought exactly.

I have a fix in my `master` branch here:
https://github.com/jlindgren90/labwc/commit/3a4f38d022138f2ac968975f802a2c902dd2b96f

It will be easier to backport after #541 is merged.
