### ISSUE TITLE
[Discussion] C++

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#548]
I'm wondering what the project's opinions are on allowing some use of C++.  I'm not suggesting a full-scale re-write of the code, but merely compiling the existing code as C++ and then starting to use some memory-safe/type-safe conveniences like destructors, `operator=()`, `std::string`, `str::unique_ptr`, etc.

We did something similar with Audacious a few years back, and in my opinion, it made the code much easier/more enjoyable to work with.

Maybe I'm jusy lazy, but trying to remember to `strdup()` and `free()` all the `char*`s, `wl_list_remove()` all the `wl_listener.link`s, etc., feels very tedious and error-prone to me.  With C++, we could wrap the resouce cleanup in a class destructor and then just let the compiler deal with it.

I don't personally see too many downsides here:

- Dealing safely with arcane stuff like `wl_list` and `wl_listener` already requires expert-level software background anyway, so I don't think we're raising the bar to entry for new developers very much by requiring some basic C++ knowledge.
- No increase in runtime dependencies, because labwc already links to libstdc++ anyway (due to the Pango -> HarfBuzz dependency, I believe).
- The biggest immediate hurdle to compiling as C++ is probably going to be the implicit casts from `void*` everywhere (which are illegal in C++) but making those casts explicit probably isn't a bad thing anyway.

I could start experimenting on a branch with some of the basic ideas fleshed out, if there's openness to the idea in principle.

**Comment by Consolatis** [comment]
I very much prefer the explicit usage of C (like `malloc()` -> `free()`) over C++ "magic" (and as consequence also don't have that much practical experience with it, actually close-to-none) but that is just my personal opinion. This is really something for @johanmalm to decide.

Regarding `sdt::string`: we aren't really manipulating that many strings and there is always glib we could use if required. Operator overloading is something I really dislike because the code doesn't make any sense without also reading the whole source of the class in case there is an operator overload. Function overloading flies a bit better for me, learned to actually like those when writing Java a long time ago.

**Comment by johanmalm** [comment]
I'm not anti-C++ but have never particularly grown to like it the way I like C.
Truth be told, I don't know it particularly well so would feel a bit uneasy providing governance and oversight in that space.
RAII certainly has its advantages - I get that :smile: I've never explored if it can be done in C.
Sorry, that's a bit vague. Probably need a longer discussion.

**Comment by Consolatis** [comment]
> Hmm, are there particular aspects of C++ you consider "magic"? 

Well, it was an oversimplification. Basically it comes down to the first point: In C I personally prefer the explicit variant vs the implicit one. 

> What I'm attracted to is having the compiler prevent me from doing something like free() some struct while it's still pointed to by a `wl_list` somewhere, or while it contains a `char*` that also needs to be freed. 

But then you'd have to put in the logic in the destructor as well and the concept of constructor / destructor can also be used in C (example: `action_create()` -> `action_list_free()` or `ssd_*_create()` -> `ssd_*_destroy()`).

**Comment by jlindgren90** [comment]
> But then you'd have to put in the logic in the destructor as well

The difference being that in C++, I only have to write the destructor for my `String` or `Listener` class once, and then the compiler will generate the destructor for my `View` class (and every other parent class) with all the right calls to `~String()` and `~Listener()`.

In C, I still have to add the `free()` for every string and the `unregister()` for every `wl_listener` manually to `view_destroy()`.  And then remember to update `view_destroy()` whenever a new member is added to `struct view`.

It's certainly possible to do it in C, there's just more steps to remember.

And it's not a theoretical issue only; I believe there have been crashers already in labwc because a `wl_listener` wasn't unregistered when the parent struct was destroyed.  Some judicious just of C++ would make it possible to eliminate a whole class of "forgot to free" or "forgot to unregister" bugs.

**Comment by jlindgren90** [comment]
We can let this rest, thanks for the feedback. I think there's a lot that can still be done to improve the quality of the code without switching languages, so I'll focus my efforts on that.
