### ISSUE TITLE
Issues with cursor after disabling and re-enabling of output

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#561]
1. Cursor is always positioned at 0, 0
2. Cursor is hidden until moving
3. If the cursor was on the blank background before on/off its invisible until moving over a window, even while opening the root menu.

**Comment by Consolatis** [comment]
3. sounds partly related to not setting the server cursor to the same it is already set. So we it seems we are missing some reset of `seat->server_cursor` on output loss / restore.

**Comment by jlindgren90** [comment]
The `0, 0` passed to `wlr_cursor_move()` there are delta coordinates -- that should not be moving the cursor at all.

>    Cursor is always positioned at 0, 0
>    Cursor is hidden until moving
>    If the cursor was on the blank background before on/off its invisible until moving over a window, even while opening the root menu.

That sounds like exactly what used to happened before I added the `wlr_cursor_move() + `set_cursor_image()` workaround. Maybe `output_update_for_layout_change()` isn't being called for some reason, or something changed in `wlroots` that broke the workaround?

**Comment by jlindgren90** [comment]
For background, `wlroots` internally has a separate cursor (`wlr_output_cursor` if the comment is still correct) per output. So if you add an output, the cursor on it starts out essentially uninitialized -- at (0,0) and invisible. That's what the `wlr_cursor_move() + set_cursor_image()` workaround was supposed to solve.

**Comment by jlindgren90** [comment]
@Flrian Can you try #562 and see if it helps?

**Comment by jlindgren90** [comment]
@Flrian thanks for testing. Is this a single-monitor setup, or what type of layout do you have? How are you enabling/disabling outputs?

**Comment by jlindgren90** [comment]
I can reproduce the (0,0) issue now that I know it's a single-monitor setup.
