### ISSUE TITLE
Systemd-managed start + XDG autostart, yet another take

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#566]
Hi!
I've created an integrated and plugin-extendable script for managing sessions for sway (and other wayland WM's). It supports environment management, XDG autostart, including best effort clean stop. I hope it might be of interest.
https://github.com/Vladimir-csp/uwsm/

**Comment by johanmalm** [comment]
Hi there. Long time indeed!
Looks interesting. Will have a look.
