### ISSUE TITLE
Add clear-keybind functionality

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#567]
We are missing an actual clear-keybind functionality. Maybe `actions_run()` could have a `bool` return value which allows the key combination to be delivered to the focused application instead? Or do we need a futher `Clear` action instead? Or do we solve this by implementing the suggestion above with deduplication + clearing of the bindings with empty action list? We could also add a `SendKeys` action which would possibly allow for some macro magic as well.

Currently its impossible to use `A-Left` or `A-Right` for applications while also using `<default />` for keybinds, even when setting the keybind to the new `None` action.

_Originally posted by @Consolatis in https://github.com/labwc/labwc/issues/529#issuecomment-1253201447_

**Comment by johanmalm** [comment]
> Currently its impossible to use `A-Left` or `A-Right` for applications while also using `<default />` for keybinds, even when setting the keybind to the new `None` action.

Very good point. Agree that we ought to have the ability to delete default keybinds.

We could also consider changing the default 'A-Left' to 'C-W-Left' or similar. I had noted that it interferes with going forwards + backwards in `firefox`.

**Comment by Consolatis** [comment]
I am not sure if we should change the defaults, it might confuse some users.
