### ISSUE TITLE
Usage of `wl_list_insert(list.prev, element)`

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#572]
# Background

[`wayland-util.h`](https://github.com/wayland-project/wayland/blob/master/src/wayland-util.h) provides macros and functions for doubly-linked lists. They are very similar to the Linux kernel [`list.h`](https://github.com/torvalds/linux/blob/master/include/linux/list.h) implementation and are used as the defacto way of doing lists in wlroots and therefore by us.

# The Inconsistency

Consider the following commonly used list functions/macros.

```
wl_list_insert(list, element);

wl_list_for_each(element, list, link) {
	foo(element);
}
```

Anyone not used to this interface could be forgiven for thinking that `wl_list_insert()` adds the element to the end of the list, so that when iterating over the list the oldest element comes first.

Well, it doesn't. `wl_list_insert()` adds the element at the head/front :smile: This is good for implenting stacks (last in first out).

So, if you want a queue (first in first out) - like `.append()` in python - then you've got three options:

1. Use `wl_list_insert(list.prev, element)` (i.e. use `list.prev` instead of `list`). This adds the element to the tail of the list. We do this quite a lot in `labwc`.
2. Use `wl_list_insert()` and then iterate with `wl_list_for_each_reverse()` - basically what most people would probably think of as a queue in reverse.
3. Craft your own `wl_list_insert_tail()` which we did [here](https://github.com/labwc/labwc/blob/d424514e24bbee1c32b19c9192a065c18c9e7fe5/src/desktop.c#L72) and then iterate using `wl_list_for_each()`

Interesting, the Linux kernel calls the equivalent `list_add()` (stack) and `list_add_tail()` (queue).

I did some quick analysis on our `labwc`:

- `ack wl_list_insert src/ | grep -v prev | wc -l` gives 12
- `ack wl_list_insert src/ | grep prev | wc -l` gives 14
- `ack wl_list_for_each_reverse src | wc -l` gives 14

Interestingly wlroots uses wl_list_insert() without `prev` 157 times and with `prev` 17 times. I haven't analysed, but suspect the 157 times is when the order does not matter and the 17 is when they really want a queue.

# Options

1. Ignore this.
2. Make a note in `CONTRIBUTING.md` to say that we use the `link.prev` approach when we desire a queue-like list. Consistent with wlroots.
3. Put our `wl_list_insert_tail()` in `src/common`. We ought to really drop the `wl_` as that prefix belongs to the Wayland library. We could consider renaming it to `list_append()`, `list_insert_tail()`, `list_add_tail()`, `list_add()`, `list_push_end()`... run out of steam.

If going with (2) or (3) I suppose we ought to review all the instances of `wl_list_for_each_reverse()` to see if want to reverse the ordering to make it more intuitive for future developers.

**Comment by Consolatis** [comment]
We could also put something like this in src/common
```c
#define lab_wl_list_append(list, el) wl_list_insert((list).prev, el)
```

**Comment by johanmalm** [comment]
I think we're pretty aligned :smile:

> I really don't like this. IMO `_reverse` should only be used if we actually want to loop in reverse over a list...

Agree. Just threw it in for good measure.

> > 3. Put our `wl_list_insert_tail()` in `src/common`. We ought to really drop the `wl_` as that prefix belongs to the Wayland library.
> 
> I would prefer this variant in combination with a note in `CONTRIBUTING.md`. Regarding the naming we could also use something like this
> 
> ```c
> #define lab_wl_list_append(list, el) wl_list_insert((list)->prev, el)
> ```

Yes, maybe that's the simplest. Should we be brave and just call it `wl_list_append()`. I know it goes against the grain to use the prefix of a library, but it would look so much more consistent.

**Comment by johanmalm** [comment]
Is it better to implement as a function to avoid macros issues, improve stack-traces, and so on?

Could just do it as a static inline and keep it in a very small header file.
https://github.com/jgmenu/jgmenu/blob/f64d38c247fa1b09ba1db11d364c6c2a39d0d8e7/src/list.h#L86

**Comment by Consolatis** [comment]
Could you expand on the "macros issues" and "improve stack-traces" points?
As for now I personally I don't have a strong preference in either direction.

**Comment by Consolatis** [comment]
Good points. Lets use a function then.
