### ISSUE TITLE
Add CLI option to logout/exit from labwc session

### ISSUE THREAD

**Issue by hellium6** [labwc/labwc#573]
Openbox has a --exit CLI option which makes it easy to have a menu with logout option.

```
$ openbox --help
...
  --exit              Exit Openbox
```

labwc only has a "Exit" menu in the desktop right click menu and no CLI argument to do the same thing. Please make this available.

**Comment by johanmalm** [comment]
We handle `SIGTERM` for this purpose just as we handle `SIGHUP` for reconfigure.

So just do `killall -s SIGTERM labwc` and the compositor will gracefully exit :smile:

I prefer it this way in interest of simplicity.

**Comment by hellium6** [comment]
It's weird, but I'll take it.

1\. I see SIGHUP is mentioned in manpage:

> The configuration file and theme are re-loaded on receiving signal SIGHUP.

But not SIGTERM.

2\. Can the killall command be included in the manpage? It would save a lot of typing.

**Comment by jlindgren90** [comment]
> So just do killall -s SIGTERM labwc and the compositor will gracefully exit 😄

An improvement to this would be to set a `LABWC_PID` environment variable on launch so that a user could run multiple sessions, and still be able to kill the right one.

Probably not a common use case though.

**Comment by johanmalm** [comment]
^Now that we support virtual keyboards we could also use wtype to issue a key-combination to exit a particular instance of labwc.

**Comment by Consolatis** [comment]
> use wtype to issue a key-combination to exit a particular instance of labwc

That would also work I guess.

I think the `LABWC_PID` env var approach could be done as well though, should be easy to implement and seems all around more elegant to me than to trigger keybinds via `wtype`.

**Comment by johanmalm** [comment]
^ Yes, simple and elegant. Let’s do the LABWC_PID

**Comment by Consolatis** [comment]
implemented by #580:

`labwc --reconfigure` reloads the configuration
`labwc --exit` exits the compositor
