### ISSUE TITLE
Cannot switch between desktops 

### ISSUE THREAD

**Issue by 1qh** [labwc/labwc#576]
Here's my [rc.xml](https://github.com/1qh/arch-setup/blob/master/labwc/rc.xml)

Everything works but `W-1 / W-2` or `W-Left / W-Right` didn't do anything. Did I configure it properly?

Arch Linux.
labwc 0.5.3 installed from AUR.

Thanks a lot!

**Comment by Consolatis** [comment]
0.5.3 doesn't support workspaces. You'd need to run the master branch / labwc-git from AUR for that.

**Comment by 1qh** [comment]
It works now. Thanks!

**Comment by stefonarch** [comment]
Not to open another issue, but I can't just configure working shortcuts for workspace switching and the link to the `rc.xml` above is 404:

```
    <keybind key="C-A-Right">
      <action name="GoToDesktop" /><right />
    </keybind>
    <keybind key="C-A-Left">
      <action name="GoToDesktop" /><left />
    </keybind>
```

Any hint on the correct syntax?

**Comment by Consolatis** [comment]
See also:
- https://labwc.github.io/tips-and-tricks.html regarding the different ways to specify actions
- https://labwc.github.io/labwc-actions.5.html for the argument naming

I guess we could actually sync the man pages with [docs/rc.xml.all](../tree/master/docs/rc.xml.all) e.g. use `<action name="foobar" arg="barfoo" />` there as well to reduce confusion.

**Comment by stefonarch** [comment]
@Flrian Thanks, I lost so much time about that.

manpage should be updated IMHO:

```
     <action name="GoToDesktop"><to>
           Switch to workspace. Supported values are "last",
           "left", "right" or the full name of a workspace or
           its index (starting at 1) as configured in rc.xml.

```
```

     <action name="GoToDesktop" to="">
           Switch to workspace. Supported values are "last",
           "left", "right" or the full name of a workspace or
           its index (starting at 1) as configured in rc.xml.
```
