### ISSUE TITLE
Please implement <action name="Lower">

### ISSUE THREAD

**Issue by jech** [labwc/labwc#578]
I'm currently exploring the possibility of switching from X11+OpenBox to labwc, and I cannot find a way to reproduce the following OpenBox behaviour:
```
    <keybind key="A-Down">
      <action name="Lower"/>
      <action name="FocusToBottom"/>
      <action name="Unfocus"/>
    </keybind>
```
I'm not sure about the focusing behaviour, but I'm fairly positive that the "Lower" action is not implemented in labwc.  Since it seems to my untrained eyes like a three line modification, I'd be grateful if it could be implemented.

**Comment by johanmalm** [comment]
I’m easy. They’re in the scope document as B - so very much at the discretion of the devs. 

The “Lower” action looks technically easy to implement. I suspect the focus ones will take some discussion and may add unwanted complexity.

Would you mind describing the use-case as a starting point? That will help determine if the benefits outweigh the “costs”.

**Comment by jech** [comment]
> Would you mind describing the use-case as a starting point?

With pleasure.

I use focus-follows-mouse, and I usually have at least one stack of
overlapping windows.  For example, if I'm writing in TeX, I might have an
editor window and a terminal that both cover the left half of my screen,
and the typeset PDF in the right half of my screen.
```
+-------+  +-------+
|       |  |       |
| Emacs |  |       |
|       |  |       |
++-----+|  | PDF   |
||     ||  |Viewer |
||XTerm||  |       |
||     ||  |       |
|+-----+|  |       |
+-------+  +-------+

```

In order to switch between the editor and the terminal, I hit Alt-down,
which rotates the stack of windows that are under the mouse cursor: it
moves the focused window to the bottom of the stack, then focuses the new
top window, as expected with focus-follow-mouse.  This is way faster than
hitting Alt-tab, which would force me to rotate through all the windows,
even those that are not under the mouse.

**Comment by Consolatis** [comment]
Thanks for the explanation. Adding the new `Lower` action sounds doable and reasonable.

I am not sure if we need additional infrastructure in place to also have it working as intuitive as possible with `focus.followMouse` enabled / disabled. Without that we might actually (keyboard)focus the right window instead if it was previously activated and is thus the "topmost" window after lowering the editor. This might be what is expected by a user or maybe it is not.

Even with `focus.followMouse` enabled I don't think our current infrastructure for `cursor_update_focus()` deals with keyboard focus at all, AFAIR we are only doing that when the cursor moves. So we would need to add that as well.

**Comment by jech** [comment]
PR #829 fixes the issue.  I can now say
```
    <keybind key="A-Down">
      <action name="Lower"/>
      <action name="Focus"/>
    </keybind>
```
which in my limited testing appears to have the right behaviour.

**Comment by Consolatis** [comment]
Is the separate `Focus` action still required on current master with `followMouse` enabled?
It seems like it should not as we are now calling `cursor_update_focus()` after moving the window to the back which in turn gives keyboard focus to the surface under the cursor.

**Comment by jech** [comment]
> Is the separate Focus action still required on current master with followMouse enabled?

No.  Labwc currently has much more consistent FFM support than OpenBox ever had.
