### ISSUE TITLE
Waybar tray menus break if icon is removed while menu is open

### ISSUE THREAD

**Issue by kode54** [labwc/labwc#579]
Not sure if this one is a bug in Waybar or in labwc. Basically, I quit Steam with the tray icon from Waybar, because its main window had stopped responding due to another issue possibly with XWayland. Then I accidentally right clicked on the icon again when it was quitting, then the icon disappeared. The menu disappeared as well, except for its window outline, which stayed on the screen. The space inside the outline also appeared to be blocking clicks to the desktop, as the root menu would not appear if I clicked inside the outline.

**Comment by johanmalm** [comment]
Is this with the latest labwc master branch?
I recognise the issues but they were patched quite a while ago.

**Comment by johanmalm** [comment]
Is it related to this?

**Comment by kode54** [comment]
I'm not sure. I'm using the `wlroots-git` and `labwc-git` PKGBUILDs from the AUR, so it should be using the latest version, which I just rebuilt tonight.

**Comment by johanmalm** [comment]
Okay, that’s fine. Just wanted to rule out that you were running with0.5.x series.

Can you reproduce it? If so, what are steps to reproduce.

If it happens again, can you kill the steam game with killall from a terminal?

**Comment by johanmalm** [comment]
This might be related.
https://github.com/labwc/labwc/commit/62ae87bbd9d90bdd3566f4fcff5b51be1425f800

Any detective work welcome.
If you’re able to build labwc, you could try reverting the commit to see if it solves the issue.

**Comment by johanmalm** [comment]
@kode54 Please could you provide steps to reproduce this issue.

**Comment by kode54** [comment]
Let me describe what I was doing, like I did on IRC.

Basically, I experienced a possible XWayland or other Wayland issue with the Xorg app, Steam.

I run my wlroots compositors using the project, [uwsm](https://github.com/Vladimir-csp/uwsm), which I insert the snippet for into my .zprofile and log in from TTY1.

I use the following autostarts:
```
# Set background picture.
swaybg -i /home/chris/Pictures/BingWallpaper/20220923-GoldenJellyfish_EN-US6743816471_UHD.jpg >/dev/null 2>&1 &

# Configure output directives
kanshi >/dev/null 2>&1 &

# Launch a panel
waybar >/dev/null 2>&1 &

# Enable notifications
mako >/dev/null 2>&1 &

# Lock screen after 5 minutes; turn off display after another 5 minutes

swayidle -w \
	timeout 300 'swaylock -f -c 000000' \
	timeout 600 'wlopm --off \*' \
	resume 'wlopm --on \*' \
	before-sleep 'swaylock -f -c 000000' >/dev/null 2>&1 &

# this appears to be broken right now - switching back to stock xorg
#xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2

# xdg-autostart >/dev/null 2>&1 &

systemd-notify --ready
```

And I have Steam starting through my .config/autostart/steam.desktop file, along with some other apps. (Alacritty, TeamViewer, Discord, Firefox, Element, Keybase, CoreCtrl, and Telegram Desktop.)

Steam is responsive and functional for the first minute or so within logging in, so I go on to do other things with other apps in the session.

Within a minute or two of login, the Steam Library page has locked up, and the entire window is unresponsive to mouse input. I can't resize or move it, either.

So I attempted to Exit Steam through the tray icon interface menu. It was taking its sweet time, so I opened the tray menu again, and then Steam quit itself precisely while the menu was open.

The menu disappeared when Steam quit and the tray icon was removed. This left a 1px black outline on the screen where the menu was, and the desktop's root menu would not open if I clicked within this black outline.

I do not know if this is reproducible with my current configuration, as I have since doubled my RAM to 32GiB. I will try again tomorrow night if I remember to attempt to reproduce it.

**Comment by kode54** [comment]
Okay, the outline does go away on its own after a while. Apparently something gets stuck for a moment.

**Comment by Consolatis** [comment]
> Within a minute or two of login, the Steam Library page has locked up, and the entire window is unresponsive to mouse input. I can't resize or move it, either.

I'd think this one is the actual issue here. Do you get further clues on why this happens when you start steam via terminal?

**Comment by Consolatis** [comment]
Closing for now, feel free to reopen if this still happens on latest master and you have further clues which could aid the debug process or reproduce this (preferably without Steam).
