### ISSUE TITLE
garbled display with latest labwc git

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#583]
I can't get a readable display, running dual head AMD ryzen 5, AMD graphics.

I've narrowed it down to d15f3005

I just copied in 694e9bbb9d7114f39311d93e885e010606a88dae (which is wlroots latest ATM) to subprojects/wlroots.wrap and this fixes my problem. There have been many commits to wlroots since 68c8cef38edafa5e52532e0b43a4888554168361 as I'm sure you are aware so I'm not prepared to narrow that range down! 

Thanks!

**Comment by Consolatis** [comment]
Thanks for the investigation.
As discussed via IRC just updating the .wrap file to the latest wlroots master should be enough in this case, no need for further bisecting.
