### ISSUE TITLE
1-second lag in closing XWayland menus (XWayland issue?)

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#597]
Since updating xwayland from 22.1.3 to 22.1.4, there is approximately a one-second lag from the time an XWayland menu item is selected until the menu closes.  This leads to confusion as to whether the menu selection took effect or not, since there is no visual response until one second later.

With xwayland 22.1.3, menus close more-or-less instantly.

I reported this upstream as https://gitlab.freedesktop.org/xorg/xserver/-/issues/1399, but I'm not sure yet if there is something we can do on the compositor side to fix/mitigate the issue.

**Comment by Consolatis** [comment]
Not sure why this relies on the destroy signal, shouldn't the menu window send an unmap signal first anyway?
After a quick look at `src/xwayland-unmanaged.c` it seems we are not actually handling the unmap signal by calling `wlr_scene_node_set_enabled(node, false)` so this very much seems like a labwc bug.

**Comment by jlindgren90** [comment]
Adding `wlr_scene_node_set_enabled(unmanaged->node, false)` seems to fix it. I'll create a PR. Thanks for the suggestion!
