### ISSUE TITLE
Headless causing failed assert

### ISSUE THREAD

**Issue by suncore** [labwc/labwc#605]
I was trying to run labwc in headless mode but it failed on an assert:

$ export WLR_RENDER_DRM_DEVICE=/dev/dri/renderD128
$ export WLR_BACKENDS=headless 
$ export WLR_LIBINPUT_NO_DEVICES=1
$ ./labwc
00:00:00.062 [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
labwc: types/output/render.c:169: output_test_with_back_buffer: Assertion `output->impl->test != NULL' failed.
Aborted (core dumped)

Maybe this is not supposed to work yet though. I was just thinking since headless should be a part of wlroots it might work anyway. The above sequence works ok for wayfire, sway and tinywl.

**Comment by Consolatis** [comment]
Can you try with `labwc -d` ?

I tried it nested with `WLR_RENDERER=gles2` and `WLR_RENDERER=pixman` and I didn't hit the assert.
The difference might be the nested aspect vs. running it from a TTY.

**Comment by suncore** [comment]
I'm attaching 3 outputs. First with unset WLR_RENDERER and then with gles2 and then with pixmap. Same results. I'm starting labwc from within a vnc session. How do I start it nested?
[out.txt](https://github.com/labwc/labwc/files/9931652/out.txt)
[out-pixman.txt](https://github.com/labwc/labwc/files/9931653/out-pixman.txt)
[out-gles2.txt](https://github.com/labwc/labwc/files/9931654/out-gles2.txt)

**Comment by Consolatis** [comment]
Ah, it seems to work with a more recent wlroots version.
You can try if this fixes it:
```sh
cd subprojects/wlroots
git checkout master
git pull
cd ../..
meson compile -C build
```
I also added a [PR](https://github.com/labwc/labwc/pull/606) to update the wlroots version. 

> How do I start it nested?

You can started it nested by just executing labwc within an existing wayland or x11 session (e.g. from within sway, wayfire or tinywl).

**Comment by suncore** [comment]
Thanks! That fixed it.
