### ISSUE TITLE
Add support for SVG 

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#609]
Currently labwc themes only support XBM images. However, XBM images do not scale and this quickly becomes an issue due to HiDPI. Creating larger XBM images breaks multi-DPI cases (like HiDPI laptop and regular monitor).

**Comment by Consolatis** [comment]
@johanmalm I guess this one requires some discussion about where to draw the line on feature creep vs legit usability improvements vs openbox theme standards.

From the pure technical side of things, this should be relatively easy to implement as we are already using glib and everything other than the XBM parser is only dealing with pixel data anyway.
