### ISSUE TITLE
Firefox main window sees pointer hover while dragging right-click menu

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#621]
To reproduce:

- Open Firefox (this seems to be triggered by its GUI toolkit, and not Gtk-related, as programs that use Gtk directly don't exhibit this behavior).
- Press and hold the right mouse button on the web page, opening the right-click menu.
- Without releasing the button, move the mouse. Observe that the menu entries in the right click menu are not highlit when hovered, but the main Firefox window *does* respond as if the mouse is hovering in the corresponding position in that window (near the top-left).
- Release the right mouse button. The menu option under the cursor does not activate, but it will now be highlit as hovered.

Something seems to be wrong in how we give pointer focus to popups in the presence of a grab.

**Comment by bi4k8** [comment]
Comparing `WAYLAND_DEBUG=1` logs of FF under labwc and under Sway, it seems that the difference is that in labwc there's a `wl_pointer.enter` event emitted after the mouse button is pressed.

Stubbing out `update_pressed_surface` in `cursor.c` makes Firefox behave correctly, but breaks native Gtk programs. I'm very curious how Sway makes this work.

**Comment by bi4k8** [comment]
Ah. Native Gtk programs are broken under Sway.

**Comment by bi4k8** [comment]
cc @jlindgren90 re: https://gitlab.gnome.org/GNOME/gtk/-/issues/3662#note_1549292

**Comment by bi4k8** [comment]
This horrible hack makes Firefox behave:
```diff
diff --git a/src/cursor.c b/src/cursor.c
index 54d6532..5df0b53 100644
--- a/src/cursor.c
+++ b/src/cursor.c
@@ -264,6 +264,16 @@ update_pressed_surface(struct seat *seat, struct cursor_context *ctx)
         */
        if (seat->pressed.surface && ctx->surface != seat->pressed.surface) {
                struct wlr_surface *toplevel = get_toplevel(ctx->surface);
+
+               /* detect Firefox and bail out. Firefox is broken. */
+               if (wlr_surface_is_xdg_surface(toplevel)) {
+                       struct wlr_xdg_surface *xdg_surface = wlr_xdg_surface_from_wlr_surface(toplevel);
+                       const char* app_id = xdg_surface->toplevel->app_id;
+                       if (app_id && !strcmp(app_id, "firefox")) {
+                               return false;
+                       }
+               }
+
                if (toplevel && toplevel == seat->pressed.toplevel) {
                        /* No need to recompute resize edges here */
                        seat_set_pressed(seat, ctx->view,
```

**Comment by Consolatis** [comment]
Heh, that indeed is some beautifully horrible hack. Nice investigation.
Personally I'd rather prefer to have Firefox slightly broken than to ship something like this though.

**Comment by bi4k8** [comment]
I had hoped the `wlr_surface_is_xdg_surface` check would protect us from `wlr_xdg_surface_from_wlr_surface` returning `NULL`.

I agree this is awful and not something we want to ship. I'll look into what it would take to fix Firefox.

**Comment by jlindgren90** [comment]
Somehow under Weston, both native GTK menus and the Firefox right-click menu are working. It would be nice to figure out what Weston is doing differently.
