### ISSUE TITLE
Document how to enable NumLock automatically

### ISSUE THREAD

**Issue by jlindgren90** [labwc/labwc#637]
I couldn't find in the documentation how to enable keyboard NumLock automatically.
Do we have a method for doing this?

For Sway, you can apparently enable NumLock by adding to `~/.config/sway/config`:
```
input type:keyboard xkb_numlock enabled
```

**Comment by johanmalm** [comment]
I don’t know how that’s done. We’ve not implemented anything to support numlock enable/disable.
It’s possible that some environment variable (XKB_DEFAULT_OPTIONS or similar) can do this, but I’ve not investigated.

**Comment by 01micko** [comment]
This is what I am using right now - _ugly_

```c
#include <fcntl.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <linux/uinput.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {
	struct uinput_setup setup = {.name = "numlock"};
	struct input_event ev;
	int uinput, i;

	uinput = open("/dev/uinput", O_WRONLY | O_NONBLOCK);
	if (uinput < 0) {
		return EXIT_FAILURE;
	}

	if ((ioctl(uinput, UI_SET_EVBIT, EV_KEY) < 0) ||
		(ioctl(uinput, UI_SET_EVBIT, EV_SYN) < 0) ||
		(ioctl(uinput, UI_SET_KEYBIT, KEY_NUMLOCK) < 0) ||
		(ioctl(uinput, UI_DEV_SETUP, &setup) < 0) ||
		(ioctl(uinput, UI_DEV_CREATE) < 0)) {
		close(uinput);
		return EXIT_FAILURE;
	}

	sleep(5); /* time for device to be created - could be slow */
	for(i=1; i>=0; i--) {
		ev.type = EV_KEY;
		ev.code = KEY_NUMLOCK;
		ev.value = i;

		if (write(uinput, &ev, sizeof(ev)) != sizeof(ev)) {
			return EXIT_FAILURE;
		}
	}

	ev.type = EV_SYN;
	ev.code = 0;
	ev.value = 1;

	if (write(uinput, &ev, sizeof(ev)) != sizeof(ev)) {
		return EXIT_FAILURE;
	}

	ioctl(uinput, UI_DEV_DESTROY);
	close(uinput);

	return EXIT_SUCCESS;

}
```

Can be started however you like and is independent of UI. It's _supposed to toggle_ but doesn't under wlroots. The timing is the problem because on slower kit the sleep would well be useless. Need to find a graceful way to find when the device is ready.

**Comment by 01micko** [comment]
BTW, the original (used to work in labwc-0.5.x) is [here](https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-petbuilds/labwc/numlockt.c)

**Comment by 01micko** [comment]
So sway uses [`xkbcommon-names.h`](https://github.com/swaywm/sway/blob/81518e299c8eacaa9563c61e550db5f0a424ce61/sway/input/keyboard.c#L10) to set various settings, including numlock, so it's a bit more than documenting @johanmalm @jlindgren90 .

We do need a method.

**Comment by johanmalm** [comment]
Just scanned on phone, but probably this:

https://github.com/swaywm/sway/blob/81518e299c8eacaa9563c61e550db5f0a424ce61/sway/input/keyboard.c#L1029

https://github.com/swaywm/sway/blob/81518e299c8eacaa9563c61e550db5f0a424ce61/sway/input/keyboard.c#L1044

Fancy trying a patch? :smile:

**Comment by 01micko** [comment]
> Fancy trying a patch? smile

Sure!

**Comment by Arnaudv6** [comment]
I have a [dirty hack](https://github.com/Arnaudv6/labwc/tree/master) for this.
The part I'm struggling with is restoring the keyboard state when leaving labwc.

**Comment by 01micko** [comment]
Well, I set this in `~/.config/labwc/environment` and it works:
```
XKB_DEFAULT_OPTIONS=numpad:mac
```

_however_, some undesirable behaviour:
- numlock led doesn't work
- numlock _cant_ be turned off!

**Comment by Arnaudv6** [comment]
might be affected by #602 refactoring

**Comment by stefonarch** [comment]
I miss this setting.
`XKB_DEFAULT_OPTIONS=numpad:mac` doesn't work here.

`XKB_NUMLOCK_DEFAULT_STATE = true` works in sway, `kb_numlock_default_state = true` in wayfire, hopefully it will be implemented in labwc too.

**Comment by SpidFightFR** [comment]
+Up ! would be cool if it was implemented !
