### ISSUE TITLE
Cannot set adaptive sync

### ISSUE THREAD

**Issue by heroin-moose** [labwc/labwc#642]
I have a Matebook X Pro 2022 with a 90Hz monitor supporting VRR.

However:

```
$ drm_info | grep vrr
│   │       └───"vrr_capable" (immutable): range [0, 1] = 1

$ wlr-randr --output eDP-1 --adaptive-sync enabled

$ grep 'adaptive sync' labwc.log
00:00:00.458 [INFO] [../labwc/src/output.c:180] enable adaptive sync on eDP-1
00:00:00.458 [ERROR] [../labwc/src/output.c:184] adaptive sync failed, ignoring
```

**Comment by Consolatis** [comment]
Does it work when you set it in rc.xml and restart labwc?

Starting labwc with debug output (`labwc -d`) might reveal some more information from wlroots which can be grepped for like `grep -C 10 'adaptive sync' labwc.log`.

**Comment by heroin-moose** [comment]
I have both :(

**Comment by heroin-moose** [comment]
I have rather lengthy DRM log too, but cannot find anything related there.

**Comment by johanmalm** [comment]
> `00:00:00.458 [ERROR] [../labwc/src/output.c:184] adaptive sync failed, ignoring`

Do you get this from tty or running nested?

It's the first time we've done a `wlr_output_test_state()` so might have implemented it wrong.
https://github.com/labwc/labwc/blob/56f8837ca60dd19e395e38610ff543994c0e5ff0/src/output.c#L183
Grateful if you have time to experiment / look into it.

Does it work with sway?

**Comment by heroin-moose** [comment]
> Do you get this from tty or running nested?

```
$ labwc -dV >labwc.log 2>&1
```

> Does it work with sway?

I'll try.

**Comment by Consolatis** [comment]
There is a wlroots [commit](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/8cf1bd5582e9d40a6a2305ba8cefb16c0942010b) in the 0.16 branch talking about fixing the adaptive sync test. Might worth a try to re-test this with the latest wlroots 0.16 branch.

**Comment by Consolatis** [comment]
What is the current state of this issue, does enabling adaptive sync via config file work using wlroots 0.16.2 or the wlroots 0.16 branch?
If yes, does it work during runtime via wlr-randr as well?

Related: #777

**Comment by heroin-moose** [comment]
Nope. Latest labwc from git (bundled wlroots):

```
pogg ~$ wlr-randr --output eDP-1 --adaptive-sync enabled
pogg ~$ wlr-randr
eDP-1 "Thermotrex Corporation 0x1422 0x00007730 (eDP-1)"
  Make: Thermotrex Corporation
  Model: 0x1422
  Serial: 0x00007730
  Physical size: 300x200 mm
  Enabled: yes
  Modes:
    3120x2080 px, 48.000000 Hz
    3120x2080 px, 60.000000 Hz
    3120x2080 px, 90.000000 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 2.000000
  Adaptive Sync: disabled
  ```

**Comment by Consolatis** [comment]
I am not sure we actually support setting adaptive sync during runtime.

As far as I see we only set adaptive sync when creating a new output, e.g. usually when starting up labwc.
While looking at the code I think we might be doing something wrong though: we create an empty state (e.g. no resolution or similar), enable adaptive sync on that state and then ask wlroots to confirm if the state is valid. I think we'd need to actually get a copy of the current state, enable adaptive sync on that state and then let wlroots test it.

So this seems double broken:
- when trying to enable adaptive sync when starting up (possibly)
- we are not handling the `adaptive_sync_enabled` field of the output management config, e.g. what we get when somebody uses wlr-randr or kanshi and friends

**Comment by Consolatis** [comment]
This might fix the runtime selection:
```diff
diff --git a/src/output.c b/src/output.c
index 440e56d..bafab85 100644
--- a/src/output.c
+++ b/src/output.c
@@ -310,6 +310,7 @@ output_config_apply(struct server *server,
 			}
 			wlr_output_set_scale(o, head->state.scale);
 			wlr_output_set_transform(o, head->state.transform);
+			wlr_output_enable_adaptive_sync(o, head->state.adaptive_sync_enabled);
 		}
 		if (!wlr_output_commit(o)) {
 			wlr_log(WLR_ERROR, "Output config commit failed");
```
Testing appreciated as I don't have access to a working VRR setup.

**Comment by heroin-moose** [comment]
It horribly works:

```
pogg ~$ wlr-randr --output eDP-1 --adaptive-sync enabled








































































pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$
pogg ~$ wlr-randr
eDP-1 "Thermotrex Corporation 0x1422 0x00007730 (eDP-1)"
  Make: Thermotrex Corporation
  Model: 0x1422
  Serial: 0x00007730
  Physical size: 300x200 mm
  Enabled: yes
  Modes:
    3120x2080 px, 48.000000 Hz
    3120x2080 px, 60.000000 Hz
    3120x2080 px, 90.000000 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 2.000000
  Adaptive Sync: enabled
```

The screen goes blank and you can see that Enter is sent multiple times, but the final result is okay.

**Comment by Consolatis** [comment]
The repeated enter is the result of the client (terminal emulator) key repeat timer. It seems enabling VRR blocks wlroots (and thus us) until the kernel reports success for the modeset.

**Comment by heroin-moose** [comment]
Not ideal, but not that big of deal since kanshi usually does the job.

**Comment by heroin-moose** [comment]
Your theory is correct :)

**Comment by heroin-moose** [comment]
Btw, VRR also works, the power consumption reduced about ~0.75W. Gives my an additional hour or so at full capacity.

**Comment by heroin-moose** [comment]
However, the config does not work, only wlr-randr.

**Comment by heroin-moose** [comment]
```
$ cat .config/labwc/rc.xml
<?xml version="1.0"?>
<labwc_config>
  <core>
    <adaptiveSync>yes</adaptiveSync>
...
pogg ~$ wlr-randr
eDP-1 "Thermotrex Corporation 0x1422 0x00007730 (eDP-1)"
  Make: Thermotrex Corporation
  Model: 0x1422
  Serial: 0x00007730
  Physical size: 300x200 mm
  Enabled: yes
  Modes:
    3120x2080 px, 48.000000 Hz
    3120x2080 px, 60.000000 Hz
    3120x2080 px, 90.000000 Hz (preferred, current)
  Position: 0,0
  Transform: normal
  Scale: 2.000000
  Adaptive Sync: disabled
```

**Comment by Consolatis** [comment]
Yes, that one liner patch above was just for the runtime changes.
This one should fix the init one:
```diff
diff --git a/src/output.c b/src/output.c
index 440e56d..63e3ae1 100644
--- a/src/output.c
+++ b/src/output.c
@@ -150,6 +150,18 @@ new_output_notify(struct wl_listener *listener, void *data)
 		}
 	}
 
+	if (rc.adaptive_sync) {
+		wlr_output_enable_adaptive_sync(wlr_output, true);
+		if (!wlr_output_test(wlr_output)) {
+			wlr_log(WLR_ERROR, "enabling adaptive sync failed for output %s",
+				wlr_output->name);
+			wlr_output_enable_adaptive_sync(wlr_output, false);
+		} else {
+			wlr_log(WLR_INFO, "adaptive sync enabled successfully for output %s",
+				wlr_output->name);
+		}
+	}
+
 	wlr_output_commit(wlr_output);
 
 	struct output *output = znew(*output);
@@ -206,20 +218,6 @@ new_output_notify(struct wl_listener *listener, void *data)
 	wlr_scene_node_raise_to_top(&output->layer_popup_tree->node);
 	wlr_scene_node_raise_to_top(&output->session_lock_tree->node);
 
-	if (rc.adaptive_sync) {
-		wlr_log(WLR_INFO, "enable adaptive sync on %s", wlr_output->name);
-		struct wlr_output_state pending = { 0 };
-		wlr_output_state_set_adaptive_sync_enabled(&pending, true);
-		if (!wlr_output_test_state(wlr_output, &pending)) {
-			wlr_log(WLR_ERROR, "adaptive sync failed, ignoring");
-			wlr_output_state_set_adaptive_sync_enabled(&pending, false);
-		}
-		if (!wlr_output_commit_state(wlr_output, &pending)) {
-			wlr_log(WLR_ERROR, "failed to commit output %s",
-				wlr_output->name);
-		}
-	}
-
 	/*
 	 * Wait until wlr_output_layout_add_auto() returns before
 	 * calling do_output_layout_change(); this ensures that the
```

Testing appreciated, the log should state "adaptive sync enabled successfully"

**Comment by heroin-moose** [comment]
Works. IMO, this should be DEBUG with a different message:

```
+			wlr_log(WLR_ERROR, "enabling adaptive sync failed for output %s",
+				wlr_output->name);
```

I have two monitors and one is VRR, the second is not. The second one will always print errors in the log.

**Comment by Consolatis** [comment]
Good point. I'll change it to debug. Suggestions for a different message? I think it is fine if set to debug though.

**Comment by heroin-moose** [comment]
Hmm... Yeah, perhaps you are right, it seems there is no way to make a difference between

1. Failed because the output does not support VRR
2. Failed because something is wrong

**Comment by Consolatis** [comment]
Looks like it, there is a `drm_connector_supports_vrr()` function but we are only dealing with the wlroots output abstraction in labwc. We might spend some time to figure out how to get the underlying implementation and then link to libdrm to fetch that information but it seems a bit overkill for a debug log message.
