### ISSUE TITLE
Add default configs to docs/meson.build install step

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#643]
And figure out if there is some meson `get_option(docsdir)` available.

Suggested config examples:
- rc.xml
- rc.xml.all
- menu.xml

Not sure about
- autostart
- environment

Edit:
As per https://mesonbuild.com/Builtin-options.html it doesn't look like there is a `docdir` option so I guess we'd have to use something like [this](https://github.com/mesonbuild/meson/pull/6785#issuecomment-600206928) instead:
```
my_docdir = get_option('datadir') / 'doc' / meson.project_name()
```

**Comment by Consolatis** [comment]
Something like this seems to do the trick:
```diff
diff --git a/docs/meson.build b/docs/meson.build
index 953c5a8..a3264a2 100644
--- a/docs/meson.build
+++ b/docs/meson.build
@@ -23,3 +23,14 @@ if scdoc.found()
     )
   endforeach
 endif
+
+install_data(
+  [
+    'autostart',
+    'environment',
+    'menu.xml',
+    'rc.xml',
+    'rc.xml.all'
+  ],
+  install_dir: get_option('datadir') / 'doc' / meson.project_name()
+)
```

Maybe we should throw in a `README` as well which mentions the man pages and `~/.config/labwc/` directory.

**Comment by johanmalm** [comment]
Happy with this.
