### ISSUE TITLE
2 issues after PR #650

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#653]
imv now opens with ssd off screen. Same if you start labwc nested. Both windows open in the top left, might be related?

foot ssd gets moved partially off screen when snapping to edge. If I reconfigure labwc while foot is open and then snap it, it works fine.

[Screenshot showing both bugs](https://user-images.githubusercontent.com/4444593/204109708-3b8fe729-f901-4bf5-8084-90f321c49b7f.png)

**Comment by jlindgren90** [comment]
I'll look into this. I have an idea what the issue may be.

**Comment by jlindgren90** [comment]
I think both are the same issue. Should be fixed by #655.
