### ISSUE TITLE
Hide Alt+Tab Dialog

### ISSUE THREAD

**Issue by wesbluemarine** [labwc/labwc#672]
Is there a way to remove the dialog?

**Comment by johanmalm** [comment]
No. 

I have no issue with adding - maybe as a core.cycleViewOSD

https://github.com/labwc/labwc/blob/e4aa7cef765a81a6911839de16644eceeb2fb5e9/docs/rc.xml.all#L15

**Comment by Consolatis** [comment]
Should be relatively easy to implement (either by just disabling the OSD scene tree or actually preventing the rendering, 2nd option preferred but also a bit more involved as we still want to keep showing window previews / preview outlines).

PR welcome.
