### ISSUE TITLE
Implement Run or Raise

### ISSUE THREAD

**Issue by wesbluemarine** [labwc/labwc#673]
Is it possible to achieve something like [this](https://github.com/mkropat/jumpapp)? Could be nice especially for those that don't want to use a bar/panel.

**Comment by Consolatis** [comment]
If they implement wayland support via wlr-foreign-toplevel protocol (or some wrapper around it) you could potentially use that application directly. It should already work for X11 applications, you'd just have to configure the keybinds to call it.

I don't think we want to implement anything like that in the compositor itself, especially as we are already exposing the wlr-foreign-toplevel protocol.

**Comment by johanmalm** [comment]
Agree. 

The following link is a good starting point for listing app_ids of running applications + raising them.
https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/examples/foreign-toplevel.c

To write this well, you’d have to parse system .desktop files to translate app_id to Name, so gets a but cumbersome.

**Comment by Consolatis** [comment]
As alternative to the application mentioned above this should work for all compositors that support the wlr-foreigen-toplevel-management protocol:

```bash
#!/bin/bash

if ! wlrctl window focus "$1"; then
	"$1" &
	disown
fi
```
Requires https://git.sr.ht/~brocellous/wlrctl

**Comment by wesbluemarine** [comment]
Could be possible to adapt that script for something like file managers/text editors that don't have a fixed app_id?

**Comment by Consolatis** [comment]
They should have a fixed app_id, usually just the title differs.

If you press `A-Tab` the three columns are:
- `[xwayland / xdg-shel]` X11 application or wayland native one, can be ignored
- `app_id`
- `title`

`wlrctl` also supports matching by title. So you could do something like `wlrctl window focus title:"VLC media player"` or even combine the two like `wlrctl window focus vlc title:"VLC media player"` if you have multiple applications with the same app_id but different titles.
