### ISSUE TITLE
Issue on startup

### ISSUE THREAD

**Issue by MmePsychosis** [labwc/labwc#677]
Newly setup arch install. Have wlroots 0.15.1-6 installed and labwc 0.5.3-1 from AUR installed. 

Whenever I run `labwc` I get a black screen for a second and then kicked back to cli with the error: "labwc: render/wlr_texture.c:28: wlr_texture_from_pixels: Assertion 'stride > 0' failed.

**Comment by Consolatis** [comment]
That sounds like there is something wrong with either your GPU drivers or wlroots doesn't detect the right render node.
You can try `WLR_RENDERER=pixman labwc`, that should work but will run in software compositing mode.

Or if its indeed the issue of wlroots trying to use a wrong render node you can try something like `WLR_RENDER_DRM_DEVICE=/dev/dri/renderD128 labwc`. You can further look into `/dev/dri/by-path/` to decide which render node to use.

If neither of these work, more information can be logged by starting labwc via `labwc -d 2>&1 > some.log.file`

**Comment by Consolatis** [comment]
Closing for now, feel free to comment and we'll reopen this issue.
