### ISSUE TITLE
HP laptop beeps after pressing "k" button

### ISSUE THREAD

**Issue by schw0reismus** [labwc/labwc#683]
Also the symbol 'k' does not print, I have to use a workaround (Capslock+Ctrl) or copy it. It happens only in English (us) layout. I'm not sure that it's a BIOS beep since it's very loud and eerie.
I'm currently using a git version, although it happened much earlier.
Laptop: HP Pavilion Laptop 15-eh0032ur
OS: Void Linux

**Comment by schw0reismus** [comment]
I suddenly has solved the problem. Some time ago I tried to make the Print key work for the `grim - | wl-copy` command so I tried the following:

```
    </keybind>
    <keybind key="0x6B">
      <action name="Execute"><command>grim - | wl-copy</command></action>
    </keybind>
```

The `0x6B` in the code caused the problem. I've opened the task manager (from xfce4), pressed and held the 'k' key for some time and saw a lot of `grim - | wl-copy` and huge increase in `labwc` memory usage. The issue can be closed. However, I still didn't get the Print key work as intended.

**Comment by Consolatis** [comment]
> However, I still didn't get the Print key work as intended.

This is what I am using:
```xml
	<keybind key="Print">
		<action name="Execute">
			<command>sh -c 'grim -g "`slurp`"'</command>
		</action>
	</keybind>
```

If you store the actual command with its pipe / subshell in a script and then just call that script you can also do this instead:
```xml
	<keybind key="Print">
		<action name="Execute" command="screen_clip" />
	</keybind>
```
