### ISSUE TITLE
RDP Sessions are flickering

### ISSUE THREAD

**Issue by boris3812** [labwc/labwc#689]
When i use freeRDP (for wayland with **wlfreerdp** command)  on labwc DE - so as result remote session screen flickers , always, and its imposible to work. On other DE based on wlroots is fine (with this question) , like wayfire, when I use wlfreerdp.

all what  i have now is something like this message:
[10:27:12:516] [16225:16225] [WARN][com.freerdp.client.wayland.pointer] - wlf_Pointer_SetPosition not implemented
I purpose, this is another question with pointer, that i asked a few weeks ago, and we are waiting for a new release for FreeRDP.
https://github.com/FreeRDP/FreeRDP/issues/8434

If we choose **xfreerdp** , so by using Xwayland - here we have another problem :
after some time working "fine" on rdp session, ex.3 minutes , not more, - then all my labwc desktop slows down. so when I close xfreerdp - labwc session works fine again, no slow motion.  :) 

So yes , we have 2 problems, but if we  aim to use full wayland sessions, so first of all we are interested in using  wlfreerdp .
The question will be : is this a error or some task for implementation some other wlroots protocols in labwc ? or this is a problem for FreeRDP ? or may be there are some environment variables or other settings that I don't know...

**Comment by Consolatis** [comment]
I can't really reproduce this on latest master / 0.6.0.

Tested wlfreerdp with an xrdp installation and didn't see any flickers. Only strange thing I saw that `/f` doesn't seem to work correctly, it will get positioned below a top panel which suggests that wlfreerdp does not actually request a proper fullscreen.
Tested version 2.3.0 and 2.9.0.

Also tested xfreerdp version 2.9.0 and other than it seems really laggy for unknown reasons I did not experience lags in other applications. I did not really test it for more than a minute though.

Remmina with the RDP plugin was also working fine for me.

Do you run labwc on a nvidia GPU by chance? I remember issues about chromium causing screen flickers quite a while back.

**Comment by boris3812** [comment]
https://filedn.com/lyCLU10bkY6FUrIxXH2IUHz/2022-12-22%2010-28-30.mp4

**Comment by boris3812** [comment]
About GPU, - no i use intel
![Screenshot-20221222-103846](https://user-images.githubusercontent.com/93073422/209093306-f1025967-5b21-4815-bd23-519db94c0439.png)
And i forgot to show Freerdp version:
![Screenshot-20221222-104014](https://user-images.githubusercontent.com/93073422/209093678-7a78fbc7-63ff-4c7c-871c-785c00d66a85.png)

**Comment by Consolatis** [comment]
What version of labwc are you using?

**Comment by boris3812** [comment]
So yes , thats it . 
After building with subrojects for wlroots  - now fickering is gone, when using wlfreerdp . I put builded file , labwc , in bin path and now we can work :) . but i hope sometime we'll have in official repo labwc package and of course with using official wlroots packages . now it is 0.15.1-6 in official repo ( community for example) , but all other packeges in AUR are 0.17.0... , and just 1 package 0.16.0, **wlroots-eglstreams-git**, so i must to use it :) i hope , sometime we'll have some release in repo with that versions what are in repo, not with aditional patches. 
 For exemple , **the next problem what i have and now in 0.6.0 version labwc, and it was in 0.5 - sometimes the close button is not working**, and you must a lot of time to press it , to close that window, or using sfwbar menu, 
and that means that someday i'll have to build it again )
so i think it will be my next issue, will see when the package  0.6.0 will be in AUR  or may be some of oficcial repo. I don't now how you are deciding to fix in current release or  will be all fixes also in the next release. thanks for help !)

**Comment by Consolatis** [comment]
Thanks for reporting back.

I think sway had a release recently which requires wlroots 0.16 so chances are that it will be packaged for Arch soon and labwc will be updated to 0.6.0 as well.

> wlroots-eglstreams-git

This is not supported at all and AFAIU it was only created to support nvidia cards and shouldn't be required anymore for that either.

**Comment by johanmalm** [comment]
sway is still on rc4. I have no “inside” knowledge, but expect a release before the end of the year which will then trigger the packaging process.
This will make things easier in terms of distributing labwc.
