### ISSUE TITLE
Mention gamescope on website / readme

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#690]
Debugging X11 wine game issues is basically impossible for me because of my aarch64 system and the other core devs don't seem to game all day either. Most issues apparently can be "solved" by running the games via a nested gamescope instance so we should mention that prominently in the readme / website to make sure users are able to game as easy as possible on labwc.

**Comment by Joshua-Ashton** [comment]
Are there any game related issues that need to be addressed? Can you point them out to me and I can take a look.

As one of the devs of Gamescope and on SteamOS, I obviously play games a lot, so if there are issues I am happy to look into them for LabWC as I daily drive it :)
