### ISSUE TITLE
Layer-shell keyboard interactivity

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#704]
This covers a new issue discovered by @Tamaranch at the end of #667.

> @johanmalm Yes I can confirm that this issue is fixed +1 However, keyboard interactivity does not work properly anymore for me: the Esc key does not close the panel menus (e.g. apps menu). It worked until [d7eecca](https://github.com/labwc/labwc/commit/d7eecca34db0b65708713262cb4951bf39de62af) (at least).

I have narrowed the 'breakage' down to this commit https://github.com/labwc/labwc/commit/86fa0c0a6558eb85542e78eb050aa8b8a58b42eb

I'm not sure what the correct approach is here. It appears some clients want `get_cursor_context()` to return layer-shell subsurface surfaces, and others don't. Grateful for advice if anyone has knowledge or experience in this space.

**Comment by Consolatis** [comment]
Maybe we could get away with storing both surfaces, the main one used for keyboard focus and the other one for cursor focus?

**Comment by Consolatis** [comment]
As stated in https://github.com/labwc/labwc/pull/734#issuecomment-1407637384 this seems fixed.
Feel free to comment / reopen if that is not the case.
