### ISSUE TITLE
Native language support needs updating

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#708]
There are a few new entries since I visited this: (workspaces)
- "Move left"
- "Move right"
- "Workspace"

There is also a couple of small bugs and subsequently docs need updating.

1. 'tr' (Turkish) is missing from LINGUAS. This is no big deal except that if one uses Meson to update pot/po files (which we should instead of `xgettext`) 'tr' wont get updated. I expect this would be the case wih `xgettext` anyway - didn't try.
eg:
```
meson compile labwc-pot
meson compile labwc-update-po
```
2. At the moment, when generating pot/po files with `meson` the comments are not inserted into po/pot files because of this line:
https://github.com/labwc/labwc/blob/45ce978b5aadc8fd82869e86f39eddc3ab37a244/po/meson.build#L8
Do we even want the comments? I suppose they may help newcomers, but as the code changes those line numbers may change. Gettext doesn't rely on them it's just a user convenience.

With the 3 new entries the `po/pot` files will need updating by translators. That can happen later.

#### Docs
In the Native Language Support section the line:
```
xgettext --keyword=_ --language=C --add-comments -o po/labwc.pot src/menu/menu.c
```
could/should be replaced with:

```
meson build
cd build
meson compile labwc-update-po
cd ..
```
or similar. This would only need running after verbal changes in graphical parts of `labwc` (at this stage only menus).
Note that the two last commands _update the source_. The project _does not_ need to be compiled. Actually I can rework that whole section because if a new translator comes on board they will need to add their language code to `po/LINGUAS` and then generate the `po/mylang.po` file. For example, a translator is doing `fr` (French) would need to run the commands to generate `po/fr.po`. Also the `pot` file needs to be copied as `po/fr.pot` and the header fixed manually.

This would be good to have in place before the 0.6.1 release.

**Comment by johanmalm** [comment]
>     2. At the moment, when generating pot/po files with `meson` the comments are not inserted into po/pot files because of this line:
>        https://github.com/labwc/labwc/blob/45ce978b5aadc8fd82869e86f39eddc3ab37a244/po/meson.build#L8
>        
>        Do we even want the comments? I suppose they may help newcomers, but as the code changes those line numbers may change. Gettext doesn't rely on them it's just a user convenience.

I don't feel strongly either way, but vote for leaving them in.

> #### Docs
> 
> In the Native Language Support section the line:
> 
> ```
> xgettext --keyword=_ --language=C --add-comments -o po/labwc.pot src/menu/menu.c
> ```
> 
> could/should be replaced with:
> 
> ```
> meson build
> cd build
> meson compile labwc-update-po
> cd ..
> ```


Or the following - for consistency with `README.md` (and `meson build` is deprecated)

```
meson setup build
meson compile -C build labwc-update-po
```

**Comment by 01micko** [comment]
I didn't actually put the `meson` stuff in the PR. It's just as easy (easier?) to copy the existing pot file.

**Comment by johanmalm** [comment]
I'm guessing it'll only the likes of you and me to actually update the pot file though, right? And if you don't do it, I'm likely to forget the command for how to do it :smile:

**Comment by 01micko** [comment]
> I'm guessing it'll only the likes of you and me to actually update the pot file though, right? And if you don't do it, I'm likely to forget the command for how to do it smile

I'll try to keep things updated. :smile: It's quite simple and I have run the meson commands enough to remember them. I'll note down the newer syntax. Since the issue is solved I'll close.
