### ISSUE TITLE
Latest master make machine runs heavy.

### ISSUE THREAD

**Issue by ahmadraniri1994** [labwc/labwc#71]
I'm sorry for non-technical description, I compile latest master and run it, something I notice is my fan runs faster. It doesn't happen when I use other Wayland compositor (e.g Sway, hikari) and Labwc from my previous compilation (before the latest master). Happening for both archlinux and Debian. Thanks.

**Comment by johanmalm** [comment]
Thanks for feedback.
I know it’s a big ask, but it there any chance you could establish what commit (in labwc or wlroots) had this effect?

If you run ‘top’ from a terminal you can monitor CPU usage.

Are you running swaybg or similar? Does that have an effect on CPU usage?

**Comment by johanmalm** [comment]
@ARDiDo - like passing ships. That's interesting!
I've pushed a fix that sorts it for the old version too.
It works on mine, so will close this issue for now. Shout if it persists for anyone.
