### ISSUE TITLE
Can't upgrade Arch Linux due to wlroots 0.16.1-2

### ISSUE THREAD

**Issue by hellium6** [labwc/labwc#714]
wlroots 0.16.1-2 is now on [community repo of Arch Linux](https://archlinux.org/packages/community/x86_64/wlroots/). This is causing error when I try to do an upgrade:

```
$ sudo pacman -Syu
:: Synchronizing package databases...
...
...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing wlroots (0.16.1-2) breaks dependency 'wlroots<0.16' required by labwc
```

Currently I have aur/labwc 0.5.3-1 installed. I tried to update/install aur/labwc or aur/labwc-git but same message there:

```
$ yay -S labwc
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make:1]  wlroots-0.16.1-2
[Aur:1]  labwc-0.6.0-2

:: Remove make dependencies after install? [y/N] 
:: (1/1) Downloaded PKGBUILD: labwc
  1 labwc                                    (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: labwc
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing wlroots (0.16.1-2) breaks dependency 'wlroots<0.16' required by labwc
 -> error installing repo packages
```

What are the steps to remedy this?

**Comment by jlindgren90** [comment]
Arch Linux forums (AUR section) would be a better place for this question IMHO.

That said, I would:
1. Uninstall labwc 0.5.3
2. Update wlroots
3. Install labwc 0.6.0

**Comment by Consolatis** [comment]
See comments [here](https://aur.archlinux.org/packages/labwc).

In short, the AUR package for labwc needs to be updated to keep working with the latest packaged wlroots.
Now that wlroots 0.16 reached AUR, labwc-git should also depend on wlroots instead of wlroots-git.
If you want to use labwc-git with wlroots-git see #626 

CC @narrat

**Comment by hellium6** [comment]
@jlindgren90

> Arch Linux forums (AUR section) would be a better place for this question IMHO.
> 
> That said, I would:
> 
>     1. Uninstall labwc 0.5.3
> 
>     2. Update wlroots
> 
>     3. Install labwc 0.6.0

Thanks. It worked.

@Consolatis 

> ...it seems the packages were updated 9 days ago.

Yes. I was confused because of this. The dependencies of aur/labwc package was [changed to](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=labwc&id=94460622dfe231b6fb153c08e4dab11237dd40d2) `'wlroots>=0.16' 'wlroots<0.17'`. Still yay was seeing labwc to be requiring the old `wlroots<0.16` dependency (as evident in the above outputs). Not sure why that happened.
