### ISSUE TITLE
Application's dialog box placement problem

### ISSUE THREAD

**Issue by milisarge** [labwc/labwc#721]
Some of applications dialog boxes (e.g geany's open file) place on panel area, not properly placed at the top of the panel. I am doing maximize then it places to right positions.

**Comment by Consolatis** [comment]
The original issue should be solved, the issue of bigger-than-screen dialog windows is a generic one and not strictly related to labwc (or even wayland). Just automatically maximizing a dialog window when its bigger than the output sounds a bit hacky so closing this for now.
