### ISSUE TITLE
Screen temporarily goes blank at startup because of video mode reset

### ISSUE THREAD

**Issue by jacopo-salamina** [labwc/labwc#724]
**My current setup**

- I'm using my laptop's screen;
- preferred video mode is 2880x1620@120Hz;
- I'd like to use another video mode, same resolution as above but 60Hz;
- I configured this at boot time, setting the kernel parameter `video` to `eDP-1:2880x1620@60`.

**Expectation**

The screen should switch to 60Hz during boot, and never ever change refresh rate; moreover, labwc's startup time shouldn't be affected by the aforementioned configuration.

**Reality**

As soon as labwc starts, it activates the screen's preferred mode, switching the refresh rate to 120Hz. **This video mode change leaves the screen blank for about one second** before labwc becomes usable and anything gets shown on screen.

**Additional info**

- Computer: ASUS Vivobook S15 M3502QA;
- OS: Arch Linux;
- labwc version: `0.6.0-128-g5ebaf3f` (using `labwc-git` from the AUR, which downloads a fresh copy of the `master` branch and builds it locally);
- wlr-randr version: `0.2.0`;
- the two video modes mentioned above (2880x1620@120Hz and 2880x1620@60Hz) are automatically detected by wlr-randr, as shown in the following log files;
- I ran three tests:
  - on the first one, I set 60Hz at boot time, then started `labwc -d > labwc-with-kernel-param.log 2>&1`:
    - the resulting log file can be found below;
    - the screen goes blank for about one second;
    - the log file shows the video mode is set during labwc's startup, and after that there's a one second gap in the logs;
    - wlr-randr shows the screen is running at 120Hz;
  - on the second one, I removed the kernel parameter `video`, then started `labwc -d > labwc-only.log 2>&1`:
    - the resulting log file can be found below;
    - the screen doesn't go blank (or it did go blank, but was barely noticeable) and labwc is usable right away;
    - the log file shows the video mode is still set during labwc's startup, however there's just a 41 milliseconds gap in the logs;
    - wlr-randr shows the screen is running at 120Hz;
  - on the third one, I tried to work around this issue using kanshi: I set 60Hz at boot time once again, then added kanshi to `~/.config/labwc/autostart`, and then ran `labwc -d > labwc-with-kernel-param-and-kanshi.log 2>&1`:
    - the resulting log file can be found below;
    - the screen goes blank for about 2 seconds (which means this "workaround" only worsened the screen blanking issue);
    - the log file shows the video mode is set twice, during labwc's startup (120Hz) and when running `~/.config/labwc/autostart` (60Hz), and each time there's a one second gap afterwards in the logs;
    - wlr-randr shows the screen is running at 60Hz.

**Various log files**

- First test's log file: [labwc-with-kernel-param.log](https://github.com/labwc/labwc/files/10448497/labwc-with-kernel-param.log);
- output of `wlr-randr > wlr-randr.log` (during the first test): [wlr-randr.log](https://github.com/labwc/labwc/files/10448751/wlr-randr.log);
- second test's log file: [labwc-only.log](https://github.com/labwc/labwc/files/10448501/labwc-only.log);
- third test's log file: [labwc-with-kernel-param-and-kanshi.log](https://github.com/labwc/labwc/files/10448481/labwc-with-kernel-param-and-kanshi.log).

**Comment by Consolatis** [comment]
Thanks for the extensive report.
So AFAIS there are two issues here:
- 1 second delay when setting a new mode
- labwc always setting the preferred mode when detecting a new output

For the 1 second delay:
If a manual mode switch via `wlr-randr --output eDP-1 --mode 2880x1620@60.123456` (you might need to use the exact timing as shown by `wlr-randr`) also results in the delay its most likely an issue caused by wlroots, your KMS drivers or even your hardware itself. I didn't investigate this further but I assume there is not much we can do about that.

For always setting the preferred mode for new outputs:
We might need a config option (including the name of the output) to prevent that, currently labwc doesn't have the infrastructure to do so.  Thoughts on where to add the config option and how to name it @johanmalm ?

**Comment by johanmalm** [comment]
I prefer to use external clients (such as `kanshi`) if sensible/practical, because it keeps things simple and avoids conflicting config options, precedence definitions and so on. Now if we can't get the right behavior without an `rc.xml` option, then let's consider it, but that's a last resort for me.

Does it work if you specify all the decimals when setting the frequency with kanshi? Other users have reported issues on Wayland when not specifying decimals.

Does it make a difference if you use all the decimals when setting the kernel parameter?

If you've got the means and ability, testing this on sway would be a useful reference.

**Comment by jacopo-salamina** [comment]
> For the 1 second delay: If a manual mode switch via `wlr-randr --output eDP-1 --mode 2880x1620@60.000999` (you might need to use the exact timing as shown by `wlr-randr`) also results in the delay its most likely an issue caused by wlroots, your KMS drivers or even your hardware itself. I didn't investigate this further but I assume there is not much we can do about that.

I tried switching video mode with wlr-randr, and changing the refresh rate results in the one second screen blank. So yeah, labwc has nothing to do with _the amount of time_ needed for switching video mode.

> Edit: For a quick test you could just comment out the line `wlr_output_set_mode(wlr_output, preferred_mode);` in `src/output.c`, line `116` and recompile. However, this might cause issues when connecting an external screen.

I tried the aforementioned patch, and, since you mentioned possible external screens issues, I also played with an HDMI monitor.
The dual-screen test simply consisted in dragging a window from one screen to the other and vice-versa; I had no issues at all, with or without the patch.
Also, when running patched labwc, there was no screen blanking at all, with or without the external monitor attached.
These are the log files resulting from `labwc -d`, just in case:

- no labwc patch, no HDMI monitor: [labwc-no-patch-no-hdmi.log](https://github.com/labwc/labwc/files/10451869/labwc-no-patch-no-hdmi.log);
- no labwc patch, HDMI monitor attached: [labwc-no-patch-with-hdmi.log](https://github.com/labwc/labwc/files/10451870/labwc-no-patch-with-hdmi.log);
- patched labwc, no HDMI monitor: [labwc-with-patch-no-hdmi.log](https://github.com/labwc/labwc/files/10451872/labwc-with-patch-no-hdmi.log);
- patched labwc, HDMI monitor attached: [labwc-with-patch-with-hdmi.log](https://github.com/labwc/labwc/files/10451874/labwc-with-patch-with-hdmi.log).

> Does it work if you specify all the decimals when setting the frequency with kanshi? Other users have reported issues on Wayland when not specifying decimals.

Within my first comment, I mentioned a test I ran using kanshi (test n. 3); this was the configuration I was using:

```
profile "main" {
    output eDP-1 mode 2880x1620@60.000999Hz scale 1.75
}
```

As you can see, the decimals were already there, and wlr-randr detects the same exact value for the refresh rate (see [wlr-randr.log](https://github.com/labwc/labwc/files/10448751/wlr-randr.log)); the screen went blank anyway.

> Does it make a difference if you use all the decimals when setting the kernel parameter?

I tried to run the same tests described in my first post, by setting `video` to `eDP-1:2880x1620@60.000999`; unfortunately the screen went blank anyway. In case it might be useful, this is what I did:

- running `labwc -d`, kanshi not added to `~/.config/labwc/autostart`:
  - the screen goes blank for one second;
  - resulting log file: [labwc-kernel-param-decimals-no-kanshi.log](https://github.com/labwc/labwc/files/10452068/labwc-kernel-param-decimals-no-kanshi.log);
- running `labwc -d`, kanshi added `~/.config/labwc/autostart` (with the same configuration file as above):
  - the screen goes blank for 2 seconds;
  - resulting log file: [labwc-kernel-param-decimals-with-kanshi.log](https://github.com/labwc/labwc/files/10452075/labwc-kernel-param-decimals-with-kanshi.log).

> If you've got the means and ability, testing this on sway would be a useful reference.

I'll give it a try within the next few days.

**Comment by Consolatis** [comment]
> Also, when running patched labwc, there was no screen blanking at all

Thanks for testing.
By removing that line we should use whatever mode the Linux kernel / login manager configured the output to be.
In your case that is exactly what you intend to happen but we can't know that. As such it may cause a regression for other users because they may suddenly have to set the `preferred` mode manually. So I really think we need a default disabled config option or even a labwc command line argument to prevent changing the resolution to the `preferred` one. That way the usual case of using the preferred resolution / refresh rate keeps working while also providing a solution for people who just want to use whatever output mode is active when starting labwc.

> The dual-screen test simply consisted in dragging a window from one screen to the other and vice-versa

This is unrelated, the issue that might arise is that plugging in a new output while labwc is running might not use the preferred mode of the new output. I did not test that (my daily driver only has a single HDMI output).

**Comment by jacopo-salamina** [comment]
> This is unrelated, the issue that might arise is that plugging in a new output while labwc is running might not use the preferred mode of the new output. I did not test it (my daily driver only has a single HDMI output).

I tried this out. I removed the kernel parameter `video`, ran `labwc > labwc.log 2>&1` (with the suggested patch, without running kanshi from `autostart`), then plugged a 1080p TV screen using an HDMI cable and ran `wlr-randr.log > wlr-randr.log`. These are the resulting log files:

- [labwc.log](https://github.com/labwc/labwc/files/10475181/labwc.log);
- [wlr-randr.log](https://github.com/labwc/labwc/files/10475182/wlr-randr.log).

As you're going to see in the output of wlr-randr, the preferred mode for `HDMI-A-1` is not configured. (As for why preferred and current mode look identical, a possible explanation can be found at https://github.com/emersion/wlr-randr/issues/11#issuecomment-758583632)
I don't have any other kind of external monitor to try out.

> If you've got the means and ability, testing this on sway would be a useful reference.

I finally managed to run sway, both with and without kernel parameter `video`. In both cases, sway sets the preferred video mode (with the refresh rate set to 120Hz), and when the kernel parameter is added, the screen goes blank for a second.
Here are some files:

- log file of `sway -d > sway-no-kernel-param.log 2>&1` (first test, no kernel parameter): [sway-no-kernel-param.log](https://github.com/labwc/labwc/files/10475197/sway-no-kernel-param.log);
- log file of `sway -d > sway-with-kernel-param.log 2>&1` (second test, with kernel parameter): [sway-with-kernel-param.log](https://github.com/labwc/labwc/files/10475198/sway-with-kernel-param.log);
- `~/.config/sway/config` used in both tests (GitHub forced me to change the file extension): [config](https://github.com/labwc/labwc/files/10475202/config.txt).

**Comment by Consolatis** [comment]
@jacopo-salamina Testing of
- #726

would be welcome, requires setting a new config option: `<reuseOutputMode>yes</reuseOutputMode>` within `<core>`

**Comment by jacopo-salamina** [comment]
I will add this new option, recompile, run `labwc -d`, then plug the HDMI monitor and run `wlr-randr`. All of that two times, first without kernel parameter `video`, then with the parameter.

Any other meaningful tests (which only involve one HDMI monitor)?

**Comment by Consolatis** [comment]
> Any other meaningful tests (which only involve one HDMI monitor)?

Output of the different `wlr-randr`s should be enough.
Also just to make sure we are on the same page: does enabling the new setting fix your issue completely?

**Comment by jacopo-salamina** [comment]
> I will add this new option, recompile, run `labwc -d`, then plug the HDMI monitor and run `wlr-randr`. All of that two times, first without kernel parameter `video`, then with the parameter.

I did it, these are the resulting log files (whose names should be self-explanatory):

- [labwc-no-kernel-param.log](https://github.com/labwc/labwc/files/10481312/labwc-no-kernel-param.log);
- [wlr-randr-no-kernel-param.log](https://github.com/labwc/labwc/files/10481315/wlr-randr-no-kernel-param.log);
- [labwc-with-kernel-param.log](https://github.com/labwc/labwc/files/10481316/labwc-with-kernel-param.log);
- [wlr-randr-with-kernel-param.log](https://github.com/labwc/labwc/files/10481317/wlr-randr-with-kernel-param.log).

> Also just to make sure we are on the same page: does enabling the new setting fixes your issue completely?

During both tests, the laptop's screen never went blank, and during the second test the refresh rate stayed at 60Hz. So yeah, this definitely fixes my issue.

**Comment by Consolatis** [comment]
> During both tests, the laptop's screen never went blank

Sweet, thanks for testing and bringing this up in the first place.
