### ISSUE TITLE
Focus lost when a notification occurs

### ISSUE THREAD

**Issue by Hazegard** [labwc/labwc#725]
Hello

When tools such as: 
- https://github.com/ErikReider/SwayNotificationCenter 
- https://github.com/francma/wob
- https://github.com/dunst-project/dunst
 displays a popup, the focus on the currently active window is lost:

![cropped2](https://user-images.githubusercontent.com/11147206/213935398-881e3155-88c0-4626-90f5-9521546826d1.gif)

I tried to enable the ` followMouse` option, which does not really solve the issue as I still have to move the mouse to get back the focus on the previously focused window.

Is there an option that allows to keep the focus when a notification is displayed on the screen?

**Comment by johanmalm** [comment]
Thanks for raising this.

Are you able to build from source?
If so could you try if it still happen if the following bit is commented out:

https://github.com/labwc/labwc/blob/5ebaf3ff52c3a4e408c86670e45a9143d1947b8c/src/desktop.c#L382-L399

**Comment by Hazegard** [comment]
Hello, 

I tried to build from source while commenting lines 382 to 399 and the issue still happens.

To provide more information, I notice that the issue also occurs when the notification disappear from the screen.

**Comment by johanmalm** [comment]
I've just tried with the `labwc` master branch + `wlroots` 0.16.0 but I can't reproduce it.

Steps I took:
1. Install dunst from Arch Linux repo.
2. Start dunst
3. Run `sleep 5 ; notify-send foo` from a terminal.
4. Quickly alt-tab to another terminal, the press+hold `a`

Result: keyboard focus stays with the terminal where I'm pressing `a` event when the `dunst` notification appears.

I can't think of what might be triggering it on your machine. Could you confirm the following:
- Are you running the latest `labwc` master?
- Are you setting any unusual environment variables?
- Do you get the same with `labwc` 0.5.0?

**Comment by Hazegard** [comment]
After more digging on the issue, I noticed that the culprit is xfce4-panel.

I only tried labwc after xfce-panel was available on wayland, so i did not notice that the issue does not come from labwc.

**Comment by johanmalm** [comment]
> After more digging on the issue, I noticed that the culprit is xfce4-panel. 
> I only tried labwc after xfce-panel was available on wayland, so i did not notice that the issue does not come from labwc.

I can now re-produce it, which is a great start for fault finding.
I suspect `labwc` should handle this better. Will do some digging.
