### ISSUE TITLE
foreign-toplevel-management: app-id never set

### ISSUE THREAD

**Issue by dnkl** [labwc/labwc#74]
Not really reported, but nevertheless discovered in https://codeberg.org/dnkl/yambar/issues/115. Labwc never sets/sends the app-id. I.e. there aren't any calls to `wlr_foreign_toplevel_handle_v1_set_app_id()`.

**Comment by johanmalm** [comment]
labwc now handles `set_app_id` and `set_class` events and calls `wlr_foreign_toplevel_handle_v1_set_app_id()` accordingly

**Comment by dnkl** [comment]
Thanks!
