### ISSUE TITLE
Region overlay shows up when using A-Left + Drag to move windows

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#761]
I wouldn't say its a bug, but it just seems a bit weird/wrong to me from an UX perspective.

Maybe its possible to only show the overlay when a modifier is pressed while the move action is already in progress, and not when it was pressed to start the move action? Idk.

**Comment by Consolatis** [comment]
> Maybe its possible to only show the overlay when a modifier is pressed while the move action is already in progress, and not when it was pressed to start the move action?

That could actually work, nice idea.

Another option could be to just provide a config option to disable the whole region mouse snapping thing.
That way regions could still be used via `SnapToRegion` but not with the mouse.

**Comment by Consolatis** [comment]
I thought about the original request a bit more: we could even react to modifier release events and if we are currently in a move and there are no modifiers pressed anymore we could reset that modifier state. Thus `A-Left` to move a window would not cause `snap_to_region()` machinery to kick in, then releasing `Alt` and pressing it again (or any other modifier) would enable it. That would allow undecorated windows to still use snap to edge but would not confuse users that just want to move their windows around.

**Comment by johanmalm** [comment]
^ sounds a good approach.
