### ISSUE TITLE
Make it possible to configure the number of Workspaces without naming them

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#763]
To make it work more similar to [how it does in Openbox, at least according to the wiki?](http://openbox.org/wiki/Help:Configuration#Desktops)

```
<desktops>
  <number>4</number>
</desktops>
```

>number The number of virtual desktops to use.

>names Each name tag names your desktops, in ascending order. Unnamed desktops will be named automatically depending on the locale. You can name more desktops than specified in number if you want.

Very very very low priority, just thought it would be nice to have sometime in the future?

**Comment by Consolatis** [comment]
The feature should be designed in a way that all of this variants work correctly, e.g. end up with "Workspace 1" to "Workspace 4":
```xml
<desktops number="4" />

<desktops>
  <number>4</number>
</desktops>

<desktops>
  <number>4</number>
  <names>
    <name>Workspace 1</name>
    <name>Workspace 2</name>
  </names>
</desktops>

<desktops number="4">
  <names>
    <name>Workspace 1</name>
    <name>Workspace 2</name>
  </names>
</desktops>
```

**Comment by Sachin-Bhat** [comment]
Hello folks, I tried my hand at this issue. I am still fairly new to C. So, if possible could someone kindly direct me on building and testing my code. To give some context I am running Arch Linux with labwc. I just want to ensure that I don't brick what I currently have set up!

**Comment by johanmalm** [comment]
To build:

```
meson setup build
ninja -C build/
```

Run with `./build/labwc`

Carry out some some basics checks on a file, by running: `./scripts/check --file=src/workspaces.c`

We don't have any unit tests, so rely on peer review and manually testing features.

In terms of sharing your patches, I suggest the following (assuming that you've cloned `https://github.com/Sachin-Bhat/labwc.git` and that you're working from the toplevel directory of that repo):

```
git checkout -b config-workspaces-by-number
# make some changes to src//workspaces.c etc
git add src/workspaces.c
git commit -m 'config: support <desktops number="">'
git push origin config-workspaces-by-number
```

Then, either go to the github website and create a draft pull request against the `labwc/labwc.git` master branch or just let us know that you've pushed some commits against a branch on your fork and we can give you some feedback.

You might have written the perfect patch-set, but don't worry if you haven't. Most people don't :smile: including me. Being able to discuss and take feedback is an important part of development.
The good thing is that you can keep force-pushing on your development branch (which overwrites the commit history) until you/we are happy with it. So in the end the merged commits look nice and tidy.

Obviously we would never force-push on the labwc master branch.

**Comment by Sachin-Bhat** [comment]
Hello folks! Was working on the said changes. It has been pushed to my fork ([https://github.com/Sachin-Bhat/labwc/tree/config-workspaces-by-number](url)). I am still quite new to this. Thus I haven't been able to hard test it. It does build and the script checks that was mentioned earlier did not throw errors. If possible, I would hope to get some feedback on it.
I have done changes in the following files:
- `src/config/rcxml.c`
- `src/workspaces.c`
- `include/config/rcxml.h`
- `include/workspaces.h`  

I have documented the changes within these files itself though the documentation of the new config setting in `docs/rc.xml.all` and `docs/labwc-config.5.scd` are still pending.

**Comment by Consolatis** [comment]
Thank you for working on this :)

> I am still quite new to this.

No worries, we all were at some point.

> If possible, I would hope to get some feedback on it.

The easiest way to organize the feedback is to open a PR in this repository. You can set it to "Draft" to state the work-in-progress aspect. I had a quick look at your branch and it goes into the right direction. Once you open up the PR I'll add some more detailed feedback there. And don't worry about the commit history and the finer details of git, we can always fix it as the last step before merging.

**Comment by Sachin-Bhat** [comment]
This issue can be closed by the looks of it. #956 adds a fix.

**Comment by Consolatis** [comment]
@Sachin-Bhat Thanks for implementing this feature.
