### ISSUE TITLE
Cursor doesn't move on Scummvm

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#776]
Hi there,

I am trying labwc for the first time, and I have just built the latest stable version on wlroots 0.16.2, and use the GLES renderer.
Now, the problem is that the cursor won't move at all in Scummvm. It runs on SDL2-2.26.2, which I built with Wayland support for this purpose.
The SDL2 mouse tests seem to work, and also other game engines working on SDL2 work well, like DevilutionX, etc.

So, any idea on why Scummvm could be failing with the Labwc compositor only?

**Comment by vanfanel** [comment]
More info: if I move the left analog joystick on an X360 Controller, mouse in Scummvm starts working.
I know it sounds like nonsense, but maybe Labwc has some problem with mice initialization and the joystick interface "kicks labwc" into start working somehow?

**Comment by Consolatis** [comment]
Labwc is missing an essential part for games: confining the cursor correctly.
As a workaround until it is implemented properly you can run your game in gamescope.

For further details see.
- #772

**Comment by vanfanel** [comment]
@Consolatis Ah, I see! That would explain it... Even Weston is missing the correct cursor confinement... I have been trying to fix that for weeks, with no success.

@Joshua-Ashton I read on another thread that you are taking a look at the missing pointer stuff soon. Please, PLEASE let programs get mouse confinement as soon as they go fullscreen, while you are at it.
Some compositors, like Weston, need the user to click on the screen to gran pointer confinement which is absurd and counter-intuitive.

**Comment by vanfanel** [comment]
Jeez... gamescope isn't a solution at all, it depends on tons of X11 crap :(

**Comment by AnErrupTion** [comment]
> Jeez... gamescope isn't a solution at all, it depends on tons of X11 crap :(

Works fine for me. I think it uses XWayland to capture frames, according to the repository's README.

**Comment by Ph42oN** [comment]
I had issue with cursor not moving at all in planetside 2 if its in fullscreen mode. Running in borderless window mode it does not happen. I also have fork where i have partial implementation of mouse constraints, with it this issue also does not happen. Constraints on my fork work correctly for fullscreen, but not for windowed. If you want to try its here: https://github.com/Ph42oN/labwc

**Comment by vanfanel** [comment]
@Ph42oN Maybe you can try to merge your pointer confinement implementation into upstream labwc?

**Comment by Ph42oN** [comment]
I tried: https://github.com/labwc/labwc/pull/586
Didnt get merged... I also tried to look if i could make it fully working implementation but i couldn't figure out how.

**Comment by vanfanel** [comment]
> I tried: #586 Didnt get merged... I also tried to look if i could make it fully working implementation but i couldn't figure out how.

Ouch! So much effort for nothing :(
Well, I guess I'll look for another compositor then. Thanks!

**Comment by johanmalm** [comment]
Bear with us. We will get there.
We really appreciate the effort with writing the patch.
I remember seeing some notes from @Consolatis on the type of situations that we need to handle.
I haven’t had a chance to look at it myself

**Comment by vanfanel** [comment]
@Consolatis Now that's what I call a helping post! Thanks!

I have been using Sway, but for some reason it started to make Vulkan very slow since a MESA update (already reported to MESA a couple of months ago).

I like Weston, but it's pointer confinement is broken, too: pointer confinement isn't activated until the game area is double-clicked, and in the GIT versions of Weston, quitting a program with granted pointer confinement causes Weston to crash.

kwin and mutter... Can they be used "standalone"? I dont think so, and they have huge dependencies.

Gamescope requites the whole X11 truck of cruft I don't want to deal with, you are right.

Hyprland is too heavy for the Pi4 where I use those things.

And that's about it.

**Comment by Consolatis** [comment]
Forgot to mention [cage](https://github.com/Hjdskes/cage), if you really just want to use it for a single fullscreen application that actually sounds like the perfect fit.

**Comment by vanfanel** [comment]
@Consolatis Cage is a great idea... except it doesn't even support pointer confinement at all.
But if it did, it would be perfect, yes.

**Comment by johanmalm** [comment]
Hey troops - call for olive branch and friendly co-existence.

We really mean it when we say that we care about the end-user and that we want people to use labwc. Otherwise we would not commit so much time to it.

@Consolatis and other core devs are doing an amazing job.

In my view, the biggest risk to FOSS projects like this is not finding/keeping enough devs who are willing to roll up their sleeves and get stuck in. Being provocative / argumentative / etc is probably the single best way of turning people off… so it’d be really great if unhelpful posts were left unwritten.

I understand that it’s frustrating when features are missing, but please channel that energy into something that’s constructive for the project if possible.

Appreciate help with writing patches to get the pointer constraint working. 

Also welcome constructive discussions on approach and things to consider with the implementation.

**Comment by vanfanel** [comment]
@johanmalm I am not complaining at all, sorry if I sounded like that. I REALLY like labwc, and it may be my daily compositor in the future, once pointer confinement is working right. Aside from that, seems to be light and stable, which is what I need.

**Comment by johanmalm** [comment]
> @johanmalm I am not complaining at all, sorry if I sounded like that. I REALLY like labwc, and it may be my daily compositor in the future, once pointer confinement is working right. Aside from that, seems to be light and stable, which is what I need. And what GNU/Linux desktop needs, in fact: stable and light wayland compositors.

That's great. Thanks for your support.

**Comment by Consolatis** [comment]
This should be fixed by #586.
If it isn't feel free to comment and we'll reopen this issue.

**Comment by vanfanel** [comment]
@Consolatis Yes, pointer confinement works perfectly now! Thanks a lot! I can confirm this is fixed!
labwc is now perfect for my needs :dancers:
