### ISSUE TITLE
IME support (text_input_v3 protocol  & zwp_input_method_keyboard_grab_v2 ?)

### ISSUE THREAD

**Issue by rico256-cn** [labwc/labwc#783]
https://bugs.chromium.org/p/chromium/issues/detail?id=1039161

google chrome version 112 supports the text_input_v3  protocol.   

Does labwc support text_input_v3 protocol?

**Comment by Consolatis** [comment]
No, neither v2 nor v3 are implemented by labwc.
Marking this as a feature request.

[This](https://github.com/swaywm/sway/pull/4740/files) is the old implementation for sway for future reference.

**Comment by rico256-cn** [comment]
LabWC runs very smoothly. I want to use LabWC to build a minimal wayland desktop environment. chrome needs this feature to use the input method. Hope to see this feature soon.

**Comment by Consolatis** [comment]
I completely agree that we should implement it. Not everybody uses the latin alphabet.

We do support the [virtual-keyboard-unstable-v1](https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/protocol/virtual-keyboard-unstable-v1.xml) protocol though,
maybe there is some on-screen-keyboard which could make use of it?

Small overview for future reference : https://dcz_self.gitlab.io/posts/input_method/

**Comment by rico256-cn** [comment]
On-screen-keyboard is not suitable for production use and is inefficient. input-method-v 3 is recommended as a priority。

**Comment by rico256-cn** [comment]
Thank you, I will wait patiently for the implementation of this feature, hope labwc better and better

**Comment by rico256-cn** [comment]
Please refer:
https://github.com/fcitx/fcitx5/issues/206

**Comment by johanmalm** [comment]
Is it enough to just call wlr_text_input_manager_v3_create() from server_init()?

**Comment by rico256-cn** [comment]
FYI:


https://github.com/WayfireWM/wayfire/issues/1160

**Comment by kmephistoh** [comment]
Application/Compositor uses text-input-v3  --> [link](https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Sway)
Comopositor/Application uses zwp_input_method_v2 (I don't know which version is the right choice,  How sway do it ?) --> May useful [link](https://wayland.app/protocols/text-input-unstable-v3)

**Comment by tokyo4j** [comment]
This is my work-in-progress implementation: [link](https://github.com/tokyo4j/labwc/tree/input-method)

**Comment by johanmalm** [comment]
> This is my work-in-progress implementation: [link](https://github.com/tokyo4j/labwc/tree/input-method)

Great stuff. Thanks for working on this.

**Comment by johanmalm** [comment]
Implemented with https://github.com/labwc/labwc/pull/1548
