### ISSUE TITLE
clipboard problem: when program exit,  the data in clipboard will lost.

### ISSUE THREAD

**Issue by rico256-cn** [labwc/labwc#784]
I am testing and evaluating labwc. I found that after I ctrl+c copied some data in an application A, I can paste it in other applications, but when this application A exits, the clipboard data is automatically cleared. Excuse me Will labwc support clipboard data persistence (even if the application exits)?

**Comment by Consolatis** [comment]
You need a clipboard manager supporting  the [wlr-data-control-unstable-v1](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-data-control-unstable-v1.xml) protocol for that to work.

Labwc itself does not store any clipboard data, the way this works in wayland is:
- an application announces it has data to share
- another application requests that data directly from the first one
- the wayland compositor (e.g. labwc in this case) just relays file descriptors and thus never sees the actual content of the clipboard

**Comment by xi** [comment]
wlroots ticket: https://github.com/swaywm/wlroots/issues/1648
