### ISSUE TITLE
Does labwc support workspaces show up on waybar?

### ISSUE THREAD

**Issue by rico256-cn** [labwc/labwc#793]
I had configure two workspace in labwc.  It works fine.

 and I configured according to waybar manual, taskbar works fine, but workspaces cannot be displayed. Does labwc support workspaces show up on waybar?   Who can help me?

my waybar config:
-----------------------------
  
`      "layer": "top",
        "modules-left": ["wlr/workspaces"],
        "modules-center": ["wlr/taskbar"],
        "modules-right": ["cpu", "memory", "clock", "tray"],

"wlr/workspaces": {
        "format": "{name}: {icon}",
        "format-icons": {
                "1": "",
                "2": "",
                "focused": "",
                "default": ""
        },
        "sort-by-number": true
},

        "wlr/taskbar": {
        "format": "{icon} {title}",
        "icon-size": 14,
        "icon-theme": "Numix-Circle",
        "tooltip-format": "{title}",
        "on-click": "activate",
        "on-click-middle": "close",
        "ignore-list": [
            "Alacritty"
        ],
        "app_ids-mapping": {
                "firefoxdeveloperedition": "firefox-developer-edition"
        }
  },`

**Comment by Consolatis** [comment]
This will sadly not work on labwc as long as the respective [wayland protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) isn't accepted and implemented.

Some other compositors make this work by using custom IPC systems which labwc doesn't support (on purpose: prevents even more fragmentation).

**Comment by liumingedwin** [comment]
wtype and Hotkeys can be used to switch and show workspaces~
