### ISSUE TITLE
Please consider adding a very basic set of effects

### ISSUE THREAD

**Issue by Vladimir-csp** [labwc/labwc#805]
X WMs could be enhanced with standalone compositors like picom. It seems that such thing is not possible in Wayland world.
Please consider adding basic shadow, fade-in/fade-out, blur

**Comment by heroin-moose** [comment]
Yeah, shadows are a must-have (optional of course). I'm currently working on a patch and will be nagging about getting it merged for some time :3

**Comment by johanmalm** [comment]
It's a no to this I'm afraid.

We're pretty clear in the [https://github.com/labwc/labwc#11-what-is-this](README) that bling, animations and decorative gradients are out-of-scope.

Kwin, mutter, wayfire and hyprland all support these, but our project soul takes us down a different path.
