### ISSUE TITLE
How to allow app to capture keyboard shortcuts?

### ISSUE THREAD

**Issue by 1qh** [labwc/labwc#810]
I wonder if it is possible to use keyboard shortcuts in a virtual machine. For example, with a Windows VM, I cannot Alt+Tab, or some keybindings with Win+...

With gnome, this can be done easily. It shows a dialog to ask if i want to capture shortcut. I understand that labwc doesn't have any kind of dialog to confirm like that, so I think this feature can be set with app-specific configuration. I've read every documents available for labwc, as well as a lot of thread about using virt-manager or remote-viewer under Wayland, but have no luck...

I want to share that I have begin with gnome, then switch to i3, then sway, finally here. Now labwc is a thing that I will live with as long as I can still sit in front of a computer. That explains how awesome this project is to me.

I'm looking forward to your response. Thank you guys a lot.

**Comment by Consolatis** [comment]
This is in fact a missing feature from labwc.
There is a wayland-protocol which allows for this but we will very likely not implement it to prevent random applications from disabling all shortcuts.

The current thoughts about a solution to this issue is listed at
- #738

**Comment by Consolatis** [comment]
I like that approach. This variant could even slightly change some theme setting via `themerc-override` like turning `window.active.border.color` red.

**Comment by johanmalm** [comment]
@Consolatis Might we want to consider adding an action (like `ToggleKeybindsEnabled` or something) that users can add to their root-menu. I have admit I sometimes miss this when wanting to try out a key-combination on a nested version. I of course then just run the nested with a separate config file, but it would be neat to just right click the desktop and go `DisableKeybinds`.

I'm not sure if it's as simple as adding an `if (rc.keybinds_disabled) { return false }` to 
https://github.com/labwc/labwc/blob/d571b0b28aab8fc117756cf03e83868d306ee7a3/src/keyboard.c#L82

**Comment by Consolatis** [comment]
> Might we want to consider adding an action (like `ToggleKeybindsEnabled` or something) that users can add to their root-menu.

I guess we could do that.. But from a UX perspective I think we should also allow re-enabling the keybinds via a keybind.
What about something like this when looping through the keybinds:
```c
diff --git a/src/keyboard.c b/src/keyboard.c
index 894ae63..b2d1737 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -87,6 +87,9 @@ handle_keybinding(struct server *server, uint32_t modifiers, xkb_keysym_t sym)
 		}
 		for (size_t i = 0; i < keybind->keysyms_len; i++) {
 			if (xkb_keysym_to_lower(sym) == keybind->keysyms[i]) {
+				if (rc.keybinds_disabled && !actions_is_toggle_keybinds(actions)) {
+					continue;
+				}
 				key_state_store_pressed_keys_as_bound();
 				actions_run(NULL, server, &keybind->actions, 0);
 				return true;
```

**Comment by 1qh** [comment]
Thank you guys a lot, now I'm using @Flrian's workaround and i works great! [Here](https://github.com/1qh/arch/tree/master/labwc) is my config.

**Comment by Consolatis** [comment]
You may now also use the `ToggleKeybind` action directly.

**Comment by 1qh** [comment]
Super awesome! This is exactly what I need! So this action will be in the next release (may be 0.6.2) right?

I’m using `labwc` package from AUR

**Comment by johanmalm** [comment]
Yes, will be in `0.6.2`.

If you re-install from AUR you'll have it now :smile:
