### ISSUE TITLE
Crash due to overwriting server->input_mode

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#817]
```
<kode54> please test this game demo on Steam
<kode54> https://store.steampowered.com/app/1522810/Shield_Cat/
<kode54> I was running that by setting to use proton for everything so it would let me install it
<kode54> then ran it with ge proton 49
<kode54> I ran it in windowed mode and used a bluetooth DualShock 4 controller
<kode54> when I quit the game, labwc crashed
<kode54> and then the uwsm setup didn't tear down correctly as a result, so I had to reboot to log in again
<kode54> Mar 05 20:28:32 mrgency labwc[54233]: labwc: ../labwc/src/menu/menu.c:843: menu_close_root: Assertion `server->input_mode == LAB_INPUT_STATE_MENU' failed.
<Consolatis> uh? that is a new one
<Consolatis> we didn't change anything around there for ages, will have a look later today
<Consolatis> thanks for the pointer
<Consolatis> oh, i see. could reproduce. same happens when opening a client menu, then calling for example a Move keybind and finally closing that window
<Consolatis> the reason that it didn't show up before is likely that nobody uses move or resize keybinds in the first place and instead uses the mouse
<Consolatis> so the controller input might have be interpreted as some keybind, that is just guesswork though
```

So to reproduce (assumingly) the same issue:
- bind `Move` to some keybind
- open a window/client-menu (e.g. `A-Space` or the left SSD icon)
- move the mouse over some window
- press the `Move` keybind
- server->input_mode gets overwritten due to the move
- close the window owning the client-menu opened earlier
- labwc crashes on the aforementioned assert() because we now have the client menu open but input_mode being something else

Now the question is how we should fix this:
- Just remove the assert and live with `server->input_mode` potentially getting overwritten
- Prevent modifications of server->input when its not `_PASSTHROUGH`, e.g. return early in `show_menu()` and `interactive_begin()`
- Stop setting `server->input_mode` directly and instead use something like `server_set_state(server, LAB_INPUT_STATE_MOVE)`
  - Have the new function check the previous state and clean up, e.g.
    - for _MOVE and _RESIZE call `interactive_cancel()` (or `interactive_end()`?)
    - for _MENU call `menu_close_root()`

I didn't investigate if similar issues also happen in other combinations, e.g. using a `Move` keybind while currently resizing or spawning a menu via keybind while resizing or moving.

Personally I think I'd prefer the early-out variant but completely open to suggestions.

**Comment by johanmalm** [comment]
Agree. Early return in `show_menu()` and `interactive_begin()` seem simplest.

An alternative (similar to your third point) could be to create an `input-mode.c` with a `static enum` within that translation unit and associated getters/setters. That way the variable is truly private and we can control how it's set. 
Maybe slight overkill considering that we only set `view->input_mode` in two places, but I suppose it prevents similar problems in the future in the case of scope expansion.

**Comment by Consolatis** [comment]
> Agree. Early return in show_menu() and interactive_begin() seem simplest.

Done that: #819
With that PR I can't reproduce the crash anymore.

> An alternative (similar to your third point) could be to create an input-mode.c with a static enum within that translation unit and associated getters/setters. 

I think that would indeed be a bit overkill as we should be fine even with just a convention to never set it manually (similar to `view->current` outside of the commit handlers for example). However that might not be required in this case in the first place unless we add more modes in the future and the current checks become way too complicated.
