### ISSUE TITLE
Prevent parent windows from displaying above modal dialog

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#823]
See https://github.com/labwc/labwc/issues/688#issuecomment-1361972690

For example when opening the about dialog in nautilus you can switch back to the main window and if you didn't pay attention it isn't immediately obvious why you can't interact with it.

I'm also having a bug in calibre where a dialog sometimes (not sure why) spawns below the main application, very noticeable there.

**Comment by stefonarch** [comment]
Same here, some filedialog maybe open and waybar/taskbar shows it with the app_id while the main window is blocked. Tried using window rules using `"title"="Open*"` and `ToggleAlwaysOntop` Tbut this workaround doesn't work unfortunately.

**Comment by stefonarch** [comment]
Fixed by  https://github.com/labwc/labwc/pull/998

**Comment by johanmalm** [comment]
Thanks for the reminder.
