### ISSUE TITLE
HiDPI scaling with LabWC (and woes with XWayland)

### ISSUE THREAD

**Issue by joshuataylor** [labwc/labwc#828]
Howdy

I thought I should share my adventures with HiDPI scaling with LabWC, an issue is probably not the correct place, but maybe we could add this to the wiki? [Hyprland has it in their wiki](https://wiki.hyprland.org/Configuring/XWayland/), sway strong opinions (for good reason, imho, but sucks for older software).

I will be using the terminology HiDPI from the (as always) excellent ArchWiki article about [HiDPI](https://wiki.archlinux.org/title/HiDPI).

Out of the box LabWC supports scaling, which will make Wayland native apps look fantastic. What are "Wayland native" apps?

These are apps which run natively in Wayland, aka not through XWayland. Most of the apps I use are now "Wayland native", with the main exception being Java. So if you use [https://www.jetbrains.com](Jetbrains Products) such as IntelliJ/CLion/PyCharm/Datagrip/Rubymine/Goland/Rider/Webstorm/PHPStorm, you're going to have super blurry apps, as XWayland can't be scaled properly (yet).

> Sidenote, work is being done in "Project Wakefield" for native Java on Wayland [0](https://wiki.openjdk.org/display/wakefield/Work+breakdown), [1](https://github.com/openjdk/wakefield/tree/pure_wl_toolkit)

I manage my scale configuration with [kanshi](https://sr.ht/~emersion/kanshi/), my config looks as follows:

```
profile {
  output DP-1 mode 3840x2160@143.9629972Hz position 0,0 scale 1.35
}
```

I found 1.35 works well for my monitor, my laptop 1.25 works well.

This won't turn into a post about [Wayland](https://wiki.archlinux.org/title/wayland), [XWayland](https://wiki.archlinux.org/title/wayland#XWayland) (xorg-xwayland), wlroots, etc.. as I'll get too sidetracked.

I was super impressed how easy it was to get scaling to work, and how it didn't break everything else on my system to get it to work! If I didn't have to run XWayland apps, I would be an extremely happy camper :).

## Installation Notes
I tested this first on sway (as the patches were for wlroots `0.17`), which worked, then tried on labwc and it worked well!

1. This will be focusing on ArchLinux. This will work on other distros, but you'll need to apply some patches and build a couple of dependencies yourself. If you take a look at the `PKGBUILD` for the packages, you'll be able to see how this is done.
2. This will be using the latest commits against `main` for labwc, with a WIP branch for 0.17 wlroots support. This is because the patches for wlroots only apply against the latest main branch, and from my futzing I couldn't get it to build correctly for `0.16.2`. When I have more time I'll try to backport the changes to make this work, as I'm unsure how long until wlroots `0.17` support is added to labwc.

## Installation Steps (ArchLinux)
1. You're going to be installing the following packages from aur:
1a. [xorg-xwayland-hidpi-xprop](https://aur.archlinux.org/packages/xorg-xwayland-hidpi-xprop)
1b. [wlroots-hidpi-xprop-git](https://aur.archlinux.org/packages/wlroots-hidpi-xprop-git)

These packages need to be installed because they add support for the [infamous patch 733](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/733) merge request, which adds hidpi support to xorg and wlroots.

2. In your `~/.config/labwc/autostart`, add the following line:
`xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2`

This makes XWayland apps scale at 2x.

3.
Now this step is optional, as it doesn't change non-Wayland GTK apps, but I like to do this on a per-app basis.

Where you set your environment variables (`/etc/environment` etc), add the following:
`GDK_SCALE=2`

This will make non-Wayland GTK apps 2x.

4. You will need to use the branch at https://github.com/labwc/labwc/pull/626 , which adds support for wlroots 0.17. I have included a [PKGBUILD here](https://github.com/labwc/labwc/pull/626#issuecomment-1465147549) you can use.

### Cursor size is small
The cursor is tiny, as it's your half usual cursor size, `XCURSOR_SIZE` / 2.

I'm not sure how to change `XCURSOR_SIZE` for JUST XWayland, or on a per app basis, but before starting my XWayland apps, I set the following:
```
export XCURSOR_SIZE=48
export XCURSOR_THEME=Adwaita
```

### Jetbrains Notes
I add these on a per-app basis. If you've installed these via Jetbrains Toolbox, they are in `~/.local/share/applications`. You can then add at the start of the `Exec=` line, see the [Modify environment variables](https://wiki.archlinux.org/title/Desktop_entries#Modify_environment_variables) archwiki page for instructions.

> These will be updated every time the product updates.. So you'll need to keep adding them here, which is a pain. You could have another desktop entry, which sets then launches this one, but then you'll have two entries in your launcher..

They can also create scripts for you, if you want to launch via terminal/another app, where they save like `idea.sh` `clion.sh` into a directory, so you could create a shell script that exports the variables then launches that file. :shrug:

**Comment by kode54** [comment]
Something about this is sort of broken with Steam. The main window insists its minimum size is larger than my desktop.

**Comment by joshuataylor** [comment]
Try and force Electron apps to run as native Wayland, you'll have a much better experience from what I've found.

You can add `--enable-features=UseOzonePlatform --ozone-platform=wayland` and you *should* get Wayland support with Electron for that app.

Flag locations so you don't need to do this:


VScode: `~/.config/code-flags.conf`
Chrome: ~/.config/chrome-flags.conf`

Generic electron flags should be at `~/.config/electron-flags.conf`, but this has mixed results.

**Comment by kode54** [comment]
The Discord package has no such script, I had to create one from another Electron package's files manually. And then it refused to even start when I was running scaled if I enforced the Ozone platform.

**Comment by ad4g472aqvti** [comment]
You'll want to use discord canary (Discord's official alpha client) as it was recently updated with a new version of electron that supports wayland. 

As for the topic at hand, games have been the biggest issue for me as scaling changes the logical resolution. Mutter seems to have a fix for this in their xwayland implementation but this ain't the case for wlroots/labwc. These aren't really labwc problems specifically but still something that should be noted.

**Comment by kode54** [comment]
If you use the HiDPI patches, you won't experience blurring or logical resolution problems, or at least, they'll be different.

For example, in my setup, with a 3840x2160@60 monitor (LG 24UD58-B) running 2.0 scale, and a 1920x1080@60 monitor (Dell P2414H) running 1.0 scale, and Xwayland running with the xprop scale factor set to 2, I Xorg apps seeing the resolution of both monitors as 3840x2160, apps run pixel per pixel on the HiDPI display, and downscaled on the other one.

The games I've tried thus far seem to run unscaled on the HiDPI display. Apps that observe the GDK_SCALE environment variable will upscale to 2.0 and run normally on both displays. Steam seems to be the one outlier, where it will see the GDK_SCALE on startup and double its resolution, and also does its own window size doubling, in addition to the Xwayland doubling due to the scale factor. This seems to only be designed to work properly on Gnome, which does its own thing that doesn't involve Xorg having any knowledge of scaling.

**Comment by johanmalm** [comment]
@joshuataylor Thanks!
We should put this on the labwc website.
I think it deserves its own page.
Do you want me to try to distill it into a PR or would you be happy to?

**Comment by joshuataylor** [comment]
I'll take a crack at it. I believe there is a fair bit that could be added to this topic, as well as general "waylandisms" that would make good pages/reference points.

LabWC is great, as you can basically build your own dream DE, but Wayland/XWayland/wlroots is moving fast, so we'll need to ensure the documentation is kept up to date.

**Comment by johanmalm** [comment]
^ Yes, agree - docs very important.

Shout if you want a steer with the website setup. It’s basically just a matter of creating an .md file in the src/ folder. There is a workflow that does the magic.

**Comment by joshuataylor** [comment]
Created a PR here, sorry for the delay on this, been crazy busy the last few weeks.

https://github.com/labwc/labwc.github.io/pull/18

**Comment by dinotheextinct** [comment]
I am not sure where else to put this, I am using labwc again after a hiatus through Plasma. I managed to fix some scaling issues, with flatpak apps, through flatseal. But one issue remains with steam.

When using `❯ bat --pager=never -p .config/kanshi/config
profile {
  output DP-2 mode 3840x2160@240Hz position 0,0 scale 1.35
}`

Steam looks blurry, although supposedly there should be a fix for this now with: https://github.com/ValveSoftware/steam-for-linux/issues/5460#issuecomment-2253588058
Although I am not sure what that exactly means in terms of labwc.

When I uncomment the following from labwc/environment:
`XDG_CURRENT_DESKTOP=wlroots
XDG_CURRENT_DESKTOP=labwc
# GDK_SCALE=1.35
# GDK_DPI_SCALE=1.35`

It seems steam gets sharper, although the size is still quite big, although I am using the exact same value as for the kanshi setting. The problem with this is, the GDK_SCALE also affects e.g. Firefox and makes it tremendously big.

So I am really at a loss here how to properly configure scaling. According to https://labwc.github.io/hidpi-scaling.html#scaling the GDK_SCALE should only affect non-wayland apps, whilst Firefox runs on wayland natively, so I am really confused.

**Comment by johanmalm** [comment]
I think I'm right in saying that most of the devs don't run with scale > 1, so don't have a huge amount of experience with this.

@kode54 @ahesford - from memory you sometimes run with scale >  1... any advice?

**Comment by ahesford** [comment]
Is Steam running as an X11 client? XWayland will always be blurry with fractional scaling in wlroots, and there's not much we can do about it.

**Comment by dinotheextinct** [comment]
> Is Steam running as an X11 client? XWayland will always be blurry with fractional scaling in wlroots, and there's not much we can do about it.

Yes to my knowledge Steam has no native Wayland client. That all Xwayland applications will be blurry with fractional scalign in wlroots is news to me.

I am still wondering why Steam is affect by both settings. If I find the time I will check other wayland WM issues in regards to this.
