### ISSUE TITLE
Focus follows mouse is incomplete

### ISSUE THREAD

**Issue by jech** [labwc/labwc#830]
When using focus follows mouse, the focus does not always follow the mouse.  Specific cases that I've noticed:

   * if the focused window is closed, the window under the cursor is not selected until I move the mouse;
   * after switching desktops using action `GoToDesktop`, the window under the cursor does not get selected.
 
There are certainly others, these are just the cases that bother me in everyday usage.

**Comment by Consolatis** [comment]
Hm.. right. Thanks for bringing this up.
We are only updating the mouse focus in those cases but do not update the keyboard focus.

I wonder if we could get away with just doing the `desktop_focus_and_activate_view()` / `desktop_move_to_front()` dance in `cursor_update_focus()` if followMouse / raiseOnFocus is set by the user.

**Comment by jech** [comment]
Thanks, that seems to work fine.  It brings labwc to a level at which I can attempt to do some serious work under it :-)

**Comment by Consolatis** [comment]
Should be fixed by #844, feel free to comment when that is not the case.
