### ISSUE TITLE
No obvious way to unminimise a window

### ISSUE THREAD

**Issue by jech** [labwc/labwc#843]
I'm running labwc without a dock, and by default every window has a minimise button.  If I click the minimise button, the window disappears, and I've been unable to find a way to get it back.

Under OpenBox, the `client-menu` can be used to recover the window.  I suggest that until a client menu is implemented in labwc, the decorations should not include a minimise button by default.

**Comment by Consolatis** [comment]
The usual way to restore minimized windows is via `A-Tab` or some panel.

**Comment by johanmalm** [comment]
^ What @Consolatis said.
