### ISSUE TITLE
A-Tab OSD does not scale to font size

### ISSUE THREAD

**Issue by domo141** [labwc/labwc#852]
when enlarging

 &lt;font place="OnScreenDisplay"&gt;... &lt;size&gt;10&lt;/size&gt;...

to something larger the text in in OSD selector is larger but rest of the OSD popup seems to look the same.

In my current configuration I use size 20 which is useable but ugly...

As I wish to use size 30, I looked the code and did the following (naive) change in src/osd.c

    -#define OSD_ITEM_HEIGHT (20)
    -#define OSD_ITEM_WIDTH (600)
    -#define OSD_ITEM_PADDING (10)
    -#define OSD_BORDER_WIDTH (6)
    +#define OSD_ITEM_HEIGHT (20 * 3)
    +#define OSD_ITEM_WIDTH (600 * 3)
    +#define OSD_ITEM_PADDING (10 * 3)
    +#define OSD_BORDER_WIDTH (6 * 3)

changed size to 30 and -- so far, with 3 rxvt-unicode windows, the OSD looked ok.

As I am not familiar with the code I don't try to make proper patch, or even try to suggest how code should be changed.

I have configured "MenuItem"s to have font size 30 and weight bold -- that works fine. 

The issue #405 is interesting in this context. At least it would not be worse for size 10 fonts if this issue gets improved...

**Comment by johanmalm** [comment]
Thanks for raising. Yes, those defines are not great :smile:
We need to make it dynamic/configurable.
It'd be good to get some thoughts on this on the rule-set for this.

**Comment by 1qh** [comment]
![image](https://user-images.githubusercontent.com/64073540/231778611-47ee44e1-aa16-4c9d-bccd-5f0a2f74226d.png)

It would be awesome if we can have following configurations for the OSD:
- item height, width
- item vertical padding
- focus item border width
- focus item background and text color
- possible to hide each of 3 columns
- position of desktop name (top/bottom) 
- different font size for desktop switcher and window switcher
- size of the squares in desktop switcher

Thanks a lot. Looking forward for you to add these features.

**Comment by domo141** [comment]
fixed by commit  df53c28a0 (2023-06-29)
