### ISSUE TITLE
Make columns of window switcher configurable

### ISSUE THREAD

**Issue by Eucyon** [labwc/labwc#855]
Currently the protocol, the program name and the window title are show.

Please enable blinding out columns per configuration.

Thanks, also in general for this great compositor!

**Comment by johanmalm** [comment]
Good idea.

How about something like

```xml
<core>
  <windowSwitcher>
      <column content="type" width="25%" />
      <column content="app_id" width="50%" />
      <column content="title" width="25%" />
  </windowSwitcher>
</core>
```

**Comment by Eucyon** [comment]
That would be great!

**Comment by Consolatis** [comment]
> Good idea.
> 
> How about something like
> 
> ```xml
> <core>
>   <windowSwitcher>
>       <column content="type" width="25%" />
>       <column content="app_id" width="50%" />
>       <column content="title" width="25%" />
>   </windowSwitcher>
> </core>
> ```

Or with an additional `<columns>` node? e.g. something like
```xml
<core>
  <windowSwitcher show="true" preview="yes" outlines="yes">
    <colums>
      <column width="25%" content="type" />
      <column width="50%" content="app_id" />
      <column width="25%" content="title" />
    </colums>
  </windowSwitcher>
</core>
```

I guess both would work but I feel like the additional node is a bit cleaner. I am fine with the other variant as well though.

**Comment by johanmalm** [comment]
I like the `<columns><column>` approach. It's consistent with the surrounding config syntax.

On further thought, I have three further questions before delving into coding it:

1. How about moving `<windowSwitcher>` up a level so it's not a child of `<core>`. I know it's another breaking change, but if we want to do it, it's better now before the next release.
2. Suggest calling it `<field>` rather than `<column>` because it's clearer and keeps options open for using columns of views in the future.
3. Shall we put the following windowSwitcher options in `themerc-override` rather than `rc.xml`: item height/width, item vertical padding, focus item border width and focus item background/text color (see #879)

```
<windowSwitcher show="true" preview="yes" outlines="yes">
  <fields>
    <field width="25%" content="type" />
    <field width="50%" content="app_id" />
    <field width="25%" content="title" />
  </fields>
</windowSwitcher>
```

**Comment by Consolatis** [comment]
> 1. How about moving `<windowSwitcher>` up a level so it's not a child of `<core>`. I know it's another breaking change, but if we want to do it, it's better now before the next release.

Fine with me, with fallback to `windowSwitcher.core` + deprecation message?

> 2\. Suggest calling it `<field>` rather than `<column>` because it's clearer and keeps options open for using columns of views in the future.

Personally I think `column` is more clear but I don't feel particularly strong about it either way. What kind of "columns of views" are you referring to here?

> 3\. Shall we put the following windowSwitcher options in `themerc-override` rather than `rc.xml`: item height/width, item vertical padding, focus item border width and focus item background/text color (see [OSD customizations #879](https://github.com/labwc/labwc/issues/879))

In general I am in favor of having settings that describe the look of things in the theme. Regarding the specific variants here, I'd suggest removing item height completely and instead replacing it with something like `osd.item.padding.y` and then always calculate the height like `osd.item.padding.y * 2 + font_height(osd_font)`. The others seem fine on the first glance.

**Comment by johanmalm** [comment]
Looks like we're aligned on 1+3.

Regarding the use of `<column>` - I was just trying to future proof in case we ever wanted to use a grid of entries (=toplevel views). At the moment we only use one column (in the grid sense of the word), but I suppose it's foreseeable that we might want to support _n_x2 or _n_x3 in future. Just to be clear - as a feature I don't think it's something we ought spend time on now - but if we wanted to reserve the word `column` than `field` could be a good option.

**Comment by Consolatis** [comment]
Should be fixed by
- #886
- #889

@Eucyon Feel free to comment if that is not the case and we'll reopen the issue. Thanks for the suggestion.
