### ISSUE TITLE
AlwaysOnTop windows don't appear in the OSD

### ISSUE THREAD

**Issue by ghost** [labwc/labwc#856]
Easy to replicate, toggle any window AlwaysOnTop via the graphical client-menu and then Alt+Tab.
It happens with Wayland native programs and Xwayland as well. I only tested this on the lastest git master.
I believe this is a bug because the user cannot gain control back on the "OnTop" window.

**Comment by Consolatis** [comment]
Note about implementing a fix:
We might need to return to looping over `server->views` with a filter for node->parent being either the current workspace tree or the always-on-top tree. That should fix it.

**Comment by Consolatis** [comment]
> > I actually intend to revert to using server->views + filter for current workspace (at least for `A-Tab`) because otherwise always-on-top views (and other non direct children of the workspace nodes) will not show up there (#856).
> 
> I had been thinking similar thoughts :smile:
> +possibly showing all workspaces in windowSwitcher? I know we said originally that we wouldn't but...
> Preview would be hard I guess - but possibly not needed for other workspaces.

_Originally posted by @johanmalm in https://github.com/labwc/labwc/issues/866#issuecomment-1493115601_

Good point regarding preview. Guess there is still some stuff to work out if we ever to decide to add that config option.

**Comment by johanmalm** [comment]
COMPLETE
https://github.com/labwc/labwc/commit/c71fccbcec7749635bac1967942fe18d1873f8f8
