### ISSUE TITLE
Implement `titleLayout` feature

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#857]
[B+ - 2.4.2](https://github.com/labwc/labwc-scope#24-configuration---theme)
See [here](http://openbox.org/wiki/Help:Configuration#Theme) for more info.

I'd like to be able to remove to remove the client-menu button, because I can always just right click the title bar anyways so it seems unnecessary to me. Also having the option to move the window buttons to the left might be nice for some people.

**Comment by CosmicFusion** [comment]
i want them on the left

**Comment by johanmalm** [comment]
Until titleLayout is implemented you can hide the menu buttons by adding the following to `~/.config/labwc/themerc-override`:

```
window.active.button.menu.unpressed.image.color: #000000 0
window.inactive.button.menu.unpressed.image.color: #000000 0
```

Note the `0` at the end for zero alpha (i.e. transparent)
