### ISSUE TITLE
With `focus.followMouse` enabled, new windows no longer receive focus

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#862]
Bisection indicates that this regressed in f5c4651c67236191caa30b09c5e5f3774fa98864. To reproduce, simply enable `focus.followMouse`, open a window, maximize it, and open a second window. The second, new window does not receive focus.

Openbox has a `focus.focusNew` [setting](http://openbox.org/wiki/Help:Configuration#Focus), which is independent of `focus.followMouse`. labwc doesn't implement this setting yet, but I don't think the focus-new behavior should depend on `focus.followMouse` the way they now do. In general it is surprising that all of a sudden new windows no longer receive focus.

I believe the changes in f5c4651c67236191caa30b09c5e5f3774fa98864 may have made `focus.followMouse` behave more like `focus.underMouse`, another Openbox setting that labwc doesn't yet support.

**Comment by Consolatis** [comment]
`focus.focusNew` is the default for labwc so I don't think we need a setting for it. It would also severly complicate the already somewhat complex codepaths for followMouse in general.

We could implement `focus.underMouse` (which btw is a somewhat confusing name in regard to the overall `focus.*` family) and make our latest changes depend on it. That should restore the state from before the changes and also allow a more strict usage as "if its under the cursor it receives foucs (unless we are in `A-Tab`)".

**Comment by Consolatis** [comment]
Regression should be fixed and now default to the old behavior.
