### ISSUE TITLE
wlr-randr: display off/on looses window's fullscreen state

### ISSUE THREAD

**Issue by m1027** [labwc/labwc#864]
Hi,

I have got key bindings to switch the display off and on via wlr-randr. When the display is swiched on again, all maximized windows appear unmaximized.

See my config below.

Thanks

`<keybind key="C-A-1"><action name="Execute"><command>wlr-randr --output eDP-1 --off</command></action></keybind>`

`<keybind key="C-A-2"><action name="Execute"><command>wlr-randr --output eDP-1 --on</command></action></keybind>`

**Comment by Consolatis** [comment]
I assume you have a single display?

**Comment by m1027** [comment]
Yes, a single display only.

The version is this commit from master:

commit e44d56567284c5860c1c3148c09628b50ce477db (HEAD -> master, origin/master, origin/HEAD)
Author: Consolatis <35009135+Consolatis@users.noreply.github.com>
Date:   Tue Mar 28 19:23:49 2023 +0200

And maybe I should be more precise: I am not 100% sure but it is probably the fullscreen state that gets lost, not the maximized state.

Thanks for investigating this issue.

**Comment by Consolatis** [comment]
Yes, the fullscreen state is indeed removed when turning the monitor off.
This was a deliberate choice because usually the windows will be transferred to a still running output (if there are multiple ones).
And as the resolution of the new output may be different to the old one we just disable fullscreen in that case to not confuse applications that are in fullscreen and suddenly get their output / dimensions changed.
If there is only a single output available, disabling and re-enabling it is basically the same as transferring applications to another output (that just happens to have the same dimensions and layout position).

The maximized state (same for the tiling states) should not be lost.

**Comment by m1027** [comment]
Thanks again for your effort in this.

While understanding the reasons for your choice I permit myself to see things differently here: :-)

- I am just saving energy by switching the display off when not needed. So that's quite often and not for attaching a new monitor.
- When looking for code how sway handles it, I often see snippets that save energy by swichting the display off together with a screen locker.
- I've been using wayfire for some time and they just keep the fullscreen / maximized state even after display off/on.
- There are probably a lot of users with a single screen scenario only and I believe most users tend to be a little surprised when their windows get resized by display off/on.

I hope you see the use case here and that there will be a way in labwc too to not loose the fullscreen state in case its the same display being off and on (or one with the same dimensions). 

Thanks again for this awesome WM.

**Comment by johanmalm** [comment]
I haven't looked into this, but quick response nonetheless:

- There are two protocols here. `wlr-output-power-management` (that wlopm uses) and `wlr-output-management` (that wlr-randr uses).
- I think I'm right in saying that `wlr-output-power-management` is the one that should be used to 'turn off' displays with a screensaver, whereas `wlr-output-management` is the equivalent of pulling out the screen-cable.
- Again, I prefix this with "I think" that `wlopm --off` is just as energy efficient as `wlr-randr --off` (i.e. both should be zero).
- The main difference is that with `wlr-randr --off` we move windows to different outputs whereas with `wlopm --off` we just leave windows where they are (hopefully the reasons are obvious). I haven't tried this with `sway` for a long time, and probably never with `wayfire` and would be curious to know if they behave differently.

Having said all that, I take @1027's point that if we do `wlr-randr --off` on the last remaining output we could leave windows as they are. I haven't looked at the code for this - it might create an messy edge case... not sure.
I'd appreciate feedback from other users... is it common practice to use `wlr-randr --off` with your screenlock ???

See this for reference:
https://github.com/labwc/labwc/blob/e44d56567284c5860c1c3148c09628b50ce477db/docs/autostart#L23-L34

**Comment by Consolatis** [comment]
So something like this (not even compile tested)
```c
/* In output.c */
size_t output_get_active_count(struct server *server)
{
	size_t count = 0;
	struct output *output;
	wl_list_for_each(output, &server->outputs, link) {
		if (output_is_usable(output)) {
			count++;
		}
	}
	return count;
}

/* And in view_adjust_for_layout_change  */
/* ... */
if (was_fullscreen && !output_is_usable(view->output) && output_get_active_count(server) > 0) {
	set_fullscreen(view, false);
}
/* ... */
```
It would also require some more minor changes in view.c as we currently `assert(!view->fullscreen)` in for example `view_discover_output()`.

**Comment by jlindgren90** [comment]
My suggestion would be to handle the fullscreen state just like the maximized state. So when an output is disabled/disconnected, we first try to move any fullscreen view(s) on it to another output (where they remain fullscreen). Or if all outputs are disabled, we leave the internal "fullscreen" flag set, but don't touch the geometry until some output is enabled again.

I think overall that would simplify the code a bit. (Though we need to be a little careful with the  `ZWLR_LAYER_SHELL_V1_LAYER_TOP` stuff; that logic currently isn't prepared to handle a fullscreen view moving between outputs.)

**Comment by jlindgren90** [comment]
I would also echo what's been said already though, to use `wlopm` for power management rather than `wlr-randr`.

**Comment by m1027** [comment]
I've been playing with wlopm and it indeed WFM.

That being said, I still believe the new behaviour discussed here makes sense to be implemented:

- I don't know how established wlopm is yet. At least, it is not packed for Gentoo and I had to build it manually. (I can try to make it a package, though. labwc is missing either.)
- @johanmalm : The distinction between the two protocols sounds convincing, however it seems that it is at least still a common practise to use wlr-randr.
- I believe that in a single monitor scenario it whould still be a good thing to get the windows in the previous state when the (single) monitor is unplugged and re-plugged. Why changing the window state in such a case.

Thanks again!

**Comment by xxhh1112** [comment]
ewewq
