### ISSUE TITLE
Pointer warp doesn't seem to be implemented(?), breaking certain games.

### ISSUE THREAD

**Issue by FuzzyQuills** [labwc/labwc#872]
This bug shows up in the most obvious way in Overwatch 2; normally when opening the communication wheel in-game by holding down the C key, the cursor gets recentered to the middle of the wheel by the game. 

In Labwc however, this doesn't occur and as a result, the cursor is still sitting where it was last moved. (Let's say I said "thank you" before closing the wheel, next time it's opened, it's still sitting on "thank you" instead of being in the middle like it's supposed to be)

Workaround: Play game through gamescope or use a different WM.

Given Sway also has this issue, could this be a wlroots bug?
KDE doesn't have this issue.

**Comment by FuzzyQuills** [comment]
Just made an attempt to fix this issue myself; feedback would be appreciated!

**Comment by Consolatis** [comment]
Thanks a lot. I am a bit short on time currently but will review the PR later today.
