### ISSUE TITLE
OSD customizations

### ISSUE THREAD

**Issue by 1qh** [labwc/labwc#879]
![image](https://user-images.githubusercontent.com/64073540/231778611-47ee44e1-aa16-4c9d-bccd-5f0a2f74226d.png)

It would be awesome if we can have following configurations for the OSD:
- item height, width
- item vertical padding
- focus item border width
- focus item background and text color
- possible to hide each of 3 columns
- position of desktop name (top/bottom) 
- different font size for desktop switcher and window switcher
- size of the squares in desktop switcher

Thanks a lot. Looking forward for you to add these features.

**Comment by m1027** [comment]
Same here, I recently tried a large font size but the line height does not scale, so the displayed lines start to overlap.
`<font place="OnScreenDisplay">
		<name>DejaVu Sans Mono</name>
		<size>30</size><weight>normal</weight><slant>normal</slant>
    </font>
`

**Comment by Consolatis** [comment]
Hm.. right. Although we actually calculate the line height of the configured font, we only subtract it from a hardcoded item height (20px) to center the line. So if the line height based on the font config is > 20px, stuff starts to get wrong. We should likely replace that logic with some theme setting like `osd.item.padding.y` and remove the height of the item completely so its always calculated like `osd.item.padding.y * 2 + font_height(font_osd)`

If you feel like modifying the code itself to make your local copy work for bigger font sizes, `src/osd.c` right at the top: `OSD_ITEM_HEIGHT`.

**Comment by johanmalm** [comment]
Will track this in #968 
Closing.
