### ISSUE TITLE
Cannot get `wl-gammarelay-rs` to work

### ISSUE THREAD

**Issue by 1qh** [labwc/labwc#884]
[This program](https://github.com/MaxVerevkin/wl-gammarelay-rs) has been [reported](https://github.com/swaywm/sway/issues/6577) to work perfectly on sway, but I cannot figure out how to use it with labwc. Could anyone take a look? I just simply want to be able to invert color that I sometimes need to.

Thank you a lot!

**Comment by 1qh** [comment]
@Flrian Have you try the version installed from AUR? Mine still not working :(

**Comment by johanmalm** [comment]
> @Flrian I've tried install with cargo but got no luck. Have you try the version installed from AUR? Or do I need to set some kind of env variable?

I use Arch. I just installed `wl-gammarelay-rs` from the AUR and it worked using the command the @Flrian gave. I don't think I've got any environment variables set that would affect this.

**Comment by Consolatis** [comment]
Is there any error message that could indicate a reason?
If not, starting the daemon like `WAYLAND_DEBUG=1 wl-gammarelay-rs run` might shed some light on the issue.

**Comment by 1qh** [comment]
Oh I figured out why. Simply because I also have `wlsunset` in my `~/.config/labwc/autostart`. Basically these 2 programs cannot run at the same time.

**Comment by Consolatis** [comment]
Thanks for reporting back :)
