### ISSUE TITLE
Popup when switching a workspace is shown two times

### ISSUE THREAD

**Issue by franzmondlichtmann** [labwc/labwc#914]
The popup when switching a workspace is shown two times on a wide display (30inch 2560x1080 px, 180.000000 Hz).
One popup is set perfectly in the middle.
The other popup appears ca 2 cm to the left and 0,5 cm up.
Otherwise the popup work fine, it just looks weird.

**Comment by franzmondlichtmann** [comment]
I'm also using Kanshi to disable my first display (notebook) and and activate the second display.

**Comment by Consolatis** [comment]
Sounds like the workspace OSD isn't checking if the output is enabled.
Thanks for reporting and including the kanshi-to-disable-first-display hint, that made figuring out why this is happening a lot easier.
I'll prepare a PR to fix this later.

**Comment by franzmondlichtmann** [comment]
@Consolatis I will look into it when I have some time.

**Comment by franzmondlichtmann** [comment]
Whats the best way to test this issue on a system with labwc already installed?

**Comment by Consolatis** [comment]
You could do something like this:
```shell
mkdir -p ~/testing && cd ~/tmp/testing
git clone https://github.com/labwc/labwc.git
cd labwc
git fetch origin pull/915/head && git checkout FETCH_HEAD
meson setup build
meson compile -C build
```

Then exit your installed labwc so you are on your TTY and start the newly compiled labwc:
```
cd ~/testing/labwc
build/labwc
```
It should pick up all your existing settings. When you verified the double workspace popup isn't happening anymore (and it isn't crashing or anything) you can simply exit labwc again and start up your usual one.
After that you can delete `~/testing/labwc` or keep it around in case you want to test the latest version or some other PR in the future.

Disclaimer: I wrote the commands by hand, so some silly typing mistake is possible.

**Comment by franzmondlichtmann** [comment]
It is crashing in the testing environment, when I switch the workspace via the meta + number keys.
I did start with the debug flag. Where are the logs?

**Comment by Consolatis** [comment]
I missed a code path, sorry about that. Have pushed a fix for the PR.

If you want to test again:
```shell
cd ~/testing/labwc
git fetch origin pull/915/head && git checkout FETCH_HEAD
meson compile -C build
```

**Comment by franzmondlichtmann** [comment]
Perfect, works like intended. (Single popup in the middle)

**Comment by Consolatis** [comment]
Sweet, thanks for reporting and testing.
