### ISSUE TITLE
Mouse buttons are mapped backwards for config

### ISSUE THREAD

**Issue by 10leej** [labwc/labwc#925]
Hello, running 0.6.3 I noticed that the default configuration maps the [desktop menu to the right mouse button click](https://github.com/labwc/labwc/blob/master/docs/rc.xml#L39), however in practice I found that it's backwards.  
I'm not certain if there's a difference since I'm in the US compared to SE

**Comment by Consolatis** [comment]
The example `rc.xml` should show the usual "application" menu on left click and a simplified `Reconfigure` and `Exit` menu on right click. Maybe you are missing the default `menu.xml` file in `~/.config/labwc/`?
