### ISSUE TITLE
If I turn my second monitor off, its off forever.

### ISSUE THREAD

**Issue by franzmondlichtmann** [labwc/labwc#928]
I autostart Kanshi, like so:
`kanshi >/dev/null 2>&1 &`
Kanshi profile:
`profile {
	output eDP-1 disable
	output HDMI-A-1 mode 2560x1080@180Hz
}`
If I turn my second monitor off, and then on again it keeps being black (ASUS Start Logo appears though.)
It says HDMI-1 connection not found.
And my laptop monitor is also off, because of Kanshi.
Therefore only option is to turn of the laptop with the power button.

**Comment by Consolatis** [comment]
If not starting kanshi, does the same thing happen for the HDMI output as well? e.g. not returning after being turned off?

**Comment by franzmondlichtmann** [comment]
Sorry, seems to be a kanshi problem
