### ISSUE TITLE
Seperate files for right click and left click menu

### ISSUE THREAD

**Issue by franzmondlichtmann** [labwc/labwc#930]
A way to specify the path to a custom menu-config file in rc.xml for the right click menu.
Or a default right click menu config file.
I use the labwc menu generator and it overrides the default menu.xml file. So far so fine.
But I want a seperate right click menu for an exit command. Normally that would be done inside the menu.xml file.

**Comment by zeGolem** [comment]
You should be able to achieve that by creating 2 separate menus in menu.xml, then linking them to the corresponding mouse button. Haven't tested it, but it should be something like this:

rc.xml:

```xml
...
<mouse>
    ...
    <context name="Root">
        ...
        <mousebind button="Right" action="Press">
            <action name="ShowMenu" menu="root-menu-right"/>
        </mousebind>
        <mousebind button="Left" action="Press">
            <action name="ShowMenu" menu="root-menu-left"/>
        </mousebind>
        ...
    </context>
    ...
</mouse>
...

```

menu.xml

```xml
...
<menu id="root-menu-right">
  <!-- Menu for right click -->
</menu>
<menu id="root-menu-left">
  <!-- Menu for left click -->
</menu>
...
```

**Comment by Consolatis** [comment]
I don't think a second `menu.xml` would really make it easier. And even if we were to implement something like a `<include "some-other-menu.xml" />` tag, it would still require to manually update the generated `menu.xml` file at which point the second menu could manually be included there as well as in the example posted by @zeGolem.

So if @johanmalm agrees I'd vote for closing this issue.

**Comment by johanmalm** [comment]
Trust that @zeGolem ’s response answers this
