### ISSUE TITLE
vscode-insiders is glitchy and laggy.

### ISSUE THREAD

**Issue by franzmondlichtmann** [labwc/labwc#936]
I installed labwc on a machine which has nvidia gtx 1060 on board.
Firefox and chrome work without problems, but vscode-insiders is glitchy and laggy.

CPU: 6-core Intel Core i5-9500 (-MCP-)
speed/min/max: 3000/800/4400 MHz Kernel: 6.3.2-arch1-1 x86_64
Up: 32m Mem: 1472.4/15801.5 MiB (9.3%)
Storage: 912.89 GiB (1.0% used) Procs: 175 Shell: fish inxi: 3.3.27

**Comment by franzmondlichtmann** [comment]
I should add that vscode-insiders its laggy and glitchy from the start

**Comment by franzmondlichtmann** [comment]
Setting following environment variables solved the issue:
`
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
`

**Comment by Consolatis** [comment]
Very interesting. Thanks for adding the fix here as well.
