### ISSUE TITLE
Raise minimized windows of other workspaces impossible with waybar

### ISSUE THREAD

**Issue by stefonarch** [labwc/labwc#937]
To test:

1. minimize a window
2. switch workspace
3. try to activate it with waybar `wlr/taskbar`

Using `yatbwf` instead this issue doesn't exist and all windows can be raised. Also no issue with waybar on wayfire

**Comment by Consolatis** [comment]
Hm.. it might just call `unset_minimized()` instead of also `activate()`.
Activate should automatically switch to the workspace the window is currently on.

**Comment by stefonarch** [comment]
I stumpled upon that testing  a "Show Desktop" button on the panel which executed ` wlrctl toplevel minimize state:inactive`. It worked quite well, but most buttons on the taskbar were "dead" after using it.

The patch looks working fine, had to apply id manually as I got 

```
$ cat minimize_diff |git apply
error: corrupt patch at line 22

```

**Comment by Consolatis** [comment]
> EDIT: the patch has an issue - a minimized window on the same desktop is not raised anymore.

The patch really shouldn't make a difference in that regard, the only thing it should be doing is additionally switching the workspace on unminimize. I can't really reproduce it, neither with nor without the patch.

**Comment by stefonarch** [comment]
Can't reproduce anymore.
