### ISSUE TITLE
lxqt

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#941]
Things to fix in general:

- [x] Window-rule property ~~`skipInteractiveMoveResize`~~ `fixedPosition`
- [x] #940 
- ~~Remove 60px hard-coded min-height~~
- [x] Hide always-on-top layer when running an application in full-screen. See conversation here: https://github.com/labwc/labwc/pull/947#issuecomment-1606256482

In support of `lxqt-panel`
- [x] `MoveTo` action (#947)
- [x] `<margin>` (#947)
- [x] `matchOnce` property to only apply rules to panel rather than configuration windows with the same app_id (#947)

In support of `lxqt-notificationd`
- ~~Window-rule property `allowFocusRequest` in support of `<windowRule identifier="lxqt-notificationd" skipTaskbar="yes" skipWindowSwitcher="yes" allowFocusRequst="no">`~~

**Comment by stefonarch** [comment]
For notifications some kind of  ` <windowRule identifier="lxqt-notificationd" skipTaskbar="yes" skipWindowSwitcher="yes" nofocus="yes">` rule would be  needed.

**Comment by stefonarch** [comment]
> In support of `lxqt-panel`

Just started using gaps and the panel is affected by it, so a `gap="no"` maybe needed.

**Comment by Consolatis** [comment]
That might somewhat complicate the codebase. Just thinking out loud, maybe we could instead add an optional argument to `MoveToEdge` which ignores the gap. I am not sure which variant is less disruptive.

**Comment by johanmalm** [comment]
> > In support of `lxqt-panel`
> 
> Just started using gaps and the panel is affected by it, so a `gap="no"` maybe needed.

Yes, I had noticed the regions/gap interaction. Also, regions currently only take a % argument, so not quite right atm.
I envisaged a simple `MoveTo` (which doesn't take into account gaps) as suggested in Original Post. Thoughts?

**Comment by stefonarch** [comment]
This sounds good. Using "regions" has also the downside  that it affects the config window.

**Comment by stefonarch** [comment]
Some checkboxes can be ticked. The 60px rule could stay as it doesn't matter anymore, a bottom panel can be placed with `<action name="MoveTo" x="0" y="x"/>`  with x = screen height - panel height, although all popups open at screen border so it's anyway not really usable.

**Comment by stefonarch** [comment]
>Hide always-on-top layer when running an application in full-screen.

Nonetheless I knew that for a panel "layer-bottom+exclusive zone" is the best combination I never tested it until today. It works perfectly, although 2 applications are on the bottom layer (panel and pcmanf-qt's desktop) the panel stays above the desktop always as the latter respects "margin-top".

So "nofocus" rule is the last missing piece: https://github.com/labwc/labwc/issues/1057

**Comment by stefonarch** [comment]
>In support of lxqt-notificationd

This can be removed as in LXQt 2.0 all components which need layershell have it built it. 

>Remove 60px hard-coded min-height

I don't remember exactly  but with `margin=` it was no issue anymore 

>Hide always-on-top layer when running an application in full-screen.

`lxqt-panel` 2.0 uses `mLayerWindow->setLayer(LayerShellQt::Window::LayerTop);` and and using F11 on other applications or fullscreen youtube the panel is hidden, so this looks solved somewhere.
Thanks a lot for the support of LXQt 1.x .

**Comment by johanmalm** [comment]
Thanks @stefonarch 
Have updated OP. Closing.
