### ISSUE TITLE
Feature request: tiling with mouse cursor

### ISSUE THREAD

**Issue by glow12121** [labwc/labwc#943]
Getting windows tile with hotkes is a great feature but doing the same with the mouse cursor, like in Windows or Gnome, would be super nice. Thanks!

What I mean is dragging windows to the screen edges so they resize to a certain size and position within a tile grid.

**Comment by johanmalm** [comment]
This is already supported through the following:

https://labwc.github.io/labwc-config.5.html#window_snapping
https://labwc.github.io/labwc-config.5.html#regions

Feel free to re-open if I'm misunderstanding the feature request.
