### ISSUE TITLE
changing workspace with scrolling doesn't work on upstream

### ISSUE THREAD

**Issue by mantarimay** [labwc/labwc#948]
Version: labwc-0.6.3+git12.f817a9e

**Comment by johanmalm** [comment]
Have you defined some workspaces? By default there is only one.

https://labwc.github.io/labwc-config.5.html#workspaces

**Comment by mantarimay** [comment]
@johanmalm its work with key bind but it did not work with mouse scrolling
![Screenshot from 2023-06-09 16-18-44](https://github.com/labwc/labwc/assets/42089808/59434fba-d7a6-4169-b9cd-e42475d67252)

**Comment by johanmalm** [comment]
Thanks for reporting. Great catch.
I can reproduce and understand what's going on here. 
PR #950 raised.
