### ISSUE TITLE
Clicking root window doesn't close GTK menus

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#949]
See https://github.com/LBCrion/sfwbar/issues/98 for context.

**Comment by 01micko** [comment]
Actually clink anything other than the root window, doesn't need to be GTK closes the GTK menu.

**Comment by johanmalm** [comment]
Linked to #826

**Comment by Consolatis** [comment]
I am not 100% convinced that we aren't simply missing a `seat_focus(seat, NULL);` on clicks to labwc "owned" surfaces.
E.g. GTK closing its menus itself when it looses keyboard focus.

**Comment by 01micko** [comment]
I ran [waybox](https://github.com/wizbright/waybox) nested and started sfwbar and the popups close clicking on the empty desktop so it doesn't have this issue. It's fairly spartan compared to `labwc`. Not for me :laughing:

**Comment by Consolatis** [comment]
Thanks for linking it though, its completely new to me.

On a related note, feel free to give
- #1016

a test ride.

**Comment by 01micko** [comment]
> Thanks for linking it though, its completely new to me.
> 
> On a related note, feel free to give
> 
> * [src/cursor.c: end popup grab on desktop click #1016](https://github.com/labwc/labwc/pull/1016)
> 
> a test ride.

Test passed :)
