### ISSUE TITLE
Touchpad two finger right click not working

### ISSUE THREAD

**Issue by mohit310** [labwc/labwc#957]
I've set my rc.xml to use the following libinput config but the touchpad doesn't use two finger rightclick. Based on your current config, you are missing setting libinput click methods to clickfinger for the tapButtonMap -> lrm to work 
 

rc.xml
```xml
<libinput>
    <device category="SynPS/2 Synaptics TouchPad">
      <naturalScroll>no</naturalScroll>
      <leftHanded>no</leftHanded>
      <accelProfile>adaptive</accelProfile>
      <tap>yes</tap>
      <tapButtonMap>lrm</tapButtonMap>
      <middleEmulation>no</middleEmulation>
      <disableWhileTyping>yes</disableWhileTyping>
    </device>
</libinput>
```

Here is my libinput list-device output for my touchpad.
```
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event14
Group:            7
Seat:             seat0, default
Size:             70x50mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```

PS - Love all the work everyone has put in this. this is my daily driver and would love to see 2 issues -> this one and other 'Show desktop' fixed.

**Comment by Consolatis** [comment]
To rule out matching criteria issues, could you try `<device category="default">`?
`Tap-to-click` seems to be disabled which doesn't match your configuration for `<tap>`.

**Comment by mohit310** [comment]
tried with default and still same 
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event14
Group:            7
Seat:             seat0, default
Size:             70x50mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a

**Comment by johanmalm** [comment]
I don’t know what the problem is here.

Ref: https://wayland.freedesktop.org/libinput/doc/latest/clickpad-softbuttons.html#clickfinger

How many fingers does your device support?

Could you try printf()ing libinput_device_config_tap_get_finger_count(libinput_dev)
… in seat.c around line 89

**Comment by datMaffin** [comment]
Currently looking into basically the same issue. I would like to have:
* 1 finger click -> always left click
* 2 finger click -> always right click
* 3 finger click -> always middle click

> I don’t know what the problem is here.
> 
> Ref: https://wayland.freedesktop.org/libinput/doc/latest/clickpad-softbuttons.html#clickfinger
> 
> How many fingers does your device support?
> 
> Could you try printf()ing libinput_device_config_tap_get_finger_count(libinput_dev) … in seat.c around line 89

I think the output was misread: clickfinger is NOT enabled: 
>  Click methods: *button-areas clickfinger

It has "button-areas" enabled. I would like to switch to "clickfinger", however, I don't see an example in https://github.com/labwc/labwc/blob/master/docs/rc.xml.all for how one would do that.

The "button-areas" functionality means that depending, on whether one clicks on the left, middle or right of the trackpad, it will do the corresponding click. 

my setup:
```xml
        <libinput><device category="SynPS/2 Synaptics TouchPad">
          <naturalScroll>yes</naturalScroll>
          <disableWhileTyping>yes</disableWhileTyping>
          <tap>no</tap>
        </device></libinput>
```
```
Device:           SynPS/2 Synaptics TouchPad
Kernel:           /dev/input/event7
Group:            7
Seat:             seat0, default
Size:             70x50mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    *button-areas clickfinger
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```

**Comment by datMaffin** [comment]
> I don’t know what the problem is here.
> 
> Ref: https://wayland.freedesktop.org/libinput/doc/latest/clickpad-softbuttons.html#clickfinger
> 
> How many fingers does your device support?
> 
> Could you try printf()ing libinput_device_config_tap_get_finger_count(libinput_dev) … in seat.c around line 89

I added the printf, and the output is
```
3
0
```

Don't know what it means. (I don't have tap enabled, so not sure why are there are always exactly two printouts)
