### ISSUE TITLE
Alt-tabbing fullscreen games results in black screen

### ISSUE THREAD

**Issue by Ph42oN** [labwc/labwc#958]
Alt-tabbing from game that is running in fullscreen, if it gets minimized, going back always gives black screen. It looks like getting minimized causes this, as some games don't get auto-minimized and this issue doesn't happen. Sounds keep playing.

To confirm its not something with my pc i tried on sway, when game is not focused it gets black screen, but when it gets focus its back to normal.

Happens on my laptop and desktop, both running amdgpu.

**Comment by johanmalm** [comment]
Not sure what's going on here.
IIRC sway doesn't handle minimize in the way a stacking window manager does. Try running `nautilus` and click the minimize button and you'll see that nothing happens. 
In `labwc` we actually `unmap` the window on `minimize`.
I don't know what the answer is here, but it might be worth exploring window-rules around `activate`.
What game is it?
Most of the `labwc` core devs run pretty modest hardware, so debugging with steam games can be hard for us :smile:

**Comment by Ph42oN** [comment]
I know that minimize doesn't work same in sway but the point was that it too gives black screen but when its focused again it goes back to normal.

The issue happens in most games running in wine/proton, and it might be only wine/proton but wide range of games have this problem, i think it would be easier to list games where it doesn't happen than games where it does. Tested few native games, doesnt seem to be happening, cs source did get minimized but when i switch back to it, its in window (can restore with togglefullscreen keybind). I think its pointing that something is not done correctly when switching back to game.

I think this issue was here when i first tried labwc, i just used borderless mostly as that prevents it from happening.

**Comment by johanmalm** [comment]
> I know that minimize doesn't work same in sway but the point was that it too gives black screen but when its focused again it goes back to normal.

Got it.

I can't run those games to reproduce, but if you're able to test PR #960 that would be awesome.

If that doesn't work, if you could insert a `printf()` where we re-add the commit-hander on map (https://github.com/labwc/labwc/blob/945928a8f69edd99647de81482bf4715aa2384d6/src/xwayland.c#L488) and then check that this happens when you alt-tab to unminimize, that would be great.

**Comment by Ph42oN** [comment]
I compiled labwc with that, and the issue is gone. Also checked cs source and now it stays in fullscreen when switching back as it should.

Thanks

**Comment by Consolatis** [comment]
Thank you for reporting and testing.
And obviously thanks @johanmalm for fixing it :)
