### ISSUE TITLE
Support sub-menus

### ISSUE THREAD

**Issue by 01micko** [labwc/labwc#96]
Is this a possibility?

I couldn't see a reference in the scope but it should be possible and maybe something for the future, in the name of user friendliness.

I already have code that generates a `menu.xml` file.

It is based on work by @jamesbond3142 - see [fatdog/openbox-xdgmenu](https://distro.ibiblio.org/fatdog/source/800/openbox-xdgmenu-0.4.tar.bz2) depending on [fatdog/gnome-menus-2](https://distro.ibiblio.org/fatdog/source/800/gnome-menus-2.30.5.tar.bz2)

I just stripped out the icon code, hence removing gtk dependency and  formatted `xml` a bit better

Code zipped file below;
[openbox-xdgmenu.zip](https://github.com/johanmalm/labwc/files/7402493/openbox-xdgmenu.zip)

Used with `-p` option categories are ignored and a monolithic menu is built and works in labwc, but of course goes off screen if many GUI packages are installed.

![20211023_18h16m02s_grim](https://user-images.githubusercontent.com/1019119/138548668-b8bbf5b0-b94c-4632-92b4-ae0db4d40eae.png)

Similar could be written in pure shell but would be a little slower, but exactly the same end result could be achieved.

Example output with categories enabled:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<openbox_menu>
<menu id="xdg-menu-Accessories" label="Accessories">
  <item label="Graphical Disk Map">
	<action name="Execute"><command>gdmap</command></action>
  </item>
  <item label="PeasyDiff compare two files/folders">
	<action name="Execute"><command>peasydiff</command></action>
  </item>
  <item label="PupMenu">
	<action name="Execute"><command>PupMenu</command></action>
  </item>
  <item label="PupMenuEdit">
	<action name="Execute"><command>PupMenuEdit</command></action>
  </item>
  <item label="UExtract">
	<action name="Execute"><command>/usr/local/apps/UExtract/AppRun</command></action>
  </item>
  <item label="X Virtual Keyboard">
	<action name="Execute"><command>x-keyboard</command></action>
  </item>
  <item label="Xarchiver">
	<action name="Execute"><command>xarchiver   </command></action>
  </item>
  <item label="pRun">
	<action name="Execute"><command>prun</command></action>
  </item>
  <item label="pupMd5sum Graphical Checksum">
	<action name="Execute"><command>pupmd5sum.sh</command></action>
  </item>
</menu>
<menu id="xdg-menu-Games" label="Games">
  <item label="Pipe Panic">
	<action name="Execute"><command>pipepanic</command></action>
  </item>
</menu>
<menu id="xdg-menu-Graphics" label="Graphics">
  <item label="GNU Image Manipulation Program">
	<action name="Execute"><command>gimp-2.10</command></action>
  </item>
</menu>
<menu id="xdg-menu-Internet" label="Internet">
  <item label="Firewall Setup">
	<action name="Execute"><command>firewall_ng</command></action>
  </item>
  <item label="PcurlFtp file sharing">
	<action name="Execute"><command>rox -d /root/File-Sharing</command></action>
  </item>
  <item label="PeasyPort LAN scanner">
	<action name="Execute"><command>peasyport</command></action>
  </item>
  <item label="PureFTPd">
	<action name="Execute"><command>run-pureftpd</command></action>
  </item>
  <item label="YASSM Samba share mounter">
	<action name="Execute"><command>yassm</command></action>
  </item>
</menu>
<menu id="xdg-menu-Office" label="Office">
  <item label="AbiWord">
	<action name="Execute"><command>abiword</command></action>
  </item>
  <item label="Gnumeric">
	<action name="Execute"><command>gnumeric</command></action>
  </item>
</menu>
<!-- snipped here for brevity -->
</openbox_menu>
```

Anyway, supporting the `Categories` would be the key.

What would be the simplest and of course cleanest way to go about adding sub-menus?

Possibilities that I see:
- use the output as above - but that would involve pipe menus - probably a lot of work
- separate each sub-menu into it's own menu, and having the `root` menu execute each sub-menu
- is it already possible?
- something else?

Thanks for reading.

**Comment by johanmalm** [comment]
I'm working on this now.

TODO:

1. [ ] Parsing sub-menus in menu.xml
2. [ ] Render sub-menus and handle cursor movements and button presses
2. [ ] Handle some basic keys such as arrows and escape
3. [ ] Fit within output geometry
4. [ ] Support hover-delay (i.e. delay before showing sub-menu when hovering over sub-menu item)

**Comment by 01micko** [comment]
Thanks for looking at this. IMHO this will allow `labwc` to be more user friendly and and a good step to bringing it out of the 'lab'.

**Comment by johanmalm** [comment]
I like "bringing out the `lab`". Very puppy-like.

I've had a quick go. Still not working very well though :smile:

![20211101_21h01m34s_grim](https://user-images.githubusercontent.com/6955353/139741864-2bc42a76-4963-4f8f-a82f-facfe5fdd81d.png)

**Comment by 01micko** [comment]
> I like "bringing out the `lab`". Very puppy-like.
> 

Was early morning when I posted and that thought hadn't occurred to me. It gives me a good idea for a wallpaper at least when I can get a `labwc` based puppy ready for testing. :smile:

**Comment by 01micko** [comment]
In Puppy, JWM uses dynamic menus. I certainly don't expect `labwc` to support this so I've raised an issue on gtkdialog to support [`gtk-layer-shell`](https://github.com/puppylinux-woof-CE/gtkdialog/issues/101).

**Comment by johanmalm** [comment]
> In Puppy, JWM uses dynamic menus. I certainly don't expect `labwc` to support this so I've raised an issue on gtkdialog to support [`gtk-layer-shell`](https://github.com/puppylinux-woof-CE/gtkdialog/issues/101).

What is a dynamic menu? It is like a pipe-menu in openbox?

**Comment by 01micko** [comment]
> What is a dynamic menu? It is like a pipe-menu in openbox?

Yes, similar

**Comment by johanmalm** [comment]
First attempt pushed. It'd doesn't supported nested (inline) definitions yet.

**Comment by 01micko** [comment]
> First attempt pushed. It'd doesn't supported nested (inline) definitions yet.

Working great for me with very minor issue (gap - see screencap)

```xml
<openbox_menu>
<menu id="submenu0" label="Net">
  <item label="Browser">
    <action name="Execute"><command>$BROWSER</command></action>
  </item>
  <item label="Torrent">
    <action name="Execute"><command>transmission-gtk</command></action>
  </item>
</menu>
<menu id="submenu1" label="Doc">
  <item label="Word Processor">
    <action name="Execute"><command>abiword</command></action>
  </item>
  <item label="Spread Sheet">
    <action name="Execute"><command>gnumeric</command></action>
  </item>
  <item label="Text Editor">
    <action name="Execute"><command>geany</command></action>
  </item>
  <item label="PDF Viewer">
    <action name="Execute"><command>evince</command></action>
  </item>
</menu>
<menu id="submenu2" label="Graphic">
  <item label="Image Viewer">
    <action name="Execute"><command>imgview</command></action>
  </item>
  <item label="Image Editor">
    <action name="Execute"><command>mtpaint</command></action>
  </item>
</menu>
<menu id="submenu3" label="Utility">
  <item label="Terminal">
    <action name="Execute"><command>lxterminal</command></action>
  </item>
  <item label="Processes">
    <action name="Execute"><command>lxtask</command></action>
  </item>
</menu>

<menu id="root-menu" label="">
  <menu id="submenu0" />
  <menu id="submenu1" />
  <menu id="submenu2" />
  <menu id="submenu3" />
  <item label="____________">
  </item>
  <item label="Exit">
    <action name="Exit"></action>
  </item>
  <item label="Reconfigure">
    <action name="Reconfigure"></action>
  </item>
</menu>
</openbox_menu>

```
![labwc-sub](https://user-images.githubusercontent.com/1019119/140036980-2220544e-906c-42df-aaf6-2117fd39f7e0.png)

**Comment by johanmalm** [comment]
That’s good.

Regarding the gap, sorry I just hard-coded a value of 10 with a TODO note.
I will implement theme option menu.overlap.x

http://openbox.org/wiki/Help:Themes#menu.overlap.x

**Comment by 01micko** [comment]
I re-coded the menu generator and use a template script to build the menu. Works great!

See screen recording:

https://user-images.githubusercontent.com/1019119/140593510-4eedd541-3b40-4ebb-82fb-f5797c386101.mp4

**Comment by 01micko** [comment]
The code for `labc-xdgmenu`

```c
/**
 * labwc-xdgmenu
 * 
 * This command line application generates an OpenBox menu XML segment based on
 * an Xdg menu structure. Adapted for labwc <https://github.com/johanmalm/labwc>
 * 
 * Usage: labwc-xdgmenu <Xdg menu file>
 * 
 * Copyright (C) Nathan Fisher <nfisher@grafpup.com>
 * Copyright (C) 2008 Siegfried-A. Gevatter <rainct@ubuntu.com>
 * Copyright (C) 2011 Kévin Joly <joly.kevin25@gmail.com>
 * Copyright (C) 2016 James Budiono <jamesbond3142@gmail.com>
 * Copyright (C) 2021 Michael Amadio <01micko@gmail.com>
 * Originally based upon code by Raul Suarez <rarsa@yahoo.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Dependencies:
 *   gnome-menus
 *   glib
 */

#include <string.h>
#include <glib.h>
#include <glib/gprintf.h>
#include <gnome-menus/gmenu-tree.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

/*=============================================================================
 * Declarations
 */
static void show_help();
static void process_directory(GMenuTreeDirectory *directory);
static void process_entry(GMenuTreeEntry *entry);

/*=============================================================================
 * Main Function
 */
int main (int argc, char **argv)
{
    if ((argc < 2)
      || (strcmp (argv[1], "-h") == 0)
      || (strcmp (argv[1], "-help") == 0)
      || (strcmp (argv[1], "--help") == 0))
  {
    show_help();
    return (1);
  }
    
    GMenuTree *menuTree = gmenu_tree_lookup (argv[1],  GMENU_TREE_FLAGS_NONE );
    
    GMenuTreeDirectory *rootDirectory = gmenu_tree_get_root_directory(menuTree);
        
    process_directory(rootDirectory);
    
    gmenu_tree_item_unref (rootDirectory);   

    return 0;
}

/*=============================================================================
 * Shows usage parameters
 */
void show_help()
{
    g_printf ("Creates a labwc menu from an Xdg menu structure.\n");
    g_printf ("\n");
    g_printf ("Usage:\n");
    g_printf ("  labwc-xdgmenu <Xdg menu file>\n");
    g_printf ("\n");
    g_printf ("For example:\n");
    g_printf ("  labwc-xdgmenu \"/etc/xdg/menus/applications.menu\"\n\n");
}

/*=============================================================================
 * This function processes a directory entry and all it's child nodes
 */
void process_directory(GMenuTreeDirectory *directory)
{
   g_printf(
		  "<menu id=\"xdg-menu-%s\" label=\"%s\">\n",
		  gmenu_tree_directory_get_name(directory),
		  gmenu_tree_directory_get_name(directory));

    GMenuTreeItemType entryType;
    GSList *entryList = gmenu_tree_directory_get_contents (directory);
    GSList *l;
    
     for (l = entryList; l; l = l->next)
    {
        GMenuTreeItem *item = l->data;
        
        entryType = gmenu_tree_item_get_type (GMENU_TREE_ITEM(item));
        
        switch (entryType)
        {
            case GMENU_TREE_ITEM_DIRECTORY:
                break;
            case GMENU_TREE_ITEM_ENTRY:
                process_entry(GMENU_TREE_ENTRY(item));
                break;
        }
        
        gmenu_tree_item_unref (item);
    }
    
    g_printf("</menu>\n");
    g_slist_free (entryList);
}

/*=============================================================================
 * This function adds an application entry
 */
void process_entry(GMenuTreeEntry *entry)
{
    char *name = g_strdup (gmenu_tree_entry_get_name(entry));
    char *exec = g_strdup (gmenu_tree_entry_get_exec(entry));
    int i;
    
    for (i = 0; i < strlen(exec) - 1; i++) {
        if (exec[i] == '%')
        {
            switch (exec[i+1]) {
                case 'f': case 'F':
                case 'u': case 'U':
                case 'd': case 'D':
                case 'n': case 'N':
                case 'i': case 'c': case 'k': case 'v': case 'm':
                    exec[i] = ' ';
                    exec[i+1] = ' ';
                    i++;
                    break;
            }
        }
    }

    g_printf("  <item label=\"%s\">\n", g_strjoinv("&amp;", g_strsplit(name,"&",0))),
    g_printf("    <action name=\"Execute\"><command>%s</command></action>\n", exec),
    g_printf("  </item>\n");
    
    g_free(name);
    g_free(exec);
}

/*=============================================================================
 */
```

It puts each category iterated over on STDOUT . I might event start a github repo for this.

**Comment by johanmalm** [comment]
Excellent.
Video looks great.
Just an idea - maybe we ought to create a labwc organization (github.com/labwc) and move the whole repo there.
Then we could add separate repos for
- labwc-gnome-menus (yours)
- labwc-gnome-menus-3.0 (just had a quick play and reckon it would be fairly quick to do - with gio, etc)
- labwc-lxmenu (I have the structure for this in jgmenu/contrib)
- labwc-garcon (for xfce users)

**Comment by 01micko** [comment]
A separate `labwc` organization sounds like a good idea. It *could* -
- attract more interest
- have it's own github.io website
-  have useful forks of related projects

**Comment by johanmalm** [comment]
Yeah. I’ve just created the org.

**Comment by 01micko** [comment]
> Yeah. I’ve just created the org.

A simple logo

![labwc](https://user-images.githubusercontent.com/1019119/140625568-75c9cf5c-fd5c-4740-a7ac-6ecf443f04be.png)

---
`labwc.svg`
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 120 160">
  <!--labwc logo-->
  <path d="m 82.5,32 a 3 3 0 0 1 -3,3 l -30,0 -30,-20 0,60 30,-20 30,0 a 3 3 0 0 1 3,3" style="fill:none;stroke:#000000;stroke-width:5;stroke-linejoin:round" />
  <path d="m 49.5,52.5 -30,0 0,20 z" style="fill:#000000" />
  <path d="m 75,80 0,60 a 10,10 0 0 0 20,0 l 0,-60" style="fill:none;stroke:#000000;stroke-width:5" />
  <path d="m 75,120 0,20 a 10,10 0 0 0 20,0 l 0,-20 z" style="fill:#000000;" />
  <path d="m 85,58 a 10 10 0 0 1 -3,7 a 5 5 1 1 0 6,0 a 10 10 0 0 1 -3,-7" style="fill:#000000;stroke-linejoin:round"  />
</svg>
```

**Comment by johanmalm** [comment]
Any copyright on it. Did you make it?

**Comment by 01micko** [comment]
> Any copyright on it. Did you make it?

Yes I did. I'll add a comment in the xml... later.

**Comment by 01micko** [comment]
I updated comment, yes, I live in Labrador :rofl:

**Comment by 01micko** [comment]
I updated comment, yes, I live in Labrador :rofl: 

EDIT: forgot to save, now updated.

**Comment by johanmalm** [comment]
@01micko 
Nested menus work now :) And I've added support for menu.overlap.{x,y} which solves the gap issue.

**Comment by 01micko** [comment]
> @01micko Nested menus work now :) And I've added support for menu.overlap.{x,y} which solves the gap issue.

Excellent, thanks :smile: . Just built and running now from 3541616

**Comment by johanmalm** [comment]
@01micko 
I've written a little hack for libgnome-menu-3.0 and gio.
https://github.com/labwc/labwc-menu-gnome3

**Comment by dimkr** [comment]
> @01micko I've written a little hack for libgnome-menu-3.0 and gio. https://github.com/labwc/labwc-menu-gnome3

Puppy's menu generator with JWM this patch (https://github.com/puppylinux-woof-CE/woof-CE/blob/testing/woof-code/rootfs-petbuilds/xdg-puppy-jwm/2089.patch), which:
1. Adds tooltips
2. Removes `%F` and friends -
```
$ grep ^Exec /usr/share/applications/geany.desktop 
Exec=geany %F
```
3. Runs applications with `Terminal=true` inside a terminal emulator, and wraps the command-line with `sh -c` (https://github.com/puppylinux-woof-CE/woof-CE/issues/2542, https://github.com/puppylinux-woof-CE/woof-CE/issues/2561)

@johanmalm I'll open a PR to https://github.com/labwc/labwc-menu-gnome3, with 2 and 3, sometime soon.

**Comment by johanmalm** [comment]
> I'm working on this now.
> 
> TODO:
> 
>     1. [x]  Parsing sub-menus in menu.xml
> 
>     2. [x]  Render sub-menus and handle cursor movements and button presses
> 
>     3. [ ]  Handle some basic keys such as arrows and escape
> 
>     4. [ ]  Fit within output geometry
> 
>     5. [ ]  Support hover-delay (i.e. delay before showing sub-menu when hovering over sub-menu item)
> 
>     6. [x]  Support nested menus
> 
>     7. [ ]  Support `<separator>`

I've added support for `<separator>`. Still lots to do with menus :smile:


https://user-images.githubusercontent.com/6955353/141661073-7eb24d83-ff3d-4f3f-95fc-ec3a3482f45f.mp4

**Comment by 01micko** [comment]
Looking good.

I want to see if I can add icon font support to the menu generator :laughing: 
![20211114_08h42m02s_grim](https://user-images.githubusercontent.com/1019119/141661219-38dae104-ccb8-45e4-974b-d82b34387951.png)

**Comment by johanmalm** [comment]
I like the look of that. Keeps it simple and avoids all the color clashes that comes with PNG/SVG icons.

Talking of icons - for the longer term most advanced layer-shell menu (with pipemenus, icons, etc, I think this library will be great https://gitlab.freedesktop.org/ddevault/fdicons

**Comment by Arnaudv6** [comment]
does implementation allow to fix drawn out-of screen menus?
(in master when right-clicking the desktop near screen right-edge, menu will draw off-screen)

**Comment by Arnaudv6** [comment]
sorry, please ignore, had not seen your 4th point

**Comment by johanmalm** [comment]
Will close this now as sub-menus have been implemented.
Will track other menu enhancements here https://github.com/labwc/labwc-acceptance-criteria/blob/main/TODO.md
Have written a `separator` implementation, just need to refactoring some output.c code before committing.
