### ISSUE TITLE
menu.xml and "CDATA"

### ISSUE THREAD

**Issue by ncmprhnsbl** [labwc/labwc#972]
i've noticed that some menu generators (eg. obmenu-generator and obamenu.py) output their xml execute sections enclosed in \<![CDATA[foo]]> tags, which it appears labwc doesn't support?
could be out of scope and not a huge deal with labwc/wayland specific generators in the works.

also, as a work around it's fairly easy to hack those two examples being just scripts and remove the CDATA parts.

**Comment by johanmalm** [comment]
Hi. Thanks for raising.
We need to use `xmlNodeGetContent(node)` instead of just `node->content` for those `<command>` tags.
It's not super-trivial, but I'll have a go later at a patch for discussion.

**Comment by ncmprhnsbl** [comment]
cool,  initial testing of above the commit seems to be partially working, in that entries on the main menu work, but not on submenus.
caveat: i'm just replacing menu.c in labwc/labwc git head

**Comment by johanmalm** [comment]
Submenus work for me (with obmenu-generator)

Pipemenus are not supported if that’s what you mean (dynamic menus)

Could you post your menu.xml

**Comment by johanmalm** [comment]
Sorry - I get it now. My bad. I'll sort tonight.

**Comment by johanmalm** [comment]
Okay. All working now.

Would appreciate another test drive (...because my testing skills are evidently not what they ought to be :monkey: )

**Comment by ncmprhnsbl** [comment]
:) passes testing here, all levels of submenu working for me.
