### ISSUE TITLE
Add support for `ext_idle_notifier_v1` as swayidle removed support for `org_kde_kwin_idle`

### ISSUE THREAD

**Issue by CaptainBloodz** [labwc/labwc#980]
user@amd64 ~ $ labwc -v
labwc 0.6.3-57-ge06a8cf

user@amd64 ~ $ swayidle -d
2023-07-08 15:35:47 - [Line 708] Register idle timeout at 600000 ms
2023-07-08 15:35:47 - [Line 709] Setup idle
2023-07-08 15:35:47 - [Line 671] Command: grim  /tmp/screen_locked.png && convert /tmp/screen_locked.png -scale 5% -scale 2000% /tmp/screen_locked.png && swaylock -f -i /tmp/screen_locked.png
2023-07-08 15:35:47 - [Line 1041] Loaded config at /home/luc/.config/swayidle/config
2023-07-08 15:35:47 - [Line 1074] Compositor doesn't support idle protocol

swayidle arguments launch fine from foot terminal.

Working fine in sway.

What can I be missing?

**Comment by Consolatis** [comment]
Thanks for reporting this.

There are two protocols for idle notifications. Maybe swayidle switched to the `ext-` variant and dropped support for the `kde-`  variant. Labwc only supports the `kde-` one at the moment.

Just checked wlroots 0.16 and it provides support for both so we should simply add it to labwc as well.
As a short term measure it might be enough to use an older version of swayidle (or just revert https://github.com/swaywm/swayidle/commit/61d653fb7a752910f71efb3e7d08d75b266cf3ea).

See also: https://github.com/swaywm/swayidle/pull/137

**Comment by CaptainBloodz** [comment]
> Thanks for reporting this.
> 
> There are two protocols for idle notifications. Maybe swayidle switched to the `ext-` variant and dropped support for the `kde-` variant. Labwc only supports the `kde-` one at the moment.
> 
> Just checked wlroots 0.16 and it provides support for both so we should simply add it to labwc as well. As a short term measure it might be enough to use an older version of swayidle (or just revert [swaywm/swayidle@61d653f](https://github.com/swaywm/swayidle/commit/61d653fb7a752910f71efb3e7d08d75b266cf3ea)).

Previously running git-master,, switching back to  1.8.0 (2022-12-04) fixed the error indeed.

**Comment by CaptainBloodz** [comment]
> or just revert [swaywm/swayidle@61d653f](https://github.com/swaywm/swayidle/commit/61d653fb7a752910f71efb3e7d08d75b266cf3ea).
 Seems fine too here.

**Comment by Consolatis** [comment]
If you want a third option you could also test #981 and git master of swayidle if you feel like it.

**Comment by stefonarch** [comment]
Just a note: It looks like `kidletime` is working fine under wayland -  `lxqt-powermanagement` settings are working, including inhibit on fullscreen (and excluding screenlocking - but that's another issue).

**Comment by CaptainBloodz** [comment]
> If you want a third option you could also test #981 and git master of swayidle if you feel like it.
Fine indeed here too.
