### ISSUE TITLE
Top left and top right borders render incorrectly.

### ISSUE THREAD

**Issue by burein-ita** [labwc/labwc#988]
Using 6b83db34afca59686d36a458b527b71355680d48
Arch-Linux

Setting `cornerRadius` to `0` causes the top left and to right borders to render incorrectly.
It is more noticeable if the border thickness is set to some stupid value.

![wack](https://github.com/labwc/labwc/assets/131406764/f3fa6523-5b2b-448e-a308-d3a51ab6ff02)

Top picture border is set to 1px.
Bottom one is set to 25px.

**Comment by Consolatis** [comment]
Thanks for bringing this up. It also looks very wrong at other `cornerRadius` values and a 25px border width.
Something is definitely off here!

**Comment by Consolatis** [comment]
Should be fixed by
- #990

Thanks again for bringing this up.
