### ISSUE TITLE
libreoffice on labwc: Error reading events from display: Invalid argument

### ISSUE THREAD

**Issue by jonleivent** [labwc/labwc#989]
On Debian 12, running labwc 0.6.4.  Trying to start up libreoffice, I get the error:
`Gdk-Message: 19:20:01.316: Error reading events from display: Invalid argument`
I can't find anything online about this error, and I can see that others have successfully run libreoffice on labwc.  So this is probably something about my setup, but I don't know what.  Can anyone offer any clues?

**Comment by jonleivent** [comment]
Nevermind!  It was something about the apparmor profiles that Debian includes with libreoffice.  Probably, those profiles only allow connections to X, not wayland.  I'll investigate - but libreoffice works on labwc if I disable those profiles.

**Comment by Consolatis** [comment]
`Invalid argument` indeed sounds like some apparmor / SELinux shenanigans.
Thanks for stating your solution.

**Comment by jonleivent** [comment]
Note that I would not have tripped over this if I built labwc with
xwayland support.  I think the apparmor issue is that the
usr.lib.libreoffice.program.oosplash apparmor profile does not include
the apparmor wayland abstraction.  Probably should be reported to
someone else - maybe Debian (which included the apparmor profile in the
libreoffice package)? Maybe Ubuntu (which maintains apparmor)? Maybe
libreoffice? Is there a Wayland advocacy group that can put more weight
behind this than could a single user?

**Comment by Consolatis** [comment]
> Note that I would not have tripped over this if I built labwc with xwayland support.

Why is that? Because libre office would default to use X11 instead of wayland? Otherwise the apparmor profile would likely still intervene.

> Probably should be reported to someone else

If the profile is coming from Debian, that sounds like the best place to fill a bug.
