### ISSUE TITLE
Certain key combinations aren't recognized by labwc

### ISSUE THREAD

**Issue by burein-ita** [labwc/labwc#992]
Using 0eab7e082c4f37f6c4472d609ce9351a5d5d6bd0
Arch-Linux

The relevant part of rc.xml:
```
    <!-- Switch to Desktop -->
    <keybind key="W-Tab">
      <action name="GoToDesktop" to="right" wrap="yes" />
    </keybind>
    <keybind key="W-S-Tab">
      <action name="GoToDesktop" to="left" wrap="yes" />
    </keybind>
    <!-- Send to Desktop -->
    <keybind key="W-S-1">
      <action name="SendToDesktop" to="1" follow="no" wrap="no" />
    </keybind>
    <keybind key="W-S-2">
      <action name="SendToDesktop" to="2" follow="no" wrap="no" />
    </keybind>
    <keybind key="W-S-3">
      <action name="SendToDesktop" to="3" follow="no" wrap="no" />
    </keybind>
    <keybind key="W-S-4">
      <action name="SendToDesktop" to="4" follow="no" wrap="no" />
    </keybind>

```
`W-Tab` works as expected.
`W-S-Tab and W-S-1→4` are not recognized by labwc.

Running `labwc -d` doesn't return any significant logs.
Tested different keyboards. All had the same behavior.
This key combinations work on other compositors. Tested sway and Hyprland.

**Comment by stefonarch** [comment]
```
I don't know but can super not be combined with other modifiers maybe? The first works, the second not:

    <keybind key="C-A-1">
      <action name="GoToDesktop" to="1"/>
    </keybind>
        <keybind key="S-W-1">
      <action name="GoToDesktop" to="1"/>
    </keybind>
```

**Comment by burein-ita** [comment]
> I don't know but can super not be combined with other modifiers maybe? The first works, the second not:

Yeah.

`W-A-1` and `W-A-Tab` works. I'm using these as a workaround for now.
`W-S-!` doesn't.

I failed to mention that some combinations using `W-S` do work.
```
    <!-- Pseudo Tiling -->
    <keybind key="W-S-Left">
      <action name="SnapToEdge" direction="left" />
    </keybind>
    <keybind key="W-S-Right">
      <action name="SnapToEdge" direction="right" />
    </keybind>
    <keybind key="W-S-Up">
      <action name="SnapToEdge" direction="up" />
    </keybind>
    <keybind key="W-S-Down">
      <action name="SnapToEdge" direction="down" />
    </keybind>
    <keybind key="W-S-m">
      <action name="SnapToEdge" direction="center" />
    </keybind>
```
All of the above work as intended.

**Comment by Consolatis** [comment]
Still an unfixed issue:

For `W-S-Tab`: `W-S-ISO_Left_Tab`
See
- #163

For `W-S-Number`:
`W-S-exclam` or `W-S-0x21`, both depend on the keyboard layout.
You can use something like `python3 -c 'print("W-S-0x%0x" % ord("!"))'` for translation. See
- #365

**Comment by Consolatis** [comment]
Should be fixed by
- #997

Note: the workaround keybinds will have preference over raw ones, e.g. `W-S-0x21` would get used if defined and `W-S-1` would not be used at all. Thus suggesting to replace all workaround keybinds with proper ones. Feel free to open a new issue if there are any further issues with the keybinds.
