### ISSUE TITLE
[Question] Tilde key has to be pressed twice

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#993]
Hi there,

I have recently updated to Debian 12, and I have built latest stable Labwc on top of a minimal image.

Thing is, I am using an spanish keyboard, but since I upgraded to Debian 12 and latest stable Labwc, I have to press the tilde key twice for it to be actually printed.

For setting up the Labwc keymap, all I have always done is create **.config/labwc/enviroment** with this content:

`XKB_DEFAULT_LAYOUT=es`

It worked fine until now.

My guess is that it has something to do with dead keys: there must be a value I can set in `XKB_DEFAULT_VARIANT=` to fix this, but I can't even find possible values.

On the TTY, I don't have this problem: I have setup the keyboard via `dpkg-reconfigure keyboard-configuration` to a generic 105 keys, Spanish layout, "NO DEAD KEYS" variant.
...But how can I do the same for Labwc, please?

**Comment by vanfanel** [comment]
Answering myself. This is what `~/.config/labwc/environment` must have:
```

XKB_DEFAULT_LAYOUT=es
XKB_DEFAULT_VARIANT=nodeadkeys
```

So, that's all, no more press twice for tilde.

**Comment by Consolatis** [comment]
Thanks for updating this with the answer, I actually had the same issue but it didn't bother me enough to search for a fix.
I wonder if we should add this somewhere to https://labwc.github.io.

**Comment by vanfanel** [comment]
Yes, add it, please

**Comment by 01micko** [comment]
https://labwc.github.io/tips-and-tricks.html#environment-variables :grey_question:

**Comment by Consolatis** [comment]
And / or https://labwc.github.io/getting-started.html `Step 1 - Set your keyboard layout`.
